# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/UmicomActiveCSource.cmake")
function(check_source text expected label)
    umicom_potentially_active_c("${text}" _active)
    string(REGEX MATCH "gtk_drop_down_new[ \t\r\n]*\\([ \t\r\n]*G_LIST_MODEL" _bad "${_active}")
    if(expected AND NOT _bad)
        message(FATAL_ERROR "Active constructor hidden: ${label}")
    elseif(NOT expected AND _bad)
        message(FATAL_ERROR "Inactive constructor mistaken for execution: ${label}")
    endif()
endfunction()
set(_bad "gtk_drop_down_new(G_LIST_MODEL(model), NULL);")
check_source("${_bad}" TRUE direct)
check_source("#if 0\n${_bad}\n#endif\n" FALSE disabled)
check_source("#if 0\n#if FEATURE\n${_bad}\n#else\n${_bad}\n#endif\n#endif\n" FALSE nested)
check_source("#if 0\n#else\n${_bad}\n#endif\n" TRUE else)
check_source("#if 0\n#elif FEATURE\n${_bad}\n#endif\n" TRUE elif)
check_source("#ifdef FEATURE\n${_bad}\n#endif\n" TRUE unknown)
check_source("#if 1\n${_bad}\n#endif\n" TRUE one)
check_source("#if 0 || FEATURE\n${_bad}\n#endif\n" TRUE compound)
check_source("#if 0\n#endif\n${_bad}" TRUE after)
check_source("/*\n#if 0\n*/\n${_bad}" TRUE comment_directive)
check_source("/* ${_bad} */" FALSE block_comment)
check_source("// ${_bad}\n" FALSE line_comment)
check_source("const char *s = \"${_bad}\";" FALSE string)
check_source("const char *s = \"/*\\\" //\";\n${_bad}" TRUE quoted_comment)
check_source("#if 0 /* retained */\n${_bad}\n#endif\n" FALSE commented_condition)
check_source("#if FEATURE\n#if 0\n${_bad}\n#endif\n#else\n${_bad}\n#endif" TRUE unknown_else)
