# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Extract potentially executable C for source-policy checks. This is deliberately
# not a C preprocessor: unknown conditions keep every branch under inspection.
include_guard(GLOBAL)
function(umicom_potentially_active_c source output)
    # Match literals and comments together, so comment markers inside strings
    # cannot hide following code. Newlines separate tokens after removal.
    set(_non_code [=[/\*([^*]|\*+[^*/])*\*+/|"([^"\\]|\\.)*"|'([^'\\]|\\.)*']=])
    # Quoted CMake arguments decode CR/LF; bracket arguments deliberately do not.
    set(_line_comment "//[^\r\n]*")
    string(APPEND _non_code "|${_line_comment}")
    string(REGEX REPLACE "${_non_code}" "\n" _remaining "${source}")
    string(REPLACE "\r\n" "\n" _remaining "${_remaining}")
    set(_parents)
    set(_disabled 0)
    set(_active "")
    while(NOT _remaining STREQUAL "")
        string(FIND "${_remaining}" "\n" _end)
        if(_end LESS 0)
            set(_line "${_remaining}")
            set(_remaining "")
        else()
            string(SUBSTRING "${_remaining}" 0 ${_end} _line)
            math(EXPR _next "${_end} + 1")
            string(SUBSTRING "${_remaining}" ${_next} -1 _remaining)
        endif()
        if(_line MATCHES "^[ \t]*#[ \t]*(if|ifdef|ifndef)([ \t]|$)")
            list(APPEND _parents "${_disabled}")
            # Only literal #if 0 is proven inactive. Do not evaluate macros.
            if(_line MATCHES "^[ \t]*#[ \t]*if[ \t]+0[ \t]*$")
                set(_disabled 1)
            endif()
        elseif(_line MATCHES "^[ \t]*#[ \t]*(else|elif)([ \t]|$)")
            list(LENGTH _parents _depth)
            if(_depth GREATER 0)
                list(GET _parents -1 _disabled)
            else()
                set(_disabled 0)
            endif()
        elseif(_line MATCHES "^[ \t]*#[ \t]*endif([ \t]|$)")
            list(LENGTH _parents _depth)
            if(_depth GREATER 0)
                list(POP_BACK _parents _disabled)
            else()
                set(_disabled 0)
            endif()
        elseif(NOT _disabled)
            string(APPEND _active "${_line}\n")
        endif()
    endwhile()
    set(${output} "${_active}" PARENT_SCOPE)
endfunction()
