#-----------------------------------------------------------------------------
# Umicom Framework
# File: docs/site/check_site.cmake
# PURPOSE: Check assembled public pages, real example content and source inputs.
# AUTHOR AND ORGANISATION: Sammy Hegab, Umicom Foundation
# LICENCE: MIT
#-----------------------------------------------------------------------------
cmake_minimum_required(VERSION 3.24)
function(RequireText text needle)
    string(FIND "${text}" "${needle}" _position)
    if(_position LESS 0)
        message(FATAL_ERROR "Required content missing: ${needle}")
    endif()
endfunction()
if(CASE STREQUAL "pages")
    foreach(_path IN ITEMS index.html getting-started.html products.html downloads.html
            publishing.html contributing.html source-map.html wiki/index.html
            wiki/working-copies.html wiki/compiler-diagnostics.html wiki/components.html
            studio/index.html trader/index.html desktop/index.html bank/index.html
            studio/EDITING_FILES.html studio/READING_BUILD_ERRORS.html build-and-publish.html
            assets/site.css assets/site.js reference/html/index.html)
        if(NOT EXISTS "${SITE}/${_path}")
            message(FATAL_ERROR "Missing assembled file: ${_path}")
        endif()
        file(SIZE "${SITE}/${_path}" _size)
        if(_size EQUAL 0)
            message(FATAL_ERROR "Empty assembled file: ${_path}")
        endif()
    endforeach()
elseif(CASE STREQUAL "catalogue")
    file(READ "${SITE}/source-map.html" _map)
    string(REGEX MATCHALL "<tr data-source-row>" _rows "${_map}")
    list(LENGTH _rows _count)
    if(NOT _count EQUAL EXPECTED_HEADERS)
        message(FATAL_ERROR "Header inventory mismatch: ${_count} versus ${EXPECTED_HEADERS}")
    endif()
    RequireText("${_map}" "include/umicom/build/parser.h")
    RequireText("${_map}" "include/umicom/document/coordinator.h")
    RequireText("${_map}" "include/umicom/ui/components/component.h")
elseif(CASE STREQUAL "examples")
    foreach(_pair IN ITEMS "build_diagnostics/main.c|compiler-diagnostics.html"
            "editor_workflow/complete_document.c|working-copies.html")
        string(REPLACE "|" ";" _parts "${_pair}")
        list(GET _parts 0 _source)
        list(GET _parts 1 _page)
        file(READ "${FRAMEWORK}/examples/${_source}" _code)
        string(REPLACE "&" "&amp;" _code "${_code}")
        string(REPLACE "<" "&lt;" _code "${_code}")
        string(REPLACE ">" "&gt;" _code "${_code}")
        string(REPLACE "\"" "&quot;" _code "${_code}")
        file(READ "${SITE}/wiki/${_page}" _html)
        RequireText("${_html}" "${_code}")
    endforeach()
elseif(CASE STREQUAL "products")
    execute_process(COMMAND "${GIT_EXECUTABLE}" config --file "${SUITE}/.gitmodules"
        --get-regexp "^submodule\\..*\\.path$"
        RESULT_VARIABLE _status OUTPUT_VARIABLE _paths ERROR_VARIABLE _error)
    if(NOT _status EQUAL 0)
        message(FATAL_ERROR "Cannot read the registered products: ${_error}")
    endif()
    file(READ "${SITE}/products.html" _products)
    string(REPLACE "\n" ";" _lines "${_paths}")
    foreach(_line IN LISTS _lines)
        string(REGEX MATCH " applications/[A-Za-z0-9_-]+$" _path "${_line}")
        if(_path)
            string(STRIP "${_path}" _path)
            RequireText("${_products}" "<code>${_path}</code>")
        endif()
    endforeach()
elseif(CASE STREQUAL "exclusions")
    file(READ "${DOXYFILE}" _configuration)
    string(FIND "${_configuration}" "*/build/*" _bad_exclusion)
    if(NOT _bad_exclusion EQUAL -1)
        message(FATAL_ERROR "A wildcard still excludes actual build-service source.")
    endif()
    RequireText("${_configuration}" "${FRAMEWORK}/src")
    RequireText("${_configuration}" "${FRAMEWORK}/include")
    string(FIND "${_configuration}" "${FRAMEWORK}/docs\"" _whole_docs)
    if(NOT _whole_docs EQUAL -1)
        message(FATAL_ERROR "The public reference must not ingest the entire docs directory.")
    endif()
else()
    message(FATAL_ERROR "Unknown documentation test case: ${CASE}")
endif()
