/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/designer/source_generation.c
 *
 * PURPOSE:
 *   Emit visible declarative, C23 and CMake source files from designer state.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/

#include "umicom/designer/source_generation.h"

#include "umicom/declarative/serializer.h"

#include <stdio.h>
#include <string.h>

/* Provide the add static operation used by this module and its client applications. */
static UmiStatus add_static(UmiDesignerGeneratedSource *source, const char *path, const char *content)
{
    UmiDesignerGeneratedFile *file;
    UmiStatus status;
    /* Keep the operation inside its valid bounds before reading, writing or adding data. */
    if (source->file_count >= UMI_DESIGNER_MAX_GENERATED_FILES) return UMI_STATUS_CAPACITY_EXCEEDED;
    file = &source->files[source->file_count];
    status = umi_decl_copy_text(file->path, sizeof(file->path), path);
    /* Preserve the original failure result so the caller can respond to the correct cause. */
    if (status == UMI_STATUS_OK) status = umi_decl_copy_text(file->content, sizeof(file->content), content);
    /* Preserve the original failure result so the caller can respond to the correct cause. */
    if (status != UMI_STATUS_OK) return status;
    file->length = strlen(file->content);
    source->file_count += 1U;
    return UMI_STATUS_OK;
}

/*
 * Provide the designer source generation generate operation used by this module and its
 * client applications.
 */
UmiStatus umi_designer_source_generation_generate(const UmiDesignerDocument *document,
                                                      UmiDesignerGeneratedSource *out_source)
{
    UmiDesignerGeneratedFile *declarative;
    UmiDesignerDocumentSnapshot snapshot;
    UmiStatus status;
    /*
     * Protect caller-owned memory by checking that required state is available before it is
     * used.
     */
    if (document == NULL || out_source == NULL) return UMI_STATUS_INVALID_ARGUMENT;
    (void)memset(out_source, 0, sizeof(*out_source));
    declarative = &out_source->files[0];
    status = umi_decl_copy_text(declarative->path, sizeof(declarative->path), "application.umiapp");
    /* Preserve the original failure result so the caller can respond to the correct cause. */
    if (status == UMI_STATUS_OK) {
        status = umi_decl_serialize(umi_designer_document_declarative((UmiDesignerDocument *)document),
                                    declarative->content, sizeof(declarative->content), &declarative->length);
    }
    /* Preserve the original failure result so the caller can respond to the correct cause. */
    if (status != UMI_STATUS_OK) return status;
    out_source->file_count = 1U;
    status = add_static(out_source, "main.c",
        "/* Generated by Umicom Visual Application Builder v2. */\n"
        "#include <stdio.h>\n\n"
        "int main(void)\n{\n    puts(\"Load application.umiapp with the Umicom declarative runtime\");\n    return 0;\n}\n");
    /* Preserve the original failure result so the caller can respond to the correct cause. */
    if (status == UMI_STATUS_OK) status = add_static(out_source, "CMakeLists.txt",
        "cmake_minimum_required(VERSION 3.24)\n"
        "project(umicom_generated_application LANGUAGES C)\n"
        "set(CMAKE_C_STANDARD 23)\nset(CMAKE_C_STANDARD_REQUIRED ON)\n"
        "add_executable(umicom_generated_application main.c)\n");
    /* Preserve the original failure result so the caller can respond to the correct cause. */
    if (status == UMI_STATUS_OK) status = add_static(out_source, "README.md",
        "# Generated Umicom application\n\nAll generated files are visible and may be edited or reviewed.\n");
    /* Preserve the original failure result so the caller can respond to the correct cause. */
    if (status == UMI_STATUS_OK) {
        (void)umi_designer_document_snapshot(document, &snapshot);
        out_source->source_revision = snapshot.revision;
    }
    return status;
}

/*
 * Find designer source generation while leaving the underlying catalogue or model owned by
 * this module.
 */
const UmiDesignerGeneratedFile *umi_designer_source_generation_find(
    const UmiDesignerGeneratedSource *source,
    const char *path)
{
    size_t index;
    /*
     * Protect caller-owned memory by checking that required state is available before it is
     * used.
     */
    if (source == NULL || path == NULL) return NULL;
    /* Visit each bounded item once so every record receives the same rule. */
    for (index = 0U; index < source->file_count; ++index) {
        /* Keep the operation inside its valid bounds before reading, writing or adding data. */
        if (strcmp(source->files[index].path, path) == 0) return &source->files[index];
    }
    return NULL;
}
