/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/application/presentation/window_specs/desktop/learning.inc
 *
 * PURPOSE:
 *   Define the portable learning window for the desktop workspace.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
WINDOW_SPEC("org.umicom.workspace.desktop.learning", "org.umicom.window.desktop.learning",
            UMI_APPLICATION_PRESENTATION_DENSITY_COMFORTABLE,
            UMI_APPLICATION_PRESENTATION_NAVIGATION_EXPANDED,
            1600U, 1000U, 300U, 380U, 300U,
            1, 1, 1, 0,
                 960U, 640U),
