# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
cmake_minimum_required(VERSION 3.24)
if(NOT DEFINED ROOT OR NOT DEFINED DEST OR NOT DEFINED CASE)
    message(FATAL_ERROR "Surface audit fixture requires ROOT, DEST and CASE")
endif()
file(MAKE_DIRECTORY "${DEST}/applications/sample/src/console")
set(_entry src/console/main.c)
set(_expected 0)
if(CASE STREQUAL "os")
    set(_entry src/main.c)
elseif(CASE STREQUAL "missing" OR CASE STREQUAL "undeclared")
    set(_expected 1)
elseif(NOT CASE STREQUAL "portfolio" AND NOT CASE STREQUAL "alternate-declared")
    message(FATAL_ERROR "Unknown surface audit fixture")
endif()
if(NOT CASE STREQUAL "missing")
    file(WRITE "${DEST}/applications/sample/${_entry}" "int main(void) { return 0; }\n")
endif()
if(CASE STREQUAL "undeclared")
    set(_declaration "add_library(sample INTERFACE)\n")
elseif(CASE STREQUAL "alternate-declared")
    # An unused conventional file must not mask a valid direct entry point.
    file(WRITE "${DEST}/applications/sample/src/main.c" "int main(void) { return 0; }\n")
    set(_declaration "add_executable(sample src/main.c)\n")
else()
    set(_declaration "add_executable(sample ${_entry})\n")
endif()
file(WRITE "${DEST}/applications/sample/CMakeLists.txt" "${_declaration}")
execute_process(COMMAND "${CMAKE_COMMAND}"
    "-DUMICOM_APPLICATION_ROOT=${DEST}/applications"
    "-DUMICOM_SURFACE_AUDIT_OUTPUT=${DEST}/result.json"
    -P "${ROOT}/cmake/UmicomApplicationSurfaceAudit.cmake"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _output ERROR_VARIABLE _error)
if(_expected EQUAL 0 AND NOT _result STREQUAL "0")
    message(FATAL_ERROR "A declared headless entry was refused: ${_error}")
elseif(_expected EQUAL 1)
    if(_result STREQUAL "0" OR NOT _error MATCHES "Application surface audit failed")
        message(FATAL_ERROR "An incomplete application did not fail its surface audit: ${_error}")
    endif()
endif()
file(READ "${DEST}/result.json" _report)
string(JSON _count GET "${_report}" application_count)
string(JSON _ready GET "${_report}" ready_count)
math(EXPR _expected_ready "1 - ${_expected}")
if(NOT _count EQUAL 1 OR NOT _ready EQUAL _expected_ready)
    message(FATAL_ERROR "Surface audit reported incorrect application counts")
endif()
