# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
cmake_minimum_required(VERSION 3.24)
file(MAKE_DIRECTORY "${DEST}/review space-δ")
set(_folder "${DEST}/review space-δ")
set(_context "0123456789abcdef0123456789abcdef\t2f737263\t2f6275696c64\t4465627567")
set(_cmake "UMICOM-RELEASE-INVENTORY\t1\ncontext\tcmake\t${_context}\n")
set(_ctest "UMICOM-RELEASE-INVENTORY\t1\ncontext\tctest\t${_context}\n")
file(WRITE "${_folder}/configured.tsv" "${_cmake}test\t611b5b326a\t\tregistered\t\n")
file(WRITE "${_folder}/registered.tsv" "${_ctest}test\t611b5b326a\t\tregistered\t\n")
file(WRITE "${_folder}/disabled.tsv" "${_ctest}test\t611b5b326a\t\tdisabled\t\n")
file(WRITE "${_folder}/missing-command.tsv" "${_ctest}test\t611b5b326a\t\tmissing-command\t\n")
file(WRITE "${_folder}/invalid.tsv" "not an inventory")
file(WRITE "${_folder}/empty.tsv" "${_ctest}")
execute_process(COMMAND "${TOOL}" list "${_folder}/configured.tsv" RESULT_VARIABLE _result OUTPUT_VARIABLE _output)
string(ASCII 27 _escape)
string(FIND "${_output}" "${_escape}" _escape_index)
string(FIND "${_output}" "\\x1b" _safe_index)
if(NOT _result STREQUAL "0" OR NOT _escape_index EQUAL -1 OR _safe_index EQUAL -1)
    message(FATAL_ERROR "CLI Unicode file paths or console escaping failed")
endif()
foreach(_case IN ITEMS registered disabled missing-command invalid empty)
    set(_expected 1)
    if(_case STREQUAL "registered")
        set(_expected 0)
    elseif(_case STREQUAL "invalid" OR _case STREQUAL "empty")
        set(_expected 2)
    endif()
    execute_process(COMMAND "${TOOL}" compare "${_folder}/configured.tsv" "${_folder}/${_case}.tsv"
        RESULT_VARIABLE _result OUTPUT_QUIET ERROR_QUIET)
    if(NOT _result STREQUAL "${_expected}")
        message(FATAL_ERROR "CLI ${_case}: expected ${_expected}, received ${_result}")
    endif()
endforeach()
execute_process(COMMAND "${TOOL}" show "${_folder}/does-not-exist.tsv" RESULT_VARIABLE _result OUTPUT_QUIET ERROR_QUIET)
if(NOT _result STREQUAL "2")
    message(FATAL_ERROR "CLI did not report missing input")
endif()
