# Umicom Framework | Sammy Hegab | Umicom Foundation | MIT
# Fixture-only prefix; no developer runtime is read or changed by this test.
cmake_minimum_required(VERSION 3.24)
if(NOT DEFINED CASE OR NOT DEFINED FRAMEWORK OR NOT DEFINED WORK)
    message(FATAL_ERROR "CASE, FRAMEWORK and WORK are required")
endif()
include("${FRAMEWORK}/cmake/windows/SourceViewResources.cmake")
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef _nonce)
set(_prefix "${WORK}/fixture-${_nonce}/prefix with spaces")
file(MAKE_DIRECTORY "${_prefix}")
set(_schema "${_prefix}/share/gtksourceview-5/language-specs/language2.rng")
set(_dependencies "${_prefix}/bin/libgtksourceview-5-0.dll")
if(CASE STREQUAL "no-sourceview" OR CASE STREQUAL "wrong-major")
    set(_dependencies "${_prefix}/bin/libgtk-4-1.dll")
    if(CASE STREQUAL "wrong-major")
        set(_dependencies "${_prefix}/bin/libgtksourceview-6-0.dll")
    endif()
elseif(NOT CASE STREQUAL "missing-schema")
    file(MAKE_DIRECTORY "${_prefix}/share/gtksourceview-5/language-specs")
    if(CASE STREQUAL "directory-schema")
        file(MAKE_DIRECTORY "${_schema}")
    elseif(CASE STREQUAL "empty-schema")
        file(WRITE "${_schema}" "")
    else()
        file(WRITE "${_schema}" "<grammar xmlns=\"http://relaxng.org/ns/structure/1.0\"/>\n")
        if(CASE STREQUAL "optional-data")
            set(_dependencies "${_prefix}/bin/libgtk-4-1.dll")
        elseif(CASE STREQUAL "uppercase")
            set(_dependencies "${_prefix}/bin/LIBGTKSOURCEVIEW-5-0.DLL")
        elseif(CASE STREQUAL "msvc-name")
            set(_dependencies "${_prefix}/bin/gtksourceview-5.dll")
        elseif(CASE STREQUAL "schema-symlink")
            file(RENAME "${_schema}" "${_schema}.target")
            file(CREATE_LINK "${_schema}.target" "${_schema}" SYMBOLIC RESULT _link)
            if(NOT _link STREQUAL "0")
                message(FATAL_ERROR "Cannot create symbolic-link fixture: ${_link}")
            endif()
        endif()
    endif()
endif()
umicom_windows_sourceview_resources("${_prefix}" "${_dependencies}" _trees)
if(CASE STREQUAL "no-sourceview" OR CASE STREQUAL "wrong-major")
    if(NOT _trees STREQUAL "")
        message(FATAL_ERROR "Unrelated application acquired GtkSourceView data")
    endif()
elseif(NOT _trees STREQUAL "share/gtksourceview-5")
    message(FATAL_ERROR "GtkSourceView data was not selected as one owned resource tree")
endif()
