/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: include/umicom/workbench_selection_provider/workbench_selection_provider.h
 *
 * PURPOSE:
 *   Expose the complete structured model-to-selection provider platform.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
#ifndef UMICOM_WORKBENCH_SELECTION_PROVIDER_WORKBENCH_SELECTION_PROVIDER_H
#define UMICOM_WORKBENCH_SELECTION_PROVIDER_WORKBENCH_SELECTION_PROVIDER_H

#include "umicom/workbench_selection_provider/account_mapping.h"
#include "umicom/workbench_selection_provider/account_row_record.h"
#include "umicom/workbench_selection_provider/action_record.h"
#include "umicom/workbench_selection_provider/application_binding.h"
#include "umicom/workbench_selection_provider/audit_record.h"
#include "umicom/workbench_selection_provider/backpressure_record.h"
#include "umicom/workbench_selection_provider/bookmark_record.h"
#include "umicom/workbench_selection_provider/cache_key.h"
#include "umicom/workbench_selection_provider/cache_record.h"
#include "umicom/workbench_selection_provider/capability_record.h"
#include "umicom/workbench_selection_provider/causation_record.h"
#include "umicom/workbench_selection_provider/cell_record.h"
#include "umicom/workbench_selection_provider/coalesce_record.h"
#include "umicom/workbench_selection_provider/column_record.h"
#include "umicom/workbench_selection_provider/command_record.h"
#include "umicom/workbench_selection_provider/compatibility_record.h"
#include "umicom/workbench_selection_provider/conflict_record.h"
#include "umicom/workbench_selection_provider/context_binding.h"
#include "umicom/workbench_selection_provider/controller.h"
#include "umicom/workbench_selection_provider/conversion_record.h"
#include "umicom/workbench_selection_provider/correlation_record.h"
#include "umicom/workbench_selection_provider/counter_record.h"
#include "umicom/workbench_selection_provider/cursor_record.h"
#include "umicom/workbench_selection_provider/dedupe_record.h"
#include "umicom/workbench_selection_provider/descriptor.h"
#include "umicom/workbench_selection_provider/diagnostic_record.h"
#include "umicom/workbench_selection_provider/edge_record.h"
#include "umicom/workbench_selection_provider/enrichment_record.h"
#include "umicom/workbench_selection_provider/error_record.h"
#include "umicom/workbench_selection_provider/event_record.h"
#include "umicom/workbench_selection_provider/evidence_record.h"
#include "umicom/workbench_selection_provider/export_record.h"
#include "umicom/workbench_selection_provider/field_mapping.h"
#include "umicom/workbench_selection_provider/field_requirement.h"
#include "umicom/workbench_selection_provider/field_rule.h"
#include "umicom/workbench_selection_provider/filter_record.h"
#include "umicom/workbench_selection_provider/freshness_record.h"
#include "umicom/workbench_selection_provider/group_binding.h"
#include "umicom/workbench_selection_provider/health.h"
#include "umicom/workbench_selection_provider/health_record.h"
#include "umicom/workbench_selection_provider/hierarchy_record.h"
#include "umicom/workbench_selection_provider/history.h"
#include "umicom/workbench_selection_provider/history_entry.h"
#include "umicom/workbench_selection_provider/identity.h"
#include "umicom/workbench_selection_provider/import_record.h"
#include "umicom/workbench_selection_provider/instrument_mapping.h"
#include "umicom/workbench_selection_provider/instrument_row_record.h"
#include "umicom/workbench_selection_provider/latency_record.h"
#include "umicom/workbench_selection_provider/mapping_state.h"
#include "umicom/workbench_selection_provider/merge_record.h"
#include "umicom/workbench_selection_provider/metric_record.h"
#include "umicom/workbench_selection_provider/migration_record.h"
#include "umicom/workbench_selection_provider/node_record.h"
#include "umicom/workbench_selection_provider/normalization_record.h"
#include "umicom/workbench_selection_provider/page_record.h"
#include "umicom/workbench_selection_provider/paging_record.h"
#include "umicom/workbench_selection_provider/panel_binding.h"
#include "umicom/workbench_selection_provider/permission_record.h"
#include "umicom/workbench_selection_provider/pipeline_state.h"
#include "umicom/workbench_selection_provider/policy_record.h"
#include "umicom/workbench_selection_provider/presentation_record.h"
#include "umicom/workbench_selection_provider/problem.h"
#include "umicom/workbench_selection_provider/problem_mapping.h"
#include "umicom/workbench_selection_provider/problem_row_record.h"
#include "umicom/workbench_selection_provider/project.h"
#include "umicom/workbench_selection_provider/project_mapping.h"
#include "umicom/workbench_selection_provider/project_node_record.h"
#include "umicom/workbench_selection_provider/projection_record.h"
#include "umicom/workbench_selection_provider/provider_profile.h"
#include "umicom/workbench_selection_provider/provider_state.h"
#include "umicom/workbench_selection_provider/query_record.h"
#include "umicom/workbench_selection_provider/rate_limit_record.h"
#include "umicom/workbench_selection_provider/registry.h"
#include "umicom/workbench_selection_provider/remediation_record.h"
#include "umicom/workbench_selection_provider/replay_record.h"
#include "umicom/workbench_selection_provider/resolver_state.h"
#include "umicom/workbench_selection_provider/result_record.h"
#include "umicom/workbench_selection_provider/retry_record.h"
#include "umicom/workbench_selection_provider/revision_record.h"
#include "umicom/workbench_selection_provider/row_record.h"
#include "umicom/workbench_selection_provider/schema_compatibility.h"
#include "umicom/workbench_selection_provider/schema_record.h"
#include "umicom/workbench_selection_provider/search_record.h"
#include "umicom/workbench_selection_provider/selection_binding.h"
#include "umicom/workbench_selection_provider/selection_state.h"
#include "umicom/workbench_selection_provider/selection_token.h"
#include "umicom/workbench_selection_provider/service.h"
#include "umicom/workbench_selection_provider/snapshot.h"
#include "umicom/workbench_selection_provider/snapshot_item.h"
#include "umicom/workbench_selection_provider/sort_record.h"
#include "umicom/workbench_selection_provider/source_binding.h"
#include "umicom/workbench_selection_provider/source_branch_mapping.h"
#include "umicom/workbench_selection_provider/source_change_mapping.h"
#include "umicom/workbench_selection_provider/source_commit_mapping.h"
#include "umicom/workbench_selection_provider/source_control.h"
#include "umicom/workbench_selection_provider/source_row_record.h"
#include "umicom/workbench_selection_provider/staleness_record.h"
#include "umicom/workbench_selection_provider/studio_bridge.h"
#include "umicom/workbench_selection_provider/studio_profile.h"
#include "umicom/workbench_selection_provider/studio_profile_record.h"
#include "umicom/workbench_selection_provider/synchronization_record.h"
#include "umicom/workbench_selection_provider/telemetry_record.h"
#include "umicom/workbench_selection_provider/test.h"
#include "umicom/workbench_selection_provider/test_mapping.h"
#include "umicom/workbench_selection_provider/test_row_record.h"
#include "umicom/workbench_selection_provider/throughput_record.h"
#include "umicom/workbench_selection_provider/trace_record.h"
#include "umicom/workbench_selection_provider/trade_mapping.h"
#include "umicom/workbench_selection_provider/trade_row_record.h"
#include "umicom/workbench_selection_provider/trading_profile_record.h"
#include "umicom/workbench_selection_provider/trading_workbench.h"
#include "umicom/workbench_selection_provider/tree_record.h"
#include "umicom/workbench_selection_provider/types.h"
#include "umicom/workbench_selection_provider/validation_record.h"
#include "umicom/workbench_selection_provider/warning_record.h"

#endif
