#-----------------------------------------------------------------------------
# Umicom Framework
# File: tests/implementation_fingerprint/check_content.cmake
# PURPOSE: Check content identity independently of order and source-tree location.
# AUTHOR AND ORGANISATION: Sammy Hegab, Umicom Foundation
# LICENCE: MIT
#-----------------------------------------------------------------------------
cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/UmicomImplementationFingerprint.cmake")
if(NOT DEFINED WORK_ROOT OR NOT DEFINED CASE)
    message(FATAL_ERROR "WORK_ROOT and CASE are required.")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run)
set(work "${WORK_ROOT}/${CASE}-${run}")
file(MAKE_DIRECTORY "${work}/first" "${work}/second")
file(WRITE "${work}/first/owner.c" "int retained(void) { return 12; }\n")
file(WRITE "${work}/first/private.h" "#define VALUE 41\n")
file(WRITE "${work}/outside.c" "int outside(void) { return 0; }\n")
set(inputs owner.c private.h)

# Child invocations prove each rejection came from the intended guard, not an
# unrelated setup error. The parent requires both failure and its explanation.
if(CASE STREQUAL "missing-child")
    umicom_compute_implementation_fingerprint(value "${work}/first" absent.c)
elseif(CASE STREQUAL "empty-child")
    umicom_compute_implementation_fingerprint(value "${work}/first")
elseif(CASE STREQUAL "outside-child")
    umicom_compute_implementation_fingerprint(value "${work}/first" ../outside.c)
elseif(CASE STREQUAL "refusals")
    foreach(kind missing empty outside)
        execute_process(COMMAND "${CMAKE_COMMAND}" "-DCASE=${kind}-child" "-DWORK_ROOT=${work}"
            -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(kind STREQUAL "missing")
            set(expected "Implementation input is missing")
        elseif(kind STREQUAL "empty")
            set(expected "needs at least one source input")
        else()
            set(expected "Implementation input is outside its source root")
        endif()
        if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected}")
            message(FATAL_ERROR "${kind} did not produce its required refusal: ${output}${error}")
        endif()
    endforeach()
    return()
endif()

umicom_compute_implementation_fingerprint(before "${work}/first" ${inputs})
if(CASE STREQUAL "source")
    file(APPEND "${work}/first/owner.c" "int checked(void) { return 41; }\n")
elseif(CASE STREQUAL "private-header")
    file(WRITE "${work}/first/private.h" "#define VALUE 42\n")
elseif(CASE STREQUAL "relocation")
    file(COPY "${work}/first/" DESTINATION "${work}/second")
    umicom_compute_implementation_fingerprint(after "${work}/second" ${inputs})
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "Moving identical source files changed their content identity.")
    endif()
    return()
elseif(CASE STREQUAL "inputs")
    umicom_compute_implementation_fingerprint(after "${work}/first" private.h owner.c owner.c)
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "Input order or repetition changed the content identity.")
    endif()
    umicom_compute_implementation_fingerprint(after "${work}/first" owner.c)
    if(before STREQUAL after)
        message(FATAL_ERROR "Removing an input did not change the content identity.")
    endif()
    return()
else()
    message(FATAL_ERROR "Unknown content fingerprint case: ${CASE}")
endif()
umicom_compute_implementation_fingerprint(after "${work}/first" ${inputs})
if(before STREQUAL after)
    message(FATAL_ERROR "The fingerprint ignored a ${CASE} content change.")
endif()
