# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
cmake_minimum_required(VERSION 3.24)
# A unique output folder keeps repeat runs valid without deleting old evidence.
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef _run)
set(_folder "${DEST}/review space-δ-${_run}")
file(MAKE_DIRECTORY "${_folder}")
set(_context "0123456789abcdef0123456789abcdef\t2f737263\t2f6275696c64\t4465627567\n")
set(_rows "test\t61\t\tregistered\t\ntest\t62\t\tregistered\t\n")
file(WRITE "${_folder}/configured.tsv" "UMICOM-RELEASE-INVENTORY\t1\ncontext\tcmake\t${_context}${_rows}")
file(WRITE "${_folder}/observed.tsv" "UMICOM-RELEASE-INVENTORY\t1\ncontext\tctest\t${_context}test\t61\t\tregistered\t\ntest\t62\t\tdisabled\t\n")
function(expect result)
    execute_process(COMMAND "${TOOL}" ${ARGN} RESULT_VARIABLE _result OUTPUT_VARIABLE _output ERROR_VARIABLE _error)
    if(NOT _result STREQUAL "${result}")
        message(FATAL_ERROR "Policy CLI expected ${result}, received ${_result}: ${_output} ${_error}")
    endif()
endfunction()
expect(0 draft-policy "${_folder}/configured.tsv" "${_folder}/draft.tsv")
file(SHA256 "${_folder}/draft.tsv" _before)
expect(2 draft-policy "${_folder}/configured.tsv" "${_folder}/draft.tsv")
file(SHA256 "${_folder}/draft.tsv" _after)
if(NOT _before STREQUAL _after)
    message(FATAL_ERROR "Existing output was changed")
endif()
expect(1 assess-policy "${_folder}/configured.tsv" "${_folder}/observed.tsv" "${_folder}/draft.tsv")
expect(0 set-policy "${_folder}/draft.tsv" a required "Framework owner" "Required behaviour" "${_folder}/one.tsv")
expect(0 set-policy "${_folder}/one.tsv" b optional "Framework owner" "Optional teaching test in this fixture" "${_folder}/two.tsv")
expect(0 review-policy "${_folder}/two.tsv")
expect(0 assess-policy "${_folder}/configured.tsv" "${_folder}/observed.tsv" "${_folder}/two.tsv")
expect(2 set-policy "${_folder}/two.tsv" "a*" required "Owner" "Reason" "${_folder}/absent.tsv")
if(EXISTS "${_folder}/absent.tsv")
    message(FATAL_ERROR "Invalid edit created output")
endif()
expect(0 set-policy "${_folder}/two.tsv" b required "Framework owner" "Now required" "${_folder}/required.tsv")
expect(2 set-policy "${_folder}/two.tsv" b required "Framework owner" "Now required" "${_folder}/draft.tsv")
file(SHA256 "${_folder}/draft.tsv" _retained)
if(NOT _retained STREQUAL _before)
    message(FATAL_ERROR "Original decision draft was changed by an edit")
endif()
expect(1 assess-policy "${_folder}/configured.tsv" "${_folder}/observed.tsv" "${_folder}/required.tsv")
file(READ "${_folder}/configured.tsv" _configured)
string(REPLACE "0123456789abcdef0123456789abcdef" "1123456789abcdef0123456789abcdef" _changed "${_configured}")
file(WRITE "${_folder}/changed.tsv" "${_changed}")
expect(2 assess-policy "${_folder}/changed.tsv" "${_folder}/observed.tsv" "${_folder}/two.tsv")
