set(UMICOM_CREATIVE_AUDIO_CASES
    truncated_header
    wrong_magic
    riff_length
    format_tag
    sample_bits
    channels
    sample_rate
    block_alignment
    byte_rate
    partial_frame
    empty_data
    oversized_chunk
    missing_chunks
    truncated_payload
    metadata_padding
    fmt_extension
    chunk_limit
    duplicate_format
    duplicate_data
    stereo_samples
    copied_ownership
    unchanged_outputs
    full_range_exact
    trim_boundaries
    invalid_edits
    live_export_refused
    gain_and_fades
    overview_reference
    single_frame
    data_before_format
    mono_rates
    all_pcm_values
    maximum_file
    oversized_file
    mutations
    file_missing
    file_relative
    file_empty
    file_roundtrip
    file_unicode
)
