/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/language_runtime/json.c
 *
 * PURPOSE:
 *   Implement a bounded parent-linked JSON tokenizer and value readers.
 *
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/

#include "umicom/language_runtime/json.h"
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
typedef struct P { const char *j; size_t n,p; UmiLanguageRuntimeJsonDocument *d; int parent; } P;
static int tok(P *p,UmiLanguageRuntimeJsonTokenType t,int s){size_t i;if(p->d->token_count>=UMI_LANGUAGE_RUNTIME_MAX_TOKENS)return -1;i=p->d->token_count++;p->d->tokens[i]=(UmiLanguageRuntimeJsonToken){t,s,-1,0,p->parent};if(p->parent>=0)p->d->tokens[p->parent].size++;return(int)i;}
static void ws(P*p){while(p->p<p->n&&isspace((unsigned char)p->j[p->p]))p->p++;}
static UmiStatus val(P*p);
static UmiStatus str(P*p){int i=tok(p,UMI_LANGUAGE_RUNTIME_JSON_STRING,(int)p->p+1);if(i<0)return UMI_STATUS_CAPACITY_EXCEEDED;p->p++;while(p->p<p->n){char c=p->j[p->p++];if(c=='"'){p->d->tokens[i].end=(int)p->p-1;return UMI_STATUS_OK;}if((unsigned char)c<0x20U)return UMI_STATUS_PARSE_ERROR;if(c=='\\'){if(p->p>=p->n)return UMI_STATUS_PARSE_ERROR;c=p->j[p->p++];if(c=='u'){for(int k=0;k<4;k++){if(p->p>=p->n||!isxdigit((unsigned char)p->j[p->p]))return UMI_STATUS_PARSE_ERROR;p->p++;}}else if(strchr("\"\\/bfnrt",c)==NULL)return UMI_STATUS_PARSE_ERROR;}}return UMI_STATUS_PARSE_ERROR;}
static UmiStatus prim(P*p){size_t s=p->p;int i;while(p->p<p->n){char c=p->j[p->p];if(isspace((unsigned char)c)||c==','||c==']'||c=='}')break;if(c==':'||c=='"'||c=='['||c=='{'||(unsigned char)c<0x20U)return UMI_STATUS_PARSE_ERROR;p->p++;}if(p->p==s)return UMI_STATUS_PARSE_ERROR;i=tok(p,UMI_LANGUAGE_RUNTIME_JSON_PRIMITIVE,(int)s);if(i<0)return UMI_STATUS_CAPACITY_EXCEEDED;p->d->tokens[i].end=(int)p->p;return UMI_STATUS_OK;}
static UmiStatus arr(P*p){int old=p->parent,i=tok(p,UMI_LANGUAGE_RUNTIME_JSON_ARRAY,(int)p->p);UmiStatus s;if(i<0)return UMI_STATUS_CAPACITY_EXCEEDED;p->parent=i;p->p++;ws(p);if(p->p<p->n&&p->j[p->p]==']'){p->d->tokens[i].end=(int)++p->p;p->parent=old;return UMI_STATUS_OK;}for(;;){s=val(p);if(s!=UMI_STATUS_OK)return s;ws(p);if(p->p>=p->n)return UMI_STATUS_PARSE_ERROR;if(p->j[p->p]==']'){p->d->tokens[i].end=(int)++p->p;p->parent=old;return UMI_STATUS_OK;}if(p->j[p->p]!=',')return UMI_STATUS_PARSE_ERROR;p->p++;ws(p);}}
static UmiStatus obj(P*p){int old=p->parent,i=tok(p,UMI_LANGUAGE_RUNTIME_JSON_OBJECT,(int)p->p);UmiStatus s;if(i<0)return UMI_STATUS_CAPACITY_EXCEEDED;p->parent=i;p->p++;ws(p);if(p->p<p->n&&p->j[p->p]=='}'){p->d->tokens[i].end=(int)++p->p;p->parent=old;return UMI_STATUS_OK;}for(;;){if(p->p>=p->n||p->j[p->p]!='"')return UMI_STATUS_PARSE_ERROR;s=str(p);if(s!=UMI_STATUS_OK)return s;ws(p);if(p->p>=p->n||p->j[p->p]!=':')return UMI_STATUS_PARSE_ERROR;p->p++;ws(p);s=val(p);if(s!=UMI_STATUS_OK)return s;ws(p);if(p->p>=p->n)return UMI_STATUS_PARSE_ERROR;if(p->j[p->p]=='}'){p->d->tokens[i].end=(int)++p->p;p->parent=old;return UMI_STATUS_OK;}if(p->j[p->p]!=',')return UMI_STATUS_PARSE_ERROR;p->p++;ws(p);}}
static UmiStatus val(P*p){ws(p);if(p->p>=p->n)return UMI_STATUS_PARSE_ERROR;switch(p->j[p->p]){case'{':return obj(p);case'[':return arr(p);case'"':return str(p);default:return prim(p);}}
UmiStatus umi_language_runtime_json_parse(const char*j,UmiLanguageRuntimeJsonDocument*d){P p;UmiStatus s;if(j==NULL||d==NULL)return UMI_STATUS_INVALID_ARGUMENT;memset(d,0,sizeof(*d));d->json=j;p=(P){j,strlen(j),0U,d,-1};s=val(&p);if(s!=UMI_STATUS_OK)return s;ws(&p);return p.p==p.n?UMI_STATUS_OK:UMI_STATUS_PARSE_ERROR;}
static int eq(const UmiLanguageRuntimeJsonDocument*d,int t,const char*s){size_t n;if(d==NULL||s==NULL||t<0||(size_t)t>=d->token_count)return 0;n=strlen(s);return d->tokens[t].type==UMI_LANGUAGE_RUNTIME_JSON_STRING&&d->tokens[t].end-d->tokens[t].start==(int)n&&strncmp(d->json+d->tokens[t].start,s,n)==0;}
static int sib(const UmiLanguageRuntimeJsonDocument*d,int t){int i=t+1,p=d->tokens[t].parent;while((size_t)i<d->token_count){if(d->tokens[i].parent==p)return i;i++;}return-1;}
int umi_language_runtime_json_object_get(const UmiLanguageRuntimeJsonDocument*d,int o,const char*k){int i;if(d==NULL||k==NULL||o<0||(size_t)o>=d->token_count||d->tokens[o].type!=UMI_LANGUAGE_RUNTIME_JSON_OBJECT)return-1;i=o+1;while((size_t)i<d->token_count&&d->tokens[i].parent==o){int v=sib(d,i);if(v<0||d->tokens[v].parent!=o)return-1;if(eq(d,i,k))return v;i=sib(d,v);}return-1;}
size_t umi_language_runtime_json_object_count(const UmiLanguageRuntimeJsonDocument*d,int o){size_t c=0;int i;if(d==NULL||o<0||(size_t)o>=d->token_count||d->tokens[o].type!=UMI_LANGUAGE_RUNTIME_JSON_OBJECT)return 0;i=o+1;while((size_t)i<d->token_count&&d->tokens[i].parent==o){int v=sib(d,i);if(v<0||d->tokens[v].parent!=o)break;c++;i=sib(d,v);}return c;}
UmiStatus umi_language_runtime_json_object_entry_at(const UmiLanguageRuntimeJsonDocument*d,int o,size_t ix,int*k,int*v){size_t c=0;int i;if(d==NULL||k==NULL||v==NULL||o<0||(size_t)o>=d->token_count||d->tokens[o].type!=UMI_LANGUAGE_RUNTIME_JSON_OBJECT)return UMI_STATUS_INVALID_ARGUMENT;i=o+1;while((size_t)i<d->token_count&&d->tokens[i].parent==o){int x=sib(d,i);if(x<0||d->tokens[x].parent!=o)return UMI_STATUS_PARSE_ERROR;if(c++==ix){*k=i;*v=x;return UMI_STATUS_OK;}i=sib(d,x);}return UMI_STATUS_NOT_FOUND;}
int umi_language_runtime_json_array_at(const UmiLanguageRuntimeJsonDocument*d,int a,size_t ix){size_t c=0;int i;if(d==NULL||a<0||(size_t)a>=d->token_count||d->tokens[a].type!=UMI_LANGUAGE_RUNTIME_JSON_ARRAY)return-1;i=a+1;while((size_t)i<d->token_count&&d->tokens[i].parent==a){if(c++==ix)return i;i=sib(d,i);}return-1;}
size_t umi_language_runtime_json_array_count(const UmiLanguageRuntimeJsonDocument*d,int a){size_t c=0;int i;if(d==NULL||a<0||(size_t)a>=d->token_count||d->tokens[a].type!=UMI_LANGUAGE_RUNTIME_JSON_ARRAY)return 0;i=a+1;while((size_t)i<d->token_count&&d->tokens[i].parent==a){c++;i=sib(d,i);}return c;}
static int hx(char c){if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return 10+c-'a';if(c>='A'&&c<='F')return 10+c-'A';return-1;}
static UmiStatus utf8(char*out,size_t cap,size_t*u,unsigned cp){unsigned char b[3];size_t n;if(cp<=0x7F){b[0]=(unsigned char)cp;n=1;}else if(cp<=0x7FF){b[0]=(unsigned char)(0xC0|(cp>>6));b[1]=(unsigned char)(0x80|(cp&63));n=2;}else{b[0]=(unsigned char)(0xE0|(cp>>12));b[1]=(unsigned char)(0x80|((cp>>6)&63));b[2]=(unsigned char)(0x80|(cp&63));n=3;}if(*u+n+1>cap)return UMI_STATUS_CAPACITY_EXCEEDED;memcpy(out+*u,b,n);*u+=n;out[*u]=0;return UMI_STATUS_OK;}
UmiStatus umi_language_runtime_json_string(const UmiLanguageRuntimeJsonDocument*d,int t,char*out,size_t cap){size_t c,u=0;if(d==NULL||out==NULL||cap==0||t<0||(size_t)t>=d->token_count||d->tokens[t].type!=UMI_LANGUAGE_RUNTIME_JSON_STRING)return UMI_STATUS_INVALID_ARGUMENT;out[0]=0;c=(size_t)d->tokens[t].start;while(c<(size_t)d->tokens[t].end){unsigned char x=(unsigned char)d->json[c++];if(x=='\\'){char e=d->json[c++];if(e=='u'){unsigned cp=0;for(int k=0;k<4;k++){int h=hx(d->json[c++]);if(h<0)return UMI_STATUS_PARSE_ERROR;cp=cp*16U+(unsigned)h;}if(utf8(out,cap,&u,cp)!=UMI_STATUS_OK)return UMI_STATUS_CAPACITY_EXCEEDED;continue;}switch(e){case'"':x='"';break;case'\\':x='\\';break;case'/':x='/';break;case'b':x='\b';break;case'f':x='\f';break;case'n':x='\n';break;case'r':x='\r';break;case't':x='\t';break;default:return UMI_STATUS_PARSE_ERROR;}}if(u+2>cap)return UMI_STATUS_CAPACITY_EXCEEDED;out[u++]=(char)x;out[u]=0;}return UMI_STATUS_OK;}
UmiStatus umi_language_runtime_json_int64(const UmiLanguageRuntimeJsonDocument*d,int t,int64_t*out){char b[64],*e;long long v;size_t n;if(d==NULL||out==NULL||t<0||(size_t)t>=d->token_count||d->tokens[t].type!=UMI_LANGUAGE_RUNTIME_JSON_PRIMITIVE)return UMI_STATUS_INVALID_ARGUMENT;n=(size_t)(d->tokens[t].end-d->tokens[t].start);if(n==0||n>=sizeof(b))return UMI_STATUS_PARSE_ERROR;memcpy(b,d->json+d->tokens[t].start,n);b[n]=0;v=strtoll(b,&e,10);if(e==b||*e)return UMI_STATUS_PARSE_ERROR;*out=(int64_t)v;return UMI_STATUS_OK;}
UmiStatus umi_language_runtime_json_bool(const UmiLanguageRuntimeJsonDocument*d,int t,int*out){const UmiLanguageRuntimeJsonToken*x;if(d==NULL||out==NULL||t<0||(size_t)t>=d->token_count)return UMI_STATUS_INVALID_ARGUMENT;x=&d->tokens[t];if(x->type!=UMI_LANGUAGE_RUNTIME_JSON_PRIMITIVE)return UMI_STATUS_INVALID_ARGUMENT;if(x->end-x->start==4&&strncmp(d->json+x->start,"true",4)==0){*out=1;return UMI_STATUS_OK;}if(x->end-x->start==5&&strncmp(d->json+x->start,"false",5)==0){*out=0;return UMI_STATUS_OK;}return UMI_STATUS_PARSE_ERROR;}
int umi_language_runtime_json_is_null(const UmiLanguageRuntimeJsonDocument*d,int t){return d!=NULL&&t>=0&&(size_t)t<d->token_count&&d->tokens[t].type==UMI_LANGUAGE_RUNTIME_JSON_PRIMITIVE&&d->tokens[t].end-d->tokens[t].start==4&&strncmp(d->json+d->tokens[t].start,"null",4)==0;}
