/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/language_runtime/service_bridge.c
 *
 * PURPOSE:
 *   Project LSP results into existing Language Service registries without parallel Studio models.
 *
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/

#include "umicom/language_runtime/service_bridge.h"
#include <stdio.h>
#include <string.h>
static UmiStatus ok(UmiLanguageRuntimeServiceBridge*b){return b&&b->language?UMI_STATUS_OK:UMI_STATUS_INVALID_ARGUMENT;}
UmiStatus umi_language_runtime_service_bridge_init(UmiLanguageRuntimeServiceBridge*b,UmiLanguageService*l){if(!b||!l)return UMI_STATUS_INVALID_ARGUMENT;b->language=l;b->revision=1;return UMI_STATUS_OK;}
static void clear_completion(UmiLanguageCompletionRegistry*r,const char*d){size_t i=umi_language_completion_registry_count(r);while(i--){UmiLanguageCompletionSnapshot x;if(umi_language_completion_registry_at(r,i,&x)==UMI_STATUS_OK&&strcmp(x.document_id,d)==0)(void)umi_language_completion_registry_remove(r,x.id);}}
UmiStatus umi_language_runtime_publish_completion(UmiLanguageRuntimeServiceBridge*b,const char*d,uint32_t line,uint32_t col,const UmiLanguageRuntimeCompletionResult*r){size_t i;UmiLanguageCompletionRegistry*g;if(ok(b)!=UMI_STATUS_OK||!d||!r)return UMI_STATUS_INVALID_ARGUMENT;g=umi_language_service_completion(b->language);clear_completion(g,d);for(i=0;i<r->count;i++){UmiLanguageCompletionSnapshot x={0};UmiStatus s;x.struct_size=sizeof(x);x.api_version=UMI_LANGUAGE_COMPLETION_API_VERSION;snprintf(x.id,sizeof(x.id),"%s.completion.%zu",d,i);snprintf(x.document_id,sizeof(x.document_id),"%s",d);snprintf(x.label,sizeof(x.label),"%s",r->items[i].label);snprintf(x.detail,sizeof(x.detail),"%s",r->items[i].detail);snprintf(x.insert_text,sizeof(x.insert_text),"%s",r->items[i].insert_text);snprintf(x.kind,sizeof(x.kind),"%d",r->items[i].kind);snprintf(x.sort_text,sizeof(x.sort_text),"%s",r->items[i].sort_text);x.line=line;x.column=col;x.revision=b->revision+1;s=umi_language_completion_registry_upsert(g,&x);if(s!=UMI_STATUS_OK)return s;}b->revision++;return UMI_STATUS_OK;}
static void clear_hover(UmiLanguageHoverRegistry*r,const char*d){size_t i=umi_language_hover_registry_count(r);while(i--){UmiLanguageHoverSnapshot x;if(umi_language_hover_registry_at(r,i,&x)==UMI_STATUS_OK&&strcmp(x.document_id,d)==0)(void)umi_language_hover_registry_remove(r,x.id);}}
UmiStatus umi_language_runtime_publish_hover(UmiLanguageRuntimeServiceBridge*b,const char*d,uint32_t line,uint32_t col,const UmiLanguageRuntimeHoverResult*r){UmiLanguageHoverSnapshot x={0};UmiLanguageHoverRegistry*g;if(ok(b)!=UMI_STATUS_OK||!d||!r)return UMI_STATUS_INVALID_ARGUMENT;g=umi_language_service_hover(b->language);clear_hover(g,d);if(!r->contents[0])return UMI_STATUS_OK;x.struct_size=sizeof(x);x.api_version=UMI_LANGUAGE_HOVER_API_VERSION;snprintf(x.id,sizeof(x.id),"%s.hover",d);snprintf(x.document_id,sizeof(x.document_id),"%s",d);snprintf(x.contents,sizeof(x.contents),"%s",r->contents);x.line=line;x.column=col;if(r->has_range){x.start_line=r->range.start.line;x.start_column=r->range.start.character;x.end_line=r->range.end.line;x.end_column=r->range.end.character;}x.revision=++b->revision;return umi_language_hover_registry_upsert(g,&x);}
static void clear_sig(UmiLanguageSignatureRegistry*r,const char*d){size_t i=umi_language_signature_registry_count(r);while(i--){UmiLanguageSignatureSnapshot x;if(umi_language_signature_registry_at(r,i,&x)==UMI_STATUS_OK&&strcmp(x.document_id,d)==0)(void)umi_language_signature_registry_remove(r,x.id);}}
UmiStatus umi_language_runtime_publish_signature(UmiLanguageRuntimeServiceBridge*b,const char*d,uint32_t line,uint32_t col,const UmiLanguageRuntimeSignatureResult*r){UmiLanguageSignatureSnapshot x={0};UmiLanguageSignatureRegistry*g;if(ok(b)!=UMI_STATUS_OK||!d||!r)return UMI_STATUS_INVALID_ARGUMENT;g=umi_language_service_signature(b->language);clear_sig(g,d);if(!r->available)return UMI_STATUS_OK;x.struct_size=sizeof(x);x.api_version=UMI_LANGUAGE_SIGNATURE_API_VERSION;snprintf(x.id,sizeof(x.id),"%s.signature",d);snprintf(x.document_id,sizeof(x.document_id),"%s",d);snprintf(x.label,sizeof(x.label),"%s",r->label);snprintf(x.documentation,sizeof(x.documentation),"%s",r->documentation);x.active_parameter=r->active_parameter;x.line=line;x.column=col;x.revision=++b->revision;return umi_language_signature_registry_upsert(g,&x);}
UmiStatus umi_language_runtime_publish_locations(UmiLanguageRuntimeServiceBridge*b,const char*d,const char*sid,int def,const UmiLanguageRuntimeLocationList*r){UmiLanguageReferenceRegistry*g;size_t i;if(ok(b)!=UMI_STATUS_OK||!d||!sid||!r)return UMI_STATUS_INVALID_ARGUMENT;g=umi_language_service_reference(b->language);umi_language_reference_registry_clear(g);for(i=0;i<r->count;i++){UmiLanguageReferenceSnapshot x={0};UmiStatus s;x.struct_size=sizeof(x);x.api_version=UMI_LANGUAGE_REFERENCE_API_VERSION;snprintf(x.id,sizeof(x.id),"%s.reference.%zu",d,i);snprintf(x.symbol_id,sizeof(x.symbol_id),"%s",sid);snprintf(x.document_id,sizeof(x.document_id),"%s",d);snprintf(x.uri,sizeof(x.uri),"%s",r->items[i].uri);x.line=r->items[i].range.start.line;x.column=r->items[i].range.start.character;x.definition=def;x.revision=b->revision+1;s=umi_language_reference_registry_upsert(g,&x);if(s!=UMI_STATUS_OK)return s;}b->revision++;return UMI_STATUS_OK;}
static void clear_symbols(UmiLanguageSymbolRegistry*r,const char*d){size_t i=umi_language_symbol_registry_count(r);while(i--){UmiLanguageSymbolSnapshot x;if(umi_language_symbol_registry_at(r,i,&x)==UMI_STATUS_OK&&strcmp(x.document_id,d)==0)(void)umi_language_symbol_registry_remove(r,x.id);}}
UmiStatus umi_language_runtime_publish_symbols(UmiLanguageRuntimeServiceBridge*b,const char*d,const UmiLanguageRuntimeSymbolList*r){UmiLanguageSymbolRegistry*g;size_t i;if(ok(b)!=UMI_STATUS_OK||!d||!r)return UMI_STATUS_INVALID_ARGUMENT;g=umi_language_service_symbol(b->language);clear_symbols(g,d);for(i=0;i<r->count;i++){UmiLanguageSymbolSnapshot x={0};UmiStatus s;x.struct_size=sizeof(x);x.api_version=UMI_LANGUAGE_SYMBOL_API_VERSION;snprintf(x.id,sizeof(x.id),"%s.symbol.%zu",d,i);snprintf(x.document_id,sizeof(x.document_id),"%s",d);snprintf(x.name,sizeof(x.name),"%s",r->items[i].name);snprintf(x.kind,sizeof(x.kind),"%d",r->items[i].kind);snprintf(x.container,sizeof(x.container),"%s",r->items[i].container);x.line=r->items[i].range.start.line;x.column=r->items[i].range.start.character;x.end_line=r->items[i].range.end.line;x.end_column=r->items[i].range.end.character;x.revision=b->revision+1;s=umi_language_symbol_registry_upsert(g,&x);if(s!=UMI_STATUS_OK)return s;}b->revision++;return UMI_STATUS_OK;}

static void clear_diag(UmiLanguageDiagnosticRegistry*r,const char*d){size_t i=umi_language_diagnostic_registry_count(r);while(i--){UmiLanguageDiagnosticSnapshot x;if(umi_language_diagnostic_registry_at(r,i,&x)==UMI_STATUS_OK&&strcmp(x.document_id,d)==0)(void)umi_language_diagnostic_registry_remove(r,x.id);}}
UmiStatus umi_language_runtime_publish_diagnostics(UmiLanguageRuntimeServiceBridge*b,const char*d,const UmiLanguageRuntimeDiagnosticList*r){UmiLanguageDiagnosticRegistry*g;size_t i;if(ok(b)!=UMI_STATUS_OK||!d||!r)return UMI_STATUS_INVALID_ARGUMENT;g=umi_language_service_diagnostic(b->language);clear_diag(g,d);for(i=0;i<r->count;i++){UmiLanguageDiagnosticSnapshot x={0};UmiStatus s;x.struct_size=sizeof(x);x.api_version=UMI_LANGUAGE_DIAGNOSTIC_API_VERSION;snprintf(x.id,sizeof(x.id),"%s.diagnostic.%zu",d,i);snprintf(x.document_id,sizeof(x.document_id),"%s",d);snprintf(x.message,sizeof(x.message),"%s",r->items[i].message);snprintf(x.source,sizeof(x.source),"%s",r->items[i].source);snprintf(x.code,sizeof(x.code),"%s",r->items[i].code);x.severity=r->items[i].severity;x.line=r->items[i].range.start.line;x.column=r->items[i].range.start.character;x.end_line=r->items[i].range.end.line;x.end_column=r->items[i].range.end.character;x.revision=b->revision+1;s=umi_language_diagnostic_registry_upsert(g,&x);if(s!=UMI_STATUS_OK)return s;}b->revision++;return UMI_STATUS_OK;}
static void clear_actions(UmiLanguageCodeActionRegistry*r,const char*d){size_t i=umi_language_code_action_registry_count(r);while(i--){UmiLanguageCodeActionSnapshot x;if(umi_language_code_action_registry_at(r,i,&x)==UMI_STATUS_OK&&strcmp(x.document_id,d)==0)(void)umi_language_code_action_registry_remove(r,x.id);}}
UmiStatus umi_language_runtime_publish_code_actions(UmiLanguageRuntimeServiceBridge*b,const char*d,const UmiLanguageRuntimeCodeActionList*r){UmiLanguageCodeActionRegistry*g;size_t i;if(ok(b)!=UMI_STATUS_OK||!d||!r)return UMI_STATUS_INVALID_ARGUMENT;g=umi_language_service_code_action(b->language);clear_actions(g,d);for(i=0;i<r->count;i++){UmiLanguageCodeActionSnapshot x={0};UmiStatus s;x.struct_size=sizeof(x);x.api_version=UMI_LANGUAGE_CODE_ACTION_API_VERSION;snprintf(x.id,sizeof(x.id),"%s.code-action.%zu",d,i);snprintf(x.document_id,sizeof(x.document_id),"%s",d);snprintf(x.title,sizeof(x.title),"%s",r->items[i].title);snprintf(x.kind,sizeof(x.kind),"%s",r->items[i].kind);snprintf(x.command_id,sizeof(x.command_id),"%s",r->items[i].command);x.preferred=r->items[i].preferred;x.revision=b->revision+1;s=umi_language_code_action_registry_upsert(g,&x);if(s!=UMI_STATUS_OK)return s;}b->revision++;return UMI_STATUS_OK;}
static void clear_sem(UmiLanguageSemanticTokenRegistry*r,const char*d){size_t i=umi_language_semantic_token_registry_count(r);while(i--){UmiLanguageSemanticTokenSnapshot x;if(umi_language_semantic_token_registry_at(r,i,&x)==UMI_STATUS_OK&&strcmp(x.document_id,d)==0)(void)umi_language_semantic_token_registry_remove(r,x.id);}}
UmiStatus umi_language_runtime_publish_semantic_tokens(UmiLanguageRuntimeServiceBridge*b,const char*d,const UmiLanguageRuntimeSemanticTokens*r){UmiLanguageSemanticTokenRegistry*g;size_t i;uint32_t line=0,col=0;if(ok(b)!=UMI_STATUS_OK||!d||!r)return UMI_STATUS_INVALID_ARGUMENT;g=umi_language_service_semantic_token(b->language);clear_sem(g,d);for(i=0;i+4<r->count;i+=5){UmiLanguageSemanticTokenSnapshot x={0};UmiStatus s;uint32_t dl=r->data[i],ds=r->data[i+1];if(dl){line+=dl;col=ds;}else col+=ds;x.struct_size=sizeof(x);x.api_version=UMI_LANGUAGE_SEMANTIC_TOKEN_API_VERSION;snprintf(x.id,sizeof(x.id),"%s.semantic.%zu",d,i/5);snprintf(x.document_id,sizeof(x.document_id),"%s",d);snprintf(x.token_type,sizeof(x.token_type),"type-%u",r->data[i+3]);snprintf(x.modifiers,sizeof(x.modifiers),"0x%08x",r->data[i+4]);x.line=line;x.column=col;x.length=r->data[i+2];x.revision=b->revision+1;s=umi_language_semantic_token_registry_upsert(g,&x);if(s!=UMI_STATUS_OK)return s;}b->revision++;return UMI_STATUS_OK;}
static void clear_hint(UmiLanguageInlayHintRegistry*r,const char*d){size_t i=umi_language_inlay_hint_registry_count(r);while(i--){UmiLanguageInlayHintSnapshot x;if(umi_language_inlay_hint_registry_at(r,i,&x)==UMI_STATUS_OK&&strcmp(x.document_id,d)==0)(void)umi_language_inlay_hint_registry_remove(r,x.id);}}
UmiStatus umi_language_runtime_publish_inlay_hints(UmiLanguageRuntimeServiceBridge*b,const char*d,const UmiLanguageRuntimeInlayHintList*r){UmiLanguageInlayHintRegistry*g;size_t i;if(ok(b)!=UMI_STATUS_OK||!d||!r)return UMI_STATUS_INVALID_ARGUMENT;g=umi_language_service_inlay_hint(b->language);clear_hint(g,d);for(i=0;i<r->count;i++){UmiLanguageInlayHintSnapshot x={0};UmiStatus s;x.struct_size=sizeof(x);x.api_version=UMI_LANGUAGE_INLAY_HINT_API_VERSION;snprintf(x.id,sizeof(x.id),"%s.inlay.%zu",d,i);snprintf(x.document_id,sizeof(x.document_id),"%s",d);snprintf(x.label,sizeof(x.label),"%s",r->items[i].label);snprintf(x.kind,sizeof(x.kind),"%d",r->items[i].kind);x.line=r->items[i].position.line;x.column=r->items[i].position.character;x.visible=1;x.revision=b->revision+1;s=umi_language_inlay_hint_registry_upsert(g,&x);if(s!=UMI_STATUS_OK)return s;}b->revision++;return UMI_STATUS_OK;}
static void clear_fold(UmiLanguageFoldingRangeRegistry*r,const char*d){size_t i=umi_language_folding_range_registry_count(r);while(i--){UmiLanguageFoldingRangeSnapshot x;if(umi_language_folding_range_registry_at(r,i,&x)==UMI_STATUS_OK&&strcmp(x.document_id,d)==0)(void)umi_language_folding_range_registry_remove(r,x.id);}}
UmiStatus umi_language_runtime_publish_folding_ranges(UmiLanguageRuntimeServiceBridge*b,const char*d,const UmiLanguageRuntimeFoldingRangeList*r){UmiLanguageFoldingRangeRegistry*g;size_t i;if(ok(b)!=UMI_STATUS_OK||!d||!r)return UMI_STATUS_INVALID_ARGUMENT;g=umi_language_service_folding_range(b->language);clear_fold(g,d);for(i=0;i<r->count;i++){UmiLanguageFoldingRangeSnapshot x={0};UmiStatus s;x.struct_size=sizeof(x);x.api_version=UMI_LANGUAGE_FOLDING_RANGE_API_VERSION;snprintf(x.id,sizeof(x.id),"%s.fold.%zu",d,i);snprintf(x.document_id,sizeof(x.document_id),"%s",d);snprintf(x.kind,sizeof(x.kind),"%s",r->items[i].kind);x.start_line=r->items[i].start_line;x.end_line=r->items[i].end_line;x.collapsed=0;x.revision=b->revision+1;s=umi_language_folding_range_registry_upsert(g,&x);if(s!=UMI_STATUS_OK)return s;}b->revision++;return UMI_STATUS_OK;}
UmiStatus umi_language_runtime_publish_formatting_available(UmiLanguageRuntimeServiceBridge*b,const char*d,const char*p,uint32_t tab,int spaces){UmiLanguageFormattingSnapshot x={0};if(ok(b)!=UMI_STATUS_OK||!d||!p||!tab)return UMI_STATUS_INVALID_ARGUMENT;x.struct_size=sizeof(x);x.api_version=UMI_LANGUAGE_FORMATTING_API_VERSION;snprintf(x.id,sizeof(x.id),"%s.formatting",d);snprintf(x.document_id,sizeof(x.document_id),"%s",d);snprintf(x.provider_id,sizeof(x.provider_id),"%s",p);snprintf(x.mode,sizeof(x.mode),"document");x.tab_size=tab;x.insert_spaces=spaces!=0;x.available=1;x.revision=++b->revision;return umi_language_formatting_registry_upsert(umi_language_service_formatting(b->language),&x);}
UmiStatus umi_language_runtime_publish_rename(UmiLanguageRuntimeServiceBridge*b,const char*d,const char*sid,const char*old,const char*newn,const UmiLanguageRuntimeWorkspaceEdit*e){UmiLanguageRenameSnapshot x={0};if(ok(b)!=UMI_STATUS_OK||!d||!sid||!old||!newn||!e)return UMI_STATUS_INVALID_ARGUMENT;x.struct_size=sizeof(x);x.api_version=UMI_LANGUAGE_RENAME_API_VERSION;snprintf(x.id,sizeof(x.id),"%s.rename",d);snprintf(x.symbol_id,sizeof(x.symbol_id),"%s",sid);snprintf(x.old_name,sizeof(x.old_name),"%s",old);snprintf(x.new_name,sizeof(x.new_name),"%s",newn);snprintf(x.document_id,sizeof(x.document_id),"%s",d);x.state=e->count?1:0;x.conflict_count=0;x.revision=++b->revision;return umi_language_rename_registry_upsert(umi_language_service_rename(b->language),&x);}
