/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/language_runtime/server.c
 *
 * PURPOSE:
 *   Implement framed JSON-RPC I/O, request correlation and client lifecycle accounting.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/

#include "umicom/language_runtime/server.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
struct UmiLanguageRuntimeServer{char id[UMI_LANGUAGE_RUNTIME_ID_CAPACITY];UmiLanguageServerProfile profile;char root[UMI_LANGUAGE_RUNTIME_PATH_CAPACITY];UmiLanguageRuntimeTransport t;UmiLanguageRuntimeFramer f;UmiLanguageRuntimePendingTable p;UmiLanguageClientSession session;UmiLanguageRuntimeServerState state;uint64_t next,sent,recv,bs,br,rev;};
static UmiStatus st(UmiLanguageRuntimeServer*s,UmiLanguageRuntimeServerState x){UmiLanguageClientState y;if(!s)return UMI_STATUS_INVALID_ARGUMENT;switch(x){case UMI_LANGUAGE_RUNTIME_SERVER_STOPPED:y=UMI_LANGUAGE_CLIENT_STOPPED;break;case UMI_LANGUAGE_RUNTIME_SERVER_STARTING:y=UMI_LANGUAGE_CLIENT_STARTING;break;case UMI_LANGUAGE_RUNTIME_SERVER_INITIALIZING:y=UMI_LANGUAGE_CLIENT_INITIALIZING;break;case UMI_LANGUAGE_RUNTIME_SERVER_READY:y=UMI_LANGUAGE_CLIENT_READY;break;case UMI_LANGUAGE_RUNTIME_SERVER_STOPPING:y=UMI_LANGUAGE_CLIENT_STOPPING;break;default:y=UMI_LANGUAGE_CLIENT_FAILED;break;}if(s->session.state!=y){UmiStatus q=umi_language_client_session_transition(&s->session,y);if(q!=UMI_STATUS_OK)return q;}s->state=x;s->rev++;return UMI_STATUS_OK;}
UmiStatus umi_language_runtime_server_create_with_transport(const char*id,const UmiLanguageServerProfile*p,const char*root,UmiLanguageRuntimeTransport*t,UmiLanguageRuntimeServer**out){UmiLanguageRuntimeServer*s;UmiStatus q;if(!id||!*id||!p||!p->id[0]||!root||!*root||!t||!out)return UMI_STATUS_INVALID_ARGUMENT;q=umi_language_runtime_transport_validate(t);if(q!=UMI_STATUS_OK)return q;*out=NULL;s=calloc(1,sizeof(*s));if(!s)return UMI_STATUS_OUT_OF_MEMORY;if(snprintf(s->id,sizeof(s->id),"%s",id)<0||snprintf(s->root,sizeof(s->root),"%s",root)<0){free(s);return UMI_STATUS_CAPACITY_EXCEEDED;}s->profile=*p;s->t=*t;memset(t,0,sizeof(*t));umi_language_runtime_framer_init(&s->f);umi_language_runtime_pending_init(&s->p);s->next=1;s->rev=1;q=umi_language_client_session_init(&s->session,id,p->id,root);if(q==UMI_STATUS_OK)q=st(s,UMI_LANGUAGE_RUNTIME_SERVER_STARTING);if(q!=UMI_STATUS_OK){s->t.destroy(s->t.instance);free(s);return q;}*out=s;return UMI_STATUS_OK;}
UmiStatus umi_language_runtime_server_start(const char*id,const UmiLanguageServerProfile*p,const char*root,const char*wd,UmiLanguageRuntimeServer**out){UmiLanguageRuntimeArguments a;UmiLanguageRuntimeProcessStreamConfig c={0};UmiLanguageRuntimeProcessStream*ps=NULL;UmiLanguageRuntimeTransport t;UmiStatus q;if(!p||!p->executable[0])return UMI_STATUS_INVALID_ARGUMENT;q=umi_language_runtime_arguments_parse(p->arguments,&a);if(q!=UMI_STATUS_OK)return q;c.program=p->executable;c.arguments=a.values;c.argument_count=a.count;c.working_directory=wd;q=umi_language_runtime_process_stream_start(&c,&ps);if(q!=UMI_STATUS_OK)return q;q=umi_language_runtime_transport_from_process(ps,&t);if(q!=UMI_STATUS_OK){umi_language_runtime_process_stream_destroy(ps);return q;}q=umi_language_runtime_server_create_with_transport(id,p,root,&t,out);if(q!=UMI_STATUS_OK&&t.instance)t.destroy(t.instance);return q;}
void umi_language_runtime_server_destroy(UmiLanguageRuntimeServer*s){if(!s)return;if(s->t.instance)s->t.destroy(s->t.instance);free(s);}
UmiStatus umi_language_runtime_server_transition(UmiLanguageRuntimeServer*s,UmiLanguageRuntimeServerState x){return x>=UMI_LANGUAGE_RUNTIME_SERVER_STOPPED&&x<=UMI_LANGUAGE_RUNTIME_SERVER_FAILED?st(s,x):UMI_STATUS_INVALID_ARGUMENT;}
static UmiStatus sendj(UmiLanguageRuntimeServer*s,const char*j){char fr[UMI_LANGUAGE_RUNTIME_FRAME_CAPACITY];size_t n=0;UmiStatus q=umi_language_runtime_frame_encode(j,fr,sizeof(fr),&n);if(q!=UMI_STATUS_OK)return q;q=s->t.write(s->t.instance,fr,n);if(q==UMI_STATUS_OK){s->sent++;s->bs+=n;s->rev++;}return q;}
UmiStatus umi_language_runtime_server_send_request(UmiLanguageRuntimeServer*s,const char*m,const char*p,const char*d,uint64_t*out){char j[UMI_LANGUAGE_RUNTIME_JSON_CAPACITY];uint64_t id;UmiStatus q;UmiLanguageRuntimePendingRequest ignored;if(!s||!m)return UMI_STATUS_INVALID_ARGUMENT;id=s->next++;if(!id)id=s->next++;q=umi_language_runtime_build_request(id,m,p,j,sizeof(j));if(q!=UMI_STATUS_OK)return q;q=umi_language_runtime_pending_add(&s->p,id,m,d);if(q!=UMI_STATUS_OK)return q;q=sendj(s,j);if(q!=UMI_STATUS_OK){(void)umi_language_runtime_pending_take(&s->p,id,&ignored);return q;}umi_language_client_session_record_request(&s->session);if(out)*out=id;return UMI_STATUS_OK;}
UmiStatus umi_language_runtime_server_send_notification(UmiLanguageRuntimeServer*s,const char*m,const char*p){char j[UMI_LANGUAGE_RUNTIME_JSON_CAPACITY];UmiStatus q;if(!s||!m)return UMI_STATUS_INVALID_ARGUMENT;q=umi_language_runtime_build_notification(m,p,j,sizeof(j));return q==UMI_STATUS_OK?sendj(s,j):q;}
UmiStatus umi_language_runtime_server_receive(UmiLanguageRuntimeServer*s,uint32_t tm,UmiLanguageRuntimeEnvelope*out){unsigned char b[8192];size_t n=0,jn=0;char j[UMI_LANGUAGE_RUNTIME_JSON_CAPACITY];UmiStatus q;if(!s||!out)return UMI_STATUS_INVALID_ARGUMENT;while(!umi_language_runtime_framer_has_message(&s->f)){q=s->t.read(s->t.instance,b,sizeof(b),tm,&n);if(q!=UMI_STATUS_OK)return q;s->br+=n;q=umi_language_runtime_framer_feed(&s->f,b,n);if(q!=UMI_STATUS_OK)return q;if(!n)return UMI_STATUS_NOT_FOUND;}q=umi_language_runtime_framer_pop(&s->f,j,sizeof(j),&jn);if(q!=UMI_STATUS_OK)return q;(void)jn;q=umi_language_runtime_message_parse(j,out);if(q!=UMI_STATUS_OK)return q;if((out->kind==UMI_LANGUAGE_RUNTIME_MESSAGE_RESPONSE||out->kind==UMI_LANGUAGE_RUNTIME_MESSAGE_ERROR)&&out->request_id){UmiLanguageRuntimePendingRequest x;if(umi_language_runtime_pending_take(&s->p,out->request_id,&x)==UMI_STATUS_OK)snprintf(out->method,sizeof(out->method),"%s",x.method);umi_language_client_session_record_response(&s->session);}else if(out->kind==UMI_LANGUAGE_RUNTIME_MESSAGE_NOTIFICATION)umi_language_client_session_record_notification(&s->session);s->recv++;s->rev++;return UMI_STATUS_OK;}
UmiStatus umi_language_runtime_server_stop(UmiLanguageRuntimeServer*s,uint32_t tm){UmiStatus q;if(!s)return UMI_STATUS_INVALID_ARGUMENT;(void)st(s,UMI_LANGUAGE_RUNTIME_SERVER_STOPPING);q=s->t.stop(s->t.instance,tm);(void)st(s,q==UMI_STATUS_OK?UMI_LANGUAGE_RUNTIME_SERVER_STOPPED:UMI_LANGUAGE_RUNTIME_SERVER_FAILED);return q;}
int umi_language_runtime_server_is_running(UmiLanguageRuntimeServer*s){return s&&s->t.instance&&s->t.is_running(s->t.instance);}
UmiStatus umi_language_runtime_server_snapshot(const UmiLanguageRuntimeServer*s,UmiLanguageRuntimeServerSnapshot*out){if(!s||!out)return UMI_STATUS_INVALID_ARGUMENT;memset(out,0,sizeof(*out));snprintf(out->server_id,sizeof(out->server_id),"%s",s->id);snprintf(out->profile_id,sizeof(out->profile_id),"%s",s->profile.id);snprintf(out->root_uri,sizeof(out->root_uri),"%s",s->root);out->state=s->state;out->next_request_id=s->next;out->pending_requests=s->p.active_count;out->messages_sent=s->sent;out->messages_received=s->recv;out->bytes_sent=s->bs;out->bytes_received=s->br;out->revision=s->rev;return UMI_STATUS_OK;}
