/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/developer_project/templates/assembly_console.c
 *
 * PURPOSE:
 *   Define the complete Assembly Console Project starter recipe. Generated source remains
 *   product-specific while reusable lifecycle/platform behaviour stays in
 *   Umicom Framework.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
#include "umicom/developer_project/templates/assembly_console.h"

static const char *const SECONDARY_LANGUAGES[] = {
    "developer.language.c23"
};

static const UmiDeveloperProjectTemplateFile FILES[] = {
    {
        "CMakeLists.txt",
        "#-----------------------------------------------------------------------------\n# {{APPLICATION_NAME}}\n# Generated by Umicom Framework project templates.\n# Author: Sammy Hegab\n# Organisation: Umicom Foundation\n# Licence: MIT\n#-----------------------------------------------------------------------------\ncmake_minimum_required(VERSION 3.24)\nproject({{TARGET_NAME}} VERSION 0.1.0 LANGUAGES C ASM)\nset(CMAKE_C_STANDARD 23)\nset(CMAKE_C_STANDARD_REQUIRED ON)\nset(CMAKE_C_EXTENSIONS OFF)\nset(CMAKE_RUNTIME_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/bin\")\nset(CMAKE_LIBRARY_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/lib\")\nset(CMAKE_ARCHIVE_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/lib\")\n\nadd_executable({{TARGET_NAME}} src/main.c src/answer.S)\ninstall(TARGETS {{TARGET_NAME}} RUNTIME DESTINATION bin)\nset(CPACK_GENERATOR \"ZIP\")\ninclude(CPack)\n",
        0,
        0
    },
    {
        "CMakePresets.json",
        "{\n  \"version\": 6,\n  \"configurePresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"displayName\": \"Windows MSYS2 UCRT64 Debug\",\n      \"generator\": \"Ninja\",\n      \"binaryDir\": \"${sourceDir}/build/windows-ucrt64-debug\",\n      \"cacheVariables\": {\n        \"CMAKE_BUILD_TYPE\": \"Debug\",\n        \"CMAKE_C_COMPILER\": \"C:/msys64/ucrt64/bin/gcc.exe\",\n        \"CMAKE_MAKE_PROGRAM\": \"C:/msys64/ucrt64/bin/ninja.exe\",\n        \"BUILD_TESTING\": \"ON\"\n      }\n    }\n  ],\n  \"buildPresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"configurePreset\": \"windows-ucrt64-debug\"\n    }\n  ],\n  \"testPresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"configurePreset\": \"windows-ucrt64-debug\",\n      \"output\": {\n        \"outputOnFailure\": true\n      }\n    }\n  ]\n}\n",
        0,
        0
    },
    {
        "src/main.c",
        "/*-----------------------------------------------------------------------------\n * {{APPLICATION_NAME}}\n *\n * Generated from the Umicom Framework project platform.\n * Author: Sammy Hegab\n * Organisation: Umicom Foundation\n * Licence: MIT\n *---------------------------------------------------------------------------*/\n\n#include <stdio.h>\n\nint umicom_generated_answer(void);\n\nint main(void)\n{\n    (void)printf(\"Assembly answer: %d\\n\", umicom_generated_answer());\n    return 0;\n}\n",
        0,
        0
    },
    {
        "src/answer.S",
        "# -----------------------------------------------------------------------------\n# {{APPLICATION_NAME}}\n# Generated assembly example.\n# Author: Sammy Hegab\n# Organisation: Umicom Foundation\n# Licence: MIT\n# -----------------------------------------------------------------------------\n    .text\n    .globl umicom_generated_answer\numicom_generated_answer:\n    mov $42, %eax\n    ret\n",
        0,
        0
    },
    {
        "README.md",
        "# {{APPLICATION_NAME}}\n\nGenerated from the Umicom Framework project platform.\n\nThis starter keeps reusable behaviour in **Umicom Framework** and limits the\nproduct repository to product-specific composition, branding and business logic.\n\n## Build on Windows\n\n```powershell\n$env:Path = \"C:/msys64/ucrt64/bin;$env:Path\"\ncmake --preset windows-ucrt64-debug\ncmake --build --preset windows-ucrt64-debug --parallel 2\nctest --preset windows-ucrt64-debug\n```\n",
        0,
        0
    },
    {
        ".gitignore",
        "build/\ninstall/\ndist/\n*.o\n*.obj\n*.exe\n*.dll\n*.so\n*.dylib\n",
        0,
        0
    }
};

/*
 * Provide the developer project template assembly console operation used by this module
 * and its client applications.
 */
const UmiDeveloperProjectTemplate *umi_developer_project_template_assembly_console(void)
{
    static const UmiDeveloperProjectTemplate project_template = {
        .structure_size = (uint32_t)sizeof(UmiDeveloperProjectTemplate),
        .api_version = UMI_DEVELOPER_PROJECT_API_VERSION,
        .template_id = "developer.template.assembly-console",
        .title = "Assembly Console Project",
        .description = "Assembly-first project built by CMake with a tiny C host for portable startup.",
        .kind = UMI_DEVELOPER_PROJECT_EXECUTABLE,
        .build_system = UMI_DEVELOPER_PROJECT_BUILD_CMAKE,
        .primary_language_id = "developer.language.assembly",
        .secondary_language_ids = SECONDARY_LANGUAGES,
        .secondary_language_count = sizeof(SECONDARY_LANGUAGES) / sizeof(SECONDARY_LANGUAGES[0]),
        .recommended_frontends = 1U,
        .files = FILES,
        .file_count = sizeof(FILES) / sizeof(FILES[0]),
        .thin_application = 0,
        .supports_tests = 1,
        .supports_install = 1,
        .supports_package = 1
    };

    return &project_template;
}
