/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/developer_project/templates/bash_tool.c
 *
 * PURPOSE:
 *   Define the complete Bash Tool starter recipe. Generated source remains
 *   product-specific while reusable lifecycle/platform behaviour stays in
 *   Umicom Framework.
 *
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
#include "umicom/developer_project/templates/bash_tool.h"

static const UmiDeveloperProjectTemplateFile FILES[] = {
    {
        "bin/{{TARGET_NAME}}.sh",
        "#!/usr/bin/env bash\n# -----------------------------------------------------------------------------\n# {{APPLICATION_NAME}}\n# Generated by Umicom Framework.\n# Author: Sammy Hegab\n# Organisation: Umicom Foundation\n# Licence: MIT\n# -----------------------------------------------------------------------------\nset -euo pipefail\nprintf '%s\\n' '{{APPLICATION_NAME}}'\n",
        1,
        0
    },
    {
        "README.md",
        "# {{APPLICATION_NAME}}\n\nGenerated from the Umicom Framework project platform.\n\nThis starter keeps reusable behaviour in **Umicom Framework** and limits the\nproduct repository to product-specific composition, branding and business logic.\n\n## Build on Windows\n\n```powershell\n$env:Path = \"C:/msys64/ucrt64/bin;$env:Path\"\ncmake --preset windows-ucrt64-debug\ncmake --build --preset windows-ucrt64-debug --parallel 2\nctest --preset windows-ucrt64-debug\n```\n",
        0,
        0
    },
    {
        ".gitignore",
        "build/\ninstall/\ndist/\n*.o\n*.obj\n*.exe\n*.dll\n*.so\n*.dylib\n",
        0,
        0
    }
};

const UmiDeveloperProjectTemplate *umi_developer_project_template_bash_tool(void)
{
    static const UmiDeveloperProjectTemplate project_template = {
        .structure_size = (uint32_t)sizeof(UmiDeveloperProjectTemplate),
        .api_version = UMI_DEVELOPER_PROJECT_API_VERSION,
        .template_id = "developer.template.bash-tool",
        .title = "Bash Tool",
        .description = "Small Bash automation project with explicit script entry point.",
        .kind = UMI_DEVELOPER_PROJECT_SCRIPT,
        .build_system = UMI_DEVELOPER_PROJECT_BUILD_SCRIPT,
        .primary_language_id = "developer.language.bash",
        .secondary_language_ids = NULL,
        .secondary_language_count = 0U,
        .recommended_frontends = 1U,
        .files = FILES,
        .file_count = sizeof(FILES) / sizeof(FILES[0]),
        .thin_application = 0,
        .supports_tests = 0,
        .supports_install = 0,
        .supports_package = 0
    };

    return &project_template;
}
