/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/developer_project/templates/c23_static_library.c
 *
 * PURPOSE:
 *   Define the complete C23 Static Library starter recipe. Generated source remains
 *   product-specific while reusable lifecycle/platform behaviour stays in
 *   Umicom Framework.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
#include "umicom/developer_project/templates/c23_static_library.h"

static const UmiDeveloperProjectTemplateFile FILES[] = {
    {
        "CMakeLists.txt",
        "#-----------------------------------------------------------------------------\n# {{APPLICATION_NAME}}\n# Generated by Umicom Framework project templates.\n# Author: Sammy Hegab\n# Organisation: Umicom Foundation\n# Licence: MIT\n#-----------------------------------------------------------------------------\ncmake_minimum_required(VERSION 3.24)\nproject({{TARGET_NAME}} VERSION 0.1.0 LANGUAGES C)\nset(CMAKE_C_STANDARD 23)\nset(CMAKE_C_STANDARD_REQUIRED ON)\nset(CMAKE_C_EXTENSIONS OFF)\nset(CMAKE_RUNTIME_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/bin\")\nset(CMAKE_LIBRARY_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/lib\")\nset(CMAKE_ARCHIVE_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/lib\")\n\ninclude(CTest)\nadd_library({{TARGET_NAME}} STATIC src/{{TARGET_NAME}}.c)\ntarget_include_directories({{TARGET_NAME}} PUBLIC include)\ntarget_compile_options({{TARGET_NAME}} PRIVATE -Wall -Wextra -Wpedantic)\ninstall(TARGETS {{TARGET_NAME}} ARCHIVE DESTINATION lib)\ninstall(DIRECTORY include/ DESTINATION include)\nif(BUILD_TESTING)\n    add_executable({{TARGET_NAME}}-test tests/test_{{TARGET_NAME}}.c)\n    target_link_libraries({{TARGET_NAME}}-test PRIVATE {{TARGET_NAME}})\n    add_test(NAME {{TARGET_NAME}}.unit COMMAND {{TARGET_NAME}}-test)\nendif()\nset(CPACK_GENERATOR \"ZIP\")\ninclude(CPack)\n",
        0,
        0
    },
    {
        "CMakePresets.json",
        "{\n  \"version\": 6,\n  \"configurePresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"displayName\": \"Windows MSYS2 UCRT64 Debug\",\n      \"generator\": \"Ninja\",\n      \"binaryDir\": \"${sourceDir}/build/windows-ucrt64-debug\",\n      \"cacheVariables\": {\n        \"CMAKE_BUILD_TYPE\": \"Debug\",\n        \"CMAKE_C_COMPILER\": \"C:/msys64/ucrt64/bin/gcc.exe\",\n        \"CMAKE_MAKE_PROGRAM\": \"C:/msys64/ucrt64/bin/ninja.exe\",\n        \"BUILD_TESTING\": \"ON\"\n      }\n    }\n  ],\n  \"buildPresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"configurePreset\": \"windows-ucrt64-debug\"\n    }\n  ],\n  \"testPresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"configurePreset\": \"windows-ucrt64-debug\",\n      \"output\": {\n        \"outputOnFailure\": true\n      }\n    }\n  ]\n}\n",
        0,
        0
    },
    {
        "include/{{TARGET_NAME}}/{{TARGET_NAME}}.h",
        "/*-----------------------------------------------------------------------------\n * {{APPLICATION_NAME}}\n *\n * Generated from the Umicom Framework project platform.\n * Author: Sammy Hegab\n * Organisation: Umicom Foundation\n * Licence: MIT\n *---------------------------------------------------------------------------*/\n\n#ifndef {{HEADER_GUARD}}\n#define {{HEADER_GUARD}}\n\nint {{TARGET_NAME}}_add(int left, int right);\n\n#endif\n",
        0,
        0
    },
    {
        "src/{{TARGET_NAME}}.c",
        "/*-----------------------------------------------------------------------------\n * {{APPLICATION_NAME}}\n *\n * Generated from the Umicom Framework project platform.\n * Author: Sammy Hegab\n * Organisation: Umicom Foundation\n * Licence: MIT\n *---------------------------------------------------------------------------*/\n\n#include \"{{TARGET_NAME}}/{{TARGET_NAME}}.h\"\n\nint {{TARGET_NAME}}_add(int left, int right)\n{\n    return left + right;\n}\n",
        0,
        0
    },
    {
        "tests/test_{{TARGET_NAME}}.c",
        "/*-----------------------------------------------------------------------------\n * {{APPLICATION_NAME}}\n *\n * Generated from the Umicom Framework project platform.\n * Author: Sammy Hegab\n * Organisation: Umicom Foundation\n * Licence: MIT\n *---------------------------------------------------------------------------*/\n\n#include <assert.h>\n#include \"{{TARGET_NAME}}/{{TARGET_NAME}}.h\"\n\nint main(void)\n{\n    assert({{TARGET_NAME}}_add(2, 3) == 5);\n    return 0;\n}\n",
        0,
        0
    },
    {
        "README.md",
        "# {{APPLICATION_NAME}}\n\nGenerated from the Umicom Framework project platform.\n\nThis starter keeps reusable behaviour in **Umicom Framework** and limits the\nproduct repository to product-specific composition, branding and business logic.\n\n## Build on Windows\n\n```powershell\n$env:Path = \"C:/msys64/ucrt64/bin;$env:Path\"\ncmake --preset windows-ucrt64-debug\ncmake --build --preset windows-ucrt64-debug --parallel 2\nctest --preset windows-ucrt64-debug\n```\n",
        0,
        0
    },
    {
        ".gitignore",
        "build/\ninstall/\ndist/\n*.o\n*.obj\n*.exe\n*.dll\n*.so\n*.dylib\n",
        0,
        0
    }
};

/*
 * Provide the developer project template c23 static library operation used by this module
 * and its client applications.
 */
const UmiDeveloperProjectTemplate *umi_developer_project_template_c23_static_library(void)
{
    static const UmiDeveloperProjectTemplate project_template = {
        .structure_size = (uint32_t)sizeof(UmiDeveloperProjectTemplate),
        .api_version = UMI_DEVELOPER_PROJECT_API_VERSION,
        .template_id = "developer.template.c23-static-library",
        .title = "C23 Static Library",
        .description = "Reusable C23 static library with public headers and focused test.",
        .kind = UMI_DEVELOPER_PROJECT_STATIC_LIBRARY,
        .build_system = UMI_DEVELOPER_PROJECT_BUILD_CMAKE,
        .primary_language_id = "developer.language.c23",
        .secondary_language_ids = NULL,
        .secondary_language_count = 0U,
        .recommended_frontends = 1U,
        .files = FILES,
        .file_count = sizeof(FILES) / sizeof(FILES[0]),
        .thin_application = 0,
        .supports_tests = 1,
        .supports_install = 1,
        .supports_package = 1
    };

    return &project_template;
}
