/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/developer_project/templates/c23_console.c
 *
 * PURPOSE:
 *   Define the complete C23 Console Application starter recipe. Generated source remains
 *   product-specific while reusable lifecycle/platform behaviour stays in
 *   Umicom Framework.
 *
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
#include "umicom/developer_project/templates/c23_console.h"

static const UmiDeveloperProjectTemplateFile FILES[] = {
    {
        "CMakeLists.txt",
        "#-----------------------------------------------------------------------------\n# {{APPLICATION_NAME}}\n# Generated by Umicom Framework project templates.\n# Author: Sammy Hegab\n# Organisation: Umicom Foundation\n# Licence: MIT\n#-----------------------------------------------------------------------------\ncmake_minimum_required(VERSION 3.24)\nproject({{TARGET_NAME}} VERSION 0.1.0 LANGUAGES C)\nset(CMAKE_C_STANDARD 23)\nset(CMAKE_C_STANDARD_REQUIRED ON)\nset(CMAKE_C_EXTENSIONS OFF)\nset(CMAKE_RUNTIME_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/bin\")\nset(CMAKE_LIBRARY_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/lib\")\nset(CMAKE_ARCHIVE_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/lib\")\n\ninclude(CTest)\nadd_executable({{TARGET_NAME}} src/main.c)\ntarget_compile_options({{TARGET_NAME}} PRIVATE -Wall -Wextra -Wpedantic)\ninstall(TARGETS {{TARGET_NAME}} RUNTIME DESTINATION bin)\nif(BUILD_TESTING)\n    add_executable({{TARGET_NAME}}-test tests/test_main.c)\n    add_test(NAME {{TARGET_NAME}}.smoke COMMAND {{TARGET_NAME}}-test)\nendif()\nset(CPACK_GENERATOR \"ZIP\")\ninclude(CPack)\n",
        0,
        0
    },
    {
        "CMakePresets.json",
        "{\n  \"version\": 6,\n  \"configurePresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"displayName\": \"Windows MSYS2 UCRT64 Debug\",\n      \"generator\": \"Ninja\",\n      \"binaryDir\": \"${sourceDir}/build/windows-ucrt64-debug\",\n      \"cacheVariables\": {\n        \"CMAKE_BUILD_TYPE\": \"Debug\",\n        \"CMAKE_C_COMPILER\": \"C:/msys64/ucrt64/bin/gcc.exe\",\n        \"CMAKE_MAKE_PROGRAM\": \"C:/msys64/ucrt64/bin/ninja.exe\",\n        \"BUILD_TESTING\": \"ON\"\n      }\n    }\n  ],\n  \"buildPresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"configurePreset\": \"windows-ucrt64-debug\"\n    }\n  ],\n  \"testPresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"configurePreset\": \"windows-ucrt64-debug\",\n      \"output\": {\n        \"outputOnFailure\": true\n      }\n    }\n  ]\n}\n",
        0,
        0
    },
    {
        "src/main.c",
        "/*-----------------------------------------------------------------------------\n * {{APPLICATION_NAME}}\n *\n * Generated from the Umicom Framework project platform.\n * Author: Sammy Hegab\n * Organisation: Umicom Foundation\n * Licence: MIT\n *---------------------------------------------------------------------------*/\n\n#include <stdio.h>\n\nint main(void)\n{\n    (void)puts(\"{{APPLICATION_NAME}}\");\n    return 0;\n}\n",
        0,
        0
    },
    {
        "tests/test_main.c",
        "/*-----------------------------------------------------------------------------\n * {{APPLICATION_NAME}}\n *\n * Generated from the Umicom Framework project platform.\n * Author: Sammy Hegab\n * Organisation: Umicom Foundation\n * Licence: MIT\n *---------------------------------------------------------------------------*/\n\n#include <assert.h>\n\nint main(void)\n{\n    assert(1);\n    return 0;\n}\n",
        0,
        0
    },
    {
        "README.md",
        "# {{APPLICATION_NAME}}\n\nGenerated from the Umicom Framework project platform.\n\nThis starter keeps reusable behaviour in **Umicom Framework** and limits the\nproduct repository to product-specific composition, branding and business logic.\n\n## Build on Windows\n\n```powershell\n$env:Path = \"C:/msys64/ucrt64/bin;$env:Path\"\ncmake --preset windows-ucrt64-debug\ncmake --build --preset windows-ucrt64-debug --parallel 2\nctest --preset windows-ucrt64-debug\n```\n",
        0,
        0
    },
    {
        ".gitignore",
        "build/\ninstall/\ndist/\n*.o\n*.obj\n*.exe\n*.dll\n*.so\n*.dylib\n",
        0,
        0
    },
    {
        "application.umicom.yaml",
        "schema: umicom.application/v1\nid: {{APPLICATION_ID}}\nname: {{APPLICATION_NAME}}\nshort_name: {{TARGET_NAME}}\nversion: 0.1.0\nexecutable: {{TARGET_NAME}}\nminimum_framework_version: 0.9.0\nfrontends:\n  - console\ncapabilities:\n  - umicom.runtime\n  - umicom.application\n",
        0,
        0
    }
};

const UmiDeveloperProjectTemplate *umi_developer_project_template_c23_console(void)
{
    static const UmiDeveloperProjectTemplate project_template = {
        .structure_size = (uint32_t)sizeof(UmiDeveloperProjectTemplate),
        .api_version = UMI_DEVELOPER_PROJECT_API_VERSION,
        .template_id = "developer.template.c23-console",
        .title = "C23 Console Application",
        .description = "Native C23 console application with CMake/Ninja, tests, install and CPack.",
        .kind = UMI_DEVELOPER_PROJECT_EXECUTABLE,
        .build_system = UMI_DEVELOPER_PROJECT_BUILD_CMAKE,
        .primary_language_id = "developer.language.c23",
        .secondary_language_ids = NULL,
        .secondary_language_count = 0U,
        .recommended_frontends = 1U,
        .files = FILES,
        .file_count = sizeof(FILES) / sizeof(FILES[0]),
        .thin_application = 0,
        .supports_tests = 1,
        .supports_install = 1,
        .supports_package = 1
    };

    return &project_template;
}
