/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/developer_project/templates/c23_gtk4.c
 *
 * PURPOSE:
 *   Define the complete C23 GTK4 Application starter recipe. Generated source remains
 *   product-specific while reusable lifecycle/platform behaviour stays in
 *   Umicom Framework.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
#include "umicom/developer_project/templates/c23_gtk4.h"

static const UmiDeveloperProjectTemplateFile FILES[] = {
    {
        "CMakeLists.txt",
        "#-----------------------------------------------------------------------------\n# {{APPLICATION_NAME}}\n# Generated by Umicom Framework project templates.\n# Author: Sammy Hegab\n# Organisation: Umicom Foundation\n# Licence: MIT\n#-----------------------------------------------------------------------------\ncmake_minimum_required(VERSION 3.24)\nproject({{TARGET_NAME}} VERSION 0.1.0 LANGUAGES C)\nset(CMAKE_C_STANDARD 23)\nset(CMAKE_C_STANDARD_REQUIRED ON)\nset(CMAKE_C_EXTENSIONS OFF)\nset(CMAKE_RUNTIME_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/bin\")\nset(CMAKE_LIBRARY_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/lib\")\nset(CMAKE_ARCHIVE_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/lib\")\n\nfind_package(PkgConfig REQUIRED)\npkg_check_modules(GTK4 REQUIRED IMPORTED_TARGET gtk4>=4.10)\ninclude(CTest)\nadd_executable({{TARGET_NAME}} src/main.c)\ntarget_link_libraries({{TARGET_NAME}} PRIVATE PkgConfig::GTK4)\ntarget_compile_options({{TARGET_NAME}} PRIVATE -Wall -Wextra -Wpedantic)\ninstall(TARGETS {{TARGET_NAME}} RUNTIME DESTINATION bin)\nset(CPACK_GENERATOR \"ZIP\")\ninclude(CPack)\n",
        0,
        0
    },
    {
        "CMakePresets.json",
        "{\n  \"version\": 6,\n  \"configurePresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"displayName\": \"Windows MSYS2 UCRT64 Debug\",\n      \"generator\": \"Ninja\",\n      \"binaryDir\": \"${sourceDir}/build/windows-ucrt64-debug\",\n      \"cacheVariables\": {\n        \"CMAKE_BUILD_TYPE\": \"Debug\",\n        \"CMAKE_C_COMPILER\": \"C:/msys64/ucrt64/bin/gcc.exe\",\n        \"CMAKE_MAKE_PROGRAM\": \"C:/msys64/ucrt64/bin/ninja.exe\",\n        \"BUILD_TESTING\": \"ON\"\n      }\n    }\n  ],\n  \"buildPresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"configurePreset\": \"windows-ucrt64-debug\"\n    }\n  ],\n  \"testPresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"configurePreset\": \"windows-ucrt64-debug\",\n      \"output\": {\n        \"outputOnFailure\": true\n      }\n    }\n  ]\n}\n",
        0,
        0
    },
    {
        "src/main.c",
        "/*-----------------------------------------------------------------------------\n * {{APPLICATION_NAME}}\n *\n * Generated from the Umicom Framework project platform.\n * Author: Sammy Hegab\n * Organisation: Umicom Foundation\n * Licence: MIT\n *---------------------------------------------------------------------------*/\n\n#include <gtk/gtk.h>\n\nstatic void activate(GtkApplication *application, gpointer user_data)\n{\n    GtkWidget *window;\n    GtkWidget *label;\n\n    (void)user_data;\n\n    window = gtk_application_window_new(application);\n    gtk_window_set_title(GTK_WINDOW(window), \"{{APPLICATION_NAME}}\");\n    gtk_window_set_default_size(GTK_WINDOW(window), 960, 640);\n\n    label = gtk_label_new(\"{{APPLICATION_NAME}}\");\n    gtk_window_set_child(GTK_WINDOW(window), label);\n    gtk_window_present(GTK_WINDOW(window));\n}\n\nint main(int argc, char **argv)\n{\n    GtkApplication *application;\n    int status;\n\n    application = gtk_application_new(\n        \"{{APPLICATION_ID}}\",\n        G_APPLICATION_DEFAULT_FLAGS);\n    g_signal_connect(application, \"activate\", G_CALLBACK(activate), NULL);\n    status = g_application_run(G_APPLICATION(application), argc, argv);\n    g_object_unref(application);\n    return status;\n}\n",
        0,
        0
    },
    {
        "README.md",
        "# {{APPLICATION_NAME}}\n\nGenerated from the Umicom Framework project platform.\n\nThis starter keeps reusable behaviour in **Umicom Framework** and limits the\nproduct repository to product-specific composition, branding and business logic.\n\n## Build on Windows\n\n```powershell\n$env:Path = \"C:/msys64/ucrt64/bin;$env:Path\"\ncmake --preset windows-ucrt64-debug\ncmake --build --preset windows-ucrt64-debug --parallel 2\nctest --preset windows-ucrt64-debug\n```\n",
        0,
        0
    },
    {
        ".gitignore",
        "build/\ninstall/\ndist/\n*.o\n*.obj\n*.exe\n*.dll\n*.so\n*.dylib\n",
        0,
        0
    },
    {
        "application.umicom.yaml",
        "schema: umicom.application/v1\nid: {{APPLICATION_ID}}\nname: {{APPLICATION_NAME}}\nshort_name: {{TARGET_NAME}}\nversion: 0.1.0\nexecutable: {{TARGET_NAME}}\nminimum_framework_version: 0.9.0\nfrontends:\n  - console\n  - gtk4\ncapabilities:\n  - umicom.runtime\n  - umicom.application\n",
        0,
        0
    }
};

const UmiDeveloperProjectTemplate *umi_developer_project_template_c23_gtk4(void)
{
    static const UmiDeveloperProjectTemplate project_template = {
        .structure_size = (uint32_t)sizeof(UmiDeveloperProjectTemplate),
        .api_version = UMI_DEVELOPER_PROJECT_API_VERSION,
        .template_id = "developer.template.c23-gtk4",
        .title = "C23 GTK4 Application",
        .description = "GTK4 desktop application in C23 using pkg-config and the canonical UCRT64 workflow.",
        .kind = UMI_DEVELOPER_PROJECT_EXECUTABLE,
        .build_system = UMI_DEVELOPER_PROJECT_BUILD_CMAKE,
        .primary_language_id = "developer.language.c23",
        .secondary_language_ids = NULL,
        .secondary_language_count = 0U,
        .recommended_frontends = 3U,
        .files = FILES,
        .file_count = sizeof(FILES) / sizeof(FILES[0]),
        .thin_application = 0,
        .supports_tests = 1,
        .supports_install = 1,
        .supports_package = 1
    };

    return &project_template;
}
