/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/developer_project/templates/cpython_extension.c
 *
 * PURPOSE:
 *   Define the complete CPython Native Extension starter recipe. Generated source remains
 *   product-specific while reusable lifecycle/platform behaviour stays in
 *   Umicom Framework.
 *
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
#include "umicom/developer_project/templates/cpython_extension.h"

static const char *const SECONDARY_LANGUAGES[] = {
    "developer.language.cpython"
};

static const UmiDeveloperProjectTemplateFile FILES[] = {
    {
        "CMakeLists.txt",
        "#-----------------------------------------------------------------------------\n# {{APPLICATION_NAME}}\n# Generated by Umicom Framework project templates.\n# Author: Sammy Hegab\n# Organisation: Umicom Foundation\n# Licence: MIT\n#-----------------------------------------------------------------------------\ncmake_minimum_required(VERSION 3.24)\nproject({{TARGET_NAME}} VERSION 0.1.0 LANGUAGES C)\nset(CMAKE_C_STANDARD 23)\nset(CMAKE_C_STANDARD_REQUIRED ON)\nset(CMAKE_C_EXTENSIONS OFF)\nset(CMAKE_RUNTIME_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/bin\")\nset(CMAKE_LIBRARY_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/lib\")\nset(CMAKE_ARCHIVE_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/lib\")\n\nfind_package(Python3 REQUIRED COMPONENTS Interpreter Development.Module)\nadd_library({{TARGET_NAME}} MODULE src/module.c)\ntarget_link_libraries({{TARGET_NAME}} PRIVATE Python3::Module)\nset_target_properties({{TARGET_NAME}} PROPERTIES PREFIX \"\")\n",
        0,
        0
    },
    {
        "CMakePresets.json",
        "{\n  \"version\": 6,\n  \"configurePresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"displayName\": \"Windows MSYS2 UCRT64 Debug\",\n      \"generator\": \"Ninja\",\n      \"binaryDir\": \"${sourceDir}/build/windows-ucrt64-debug\",\n      \"cacheVariables\": {\n        \"CMAKE_BUILD_TYPE\": \"Debug\",\n        \"CMAKE_C_COMPILER\": \"C:/msys64/ucrt64/bin/gcc.exe\",\n        \"CMAKE_MAKE_PROGRAM\": \"C:/msys64/ucrt64/bin/ninja.exe\",\n        \"BUILD_TESTING\": \"ON\"\n      }\n    }\n  ],\n  \"buildPresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"configurePreset\": \"windows-ucrt64-debug\"\n    }\n  ],\n  \"testPresets\": [\n    {\n      \"name\": \"windows-ucrt64-debug\",\n      \"configurePreset\": \"windows-ucrt64-debug\",\n      \"output\": {\n        \"outputOnFailure\": true\n      }\n    }\n  ]\n}\n",
        0,
        0
    },
    {
        "src/module.c",
        "/*-----------------------------------------------------------------------------\n * {{APPLICATION_NAME}}\n *\n * Generated from the Umicom Framework project platform.\n * Author: Sammy Hegab\n * Organisation: Umicom Foundation\n * Licence: MIT\n *---------------------------------------------------------------------------*/\n\n#define PY_SSIZE_T_CLEAN\n#include <Python.h>\n\nstatic PyObject *hello(PyObject *self, PyObject *args)\n{\n    (void)self;\n    (void)args;\n    return PyUnicode_FromString(\"{{APPLICATION_NAME}}\");\n}\n\nstatic PyMethodDef methods[] = {\n    {\"hello\", hello, METH_NOARGS, \"Return the generated application name.\"},\n    {NULL, NULL, 0, NULL}\n};\n\nstatic struct PyModuleDef module = {\n    PyModuleDef_HEAD_INIT,\n    \"{{TARGET_NAME}}\",\n    \"Generated Umicom CPython extension.\",\n    -1,\n    methods\n};\n\nPyMODINIT_FUNC PyInit_{{TARGET_NAME}}(void)\n{\n    return PyModule_Create(&module);\n}\n",
        0,
        0
    },
    {
        "README.md",
        "# {{APPLICATION_NAME}}\n\nGenerated from the Umicom Framework project platform.\n\nThis starter keeps reusable behaviour in **Umicom Framework** and limits the\nproduct repository to product-specific composition, branding and business logic.\n\n## Build on Windows\n\n```powershell\n$env:Path = \"C:/msys64/ucrt64/bin;$env:Path\"\ncmake --preset windows-ucrt64-debug\ncmake --build --preset windows-ucrt64-debug --parallel 2\nctest --preset windows-ucrt64-debug\n```\n",
        0,
        0
    },
    {
        ".gitignore",
        "build/\ninstall/\ndist/\n*.o\n*.obj\n*.exe\n*.dll\n*.so\n*.dylib\n",
        0,
        0
    }
};

const UmiDeveloperProjectTemplate *umi_developer_project_template_cpython_extension(void)
{
    static const UmiDeveloperProjectTemplate project_template = {
        .structure_size = (uint32_t)sizeof(UmiDeveloperProjectTemplate),
        .api_version = UMI_DEVELOPER_PROJECT_API_VERSION,
        .template_id = "developer.template.cpython-extension",
        .title = "CPython Native Extension",
        .description = "C23 CPython extension module with CMake and Python discovery.",
        .kind = UMI_DEVELOPER_PROJECT_EXTENSION,
        .build_system = UMI_DEVELOPER_PROJECT_BUILD_CMAKE,
        .primary_language_id = "developer.language.c23",
        .secondary_language_ids = SECONDARY_LANGUAGES,
        .secondary_language_count = sizeof(SECONDARY_LANGUAGES) / sizeof(SECONDARY_LANGUAGES[0]),
        .recommended_frontends = 1U,
        .files = FILES,
        .file_count = sizeof(FILES) / sizeof(FILES[0]),
        .thin_application = 0,
        .supports_tests = 1,
        .supports_install = 1,
        .supports_package = 1
    };

    return &project_template;
}
