/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/developer_project/templates/python_tool.c
 *
 * PURPOSE:
 *   Define the complete Python Tool starter recipe. Generated source remains
 *   product-specific while reusable lifecycle/platform behaviour stays in
 *   Umicom Framework.
 *
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
#include "umicom/developer_project/templates/python_tool.h"

static const UmiDeveloperProjectTemplateFile FILES[] = {
    {
        "src/{{TARGET_NAME}}.py",
        "# {{APPLICATION_NAME}}\n# Generated by Umicom Framework.\n# Author: Sammy Hegab\n# Organisation: Umicom Foundation\n# Licence: MIT\n\ndef main() -> int:\n    print(\"{{APPLICATION_NAME}}\")\n    return 0\n\nif __name__ == \"__main__\":\n    raise SystemExit(main())\n",
        0,
        0
    },
    {
        "tests/test_{{TARGET_NAME}}.py",
        "# Generated by Umicom Framework.\n# Author: Sammy Hegab\n# Organisation: Umicom Foundation\n# Licence: MIT\n\ndef test_placeholder() -> None:\n    assert True\n",
        0,
        0
    },
    {
        "README.md",
        "# {{APPLICATION_NAME}}\n\nGenerated from the Umicom Framework project platform.\n\nThis starter keeps reusable behaviour in **Umicom Framework** and limits the\nproduct repository to product-specific composition, branding and business logic.\n\n## Build on Windows\n\n```powershell\n$env:Path = \"C:/msys64/ucrt64/bin;$env:Path\"\ncmake --preset windows-ucrt64-debug\ncmake --build --preset windows-ucrt64-debug --parallel 2\nctest --preset windows-ucrt64-debug\n```\n",
        0,
        0
    },
    {
        ".gitignore",
        "build/\ninstall/\ndist/\n*.o\n*.obj\n*.exe\n*.dll\n*.so\n*.dylib\n\n__pycache__/\n.venv/\n",
        0,
        0
    }
};

const UmiDeveloperProjectTemplate *umi_developer_project_template_python_tool(void)
{
    static const UmiDeveloperProjectTemplate project_template = {
        .structure_size = (uint32_t)sizeof(UmiDeveloperProjectTemplate),
        .api_version = UMI_DEVELOPER_PROJECT_API_VERSION,
        .template_id = "developer.template.python-tool",
        .title = "Python Tool",
        .description = "CPython script application with a conventional src/test layout.",
        .kind = UMI_DEVELOPER_PROJECT_SCRIPT,
        .build_system = UMI_DEVELOPER_PROJECT_BUILD_SCRIPT,
        .primary_language_id = "developer.language.cpython",
        .secondary_language_ids = NULL,
        .secondary_language_count = 0U,
        .recommended_frontends = 1U,
        .files = FILES,
        .file_count = sizeof(FILES) / sizeof(FILES[0]),
        .thin_application = 0,
        .supports_tests = 1,
        .supports_install = 0,
        .supports_package = 0
    };

    return &project_template;
}
