/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/developer_project/templates/rust_console.c
 *
 * PURPOSE:
 *   Define the complete Rust Console Application starter recipe. Generated source remains
 *   product-specific while reusable lifecycle/platform behaviour stays in
 *   Umicom Framework.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
#include "umicom/developer_project/templates/rust_console.h"

static const UmiDeveloperProjectTemplateFile FILES[] = {
    {
        "Cargo.toml",
        "[package]\nname = \"{{TARGET_NAME}}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[dependencies]\n",
        0,
        0
    },
    {
        "src/main.rs",
        "// {{APPLICATION_NAME}}\n// Generated by Umicom Framework.\n// Author: Sammy Hegab\n// Organisation: Umicom Foundation\n// Licence: MIT\n\nfn main() {\n    println!(\"{{APPLICATION_NAME}}\");\n}\n",
        0,
        0
    },
    {
        "README.md",
        "# {{APPLICATION_NAME}}\n\nGenerated from the Umicom Framework project platform.\n\nThis starter keeps reusable behaviour in **Umicom Framework** and limits the\nproduct repository to product-specific composition, branding and business logic.\n\n## Build on Windows\n\n```powershell\n$env:Path = \"C:/msys64/ucrt64/bin;$env:Path\"\ncmake --preset windows-ucrt64-debug\ncmake --build --preset windows-ucrt64-debug --parallel 2\nctest --preset windows-ucrt64-debug\n```\n",
        0,
        0
    },
    {
        ".gitignore",
        "build/\ninstall/\ndist/\n*.o\n*.obj\n*.exe\n*.dll\n*.so\n*.dylib\n",
        0,
        0
    }
};

const UmiDeveloperProjectTemplate *umi_developer_project_template_rust_console(void)
{
    static const UmiDeveloperProjectTemplate project_template = {
        .structure_size = (uint32_t)sizeof(UmiDeveloperProjectTemplate),
        .api_version = UMI_DEVELOPER_PROJECT_API_VERSION,
        .template_id = "developer.template.rust-console",
        .title = "Rust Console Application",
        .description = "Native Rust project with Cargo build/test/run workflow.",
        .kind = UMI_DEVELOPER_PROJECT_EXECUTABLE,
        .build_system = UMI_DEVELOPER_PROJECT_BUILD_CARGO,
        .primary_language_id = "developer.language.rust",
        .secondary_language_ids = NULL,
        .secondary_language_count = 0U,
        .recommended_frontends = 1U,
        .files = FILES,
        .file_count = sizeof(FILES) / sizeof(FILES[0]),
        .thin_application = 0,
        .supports_tests = 1,
        .supports_install = 0,
        .supports_package = 1
    };

    return &project_template;
}
