/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/developer_project/templates/zig_console.c
 *
 * PURPOSE:
 *   Define the complete Zig Console Application starter recipe. Generated source remains
 *   product-specific while reusable lifecycle/platform behaviour stays in
 *   Umicom Framework.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
#include "umicom/developer_project/templates/zig_console.h"

static const UmiDeveloperProjectTemplateFile FILES[] = {
    {
        "build.zig",
        "const std = @import(\"std\");\n\npub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    const optimize = b.standardOptimizeOption(.{});\n    const exe = b.addExecutable(.{\n        .name = \"{{TARGET_NAME}}\",\n        .root_module = b.createModule(.{\n            .root_source_file = b.path(\"src/main.zig\"),\n            .target = target,\n            .optimize = optimize,\n        }),\n    });\n    b.installArtifact(exe);\n    const run_cmd = b.addRunArtifact(exe);\n    const run_step = b.step(\"run\", \"Run the application\");\n    run_step.dependOn(&run_cmd.step);\n}\n",
        0,
        0
    },
    {
        "src/main.zig",
        "// {{APPLICATION_NAME}}\n// Generated by Umicom Framework.\n// Author: Sammy Hegab\n// Organisation: Umicom Foundation\n// Licence: MIT\nconst std = @import(\"std\");\n\npub fn main() !void {\n    std.debug.print(\"{{APPLICATION_NAME}}\\n\", .{});\n}\n",
        0,
        0
    },
    {
        "README.md",
        "# {{APPLICATION_NAME}}\n\nGenerated from the Umicom Framework project platform.\n\nThis starter keeps reusable behaviour in **Umicom Framework** and limits the\nproduct repository to product-specific composition, branding and business logic.\n\n## Build on Windows\n\n```powershell\n$env:Path = \"C:/msys64/ucrt64/bin;$env:Path\"\ncmake --preset windows-ucrt64-debug\ncmake --build --preset windows-ucrt64-debug --parallel 2\nctest --preset windows-ucrt64-debug\n```\n",
        0,
        0
    },
    {
        ".gitignore",
        "build/\ninstall/\ndist/\n*.o\n*.obj\n*.exe\n*.dll\n*.so\n*.dylib\n",
        0,
        0
    }
};

/*
 * Provide the developer project template zig console operation used by this module and its
 * client applications.
 */
const UmiDeveloperProjectTemplate *umi_developer_project_template_zig_console(void)
{
    static const UmiDeveloperProjectTemplate project_template = {
        .structure_size = (uint32_t)sizeof(UmiDeveloperProjectTemplate),
        .api_version = UMI_DEVELOPER_PROJECT_API_VERSION,
        .template_id = "developer.template.zig-console",
        .title = "Zig Console Application",
        .description = "Native Zig project with standard zig build/run/test workflow.",
        .kind = UMI_DEVELOPER_PROJECT_EXECUTABLE,
        .build_system = UMI_DEVELOPER_PROJECT_BUILD_ZIG,
        .primary_language_id = "developer.language.zig",
        .secondary_language_ids = NULL,
        .secondary_language_count = 0U,
        .recommended_frontends = 1U,
        .files = FILES,
        .file_count = sizeof(FILES) / sizeof(FILES[0]),
        .thin_application = 0,
        .supports_tests = 1,
        .supports_install = 0,
        .supports_package = 1
    };

    return &project_template;
}
