/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: include/umicom/broker_connectivity/broker_connectivity.h
 *
 * PURPOSE:
 *   Aggregate provider-neutral paper/live broker connectivity, IBKR boundary,
 *   pre-trade risk, reconciliation and execution audit contracts.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
#ifndef UMICOM_BROKER_CONNECTIVITY_H
#define UMICOM_BROKER_CONNECTIVITY_H

#include "umicom/broker_connectivity/types.h"
#include "umicom/broker_connectivity/service.h"
#include "umicom/broker_connectivity/provider_registry.h"
#include "umicom/broker_connectivity/session_supervisor.h"
#include "umicom/broker_connectivity/account_store.h"
#include "umicom/broker_connectivity/order_journal.h"
#include "umicom/broker_connectivity/execution_reconciler.h"
#include "umicom/broker_connectivity/position_store.h"
#include "umicom/broker_connectivity/pretrade_guard.h"
#include "umicom/broker_connectivity/audit_journal.h"
#include "umicom/broker_connectivity/ibkr_adapter.h"
#include "umicom/broker_connectivity/paper_runtime.h"
#include "umicom/broker_connectivity/account/buying_power.h"
#include "umicom/broker_connectivity/account/cash.h"
#include "umicom/broker_connectivity/account/currency_mapping.h"
#include "umicom/broker_connectivity/account/daily_pnl.h"
#include "umicom/broker_connectivity/account/margin_utilisation.h"
#include "umicom/broker_connectivity/account/net_liquidation.h"
#include "umicom/broker_connectivity/account/realised_pnl.h"
#include "umicom/broker_connectivity/account/reconciliation.h"
#include "umicom/broker_connectivity/account/sync.h"
#include "umicom/broker_connectivity/account/unrealised_pnl.h"
#include "umicom/broker_connectivity/audit/causation.h"
#include "umicom/broker_connectivity/audit/correction.h"
#include "umicom/broker_connectivity/audit/gap.h"
#include "umicom/broker_connectivity/audit/integrity.h"
#include "umicom/broker_connectivity/audit/persistence.h"
#include "umicom/broker_connectivity/audit/readiness.h"
#include "umicom/broker_connectivity/audit/rejection.h"
#include "umicom/broker_connectivity/audit/sequence.h"
#include "umicom/broker_connectivity/audit/source.h"
#include "umicom/broker_connectivity/audit/timestamp.h"
#include "umicom/broker_connectivity/execution/audit.h"
#include "umicom/broker_connectivity/execution/average_price.h"
#include "umicom/broker_connectivity/execution/commission.h"
#include "umicom/broker_connectivity/execution/correction.h"
#include "umicom/broker_connectivity/execution/duplicate_detection.h"
#include "umicom/broker_connectivity/execution/fill_progress.h"
#include "umicom/broker_connectivity/execution/late_detection.h"
#include "umicom/broker_connectivity/execution/quality.h"
#include "umicom/broker_connectivity/execution/reconciliation.h"
#include "umicom/broker_connectivity/execution/slippage.h"
#include "umicom/broker_connectivity/ibkr/account_mapping.h"
#include "umicom/broker_connectivity/ibkr/client_id.h"
#include "umicom/broker_connectivity/ibkr/configuration.h"
#include "umicom/broker_connectivity/ibkr/contract_mapping.h"
#include "umicom/broker_connectivity/ibkr/error_mapping.h"
#include "umicom/broker_connectivity/ibkr/execution_mapping.h"
#include "umicom/broker_connectivity/ibkr/heartbeat.h"
#include "umicom/broker_connectivity/ibkr/order_mapping.h"
#include "umicom/broker_connectivity/ibkr/status_mapping.h"
#include "umicom/broker_connectivity/ibkr/transport.h"
#include "umicom/broker_connectivity/order/ack_latency.h"
#include "umicom/broker_connectivity/order/cancel_gate.h"
#include "umicom/broker_connectivity/order/idempotency.h"
#include "umicom/broker_connectivity/order/mapping.h"
#include "umicom/broker_connectivity/order/reject_attention.h"
#include "umicom/broker_connectivity/order/replace_gate.h"
#include "umicom/broker_connectivity/order/route_readiness.h"
#include "umicom/broker_connectivity/order/state_sync.h"
#include "umicom/broker_connectivity/order/submit_gate.h"
#include "umicom/broker_connectivity/order/working_notional.h"
#include "umicom/broker_connectivity/position/average_cost.h"
#include "umicom/broker_connectivity/position/concentration.h"
#include "umicom/broker_connectivity/position/freshness.h"
#include "umicom/broker_connectivity/position/gross_exposure.h"
#include "umicom/broker_connectivity/position/market_value.h"
#include "umicom/broker_connectivity/position/net_exposure.h"
#include "umicom/broker_connectivity/position/quantity.h"
#include "umicom/broker_connectivity/position/realised_pnl.h"
#include "umicom/broker_connectivity/position/reconciliation.h"
#include "umicom/broker_connectivity/position/unrealised_pnl.h"
#include "umicom/broker_connectivity/provider/authentication.h"
#include "umicom/broker_connectivity/provider/capabilities.h"
#include "umicom/broker_connectivity/provider/connection.h"
#include "umicom/broker_connectivity/provider/contract.h"
#include "umicom/broker_connectivity/provider/health.h"
#include "umicom/broker_connectivity/provider/heartbeat.h"
#include "umicom/broker_connectivity/provider/latency.h"
#include "umicom/broker_connectivity/provider/live_mode.h"
#include "umicom/broker_connectivity/provider/paper_mode.h"
#include "umicom/broker_connectivity/provider/reconnect.h"
#include "umicom/broker_connectivity/risk/buying_power.h"
#include "umicom/broker_connectivity/risk/concentration.h"
#include "umicom/broker_connectivity/risk/daily_loss.h"
#include "umicom/broker_connectivity/risk/kill_switch.h"
#include "umicom/broker_connectivity/risk/leverage.h"
#include "umicom/broker_connectivity/risk/order_notional.h"
#include "umicom/broker_connectivity/risk/order_quantity.h"
#include "umicom/broker_connectivity/risk/position_quantity.h"
#include "umicom/broker_connectivity/risk/pretrade_readiness.h"
#include "umicom/broker_connectivity/risk/price_band.h"

#endif
