#-----------------------------------------------------------------------------
# Umicom Framework
# File: tests/library_link/check_symbol_verifier.cmake
# PURPOSE: Test the archive inspector with intentionally incomplete libraries.
#          These fixture functions are not substitutes for Framework services.
# AUTHOR AND ORGANISATION: Sammy Hegab, Umicom Foundation
# LICENCE: MIT
#-----------------------------------------------------------------------------
cmake_minimum_required(VERSION 3.24)
foreach(arg CASE ROOT CHECKER CC NM GENERATOR)
    if(NOT DEFINED ${arg})
        message(FATAL_ERROR "Missing test argument: ${arg}")
    endif()
endforeach()
# Configure the real source-membership helper with a small, isolated target
# graph. No product implementation is replaced or tested by this fixture.
if(CASE MATCHES "^registration-")
    set(folder "${ROOT}/${CASE}/registration")
    file(MAKE_DIRECTORY "${folder}/src/document" "${folder}/src/ui")
    file(WRITE "${folder}/src/document/save_session.c" "int FixtureSave(void) { return 0; }\n")
    file(WRITE "${folder}/src/ui/workbench.c" "int FixtureWorkbench(void) { return 0; }\n")
    if(NOT CASE STREQUAL "registration-missing-file")
        file(WRITE "${folder}/src/document/close_session.c" "int FixtureClose(void) { return 0; }\n")
    endif()
    set(closeSource "src/document/close_session.c")
    set(expected "")
    if(CASE STREQUAL "registration-missing-entry")
        set(closeSource "")
        set(expected "does not compile src/document/close_session.c")
    elseif(CASE STREQUAL "registration-missing-file")
        set(expected "Required source is missing:")
    elseif(NOT CASE STREQUAL "registration-complete")
        message(FATAL_ERROR "Unknown registration test: ${CASE}")
    endif()
    get_filename_component(helperDirectory "${CHECKER}" DIRECTORY)
    file(WRITE "${folder}/CMakeLists.txt"
        "cmake_minimum_required(VERSION 3.24)\nproject(RegistrationFixture C)\n"
        "add_library(umicom_document STATIC src/document/save_session.c ${closeSource})\n"
        "add_library(umicom_ui STATIC src/ui/workbench.c)\n"
        "include(\"${helperDirectory}/UmicomLibraryLinkChecks.cmake\")\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${folder}" -B "${folder}/build"
        -G "${GENERATOR}" "-DCMAKE_C_COMPILER=${CC}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 45)
    file(WRITE "${folder}/configure.log" "${output}\n${error}")
    if(expected STREQUAL "")
        if(NOT result STREQUAL "0")
            message(FATAL_ERROR "Complete registration rejected: ${output}\n${error}")
        endif()
    else()
        string(FIND "${output}\n${error}" "${expected}" found)
        if(result STREQUAL "0" OR found LESS 0)
            message(FATAL_ERROR "Expected registration rejection '${expected}', got ${result}: ${output}\n${error}")
        endif()
    endif()
    message(STATUS "Source registration case passed: ${CASE}")
    return()
endif()

set(folder "${ROOT}/${CASE}/fixture")
if(CASE STREQUAL "path-spaces")
    set(folder "${ROOT}/${CASE}/fixture with spaces")
endif()
file(MAKE_DIRECTORY "${folder}")
set(code "int UmiExpected(void) { return 3; }\n")
set(second "int UmiOther(void) { return 4; }\n")
set(manifest "# Example required function\nUmiExpected\n")
set(expected "")
if(CASE STREQUAL "complete" OR CASE STREQUAL "path-spaces")
elseif(CASE STREQUAL "missing")
    set(code "int UmiExpectedExtra(void) { return 3; }\n")
    set(expected "MISSING_SYMBOL: UmiExpected")
elseif(CASE STREQUAL "undefined")
    set(code "extern int UmiExpected(void); int Caller(void) { return UmiExpected(); }\n")
    set(expected "MISSING_SYMBOL: UmiExpected")
elseif(CASE STREQUAL "duplicate")
    set(second "int UmiExpected(void) { return 4; }\n")
    set(expected "DUPLICATE_DEFINITION: UmiExpected")
elseif(CASE STREQUAL "data-symbol")
    set(code "int UmiExpected = 3;\n")
    set(expected "NON_CODE_SYMBOL: UmiExpected")
elseif(CASE STREQUAL "empty-manifest")
    set(manifest "# No required functions\n")
    set(expected "EMPTY_MANIFEST")
elseif(CASE STREQUAL "duplicate-manifest")
    set(manifest "UmiExpected\nUmiExpected\n")
    set(expected "DUPLICATE_MANIFEST_SYMBOL")
elseif(CASE STREQUAL "invalid-manifest")
    set(manifest "UmiExpected()\n")
    set(expected "INVALID_MANIFEST")
elseif(CASE STREQUAL "missing-archive")
    set(expected "MISSING_ARCHIVE")
elseif(CASE STREQUAL "report-alias")
    set(expected "REPORT_INPUT_ALIAS")
elseif(CASE STREQUAL "empty-tool")
    set(expected "MISSING_ARGUMENT: NM_TOOL")
elseif(CASE STREQUAL "missing-tool" OR CASE STREQUAL "tool-error")
    set(expected "TOOL_FAILURE")
elseif(CASE STREQUAL "all-missing")
    set(manifest "UmiMissingOne\nUmiMissingTwo\n")
    set(expected "MISSING_SYMBOL: UmiMissingOne")
elseif(CASE STREQUAL "stale-report")
    set(expected "MISSING_SYMBOL: UmiMissingLater")
else()
    message(FATAL_ERROR "Unknown verifier case: ${CASE}")
endif()
file(WRITE "${folder}/first.c" "${code}")
file(WRITE "${folder}/second.c" "${second}")
file(WRITE "${folder}/required.symbols" "${manifest}")
file(WRITE "${folder}/CMakeLists.txt" "cmake_minimum_required(VERSION 3.24)\nproject(LinkFixture C)\nadd_library(fixture STATIC first.c second.c)\nfile(GENERATE OUTPUT \"\${CMAKE_BINARY_DIR}/archive.txt\" CONTENT \"$<TARGET_FILE:fixture>\")\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${folder}" -B "${folder}/build" -G "${GENERATOR}"
    "-DCMAKE_C_COMPILER=${CC}" RESULT_VARIABLE configured OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 45)
if(NOT configured STREQUAL "0")
    message(FATAL_ERROR "Fixture configure failed (not the expected symbol failure): ${output}\n${error}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${folder}/build" --parallel 1
    RESULT_VARIABLE built OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 45)
if(NOT built STREQUAL "0")
    message(FATAL_ERROR "Fixture build failed (not the expected symbol failure): ${output}\n${error}")
endif()
file(READ "${folder}/build/archive.txt" archive)
set(report "${folder}/result.json")
if(CASE STREQUAL "report-alias")
    set(report "${archive}")
    file(SHA256 "${archive}" originalArchiveHash)
endif()
set(tool "${NM}")
if(CASE STREQUAL "missing-archive")
    set(archive "${folder}/not-created.a")
elseif(CASE STREQUAL "empty-tool")
    set(tool "")
elseif(CASE STREQUAL "missing-tool")
    set(tool "${folder}/not-an-nm-executable")
elseif(CASE STREQUAL "tool-error")
    set(tool "${CMAKE_COMMAND}")
endif()
function(Inspect)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DARCHIVE=${archive}"
        "-DSYMBOL_FILE=${folder}/required.symbols" "-DNM_TOOL=${tool}"
        "-DREPORT=${report}" "-DALLOW_LEADING_UNDERSCORE=${ALLOW_LEADING_UNDERSCORE}"
        -P "${CHECKER}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 55)
    set(result "${result}" PARENT_SCOPE)
    set(output "${output}\n${error}" PARENT_SCOPE)
endfunction()
if(CASE STREQUAL "stale-report")
    Inspect()
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "The initial complete check did not pass: ${output}")
    endif()
    file(WRITE "${folder}/required.symbols" "UmiExpected\nUmiMissingLater\n")
endif()
Inspect()
file(WRITE "${folder}/checker.log" "${output}")
if(CASE STREQUAL "report-alias")
    file(SHA256 "${archive}" preservedArchiveHash)
    string(FIND "${output}" "REPORT_INPUT_ALIAS" found)
    if(result STREQUAL "0" OR found LESS 0 OR NOT originalArchiveHash STREQUAL preservedArchiveHash)
        message(FATAL_ERROR "Aliased report did not preserve the archive: ${output}")
    endif()
    message(STATUS "Aliased report refused without modifying its input.")
    return()
endif()
if(NOT EXISTS "${report}")
    message(FATAL_ERROR "The inspector did not create its required report: ${output}")
endif()
file(READ "${report}" json)
string(JSON state GET "${json}" state)
if(expected STREQUAL "")
    if(NOT result STREQUAL "0" OR NOT state STREQUAL "passed")
        message(FATAL_ERROR "Complete fixture rejected: ${output}")
    endif()
    string(JSON count GET "${json}" symbols 0 code_definitions)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "The report did not retain the single real definition.")
    endif()
else()
    string(FIND "${output}" "${expected}" found)
    if(result STREQUAL "0" OR NOT state STREQUAL "failed" OR found LESS 0)
        message(FATAL_ERROR "Expected '${expected}' and a failed report, got '${result}': ${output}")
    endif()
    if(CASE STREQUAL "all-missing")
        string(FIND "${output}" "MISSING_SYMBOL: UmiMissingTwo" secondMissing)
        if(secondMissing LESS 0)
            message(FATAL_ERROR "The inspector stopped before listing all missing functions.")
        endif()
    endif()
endif()
message(STATUS "Archive checker case passed: ${CASE}")
