/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/application/presentation/window_specs/mobile-studio/standard.inc
 *
 * PURPOSE:
 *   Define the portable standard window for the mobile-studio workspace.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
WINDOW_SPEC("org.umicom.workspace.mobile-studio.standard", "org.umicom.window.mobile-studio.standard",
            UMI_APPLICATION_PRESENTATION_DENSITY_BALANCED,
            UMI_APPLICATION_PRESENTATION_NAVIGATION_EXPANDED,
            1600U, 1000U, 260U, 340U, 260U,
            1, 1, 1, 1,
                 800U, 600U),
