/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/application/presentation/window_specs/ide/learning.inc
 *
 * PURPOSE:
 *   Define the portable learning window for the ide workspace.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
WINDOW_SPEC("org.umicom.workspace.ide.learning", "org.umicom.window.ide.learning",
            UMI_APPLICATION_PRESENTATION_DENSITY_COMFORTABLE,
            UMI_APPLICATION_PRESENTATION_NAVIGATION_EXPANDED,
            1760U, 1100U, 300U, 380U, 300U,
            1, 1, 1, 1,
                 960U, 640U),
