/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: include/umicom/financial_platform/financial_platform.h
 *
 * PURPOSE:
 *   Aggregate shared currencies, parties, accounts, instruments, trades,
 *   positions, payments, ledger, settlement, reconciliation, workflow and
 *   audit control-plane contracts for all financial applications.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
#ifndef UMICOM_FINANCIAL_PLATFORM_H
#define UMICOM_FINANCIAL_PLATFORM_H

#include "umicom/financial_platform/types.h"
#include "umicom/financial_platform/service.h"
#include "umicom/financial_platform/currency_rate_book.h"
#include "umicom/financial_platform/relationship_store.h"
#include "umicom/financial_platform/instrument_link_store.h"
#include "umicom/financial_platform/trade_control_book.h"
#include "umicom/financial_platform/position_control_book.h"
#include "umicom/financial_platform/payment_control_book.h"
#include "umicom/financial_platform/ledger_batch.h"
#include "umicom/financial_platform/settlement_book.h"
#include "umicom/financial_platform/reconciliation_run.h"
#include "umicom/financial_platform/workflow_instance.h"
#include "umicom/financial_platform/financial_audit_journal.h"
#include "umicom/financial_platform/financial_control_service.h"
#include "umicom/financial_platform/account/available_funds.h"
#include "umicom/financial_platform/account/balance_consistency.h"
#include "umicom/financial_platform/account/currency.h"
#include "umicom/financial_platform/account/identity.h"
#include "umicom/financial_platform/account/ownership.h"
#include "umicom/financial_platform/account/reconciliation.h"
#include "umicom/financial_platform/account/settlement.h"
#include "umicom/financial_platform/account/status.h"
#include "umicom/financial_platform/audit/actor.h"
#include "umicom/financial_platform/audit/causation.h"
#include "umicom/financial_platform/audit/immutability.h"
#include "umicom/financial_platform/audit/lineage.h"
#include "umicom/financial_platform/audit/persistence.h"
#include "umicom/financial_platform/audit/readiness.h"
#include "umicom/financial_platform/audit/sequence.h"
#include "umicom/financial_platform/audit/timestamp.h"
#include "umicom/financial_platform/currency/catalogue_coverage.h"
#include "umicom/financial_platform/currency/code_validation.h"
#include "umicom/financial_platform/currency/conversion_consistency.h"
#include "umicom/financial_platform/currency/pair_readiness.h"
#include "umicom/financial_platform/currency/precision_validation.h"
#include "umicom/financial_platform/currency/rate_freshness.h"
#include "umicom/financial_platform/currency/rate_tolerance.h"
#include "umicom/financial_platform/currency/settlement_currency.h"
#include "umicom/financial_platform/instrument/currency.h"
#include "umicom/financial_platform/instrument/identity.h"
#include "umicom/financial_platform/instrument/lifecycle.h"
#include "umicom/financial_platform/instrument/market_data.h"
#include "umicom/financial_platform/instrument/maturity.h"
#include "umicom/financial_platform/instrument/price_precision.h"
#include "umicom/financial_platform/instrument/product_mapping.h"
#include "umicom/financial_platform/instrument/settlement.h"
#include "umicom/financial_platform/ledger/account_mapping.h"
#include "umicom/financial_platform/ledger/double_entry.h"
#include "umicom/financial_platform/ledger/journal_validation.h"
#include "umicom/financial_platform/ledger/period.h"
#include "umicom/financial_platform/ledger/posting.h"
#include "umicom/financial_platform/ledger/subledger.h"
#include "umicom/financial_platform/ledger/suspense.h"
#include "umicom/financial_platform/ledger/trial_balance.h"
#include "umicom/financial_platform/party/counterparty.h"
#include "umicom/financial_platform/party/identity.h"
#include "umicom/financial_platform/party/kyc_readiness.h"
#include "umicom/financial_platform/party/legal_entity.h"
#include "umicom/financial_platform/party/lifecycle.h"
#include "umicom/financial_platform/party/ownership_consistency.h"
#include "umicom/financial_platform/party/relationship_coverage.h"
#include "umicom/financial_platform/party/role_coverage.h"
#include "umicom/financial_platform/payment/amount.h"
#include "umicom/financial_platform/payment/approval.h"
#include "umicom/financial_platform/payment/beneficiary.h"
#include "umicom/financial_platform/payment/currency.h"
#include "umicom/financial_platform/payment/cutoff.h"
#include "umicom/financial_platform/payment/instruction.h"
#include "umicom/financial_platform/payment/route.h"
#include "umicom/financial_platform/payment/settlement.h"
#include "umicom/financial_platform/position/concentration.h"
#include "umicom/financial_platform/position/currency.h"
#include "umicom/financial_platform/position/gross_exposure.h"
#include "umicom/financial_platform/position/market_value.h"
#include "umicom/financial_platform/position/net_exposure.h"
#include "umicom/financial_platform/position/pnl.h"
#include "umicom/financial_platform/position/quantity.h"
#include "umicom/financial_platform/position/reconciliation.h"
#include "umicom/financial_platform/reconciliation/ageing.h"
#include "umicom/financial_platform/reconciliation/automation.h"
#include "umicom/financial_platform/reconciliation/break_count.h"
#include "umicom/financial_platform/reconciliation/completion.h"
#include "umicom/financial_platform/reconciliation/coverage.h"
#include "umicom/financial_platform/reconciliation/exception.h"
#include "umicom/financial_platform/reconciliation/matching.h"
#include "umicom/financial_platform/reconciliation/tolerance.h"
#include "umicom/financial_platform/settlement/cash_leg.h"
#include "umicom/financial_platform/settlement/due_date.h"
#include "umicom/financial_platform/settlement/fail_age.h"
#include "umicom/financial_platform/settlement/instruction.h"
#include "umicom/financial_platform/settlement/netting.h"
#include "umicom/financial_platform/settlement/reconciliation.h"
#include "umicom/financial_platform/settlement/securities_leg.h"
#include "umicom/financial_platform/settlement/status.h"
#include "umicom/financial_platform/trade/audit_coverage.h"
#include "umicom/financial_platform/trade/counterparty.h"
#include "umicom/financial_platform/trade/economics.h"
#include "umicom/financial_platform/trade/identity.h"
#include "umicom/financial_platform/trade/lifecycle.h"
#include "umicom/financial_platform/trade/notional.h"
#include "umicom/financial_platform/trade/position_impact.h"
#include "umicom/financial_platform/trade/settlement.h"
#include "umicom/financial_platform/workflow/approval.h"
#include "umicom/financial_platform/workflow/completion.h"
#include "umicom/financial_platform/workflow/escalation.h"
#include "umicom/financial_platform/workflow/role_coverage.h"
#include "umicom/financial_platform/workflow/rollback.h"
#include "umicom/financial_platform/workflow/state_transition.h"
#include "umicom/financial_platform/workflow/task_coverage.h"
#include "umicom/financial_platform/workflow/timeout.h"

#endif
