/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: include/umicom/workbench_selection/workbench_selection.h
 *
 * PURPOSE:
 *   Expose the complete toolkit-neutral structured workbench selection platform.
 *
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
#ifndef UMICOM_WORKBENCH_SELECTION_WORKBENCH_SELECTION_H
#define UMICOM_WORKBENCH_SELECTION_WORKBENCH_SELECTION_H

#include "umicom/workbench_selection/account_item.h"
#include "umicom/workbench_selection/activation_record.h"
#include "umicom/workbench_selection/adapter_record.h"
#include "umicom/workbench_selection/ai_item.h"
#include "umicom/workbench_selection/application_binding.h"
#include "umicom/workbench_selection/application_item.h"
#include "umicom/workbench_selection/audit_record.h"
#include "umicom/workbench_selection/binding_record.h"
#include "umicom/workbench_selection/bookmark_record.h"
#include "umicom/workbench_selection/builders.h"
#include "umicom/workbench_selection/capability_record.h"
#include "umicom/workbench_selection/causation_record.h"
#include "umicom/workbench_selection/command_record.h"
#include "umicom/workbench_selection/compare_record.h"
#include "umicom/workbench_selection/consumer_record.h"
#include "umicom/workbench_selection/consumer_state.h"
#include "umicom/workbench_selection/correlation_record.h"
#include "umicom/workbench_selection/debug_item.h"
#include "umicom/workbench_selection/diagnostic_item.h"
#include "umicom/workbench_selection/duplicate_record.h"
#include "umicom/workbench_selection/event_record.h"
#include "umicom/workbench_selection/evidence_record.h"
#include "umicom/workbench_selection/export_record.h"
#include "umicom/workbench_selection/field.h"
#include "umicom/workbench_selection/field_mapping.h"
#include "umicom/workbench_selection/field_requirement.h"
#include "umicom/workbench_selection/file_node.h"
#include "umicom/workbench_selection/filter_record.h"
#include "umicom/workbench_selection/focus_record.h"
#include "umicom/workbench_selection/group_binding.h"
#include "umicom/workbench_selection/health_record.h"
#include "umicom/workbench_selection/history_record.h"
#include "umicom/workbench_selection/import_record.h"
#include "umicom/workbench_selection/instrument_item.h"
#include "umicom/workbench_selection/latency_record.h"
#include "umicom/workbench_selection/media_item.h"
#include "umicom/workbench_selection/merge_record.h"
#include "umicom/workbench_selection/metric_record.h"
#include "umicom/workbench_selection/multi_selection.h"
#include "umicom/workbench_selection/navigation_record.h"
#include "umicom/workbench_selection/node_capability.h"
#include "umicom/workbench_selection/node_identity.h"
#include "umicom/workbench_selection/node_parent.h"
#include "umicom/workbench_selection/node_path.h"
#include "umicom/workbench_selection/open_record.h"
#include "umicom/workbench_selection/panel_binding.h"
#include "umicom/workbench_selection/permission_record.h"
#include "umicom/workbench_selection/policy_record.h"
#include "umicom/workbench_selection/preview_record.h"
#include "umicom/workbench_selection/producer_record.h"
#include "umicom/workbench_selection/producer_state.h"
#include "umicom/workbench_selection/profile_record.h"
#include "umicom/workbench_selection/project_node.h"
#include "umicom/workbench_selection/provider_record.h"
#include "umicom/workbench_selection/provider_state.h"
#include "umicom/workbench_selection/publication_record.h"
#include "umicom/workbench_selection/query_record.h"
#include "umicom/workbench_selection/rate_record.h"
#include "umicom/workbench_selection/refresh_record.h"
#include "umicom/workbench_selection/rejection_record.h"
#include "umicom/workbench_selection/remediation_record.h"
#include "umicom/workbench_selection/resolver.h"
#include "umicom/workbench_selection/resolver_record.h"
#include "umicom/workbench_selection/result_record.h"
#include "umicom/workbench_selection/reveal_record.h"
#include "umicom/workbench_selection/schema_record.h"
#include "umicom/workbench_selection/search_record.h"
#include "umicom/workbench_selection/selection.h"
#include "umicom/workbench_selection/selection_origin.h"
#include "umicom/workbench_selection/selection_set.h"
#include "umicom/workbench_selection/selection_state.h"
#include "umicom/workbench_selection/service.h"
#include "umicom/workbench_selection/session_record.h"
#include "umicom/workbench_selection/snapshot_record.h"
#include "umicom/workbench_selection/source_branch.h"
#include "umicom/workbench_selection/source_change.h"
#include "umicom/workbench_selection/source_commit.h"
#include "umicom/workbench_selection/stale_record.h"
#include "umicom/workbench_selection/statistics_record.h"
#include "umicom/workbench_selection/terminal_item.h"
#include "umicom/workbench_selection/test_item.h"
#include "umicom/workbench_selection/test_result.h"
#include "umicom/workbench_selection/trace_record.h"
#include "umicom/workbench_selection/trade_item.h"
#include "umicom/workbench_selection/types.h"
#include "umicom/workbench_selection/validation_record.h"
#include "umicom/workbench_selection/workspace_binding.h"
#include "umicom/workbench_selection/workspace_item.h"

#endif
