# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Every mutation belongs to a new disposable fixture beneath the CTest build directory.
if(NOT DEFINED TEST_BINARY OR NOT DEFINED TEST_ROOT OR NOT DEFINED GIT_EXECUTABLE)
    message(FATAL_ERROR "Working-tree fixture arguments are incomplete.")
endif()
get_filename_component(TEST_ROOT "${TEST_ROOT}" ABSOLUTE)
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef fixture_token)
set(fixture "${TEST_ROOT}/git-working-tree-${fixture_token}")
set(parent "${fixture}/parent")
set(seed "${fixture}/seed")
set(hooks "${fixture}/empty-hooks")
file(MAKE_DIRECTORY "${parent}" "${seed}" "${hooks}")
function(git_run root)
    execute_process(COMMAND "${GIT_EXECUTABLE}" --no-optional-locks
        -c core.fsmonitor=false -c "core.hooksPath=${hooks}" -c "init.templateDir=${hooks}"
        -c "user.name=Umicom Fixture" -c "user.email=fixture@example.invalid"
        -c commit.gpgsign=false -c protocol.file.allow=always -C "${root}" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 20)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Fixture Git operation failed (${result}): ${errors}\nFixture retained: ${fixture}")
    endif()
endfunction()
function(observe mode)
    # Optional index locking must not refresh the parent's index during passive inspection.
    if(EXISTS "${parent}/.git/index")
        file(SHA256 "${parent}/.git/index" before)
    else()
        set(before "")
    endif()
    execute_process(COMMAND "${TEST_BINARY}" "${parent}" "${mode}" "${GIT_EXECUTABLE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 35)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Observation ${mode} failed (${result}): ${errors}\nFixture retained: ${fixture}")
    endif()
    if(NOT before STREQUAL "")
        file(SHA256 "${parent}/.git/index" after)
        if(NOT before STREQUAL after)
            message(FATAL_ERROR "Passive observation changed the parent index. Fixture: ${fixture}")
        endif()
    endif()
endfunction()
# Exercise the public command against the same isolated repositories. No owner
# repository is used and index bytes must remain identical after every review.
function(observe_cli)
    if(NOT DEFINED CLI_BINARY)
        return()
    endif()
    if(EXISTS "${parent}/.git/index")
        file(SHA256 "${parent}/.git/index" before_cli)
    else()
        set(before_cli "")
    endif()
    execute_process(COMMAND "${CLI_BINARY}" repo review --root "${parent}" --children --timeout-ms 5000
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 15)
    if(NOT result EQUAL 0 OR NOT output MATCHES "local status observation")
        message(FATAL_ERROR "Native repository review failed: ${result} ${errors}\n${output}")
    endif()
    if(NOT before_cli STREQUAL "")
        file(SHA256 "${parent}/.git/index" after_cli)
        if(NOT before_cli STREQUAL after_cli)
            message(FATAL_ERROR "Native repository review changed the index.")
        endif()
    endif()
endfunction()
git_run("${parent}" init -b main)
observe(unborn)
git_run("${seed}" init -b main)
file(WRITE "${seed}/source.c" "int value = 1;\n")
git_run("${seed}" add source.c)
git_run("${seed}" commit -m "Create fixture source")
git_run("${parent}" submodule add "${seed}" framework)
git_run("${parent}" add .gitmodules framework)
git_run("${parent}" commit -m "Record fixture child")
observe(clean)
file(WRITE "${parent}/framework/source.c" "int value = 2;\n")
file(WRITE "${parent}/framework/file with spaces.c" "int second_value = 3;\n")
observe(child-dirty)
observe_cli()
git_run("${parent}/framework" add source.c "file with spaces.c")
git_run("${parent}/framework" commit -m "Update fixture child")
observe(child-committed)
git_run("${parent}" add framework)
observe(parent-staged)
observe_cli()
file(WRITE "${parent}/framework/source.c" "int value = 4;\n")
observe(parent-staged-child-dirty)
# The random fixture is a direct child of the supplied build directory and was created by this script.
get_filename_component(fixture_parent "${fixture}" DIRECTORY)
if(NOT fixture_parent STREQUAL TEST_ROOT)
    message(FATAL_ERROR "Refusing to remove a fixture outside the test directory.")
endif()
file(REMOVE_RECURSE "${fixture}")
