/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/compiler/native/lexer.c
 *
 * PURPOSE:
 *   Tokenize a practical C23 source subset with comments, literals, identifiers, keywords, numbers and punctuation.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
#include "umicom/compiler/native/lexer.h"
#include <ctype.h>
#include <string.h>
static UmiStatus push_text(UmiNativeTokenStream *s,UmiNativeTokenKind k,UmiNativeSourceSpan sp,const char *p,size_t n){ if(n>=UMI_NC_TOKEN_TEXT_CAPACITY) return UMI_STATUS_CAPACITY_EXCEEDED; char buf[UMI_NC_TOKEN_TEXT_CAPACITY]; memcpy(buf,p,n); buf[n]='\0'; UmiNativeToken t; UmiStatus st=umi_nc_token_init(&t,k,sp,buf); return st==UMI_STATUS_OK?umi_nc_token_stream_push(s,&t):st; }
UmiStatus umi_nc_lexer_run(const UmiNativeSourceBuffer *source,UmiNativeTokenStream *out_stream,UmiNativeLexerReport *out_report){ if(source==NULL||out_stream==NULL||out_report==NULL) return UMI_STATUS_INVALID_ARGUMENT; umi_nc_token_stream_init(out_stream); memset(out_report,0,sizeof(*out_report)); size_t i=0U; uint32_t line=1U,col=1U; while(i<source->length){ unsigned char ch=(unsigned char)source->text[i]; if(ch==' '||ch=='\t'||ch=='\r'){i++;col++;continue;} if(ch=='\n'){i++;line++;col=1U;continue;} UmiNativeSourceSpan sp={1U,i,0U,line,col}; if(ch=='/'&&i+1U<source->length&&source->text[i+1U]=='/'){ size_t start=i; while(i<source->length&&source->text[i]!='\n'){i++;col++;} sp.length=i-start; if(push_text(out_stream,UMI_NC_TOKEN_COMMENT,sp,source->text+start,sp.length)!=UMI_STATUS_OK) return UMI_STATUS_CAPACITY_EXCEEDED; out_report->comments++; continue; } if(ch=='/'&&i+1U<source->length&&source->text[i+1U]=='*'){ size_t start=i; i+=2U; col+=2U; bool closed=false; while(i<source->length){ if(source->text[i]=='*'&&i+1U<source->length&&source->text[i+1U]=='/'){i+=2U;col+=2U;closed=true;break;} if(source->text[i]=='\n'){i++;line++;col=1U;} else {i++;col++;} } sp.length=i-start; if(push_text(out_stream,closed?UMI_NC_TOKEN_COMMENT:UMI_NC_TOKEN_ERROR,sp,source->text+start,sp.length)!=UMI_STATUS_OK) return UMI_STATUS_CAPACITY_EXCEEDED; if(closed) out_report->comments++; else out_report->errors++; continue; } if(isalpha(ch)!=0||ch=='_'){ size_t start=i; while(i<source->length){ unsigned char c=(unsigned char)source->text[i]; if(isalnum(c)==0&&c!='_') break; i++;col++; } sp.length=i-start; if(push_text(out_stream,UMI_NC_TOKEN_IDENTIFIER,sp,source->text+start,sp.length)!=UMI_STATUS_OK) return UMI_STATUS_CAPACITY_EXCEEDED; continue; } if(isdigit(ch)!=0){ size_t start=i; while(i<source->length){ unsigned char c=(unsigned char)source->text[i]; if(isalnum(c)==0&&c!='.'&&c!='_') break; i++;col++; } sp.length=i-start; if(push_text(out_stream,UMI_NC_TOKEN_NUMBER,sp,source->text+start,sp.length)!=UMI_STATUS_OK) return UMI_STATUS_CAPACITY_EXCEEDED; continue; } if(ch=='\"'||ch=='\''){ char quote=(char)ch; UmiNativeTokenKind kind=quote=='\"'?UMI_NC_TOKEN_STRING:UMI_NC_TOKEN_CHARACTER; size_t start=i++; col++; bool closed=false; while(i<source->length){ char c=source->text[i++]; col++; if(c=='\\'&&i<source->length){i++;col++;continue;} if(c==quote){closed=true;break;} if(c=='\n'){line++;col=1U;} } sp.length=i-start; if(push_text(out_stream,closed?kind:UMI_NC_TOKEN_ERROR,sp,source->text+start,sp.length)!=UMI_STATUS_OK) return UMI_STATUS_CAPACITY_EXCEEDED; if(!closed) out_report->errors++; continue; } sp.length=1U; if(push_text(out_stream,UMI_NC_TOKEN_PUNCTUATION,sp,source->text+i,1U)!=UMI_STATUS_OK) return UMI_STATUS_CAPACITY_EXCEEDED; i++;col++; }
 UmiNativeSourceSpan eof={1U,source->length,0U,line,col}; UmiNativeToken t; if(umi_nc_token_init(&t,UMI_NC_TOKEN_EOF,eof,"")!=UMI_STATUS_OK) return UMI_STATUS_INTERNAL_ERROR; if(umi_nc_token_stream_push(out_stream,&t)!=UMI_STATUS_OK) return UMI_STATUS_CAPACITY_EXCEEDED; out_report->tokens=out_stream->count; out_report->final_line=line; return out_report->errors==0U?UMI_STATUS_OK:UMI_STATUS_PARSE_ERROR; }
