/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: include/umicom/document/generation.h
 *
 * PURPOSE:
 *   Define safe document-output planning, built-in text generation and
 *   replaceable adapters for PDF, word-processing and presentation formats.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
#ifndef UMICOM_DOCUMENT_GENERATION_H
#define UMICOM_DOCUMENT_GENERATION_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "umicom/base/status.h"

#ifdef __cplusplus
extern "C" {
#endif

#define UMI_DOCUMENT_GENERATION_ID_CAPACITY 64U
#define UMI_DOCUMENT_GENERATION_NAME_CAPACITY 160U
#define UMI_DOCUMENT_GENERATION_MIME_CAPACITY 96U
#define UMI_DOCUMENT_GENERATION_EXTENSION_CAPACITY 16U

/* Formats name document intent without coupling to a commercial application. */
typedef enum UmiDocumentGenerationFormat {
    UMI_DOCUMENT_GENERATION_TEXT = 0,
    UMI_DOCUMENT_GENERATION_PDF = 1,
    UMI_DOCUMENT_GENERATION_WORD_PROCESSING = 2,
    UMI_DOCUMENT_GENERATION_PRESENTATION = 3,
    UMI_DOCUMENT_GENERATION_VIDEO_SCRIPT = 4,
    UMI_DOCUMENT_GENERATION_STORYBOARD = 5
} UmiDocumentGenerationFormat;

/* Requests borrow input text only for the duration of the called function. */
typedef struct UmiDocumentGenerationRequest {
    const char *title;
    const char *body;
    const char *output_name;
    UmiDocumentGenerationFormat format;
} UmiDocumentGenerationRequest;

/* Plans contain copied metadata and clearly identify adapter requirements. */
typedef struct UmiDocumentGenerationPlan {
    uint32_t struct_size;
    uint32_t api_version;
    UmiDocumentGenerationFormat format;
    char output_name[UMI_DOCUMENT_GENERATION_NAME_CAPACITY];
    char extension[UMI_DOCUMENT_GENERATION_EXTENSION_CAPACITY];
    char mime_type[UMI_DOCUMENT_GENERATION_MIME_CAPACITY];
    bool requires_external_adapter;
} UmiDocumentGenerationPlan;

/* A sink consumes generated bytes without forcing the Framework to own a file. */
typedef UmiStatus (*UmiDocumentGenerationSink)(
    const void *data,
    size_t data_size,
    void *sink_context);

/* An adapter transforms one validated request and streams its output to a sink. */
typedef UmiStatus (*UmiDocumentGenerationAdapterFunction)(
    const UmiDocumentGenerationRequest *request,
    UmiDocumentGenerationSink sink,
    void *sink_context,
    void *adapter_context);

/* Adapter descriptors are copied into a registry, including callback pointers. */
typedef struct UmiDocumentGenerationAdapter {
    char adapter_id[UMI_DOCUMENT_GENERATION_ID_CAPACITY];
    UmiDocumentGenerationFormat format;
    UmiDocumentGenerationAdapterFunction generate;
    void *adapter_context;
} UmiDocumentGenerationAdapter;

/* The opaque registry owns copied adapter descriptors, not adapter contexts. */
typedef struct UmiDocumentGenerationRegistry UmiDocumentGenerationRegistry;

/* Convert a format to stable text for logs and output selectors. */
const char *umi_document_generation_format_text(
    UmiDocumentGenerationFormat format);

/* Validate a request and copy its output format metadata into a plan. */
UmiStatus umi_document_generation_plan(
    const UmiDocumentGenerationRequest *request,
    UmiDocumentGenerationPlan *out_plan);

/* Generate text, video-script or storyboard output into caller memory. */
UmiStatus umi_document_generation_write_text(
    const UmiDocumentGenerationRequest *request,
    char *buffer,
    size_t capacity,
    size_t *out_required_size);

/* Create a bounded registry for independently implemented format adapters. */
UmiStatus umi_document_generation_registry_create(
    size_t adapter_capacity,
    UmiDocumentGenerationRegistry **out_registry);

/* Destroy copied descriptors without freeing application-owned contexts. */
void umi_document_generation_registry_destroy(
    UmiDocumentGenerationRegistry *registry);

/* Register one unique adapter for one output format. */
UmiStatus umi_document_generation_registry_register(
    UmiDocumentGenerationRegistry *registry,
    const UmiDocumentGenerationAdapter *adapter);

/* Generate through the registered adapter for the request format. */
UmiStatus umi_document_generation_registry_generate(
    const UmiDocumentGenerationRegistry *registry,
    const UmiDocumentGenerationRequest *request,
    UmiDocumentGenerationSink sink,
    void *sink_context);

/* Return the number of copied adapters currently registered. */
size_t umi_document_generation_registry_count(
    const UmiDocumentGenerationRegistry *registry);

#ifdef __cplusplus
}
#endif

#endif
