#-----------------------------------------------------------------------------
# Umicom Framework
# File: tests/windows_deployment/test_deployment.cmake
#
# PURPOSE:
#   Verify packaging inputs, ownership safeguards and rendered setup contracts.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
cmake_minimum_required(VERSION 3.24)
include("${FRAMEWORK}/cmake/windows/DeploymentCommon.cmake")
include("${FRAMEWORK}/cmake/windows/RenderInstaller.cmake")
file(MAKE_DIRECTORY "${WORK}")

function(require_contains text expected)
    string(FIND "${text}" "${expected}" _position)
    if(_position LESS 0)
        message(FATAL_ERROR "Missing generated contract: ${expected}")
    endif()
endfunction()

function(make_fixture path architecture)
    get_filename_component(_directory "${path}" DIRECTORY)
    file(MAKE_DIRECTORY "${_directory}")
    execute_process(COMMAND "${FIXTURE_EXE}" --pe-fixture "${path}" "${architecture}"
        RESULT_VARIABLE _result)
    if(NOT _result STREQUAL "0")
        message(FATAL_ERROR "PE-header test fixture creation failed")
    endif()
endfunction()

if(CASE STREQUAL "safe-values")
    umicom_windows_require_identifier("umicom-studio.ide_gtk4")
    umicom_windows_require_literal("C:/Umicom Apps/$Testing")
    umicom_windows_require_relative("share/Umicom Apps/icon.svg")
elseif(CASE STREQUAL "escape")
    umicom_windows_nsis_escape([=[A$B"C]=] _value)
    if(NOT _value STREQUAL [=[A$$B$\"C]=])
        message(FATAL_ERROR "Incorrect NSIS escaping: ${_value}")
    endif()
elseif(CASE STREQUAL "bad-identifier")
    umicom_windows_require_identifier("studio/../bank")
elseif(CASE STREQUAL "bad-literal")
    umicom_windows_require_literal("a;b")
elseif(CASE STREQUAL "bad-bracket")
    umicom_windows_require_literal("a]==]b")
elseif(CASE STREQUAL "bad-newline")
    umicom_windows_require_literal("a\nb")
elseif(CASE STREQUAL "parent-path")
    umicom_windows_require_relative("bin/../outside")
elseif(CASE STREQUAL "absolute-path")
    umicom_windows_require_relative("/outside")
elseif(CASE STREQUAL "drive-path")
    umicom_windows_require_relative("C:/outside")
elseif(CASE STREQUAL "backslash-path")
    umicom_windows_require_relative("bin\\outside")
elseif(CASE STREQUAL "reserved-path")
    umicom_windows_require_relative("bin/CON.txt")
elseif(CASE STREQUAL "trailing-dot")
    umicom_windows_require_relative("bin/bad.")
elseif(CASE STREQUAL "tab-path")
    umicom_windows_require_relative("bin/bad\tname")
elseif(CASE STREQUAL "duplicate-path")
    umicom_windows_validate_unique_paths("bin/App.exe" "bin/app.exe")
elseif(CASE STREQUAL "copy" OR CASE STREQUAL "same-copy")
    file(WRITE "${WORK}/source" "complete runtime file\n")
    if(CASE STREQUAL "same-copy")
        umicom_windows_copy_file("${WORK}/source" "${WORK}/source")
    else()
        umicom_windows_copy_file("${WORK}/source" "${WORK}/nested/destination")
        file(SHA256 "${WORK}/source" _a)
        file(SHA256 "${WORK}/nested/destination" _b)
        if(NOT _a STREQUAL _b)
            message(FATAL_ERROR "Runtime copy changed bytes")
        endif()
    endif()
elseif(CASE STREQUAL "missing-file")
    umicom_windows_copy_file("${WORK}/missing" "${WORK}/destination")
elseif(CASE STREQUAL "directory-file")
    umicom_windows_copy_file("${WORK}" "${WORK}/destination")
elseif(CASE STREQUAL "symlink-file")
    file(WRITE "${WORK}/source" "not package-owned through a symlink")
    file(CREATE_LINK "${WORK}/source" "${WORK}/link" SYMBOLIC)
    umicom_windows_copy_file("${WORK}/link" "${WORK}/destination")
elseif(CASE STREQUAL "pe-x64" OR CASE STREQUAL "pe-x86" OR CASE STREQUAL "wrong-architecture")
    if(CASE STREQUAL "pe-x64")
        make_fixture("${WORK}/app.exe" x64)
        umicom_windows_require_pe("${WORK}/app.exe")
    else()
        make_fixture("${WORK}/app.exe" x86)
        if(CASE STREQUAL "pe-x86")
            umicom_windows_require_pe("${WORK}/app.exe" "4c01")
        else()
            umicom_windows_require_pe("${WORK}/app.exe")
        endif()
    endif()
elseif(CASE STREQUAL "invalid-pe")
    string(REPEAT "not a PE image" 40 _text)
    file(WRITE "${WORK}/app.exe" "${_text}")
    umicom_windows_require_pe("${WORK}/app.exe")
elseif(CASE STREQUAL "truncated-pe")
    file(WRITE "${WORK}/app.exe" "MZ")
    umicom_windows_require_pe("${WORK}/app.exe")
elseif(CASE STREQUAL "unowned-reset")
    file(MAKE_DIRECTORY "${WORK}/user-data")
    file(WRITE "${WORK}/user-data/project.c" "keep this file")
    umicom_windows_reset_owned_directory("${WORK}/user-data")
elseif(CASE STREQUAL "owned-reset")
    # Test work is disposable, but only the helper's own marker permits reset.
    if(NOT EXISTS "${WORK}/owned")
        umicom_windows_reset_owned_directory("${WORK}/owned")
    endif()
    file(WRITE "${WORK}/owned/stale" "old package")
    umicom_windows_reset_owned_directory("${WORK}/owned")
    if(EXISTS "${WORK}/owned/stale" OR NOT EXISTS "${WORK}/owned/.umicom-package-work")
        message(FATAL_ERROR "Owned package reset did not honour its contract")
    endif()
elseif(CASE STREQUAL "nonwindows-noop")
    set(WIN32 FALSE)
    include("${FRAMEWORK}/cmake/UmicomWindowsDeployment.cmake")
    umicom_prepare_windows_application(TARGET deliberately-not-a-target)
elseif(CASE MATCHES "^render" OR CASE STREQUAL "deterministic")
    set(UMI_SETUP_PAYLOAD_ROOT "${WORK}/payload")
    file(MAKE_DIRECTORY "${UMI_SETUP_PAYLOAD_ROOT}/runtime/share")
    file(WRITE "${UMI_SETUP_PAYLOAD_ROOT}/runtime/share/runtime.txt" "fixture runtime\n")
    make_fixture("${UMI_SETUP_PAYLOAD_ROOT}/studio/bin/umicom-studio-ide.exe" x64)
    make_fixture("${UMI_SETUP_PAYLOAD_ROOT}/trader/bin/umicom-trader.exe" x64)
    set(UMI_SETUP_APPS studio trader)
    set(UMI_SETUP_NAME_studio "Umicom Studio IDE")
    set(UMI_SETUP_EXE_studio "umicom-studio-ide.exe")
    set(UMI_SETUP_NAME_trader "Umicom Trader")
    set(UMI_SETUP_EXE_trader "umicom-trader.exe")
    set(UMI_SETUP_SCRIPT "${WORK}/generated/UmicomSetup.nsi")
    set(UMI_SETUP_OUTPUT_FILE "${WORK}/generated/Umicom-Setup.exe")
    set(UMI_SETUP_VERSION "0.3.0")
    set(UMI_SETUP_LICENCE "${WORK}/licence.txt")
    file(WRITE "${UMI_SETUP_LICENCE}" "Test-fixture licence, not for distribution\n")
    if(CASE STREQUAL "render-empty")
        set(UMI_SETUP_APPS "")
    elseif(CASE STREQUAL "render-missing")
        list(APPEND UMI_SETUP_APPS missing)
    elseif(CASE STREQUAL "render-duplicate-path")
        make_fixture("${UMI_SETUP_PAYLOAD_ROOT}/runtime/bin/UMICOM-STUDIO-IDE.exe" x64)
    elseif(CASE STREQUAL "render-duplicate-title")
        set(UMI_SETUP_NAME_trader "umicom studio ide")
    elseif(CASE STREQUAL "render-invalid-version")
        set(UMI_SETUP_VERSION "0.3.bad")
    elseif(CASE STREQUAL "render-control-file")
        file(WRITE "${UMI_SETUP_PAYLOAD_ROOT}/runtime/installation.ini" "not allowed")
    elseif(CASE STREQUAL "render-missing-exe")
        set(UMI_SETUP_EXE_studio missing.exe)
    elseif(CASE STREQUAL "render-bad-title")
        set(UMI_SETUP_NAME_studio "Umicom/../outside")
    elseif(CASE STREQUAL "render-dollar")
        set(UMI_SETUP_NAME_studio "Umicom $Studio")
    elseif(CASE STREQUAL "render-unicode")
        set(UMI_SETUP_NAME_studio "Umicom Éditeur")
    endif()
    umicom_render_windows_installer()
    file(READ "${UMI_SETUP_SCRIPT}" _script)
    require_contains("${_script}" "InstType \"Install all applications\"")
    require_contains("${_script}" "StrCpy $DesktopOption 0")
    require_contains("${_script}" "StrCpy $StartMenuOption 1")
    require_contains("${_script}" "RequestExecutionLevel user")
    require_contains("${_script}" "SectionGetFlags \${UMI_APP_1}")
    require_contains("${_script}" "Function UmiUserAbort")
    require_contains("${_script}" "File /r")
    require_contains("${_script}" "CRCCheck force")
    if(_script MATCHES "RMDir /r" OR _script MATCHES "WriteReg[^\r\n]*PATH" OR _script MATCHES "@UMI_SETUP_")
        message(FATAL_ERROR "Unsafe or unresolved generated setup instruction")
    endif()
    if(CASE STREQUAL "render-dollar")
        require_contains("${_script}" "Umicom $$Studio")
    endif()
    if(CASE STREQUAL "deterministic")
        file(SHA256 "${UMI_SETUP_SCRIPT}" _before)
        umicom_render_windows_installer()
        file(SHA256 "${UMI_SETUP_SCRIPT}" _after)
        if(NOT _before STREQUAL _after)
            message(FATAL_ERROR "Unchanged input did not produce a deterministic installer script")
        endif()
    endif()
else()
    message(FATAL_ERROR "Unknown test case: ${CASE}")
endif()
