/* Umicom Framework | Compiler build graphs | Sammy Hegab | Umicom Foundation | MIT */
#include "umicom/compiler/build_graph.h"
#include <stdio.h>
#include <string.h>
static size_t find_index(const UmiCompilerBuildGraph *graph,const char *id) { size_t index; if (graph == NULL || id == NULL) return SIZE_MAX; for (index = 0U; index < graph->count; ++index) if (strcmp(graph->steps[index].step_id,id) == 0) return index; return SIZE_MAX; }
UmiStatus umi_compiler_build_graph_add(UmiCompilerBuildGraph *graph,const UmiCompilerBuildStep *step) { if (graph == NULL || step == NULL || step->step_id[0] == '\0') return UMI_STATUS_INVALID_ARGUMENT; if (find_index(graph,step->step_id) != SIZE_MAX) return UMI_STATUS_ALREADY_EXISTS; if (graph->count >= UMI_COMPILER_MAX_BUILD_STEPS) return UMI_STATUS_CAPACITY_EXCEEDED; graph->steps[graph->count++] = *step; graph->revision += 1U; return UMI_STATUS_OK; }
UmiStatus umi_compiler_build_graph_add_dependency(UmiCompilerBuildGraph *graph,const char *step_id,const char *dependency_id) { size_t step = find_index(graph,step_id); size_t dependency = find_index(graph,dependency_id); int length; if (graph == NULL || step_id == NULL || dependency_id == NULL) return UMI_STATUS_INVALID_ARGUMENT; if (step == SIZE_MAX || dependency == SIZE_MAX) return UMI_STATUS_NOT_FOUND; if (graph->steps[step].dependency_count >= UMI_COMPILER_MAX_STEP_DEPENDENCIES) return UMI_STATUS_CAPACITY_EXCEEDED; length = snprintf(graph->steps[step].dependencies[graph->steps[step].dependency_count],sizeof(graph->steps[step].dependencies[0]),"%s",dependency_id); if (length < 0 || (size_t)length >= sizeof(graph->steps[step].dependencies[0])) return UMI_STATUS_CAPACITY_EXCEEDED; graph->steps[step].dependency_count += 1U; graph->revision += 1U; return UMI_STATUS_OK; }
const UmiCompilerBuildStep *umi_compiler_build_graph_find(const UmiCompilerBuildGraph *graph,const char *step_id) { size_t index = find_index(graph,step_id); return index == SIZE_MAX ? NULL : &graph->steps[index]; }
UmiStatus umi_compiler_build_graph_order(const UmiCompilerBuildGraph *graph,size_t *out_indices,size_t capacity,size_t *out_count) { bool emitted[UMI_COMPILER_MAX_BUILD_STEPS] = {false}; size_t produced = 0U; if (graph == NULL || out_indices == NULL || out_count == NULL || capacity < graph->count) return UMI_STATUS_INVALID_ARGUMENT; while (produced < graph->count) { size_t index; bool progress = false; for (index = 0U; index < graph->count; ++index) if (!emitted[index]) { size_t dependency; bool ready = true; for (dependency = 0U; dependency < graph->steps[index].dependency_count; ++dependency) { size_t required = find_index(graph,graph->steps[index].dependencies[dependency]); if (required == SIZE_MAX) return UMI_STATUS_NOT_FOUND; if (!emitted[required]) ready = false; } if (ready) { out_indices[produced++] = index; emitted[index] = true; progress = true; } } if (!progress) return UMI_STATUS_INVALID_STATE; } *out_count = produced; return UMI_STATUS_OK; }
