/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: include/umicom/test_runtime/test_runtime.h
 *
 * PURPOSE:
 *   Expose the complete Framework test-runtime and regression-stabilisation contract.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/

#ifndef UMICOM_TEST_RUNTIME_TEST_RUNTIME_H
#define UMICOM_TEST_RUNTIME_TEST_RUNTIME_H

#include "umicom/test_runtime/types.h"
#include "umicom/test_runtime/failure_classifier.h"
#include "umicom/test_runtime/environment.h"
#include "umicom/test_runtime/search_path.h"
#include "umicom/test_runtime/working_directory.h"
#include "umicom/test_runtime/executable_probe.h"
#include "umicom/test_runtime/dependency_probe.h"
#include "umicom/test_runtime/launch_plan.h"
#include "umicom/test_runtime/launch_evidence.h"
#include "umicom/test_runtime/failure_classification.h"
#include "umicom/test_runtime/bad_command_evidence.h"
#include "umicom/test_runtime/crash_evidence.h"
#include "umicom/test_runtime/timeout_evidence.h"
#include "umicom/test_runtime/timeout_policy.h"
#include "umicom/test_runtime/retry_policy.h"
#include "umicom/test_runtime/test_descriptor.h"
#include "umicom/test_runtime/catalogue.h"
#include "umicom/test_runtime/selection.h"
#include "umicom/test_runtime/profile.h"
#include "umicom/test_runtime/profile_catalogue.h"
#include "umicom/test_runtime/shard.h"
#include "umicom/test_runtime/execution_batch.h"
#include "umicom/test_runtime/result.h"
#include "umicom/test_runtime/result_store.h"
#include "umicom/test_runtime/history.h"
#include "umicom/test_runtime/regression_baseline.h"
#include "umicom/test_runtime/diagnostic.h"
#include "umicom/test_runtime/diagnostics.h"
#include "umicom/test_runtime/metrics.h"
#include "umicom/test_runtime/health.h"
#include "umicom/test_runtime/report.h"
#include "umicom/test_runtime/artifact_locator.h"
#include "umicom/test_runtime/runtime_dependency.h"
#include "umicom/test_runtime/process_environment.h"
#include "umicom/test_runtime/runtime_probe.h"
#include "umicom/test_runtime/clean_machine.h"
#include "umicom/test_runtime/ctest_bridge.h"
#include "umicom/test_runtime/scheduler.h"
#include "umicom/test_runtime/command.h"
#include "umicom/test_runtime/event.h"
#include "umicom/test_runtime/query.h"
#include "umicom/test_runtime/service.h"
#include "umicom/test_runtime/controller.h"

#include "umicom/test_runtime/execution_guard.h"
#include "umicom/test_runtime/runtime_path.h"
#include "umicom/test_runtime/environment_entry.h"
#include "umicom/test_runtime/dependency_directory.h"
#include "umicom/test_runtime/executable_location.h"
#include "umicom/test_runtime/command_line.h"
#include "umicom/test_runtime/process_identity.h"
#include "umicom/test_runtime/process_status.h"
#include "umicom/test_runtime/start_failure.h"
#include "umicom/test_runtime/exit_interpretation.h"
#include "umicom/test_runtime/assertion_evidence.h"
#include "umicom/test_runtime/sanitizer_evidence.h"
#include "umicom/test_runtime/stack_evidence.h"
#include "umicom/test_runtime/memory_evidence.h"
#include "umicom/test_runtime/dependency_closure.h"
#include "umicom/test_runtime/runtime_manifest.h"
#include "umicom/test_runtime/environment_snapshot.h"
#include "umicom/test_runtime/execution_snapshot.h"
#include "umicom/test_runtime/failure_group.h"
#include "umicom/test_runtime/failure_summary.h"
#include "umicom/test_runtime/baseline_comparison.h"
#include "umicom/test_runtime/trend.h"
#include "umicom/test_runtime/duration_budget.h"
#include "umicom/test_runtime/slow_test.h"
#include "umicom/test_runtime/quarantine.h"
#include "umicom/test_runtime/reproduction.h"
#include "umicom/test_runtime/diagnostic_bundle.h"
#include "umicom/test_runtime/result_parser.h"
#include "umicom/test_runtime/ctest_record.h"
#include "umicom/test_runtime/ctest_result.h"
#include "umicom/test_runtime/test_label.h"
#include "umicom/test_runtime/label_catalogue.h"
#include "umicom/test_runtime/resource_lock.h"
#include "umicom/test_runtime/resource_group.h"
#include "umicom/test_runtime/temporary_directory.h"
#include "umicom/test_runtime/log_capture.h"
#include "umicom/test_runtime/evidence_retention.h"
#include "umicom/test_runtime/execution_statistics.h"
#include "umicom/test_runtime/parallel_budget.h"
#include "umicom/test_runtime/suite_partition.h"

#include "umicom/test_runtime/test_family.h"
#include "umicom/test_runtime/execution_order.h"
#include "umicom/test_runtime/rerun_plan.h"
#include "umicom/test_runtime/failure_reproduction.h"
#include "umicom/test_runtime/runtime_capability.h"
#include "umicom/test_runtime/platform_requirement.h"
#include "umicom/test_runtime/tool_requirement.h"
#include "umicom/test_runtime/network_requirement.h"
#include "umicom/test_runtime/filesystem_requirement.h"
#include "umicom/test_runtime/database_requirement.h"
#include "umicom/test_runtime/ui_requirement.h"
#include "umicom/test_runtime/failure_fingerprint.h"
#include "umicom/test_runtime/failure_owner.h"
#include "umicom/test_runtime/failure_queue.h"
#include "umicom/test_runtime/resolution_evidence.h"
#include "umicom/test_runtime/execution_gate.h"
#include "umicom/test_runtime/preflight.h"
#include "umicom/test_runtime/postflight.h"
#include "umicom/test_runtime/run_identity.h"
#include "umicom/test_runtime/run_summary.h"

#endif
