# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
cmake_minimum_required(VERSION 3.24)
if(NOT DEFINED FRAMEWORK OR NOT EXISTS "${FRAMEWORK}/examples/designer_native/CMakeLists.txt" OR
   NOT DEFINED ROOT OR NOT ROOT MATCHES "/generated-build$")
    message(FATAL_ERROR "Invalid generated-build fixture")
endif()
file(REMOVE_RECURSE "${ROOT}")
file(MAKE_DIRECTORY "${ROOT}" "${ROOT}/elsewhere")
set(_log "${ROOT}/transcript.txt")
function(Run)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
    file(APPEND "${_log}" "COMMAND: ${ARGV}\n${_out}${_err}\nEXIT: ${_rc}\n")
    if(NOT _rc STREQUAL "0")
        message(FATAL_ERROR "Generated project workflow failed: ${ARGV}\n${_out}${_err}")
    endif()
endfunction()
get_filename_component(_cmake_bin "${CMAKE_COMMAND}" DIRECTORY)
find_program(CMAKE_CTEST_COMMAND NAMES ctest HINTS "${_cmake_bin}" REQUIRED)
set(_sdk "${ROOT}/sdk")
set(_extension "")
if(CMAKE_HOST_WIN32)
    set(_extension .exe)
endif()
Run("${CMAKE_COMMAND}" -S "${FRAMEWORK}/examples/designer_native" -B "${ROOT}/sdk-build" -G Ninja
    -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DUMICOM_DESIGNER_NATIVE_GTK4=OFF
    "-DCMAKE_C_COMPILER=${COMPILER}" "-DCMAKE_INSTALL_PREFIX=${_sdk}")
Run("${CMAKE_COMMAND}" --build "${ROOT}/sdk-build" --parallel 2)
Run("${CMAKE_COMMAND}" --install "${ROOT}/sdk-build")
set(_tool "${_sdk}/bin/umicom-designer-project${_extension}")
Run("${_tool}" notes "${ROOT}/notes")
Run("${CMAKE_COMMAND}" -S "${ROOT}/notes" -B "${ROOT}/notes-build" -G Ninja
    "-DCMAKE_PREFIX_PATH=${_sdk}" -DUMICOM_NATIVE_PROJECT_GUI=OFF "-DCMAKE_C_COMPILER=${COMPILER}")
Run("${CMAKE_COMMAND}" --build "${ROOT}/notes-build" --parallel 2)
Run("${CMAKE_CTEST_COMMAND}" --test-dir "${ROOT}/notes-build" --no-tests=error --output-on-failure)
Run("${CMAKE_COMMAND}" -E chdir "${ROOT}/elsewhere" "${ROOT}/notes-build/umicom_notes${_extension}" --check)
# A text import follows the canonical parser, not a separate GUI schema.
Run("${_tool}" export "${FRAMEWORK}/examples/designer_native/notes.umiapp" umicom_imported "${ROOT}/imported")
Run("${CMAKE_COMMAND}" -S "${ROOT}/imported" -B "${ROOT}/imported-build" -G Ninja
    "-DCMAKE_PREFIX_PATH=${_sdk}" -DUMICOM_NATIVE_PROJECT_GUI=OFF "-DCMAKE_C_COMPILER=${COMPILER}")
Run("${CMAKE_COMMAND}" --build "${ROOT}/imported-build" --parallel 2)
Run("${ROOT}/imported-build/umicom_imported${_extension}" --check)
# A GUI request must fail rather than quietly turn into a console placeholder.
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${ROOT}/notes" -B "${ROOT}/gui-missing" -G Ninja
    "-DCMAKE_PREFIX_PATH=${_sdk}" -DUMICOM_NATIVE_PROJECT_GUI=ON "-DCMAKE_C_COMPILER=${COMPILER}"
    RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
file(APPEND "${_log}" "Missing GUI request: ${_rc}\n${_out}${_err}\n")
if(_rc STREQUAL "0" OR NOT "${_out}${_err}" MATCHES "no native GTK adapter")
    message(FATAL_ERROR "Missing GUI dependency was not reported explicitly")
endif()
# Corrupt/incomplete source and existing destinations cannot be called exports.
file(WRITE "${ROOT}/bad.umiapp" "application notes\ncomponent root window -\nproperty root title \"unfinished\n")
execute_process(COMMAND "${_tool}" export "${ROOT}/bad.umiapp" bad "${ROOT}/bad-output" RESULT_VARIABLE _bad)
if(_bad STREQUAL "0" OR EXISTS "${ROOT}/bad-output")
    message(FATAL_ERROR "Incomplete quoted source produced output")
endif()
file(SHA256 "${ROOT}/notes/application.c" _before)
execute_process(COMMAND "${_tool}" notes "${ROOT}/notes" RESULT_VARIABLE _existing)
file(SHA256 "${ROOT}/notes/application.c" _after)
if(_existing STREQUAL "0" OR NOT _before STREQUAL _after)
    message(FATAL_ERROR "Existing project was changed")
endif()
# Independent installed-SDK consumer emits deliberately awkward UTF-8 C text.
file(MAKE_DIRECTORY "${ROOT}/fixture")
file(COPY "${FRAMEWORK}/tests/designer_native/generated_roundtrip.c" DESTINATION "${ROOT}/fixture")
file(WRITE "${ROOT}/fixture/CMakeLists.txt" "cmake_minimum_required(VERSION 3.24)\nproject(Fixture LANGUAGES C)\nfind_package(UmicomDesignerNative CONFIG REQUIRED)\nadd_executable(fixture generated_roundtrip.c)\ntarget_compile_definitions(fixture PRIVATE BUILD_FIXTURE)\nset_target_properties(fixture PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES)\ntarget_link_libraries(fixture PRIVATE Umicom::designer_native)\n")
Run("${CMAKE_COMMAND}" -S "${ROOT}/fixture" -B "${ROOT}/fixture-build" -G Ninja "-DCMAKE_PREFIX_PATH=${_sdk}" "-DCMAKE_C_COMPILER=${COMPILER}")
Run("${CMAKE_COMMAND}" --build "${ROOT}/fixture-build" --parallel 2)
Run("${ROOT}/fixture-build/fixture${_extension}" "${ROOT}/roundtrip")
file(COPY "${FRAMEWORK}/tests/designer_native/generated_roundtrip.c" DESTINATION "${ROOT}/roundtrip")
file(APPEND "${ROOT}/roundtrip/CMakeLists.txt" "\nadd_executable(roundtrip generated_roundtrip.c application.c)\nset_target_properties(roundtrip PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES)\ntarget_link_libraries(roundtrip PRIVATE Umicom::designer_native)\nadd_test(NAME application.roundtrip COMMAND roundtrip)\n")
Run("${CMAKE_COMMAND}" -S "${ROOT}/roundtrip" -B "${ROOT}/roundtrip-build" -G Ninja "-DCMAKE_PREFIX_PATH=${_sdk}" -DUMICOM_NATIVE_PROJECT_GUI=OFF "-DCMAKE_C_COMPILER=${COMPILER}")
Run("${CMAKE_COMMAND}" --build "${ROOT}/roundtrip-build" --parallel 2)
Run("${CMAKE_CTEST_COMMAND}" --test-dir "${ROOT}/roundtrip-build" --no-tests=error --output-on-failure)
message(STATUS "Installed SDK, native export, actual generated builds and exact-text constructor passed. No GUI was run.")
