set(UMICOM_CREATIVE_WORKSPACE_CASES
    project.initialise
    project.invalid_identity
    project.utf8_labels
    project.malformed_utf8
    project.settings_boundaries
    project.add_replace_remove
    project.failed_append_unchanged
    project.failed_replace_unchanged
    project.element_capacity
    project.layer_order
    project.unit_change_guard
    project.keys_start_at_zero
    project.key_sort_update
    project.key_bounds
    project.key_capacity
    project.note_timing
    project.note_invalid
    project.note_capacity
    project.failed_note_append_unchanged
    project.starters
    workspace.create_open
    workspace.undo_redo
    workspace.undo_branch
    workspace.history_capacity
    workspace.noop_padding
    workspace.expected_revision
    workspace.stale_handle
    workspace.reload_clears_history
    workspace.foreign_transaction
    workspace.missing_child
    workspace.corrupt_metadata
    workspace.delete_records_undo
    workspace.maximum_revision
    wire.round_trip
    wire.strict_numbers
    wire.invalid_tail_and_short_buffer
    scene.linear_sample
    scene.step_exact_key
    scene.hit_topmost
    scene.overlap_count
    scene.invalid_frame
    animation.extreme_endpoints
    animation.clamp_and_step
    play.sweep_prevents_tunnelling
    play.canvas_and_single_axis
    play.touch_and_move_away
    play.stale_revision
    play.reject_animated_scene
    export.svg_escaping
    export.svg_physical_units
    export.html_inert_and_branded
    export.storyboard_three_frames
    export.output_ownership
    export.invalid_input
    export.wave_header_and_silence
    export.wave_polyphony_bound
    export.write_new_no_overwrite
    sqlite.restart
    sqlite.atomic_failure
    sqlite.rollback_failure_poison
    sqlite.two_connections
    sqlite.corrupt_row_rejected
    workspace.content_conflict_same_revision
    workspace.notes_and_keys_round_trip
    wire.adversarial_bytes
    play.independent_integer_sweep
    export.maximum_duration
)
