# Umicom Framework | Education regression cases | Sammy Hegab | MIT
set(UMICOM_EDUCATION_WORKSPACE_CASES
    catalogue
    percentage_boundaries
    percentage_reference
    scoring_wraparound
    scoring_default
    open_no_write
    invalid_learner
    invalid_name
    unknown_lesson
    read_idempotent
    hint_idempotent
    notes_roundtrip
    notes_capacity
    notes_invalid_utf8
    notes_idempotent_clear
    quiz_requires_read
    quiz_invalid_answers
    quiz_prerequisite
    courses_independent
    quiz_feedback
    quiz_best_retained
    course_completion
    resume_progress
    stale_writer
    stale_noop
    learner_isolation
    stored_name
    transaction_busy
    journal_capacity
    report_escaping
    report_capacity
    corrupt_format
    corrupt_index
    corrupt_action
    corrupt_hex
    corrupt_null
    corrupt_utf8
    corrupt_quiz_state
    corrupt_leading_zero
    corrupt_unknown_record
    corrupt_extra_event
    corrupt_catalogue
    corrupt_count
    corrupt_missing_event
    orphan_event
    unrelated_records
    project_catalogue
    export_invalid_path
    sqlite_restart
    sqlite_connections
    sqlite_write_rollback
    sqlite_failure_second_write
    sqlite_failed_rollback
)
