/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: include/umicom/open_tms/open_tms.h
 *
 * PURPOSE:
 *   Aggregate the Framework-owned Umicom Open TMS treasury platform contracts.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
#ifndef UMICOM_OPEN_TMS_H
#define UMICOM_OPEN_TMS_H
#include "umicom/open_tms/types.h"
#include "umicom/open_tms/service.h"
#include "umicom/open_tms/fx_forward_book.h"
#include "umicom/open_tms/cash_book.h"
#include "umicom/open_tms/liquidity_ladder.h"
#include "umicom/open_tms/pricing_engine.h"
#include "umicom/open_tms/position_book.h"
#include "umicom/open_tms/risk_book.h"
#include "umicom/open_tms/settlement_book.h"
#include "umicom/open_tms/accounting_book.h"
#include "umicom/open_tms/reconciliation_book.h"
#include "umicom/open_tms/dashboard_service.h"
#include "umicom/open_tms/accounting/accrual.h"
#include "umicom/open_tms/accounting/double_entry.h"
#include "umicom/open_tms/accounting/event.h"
#include "umicom/open_tms/accounting/pnl.h"
#include "umicom/open_tms/accounting/posting.h"
#include "umicom/open_tms/accounting/reconciliation.h"
#include "umicom/open_tms/cash/account_coverage.h"
#include "umicom/open_tms/cash/currency_coverage.h"
#include "umicom/open_tms/cash/forecast_net.h"
#include "umicom/open_tms/cash/freshness.h"
#include "umicom/open_tms/cash/minimum_balance.h"
#include "umicom/open_tms/cash/projected_balance.h"
#include "umicom/open_tms/cash/settled_balance.h"
#include "umicom/open_tms/cash/shortfall.h"
#include "umicom/open_tms/cash/surplus.h"
#include "umicom/open_tms/cash/sweep_readiness.h"
#include "umicom/open_tms/dashboard/cash_health.h"
#include "umicom/open_tms/dashboard/liquidity_health.h"
#include "umicom/open_tms/dashboard/operations_health.h"
#include "umicom/open_tms/dashboard/risk_health.h"
#include "umicom/open_tms/dashboard/settlement_health.h"
#include "umicom/open_tms/fx_forward/audit.h"
#include "umicom/open_tms/fx_forward/confirmation.h"
#include "umicom/open_tms/fx_forward/forward_points.h"
#include "umicom/open_tms/fx_forward/forward_rate.h"
#include "umicom/open_tms/fx_forward/lifecycle.h"
#include "umicom/open_tms/fx_forward/maturity.h"
#include "umicom/open_tms/fx_forward/mtm.h"
#include "umicom/open_tms/fx_forward/notional.h"
#include "umicom/open_tms/fx_forward/settlement.h"
#include "umicom/open_tms/fx_forward/trade_readiness.h"
#include "umicom/open_tms/liquidity/bucket_coverage.h"
#include "umicom/open_tms/liquidity/buffer.h"
#include "umicom/open_tms/liquidity/concentration.h"
#include "umicom/open_tms/liquidity/coverage.h"
#include "umicom/open_tms/liquidity/funding_capacity.h"
#include "umicom/open_tms/liquidity/funding_requirement.h"
#include "umicom/open_tms/liquidity/gap.h"
#include "umicom/open_tms/liquidity/intraday.h"
#include "umicom/open_tms/liquidity/readiness.h"
#include "umicom/open_tms/liquidity/stress.h"
#include "umicom/open_tms/position/aggregation.h"
#include "umicom/open_tms/position/concentration.h"
#include "umicom/open_tms/position/currency_exposure.h"
#include "umicom/open_tms/position/gross_exposure.h"
#include "umicom/open_tms/position/mtm.h"
#include "umicom/open_tms/position/net_exposure.h"
#include "umicom/open_tms/position/readiness.h"
#include "umicom/open_tms/position/trade_coverage.h"
#include "umicom/open_tms/pricing/accrual.h"
#include "umicom/open_tms/pricing/curve_coverage.h"
#include "umicom/open_tms/pricing/discount_factor.h"
#include "umicom/open_tms/pricing/fixing_coverage.h"
#include "umicom/open_tms/pricing/forward_rate.h"
#include "umicom/open_tms/pricing/market_data.h"
#include "umicom/open_tms/pricing/present_value.h"
#include "umicom/open_tms/pricing/readiness.h"
#include "umicom/open_tms/pricing/spot.h"
#include "umicom/open_tms/pricing/valuation_quality.h"
#include "umicom/open_tms/reconciliation/breaks.h"
#include "umicom/open_tms/reconciliation/cash.h"
#include "umicom/open_tms/reconciliation/completion.h"
#include "umicom/open_tms/reconciliation/settlement.h"
#include "umicom/open_tms/reconciliation/trade.h"
#include "umicom/open_tms/risk/breach.h"
#include "umicom/open_tms/risk/counterparty.h"
#include "umicom/open_tms/risk/credit.h"
#include "umicom/open_tms/risk/limit_utilisation.h"
#include "umicom/open_tms/risk/liquidity.h"
#include "umicom/open_tms/risk/market.h"
#include "umicom/open_tms/risk/readiness.h"
#include "umicom/open_tms/risk/stress.h"
#include "umicom/open_tms/settlement/confirmation.h"
#include "umicom/open_tms/settlement/failure.h"
#include "umicom/open_tms/settlement/netting.h"
#include "umicom/open_tms/settlement/obligation.h"
#include "umicom/open_tms/settlement/queue.h"
#include "umicom/open_tms/settlement/readiness.h"
#include "umicom/open_tms/settlement/repair.h"
#include "umicom/open_tms/settlement/window.h"
#endif
