/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: include/umicom/umicom.h
 *
 * PURPOSE:
 *   Provide the aggregate public Framework include for applications that use
 *   the complete C23 foundation through the Umicom::Framework target.
 *
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
#ifndef UMICOM_UMICOM_H
#define UMICOM_UMICOM_H

#include "umicom/base/version.h"
#include "umicom/base/status.h"
#include "umicom/base/result.h"
#include "umicom/base/memory.h"

#include "umicom/diagnostics/diagnostic.h"
#include "umicom/diagnostics/log.h"
#include "umicom/diagnostics/hub.h"
#include "umicom/diagnostics/store.h"
#include "umicom/diagnostics/metrics.h"
#include "umicom/diagnostics/trace.h"
#include "umicom/diagnostics/audit.h"
#include "umicom/diagnostics/profiler.h"
#include "umicom/diagnostics/readiness.h"
#include "umicom/diagnostics/event_log.h"
#include "umicom/diagnostics/privacy_filter.h"
#include "umicom/diagnostics/crash_report.h"
#include "umicom/diagnostics/exporter.h"
#include "umicom/diagnostics/snapshot.h"

#include "umicom/messaging/message.h"
#include "umicom/messaging/event_bus.h"
#include "umicom/messaging/command_bus.h"
#include "umicom/messaging/query_bus.h"
#include "umicom/messaging/journal.h"
#include "umicom/messaging/payload.h"
#include "umicom/messaging/schema.h"
#include "umicom/messaging/channel.h"
#include "umicom/messaging/subscription.h"
#include "umicom/messaging/dispatcher.h"
#include "umicom/messaging/reliability.h"
#include "umicom/messaging/replay.h"
#include "umicom/messaging/inbox.h"
#include "umicom/messaging/outbox.h"
#include "umicom/messaging/dead_letter.h"
#include "umicom/messaging/idempotency.h"
#include "umicom/messaging/delivery_lease.h"
#include "umicom/messaging/transport.h"
#include "umicom/messaging/router.h"
#include "umicom/messaging/filter.h"
#include "umicom/messaging/transformer.h"
#include "umicom/messaging/aggregator.h"
#include "umicom/messaging/resequencer.h"
#include "umicom/messaging/flow.h"
#include "umicom/messaging/workflow.h"
#include "umicom/messaging/saga.h"
#include "umicom/messaging/topic.h"
#include "umicom/messaging/metrics.h"

#include "umicom/data/data_server.h"
#include "umicom/data/store.h"
#include "umicom/data/repository.h"
#include "umicom/data/transaction.h"
#include "umicom/data/schema_version.h"
#include "umicom/data/migration.h"
#include "umicom/data/sqlite.h"
#include "umicom/data/statement.h"
#include "umicom/data/row.h"
#include "umicom/data/blob_store.h"
#include "umicom/data/cache.h"
#include "umicom/data/metadata.h"
#include "umicom/data/lineage.h"
#include "umicom/data/backup.h"
#include "umicom/data/integrity.h"
#include "umicom/data/message_store.h"
#include "umicom/data/journal_store.h"

#include "umicom/platform/config.h"
#include "umicom/platform/settings.h"
#include "umicom/platform/path.h"
#include "umicom/platform/filesystem.h"
#include "umicom/platform/directory.h"
#include "umicom/platform/cancellation.h"
#include "umicom/platform/atomic_file.h"
#include "umicom/platform/threading.h"
#include "umicom/platform/task.h"
#include "umicom/platform/task_queue.h"
#include "umicom/platform/document_store.h"
#include "umicom/platform/workspace_graph.h"
#include "umicom/platform/file_index.h"
#include "umicom/platform/search.h"
#include "umicom/platform/session_store.h"
#include "umicom/platform/recovery.h"
#include "umicom/platform/process.h"
#include "umicom/platform/process_supervisor.h"
#include "umicom/platform/watcher.h"
#include "umicom/platform/workspace.h"
#include "umicom/platform/document.h"
#include "umicom/platform/clock.h"

#include "umicom/security/policy.h"
#include "umicom/security/secrets.h"
#include "umicom/security/identity.h"
#include "umicom/security/permission.h"
#include "umicom/security/role.h"
#include "umicom/security/session.h"
#include "umicom/security/credential.h"
#include "umicom/security/token.h"
#include "umicom/security/secret_provider.h"
#include "umicom/security/redaction.h"
#include "umicom/security/workspace_trust.h"
#include "umicom/security/event.h"
#include "umicom/security/authorisation.h"
#include "umicom/security/context.h"

#include "umicom/ui/contracts.h"
#include "umicom/ui/headless.h"
#include "umicom/ui/gtk4.h"

#include "umicom/build/types.h"
#include "umicom/build/profile.h"
#include "umicom/build/preset.h"
#include "umicom/build/diagnostic.h"
#include "umicom/build/parser.h"
#include "umicom/build/result.h"
#include "umicom/build/history.h"
#include "umicom/build/provider.h"
#include "umicom/build/cmake_provider.h"
#include "umicom/build/ninja_provider.h"
#include "umicom/build/ctest_provider.h"
#include "umicom/build/runner.h"

#include "umicom/testing/types.h"
#include "umicom/testing/case.h"
#include "umicom/testing/result.h"
#include "umicom/testing/suite.h"
#include "umicom/testing/registry.h"
#include "umicom/testing/discovery.h"
#include "umicom/testing/runner.h"
#include "umicom/testing/report.h"
#include "umicom/testing/ctest_adapter.h"

#include "umicom/terminal/types.h"
#include "umicom/terminal/command.h"
#include "umicom/terminal/transcript.h"
#include "umicom/terminal/environment.h"
#include "umicom/terminal/session.h"
#include "umicom/terminal/manager.h"
#include "umicom/terminal/shell.h"

#include "umicom/protocol/types.h"
#include "umicom/protocol/framing.h"
#include "umicom/protocol/json.h"
#include "umicom/protocol/json_rpc.h"
#include "umicom/protocol/transport.h"
#include "umicom/protocol/client.h"
#include "umicom/protocol/lsp.h"
#include "umicom/protocol/lsp_document.h"
#include "umicom/protocol/dap.h"
#include "umicom/protocol/dap_breakpoint.h"

#include "umicom/vcs/types.h"
#include "umicom/vcs/change.h"
#include "umicom/vcs/status.h"
#include "umicom/vcs/branch.h"
#include "umicom/vcs/commit.h"
#include "umicom/vcs/history.h"
#include "umicom/vcs/diff.h"
#include "umicom/vcs/provider.h"
#include "umicom/vcs/repository.h"
#include "umicom/vcs/git_cli.h"

#include "umicom/runtime/capability_registry.h"
#include "umicom/runtime/service_registry.h"
#include "umicom/runtime/command_registry.h"
#include "umicom/runtime/health.h"
#include "umicom/runtime/capability_catalogue.h"
#include "umicom/runtime/application_manifest.h"
#include "umicom/runtime/suite.h"
#include "umicom/runtime/module.h"
#include "umicom/runtime/module_registry.h"
#include "umicom/runtime/master_controller.h"
#include "umicom/runtime/scheduler.h"

#include "umicom/toolchain/tool.h"
#include "umicom/toolchain/profile.h"
#include "umicom/toolchain/discovery.h"
#include "umicom/toolchain/environment.h"
#include "umicom/toolchain/dependency.h"
#include "umicom/toolchain/build.h"

#include "umicom/resilience/backoff.h"
#include "umicom/resilience/retry.h"
#include "umicom/resilience/circuit_breaker.h"
#include "umicom/resilience/bulkhead.h"
#include "umicom/resilience/rate_limiter.h"
#include "umicom/resilience/restart_policy.h"
#include "umicom/resilience/deadline.h"
#include "umicom/resilience/fault.h"
#include "umicom/resilience/health_gate.h"
#include "umicom/resilience/supervisor.h"

#include "umicom/repository/repository.h"
#include "umicom/scaffold/scaffold.h"
#include "umicom/scaffold/repository.h"
#include "umicom/plugin/plugin.h"
#include "umicom/plugin/state.h"
#include "umicom/plugin/manifest.h"
#include "umicom/plugin/permission.h"
#include "umicom/plugin/contribution.h"
#include "umicom/plugin/registry.h"
#include "umicom/plugin/checksum.h"
#include "umicom/plugin/signature.h"
#include "umicom/plugin/compatibility.h"
#include "umicom/plugin/discovery.h"
#include "umicom/plugin/loader.h"
#include "umicom/plugin/lifecycle.h"
#include "umicom/plugin/host.h"

#endif
