/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: include/umicom/workbench_context_event/workbench_context_event.h
 *
 * PURPOSE:
 *   Expose the complete toolkit-neutral workbench interaction event platform.
 *
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
#ifndef UMICOM_WORKBENCH_CONTEXT_EVENT_WORKBENCH_CONTEXT_EVENT_H
#define UMICOM_WORKBENCH_CONTEXT_EVENT_WORKBENCH_CONTEXT_EVENT_H

#include "umicom/workbench_context_event/account_record.h"
#include "umicom/workbench_context_event/ai_record.h"
#include "umicom/workbench_context_event/application_binding.h"
#include "umicom/workbench_context_event/application_record.h"
#include "umicom/workbench_context_event/audit_record.h"
#include "umicom/workbench_context_event/backpressure_record.h"
#include "umicom/workbench_context_event/bookmark.h"
#include "umicom/workbench_context_event/builders.h"
#include "umicom/workbench_context_event/capability.h"
#include "umicom/workbench_context_event/caret_record.h"
#include "umicom/workbench_context_event/causation_record.h"
#include "umicom/workbench_context_event/coalescer.h"
#include "umicom/workbench_context_event/coalescing_policy.h"
#include "umicom/workbench_context_event/command.h"
#include "umicom/workbench_context_event/consumer_record.h"
#include "umicom/workbench_context_event/context_record.h"
#include "umicom/workbench_context_event/controller_state.h"
#include "umicom/workbench_context_event/correlation_record.h"
#include "umicom/workbench_context_event/counter.h"
#include "umicom/workbench_context_event/debug_record.h"
#include "umicom/workbench_context_event/dedupe_record.h"
#include "umicom/workbench_context_event/delivery_record.h"
#include "umicom/workbench_context_event/delivery_state.h"
#include "umicom/workbench_context_event/diagnostic.h"
#include "umicom/workbench_context_event/diagnostic_record.h"
#include "umicom/workbench_context_event/duplicate_record.h"
#include "umicom/workbench_context_event/editor_record.h"
#include "umicom/workbench_context_event/endpoint_binding.h"
#include "umicom/workbench_context_event/envelope_record.h"
#include "umicom/workbench_context_event/event.h"
#include "umicom/workbench_context_event/event_binding.h"
#include "umicom/workbench_context_event/event_group_record.h"
#include "umicom/workbench_context_event/event_record.h"
#include "umicom/workbench_context_event/failure_record.h"
#include "umicom/workbench_context_event/filter.h"
#include "umicom/workbench_context_event/group_binding.h"
#include "umicom/workbench_context_event/health_record.h"
#include "umicom/workbench_context_event/history_record.h"
#include "umicom/workbench_context_event/instrument_record.h"
#include "umicom/workbench_context_event/journal_entry.h"
#include "umicom/workbench_context_event/latency_sample.h"
#include "umicom/workbench_context_event/media_record.h"
#include "umicom/workbench_context_event/metric.h"
#include "umicom/workbench_context_event/observer_record.h"
#include "umicom/workbench_context_event/panel_binding.h"
#include "umicom/workbench_context_event/payload_mapper.h"
#include "umicom/workbench_context_event/permission.h"
#include "umicom/workbench_context_event/policy.h"
#include "umicom/workbench_context_event/processing_state.h"
#include "umicom/workbench_context_event/producer_record.h"
#include "umicom/workbench_context_event/profile.h"
#include "umicom/workbench_context_event/profile_binding.h"
#include "umicom/workbench_context_event/project_record.h"
#include "umicom/workbench_context_event/query.h"
#include "umicom/workbench_context_event/queue.h"
#include "umicom/workbench_context_event/queue_state.h"
#include "umicom/workbench_context_event/rate_sample.h"
#include "umicom/workbench_context_event/rejection_record.h"
#include "umicom/workbench_context_event/replay_request.h"
#include "umicom/workbench_context_event/retry_record.h"
#include "umicom/workbench_context_event/route.h"
#include "umicom/workbench_context_event/route_hop.h"
#include "umicom/workbench_context_event/selection_record.h"
#include "umicom/workbench_context_event/service.h"
#include "umicom/workbench_context_event/session_record.h"
#include "umicom/workbench_context_event/snapshot_item.h"
#include "umicom/workbench_context_event/source_control_record.h"
#include "umicom/workbench_context_event/source_descriptor.h"
#include "umicom/workbench_context_event/source_registry.h"
#include "umicom/workbench_context_event/source_state.h"
#include "umicom/workbench_context_event/subscription.h"
#include "umicom/workbench_context_event/terminal_record.h"
#include "umicom/workbench_context_event/test_record.h"
#include "umicom/workbench_context_event/throttle_policy.h"
#include "umicom/workbench_context_event/trace.h"
#include "umicom/workbench_context_event/trade_record.h"
#include "umicom/workbench_context_event/types.h"
#include "umicom/workbench_context_event/workspace_binding.h"
#include "umicom/workbench_context_event/workspace_record.h"

#endif
