/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: src/strategy_research/strategy_research_internal.h
 *
 * PURPOSE:
 *   Share deterministic research calculations while canonical trading, chart,
 *   replay and execution services remain authoritative.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/
#ifndef UMICOM_STRATEGY_RESEARCH_INTERNAL_H
#define UMICOM_STRATEGY_RESEARCH_INTERNAL_H

#include "umicom/strategy_research/types.h"

typedef enum UmiStrategyResearchPolicyKind {
    UMI_STRATEGY_POLICY_SCORE = 1,
    UMI_STRATEGY_POLICY_CONFIDENCE,
    UMI_STRATEGY_POLICY_ENTRY_GATE,
    UMI_STRATEGY_POLICY_EXIT_GATE,
    UMI_STRATEGY_POLICY_POSITION_SIZE,
    UMI_STRATEGY_POLICY_STOP_DISTANCE,
    UMI_STRATEGY_POLICY_TARGET_DISTANCE,
    UMI_STRATEGY_POLICY_RISK_REWARD,
    UMI_STRATEGY_POLICY_EXPIRY,
    UMI_STRATEGY_POLICY_READINESS,
    UMI_STRATEGY_POLICY_NET_PROFIT,
    UMI_STRATEGY_POLICY_GROSS_PROFIT,
    UMI_STRATEGY_POLICY_GROSS_LOSS,
    UMI_STRATEGY_POLICY_WIN_RATE,
    UMI_STRATEGY_POLICY_AVG_WIN,
    UMI_STRATEGY_POLICY_AVG_LOSS,
    UMI_STRATEGY_POLICY_PROFIT_FACTOR,
    UMI_STRATEGY_POLICY_EXPECTANCY,
    UMI_STRATEGY_POLICY_MAX_DRAWDOWN,
    UMI_STRATEGY_POLICY_RECOVERY_FACTOR,
    UMI_STRATEGY_POLICY_COUNT,
    UMI_STRATEGY_POLICY_TURNOVER,
    UMI_STRATEGY_POLICY_EXPOSURE,
    UMI_STRATEGY_POLICY_STREAK,
    UMI_STRATEGY_POLICY_SHARPE,
    UMI_STRATEGY_POLICY_SORTINO,
    UMI_STRATEGY_POLICY_CALMAR,
    UMI_STRATEGY_POLICY_ANNUALISED_RETURN,
    UMI_STRATEGY_POLICY_ANNUALISED_VOL,
    UMI_STRATEGY_POLICY_DOWNSIDE_DEV,
    UMI_STRATEGY_POLICY_PAYOFF,
    UMI_STRATEGY_POLICY_ULCER,
    UMI_STRATEGY_POLICY_EFFICIENCY,
    UMI_STRATEGY_POLICY_STABILITY,
    UMI_STRATEGY_POLICY_PROGRESS,
    UMI_STRATEGY_POLICY_SPEED,
    UMI_STRATEGY_POLICY_EVENT_RATE,
    UMI_STRATEGY_POLICY_GAP_COUNT,
    UMI_STRATEGY_POLICY_GAP_RATIO,
    UMI_STRATEGY_POLICY_CLOCK_DRIFT,
    UMI_STRATEGY_POLICY_SEEK_DISTANCE,
    UMI_STRATEGY_POLICY_DATA_QUALITY,
    UMI_STRATEGY_POLICY_CHECKPOINT,
    UMI_STRATEGY_POLICY_OBJECTIVE,
    UMI_STRATEGY_POLICY_RANK,
    UMI_STRATEGY_POLICY_OVERFIT_GAP,
    UMI_STRATEGY_POLICY_WALK_FORWARD,
    UMI_STRATEGY_POLICY_ROBUSTNESS,
    UMI_STRATEGY_POLICY_SENSITIVITY,
    UMI_STRATEGY_POLICY_PARETO,
    UMI_STRATEGY_POLICY_EARLY_STOP,
    UMI_STRATEGY_POLICY_BUDGET,
    UMI_STRATEGY_POLICY_SMA,
    UMI_STRATEGY_POLICY_EMA,
    UMI_STRATEGY_POLICY_RSI,
    UMI_STRATEGY_POLICY_ATR,
    UMI_STRATEGY_POLICY_VWAP,
    UMI_STRATEGY_POLICY_BOLLINGER,
    UMI_STRATEGY_POLICY_MACD,
    UMI_STRATEGY_POLICY_ROC,
    UMI_STRATEGY_POLICY_VOLATILITY,
    UMI_STRATEGY_POLICY_RANGE,
    UMI_STRATEGY_POLICY_CROSSOVER,
    UMI_STRATEGY_POLICY_TREND,
    UMI_STRATEGY_POLICY_SUPPORT_DISTANCE,
    UMI_STRATEGY_POLICY_RESISTANCE_DISTANCE,
    UMI_STRATEGY_POLICY_VOLUME_RATIO,
    UMI_STRATEGY_POLICY_SLIPPAGE,
    UMI_STRATEGY_POLICY_COMMISSION,
    UMI_STRATEGY_POLICY_FILL_RATIO,
    UMI_STRATEGY_POLICY_LATENCY,
    UMI_STRATEGY_POLICY_TRADE_PNL,
    UMI_STRATEGY_POLICY_CASH_CHANGE,
    UMI_STRATEGY_POLICY_POSITION_CHANGE,
    UMI_STRATEGY_POLICY_NOTIONAL,
    UMI_STRATEGY_POLICY_EVIDENCE,
    UMI_STRATEGY_POLICY_PROVENANCE
} UmiStrategyResearchPolicyKind;

typedef struct UmiStrategyResearchPolicy {
    const char *id;
    const char *label;
    UmiStrategyResearchPolicyKind kind;
    double threshold;
    double warning;
    double weightOne;
    double weightTwo;
    double weightThree;
    double weightFour;
} UmiStrategyResearchPolicy;

UmiStatus umi_strategy_research_evaluate_policy(
    const UmiStrategyResearchPolicy *policy,
    const UmiStrategyResearchInput *input,
    UmiStrategyResearchSnapshot *outSnapshot);

#endif
