#-----------------------------------------------------------------------------
# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Exercise real CMake integration in a NEW disposable build directory. Retain
# every log. Never edit the caller's source, cache, installation or broker state.
#-----------------------------------------------------------------------------
cmake_minimum_required(VERSION 3.24)
foreach(_required CASE FRAMEWORK PROBE_ROOT HOST_GENERATOR)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "Missing ${_required}")
    endif()
endforeach()
set(_cases deferred immediate mixed repeated missing partial tests_off reconfigure regenerate installed)
if(NOT CASE IN_LIST _cases)
    message(FATAL_ERROR "Unknown integration case: ${CASE}")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef _token)
set(RUN "${PROBE_ROOT}/${CASE}-${_token}")
if(EXISTS "${RUN}")
    message(FATAL_ERROR "Refusing an existing probe directory: ${RUN}")
endif()
file(MAKE_DIRECTORY "${RUN}")
set(_source "${RUN}/source with spaces")
set(_build "${RUN}/build with spaces")
file(COPY "${CMAKE_CURRENT_LIST_DIR}/probe/" DESTINATION "${_source}")
get_filename_component(_cmake_directory "${CMAKE_COMMAND}" DIRECTORY)
find_program(_ctest NAMES ctest HINTS "${_cmake_directory}" NO_DEFAULT_PATH REQUIRED)
function(Execute step)
    execute_process(COMMAND ${ARGN}
        RESULT_VARIABLE _status OUTPUT_FILE "${RUN}/${step}.out.txt"
        ERROR_FILE "${RUN}/${step}.err.txt" TIMEOUT 180)
    if(NOT "${_status}" STREQUAL "0")
        file(READ "${RUN}/${step}.err.txt" _error LIMIT 4096)
        message(FATAL_ERROR "${step} failed (${_status}). Logs: ${RUN}\n${_error}")
    endif()
endfunction()
set(_common -G "${HOST_GENERATOR}" -DCMAKE_BUILD_TYPE=Release)
if(HOST_TOOLCHAIN)
    list(APPEND _common "-DCMAKE_TOOLCHAIN_FILE=${HOST_TOOLCHAIN}")
elseif(HOST_COMPILER)
    list(APPEND _common "-DCMAKE_C_COMPILER=${HOST_COMPILER}")
endif()
if(HOST_PLATFORM)
    list(APPEND _common -A "${HOST_PLATFORM}")
endif()
if(HOST_TOOLSET)
    list(APPEND _common -T "${HOST_TOOLSET}")
endif()
set(_mode "${CASE}")
if(CASE MATCHES "^(tests_off|reconfigure|regenerate|installed)$")
    set(_mode deferred)
endif()
set(_testing ON)
if(CASE STREQUAL "tests_off")
    set(_testing OFF)
endif()
Execute(configure "${CMAKE_COMMAND}" -S "${_source}" -B "${_build}" ${_common}
    "-DFRAMEWORK=${FRAMEWORK}" "-DMODE=${_mode}" "-DBUILD_TESTING=${_testing}"
    -DPROBE_REGISTER_MATRIX=OFF -Werror=dev)
Execute(build "${CMAKE_COMMAND}" --build "${_build}" --config Release --parallel 2)
# Comparing names, not just a count, catches both omitted and duplicate tests.
function(CheckInventory stage)
    Execute(${stage} "${_ctest}" --test-dir "${_build}" -C Release --show-only=json-v1)
    file(READ "${RUN}/${stage}.out.txt" _json)
    string(JSON _count LENGTH "${_json}" tests)
    set(_actual)
    if(_count GREATER 0)
        math(EXPR _last "${_count}-1")
        foreach(_index RANGE 0 ${_last})
            string(JSON _name GET "${_json}" tests ${_index} name)
            list(APPEND _actual "${_name}")
        endforeach()
    endif()
    set(_expected)
    file(READ "${_build}/integration-result.txt" _result)
    if(_testing AND NOT _mode STREQUAL "missing")
        file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/expected-tests.txt" _entries)
        foreach(_entry IN LISTS _entries)
            if(_entry MATCHES "^(COMMON|LINUX|LINUX_WRAP)[|](framework[.].+)$")
                set(_kind "${CMAKE_MATCH_1}")
                set(_name "${CMAKE_MATCH_2}")
                if(_mode STREQUAL "partial" AND NOT _name MATCHES "^framework[.]ibkr_connection[.]")
                    continue()
                endif()
                if(_kind STREQUAL "COMMON" OR
                    (_kind STREQUAL "LINUX" AND _result MATCHES "system=Linux") OR
                    (_kind STREQUAL "LINUX_WRAP" AND _result MATCHES "system=Linux" AND
                        _result MATCHES "compiler=(GNU|Clang)"))
                    list(APPEND _expected "${_name}")
                endif()
            elseif(NOT _entry MATCHES "^#" AND NOT _entry STREQUAL "")
                message(FATAL_ERROR "Invalid expected-test record: ${_entry}")
            endif()
        endforeach()
        if(NOT _mode STREQUAL "partial")
            list(APPEND _expected framework.component_integration.lesson)
        endif()
    endif()
    list(SORT _actual)
    list(SORT _expected)
    if(NOT "${_actual}" STREQUAL "${_expected}")
        file(WRITE "${RUN}/expected-inventory.txt" "${_expected}\n")
        file(WRITE "${RUN}/actual-inventory.txt" "${_actual}\n")
        message(FATAL_ERROR "Test inventory changed. Expected and actual lists retained in ${RUN}")
    endif()
    message(STATUS "${stage}: exact ${_count}-test inventory agrees")
endfunction()
CheckInventory(inventory)
if(CASE STREQUAL "reconfigure")
    set(_iteration_number 0)
    foreach(_iteration IN ITEMS immediate deferred immediate deferred)
        math(EXPR _iteration_number "${_iteration_number}+1")
        set(_mode "${_iteration}")
        Execute(reconfigure-${_iteration_number}-${_iteration} "${CMAKE_COMMAND}" -S "${_source}" -B "${_build}"
            "-DMODE=${_mode}" -Werror=dev)
        Execute(rebuild-${_iteration_number}-${_iteration} "${CMAKE_COMMAND}" --build "${_build}" --config Release --parallel 2)
        CheckInventory(reinventory-${_iteration_number}-${_iteration})
    endforeach()
elseif(CASE STREQUAL "regenerate")
    # Trigger the same automatic regenerate-during-build route in the supplied
    # failure log. The edited file is a private COPY of this probe only.
    Execute(wait-for-stamp "${CMAKE_COMMAND}" -E sleep 1)
    file(APPEND "${_source}/CMakeLists.txt" "\n# Deliberate probe regeneration trigger.\n")
    Execute(regenerate-build "${CMAKE_COMMAND}" --build "${_build}" --config Release --parallel 2)
    CheckInventory(regenerated-inventory)
endif()
if(NOT HOST_CROSSCOMPILING AND _testing AND NOT _mode STREQUAL "missing")
    Execute(tests "${_ctest}" --test-dir "${_build}" -C Release
        --parallel 2 --no-tests=error --output-on-failure)
elseif(HOST_CROSSCOMPILING)
    file(WRITE "${RUN}/execution-not-run.txt" "Cross-compiling: compiled targets were not executed.\n")
endif()
if(CASE STREQUAL "installed")
    set(_prefix "${RUN}/installed SDK")
    Execute(install "${CMAKE_COMMAND}" --install "${_build}" --config Release --prefix "${_prefix}")
    set(_client "${RUN}/client build")
    Execute(client-configure "${CMAKE_COMMAND}"
        -S "${FRAMEWORK}/examples/component_integration/client" -B "${_client}" ${_common}
        "-DCMAKE_PREFIX_PATH=${_prefix}" -Werror=dev)
    Execute(client-build "${CMAKE_COMMAND}" --build "${_client}" --config Release --parallel 2)
    if(NOT HOST_CROSSCOMPILING)
        Execute(client-test "${_ctest}" --test-dir "${_client}" -C Release --no-tests=error --output-on-failure)
    endif()
endif()
message(STATUS "Integration case ${CASE} complete; logs retained in ${RUN}")
