# Build a disposable copy, demonstrate a detected behavioural defect, restore.
file(MAKE_DIRECTORY "${OUTPUT}")
file(COPY "${PROJECT}/" DESTINATION "${OUTPUT}/source")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${OUTPUT}/source" -B "${OUTPUT}/build"
    -G "${GENERATOR}" "-DCMAKE_C_COMPILER=${COMPILER}" -DCMAKE_BUILD_TYPE=Release
    RESULT_VARIABLE _configured OUTPUT_VARIABLE _out ERROR_VARIABLE _err TIMEOUT 30)
file(WRITE "${OUTPUT}/configure.txt" "${_out}${_err}")
if(NOT _configured STREQUAL "0")
    message(FATAL_ERROR "Practice project configuration failed: ${_err}")
endif()
function(run_practice expectation label)
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${OUTPUT}/build" --config Release --parallel 2
        RESULT_VARIABLE _built OUTPUT_VARIABLE _out ERROR_VARIABLE _err TIMEOUT 30)
    file(WRITE "${OUTPUT}/${label}-build.txt" "${_out}${_err}")
    if(NOT _built STREQUAL "0")
        message(FATAL_ERROR "Practice build failed: ${_err}")
    endif()
    execute_process(COMMAND "${CTEST}" --test-dir "${OUTPUT}/build" -C Release --no-tests=error --output-on-failure
        RESULT_VARIABLE _tested OUTPUT_VARIABLE _out ERROR_VARIABLE _err TIMEOUT 30)
    file(WRITE "${OUTPUT}/${label}-tests.txt" "${_out}${_err}")
    if(expectation STREQUAL "pass" AND NOT _tested STREQUAL "0")
        message(FATAL_ERROR "Correct practice tests failed: ${_out}${_err}")
    elseif(expectation STREQUAL "fail" AND _tested STREQUAL "0")
        message(FATAL_ERROR "The deliberate counting error was not detected")
    endif()
endfunction()
run_practice(pass correct)
file(READ "${OUTPUT}/source/notes.c" _original)
string(REPLACE "*outCount = count;" "*outCount = count + 1U;" _mutated "${_original}")
if(_mutated STREQUAL _original)
    message(FATAL_ERROR "Practice mutation target was not found")
endif()
file(WRITE "${OUTPUT}/source/notes.c" "${_mutated}")
run_practice(fail deliberate-fault)
file(WRITE "${OUTPUT}/source/notes.c" "${_original}")
run_practice(pass restored)
