# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
file(MAKE_DIRECTORY "${DEST}")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${ROOT}/tools/release_baseline" -B "${DEST}" -G Ninja "-DCMAKE_C_COMPILER=${COMPILER}" -DCMAKE_BUILD_TYPE=Release -DUMICOM_RELEASE_BASELINE_RETAIN_LIFECYCLE=OFF -DUMICOM_RELEASE_BASELINE_COMPOSITION_TESTS=OFF "-DUMICOM_RELEASE_BASELINE_DEFER=${DEFER}" RESULT_VARIABLE result OUTPUT_FILE "${DEST}/configure.txt" ERROR_FILE "${DEST}/configure-errors.txt")
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Composition configure failed; see ${DEST}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${DEST}" --parallel 2 RESULT_VARIABLE result OUTPUT_FILE "${DEST}/build.txt" ERROR_FILE "${DEST}/build-errors.txt")
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Composition build failed; see ${DEST}")
endif()
execute_process(COMMAND "${CMAKE_CTEST_COMMAND}" --test-dir "${DEST}" --no-tests=error --output-on-failure RESULT_VARIABLE result OUTPUT_FILE "${DEST}/tests.txt" ERROR_FILE "${DEST}/test-errors.txt")
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Composition tests failed; see ${DEST}")
endif()
