# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Embed canonical project files, not a separately maintained copy of their logic.
# Regeneration depends on every input, so an edited teaching file is rebuilt.
if(NOT DEFINED ROOT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "ROOT and OUTPUT are required")
endif()
set(result "/* Generated from canonical Umicom teaching projects. Do not edit. */\n#include \"umicom/education_workspace/projects.h\"\n#include <string.h>\n")
set(serial 0)
foreach(project IN ITEMS notes assembly framework)
    file(GLOB files LIST_DIRECTORIES FALSE "${ROOT}/${project}/*")
    list(SORT files)
    set(entries "")
    foreach(path IN LISTS files)
        get_filename_component(name "${path}" NAME)
        file(READ "${path}" bytes HEX)
        string(REGEX REPLACE "(..)" "0x\\1," values "${bytes}")
        string(APPEND result "static const unsigned char resource_${serial}[] = {${values}0};\n")
        string(APPEND entries "    {\"${name}\",resource_${serial},sizeof resource_${serial}-1U},\n")
        math(EXPR serial "${serial}+1")
    endforeach()
    string(APPEND result "static const UmiEducationProjectFile ${project}_files[] = {\n${entries}};\n")
endforeach()
string(APPEND result "size_t UmiEducationProjectFileCount(const char *id) { if(id==NULL)return 0U;\n")
foreach(project IN ITEMS notes assembly framework)
    string(APPEND result "if(strcmp(id,\"${project}\")==0)return sizeof ${project}_files/sizeof ${project}_files[0];\n")
endforeach()
string(APPEND result "return 0U;}\nUmiStatus UmiEducationProjectFileAt(const char *id,size_t i,UmiEducationProjectFile *out) { if(id==NULL||out==NULL)return UMI_STATUS_INVALID_ARGUMENT;if(i>=UmiEducationProjectFileCount(id))return UMI_STATUS_NOT_FOUND;\n")
foreach(project IN ITEMS notes assembly framework)
    string(APPEND result "if(strcmp(id,\"${project}\")==0){*out=${project}_files[i];return UMI_STATUS_OK;}\n")
endforeach()
string(APPEND result "return UMI_STATUS_NOT_FOUND;}\n")
file(WRITE "${OUTPUT}.tmp" "${result}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${OUTPUT}.tmp" "${OUTPUT}" COMMAND_ERROR_IS_FATAL ANY)
file(REMOVE "${OUTPUT}.tmp")
