# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-encoded-limits-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_encoded_limits.c")
    target_link_libraries(umicom-document-encoded-limits-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-encoded-limits-test)
    umicom_apply_sanitizers(umicom-document-encoded-limits-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-encoded-limits-test)
    endif()
    foreach(case utf8-bom-limit utf16-le utf16-be utf16-crlf decoded-limit serialized-limit reload external source-range)
        add_test(NAME framework.document.encoded_limits.${case} COMMAND umicom-document-encoded-limits-test ${case})
        set_tests_properties(framework.document.encoded_limits.${case} PROPERTIES TIMEOUT 180 LABELS "framework;document;format;history;regression")
    endforeach()
endif()
