# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Shared reviewed chat composes existing connection, credential and HTTP owners.
include_guard(GLOBAL)
include(GNUInstallDirs)
set(_umicom_provider_chat_root "${CMAKE_CURRENT_LIST_DIR}/..")
add_library(umicom_provider_chat STATIC
    "${_umicom_provider_chat_root}/src/provider_chat/plan.c"
    "${_umicom_provider_chat_root}/src/provider_chat/codec.c")
# Keep local history beside reviewed chat rather than changing the small-message ABI.
target_sources(umicom_provider_chat PRIVATE
    "${_umicom_provider_chat_root}/src/provider_chat/history.c"
    "${_umicom_provider_chat_root}/src/provider_chat/history_context.c")
add_library(Umicom::provider_chat ALIAS umicom_provider_chat)
set_target_properties(umicom_provider_chat PROPERTIES EXPORT_NAME provider_chat C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
target_include_directories(umicom_provider_chat PUBLIC $<BUILD_INTERFACE:${_umicom_provider_chat_root}/include> $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
target_link_libraries(umicom_provider_chat PUBLIC Umicom::provider_connection_checks PRIVATE Umicom::developer Umicom::ai)
umicom_apply_warnings(umicom_provider_chat)
umicom_apply_sanitizers(umicom_provider_chat)
install(TARGETS umicom_provider_chat EXPORT UmicomFrameworkTargets ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT Framework)
install(FILES "${_umicom_provider_chat_root}/docs/learning/chat-with-saved-connections.html" DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/learning COMPONENT Learning)

if(TARGET umicom_ui_gtk4)
    target_sources(umicom_ui_gtk4 PRIVATE
        "${_umicom_provider_chat_root}/adapters/gtk4/provider_chat_panel_gtk4.c"
        "${_umicom_provider_chat_root}/adapters/gtk4/provider_chat_worker_gtk4.c"
        "${_umicom_provider_chat_root}/adapters/gtk4/provider_chat_window_gtk4.c")
    # Context transfer shares the native owner without extending editor lifetime.
    target_sources(umicom_ui_gtk4 PRIVATE
        "${_umicom_provider_chat_root}/adapters/gtk4/provider_connections_context_gtk4.c")
    target_sources(umicom_ui_gtk4 PRIVATE "${_umicom_provider_chat_root}/adapters/gtk4/provider_chat_history_gtk4.c")
    target_link_libraries(umicom_ui_gtk4 PUBLIC Umicom::provider_chat)
endif()

if(BUILD_TESTING)
    foreach(group plan codec)
        add_executable(umicom-provider-chat-${group}-test "${_umicom_provider_chat_root}/tests/provider_chat/test_${group}.c")
        target_link_libraries(umicom-provider-chat-${group}-test PRIVATE Umicom::provider_chat)
        umicom_apply_warnings(umicom-provider-chat-${group}-test)
        umicom_apply_sanitizers(umicom-provider-chat-${group}-test)
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(umicom-provider-chat-${group}-test)
        endif()
    endforeach()
    foreach(case remote local immutable denied wrong-password stale changed-after-auth cancel cancel-after-auth timeout invalid-input scope chat-format)
        add_test(NAME framework.provider_chat.plan.${case} COMMAND umicom-provider-chat-plan-test ${case})
        set_tests_properties(framework.provider_chat.plan.${case} PROPERTIES TIMEOUT 30 LABELS "framework;provider-chat;privacy;regression")
    endforeach()
    foreach(case chat responses refusal length reasoning-limit tools response-tool duplicate duplicate-optional error trailing nul empty capacity)
        add_test(NAME framework.provider_chat.codec.${case} COMMAND umicom-provider-chat-codec-test ${case})
        set_tests_properties(framework.provider_chat.codec.${case} PROPERTIES TIMEOUT 20 LABELS "framework;provider-chat;json;regression")
    endforeach()
endif()

if(BUILD_TESTING AND TARGET umicom_ui_gtk4)
    add_executable(umicom-provider-chat-gtk-test "${_umicom_provider_chat_root}/tests/provider_chat/test_gtk4.c")
    target_link_libraries(umicom-provider-chat-gtk-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-provider-chat-gtk-test)
    umicom_apply_sanitizers(umicom-provider-chat-gtk-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-provider-chat-gtk-test)
    endif()
    foreach(case send no-approval edit password-edit stale-review cancel retained denied)
        file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/provider-chat-tests/${case}")
        add_test(NAME framework.provider_chat.gtk4.${case} COMMAND umicom-provider-chat-gtk-test ${case})
        set_tests_properties(framework.provider_chat.gtk4.${case} PROPERTIES TIMEOUT 40 SKIP_RETURN_CODE 77
            WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/provider-chat-tests/${case}" LABELS "framework;provider-chat;gtk4;privacy;ownership;regression")
    endforeach()
endif()
if(BUILD_TESTING AND UMICOM_PROVIDER_CONNECTION_CHECK_HTTP_BUILT)
    add_executable(umicom-provider-chat-http-test "${_umicom_provider_chat_root}/tests/provider_chat/test_http.c")
    target_compile_definitions(umicom-provider-chat-http-test PRIVATE UMICOM_CONNECTION_CHECK_HAS_HTTP=1)
    target_link_libraries(umicom-provider-chat-http-test PRIVATE Umicom::provider_connection_checks PkgConfig::UMICOM_CONNECTION_CHECK_CURL)
    umicom_apply_warnings(umicom-provider-chat-http-test)
    umicom_apply_sanitizers(umicom-provider-chat-http-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-provider-chat-http-test)
    endif()
    foreach(case remote local nul cancel option-failure redirect)
        add_test(NAME framework.provider_chat.http.${case} COMMAND umicom-provider-chat-http-test ${case})
        set_tests_properties(framework.provider_chat.http.${case} PROPERTIES TIMEOUT 20 LABELS "framework;provider-chat;http;privacy;regression")
    endforeach()
endif()

# Selection export exercises the document owner independently of GTK or HTTP.
if(BUILD_TESTING)
    add_executable(umicom-provider-chat-selection-test "${_umicom_provider_chat_root}/tests/provider_chat/test_selection.c")
    target_link_libraries(umicom-provider-chat-selection-test PRIVATE Umicom::ui)
    umicom_apply_warnings(umicom-provider-chat-selection-test)
    umicom_apply_sanitizers(umicom-provider-chat-selection-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-provider-chat-selection-test)
    endif()
    foreach(case selection large immutable stale empty inactive overflow bounds capacity missing invalid unicode)
        add_test(NAME framework.provider_chat.selection.${case} COMMAND umicom-provider-chat-selection-test ${case})
        set_tests_properties(framework.provider_chat.selection.${case} PROPERTIES TIMEOUT 20 LABELS "framework;provider-chat;document;privacy;regression")
    endforeach()
endif()

if(BUILD_TESTING AND TARGET umicom_ui_gtk4)
    add_executable(umicom-provider-chat-context-test "${_umicom_provider_chat_root}/tests/provider_chat/test_context_gtk4.c")
    target_link_libraries(umicom-provider-chat-context-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-provider-chat-context-test)
    umicom_apply_sanitizers(umicom-provider-chat-context-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-provider-chat-context-test)
    endif()
    foreach(case draft invalid review busy handoff failed-handoff retire empty-window)
        file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/provider-context-tests/${case}")
        add_test(NAME framework.provider_chat.context.gtk4.${case} COMMAND umicom-provider-chat-context-test ${case})
        set_tests_properties(framework.provider_chat.context.gtk4.${case} PROPERTIES TIMEOUT 40 SKIP_RETURN_CODE 77
            WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/provider-context-tests/${case}"
            LABELS "framework;provider-chat;document;gtk4;privacy;regression")
    endforeach()
endif()

install(FILES "${_umicom_provider_chat_root}/docs/learning/chat-about-selected-code.html" DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/learning COMPONENT Learning)


# These cases use owned fixtures and a fake transport; they never contact a provider.
if(BUILD_TESTING)
    add_executable(umicom-provider-chat-history-test "${_umicom_provider_chat_root}/tests/provider_chat/test_history.c")
    target_link_libraries(umicom-provider-chat-history-test PRIVATE Umicom::provider_chat)
    umicom_apply_warnings(umicom-provider-chat-history-test)
    umicom_apply_sanitizers(umicom-provider-chat-history-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-provider-chat-history-test)
    endif()
    foreach(case lifecycle owned large full invalid stale remove clear compose order utf8 ranges roles atomic context-limit flags exhausted arguments)
        add_test(NAME framework.provider_chat.history.${case} COMMAND umicom-provider-chat-history-test ${case})
        set_tests_properties(framework.provider_chat.history.${case} PROPERTIES TIMEOUT 20 LABELS "framework;provider-chat;history;privacy;regression")
    endforeach()
endif()
if(BUILD_TESTING AND TARGET umicom_ui_gtk4)
    add_executable(umicom-provider-chat-history-gtk-test "${_umicom_provider_chat_root}/tests/provider_chat/test_history_gtk4.c")
    target_link_libraries(umicom-provider-chat-history-gtk-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-provider-chat-history-gtk-test)
    umicom_apply_sanitizers(umicom-provider-chat-history-gtk-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-provider-chat-history-gtk-test)
    endif()
    foreach(case capture followup unicode no-selection stale edited-view oversize forget clear failed cancel retire pending full)
        file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/provider-history-tests/${case}")
        add_test(NAME framework.provider_chat.history.gtk4.${case} COMMAND umicom-provider-chat-history-gtk-test ${case})
        set_tests_properties(framework.provider_chat.history.gtk4.${case} PROPERTIES TIMEOUT 40 SKIP_RETURN_CODE 77
            WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/provider-history-tests/${case}"
            LABELS "framework;provider-chat;history;gtk4;privacy;ownership;regression")
    endforeach()
endif()

install(FILES "${_umicom_provider_chat_root}/docs/learning/reviewed-chat-follow-ups.html" DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/learning COMPONENT Learning)
