# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
target_sources(umicom_developer PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/debug_runtime/response_fields.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/debug_runtime/exception_filter_json.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/debug_runtime/exception_filter_catalog.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/debug_runtime/exception_filter_acknowledgement.c")
if(TARGET umicom_ui_gtk4)
    target_sources(umicom_ui_gtk4 PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../adapters/gtk4/debug_exception_filters.c")
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/DEBUG_EXCEPTION_FILTERS.html"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/umicom-framework/docs" COMPONENT Framework)
if(NOT BUILD_TESTING)
    return()
endif()
function(umicom_exception_test target source owner)
    add_executable("${target}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/debug_exceptions/${source}")
    target_link_libraries("${target}" PRIVATE "${owner}")
    set_target_properties("${target}" PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings("${target}")
    umicom_apply_sanitizers("${target}")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target("${target}")
    endif()
endfunction()
function(umicom_exception_case group target case)
    add_test(NAME framework.debug.exceptions.${group}.${case} COMMAND "${target}" "${case}" ${ARGN})
    set_tests_properties(framework.debug.exceptions.${group}.${case} PROPERTIES
        TIMEOUT 60 SKIP_RETURN_CODE 77 LABELS "framework;debug;exceptions;regression")
endfunction()
umicom_exception_test(umicom-exception-catalog-test test_catalog.c Umicom::developer)
foreach(case normal empty missing unicode escaped-keys unknown duplicate-id duplicate-key escaped-duplicate bad-label nul surrogate empty-id default-type array-type refuse command body capacity long-id)
    umicom_exception_case(catalog umicom-exception-catalog-test "${case}")
endforeach()
umicom_exception_test(umicom-exception-acknowledgement-test test_acknowledgement.c Umicom::developer)
foreach(case absent unknown verified refused-filter empty count boolean missing-verified nul duplicate null array refuse command)
    umicom_exception_case(acknowledgement umicom-exception-acknowledgement-test "${case}")
endforeach()
if(TARGET umicom-native-attach-adapter-fixture)
    umicom_exception_test(umicom-exception-protocol-test test_protocol.c Umicom::developer)
    add_dependencies(umicom-exception-protocol-test umicom-native-attach-adapter-fixture)
    foreach(case normal clear stale session count boolean refuse timeout malformed unverified unsupported closed)
        set(directory "${CMAKE_CURRENT_BINARY_DIR}/debug-exceptions/${case}")
        file(MAKE_DIRECTORY "${directory}")
        umicom_exception_case(protocol umicom-exception-protocol-test "${case}"
            "$<TARGET_FILE:umicom-native-attach-adapter-fixture>" "${directory}")
    endforeach()
endif()
if(TARGET umicom_ui_gtk4)
    umicom_exception_test(umicom-exception-gtk4-test test_gtk4.c Umicom::ui_gtk4)
    foreach(case normal unverified empty denied stale hidden retained close-read close-apply invalid-host)
        umicom_exception_case(gtk4 umicom-exception-gtk4-test "${case}")
    endforeach()
endif()
