# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_text_folding)
    if(NOT TARGET umicom_ui_gtk4)
        return()
    endif()
    get_target_property(attached umicom_ui_gtk4 UMICOM_TEXT_FOLDING_ATTACHED)
    if(attached)
        return()
    endif()
    set_target_properties(umicom_ui_gtk4 PROPERTIES UMICOM_TEXT_FOLDING_ATTACHED TRUE)
    target_sources(umicom_ui_gtk4 PRIVATE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../adapters/gtk4/text_folding_gtk4.c")
    if(BUILD_TESTING)
        add_executable(umicom-text-folding-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/editor/test_text_folding_gtk4.c")
        target_link_libraries(umicom-text-folding-test PRIVATE Umicom::ui_gtk4)
        umicom_apply_warnings(umicom-text-folding-test)
        umicom_apply_sanitizers(umicom-text-folding-test)
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(umicom-text-folding-test)
        endif()
        foreach(case basic modified header partial-end reverse unicode readonly empty single-line no-selection clear-empty clear repeated-clear edit-reveals delete-reveals replace-reveals caret-reveals selection-reveals unrelated-mark visible-caret multiple capacity independent shared-buffer shared-table other-tags buffer-switch refold apply-edit apply-navigation apply-replace-buffer apply-nested tag-add-edit tag-add-navigation tag-add-remove tag-remove-edit invalid native-history)
            add_test(NAME framework.editor.folding.gtk4.${case} COMMAND umicom-text-folding-test ${case})
            set_tests_properties(framework.editor.folding.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77 LABELS "framework;editor;folding;gtk4;ownership;regression")
        endforeach()
    endif()
endfunction()
umicom_attach_text_folding()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_text_folding)
endif()

install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/learning/manual-folding.html" DESTINATION "${CMAKE_INSTALL_DATADIR}/doc/umicom/learning" COMPONENT Development)
