# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-recovery-observations-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_recovery_observations.c")
    target_link_libraries(umicom-recovery-observations-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-recovery-observations-test)
    umicom_apply_sanitizers(umicom-recovery-observations-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-recovery-observations-test)
    endif()
    foreach(case pending synchronized caret-only text-change clean read-only capacity identity closed empty null-output)
        add_test(NAME framework.document.recovery_observations.${case} COMMAND umicom-recovery-observations-test ${case})
        set_tests_properties(framework.document.recovery_observations.${case} PROPERTIES TIMEOUT 45 LABELS "framework;document;recovery;scheduling;regression")
    endforeach()
endif()
