#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomAppearanceAccessibilityPlatform.cmake
#
# PURPOSE:
#   Extend canonical Umicom::ui with production theme resolution, typography,
#   high-DPI scaling, accessibility certification and renderer appearance parity.
#
# ARCHITECTURE:
#   Existing Design System, adaptive shell, component and frontend contracts
#   remain authoritative. This layer governs production appearance resolution.
#
# Created by: Sammy Hegab
# Organisation: Umicom Foundation
# Licence: MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_APPEARANCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
if(NOT TARGET umicom_ui)
    message(FATAL_ERROR "UmicomAppearanceAccessibilityPlatform.cmake requires canonical umicom_ui")
endif()

# Production appearance capability extends the existing canonical UI target.
target_sources(umicom_ui PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/animation_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/appearance_audit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/appearance_conformance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/appearance_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/appearance_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/appearance_service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/appearance_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/application_brand_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/border_style_projection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/color_vision_assistance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/component_state_projection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/component_style_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/contrast_certification.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/contrast_evidence.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/contrast_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/display_scale_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/dpi_class.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/elevation_style_projection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/focus_evidence.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/focus_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/focus_traversal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/font_fallback_chain.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/font_family_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/font_metric_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/font_resolution.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/font_stack.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/high_contrast_mode.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/high_dpi_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/icon_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/icon_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/icon_fallback_chain.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/icon_scale_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/icon_variant_resolution.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/input_affordance_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/input_target_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/keyboard_access_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/line_height_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/logical_pixel_transform.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/mnemonic_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/motion_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/palette_override.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/palette_resolution.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/physical_pixel_transform.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/reduced_motion_mode.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/renderer_appearance_capability.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/renderer_parity_matrix.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/renderer_theme_projection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/scale_factor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/semantic_palette_map.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/shortcut_presentation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/style_packet.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/surface_semantics.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/surface_style_projection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/system_appearance_state.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/target_size_certification.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/text_scale_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/theme_inheritance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/theme_pack.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/theme_pack_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/theme_resolution.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/theme_scope.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/theme_variant.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/transition_budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/typography_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/appearance/user_appearance_preferences.c"
)

if(BUILD_TESTING)
    function(umicom_add_ui_appearance_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_APPEARANCE_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::ui)
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;ui-appearance;accessibility;high-dpi;theme-system")
    endfunction()

    umicom_add_ui_appearance_test(
        umicom-ui-appearance-animation-gate-test
        framework.ui_appearance.animation.gate
        tests/ui_appearance/test_animation_gate.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-appearance-audit-test
        framework.ui_appearance.appearance.audit
        tests/ui_appearance/test_appearance_audit.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-appearance-conformance-test
        framework.ui_appearance.appearance.conformance
        tests/ui_appearance/test_appearance_conformance.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-appearance-profile-test
        framework.ui_appearance.appearance.profile
        tests/ui_appearance/test_appearance_profile.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-appearance-registry-test
        framework.ui_appearance.appearance.registry
        tests/ui_appearance/test_appearance_registry.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-appearance-service-test
        framework.ui_appearance.appearance.service
        tests/ui_appearance/test_appearance_service.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-appearance-snapshot-test
        framework.ui_appearance.appearance.snapshot
        tests/ui_appearance/test_appearance_snapshot.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-application-brand-binding-test
        framework.ui_appearance.application.brand.binding
        tests/ui_appearance/test_application_brand_binding.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-border-style-projection-test
        framework.ui_appearance.border.style.projection
        tests/ui_appearance/test_border_style_projection.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-color-vision-assistance-test
        framework.ui_appearance.color.vision.assistance
        tests/ui_appearance/test_color_vision_assistance.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-component-state-projection-test
        framework.ui_appearance.component.state.projection
        tests/ui_appearance/test_component_state_projection.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-component-style-binding-test
        framework.ui_appearance.component.style.binding
        tests/ui_appearance/test_component_style_binding.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-contrast-certification-test
        framework.ui_appearance.contrast.certification
        tests/ui_appearance/test_contrast_certification.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-contrast-evidence-test
        framework.ui_appearance.contrast.evidence
        tests/ui_appearance/test_contrast_evidence.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-contrast-policy-test
        framework.ui_appearance.contrast.policy
        tests/ui_appearance/test_contrast_policy.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-display-scale-profile-test
        framework.ui_appearance.display.scale.profile
        tests/ui_appearance/test_display_scale_profile.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-dpi-class-test
        framework.ui_appearance.dpi.class
        tests/ui_appearance/test_dpi_class.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-elevation-style-projection-test
        framework.ui_appearance.elevation.style.projection
        tests/ui_appearance/test_elevation_style_projection.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-focus-evidence-test
        framework.ui_appearance.focus.evidence
        tests/ui_appearance/test_focus_evidence.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-focus-policy-test
        framework.ui_appearance.focus.policy
        tests/ui_appearance/test_focus_policy.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-focus-traversal-test
        framework.ui_appearance.focus.traversal
        tests/ui_appearance/test_focus_traversal.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-font-fallback-chain-test
        framework.ui_appearance.font.fallback.chain
        tests/ui_appearance/test_font_fallback_chain.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-font-family-descriptor-test
        framework.ui_appearance.font.family.descriptor
        tests/ui_appearance/test_font_family_descriptor.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-font-metric-policy-test
        framework.ui_appearance.font.metric.policy
        tests/ui_appearance/test_font_metric_policy.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-font-resolution-test
        framework.ui_appearance.font.resolution
        tests/ui_appearance/test_font_resolution.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-font-stack-test
        framework.ui_appearance.font.stack
        tests/ui_appearance/test_font_stack.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-high-contrast-mode-test
        framework.ui_appearance.high.contrast.mode
        tests/ui_appearance/test_high_contrast_mode.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-high-dpi-policy-test
        framework.ui_appearance.high.dpi.policy
        tests/ui_appearance/test_high_dpi_policy.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-icon-catalogue-test
        framework.ui_appearance.icon.catalogue
        tests/ui_appearance/test_icon_catalogue.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-icon-descriptor-test
        framework.ui_appearance.icon.descriptor
        tests/ui_appearance/test_icon_descriptor.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-icon-fallback-chain-test
        framework.ui_appearance.icon.fallback.chain
        tests/ui_appearance/test_icon_fallback_chain.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-icon-scale-policy-test
        framework.ui_appearance.icon.scale.policy
        tests/ui_appearance/test_icon_scale_policy.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-icon-variant-resolution-test
        framework.ui_appearance.icon.variant.resolution
        tests/ui_appearance/test_icon_variant_resolution.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-input-affordance-policy-test
        framework.ui_appearance.input.affordance.policy
        tests/ui_appearance/test_input_affordance_policy.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-input-target-policy-test
        framework.ui_appearance.input.target.policy
        tests/ui_appearance/test_input_target_policy.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-keyboard-access-policy-test
        framework.ui_appearance.keyboard.access.policy
        tests/ui_appearance/test_keyboard_access_policy.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-line-height-policy-test
        framework.ui_appearance.line.height.policy
        tests/ui_appearance/test_line_height_policy.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-logical-pixel-transform-test
        framework.ui_appearance.logical.pixel.transform
        tests/ui_appearance/test_logical_pixel_transform.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-mnemonic-policy-test
        framework.ui_appearance.mnemonic.policy
        tests/ui_appearance/test_mnemonic_policy.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-motion-policy-test
        framework.ui_appearance.motion.policy
        tests/ui_appearance/test_motion_policy.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-palette-override-test
        framework.ui_appearance.palette.override
        tests/ui_appearance/test_palette_override.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-palette-resolution-test
        framework.ui_appearance.palette.resolution
        tests/ui_appearance/test_palette_resolution.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-physical-pixel-transform-test
        framework.ui_appearance.physical.pixel.transform
        tests/ui_appearance/test_physical_pixel_transform.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-reduced-motion-mode-test
        framework.ui_appearance.reduced.motion.mode
        tests/ui_appearance/test_reduced_motion_mode.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-renderer-appearance-capability-test
        framework.ui_appearance.renderer.appearance.capability
        tests/ui_appearance/test_renderer_appearance_capability.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-renderer-parity-matrix-test
        framework.ui_appearance.renderer.parity.matrix
        tests/ui_appearance/test_renderer_parity_matrix.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-renderer-theme-projection-test
        framework.ui_appearance.renderer.theme.projection
        tests/ui_appearance/test_renderer_theme_projection.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-scale-factor-test
        framework.ui_appearance.scale.factor
        tests/ui_appearance/test_scale_factor.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-semantic-palette-map-test
        framework.ui_appearance.semantic.palette.map
        tests/ui_appearance/test_semantic_palette_map.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-shortcut-presentation-test
        framework.ui_appearance.shortcut.presentation
        tests/ui_appearance/test_shortcut_presentation.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-style-packet-test
        framework.ui_appearance.style.packet
        tests/ui_appearance/test_style_packet.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-surface-semantics-test
        framework.ui_appearance.surface.semantics
        tests/ui_appearance/test_surface_semantics.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-surface-style-projection-test
        framework.ui_appearance.surface.style.projection
        tests/ui_appearance/test_surface_style_projection.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-system-appearance-state-test
        framework.ui_appearance.system.appearance.state
        tests/ui_appearance/test_system_appearance_state.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-target-size-certification-test
        framework.ui_appearance.target.size.certification
        tests/ui_appearance/test_target_size_certification.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-text-scale-policy-test
        framework.ui_appearance.text.scale.policy
        tests/ui_appearance/test_text_scale_policy.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-theme-inheritance-test
        framework.ui_appearance.theme.inheritance
        tests/ui_appearance/test_theme_inheritance.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-theme-pack-test
        framework.ui_appearance.theme.pack
        tests/ui_appearance/test_theme_pack.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-theme-pack-registry-test
        framework.ui_appearance.theme.pack.registry
        tests/ui_appearance/test_theme_pack_registry.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-theme-resolution-test
        framework.ui_appearance.theme.resolution
        tests/ui_appearance/test_theme_resolution.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-theme-scope-test
        framework.ui_appearance.theme.scope
        tests/ui_appearance/test_theme_scope.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-theme-variant-test
        framework.ui_appearance.theme.variant
        tests/ui_appearance/test_theme_variant.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-transition-budget-test
        framework.ui_appearance.transition.budget
        tests/ui_appearance/test_transition_budget.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-types-test
        framework.ui_appearance.types
        tests/ui_appearance/test_types.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-typography-policy-test
        framework.ui_appearance.typography.policy
        tests/ui_appearance/test_typography_policy.c
    )
    umicom_add_ui_appearance_test(
        umicom-ui-appearance-user-appearance-preferences-test
        framework.ui_appearance.user.appearance.preferences
        tests/ui_appearance/test_user_appearance_preferences.c
    )
endif()

message(STATUS "Umicom production appearance, accessibility and high-DPI platform enabled")
