# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-format-plan-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_format_plan.c")
    target_link_libraries(umicom-document-format-plan-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-format-plan-test)
    umicom_apply_sanitizers(umicom-document-format-plan-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-format-plan-test)
    endif()
    foreach(case lf crlf cr mixed unicode selection eof final empty empty-final final-present preserve owned no-change invalid-utf8 embedded-null split-scalar split-crlf invalid-cursor invalid-selection invalid-target invalid-final preserve-final input-limit growth-limit cancelled null-output)
        add_test(NAME framework.document.format_plan.${case} COMMAND umicom-document-format-plan-test ${case})
        set_tests_properties(framework.document.format_plan.${case} PROPERTIES TIMEOUT 45 LABELS "framework;document;format;history;regression")
    endforeach()
endif()
