# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-source-set-history-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_source_set_history.c")
    target_link_libraries(umicom-source-set-history-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-source-set-history-test)
    umicom_apply_sanitizers(umicom-source-set-history-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-source-set-history-test)
    endif()
    foreach(case selections carets unicode pending-first pending-both reverse-order unchanged-first redo active-tab)
        add_test(NAME framework.document.source_set_history.${case} COMMAND umicom-source-set-history-test ${case})
        set_tests_properties(framework.document.source_set_history.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;history;selection;regression")
    endforeach()
endif()
