#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomSharedFinancialCorePlatform.cmake
#
# PURPOSE:
#   Extend the canonical Umicom::finance target with shared financial-domain
#   reference data, lifecycle, position, settlement, market-data and valuation
#   contracts used by all thin financial applications.
#
# ARCHITECTURE:
#   The existing low-level finance identifiers, currencies, money, quantities
#   accounts and parties remain authoritative. This platform adds reusable
#   financial semantics without creating a competing finance library.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_SHARED_FINANCIAL_CORE_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
# Load the dependency only when the parent build has not already provided its target.
if(NOT TARGET umicom_finance)
    message(FATAL_ERROR "UmicomSharedFinancialCorePlatform.cmake requires canonical umicom_finance")
endif()

# Shared financial-domain capabilities extend the existing canonical finance target.
target_sources(umicom_finance PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/account_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/balance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/balance_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/book_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/business_date.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/business_date_adjustment.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/business_day_convention.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/calendar_join.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/cashflow.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/cashflow_schedule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/counterparty.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/counterparty_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/currency_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/currency_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/currency_pair.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/curve_reference.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/day_count.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/exchange_rate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/financial_account.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/financial_audit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/financial_core_service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/financial_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/financial_workflow.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/fixing.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/fixing_store.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/fx_conversion.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/holiday_calendar.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/holiday_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/legal_entity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/legal_entity_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/lifecycle_event.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/lifecycle_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/market_data_key.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/market_data_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/notional.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/portfolio.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/portfolio_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/position.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/position_aggregation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/position_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/position_key.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/price.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/pricing_context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/pricing_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/product_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/product_id.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/product_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/quote.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/rate_index.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/rate_index_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/schedule_generator.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/schedule_period.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/schedule_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/settlement_event.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/settlement_instruction.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/surface_reference.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/tenor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/trade_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/trade_event.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/trade_event_log.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/trade_id.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/trade_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/valuation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/core/valuation_book.c"
)

# Register verification targets only when the developer has enabled testing.
if(BUILD_TESTING)
    # Define the add shared financial core test build helper so parent and application
    # projects apply one consistent rule.
    function(umicom_add_shared_financial_core_test target test_name source)
        # Configure the optional target only when its feature has created it.
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_SHARED_FINANCIAL_CORE_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::finance)
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;financial-core")
    endfunction()

    umicom_add_shared_financial_core_test(
        umicom-financial-core-account-registry-test
        framework.financial_core.account.registry
        tests/finance_core/test_account_registry.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-balance-test
        framework.financial_core.balance
        tests/finance_core/test_balance.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-balance-book-test
        framework.financial_core.balance.book
        tests/finance_core/test_balance_book.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-book-test
        framework.financial_core.book
        tests/finance_core/test_book.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-book-registry-test
        framework.financial_core.book.registry
        tests/finance_core/test_book_registry.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-business-date-test
        framework.financial_core.business.date
        tests/finance_core/test_business_date.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-business-date-adjustment-test
        framework.financial_core.business.date.adjustment
        tests/finance_core/test_business_date_adjustment.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-business-day-convention-test
        framework.financial_core.business.day.convention
        tests/finance_core/test_business_day_convention.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-calendar-join-test
        framework.financial_core.calendar.join
        tests/finance_core/test_calendar_join.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-cashflow-test
        framework.financial_core.cashflow
        tests/finance_core/test_cashflow.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-cashflow-schedule-test
        framework.financial_core.cashflow.schedule
        tests/finance_core/test_cashflow_schedule.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-counterparty-test
        framework.financial_core.counterparty
        tests/finance_core/test_counterparty.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-counterparty-registry-test
        framework.financial_core.counterparty.registry
        tests/finance_core/test_counterparty_registry.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-currency-catalogue-test
        framework.financial_core.currency.catalogue
        tests/finance_core/test_currency_catalogue.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-currency-descriptor-test
        framework.financial_core.currency.descriptor
        tests/finance_core/test_currency_descriptor.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-currency-pair-test
        framework.financial_core.currency.pair
        tests/finance_core/test_currency_pair.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-curve-reference-test
        framework.financial_core.curve.reference
        tests/finance_core/test_curve_reference.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-day-count-test
        framework.financial_core.day.count
        tests/finance_core/test_day_count.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-exchange-rate-test
        framework.financial_core.exchange.rate
        tests/finance_core/test_exchange_rate.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-financial-account-test
        framework.financial_core.financial.account
        tests/finance_core/test_financial_account.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-financial-audit-test
        framework.financial_core.financial.audit
        tests/finance_core/test_financial_audit.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-financial-core-service-test
        framework.financial_core.financial.core.service
        tests/finance_core/test_financial_core_service.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-financial-snapshot-test
        framework.financial_core.financial.snapshot
        tests/finance_core/test_financial_snapshot.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-financial-workflow-test
        framework.financial_core.financial.workflow
        tests/finance_core/test_financial_workflow.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-fixing-test
        framework.financial_core.fixing
        tests/finance_core/test_fixing.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-fixing-store-test
        framework.financial_core.fixing.store
        tests/finance_core/test_fixing_store.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-fx-conversion-test
        framework.financial_core.fx.conversion
        tests/finance_core/test_fx_conversion.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-holiday-calendar-test
        framework.financial_core.holiday.calendar
        tests/finance_core/test_holiday_calendar.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-holiday-catalogue-test
        framework.financial_core.holiday.catalogue
        tests/finance_core/test_holiday_catalogue.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-legal-entity-test
        framework.financial_core.legal.entity
        tests/finance_core/test_legal_entity.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-legal-entity-registry-test
        framework.financial_core.legal.entity.registry
        tests/finance_core/test_legal_entity_registry.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-lifecycle-event-test
        framework.financial_core.lifecycle.event
        tests/finance_core/test_lifecycle_event.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-lifecycle-policy-test
        framework.financial_core.lifecycle.policy
        tests/finance_core/test_lifecycle_policy.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-market-data-key-test
        framework.financial_core.market.data.key
        tests/finance_core/test_market_data_key.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-market-data-snapshot-test
        framework.financial_core.market.data.snapshot
        tests/finance_core/test_market_data_snapshot.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-notional-test
        framework.financial_core.notional
        tests/finance_core/test_notional.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-portfolio-test
        framework.financial_core.portfolio
        tests/finance_core/test_portfolio.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-portfolio-registry-test
        framework.financial_core.portfolio.registry
        tests/finance_core/test_portfolio_registry.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-position-test
        framework.financial_core.position
        tests/finance_core/test_position.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-position-aggregation-test
        framework.financial_core.position.aggregation
        tests/finance_core/test_position_aggregation.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-position-book-test
        framework.financial_core.position.book
        tests/finance_core/test_position_book.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-position-key-test
        framework.financial_core.position.key
        tests/finance_core/test_position_key.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-price-test
        framework.financial_core.price
        tests/finance_core/test_price.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-pricing-context-test
        framework.financial_core.pricing.context
        tests/finance_core/test_pricing_context.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-pricing-result-test
        framework.financial_core.pricing.result
        tests/finance_core/test_pricing_result.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-product-descriptor-test
        framework.financial_core.product.descriptor
        tests/finance_core/test_product_descriptor.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-product-id-test
        framework.financial_core.product.id
        tests/finance_core/test_product_id.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-product-registry-test
        framework.financial_core.product.registry
        tests/finance_core/test_product_registry.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-quote-test
        framework.financial_core.quote
        tests/finance_core/test_quote.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-rate-index-test
        framework.financial_core.rate.index
        tests/finance_core/test_rate_index.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-rate-index-catalogue-test
        framework.financial_core.rate.index.catalogue
        tests/finance_core/test_rate_index_catalogue.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-schedule-generator-test
        framework.financial_core.schedule.generator
        tests/finance_core/test_schedule_generator.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-schedule-period-test
        framework.financial_core.schedule.period
        tests/finance_core/test_schedule_period.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-schedule-rule-test
        framework.financial_core.schedule.rule
        tests/finance_core/test_schedule_rule.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-settlement-event-test
        framework.financial_core.settlement.event
        tests/finance_core/test_settlement_event.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-settlement-instruction-test
        framework.financial_core.settlement.instruction
        tests/finance_core/test_settlement_instruction.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-surface-reference-test
        framework.financial_core.surface.reference
        tests/finance_core/test_surface_reference.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-tenor-test
        framework.financial_core.tenor
        tests/finance_core/test_tenor.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-trade-descriptor-test
        framework.financial_core.trade.descriptor
        tests/finance_core/test_trade_descriptor.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-trade-event-test
        framework.financial_core.trade.event
        tests/finance_core/test_trade_event.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-trade-event-log-test
        framework.financial_core.trade.event.log
        tests/finance_core/test_trade_event_log.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-trade-id-test
        framework.financial_core.trade.id
        tests/finance_core/test_trade_id.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-trade-registry-test
        framework.financial_core.trade.registry
        tests/finance_core/test_trade_registry.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-types-test
        framework.financial_core.types
        tests/finance_core/test_types.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-valuation-test
        framework.financial_core.valuation
        tests/finance_core/test_valuation.c
    )
    umicom_add_shared_financial_core_test(
        umicom-financial-core-valuation-book-test
        framework.financial_core.valuation.book
        tests/finance_core/test_valuation_book.c
    )
endif()

message(STATUS "Umicom shared financial platform core enabled")
