# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-replacement-options-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_replacement_options.c")
    target_link_libraries(umicom-document-replacement-options-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-replacement-options-test)
    umicom_apply_sanitizers(umicom-document-replacement-options-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-replacement-options-test)
    endif()
    foreach(case plan-sensitive plan-insensitive plan-smart plan-owned plan-complete plan-invalid session-policy session-owned session-invalid set-policy set-owned set-complete set-invalid)
        add_test(NAME framework.document.replacement_options.${case} COMMAND umicom-document-replacement-options-test ${case})
        set_tests_properties(framework.document.replacement_options.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;search;replacement;regression")
    endforeach()
endif()
