# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING AND TARGET Umicom::creative_workspace_gtk4)
    add_executable(umicom-creative-png-preview-test "${CMAKE_CURRENT_LIST_DIR}/../tests/creative_assets/test_png_preview_gtk4.c")
    target_link_libraries(umicom-creative-png-preview-test PRIVATE Umicom::creative_workspace_gtk4)
    umicom_creative_configure_target(umicom-creative-png-preview-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-creative-png-preview-test)
    endif()
    foreach(case preview no-auto-preview wrong-label bad-image retain-cancel clear replace failed-capture busy archive-preview independent retained-control)
        add_test(NAME framework.creative_assets.png_preview.${case} COMMAND umicom-creative-png-preview-test ${case})
        set_tests_properties(framework.creative_assets.png_preview.${case} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;creative-assets;png;gtk4;regression")
    endforeach()
endif()
