# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
target_sources(umicom_developer PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/debug_runtime/function_breakpoint_draft.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/debug_runtime/function_breakpoint_reply.c")
if(TARGET umicom_ui_gtk4)
    target_sources(umicom_ui_gtk4 PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../adapters/gtk4/debug_function_breakpoints.c")
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/DEBUG_FUNCTION_BREAKPOINTS.html"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/umicom-framework/docs" COMPONENT Framework)
if(NOT BUILD_TESTING)
    return()
endif()
function(umicom_function_breakpoint_test target source owner)
    add_executable("${target}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/function_breakpoints/${source}")
    target_link_libraries("${target}" PRIVATE "${owner}")
    set_target_properties("${target}" PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings("${target}")
    umicom_apply_sanitizers("${target}")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target("${target}")
    endif()
endfunction()
function(umicom_function_breakpoint_case group target case)
    add_test(NAME framework.debug.function_breakpoints.${group}.${case} COMMAND "${target}" "${case}" ${ARGN})
    set_tests_properties(framework.debug.function_breakpoints.${group}.${case} PROPERTIES
        TIMEOUT 60 SKIP_RETURN_CODE 77 LABELS "framework;debug;function-breakpoints;regression")
endfunction()
umicom_function_breakpoint_test(umicom-function-breakpoint-draft-test test_draft.c Umicom::developer)
foreach(case normal empty disabled conditions unicode duplicate count spaces name-empty name-long condition-long hit-long session-long newline utf8 boolean)
    umicom_function_breakpoint_case(draft umicom-function-breakpoint-draft-test "${case}")
endforeach()
umicom_function_breakpoint_test(umicom-function-breakpoint-reply-test test_reply.c Umicom::developer)
foreach(case verified unverified empty count missing duplicate nul line-zero line-overflow negative-id source refuse command)
    umicom_function_breakpoint_case(reply umicom-function-breakpoint-reply-test "${case}")
endforeach()
if(TARGET umicom-native-attach-adapter-fixture)
    umicom_function_breakpoint_test(umicom-function-breakpoint-protocol-test test_protocol.c Umicom::developer)
    add_dependencies(umicom-function-breakpoint-protocol-test umicom-native-attach-adapter-fixture)
    foreach(case normal clear disabled conditions no-condition stale session refuse timeout malformed unverified unsupported new-session closed)
        set(directory "${CMAKE_CURRENT_BINARY_DIR}/function-breakpoints/${case}")
        file(MAKE_DIRECTORY "${directory}")
        umicom_function_breakpoint_case(protocol umicom-function-breakpoint-protocol-test "${case}"
            "$<TARGET_FILE:umicom-native-attach-adapter-fixture>" "${directory}")
    endforeach()
endif()
if(TARGET umicom_ui_gtk4)
    umicom_function_breakpoint_test(umicom-function-breakpoint-gtk4-test test_gtk4.c Umicom::ui_gtk4)
    foreach(case normal empty-name duplicate remove disable condition denied stale hidden retained close-apply unsupported editing-verification)
        umicom_function_breakpoint_case(gtk4 umicom-function-breakpoint-gtk4-test "${case}")
    endforeach()
endif()
