# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/UmicomWorkbenchViewport.cmake")
if(TARGET Umicom::ui_gtk4)
    set(_umi_viewport_gtk_dependency Umicom::ui_gtk4)
elseif(TARGET PkgConfig::VIEWPORT_GTK4)
    # The focused build uses the real GTK library, not a pretend Framework host.
    set(_umi_viewport_gtk_dependency PkgConfig::VIEWPORT_GTK4)
else()
    message(FATAL_ERROR "The workbench gallery requires an actual GTK4 target")
endif()
get_filename_component(_umi_viewport_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
add_library(umicom_workbench_viewport_gtk4 STATIC
    "${_umi_viewport_root}/adapters/gtk4/workbench_viewport_gtk4.c"
    "${_umi_viewport_root}/adapters/gtk4/workbench_gallery_gtk4.c"
    "${_umi_viewport_root}/examples/workbench_viewport/practice_layout.c")
add_library(Umicom::workbench_viewport_gtk4 ALIAS umicom_workbench_viewport_gtk4)
set_target_properties(umicom_workbench_viewport_gtk4 PROPERTIES EXPORT_NAME workbench_viewport_gtk4)
target_link_libraries(umicom_workbench_viewport_gtk4 PUBLIC Umicom::workbench_viewport ${_umi_viewport_gtk_dependency})
if(WIN32)
    add_executable(umicom-component-workbench WIN32 "${_umi_viewport_root}/examples/workbench_viewport/gtk_main.c")
    if(MINGW)
        target_link_options(umicom-component-workbench PRIVATE -municode)
    endif()
else()
    add_executable(umicom-component-workbench "${_umi_viewport_root}/examples/workbench_viewport/gtk_main.c")
endif()
target_link_libraries(umicom-component-workbench PRIVATE Umicom::workbench_viewport_gtk4)
foreach(_target IN ITEMS umicom_workbench_viewport_gtk4 umicom-component-workbench)
    set_target_properties(${_target} PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    if(COMMAND umicom_apply_warnings)
        umicom_apply_warnings(${_target})
    endif()
    if(COMMAND umicom_apply_sanitizers)
        umicom_apply_sanitizers(${_target})
    endif()
endforeach()
if(COMMAND umicom_prepare_windows_application AND WIN32)
    umicom_prepare_windows_application(TARGET umicom-component-workbench
        PRODUCT_NAME "Umicom Component Workbench" RESOURCE_ROOT "${_umi_viewport_root}/resources" GUI)
endif()
# Production exports include the canonical GTK dependency. The focused GTK
# build is executable validation only; it does not export a fake UI SDK.
if(TARGET Umicom::ui_gtk4)
    install(TARGETS umicom_workbench_viewport_gtk4 EXPORT UmicomFrameworkTargets
        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT Framework)
endif()
install(TARGETS umicom-component-workbench RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT Learning)
if(BUILD_TESTING)
    add_executable(umicom-workbench-viewport-gtk4-test
        "${_umi_viewport_root}/tests/workbench_viewport/test_gtk4.c")
    target_link_libraries(umicom-workbench-viewport-gtk4-test PRIVATE Umicom::workbench_viewport_gtk4)
    set_target_properties(umicom-workbench-viewport-gtk4-test PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-workbench-viewport-gtk4-test)
    endif()
    foreach(_case IN ITEMS lifecycle invalid factory-failure retained-child preview-preserves-text two-instances locked gallery)
        add_test(NAME framework.workbench_viewport.gtk4.${_case} COMMAND umicom-workbench-viewport-gtk4-test ${_case})
        set_tests_properties(framework.workbench_viewport.gtk4.${_case} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;gtk4;lifetime")
    endforeach()
    if(COMMAND umicom_apply_warnings)
        umicom_apply_warnings(umicom-workbench-viewport-gtk4-test)
    endif()
    if(COMMAND umicom_apply_sanitizers)
        umicom_apply_sanitizers(umicom-workbench-viewport-gtk4-test)
    endif()
endif()
unset(_umi_viewport_root)
unset(_umi_viewport_gtk_dependency)
