# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(NOT BUILD_TESTING)
    return()
endif()
add_executable(umicom-language-integer-bounds-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_integer_bounds.c")
target_link_libraries(umicom-language-integer-bounds-test PRIVATE Umicom::developer)
set_target_properties(umicom-language-integer-bounds-test PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
umicom_apply_warnings(umicom-language-integer-bounds-test)
umicom_apply_sanitizers(umicom-language-integer-bounds-test)
if(COMMAND umicom_register_validation_target)
    umicom_register_validation_target(umicom-language-integer-bounds-test)
endif()
foreach(case zero negative-zero positive negative signed-max signed-min positive-overflow negative-overflow unsigned-max huge fraction exponent boolean null plus leading-zero negative-leading-zero space suffix empty minus token-bounds)
    add_test(NAME framework.language.json_integer.${case} COMMAND umicom-language-integer-bounds-test "${case}")
    set_tests_properties(framework.language.json_integer.${case} PROPERTIES TIMEOUT 10 LABELS "framework;language;json;bounds")
endforeach()
