# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-folding-query-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_folding_query.c")
    target_link_libraries(umicom-folding-query-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-folding-query-test)
    umicom_apply_sanitizers(umicom-folding-query-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-folding-query-test)
    endif()
    foreach(case valid object missing disabled wrong-provider encoding sync fragmented notification error invalid-result shutdown-error close-error timeout cancel-before cancel-during invalid-source invalid-caret invalid-kind state empty empty-array unicode crlf outside wrong-id read-error write-error)
        add_test(NAME framework.language_runtime.folding_query.${case} COMMAND umicom-folding-query-test ${case})
        set_tests_properties(framework.language_runtime.folding_query.${case} PROPERTIES TIMEOUT 30
            LABELS "framework;language;navigation;ownership;regression")
    endforeach()
endif()
