# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-local-uri-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_local_uri.c")
    target_link_libraries(umicom-document-local-uri-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-local-uri-test)
    umicom_apply_sanitizers(umicom-document-local-uri-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-local-uri-test)
    endif()
    foreach(case plain space unicode localhost case alias capacity nul control separator backslash escape utf8 authority scheme query fragment raw-space relative network limits arguments device device-extension device-port console superscript trailing-dot trailing-space alternate-stream encoded-question)
        add_test(NAME framework.document.local_uri.${case} COMMAND umicom-document-local-uri-test ${case})
        set_tests_properties(framework.document.local_uri.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;source;review;regression")
    endforeach()
endif()
