# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Compile a public header as an independent consumer of its owner's interface.
include_guard(GLOBAL)
function(umicom_add_public_header_compile_check target owner include_root header)
    if(NOT TARGET "${owner}" OR TARGET "${target}" OR NOT target MATCHES "^[A-Za-z0-9_.+-]+$")
        message(FATAL_ERROR "Header check needs an existing owner and an unused ordinary target name")
    endif()
    file(REAL_PATH "${include_root}" _include)
    file(REAL_PATH "${header}" _header BASE_DIRECTORY "${_include}")
    cmake_path(IS_PREFIX _include "${_header}" NORMALIZE _inside)
    if(NOT _inside OR NOT EXISTS "${_header}" OR IS_DIRECTORY "${_header}")
        message(FATAL_ERROR "Header check input must exist within its explicit include root")
    endif()
    file(RELATIVE_PATH _relative "${_include}" "${_header}")
    if(_relative MATCHES "[\"<>;\r\n]")
        message(FATAL_ERROR "Public header cannot be represented as an include: ${_header}")
    endif()
    string(SHA256 _key "${target}\n${_relative}")
# Compact build-only filenames replace the long paths; header ownership and compile isolation are unchanged.
# The previous composition remains for engineering review.
if(FALSE)
    set(_output "${CMAKE_CURRENT_BINARY_DIR}/release-inventory/header-consumers")
    file(MAKE_DIRECTORY "${_output}")
    set(_source "${_output}/${_key}.c")
endif()
    # Keep build paths compact without changing the independent consumer or
    # suppressing any compiler diagnostics. Detect a truncated-hash collision.
    string(SUBSTRING "${_key}" 0 20 _short_key)
    get_property(_existing GLOBAL PROPERTY "UMICOM_HEADER_SOURCE_${_short_key}")
    if(_existing AND NOT _existing STREQUAL _key)
        message(FATAL_ERROR "Public header source digest prefix collision")
    endif()
    set_property(GLOBAL PROPERTY "UMICOM_HEADER_SOURCE_${_short_key}" "${_key}")
    set(_output "${CMAKE_CURRENT_BINARY_DIR}/_umi_hdr")
    file(MAKE_DIRECTORY "${_output}")
    set(_source "${_output}/${_short_key}.c")
    # No preparatory system include or owner's private include path is added.
    # Repeated inclusion checks guards; separate TUs prevent include-order luck.
    file(WRITE "${_source}" "/* Generated public C23 consumer; build output only. */\n#include <${_relative}>\n#include <${_relative}>\nint umicom_header_probe_${_key};\n")
    add_library("${target}" OBJECT EXCLUDE_FROM_ALL "${_source}")
    set_source_files_properties("${_source}" PROPERTIES GENERATED TRUE)
    set_target_properties("${target}" PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO
        UNITY_BUILD OFF DISABLE_PRECOMPILE_HEADERS TRUE)
    target_link_libraries("${target}" PRIVATE "${owner}")
    if(MSVC)
        target_compile_options("${target}" PRIVATE /W4 /WX)
    else()
        target_compile_options("${target}" PRIVATE -Wall -Wextra -Wpedantic -Werror)
    endif()
endfunction()
