# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-native-calls-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_native_calls.c")
    target_link_libraries(umicom-native-calls-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-native-calls-test)
    umicom_apply_sanitizers(umicom-native-calls-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-native-calls-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-native-calls-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-native-calls-test)
    endif()
    foreach(case incoming outgoing empty no-calls no-sites multiple external-root unicode surrogate outside-root outside-site invalid-root invalid prepare-error error second-error shutdown encoding timeout disconnect)
        add_test(NAME framework.language_runtime.native_calls.${case} COMMAND umicom-native-calls-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.language_runtime.native_calls.${case} PROPERTIES TIMEOUT 40
            LABELS "framework;language;calls;native;ownership;regression")
    endforeach()
endif()
