# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-search-options-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_search_options.c")
    target_link_libraries(umicom-document-search-options-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-search-options-test)
    umicom_apply_sanitizers(umicom-document-search-options-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-search-options-test)
    endif()
    foreach(case sensitive insensitive smart-upper smart-lower substring whole-word next-selection backwards wrap-forward wrap-backward read-only invalid-case invalid-word default-options replace-selection replace-boundary replace-ignore-case replace-empty replace-read-only replace-missing replace-default)
        add_test(NAME framework.document.search_options.${case} COMMAND umicom-document-search-options-test ${case})
        set_tests_properties(framework.document.search_options.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;search;replacement;regression")
    endforeach()
endif()

install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/learning/document-search.html" DESTINATION "${CMAKE_INSTALL_DATADIR}/doc/umicom/learning" COMPONENT Development)
