# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-navigation-lines-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_navigation_lines.c")
    target_link_libraries(umicom-document-navigation-lines-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-navigation-lines-test)
    umicom_apply_sanitizers(umicom-document-navigation-lines-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-navigation-lines-test)
    endif()
    foreach(case lf crlf cr mixed unicode column-clamp unicode-clamp missing-line empty-tail bookmark source-range crlf-interior large)
        add_test(NAME framework.document.navigation_lines.${case} COMMAND umicom-document-navigation-lines-test ${case})
        set_tests_properties(framework.document.navigation_lines.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;source;review;regression")
    endforeach()
endif()
