# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Numeric expectations and real scene composition are distinct regressions.
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-candle-study-test "${CMAKE_CURRENT_LIST_DIR}/../tests/chart/test_candle_study.c")
    target_link_libraries(umicom-candle-study-test PRIVATE Umicom::chart)
    add_executable(umicom-candle-study-scene-test "${CMAKE_CURRENT_LIST_DIR}/../tests/chart/test_candle_study_scene.c")
    target_link_libraries(umicom-candle-study-scene-test PRIVATE Umicom::trading_ui)
    foreach(target umicom-candle-study-test umicom-candle-study-scene-test)
        umicom_apply_warnings(${target})
        umicom_apply_sanitizers(${target})
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(${target})
        endif()
    endforeach()
    foreach(case weighted bollinger donchian zero-window large-volume large-price negative-price zero-price constant overflow duplicate-time unsorted nan negative-volume invalid-ohlc period-small period-large kind short empty capacity)
        add_test(NAME framework.chart.candle_study.${case} COMMAND umicom-candle-study-test ${case})
        set_tests_properties(framework.chart.candle_study.${case} PROPERTIES TIMEOUT 20 LABELS "framework;chart;regression")
    endforeach()
    foreach(case weighted bollinger donchian short timeframe)
        add_test(NAME framework.chart.candle_study.scene.${case} COMMAND umicom-candle-study-scene-test ${case})
        set_tests_properties(framework.chart.candle_study.scene.${case} PROPERTIES TIMEOUT 20 LABELS "framework;chart;trading;regression")
    endforeach()
endif()

if(BUILD_TESTING)
    add_executable(umicom-volume-profile-test "${CMAKE_CURRENT_LIST_DIR}/../tests/chart/test_volume_profile.c")
    target_link_libraries(umicom-volume-profile-test PRIVATE Umicom::chart)
    add_executable(umicom-volume-profile-scene-test "${CMAKE_CURRENT_LIST_DIR}/../tests/chart/test_volume_profile_scene.c")
    target_link_libraries(umicom-volume-profile-scene-test PRIVATE Umicom::trading_ui)
    foreach(target umicom-volume-profile-test umicom-volume-profile-scene-test)
        umicom_apply_warnings(${target})
        umicom_apply_sanitizers(${target})
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(${target})
        endif()
    endforeach()
    foreach(case buckets tie full half flat zero empty unordered negative overflow range-overflow collapsed-edge nan-price nan-volume negative-volume small large fraction-zero fraction-large fraction-nan capacity)
        add_test(NAME framework.chart.volume_profile.${case} COMMAND umicom-volume-profile-test ${case})
        set_tests_properties(framework.chart.volume_profile.${case} PROPERTIES TIMEOUT 20 LABELS "framework;chart;volume;regression")
    endforeach()
    foreach(case scene timeframe adapter invalid-time)
        add_test(NAME framework.chart.volume_profile.scene.${case} COMMAND umicom-volume-profile-scene-test ${case})
        set_tests_properties(framework.chart.volume_profile.scene.${case} PROPERTIES TIMEOUT 20 LABELS "framework;chart;trading;regression")
    endforeach()
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/learning/candle-studies.html"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/learning COMPONENT Learning)

if(BUILD_TESTING AND TARGET umicom_ui_gtk4)
    add_executable(umicom-study-selector-gtk-test "${CMAKE_CURRENT_LIST_DIR}/../tests/chart/test_study_selector_gtk4.c")
    target_link_libraries(umicom-study-selector-gtk-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-study-selector-gtk-test)
    umicom_apply_sanitizers(umicom-study-selector-gtk-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-study-selector-gtk-test)
    endif()
    foreach(case weighted bollinger donchian profile retained detached)
        add_test(NAME framework.chart.study_selector.gtk.${case} COMMAND umicom-study-selector-gtk-test ${case})
        set_tests_properties(framework.chart.study_selector.gtk.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77 LABELS "framework;chart;gtk4;ownership;regression")
    endforeach()
endif()
