# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_reload_history_positions)
    if(NOT BUILD_TESTING OR NOT TARGET umicom-document-reload-test)
        return()
    endif()
    foreach(case history-caret history-selection history-dirty)
        add_test(NAME framework.document.reload.${case} COMMAND umicom-document-reload-test ${case})
        set_tests_properties(framework.document.reload.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;reload;history;selection;regression")
    endforeach()
endfunction()
if(TARGET umicom-document-reload-test)
    umicom_attach_reload_history_positions()
else()
    cmake_language(DEFER CALL umicom_attach_reload_history_positions)
endif()
