# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-native-code-actions-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_native_code_actions.c")
    target_link_libraries(umicom-native-code-actions-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-native-code-actions-test)
    umicom_apply_sanitizers(umicom-native-code-actions-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-native-code-actions-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-native-code-actions-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-native-code-actions-test)
    endif()
    foreach(case valid unicode multiline empty error invalid timeout encoding shutdown cancel disabled command edit-command deferred external resource annotation choices literal)
        add_test(NAME framework.language_runtime.native_code_actions.${case} COMMAND umicom-native-code-actions-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.language_runtime.native_code_actions.${case} PROPERTIES TIMEOUT 40
            LABELS "framework;language;code-actions;native;ownership;regression")
    endforeach()
endif()
