# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
target_sources(umicom_document PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/document/source_workspace.c")
if(BUILD_TESTING)
    add_executable(umicom-document-source-workspace-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_source_workspace.c")
    target_link_libraries(umicom-document-source-workspace-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-source-workspace-test)
    umicom_apply_sanitizers(umicom-document-source-workspace-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-source-workspace-test)
    endif()
    foreach(case capture order empty-source unicode owned read-only all-read-only duplicate-id duplicate-uri missing-id zero-id empty-uri invalid-source source-change dependency-change changed-back caret selection language permission uri saved external closed other-owner active-tab presentation new-document maximum count-limit arguments)
        add_test(NAME framework.document.source_workspace.${case} COMMAND umicom-document-source-workspace-test ${case})
        set_tests_properties(framework.document.source_workspace.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;source;dependencies;regression")
    endforeach()
endif()
