#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomNativeWebFrontendPlatform.cmake
#
# PURPOSE:
#   Extend the established Umicom::frontend target with a native C23,
#   server-driven browser renderer built on the existing Umicom::web server.
#
# ARCHITECTURE:
#   Umicom::web remains authoritative for HTTP/WebSocket/SSE/server concerns.
#   Umicom::frontend remains authoritative for multi-frontend plans/sessions.
#   Native Web adds HTML/CSS/DOM projection only; it needs no Wt/WebAssembly.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_NATIVE_WEB_FRONTEND_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
# Load the dependency only when the parent build has not already provided its target.
if(NOT TARGET umicom_frontend OR NOT TARGET umicom_web OR NOT TARGET umicom_ui)
    message(FATAL_ERROR "UmicomNativeWebFrontendPlatform.cmake requires canonical umicom_frontend, umicom_web and umicom_ui targets")
endif()

target_sources(umicom_frontend PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/markup_buffer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/html_escape.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/css_buffer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/semantic_element.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/element_attribute.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/element_tree.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/element_index.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/render_node_bridge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/render_context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/render_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/renderer_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/renderer_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/document_shell.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/asset_bundle.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/client_runtime.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/browser_capability.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/browser_handshake.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/browser_session_bridge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/transport_bridge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/transport_selection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/websocket_patch_protocol.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/sse_patch_protocol.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/polling_patch_protocol.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/heartbeat_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/reconnect_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/patch.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/patch_batch.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/tree_diff.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/patch_serializer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/patch_coalescer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/patch_budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/ui_event.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/event_parser.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/event_queue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/event_dispatch.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/command_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/context_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/focus_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/keyboard_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/drag_drop_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/workbench_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/application_shell_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/layout_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/panel_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/tabs_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/split_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/dock_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/toolbar_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/status_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/command_bar_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/workspace_strip_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/activity_bar_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/explorer_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/editor_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/data_grid_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/chart_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/timeline_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/node_graph_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/media_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/canvas_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/inspector_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/palette_renderer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/gtk_semantic_projection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/frontend_conformance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/frontend/native_web/runtime.c"
)

# Native-web presentation consumes the canonical toolkit-neutral UI/workstation contracts.
target_link_libraries(umicom_frontend PUBLIC Umicom::ui)

# Register verification targets only when the developer has enabled testing.
if(BUILD_TESTING)
    # Define the add native web frontend test build helper so parent and application projects
    # apply one consistent rule.
    function(umicom_add_native_web_frontend_test target test_name source)
        # Configure the optional target only when its feature has created it.
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_NATIVE_WEB_FRONTEND_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::frontend)
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;native-web-frontend")
    endfunction()

    umicom_add_native_web_frontend_test(
        umicom-native-web-types-test
        framework.frontend.native_web.types
        tests/frontend_native_web/test_types.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-markup-buffer-test
        framework.frontend.native_web.markup.buffer
        tests/frontend_native_web/test_markup_buffer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-html-escape-test
        framework.frontend.native_web.html.escape
        tests/frontend_native_web/test_html_escape.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-css-buffer-test
        framework.frontend.native_web.css.buffer
        tests/frontend_native_web/test_css_buffer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-semantic-element-test
        framework.frontend.native_web.semantic.element
        tests/frontend_native_web/test_semantic_element.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-element-attribute-test
        framework.frontend.native_web.element.attribute
        tests/frontend_native_web/test_element_attribute.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-element-tree-test
        framework.frontend.native_web.element.tree
        tests/frontend_native_web/test_element_tree.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-element-index-test
        framework.frontend.native_web.element.index
        tests/frontend_native_web/test_element_index.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-render-node-bridge-test
        framework.frontend.native_web.render.node.bridge
        tests/frontend_native_web/test_render_node_bridge.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-render-context-test
        framework.frontend.native_web.render.context
        tests/frontend_native_web/test_render_context.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-render-result-test
        framework.frontend.native_web.render.result
        tests/frontend_native_web/test_render_result.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-renderer-descriptor-test
        framework.frontend.native_web.renderer.descriptor
        tests/frontend_native_web/test_renderer_descriptor.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-renderer-registry-test
        framework.frontend.native_web.renderer.registry
        tests/frontend_native_web/test_renderer_registry.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-document-shell-test
        framework.frontend.native_web.document.shell
        tests/frontend_native_web/test_document_shell.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-asset-bundle-test
        framework.frontend.native_web.asset.bundle
        tests/frontend_native_web/test_asset_bundle.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-client-runtime-test
        framework.frontend.native_web.client.runtime
        tests/frontend_native_web/test_client_runtime.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-browser-capability-test
        framework.frontend.native_web.browser.capability
        tests/frontend_native_web/test_browser_capability.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-browser-handshake-test
        framework.frontend.native_web.browser.handshake
        tests/frontend_native_web/test_browser_handshake.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-browser-session-bridge-test
        framework.frontend.native_web.browser.session.bridge
        tests/frontend_native_web/test_browser_session_bridge.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-transport-bridge-test
        framework.frontend.native_web.transport.bridge
        tests/frontend_native_web/test_transport_bridge.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-transport-selection-test
        framework.frontend.native_web.transport.selection
        tests/frontend_native_web/test_transport_selection.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-websocket-patch-protocol-test
        framework.frontend.native_web.websocket.patch.protocol
        tests/frontend_native_web/test_websocket_patch_protocol.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-sse-patch-protocol-test
        framework.frontend.native_web.sse.patch.protocol
        tests/frontend_native_web/test_sse_patch_protocol.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-polling-patch-protocol-test
        framework.frontend.native_web.polling.patch.protocol
        tests/frontend_native_web/test_polling_patch_protocol.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-heartbeat-policy-test
        framework.frontend.native_web.heartbeat.policy
        tests/frontend_native_web/test_heartbeat_policy.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-reconnect-policy-test
        framework.frontend.native_web.reconnect.policy
        tests/frontend_native_web/test_reconnect_policy.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-patch-test
        framework.frontend.native_web.patch
        tests/frontend_native_web/test_patch.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-patch-batch-test
        framework.frontend.native_web.patch.batch
        tests/frontend_native_web/test_patch_batch.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-tree-diff-test
        framework.frontend.native_web.tree.diff
        tests/frontend_native_web/test_tree_diff.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-patch-serializer-test
        framework.frontend.native_web.patch.serializer
        tests/frontend_native_web/test_patch_serializer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-patch-coalescer-test
        framework.frontend.native_web.patch.coalescer
        tests/frontend_native_web/test_patch_coalescer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-patch-budget-test
        framework.frontend.native_web.patch.budget
        tests/frontend_native_web/test_patch_budget.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-ui-event-test
        framework.frontend.native_web.ui.event
        tests/frontend_native_web/test_ui_event.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-event-parser-test
        framework.frontend.native_web.event.parser
        tests/frontend_native_web/test_event_parser.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-event-queue-test
        framework.frontend.native_web.event.queue
        tests/frontend_native_web/test_event_queue.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-event-dispatch-test
        framework.frontend.native_web.event.dispatch
        tests/frontend_native_web/test_event_dispatch.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-command-binding-test
        framework.frontend.native_web.command.binding
        tests/frontend_native_web/test_command_binding.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-context-binding-test
        framework.frontend.native_web.context.binding
        tests/frontend_native_web/test_context_binding.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-focus-binding-test
        framework.frontend.native_web.focus.binding
        tests/frontend_native_web/test_focus_binding.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-keyboard-binding-test
        framework.frontend.native_web.keyboard.binding
        tests/frontend_native_web/test_keyboard_binding.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-drag-drop-binding-test
        framework.frontend.native_web.drag.drop.binding
        tests/frontend_native_web/test_drag_drop_binding.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-workbench-renderer-test
        framework.frontend.native_web.workbench.renderer
        tests/frontend_native_web/test_workbench_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-application-shell-renderer-test
        framework.frontend.native_web.application.shell.renderer
        tests/frontend_native_web/test_application_shell_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-layout-renderer-test
        framework.frontend.native_web.layout.renderer
        tests/frontend_native_web/test_layout_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-panel-renderer-test
        framework.frontend.native_web.panel.renderer
        tests/frontend_native_web/test_panel_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-tabs-renderer-test
        framework.frontend.native_web.tabs.renderer
        tests/frontend_native_web/test_tabs_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-split-renderer-test
        framework.frontend.native_web.split.renderer
        tests/frontend_native_web/test_split_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-dock-renderer-test
        framework.frontend.native_web.dock.renderer
        tests/frontend_native_web/test_dock_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-toolbar-renderer-test
        framework.frontend.native_web.toolbar.renderer
        tests/frontend_native_web/test_toolbar_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-status-renderer-test
        framework.frontend.native_web.status.renderer
        tests/frontend_native_web/test_status_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-command-bar-renderer-test
        framework.frontend.native_web.command.bar.renderer
        tests/frontend_native_web/test_command_bar_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-workspace-strip-renderer-test
        framework.frontend.native_web.workspace.strip.renderer
        tests/frontend_native_web/test_workspace_strip_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-activity-bar-renderer-test
        framework.frontend.native_web.activity.bar.renderer
        tests/frontend_native_web/test_activity_bar_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-explorer-renderer-test
        framework.frontend.native_web.explorer.renderer
        tests/frontend_native_web/test_explorer_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-editor-renderer-test
        framework.frontend.native_web.editor.renderer
        tests/frontend_native_web/test_editor_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-data-grid-renderer-test
        framework.frontend.native_web.data.grid.renderer
        tests/frontend_native_web/test_data_grid_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-chart-renderer-test
        framework.frontend.native_web.chart.renderer
        tests/frontend_native_web/test_chart_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-timeline-renderer-test
        framework.frontend.native_web.timeline.renderer
        tests/frontend_native_web/test_timeline_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-node-graph-renderer-test
        framework.frontend.native_web.node.graph.renderer
        tests/frontend_native_web/test_node_graph_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-media-renderer-test
        framework.frontend.native_web.media.renderer
        tests/frontend_native_web/test_media_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-canvas-renderer-test
        framework.frontend.native_web.canvas.renderer
        tests/frontend_native_web/test_canvas_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-inspector-renderer-test
        framework.frontend.native_web.inspector.renderer
        tests/frontend_native_web/test_inspector_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-palette-renderer-test
        framework.frontend.native_web.palette.renderer
        tests/frontend_native_web/test_palette_renderer.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-gtk-semantic-projection-test
        framework.frontend.native_web.gtk.semantic.projection
        tests/frontend_native_web/test_gtk_semantic_projection.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-frontend-conformance-test
        framework.frontend.native_web.frontend.conformance
        tests/frontend_native_web/test_frontend_conformance.c
    )
    umicom_add_native_web_frontend_test(
        umicom-native-web-runtime-test
        framework.frontend.native_web.runtime
        tests/frontend_native_web/test_runtime.c
    )
endif()

message(STATUS "Umicom native C23 server-driven Web frontend enabled (no Wt, no WebAssembly)")
