# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-completion-catalogue-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_completion_catalogue.c")
    target_link_libraries(umicom-completion-catalogue-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-completion-catalogue-test)
    umicom_apply_sanitizers(umicom-completion-catalogue-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-completion-catalogue-test)
    endif()
    foreach(case array list null empty invalid missing-incomplete missing-items label-type missing-label detail-type duplicate duplicate-list format defaults override defaults-type merge-mode additional-type unicode malformed-unicode owned at-atomic cancel item-limit item-boundary byte-limit label-limit arguments)
        add_test(NAME framework.language_runtime.completion_catalogue.${case} COMMAND umicom-completion-catalogue-test ${case})
        set_tests_properties(framework.language_runtime.completion_catalogue.${case} PROPERTIES TIMEOUT 30
            LABELS "framework;language;completion;editor;regression")
    endforeach()
    add_executable(umicom-completion-plan-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_completion_plan.c")
    target_link_libraries(umicom-completion-plan-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-completion-plan-test)
    umicom_apply_sanitizers(umicom-completion-plan-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-completion-plan-test)
    endif()
    foreach(case label insert-text text-edit delete additional insert-choice replace-choice default-range default-label default-empty default-pair item-override snippet indent command overlap duplicate-insert invalid-additional multiline outside negative fraction reversed bad-prefix ambiguous missing-text duplicate-range unicode surrogate crlf replacement-limit expected-limit additional-limit fallback-outside invalid-mode position-missing cancel stale-plan stale-apply cursor-surrogate cr)
        add_test(NAME framework.language_runtime.completion_plan.${case} COMMAND umicom-completion-plan-test ${case})
        set_tests_properties(framework.language_runtime.completion_plan.${case} PROPERTIES TIMEOUT 30
            LABELS "framework;language;completion;editor;regression")
    endforeach()
endif()


if(UMICOM_BUILD_LEARNING_EXAMPLES)
    add_executable(umicom-completion-review-example "${CMAKE_CURRENT_LIST_DIR}/../examples/language_runtime/completion_review.c")
    target_link_libraries(umicom-completion-review-example PRIVATE Umicom::developer Umicom::editor)
    umicom_apply_warnings(umicom-completion-review-example)
    umicom_apply_sanitizers(umicom-completion-review-example)
endif()
