#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomSharedAnalyticsPlatform.cmake
#
# PURPOSE:
#   Extend canonical Umicom::ui with reusable dashboards, charts, gauges,
#   heatmaps, streaming-series and analytical aggregation components.
#
# ARCHITECTURE:
#   Existing Design System specs, workstation chart surface, enterprise data
#   views, reactive state, adaptive shell and appearance contracts remain
#   authoritative. This layer adds analytical models and transformations only.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_UI_ANALYTICS_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
# Load the dependency only when the parent build has not already provided its target.
if(NOT TARGET umicom_ui)
    message(FATAL_ERROR "UmicomSharedAnalyticsPlatform.cmake requires canonical umicom_ui")
endif()

# Shared analytics capability extends the established canonical UI target.
target_sources(umicom_ui PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/data_point.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/time_point.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/category_value.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/series.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/series_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/data_window.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/min_max.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/statistics.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/rolling_statistics.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/percentile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/histogram.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/axis.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/axis_scale.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/axis_range.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/tick_generator.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/legend.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/tooltip.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/crosshair.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/viewport.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/chart_model.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/line_chart.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/area_chart.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/bar_chart.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/stacked_bar_chart.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/scatter_chart.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/candlestick_chart.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/sparkline.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/chart_annotation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/reference_line.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/threshold_band.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/gauge_model.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/radial_gauge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/linear_gauge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/gauge_zone.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/heatmap_model.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/heatmap_scale.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/heatmap_cell.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/matrix_layout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/correlation_heatmap.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/dashboard_metric.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/kpi_model.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/kpi_trend.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/status_indicator.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/dashboard_tile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/dashboard_grid.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/dashboard_layout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/dashboard_filter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/dashboard_context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/dashboard_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/dashboard_service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/analytics_query.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/analytics_filter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/analytics_group.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/analytics_aggregate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/analytics_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/analytics_pipeline.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/streaming_series.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/downsampler.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/lttb_downsampler.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/decimator.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/time_bucket.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/alert_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/alert_state.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/export_table.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/analytics/conformance_profile.c"
)

# Statistical, scaling and downsampling calculations use the standard math library.
if(UNIX AND NOT APPLE)
    target_link_libraries(umicom_ui PRIVATE m)
endif()

# Register verification targets only when the developer has enabled testing.
if(BUILD_TESTING)
    # Define the add ui analytics test build helper so parent and application projects apply
    # one consistent rule.
    function(umicom_add_ui_analytics_test target test_name source)
        # Configure the optional target only when its feature has created it.
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_UI_ANALYTICS_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::ui)
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;ui-analytics;dashboard;charting;visual-analytics")
    endfunction()

    umicom_add_ui_analytics_test(
        umicom-ui-analytics-types-test
        framework.ui_analytics.types
        tests/ui_analytics/test_types.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-data-point-test
        framework.ui_analytics.data.point
        tests/ui_analytics/test_data_point.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-time-point-test
        framework.ui_analytics.time.point
        tests/ui_analytics/test_time_point.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-category-value-test
        framework.ui_analytics.category.value
        tests/ui_analytics/test_category_value.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-series-test
        framework.ui_analytics.series
        tests/ui_analytics/test_series.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-series-registry-test
        framework.ui_analytics.series.registry
        tests/ui_analytics/test_series_registry.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-data-window-test
        framework.ui_analytics.data.window
        tests/ui_analytics/test_data_window.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-min-max-test
        framework.ui_analytics.min.max
        tests/ui_analytics/test_min_max.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-statistics-test
        framework.ui_analytics.statistics
        tests/ui_analytics/test_statistics.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-rolling-statistics-test
        framework.ui_analytics.rolling.statistics
        tests/ui_analytics/test_rolling_statistics.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-percentile-test
        framework.ui_analytics.percentile
        tests/ui_analytics/test_percentile.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-histogram-test
        framework.ui_analytics.histogram
        tests/ui_analytics/test_histogram.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-axis-test
        framework.ui_analytics.axis
        tests/ui_analytics/test_axis.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-axis-scale-test
        framework.ui_analytics.axis.scale
        tests/ui_analytics/test_axis_scale.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-axis-range-test
        framework.ui_analytics.axis.range
        tests/ui_analytics/test_axis_range.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-tick-generator-test
        framework.ui_analytics.tick.generator
        tests/ui_analytics/test_tick_generator.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-legend-test
        framework.ui_analytics.legend
        tests/ui_analytics/test_legend.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-tooltip-test
        framework.ui_analytics.tooltip
        tests/ui_analytics/test_tooltip.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-crosshair-test
        framework.ui_analytics.crosshair
        tests/ui_analytics/test_crosshair.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-viewport-test
        framework.ui_analytics.viewport
        tests/ui_analytics/test_viewport.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-chart-model-test
        framework.ui_analytics.chart.model
        tests/ui_analytics/test_chart_model.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-line-chart-test
        framework.ui_analytics.line.chart
        tests/ui_analytics/test_line_chart.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-area-chart-test
        framework.ui_analytics.area.chart
        tests/ui_analytics/test_area_chart.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-bar-chart-test
        framework.ui_analytics.bar.chart
        tests/ui_analytics/test_bar_chart.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-stacked-bar-chart-test
        framework.ui_analytics.stacked.bar.chart
        tests/ui_analytics/test_stacked_bar_chart.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-scatter-chart-test
        framework.ui_analytics.scatter.chart
        tests/ui_analytics/test_scatter_chart.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-candlestick-chart-test
        framework.ui_analytics.candlestick.chart
        tests/ui_analytics/test_candlestick_chart.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-sparkline-test
        framework.ui_analytics.sparkline
        tests/ui_analytics/test_sparkline.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-chart-annotation-test
        framework.ui_analytics.chart.annotation
        tests/ui_analytics/test_chart_annotation.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-reference-line-test
        framework.ui_analytics.reference.line
        tests/ui_analytics/test_reference_line.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-threshold-band-test
        framework.ui_analytics.threshold.band
        tests/ui_analytics/test_threshold_band.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-gauge-model-test
        framework.ui_analytics.gauge.model
        tests/ui_analytics/test_gauge_model.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-radial-gauge-test
        framework.ui_analytics.radial.gauge
        tests/ui_analytics/test_radial_gauge.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-linear-gauge-test
        framework.ui_analytics.linear.gauge
        tests/ui_analytics/test_linear_gauge.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-gauge-zone-test
        framework.ui_analytics.gauge.zone
        tests/ui_analytics/test_gauge_zone.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-heatmap-model-test
        framework.ui_analytics.heatmap.model
        tests/ui_analytics/test_heatmap_model.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-heatmap-scale-test
        framework.ui_analytics.heatmap.scale
        tests/ui_analytics/test_heatmap_scale.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-heatmap-cell-test
        framework.ui_analytics.heatmap.cell
        tests/ui_analytics/test_heatmap_cell.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-matrix-layout-test
        framework.ui_analytics.matrix.layout
        tests/ui_analytics/test_matrix_layout.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-correlation-heatmap-test
        framework.ui_analytics.correlation.heatmap
        tests/ui_analytics/test_correlation_heatmap.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-dashboard-metric-test
        framework.ui_analytics.dashboard.metric
        tests/ui_analytics/test_dashboard_metric.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-kpi-model-test
        framework.ui_analytics.kpi.model
        tests/ui_analytics/test_kpi_model.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-kpi-trend-test
        framework.ui_analytics.kpi.trend
        tests/ui_analytics/test_kpi_trend.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-status-indicator-test
        framework.ui_analytics.status.indicator
        tests/ui_analytics/test_status_indicator.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-dashboard-tile-test
        framework.ui_analytics.dashboard.tile
        tests/ui_analytics/test_dashboard_tile.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-dashboard-grid-test
        framework.ui_analytics.dashboard.grid
        tests/ui_analytics/test_dashboard_grid.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-dashboard-layout-test
        framework.ui_analytics.dashboard.layout
        tests/ui_analytics/test_dashboard_layout.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-dashboard-filter-test
        framework.ui_analytics.dashboard.filter
        tests/ui_analytics/test_dashboard_filter.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-dashboard-context-test
        framework.ui_analytics.dashboard.context
        tests/ui_analytics/test_dashboard_context.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-dashboard-snapshot-test
        framework.ui_analytics.dashboard.snapshot
        tests/ui_analytics/test_dashboard_snapshot.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-dashboard-service-test
        framework.ui_analytics.dashboard.service
        tests/ui_analytics/test_dashboard_service.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-analytics-query-test
        framework.ui_analytics.analytics.query
        tests/ui_analytics/test_analytics_query.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-analytics-filter-test
        framework.ui_analytics.analytics.filter
        tests/ui_analytics/test_analytics_filter.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-analytics-group-test
        framework.ui_analytics.analytics.group
        tests/ui_analytics/test_analytics_group.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-analytics-aggregate-test
        framework.ui_analytics.analytics.aggregate
        tests/ui_analytics/test_analytics_aggregate.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-analytics-result-test
        framework.ui_analytics.analytics.result
        tests/ui_analytics/test_analytics_result.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-analytics-pipeline-test
        framework.ui_analytics.analytics.pipeline
        tests/ui_analytics/test_analytics_pipeline.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-streaming-series-test
        framework.ui_analytics.streaming.series
        tests/ui_analytics/test_streaming_series.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-downsampler-test
        framework.ui_analytics.downsampler
        tests/ui_analytics/test_downsampler.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-lttb-downsampler-test
        framework.ui_analytics.lttb.downsampler
        tests/ui_analytics/test_lttb_downsampler.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-decimator-test
        framework.ui_analytics.decimator
        tests/ui_analytics/test_decimator.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-time-bucket-test
        framework.ui_analytics.time.bucket
        tests/ui_analytics/test_time_bucket.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-alert-rule-test
        framework.ui_analytics.alert.rule
        tests/ui_analytics/test_alert_rule.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-alert-state-test
        framework.ui_analytics.alert.state
        tests/ui_analytics/test_alert_state.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-export-table-test
        framework.ui_analytics.export.table
        tests/ui_analytics/test_export_table.c
    )
    umicom_add_ui_analytics_test(
        umicom-ui-analytics-conformance-profile-test
        framework.ui_analytics.conformance.profile
        tests/ui_analytics/test_conformance_profile.c
    )
endif()

message(STATUS "Umicom shared dashboard, chart, gauge, heatmap and analytics platform enabled")
