# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
# Extend the existing canonical owners so all products share one receipt model
# and one optional native adapter. Headless consumers require no GTK dependency.
target_sources(umicom_application PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/application/launch_receipts.c")
if(TARGET umicom_ui_gtk4)
    target_sources(umicom_ui_gtk4 PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../adapters/gtk4/application_processes_gtk4.c")
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../include/umicom/application/launch_receipts.h"
    DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/umicom/application" COMPONENT Framework)
if(TARGET umicom_ui_gtk4)
    install(FILES "${CMAKE_CURRENT_LIST_DIR}/../include/umicom/ui/gtk4/application_processes.h"
        DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/umicom/ui/gtk4" COMPONENT Framework)
endif()
if(BUILD_TESTING)
    add_executable(umicom-launch-receipts-test "${CMAKE_CURRENT_LIST_DIR}/../tests/application/test_launch_receipts.c")
    target_link_libraries(umicom-launch-receipts-test PRIVATE Umicom::application)
    umicom_apply_warnings(umicom-launch-receipts-test)
    umicom_apply_sanitizers(umicom-launch-receipts-test)
    foreach(case lifecycle transition duplicate-pending duplicate-running uncertain new-window reopen-exit reopen-rejected capacity-active eviction late-exit ordering text-bounds copied-text output-unchanged description small-description invalid-status null)
        add_test(NAME framework.application.launch_receipts.${case} COMMAND umicom-launch-receipts-test ${case})
        set_tests_properties(framework.application.launch_receipts.${case} PROPERTIES TIMEOUT 30 LABELS "framework;application;process;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-launch-receipts-test)
    endif()
endif()
if(BUILD_TESTING AND TARGET umicom_ui_gtk4)
    add_executable(umicom-native-receipt-child "${CMAKE_CURRENT_LIST_DIR}/../tests/application/native_receipt_child.c")
    target_link_libraries(umicom-native-receipt-child PRIVATE Umicom::ui_gtk4)
    add_executable(umicom-native-receipts-test "${CMAKE_CURRENT_LIST_DIR}/../tests/application/test_native_process_receipts.c")
    target_link_libraries(umicom-native-receipts-test PRIVATE Umicom::ui_gtk4)
    add_dependencies(umicom-native-receipts-test umicom-native-receipt-child)
    foreach(target umicom-native-receipt-child umicom-native-receipts-test)
        umicom_apply_warnings(${target})
        umicom_apply_sanitizers(${target})
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(${target})
        endif()
    endforeach()
    foreach(case relative unknown empty missing wrong-name spawn-failure exit-success exit-failure duplicate new-window unicode-path reentry destroy-active destroy-observer)
        add_test(NAME framework.application.native_receipts.${case}
            COMMAND umicom-native-receipts-test ${case} $<TARGET_FILE:umicom-native-receipt-child>)
        set_tests_properties(framework.application.native_receipts.${case} PROPERTIES TIMEOUT 30 LABELS "framework;application;process;native;regression")
    endforeach()
endif()

if(BUILD_TESTING AND TARGET umicom_ui_gtk4)
    add_executable(umicom-receipt-catalogue-test "${CMAKE_CURRENT_LIST_DIR}/../tests/application/test_receipt_catalogue_gtk4.c")
    target_link_libraries(umicom-receipt-catalogue-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-receipt-catalogue-test)
    umicom_apply_sanitizers(umicom-receipt-catalogue-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-receipt-catalogue-test)
    endif()
    foreach(profile desktop studio trader bank tms music-studio accountant cad creator database-studio education exchange games integration-studio kitchen-designer llm marketplace media-studio mobile-studio operations os rag security-centre web-studio)
        add_test(NAME framework.application.receipt_catalogue.${profile}
            COMMAND umicom-receipt-catalogue-test org.umicom.${profile})
        set_tests_properties(framework.application.receipt_catalogue.${profile} PROPERTIES TIMEOUT 30
            SKIP_RETURN_CODE 77 LABELS "framework;application;gtk4;composition;regression")
    endforeach()
endif()

install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/learning/application-launch-activity.html"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/umicom/framework/docs/learning" COMPONENT Learning)
