# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-source-inspection-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_source_inspection.c")
    target_link_libraries(umicom-document-source-inspection-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-source-inspection-test)
    umicom_apply_sanitizers(umicom-document-source-inspection-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-source-inspection-test)
    endif()
    foreach(case read-only writable empty owned stage-denied apply-denied permission-change source-change caret-change selection-change language-change other-owner other-tab arguments edit-refused)
        add_test(NAME framework.document.source_inspection.${case} COMMAND umicom-document-source-inspection-test ${case})
        set_tests_properties(framework.document.source_inspection.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;source;review;regression")
    endforeach()
endif()
