#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomRegulatoryReportingGovernancePlatform.cmake
#
# PURPOSE:
#   Extend canonical Umicom::finance with regulatory reporting, taxonomies,
#   data governance, lineage, reconciliations and financial-control services.
#
# ARCHITECTURE:
#   Existing finance, accounting, risk, quantitative and enterprise valuation
#   capabilities remain authoritative. This platform adds governed reporting
#   semantics without moving reusable implementation into applications.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_REGULATORY_REPORTING_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
if(NOT TARGET umicom_finance)
    message(FATAL_ERROR "UmicomRegulatoryReportingGovernancePlatform.cmake requires canonical umicom_finance")
endif()

# Regulatory reporting and governance capabilities extend canonical finance.
target_sources(umicom_finance PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/regulatory_authority.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reporting_entity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reporting_taxonomy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/taxonomy_concept.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/taxonomy_dimension.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/taxonomy_member.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/report_template.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/report_section.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/report_field.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reporting_period.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reporting_calendar.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reporting_value.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/report_instance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/report_instance_store.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/report_validation_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/report_validation_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/cross_field_validation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/submission_package.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/submission_channel.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/submission_status.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/submission_history.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/submission_approval.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/attestation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reporting_evidence.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reporting_audit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/source_system.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/golden_source.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/data_domain.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/data_owner.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/data_steward.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/data_lineage_node.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/data_lineage_edge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/lineage_graph.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/data_quality_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/data_quality_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/data_quality_score.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/data_quality_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/completeness_check.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/timeliness_check.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reconciliation_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reconciliation_item.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reconciliation_run.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reconciliation_break.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reconciliation_workflow.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/control_definition.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/control_execution.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/control_evidence.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/control_exception.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/control_remediation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/control_library.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/capital_measure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/capital_ratio.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/liquidity_measure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/liquidity_ratio.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/regulatory_limit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/regulatory_limit_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reporting_schedule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reporting_job.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reporting_queue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reporting_checkpoint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/reporting_replay.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/change_governance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/governance_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/regulatory_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/regulatory/regulatory_service.c"
)


if(BUILD_TESTING)
    function(umicom_add_regulatory_reporting_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_REGULATORY_REPORTING_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::finance)
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;regulatory-reporting;data-governance;financial-control")
    endfunction()

    umicom_add_regulatory_reporting_test(
        umicom-regulatory-types-test
        framework.regulatory.types
        tests/finance_regulatory/test_types.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-regulatory-authority-test
        framework.regulatory.regulatory.authority
        tests/finance_regulatory/test_regulatory_authority.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reporting-entity-test
        framework.regulatory.reporting.entity
        tests/finance_regulatory/test_reporting_entity.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reporting-taxonomy-test
        framework.regulatory.reporting.taxonomy
        tests/finance_regulatory/test_reporting_taxonomy.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-taxonomy-concept-test
        framework.regulatory.taxonomy.concept
        tests/finance_regulatory/test_taxonomy_concept.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-taxonomy-dimension-test
        framework.regulatory.taxonomy.dimension
        tests/finance_regulatory/test_taxonomy_dimension.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-taxonomy-member-test
        framework.regulatory.taxonomy.member
        tests/finance_regulatory/test_taxonomy_member.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-report-template-test
        framework.regulatory.report.template
        tests/finance_regulatory/test_report_template.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-report-section-test
        framework.regulatory.report.section
        tests/finance_regulatory/test_report_section.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-report-field-test
        framework.regulatory.report.field
        tests/finance_regulatory/test_report_field.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reporting-period-test
        framework.regulatory.reporting.period
        tests/finance_regulatory/test_reporting_period.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reporting-calendar-test
        framework.regulatory.reporting.calendar
        tests/finance_regulatory/test_reporting_calendar.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reporting-value-test
        framework.regulatory.reporting.value
        tests/finance_regulatory/test_reporting_value.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-report-instance-test
        framework.regulatory.report.instance
        tests/finance_regulatory/test_report_instance.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-report-instance-store-test
        framework.regulatory.report.instance.store
        tests/finance_regulatory/test_report_instance_store.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-report-validation-rule-test
        framework.regulatory.report.validation.rule
        tests/finance_regulatory/test_report_validation_rule.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-report-validation-result-test
        framework.regulatory.report.validation.result
        tests/finance_regulatory/test_report_validation_result.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-cross-field-validation-test
        framework.regulatory.cross.field.validation
        tests/finance_regulatory/test_cross_field_validation.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-submission-package-test
        framework.regulatory.submission.package
        tests/finance_regulatory/test_submission_package.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-submission-channel-test
        framework.regulatory.submission.channel
        tests/finance_regulatory/test_submission_channel.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-submission-status-test
        framework.regulatory.submission.status
        tests/finance_regulatory/test_submission_status.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-submission-history-test
        framework.regulatory.submission.history
        tests/finance_regulatory/test_submission_history.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-submission-approval-test
        framework.regulatory.submission.approval
        tests/finance_regulatory/test_submission_approval.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-attestation-test
        framework.regulatory.attestation
        tests/finance_regulatory/test_attestation.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reporting-evidence-test
        framework.regulatory.reporting.evidence
        tests/finance_regulatory/test_reporting_evidence.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reporting-audit-test
        framework.regulatory.reporting.audit
        tests/finance_regulatory/test_reporting_audit.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-source-system-test
        framework.regulatory.source.system
        tests/finance_regulatory/test_source_system.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-golden-source-test
        framework.regulatory.golden.source
        tests/finance_regulatory/test_golden_source.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-data-domain-test
        framework.regulatory.data.domain
        tests/finance_regulatory/test_data_domain.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-data-owner-test
        framework.regulatory.data.owner
        tests/finance_regulatory/test_data_owner.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-data-steward-test
        framework.regulatory.data.steward
        tests/finance_regulatory/test_data_steward.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-data-lineage-node-test
        framework.regulatory.data.lineage.node
        tests/finance_regulatory/test_data_lineage_node.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-data-lineage-edge-test
        framework.regulatory.data.lineage.edge
        tests/finance_regulatory/test_data_lineage_edge.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-lineage-graph-test
        framework.regulatory.lineage.graph
        tests/finance_regulatory/test_lineage_graph.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-data-quality-rule-test
        framework.regulatory.data.quality.rule
        tests/finance_regulatory/test_data_quality_rule.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-data-quality-result-test
        framework.regulatory.data.quality.result
        tests/finance_regulatory/test_data_quality_result.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-data-quality-score-test
        framework.regulatory.data.quality.score
        tests/finance_regulatory/test_data_quality_score.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-data-quality-gate-test
        framework.regulatory.data.quality.gate
        tests/finance_regulatory/test_data_quality_gate.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-completeness-check-test
        framework.regulatory.completeness.check
        tests/finance_regulatory/test_completeness_check.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-timeliness-check-test
        framework.regulatory.timeliness.check
        tests/finance_regulatory/test_timeliness_check.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reconciliation-rule-test
        framework.regulatory.reconciliation.rule
        tests/finance_regulatory/test_reconciliation_rule.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reconciliation-item-test
        framework.regulatory.reconciliation.item
        tests/finance_regulatory/test_reconciliation_item.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reconciliation-run-test
        framework.regulatory.reconciliation.run
        tests/finance_regulatory/test_reconciliation_run.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reconciliation-break-test
        framework.regulatory.reconciliation.break
        tests/finance_regulatory/test_reconciliation_break.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reconciliation-workflow-test
        framework.regulatory.reconciliation.workflow
        tests/finance_regulatory/test_reconciliation_workflow.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-control-definition-test
        framework.regulatory.control.definition
        tests/finance_regulatory/test_control_definition.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-control-execution-test
        framework.regulatory.control.execution
        tests/finance_regulatory/test_control_execution.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-control-evidence-test
        framework.regulatory.control.evidence
        tests/finance_regulatory/test_control_evidence.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-control-exception-test
        framework.regulatory.control.exception
        tests/finance_regulatory/test_control_exception.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-control-remediation-test
        framework.regulatory.control.remediation
        tests/finance_regulatory/test_control_remediation.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-control-library-test
        framework.regulatory.control.library
        tests/finance_regulatory/test_control_library.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-capital-measure-test
        framework.regulatory.capital.measure
        tests/finance_regulatory/test_capital_measure.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-capital-ratio-test
        framework.regulatory.capital.ratio
        tests/finance_regulatory/test_capital_ratio.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-liquidity-measure-test
        framework.regulatory.liquidity.measure
        tests/finance_regulatory/test_liquidity_measure.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-liquidity-ratio-test
        framework.regulatory.liquidity.ratio
        tests/finance_regulatory/test_liquidity_ratio.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-regulatory-limit-test
        framework.regulatory.regulatory.limit
        tests/finance_regulatory/test_regulatory_limit.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-regulatory-limit-result-test
        framework.regulatory.regulatory.limit.result
        tests/finance_regulatory/test_regulatory_limit_result.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reporting-schedule-test
        framework.regulatory.reporting.schedule
        tests/finance_regulatory/test_reporting_schedule.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reporting-job-test
        framework.regulatory.reporting.job
        tests/finance_regulatory/test_reporting_job.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reporting-queue-test
        framework.regulatory.reporting.queue
        tests/finance_regulatory/test_reporting_queue.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reporting-checkpoint-test
        framework.regulatory.reporting.checkpoint
        tests/finance_regulatory/test_reporting_checkpoint.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-reporting-replay-test
        framework.regulatory.reporting.replay
        tests/finance_regulatory/test_reporting_replay.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-change-governance-test
        framework.regulatory.change.governance
        tests/finance_regulatory/test_change_governance.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-governance-snapshot-test
        framework.regulatory.governance.snapshot
        tests/finance_regulatory/test_governance_snapshot.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-regulatory-snapshot-test
        framework.regulatory.regulatory.snapshot
        tests/finance_regulatory/test_regulatory_snapshot.c
    )
    umicom_add_regulatory_reporting_test(
        umicom-regulatory-regulatory-service-test
        framework.regulatory.regulatory.service
        tests/finance_regulatory/test_regulatory_service.c
    )
endif()

message(STATUS "Umicom regulatory reporting, data governance and financial control platform enabled")
