# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Separate syntax, persistence, native process and DAP peer checks so failures
# identify the boundary being exercised; these tests never contact a remote service.
include_guard(GLOBAL)
if(NOT BUILD_TESTING)
    return()
endif()
function(umicom_run_environment_target target source library)
    add_executable("${target}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/run_environment/${source}")
    target_link_libraries("${target}" PRIVATE "${library}")
    set_target_properties("${target}" PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings("${target}")
    umicom_apply_sanitizers("${target}")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target("${target}")
    endif()
endfunction()
umicom_run_environment_target(umicom-environment-plan-test test_plan.c Umicom::platform)
umicom_run_environment_target(umicom-environment-storage-test test_storage.c Umicom::build)
umicom_run_environment_target(umicom-environment-profile-test test_profile.c Umicom::build)
umicom_run_environment_target(umicom-environment-producer producer.c Umicom::platform)
umicom_run_environment_target(umicom-environment-child-test test_child.c Umicom::Framework)
add_dependencies(umicom-environment-child-test umicom-environment-producer)
foreach(case empty values invalid duplicates bounds count path inherited)
    add_test(NAME framework.run_environment.plan.${case} COMMAND umicom-environment-plan-test "${case}")
    set_tests_properties(framework.run_environment.plan.${case} PROPERTIES
        TIMEOUT 30 LABELS "framework;environment;launch;regression")
endforeach()
foreach(case migration missing damaged downgrade roundtrip)
    add_test(NAME framework.run_environment.storage.${case} COMMAND umicom-environment-storage-test "${case}")
    set_tests_properties(framework.run_environment.storage.${case} PROPERTIES
        TIMEOUT 30 LABELS "framework;environment;launch;persistence")
endforeach()
foreach(case run stream empty-value)
    add_test(NAME framework.run_environment.child.${case} COMMAND umicom-environment-child-test "${case}" "$<TARGET_FILE:umicom-environment-producer>")
    set_tests_properties(framework.run_environment.child.${case} PROPERTIES
        TIMEOUT 30 LABELS "framework;environment;launch;native")
endforeach()
add_test(NAME framework.run_environment.profile COMMAND umicom-environment-profile-test)
set_tests_properties(framework.run_environment.profile PROPERTIES TIMEOUT 30 LABELS "framework;environment;identity")
if(TARGET umicom-tool-lldb-peer)
    umicom_run_environment_target(umicom-environment-debugger-test test_debugger.c Umicom::Framework)
    add_dependencies(umicom-environment-debugger-test umicom-tool-lldb-peer)
    foreach(case lldb gdb invalid)
        add_test(NAME framework.run_environment.debugger.${case}
            COMMAND umicom-environment-debugger-test "${case}" "$<TARGET_FILE_DIR:umicom-tool-lldb-peer>" "$<TARGET_FILE:umicom-tool-lldb-peer>")
        set_tests_properties(framework.run_environment.debugger.${case} PROPERTIES
            TIMEOUT 30 LABELS "framework;environment;debugger;protocol-fixture")
    endforeach()
endif()
if(TARGET Umicom::ui_gtk4)
    umicom_run_environment_target(umicom-environment-gtk-test test_gtk4.c Umicom::ui_gtk4)
    foreach(case values invalid preset retained cancel)
        add_test(NAME framework.run_environment.gtk4.${case} COMMAND umicom-environment-gtk-test "${case}")
        set_tests_properties(framework.run_environment.gtk4.${case} PROPERTIES
            TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;environment;gtk4;ownership")
    endforeach()
endif()
