# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-web-request-frame-test "${CMAKE_CURRENT_LIST_DIR}/../tests/web/test_request_frame.c")
    target_link_libraries(umicom-web-request-frame-test PRIVATE Umicom::web)
    umicom_apply_warnings(umicom-web-request-frame-test)
    umicom_apply_sanitizers(umicom-web-request-frame-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-web-request-frame-test)
    endif()
    foreach(case get post binary-body head query trimmed length-zero partial-line partial-header partial-body duplicate-length conflicting-length length-list negative-length length-overflow oversized-body missing-host duplicate-host empty-host invalid-host bare-lf bad-cr folded-header whitespace-name control-header null-header unsupported-method unsupported-version chunked expect upgrade pipeline extra-body invalid-target path-capacity limit null-input null-output unchanged)
        add_test(NAME framework.web.request_frame.${case} COMMAND umicom-web-request-frame-test ${case})
        set_tests_properties(framework.web.request_frame.${case} PROPERTIES TIMEOUT 30 LABELS "framework;web;http;regression")
    endforeach()
endif()
