# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
# Reusable projection belongs to chart; the trading service supplies retained observations.
target_sources(umicom_chart PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/chart/timeframe.c")
target_sources(umicom_trading PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/trading/chart_timeframe.c")
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/CHART_TIMEFRAMES.md"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom-framework/docs)
if(NOT BUILD_TESTING)
    return()
endif()
function(umicom_timeframe_cases group)
    set(target "umicom-chart-timeframe-${group}-test")
    add_executable(${target} "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/chart_timeframe/test_${group}.c")
    target_link_libraries(${target} PRIVATE Umicom::trading_ui Umicom::trading_chart_persistence)
    umicom_apply_warnings(${target})
    umicom_apply_sanitizers(${target})
    foreach(case IN LISTS ARGN)
        add_test(NAME "framework.chart_timeframe.${group}.${case}" COMMAND ${target} "${case}")
        set_tests_properties("framework.chart_timeframe.${group}.${case}" PROPERTIES
            TIMEOUT 90 SKIP_RETURN_CODE 77 LABELS "framework;chart;timeframe;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(${target})
    endif()
endfunction()
umicom_timeframe_cases(aggregate source source-overlap exclusive-sequence aggregate empty boundary crossing overlap negative minimum maximum overflow capacity unordered invalid-price unsupported events gap)
umicom_timeframe_cases(time epoch negative leap date hour short bounds catalogue)
umicom_timeframe_cases(workspace aggregate source empty navigation instrument stale unsupported crossing)
umicom_timeframe_cases(persistence restore stale noop)
umicom_timeframe_cases(codec roundtrip legacy version interval overflow partial duplicate unknown negative)
umicom_timeframe_cases(scene aggregate daily empty study)
umicom_timeframe_cases(sqlite)
foreach(case restart rollback)
    add_test(NAME "framework.chart_timeframe.sqlite.${case}" COMMAND umicom-chart-timeframe-sqlite-test "${case}"
        "${CMAKE_CURRENT_BINARY_DIR}/chart-timeframe-${case}.sqlite3")
    set_tests_properties("framework.chart_timeframe.sqlite.${case}" PROPERTIES
        TIMEOUT 90 SKIP_RETURN_CODE 77 LABELS "framework;chart;sqlite;regression")
endforeach()
if(TARGET Umicom::ui_gtk4)
    umicom_timeframe_cases(native select zoom-fit stale restore stale-preview retained-control detached-root)
    target_link_libraries(umicom-chart-timeframe-native-test PRIVATE Umicom::ui_gtk4)
endif()
