# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
# Audit projections share the canonical service and CSV/date contracts.
target_sources(umicom_bank_operations PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/bank_operations/audit_query.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/bank_operations/audit_report.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/bank_operations/audit_text.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/bank_operations/audit_csv.c")
if(BUILD_TESTING)
    function(umicom_bank_audit_cases group)
        set(target "umicom-bank-audit-${group}-test")
        add_executable(${target} "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/bank_audit/test_${group}.c")
        target_link_libraries(${target} PRIVATE Umicom::bank_operations)
        umicom_bank_review_target(${target})
        foreach(case IN LISTS ARGN)
            add_test(NAME "framework.bank_audit.${group}.${case}" COMMAND ${target} "${case}")
            set_tests_properties("framework.bank_audit.${group}.${case}" PROPERTIES TIMEOUT 60 LABELS "bank;audit;regression")
        endforeach()
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(${target})
        endif()
    endfunction()
    umicom_bank_audit_cases(capture all family entity scoped-entity actor request action revision date intersection mismatch exact case-sensitive future ownership idempotent denied)
    umicom_bank_audit_cases(validation id-termination id-alphabet family action date partial-date date-order revision-order orphan journal-reference journal-scale journal-balance journal-overflow event-sequence count bounds)
    umicom_bank_audit_cases(reports summary empty detail no-posting capacity csv journal-csv invalid-utf8)
    umicom_bank_audit_cases(capacity empty-book full large-money)
    umicom_bank_audit_cases(storage)
    foreach(case reopen reload)
        add_test(NAME "framework.bank_audit.storage.${case}" COMMAND umicom-bank-audit-storage-test "${case}" "${CMAKE_CURRENT_BINARY_DIR}/bank-audit-${case}.sqlite")
        set_tests_properties("framework.bank_audit.storage.${case}" PROPERTIES TIMEOUT 90 SKIP_RETURN_CODE 77 LABELS "bank;audit;sqlite;regression")
    endforeach()
    if(TARGET umicom-bank-interest-native-test)
        foreach(case capture filters draft-filters invalid empty selection copy journals cached close)
            add_test(NAME "framework.bank_audit.native.${case}" COMMAND umicom-bank-interest-native-test "audit-${case}")
            set_tests_properties("framework.bank_audit.native.${case}" PROPERTIES TIMEOUT 90 SKIP_RETURN_CODE 77 LABELS "bank;audit;gtk4;regression")
        endforeach()
    endif()
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/BANK_AUDIT_INVESTIGATION.md" DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom-framework/docs)
