# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Shared native credential storage uses isolated OS-call fixtures for coverage.
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-platform-secrets-contract-test "${CMAKE_CURRENT_LIST_DIR}/../tests/platform_secrets/test_contract.c")
    target_link_libraries(umicom-platform-secrets-contract-test PRIVATE Umicom::security)
    umicom_apply_warnings(umicom-platform-secrets-contract-test)
    umicom_apply_sanitizers(umicom-platform-secrets-contract-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-platform-secrets-contract-test)
    endif()
    foreach(case invalid boundaries factory)
        add_test(NAME framework.platform_secrets.${case} COMMAND umicom-platform-secrets-contract-test ${case})
        set_tests_properties(framework.platform_secrets.${case} PROPERTIES TIMEOUT 30 LABELS "framework;security;credentials;regression")
    endforeach()
    if(WIN32)
        add_executable(umicom-platform-secrets-windows-test "${CMAKE_CURRENT_LIST_DIR}/../tests/platform_secrets/test_windows_store.c")
        target_link_libraries(umicom-platform-secrets-windows-test PRIVATE Umicom::security)
        umicom_apply_warnings(umicom-platform-secrets-windows-test)
        umicom_apply_sanitizers(umicom-platform-secrets-windows-test)
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(umicom-platform-secrets-windows-test)
        endif()
        foreach(case roundtrip reopen scope replace write-failure small-buffer unicode limits invalid-name read-failure remove-failure corrupt registry)
            add_test(NAME framework.platform_secrets.windows.${case} COMMAND umicom-platform-secrets-windows-test ${case})
            set_tests_properties(framework.platform_secrets.windows.${case} PROPERTIES TIMEOUT 30 LABELS "framework;security;credentials;fault-injection;regression")
        endforeach()
    endif()
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/learning/storing-provider-keys.html"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/learning COMPONENT Learning)
