# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-view-text-batch-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_view_text_batch.c")
    target_link_libraries(umicom-document-view-text-batch-test PRIVATE Umicom::ui)
    umicom_apply_warnings(umicom-document-view-text-batch-test)
    umicom_apply_sanitizers(umicom-document-view-text-batch-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-view-text-batch-test)
    endif()
    foreach(case publish abort large unchanged duplicate stale-model stale-text wrong-identity wrong-uri wrong-bytes readonly missing invalid-field invalid-cursor embedded-zero too-large arguments)
        add_test(NAME framework.document.document_view_text_batch.${case} COMMAND umicom-document-view-text-batch-test ${case})
        set_tests_properties(framework.document.document_view_text_batch.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;ui;transaction;regression")
    endforeach()
endif()
