#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomWorkbenchMosaicPlatform.cmake
#
# PURPOSE:
#   Extend canonical Umicom::ui with Layout Designer, Panel Catalogue and
#   cross-application mosaic workspace semantics.
#
# ARCHITECTURE:
#   Existing workbench/layout/context/design-system contracts remain authoritative.
#   This layer adds governed editing/catalogue/mosaic services before renderers.
#
# Created by: Sammy Hegab
# Organisation: Umicom Foundation
# Licence: MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_UI_MOSAIC_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
if(NOT TARGET umicom_ui)
    message(FATAL_ERROR "UmicomWorkbenchMosaicPlatform.cmake requires canonical umicom_ui")
endif()

# Layout editing, panel discovery and mixed-application mosaics extend canonical UI.
target_sources(umicom_ui PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_category.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_query.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_filter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_sort.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_favourite.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_recent.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_capability.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_instance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_instance_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_activation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_visibility.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_pinning.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/panel_auto_hide_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/dock_direction.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/dock_target_model.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/dock_guide.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/dock_operation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/dock_transaction.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/dock_history.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/dock_validation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/split_layout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/split_ratio.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/tab_group.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/tab_order.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/floating_panel.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/detached_window.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/window_placement.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/monitor_affinity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/monitor_fallback.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/layout_lock_state.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/layout_edit_session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/layout_snapshot_ref.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/layout_variant.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/layout_preset.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/layout_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/layout_search.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/layout_restore_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/perspective_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/perspective_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/perspective_switch.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/workspace_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/workspace_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/workspace_switch.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/context_link_group.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/context_link_member.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/context_link_colour.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/context_link_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/context_route.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/cross_app_surface.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/application_panel_pack.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/mosaic_cell.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/mosaic_grid.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/mosaic_workspace.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/mosaic_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/mosaic_activation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/layout_command.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/layout_command_set.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/designer_selection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/designer_drag.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/designer_drop_preview.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/designer_inspector.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/workbench_designer_service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/mosaic/workbench_mosaic_service.c"
)

if(BUILD_TESTING)
    function(umicom_add_ui_mosaic_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_UI_MOSAIC_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::ui)
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;ui-mosaic;layout-designer;cross-app-workbench")
    endfunction()

    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-types-test
        framework.ui_mosaic.types
        tests/ui_mosaic/test_types.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-descriptor-test
        framework.ui_mosaic.panel.descriptor
        tests/ui_mosaic/test_panel_descriptor.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-catalogue-test
        framework.ui_mosaic.panel.catalogue
        tests/ui_mosaic/test_panel_catalogue.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-category-test
        framework.ui_mosaic.panel.category
        tests/ui_mosaic/test_panel_category.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-query-test
        framework.ui_mosaic.panel.query
        tests/ui_mosaic/test_panel_query.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-filter-test
        framework.ui_mosaic.panel.filter
        tests/ui_mosaic/test_panel_filter.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-sort-test
        framework.ui_mosaic.panel.sort
        tests/ui_mosaic/test_panel_sort.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-favourite-test
        framework.ui_mosaic.panel.favourite
        tests/ui_mosaic/test_panel_favourite.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-recent-test
        framework.ui_mosaic.panel.recent
        tests/ui_mosaic/test_panel_recent.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-capability-test
        framework.ui_mosaic.panel.capability
        tests/ui_mosaic/test_panel_capability.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-instance-test
        framework.ui_mosaic.panel.instance
        tests/ui_mosaic/test_panel_instance.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-instance-registry-test
        framework.ui_mosaic.panel.instance.registry
        tests/ui_mosaic/test_panel_instance_registry.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-activation-test
        framework.ui_mosaic.panel.activation
        tests/ui_mosaic/test_panel_activation.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-visibility-test
        framework.ui_mosaic.panel.visibility
        tests/ui_mosaic/test_panel_visibility.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-pinning-test
        framework.ui_mosaic.panel.pinning
        tests/ui_mosaic/test_panel_pinning.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-panel-auto-hide-policy-test
        framework.ui_mosaic.panel.auto.hide.policy
        tests/ui_mosaic/test_panel_auto_hide_policy.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-dock-direction-test
        framework.ui_mosaic.dock.direction
        tests/ui_mosaic/test_dock_direction.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-dock-target-model-test
        framework.ui_mosaic.dock.target.model
        tests/ui_mosaic/test_dock_target_model.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-dock-guide-test
        framework.ui_mosaic.dock.guide
        tests/ui_mosaic/test_dock_guide.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-dock-operation-test
        framework.ui_mosaic.dock.operation
        tests/ui_mosaic/test_dock_operation.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-dock-transaction-test
        framework.ui_mosaic.dock.transaction
        tests/ui_mosaic/test_dock_transaction.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-dock-history-test
        framework.ui_mosaic.dock.history
        tests/ui_mosaic/test_dock_history.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-dock-validation-test
        framework.ui_mosaic.dock.validation
        tests/ui_mosaic/test_dock_validation.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-split-layout-test
        framework.ui_mosaic.split.layout
        tests/ui_mosaic/test_split_layout.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-split-ratio-test
        framework.ui_mosaic.split.ratio
        tests/ui_mosaic/test_split_ratio.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-tab-group-test
        framework.ui_mosaic.tab.group
        tests/ui_mosaic/test_tab_group.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-tab-order-test
        framework.ui_mosaic.tab.order
        tests/ui_mosaic/test_tab_order.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-floating-panel-test
        framework.ui_mosaic.floating.panel
        tests/ui_mosaic/test_floating_panel.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-detached-window-test
        framework.ui_mosaic.detached.window
        tests/ui_mosaic/test_detached_window.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-window-placement-test
        framework.ui_mosaic.window.placement
        tests/ui_mosaic/test_window_placement.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-monitor-affinity-test
        framework.ui_mosaic.monitor.affinity
        tests/ui_mosaic/test_monitor_affinity.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-monitor-fallback-test
        framework.ui_mosaic.monitor.fallback
        tests/ui_mosaic/test_monitor_fallback.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-layout-lock-state-test
        framework.ui_mosaic.layout.lock.state
        tests/ui_mosaic/test_layout_lock_state.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-layout-edit-session-test
        framework.ui_mosaic.layout.edit.session
        tests/ui_mosaic/test_layout_edit_session.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-layout-snapshot-ref-test
        framework.ui_mosaic.layout.snapshot.ref
        tests/ui_mosaic/test_layout_snapshot_ref.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-layout-variant-test
        framework.ui_mosaic.layout.variant
        tests/ui_mosaic/test_layout_variant.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-layout-preset-test
        framework.ui_mosaic.layout.preset
        tests/ui_mosaic/test_layout_preset.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-layout-catalogue-test
        framework.ui_mosaic.layout.catalogue
        tests/ui_mosaic/test_layout_catalogue.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-layout-search-test
        framework.ui_mosaic.layout.search
        tests/ui_mosaic/test_layout_search.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-layout-restore-plan-test
        framework.ui_mosaic.layout.restore.plan
        tests/ui_mosaic/test_layout_restore_plan.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-perspective-descriptor-test
        framework.ui_mosaic.perspective.descriptor
        tests/ui_mosaic/test_perspective_descriptor.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-perspective-catalogue-test
        framework.ui_mosaic.perspective.catalogue
        tests/ui_mosaic/test_perspective_catalogue.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-perspective-switch-test
        framework.ui_mosaic.perspective.switch
        tests/ui_mosaic/test_perspective_switch.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-workspace-descriptor-test
        framework.ui_mosaic.workspace.descriptor
        tests/ui_mosaic/test_workspace_descriptor.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-workspace-catalogue-test
        framework.ui_mosaic.workspace.catalogue
        tests/ui_mosaic/test_workspace_catalogue.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-workspace-switch-test
        framework.ui_mosaic.workspace.switch
        tests/ui_mosaic/test_workspace_switch.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-context-link-group-test
        framework.ui_mosaic.context.link.group
        tests/ui_mosaic/test_context_link_group.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-context-link-member-test
        framework.ui_mosaic.context.link.member
        tests/ui_mosaic/test_context_link_member.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-context-link-colour-test
        framework.ui_mosaic.context.link.colour
        tests/ui_mosaic/test_context_link_colour.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-context-link-policy-test
        framework.ui_mosaic.context.link.policy
        tests/ui_mosaic/test_context_link_policy.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-context-route-test
        framework.ui_mosaic.context.route
        tests/ui_mosaic/test_context_route.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-cross-app-surface-test
        framework.ui_mosaic.cross.app.surface
        tests/ui_mosaic/test_cross_app_surface.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-application-panel-pack-test
        framework.ui_mosaic.application.panel.pack
        tests/ui_mosaic/test_application_panel_pack.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-mosaic-cell-test
        framework.ui_mosaic.mosaic.cell
        tests/ui_mosaic/test_mosaic_cell.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-mosaic-grid-test
        framework.ui_mosaic.mosaic.grid
        tests/ui_mosaic/test_mosaic_grid.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-mosaic-workspace-test
        framework.ui_mosaic.mosaic.workspace
        tests/ui_mosaic/test_mosaic_workspace.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-mosaic-profile-test
        framework.ui_mosaic.mosaic.profile
        tests/ui_mosaic/test_mosaic_profile.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-mosaic-activation-test
        framework.ui_mosaic.mosaic.activation
        tests/ui_mosaic/test_mosaic_activation.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-layout-command-test
        framework.ui_mosaic.layout.command
        tests/ui_mosaic/test_layout_command.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-layout-command-set-test
        framework.ui_mosaic.layout.command.set
        tests/ui_mosaic/test_layout_command_set.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-designer-selection-test
        framework.ui_mosaic.designer.selection
        tests/ui_mosaic/test_designer_selection.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-designer-drag-test
        framework.ui_mosaic.designer.drag
        tests/ui_mosaic/test_designer_drag.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-designer-drop-preview-test
        framework.ui_mosaic.designer.drop.preview
        tests/ui_mosaic/test_designer_drop_preview.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-designer-inspector-test
        framework.ui_mosaic.designer.inspector
        tests/ui_mosaic/test_designer_inspector.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-workbench-designer-service-test
        framework.ui_mosaic.workbench.designer.service
        tests/ui_mosaic/test_workbench_designer_service.c
    )
    umicom_add_ui_mosaic_test(
        umicom-ui-mosaic-workbench-mosaic-service-test
        framework.ui_mosaic.workbench.mosaic.service
        tests/ui_mosaic/test_workbench_mosaic_service.c
    )
endif()

message(STATUS "Umicom Layout Designer, Panel Catalogue and cross-application mosaic platform enabled")
