# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Share one pipe-console owner across desktop project hosts.
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/UmicomProcessChannel.cmake")
add_library(umicom_program_console STATIC
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/program_console.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/program_console_worker.c")
add_library(Umicom::program_console ALIAS umicom_program_console)
set_target_properties(umicom_program_console PROPERTIES EXPORT_NAME program_console
    C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
target_include_directories(umicom_program_console PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_LIST_DIR}/../include>
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
target_link_libraries(umicom_program_console PUBLIC Umicom::platform Umicom::process_channel)
umicom_apply_warnings(umicom_program_console)
umicom_apply_sanitizers(umicom_program_console)
install(TARGETS umicom_program_console EXPORT UmicomFrameworkTargets
    ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}" COMPONENT Framework)
target_sources(umicom_build PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/build/program_console.c")
target_link_libraries(umicom_build PUBLIC Umicom::program_console)
if(TARGET umicom_ui_gtk4)
    target_sources(umicom_ui_gtk4 PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../adapters/gtk4/program_console_gtk4.c")
    target_link_libraries(umicom_ui_gtk4 PUBLIC Umicom::program_console)
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/PROGRAM_CONSOLE.html"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/umicom/docs" COMPONENT Framework)
if(NOT BUILD_TESTING)
    return()
endif()
function(umicom_program_console_test target source library)
    add_executable("${target}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/program_console/${source}")
    target_link_libraries("${target}" PRIVATE "${library}")
    set_target_properties("${target}" PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings("${target}")
    umicom_apply_sanitizers("${target}")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target("${target}")
    endif()
endfunction()
umicom_program_console_test(umicom-program-console-producer producer.c Umicom::platform)
umicom_program_console_test(umicom-program-console-queue-test test_queue.c Umicom::program_console)
umicom_program_console_test(umicom-program-console-native-test test_native.c Umicom::program_console)
umicom_program_console_test(umicom-program-console-channel-test test_channel.c Umicom::program_console)
umicom_program_console_test(umicom-program-console-profile-test test_profile.c Umicom::build)
foreach(target umicom-program-console-queue-test umicom-program-console-native-test
        umicom-program-console-channel-test umicom-program-console-profile-test)
    add_dependencies("${target}" umicom-program-console-producer)
endforeach()
function(umicom_program_console_case group target case)
    add_test(NAME framework.program_console.${group}.${case}
        COMMAND "${target}" "${case}" "$<TARGET_FILE:umicom-program-console-producer>")
    set_tests_properties(framework.program_console.${group}.${case} PROPERTIES
        TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;console;process;ownership;regression")
endfunction()
foreach(case capacity eof stop invalid request)
    umicom_program_console_case(queue umicom-program-console-queue-test "${case}")
endforeach()
if(WIN32 OR CMAKE_SYSTEM_NAME STREQUAL "Linux")
    umicom_program_console_test(umicom-program-console-backpressure-test test_backpressure.c Umicom::program_console)
    add_dependencies(umicom-program-console-backpressure-test umicom-program-console-producer)
    foreach(case blocked-input closed-output)
        umicom_program_console_case(flow umicom-program-console-backpressure-test "${case}")
    endforeach()
    foreach(case echo unicode binary eof stop timeout large exit environment copy busy)
        umicom_program_console_case(native umicom-program-console-native-test "${case}")
    endforeach()
    foreach(case inherited restricted override duplicate invalid-name invalid-utf8 eof closed-stdio)
        umicom_program_console_case(channel umicom-program-console-channel-test "${case}")
    endforeach()
    foreach(case launch untrusted lookup missing)
        umicom_program_console_case(profile umicom-program-console-profile-test "${case}")
    endforeach()
    if(TARGET umicom_ui_gtk4)
        umicom_program_console_test(umicom-program-console-gtk-test test_gtk4.c Umicom::ui_gtk4)
        add_dependencies(umicom-program-console-gtk-test umicom-program-console-producer)
        foreach(case input retained close hidden revoke untrusted reentrant prepare-close)
            umicom_program_console_case(gtk4 umicom-program-console-gtk-test "${case}")
        endforeach()
    endif()
endif()
