#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomPrudentialCapitalLiquidityStressPlatform.cmake
#
# PURPOSE:
#   Extend canonical Umicom::finance with prudential capital, liquidity and
#   enterprise stress-testing services.
#
# ARCHITECTURE:
#   This reusable capability is Framework-owned; regulated applications remain
#   thin compositions over canonical finance services.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------

include_guard(GLOBAL)

set(UMICOM_PRUDENTIAL_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
# Load the dependency only when the parent build has not already provided its target.
if(NOT TARGET umicom_finance)
    message(FATAL_ERROR "UmicomPrudentialCapitalLiquidityStressPlatform.cmake requires canonical umicom_finance")
endif()

# Prudential capital, liquidity and stress capabilities extend canonical finance.
target_sources(umicom_finance PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/prudential_entity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/capital_tier.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/capital_resource.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/capital_resource_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/exposure_class.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/exposure_bucket.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/risk_weight_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/risk_weight_table.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/credit_rwa.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/market_rwa.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/operational_rwa.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/total_rwa.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/cet1_ratio.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/tier1_ratio.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/total_capital_ratio.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/leverage_ratio.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/capital_buffer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/conservation_buffer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/countercyclical_buffer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/systemic_buffer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/capital_requirement.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/capital_headroom.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/capital_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/capital_projection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/capital_scenario.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/liquidity_asset.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/hqla_bucket.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/hqla_pool.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/liquidity_outflow.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/liquidity_inflow.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/liquidity_cashflow.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/liquidity_bucket.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/liquidity_ladder.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/lcr_measure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/nsfr_measure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/stable_funding_item.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/required_funding_item.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/liquidity_buffer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/liquidity_headroom.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/funding_concentration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/survival_horizon.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/contingency_funding_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/stress_factor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/stress_scenario.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/stress_scenario_set.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/stress_path.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/stress_shock.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/stress_projection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/stress_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/stress_result_store.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/stress_suite.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/reverse_stress_test.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/sensitivity_stress.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/capital_stress_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/liquidity_stress_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/integrated_stress_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/management_action.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/management_action_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/stress_governance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/stress_evidence.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/stress_audit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/prudential_limit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/prudential_limit_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/prudential_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/prudential/prudential_service.c"
)

# Register verification targets only when the developer has enabled testing.
if(BUILD_TESTING)
    # Define the add prudential test build helper so parent and application projects apply one
    # consistent rule.
    function(umicom_add_prudential_test target test_name source)
        # Configure the optional target only when its feature has created it.
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_PRUDENTIAL_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::finance)
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;prudential-capital;prudential-liquidity;enterprise-stress")
    endfunction()

    umicom_add_prudential_test(
        umicom-prudential-types-test
        framework.prudential.types
        tests/finance_prudential/test_types.c
    )
    umicom_add_prudential_test(
        umicom-prudential-prudential-entity-test
        framework.prudential.prudential.entity
        tests/finance_prudential/test_prudential_entity.c
    )
    umicom_add_prudential_test(
        umicom-prudential-capital-tier-test
        framework.prudential.capital.tier
        tests/finance_prudential/test_capital_tier.c
    )
    umicom_add_prudential_test(
        umicom-prudential-capital-resource-test
        framework.prudential.capital.resource
        tests/finance_prudential/test_capital_resource.c
    )
    umicom_add_prudential_test(
        umicom-prudential-capital-resource-book-test
        framework.prudential.capital.resource.book
        tests/finance_prudential/test_capital_resource_book.c
    )
    umicom_add_prudential_test(
        umicom-prudential-exposure-class-test
        framework.prudential.exposure.class
        tests/finance_prudential/test_exposure_class.c
    )
    umicom_add_prudential_test(
        umicom-prudential-exposure-bucket-test
        framework.prudential.exposure.bucket
        tests/finance_prudential/test_exposure_bucket.c
    )
    umicom_add_prudential_test(
        umicom-prudential-risk-weight-rule-test
        framework.prudential.risk.weight.rule
        tests/finance_prudential/test_risk_weight_rule.c
    )
    umicom_add_prudential_test(
        umicom-prudential-risk-weight-table-test
        framework.prudential.risk.weight.table
        tests/finance_prudential/test_risk_weight_table.c
    )
    umicom_add_prudential_test(
        umicom-prudential-credit-rwa-test
        framework.prudential.credit.rwa
        tests/finance_prudential/test_credit_rwa.c
    )
    umicom_add_prudential_test(
        umicom-prudential-market-rwa-test
        framework.prudential.market.rwa
        tests/finance_prudential/test_market_rwa.c
    )
    umicom_add_prudential_test(
        umicom-prudential-operational-rwa-test
        framework.prudential.operational.rwa
        tests/finance_prudential/test_operational_rwa.c
    )
    umicom_add_prudential_test(
        umicom-prudential-total-rwa-test
        framework.prudential.total.rwa
        tests/finance_prudential/test_total_rwa.c
    )
    umicom_add_prudential_test(
        umicom-prudential-cet1-ratio-test
        framework.prudential.cet1.ratio
        tests/finance_prudential/test_cet1_ratio.c
    )
    umicom_add_prudential_test(
        umicom-prudential-tier1-ratio-test
        framework.prudential.tier1.ratio
        tests/finance_prudential/test_tier1_ratio.c
    )
    umicom_add_prudential_test(
        umicom-prudential-total-capital-ratio-test
        framework.prudential.total.capital.ratio
        tests/finance_prudential/test_total_capital_ratio.c
    )
    umicom_add_prudential_test(
        umicom-prudential-leverage-ratio-test
        framework.prudential.leverage.ratio
        tests/finance_prudential/test_leverage_ratio.c
    )
    umicom_add_prudential_test(
        umicom-prudential-capital-buffer-test
        framework.prudential.capital.buffer
        tests/finance_prudential/test_capital_buffer.c
    )
    umicom_add_prudential_test(
        umicom-prudential-conservation-buffer-test
        framework.prudential.conservation.buffer
        tests/finance_prudential/test_conservation_buffer.c
    )
    umicom_add_prudential_test(
        umicom-prudential-countercyclical-buffer-test
        framework.prudential.countercyclical.buffer
        tests/finance_prudential/test_countercyclical_buffer.c
    )
    umicom_add_prudential_test(
        umicom-prudential-systemic-buffer-test
        framework.prudential.systemic.buffer
        tests/finance_prudential/test_systemic_buffer.c
    )
    umicom_add_prudential_test(
        umicom-prudential-capital-requirement-test
        framework.prudential.capital.requirement
        tests/finance_prudential/test_capital_requirement.c
    )
    umicom_add_prudential_test(
        umicom-prudential-capital-headroom-test
        framework.prudential.capital.headroom
        tests/finance_prudential/test_capital_headroom.c
    )
    umicom_add_prudential_test(
        umicom-prudential-capital-plan-test
        framework.prudential.capital.plan
        tests/finance_prudential/test_capital_plan.c
    )
    umicom_add_prudential_test(
        umicom-prudential-capital-projection-test
        framework.prudential.capital.projection
        tests/finance_prudential/test_capital_projection.c
    )
    umicom_add_prudential_test(
        umicom-prudential-capital-scenario-test
        framework.prudential.capital.scenario
        tests/finance_prudential/test_capital_scenario.c
    )
    umicom_add_prudential_test(
        umicom-prudential-liquidity-asset-test
        framework.prudential.liquidity.asset
        tests/finance_prudential/test_liquidity_asset.c
    )
    umicom_add_prudential_test(
        umicom-prudential-hqla-bucket-test
        framework.prudential.hqla.bucket
        tests/finance_prudential/test_hqla_bucket.c
    )
    umicom_add_prudential_test(
        umicom-prudential-hqla-pool-test
        framework.prudential.hqla.pool
        tests/finance_prudential/test_hqla_pool.c
    )
    umicom_add_prudential_test(
        umicom-prudential-liquidity-outflow-test
        framework.prudential.liquidity.outflow
        tests/finance_prudential/test_liquidity_outflow.c
    )
    umicom_add_prudential_test(
        umicom-prudential-liquidity-inflow-test
        framework.prudential.liquidity.inflow
        tests/finance_prudential/test_liquidity_inflow.c
    )
    umicom_add_prudential_test(
        umicom-prudential-liquidity-cashflow-test
        framework.prudential.liquidity.cashflow
        tests/finance_prudential/test_liquidity_cashflow.c
    )
    umicom_add_prudential_test(
        umicom-prudential-liquidity-bucket-test
        framework.prudential.liquidity.bucket
        tests/finance_prudential/test_liquidity_bucket.c
    )
    umicom_add_prudential_test(
        umicom-prudential-liquidity-ladder-test
        framework.prudential.liquidity.ladder
        tests/finance_prudential/test_liquidity_ladder.c
    )
    umicom_add_prudential_test(
        umicom-prudential-lcr-measure-test
        framework.prudential.lcr.measure
        tests/finance_prudential/test_lcr_measure.c
    )
    umicom_add_prudential_test(
        umicom-prudential-nsfr-measure-test
        framework.prudential.nsfr.measure
        tests/finance_prudential/test_nsfr_measure.c
    )
    umicom_add_prudential_test(
        umicom-prudential-stable-funding-item-test
        framework.prudential.stable.funding.item
        tests/finance_prudential/test_stable_funding_item.c
    )
    umicom_add_prudential_test(
        umicom-prudential-required-funding-item-test
        framework.prudential.required.funding.item
        tests/finance_prudential/test_required_funding_item.c
    )
    umicom_add_prudential_test(
        umicom-prudential-liquidity-buffer-test
        framework.prudential.liquidity.buffer
        tests/finance_prudential/test_liquidity_buffer.c
    )
    umicom_add_prudential_test(
        umicom-prudential-liquidity-headroom-test
        framework.prudential.liquidity.headroom
        tests/finance_prudential/test_liquidity_headroom.c
    )
    umicom_add_prudential_test(
        umicom-prudential-funding-concentration-test
        framework.prudential.funding.concentration
        tests/finance_prudential/test_funding_concentration.c
    )
    umicom_add_prudential_test(
        umicom-prudential-survival-horizon-test
        framework.prudential.survival.horizon
        tests/finance_prudential/test_survival_horizon.c
    )
    umicom_add_prudential_test(
        umicom-prudential-contingency-funding-plan-test
        framework.prudential.contingency.funding.plan
        tests/finance_prudential/test_contingency_funding_plan.c
    )
    umicom_add_prudential_test(
        umicom-prudential-stress-factor-test
        framework.prudential.stress.factor
        tests/finance_prudential/test_stress_factor.c
    )
    umicom_add_prudential_test(
        umicom-prudential-stress-scenario-test
        framework.prudential.stress.scenario
        tests/finance_prudential/test_stress_scenario.c
    )
    umicom_add_prudential_test(
        umicom-prudential-stress-scenario-set-test
        framework.prudential.stress.scenario.set
        tests/finance_prudential/test_stress_scenario_set.c
    )
    umicom_add_prudential_test(
        umicom-prudential-stress-path-test
        framework.prudential.stress.path
        tests/finance_prudential/test_stress_path.c
    )
    umicom_add_prudential_test(
        umicom-prudential-stress-shock-test
        framework.prudential.stress.shock
        tests/finance_prudential/test_stress_shock.c
    )
    umicom_add_prudential_test(
        umicom-prudential-stress-projection-test
        framework.prudential.stress.projection
        tests/finance_prudential/test_stress_projection.c
    )
    umicom_add_prudential_test(
        umicom-prudential-stress-result-test
        framework.prudential.stress.result
        tests/finance_prudential/test_stress_result.c
    )
    umicom_add_prudential_test(
        umicom-prudential-stress-result-store-test
        framework.prudential.stress.result.store
        tests/finance_prudential/test_stress_result_store.c
    )
    umicom_add_prudential_test(
        umicom-prudential-stress-suite-test
        framework.prudential.stress.suite
        tests/finance_prudential/test_stress_suite.c
    )
    umicom_add_prudential_test(
        umicom-prudential-reverse-stress-test-test
        framework.prudential.reverse.stress.test
        tests/finance_prudential/test_reverse_stress_test.c
    )
    umicom_add_prudential_test(
        umicom-prudential-sensitivity-stress-test
        framework.prudential.sensitivity.stress
        tests/finance_prudential/test_sensitivity_stress.c
    )
    umicom_add_prudential_test(
        umicom-prudential-capital-stress-result-test
        framework.prudential.capital.stress.result
        tests/finance_prudential/test_capital_stress_result.c
    )
    umicom_add_prudential_test(
        umicom-prudential-liquidity-stress-result-test
        framework.prudential.liquidity.stress.result
        tests/finance_prudential/test_liquidity_stress_result.c
    )
    umicom_add_prudential_test(
        umicom-prudential-integrated-stress-result-test
        framework.prudential.integrated.stress.result
        tests/finance_prudential/test_integrated_stress_result.c
    )
    umicom_add_prudential_test(
        umicom-prudential-management-action-test
        framework.prudential.management.action
        tests/finance_prudential/test_management_action.c
    )
    umicom_add_prudential_test(
        umicom-prudential-management-action-plan-test
        framework.prudential.management.action.plan
        tests/finance_prudential/test_management_action_plan.c
    )
    umicom_add_prudential_test(
        umicom-prudential-stress-governance-test
        framework.prudential.stress.governance
        tests/finance_prudential/test_stress_governance.c
    )
    umicom_add_prudential_test(
        umicom-prudential-stress-evidence-test
        framework.prudential.stress.evidence
        tests/finance_prudential/test_stress_evidence.c
    )
    umicom_add_prudential_test(
        umicom-prudential-stress-audit-test
        framework.prudential.stress.audit
        tests/finance_prudential/test_stress_audit.c
    )
    umicom_add_prudential_test(
        umicom-prudential-prudential-limit-test
        framework.prudential.prudential.limit
        tests/finance_prudential/test_prudential_limit.c
    )
    umicom_add_prudential_test(
        umicom-prudential-prudential-limit-result-test
        framework.prudential.prudential.limit.result
        tests/finance_prudential/test_prudential_limit_result.c
    )
    umicom_add_prudential_test(
        umicom-prudential-prudential-snapshot-test
        framework.prudential.prudential.snapshot
        tests/finance_prudential/test_prudential_snapshot.c
    )
    umicom_add_prudential_test(
        umicom-prudential-prudential-service-test
        framework.prudential.prudential.service
        tests/finance_prudential/test_prudential_service.c
    )
endif()
