# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING AND TARGET umicom_ui_gtk4)
    add_executable(umicom-workspace-edit-review-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/source_review/test_workspace_edit_gtk4.c")
    target_link_libraries(umicom-workspace-edit-review-native-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-workspace-edit-review-native-test)
    umicom_apply_sanitizers(umicom-workspace-edit-review-native-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-workspace-edit-review-native-test)
    endif()
    foreach(case apply no-review partial-review no-approval review-order stale-first stale-last undo busy cancel destroy unbind parent-close creation-unbind complete-unbind owned-inputs unchanged retained-approval annotation annotation-missing annotation-revoke annotation-retained)
        add_test(NAME framework.source_review.workspace_edit.gtk4.${case} COMMAND umicom-workspace-edit-review-native-test ${case})
        set_tests_properties(framework.source_review.workspace_edit.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77 LABELS "framework;document;replacement;gtk4;regression")
    endforeach()
endif()
