# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_language_connection_panel)
    if(NOT TARGET umicom_ui_gtk4)
        return()
    endif()
    get_target_property(attached umicom_ui_gtk4 UMICOM_LANGUAGE_CONNECTION_ATTACHED)
    if(attached)
        return()
    endif()
    target_sources(umicom_ui_gtk4 PRIVATE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../adapters/gtk4/language_connection_gtk4.c")
    target_link_libraries(umicom_ui_gtk4 PUBLIC Umicom::developer)
    set_property(TARGET umicom_ui_gtk4 PROPERTY UMICOM_LANGUAGE_CONNECTION_ATTACHED TRUE)
    if(BUILD_TESTING)
        add_executable(umicom-language-connection-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/language_runtime/test_connection_gtk4.c")
        target_link_libraries(umicom-language-connection-gtk4-test PRIVATE Umicom::ui_gtk4)
        umicom_apply_warnings(umicom-language-connection-gtk4-test)
        umicom_apply_sanitizers(umicom-language-connection-gtk4-test)
        if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
            target_link_options(umicom-language-connection-gtk4-test PRIVATE -municode)
        endif()
        add_dependencies(umicom-language-connection-gtk4-test umicom-language-process-fixture)
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(umicom-language-connection-gtk4-test)
        endif()
        foreach(case initial invalid success error cancel edit edit-back hide remap close retained notify-close repeat)
            add_test(NAME framework.language_runtime.connection.gtk4.${case}
                COMMAND umicom-language-connection-gtk4-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
            set_tests_properties(framework.language_runtime.connection.gtk4.${case} PROPERTIES
                TIMEOUT 40 SKIP_RETURN_CODE 77 LABELS "framework;language;gtk4;ownership;regression")
        endforeach()
    endif()
endfunction()
umicom_attach_language_connection_panel()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_language_connection_panel)
endif()
