# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_action_menu)
    if(NOT TARGET umicom_ui_gtk4)
        return()
    endif()
    get_target_property(attached umicom_ui_gtk4 UMICOM_ACTION_MENU_ATTACHED)
    if(attached)
        return()
    endif()
    set_target_properties(umicom_ui_gtk4 PROPERTIES UMICOM_ACTION_MENU_ATTACHED TRUE)
    target_sources(umicom_ui_gtk4 PRIVATE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../adapters/gtk4/action_menu_gtk4.c")
    if(BUILD_TESTING)
        add_executable(umicom-action-menu-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/ui_workstation/test_action_menu_gtk4.c")
        target_link_libraries(umicom-action-menu-test PRIVATE Umicom::ui_gtk4)
        umicom_apply_warnings(umicom-action-menu-test)
        umicom_apply_sanitizers(umicom-action-menu-test)
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(umicom-action-menu-test)
        endif()
        foreach(case create empty append parented non-button keyword casefold canonical compatibility clear no-match disabled hidden shown capacity query-limit query-over query-characters invalid-query invalid-keywords invalid-label label-over retained-entry retained-list retained-button retired-popover reentrant-query activation coalesced independent append-filtered invalid-owner null-output)
            add_test(NAME framework.ui.action_menu.gtk4.${case} COMMAND umicom-action-menu-test ${case})
            set_tests_properties(framework.ui.action_menu.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77 LABELS "framework;ui;action-menu;gtk4;ownership;regression")
        endforeach()
    endif()
endfunction()
umicom_attach_action_menu()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_action_menu)
endif()

install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/learning/action-menus.html" DESTINATION "${CMAKE_INSTALL_DATADIR}/doc/umicom/learning" COMPONENT Development)
