# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Configured discovery reuses the developer JSON owner and the platform reader.
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/UmicomJsonTree.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/UmicomBuildCacheReview.cmake")
target_sources(umicom_developer PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/developer_project/target_catalogue.c")
if(BUILD_TESTING)
    add_executable(umicom-configured-targets-test "${CMAKE_CURRENT_LIST_DIR}/../tests/configured_targets/test_catalogue.c")
    target_link_libraries(umicom-configured-targets-test PRIVATE Umicom::developer)
    umicom_apply_warnings(umicom-configured-targets-test)
    umicom_apply_sanitizers(umicom-configured-targets-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-configured-targets-test)
    endif()
    foreach(case unicode-root cancelled cancel-reset valid latest old-error syntax traversal duplicate-field unsupported new-error wrong-root wrong-build identity abstract duplicate-target duplicate-config no-model missing-model missing-target wrong-config bad-artifact nul-artifact byte-limit relative-root empty unnamed multi library ambiguous no-artifact launcher stale-profile build-preset)
        add_test(NAME framework.configured_targets.catalogue.${case} COMMAND umicom-configured-targets-test ${case})
        set_tests_properties(framework.configured_targets.catalogue.${case} PROPERTIES TIMEOUT 30
            LABELS "framework;developer;cmake;regression")
    endforeach()
    add_executable(umicom-configured-targets-scale-test "${CMAKE_CURRENT_LIST_DIR}/../tests/configured_targets/test_scale.c")
    target_link_libraries(umicom-configured-targets-scale-test PRIVATE Umicom::developer)
    umicom_apply_warnings(umicom-configured-targets-scale-test)
    umicom_apply_sanitizers(umicom-configured-targets-scale-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-configured-targets-scale-test)
    endif()
    foreach(case many-targets large-target duplicate-name duplicate-identity)
        add_test(NAME framework.configured_targets.scale.${case} COMMAND umicom-configured-targets-scale-test ${case})
        set_tests_properties(framework.configured_targets.scale.${case} PROPERTIES TIMEOUT 120
            LABELS "framework;developer;cmake;regression")
    endforeach()
endif()
function(umicom_attach_configured_target_native_checks)
    if(NOT BUILD_TESTING OR NOT TARGET umicom_ui_gtk4 OR TARGET umicom-configured-targets-gtk4-test)
        return()
    endif()
    add_executable(umicom-configured-targets-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/configured_targets/test_gtk4.c")
    target_link_libraries(umicom-configured-targets-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-configured-targets-gtk4-test)
    umicom_apply_sanitizers(umicom-configured-targets-gtk4-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-configured-targets-gtk4-test)
    endif()
    foreach(case cache-read cache-mismatch cache-missing cache-close cache-hide cache-changed read program build apply no-auto-read query query-existing query-conflict query-missing query-empty pending-destroy pending-hide pending-parent changed-input reentrant-entry reentrant-model model-destroy refresh-failure)
        add_test(NAME framework.configured_targets.gtk4.${case} COMMAND umicom-configured-targets-gtk4-test ${case})
        set_tests_properties(framework.configured_targets.gtk4.${case} PROPERTIES TIMEOUT 40 SKIP_RETURN_CODE 77
            LABELS "framework;developer;cmake;gtk4;ownership;regression")
    endforeach()
    # Additional choices exercise source identity after visible-row reordering.
    foreach(case projection-program projection-build projection-hidden projection-invalidated)
        add_test(NAME framework.configured_targets.gtk4.${case} COMMAND umicom-configured-targets-gtk4-test ${case})
        set_tests_properties(framework.configured_targets.gtk4.${case} PROPERTIES TIMEOUT 40 SKIP_RETURN_CODE 77
            LABELS "framework;developer;cmake;gtk4;projection;regression")
    endforeach()
endfunction()
umicom_attach_configured_target_native_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_configured_target_native_checks)
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/learning/discover-configured-targets.html"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/learning COMPONENT Learning)
