#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomNativeCompilerPlatform.cmake
#
# PURPOSE:
#   Extend the established Umicom::compiler target with the native C23 compiler
#   pipeline, compact IR, optimization passes, machine lowering, object/link
#   planning, incremental compilation and controlled Umicc self-hosting gates.
#
# ARCHITECTURE:
#   Existing GCC, Clang, MSVC, Assembly, UAI and Umicc providers remain
#   authoritative provider boundaries. This platform adds reusable native
#   compiler internals without creating a competing compiler target.
#
# Created by: Sammy Hegab
# Organisation: Umicom Foundation
# Licence: MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_NATIVE_COMPILER_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
if(NOT TARGET umicom_compiler)
    message(FATAL_ERROR "UmicomNativeCompilerPlatform.cmake requires canonical umicom_compiler")
endif()

target_sources(umicom_compiler PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/source_buffer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/source_location.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/token.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/token_stream.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/lexer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/directive.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/macro.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/macro_table.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/include_path.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/preprocess_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/ast_node.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/ast_arena.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/translation_unit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/declaration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/function_decl.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/type_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/type_table.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/symbol.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/scope.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/symbol_table.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/semantic_issue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/semantic_context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/constant_value.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/constant_eval.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/ir_type.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/ir_value.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/ir_instruction.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/ir_block.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/ir_function.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/ir_module.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/ir_builder.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/ir_verifier.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/cfg_analysis.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/use_analysis.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/liveness_analysis.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/optimization_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/optimization_pass.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/pass_manager.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/constant_folding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/dead_code_elimination.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/copy_propagation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/branch_simplify.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/target_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/target_machine.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/register_class.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/machine_operand.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/machine_instruction.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/machine_block.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/machine_function.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/calling_convention.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/frame_layout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/instruction_selection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/riscv64_lowering.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/x86_64_lowering.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/assembly_emitter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/object_section.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/relocation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/object_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/link_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/incremental_compile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/compile_fingerprint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/compilation_pipeline.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/provider_bridge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/self_host_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/compiler/native/compiler_session.c"
)

if(BUILD_TESTING)
    function(umicom_add_native_compiler_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_NATIVE_COMPILER_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::compiler)
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;native-compiler;umicc")
    endfunction()

    umicom_add_native_compiler_test(
        umicom-native-compiler-types-test
        framework.compiler.native.types
        tests/compiler_native/test_types.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-source-buffer-test
        framework.compiler.native.source.buffer
        tests/compiler_native/test_source_buffer.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-source-location-test
        framework.compiler.native.source.location
        tests/compiler_native/test_source_location.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-token-test
        framework.compiler.native.token
        tests/compiler_native/test_token.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-token-stream-test
        framework.compiler.native.token.stream
        tests/compiler_native/test_token_stream.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-lexer-test
        framework.compiler.native.lexer
        tests/compiler_native/test_lexer.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-directive-test
        framework.compiler.native.directive
        tests/compiler_native/test_directive.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-macro-test
        framework.compiler.native.macro
        tests/compiler_native/test_macro.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-macro-table-test
        framework.compiler.native.macro.table
        tests/compiler_native/test_macro_table.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-include-path-test
        framework.compiler.native.include.path
        tests/compiler_native/test_include_path.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-preprocess-plan-test
        framework.compiler.native.preprocess.plan
        tests/compiler_native/test_preprocess_plan.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-ast-node-test
        framework.compiler.native.ast.node
        tests/compiler_native/test_ast_node.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-ast-arena-test
        framework.compiler.native.ast.arena
        tests/compiler_native/test_ast_arena.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-translation-unit-test
        framework.compiler.native.translation.unit
        tests/compiler_native/test_translation_unit.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-declaration-test
        framework.compiler.native.declaration
        tests/compiler_native/test_declaration.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-function-decl-test
        framework.compiler.native.function.decl
        tests/compiler_native/test_function_decl.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-type-descriptor-test
        framework.compiler.native.type.descriptor
        tests/compiler_native/test_type_descriptor.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-type-table-test
        framework.compiler.native.type.table
        tests/compiler_native/test_type_table.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-symbol-test
        framework.compiler.native.symbol
        tests/compiler_native/test_symbol.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-scope-test
        framework.compiler.native.scope
        tests/compiler_native/test_scope.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-symbol-table-test
        framework.compiler.native.symbol.table
        tests/compiler_native/test_symbol_table.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-semantic-issue-test
        framework.compiler.native.semantic.issue
        tests/compiler_native/test_semantic_issue.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-semantic-context-test
        framework.compiler.native.semantic.context
        tests/compiler_native/test_semantic_context.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-constant-value-test
        framework.compiler.native.constant.value
        tests/compiler_native/test_constant_value.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-constant-eval-test
        framework.compiler.native.constant.eval
        tests/compiler_native/test_constant_eval.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-ir-type-test
        framework.compiler.native.ir.type
        tests/compiler_native/test_ir_type.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-ir-value-test
        framework.compiler.native.ir.value
        tests/compiler_native/test_ir_value.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-ir-instruction-test
        framework.compiler.native.ir.instruction
        tests/compiler_native/test_ir_instruction.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-ir-block-test
        framework.compiler.native.ir.block
        tests/compiler_native/test_ir_block.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-ir-function-test
        framework.compiler.native.ir.function
        tests/compiler_native/test_ir_function.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-ir-module-test
        framework.compiler.native.ir.module
        tests/compiler_native/test_ir_module.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-ir-builder-test
        framework.compiler.native.ir.builder
        tests/compiler_native/test_ir_builder.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-ir-verifier-test
        framework.compiler.native.ir.verifier
        tests/compiler_native/test_ir_verifier.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-cfg-analysis-test
        framework.compiler.native.cfg.analysis
        tests/compiler_native/test_cfg_analysis.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-use-analysis-test
        framework.compiler.native.use.analysis
        tests/compiler_native/test_use_analysis.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-liveness-analysis-test
        framework.compiler.native.liveness.analysis
        tests/compiler_native/test_liveness_analysis.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-optimization-profile-test
        framework.compiler.native.optimization.profile
        tests/compiler_native/test_optimization_profile.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-optimization-pass-test
        framework.compiler.native.optimization.pass
        tests/compiler_native/test_optimization_pass.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-pass-manager-test
        framework.compiler.native.pass.manager
        tests/compiler_native/test_pass_manager.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-constant-folding-test
        framework.compiler.native.constant.folding
        tests/compiler_native/test_constant_folding.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-dead-code-elimination-test
        framework.compiler.native.dead.code.elimination
        tests/compiler_native/test_dead_code_elimination.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-copy-propagation-test
        framework.compiler.native.copy.propagation
        tests/compiler_native/test_copy_propagation.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-branch-simplify-test
        framework.compiler.native.branch.simplify
        tests/compiler_native/test_branch_simplify.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-target-profile-test
        framework.compiler.native.target.profile
        tests/compiler_native/test_target_profile.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-target-machine-test
        framework.compiler.native.target.machine
        tests/compiler_native/test_target_machine.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-register-class-test
        framework.compiler.native.register.class
        tests/compiler_native/test_register_class.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-machine-operand-test
        framework.compiler.native.machine.operand
        tests/compiler_native/test_machine_operand.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-machine-instruction-test
        framework.compiler.native.machine.instruction
        tests/compiler_native/test_machine_instruction.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-machine-block-test
        framework.compiler.native.machine.block
        tests/compiler_native/test_machine_block.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-machine-function-test
        framework.compiler.native.machine.function
        tests/compiler_native/test_machine_function.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-calling-convention-test
        framework.compiler.native.calling.convention
        tests/compiler_native/test_calling_convention.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-frame-layout-test
        framework.compiler.native.frame.layout
        tests/compiler_native/test_frame_layout.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-instruction-selection-test
        framework.compiler.native.instruction.selection
        tests/compiler_native/test_instruction_selection.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-riscv64-lowering-test
        framework.compiler.native.riscv64.lowering
        tests/compiler_native/test_riscv64_lowering.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-x86-64-lowering-test
        framework.compiler.native.x86.64.lowering
        tests/compiler_native/test_x86_64_lowering.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-assembly-emitter-test
        framework.compiler.native.assembly.emitter
        tests/compiler_native/test_assembly_emitter.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-object-section-test
        framework.compiler.native.object.section
        tests/compiler_native/test_object_section.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-relocation-test
        framework.compiler.native.relocation
        tests/compiler_native/test_relocation.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-object-plan-test
        framework.compiler.native.object.plan
        tests/compiler_native/test_object_plan.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-link-plan-test
        framework.compiler.native.link.plan
        tests/compiler_native/test_link_plan.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-incremental-compile-test
        framework.compiler.native.incremental.compile
        tests/compiler_native/test_incremental_compile.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-compile-fingerprint-test
        framework.compiler.native.compile.fingerprint
        tests/compiler_native/test_compile_fingerprint.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-compilation-pipeline-test
        framework.compiler.native.compilation.pipeline
        tests/compiler_native/test_compilation_pipeline.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-provider-bridge-test
        framework.compiler.native.provider.bridge
        tests/compiler_native/test_provider_bridge.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-self-host-gate-test
        framework.compiler.native.self.host.gate
        tests/compiler_native/test_self_host_gate.c
    )
    umicom_add_native_compiler_test(
        umicom-native-compiler-compiler-session-test
        framework.compiler.native.compiler.session
        tests/compiler_native/test_compiler_session.c
    )
endif()

message(STATUS "Umicom native compiler pipeline, IR, optimizer and self-host platform enabled")
