# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_recovery_native_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-recovery-gtk4-test)
        return()
    endif()
    add_executable(umicom-recovery-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_recovery_gtk4.c")
    target_link_libraries(umicom-recovery-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-recovery-gtk4-test)
    umicom_apply_sanitizers(umicom-recovery-gtk4-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-recovery-gtk4-test)
    endif()
    foreach(case open empty-list capture preview restore pending-source selection unicode no-document read-only malformed missing change-selection worker-close worker-unbind parent-close retained-control restore-detach creation-unbind busy invalid-base preview-changed preview-substituted)
        add_test(NAME framework.document.recovery.gtk4.${case} COMMAND umicom-recovery-gtk4-test ${case})
        set_tests_properties(framework.document.recovery.gtk4.${case} PROPERTIES TIMEOUT 60 SKIP_RETURN_CODE 77 LABELS "framework;document;recovery;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_recovery_native_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_recovery_native_checks)
endif()
