#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomBrokerConnectivityExecutionPlatform.cmake
#
# PURPOSE:
#   Complete provider-neutral broker connectivity, paper trading, account/order/
#   execution/position synchronisation, pre-trade risk, reconciliation, audit
#   and the Interactive Brokers adapter boundary.
#
# ARCHITECTURE:
#   Canonical Umicom::trading records, risk services, broker ABI and simulated
#   broker remain authoritative. Vendor types never cross Framework public C ABI
#   boundaries. Live trading remains approval-gated and is never auto-armed.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

if(NOT TARGET umicom_trading)
    message(FATAL_ERROR
        "Broker Connectivity Execution Platform requires canonical umicom_trading")
endif()

target_sources(umicom_trading PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/broker_connectivity_internal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/provider_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/session_supervisor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/account_store.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/order_journal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/execution_reconciler.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/position_store.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/pretrade_guard.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/audit_journal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/ibkr_adapter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/paper_runtime.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/account/buying_power.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/account/cash.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/account/currency_mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/account/daily_pnl.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/account/margin_utilisation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/account/net_liquidation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/account/realised_pnl.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/account/reconciliation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/account/sync.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/account/unrealised_pnl.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/audit/causation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/audit/correction.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/audit/gap.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/audit/integrity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/audit/persistence.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/audit/readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/audit/rejection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/audit/sequence.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/audit/source.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/audit/timestamp.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/execution/audit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/execution/average_price.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/execution/commission.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/execution/correction.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/execution/duplicate_detection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/execution/fill_progress.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/execution/late_detection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/execution/quality.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/execution/reconciliation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/execution/slippage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/ibkr/account_mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/ibkr/client_id.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/ibkr/configuration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/ibkr/contract_mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/ibkr/error_mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/ibkr/execution_mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/ibkr/heartbeat.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/ibkr/order_mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/ibkr/status_mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/ibkr/transport.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/order/ack_latency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/order/cancel_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/order/idempotency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/order/mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/order/reject_attention.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/order/replace_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/order/route_readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/order/state_sync.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/order/submit_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/order/working_notional.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/position/average_cost.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/position/concentration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/position/freshness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/position/gross_exposure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/position/market_value.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/position/net_exposure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/position/quantity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/position/realised_pnl.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/position/reconciliation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/position/unrealised_pnl.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/provider/authentication.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/provider/capabilities.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/provider/connection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/provider/contract.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/provider/health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/provider/heartbeat.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/provider/latency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/provider/live_mode.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/provider/paper_mode.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/provider/reconnect.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/risk/buying_power.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/risk/concentration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/risk/daily_loss.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/risk/kill_switch.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/risk/leverage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/risk/order_notional.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/risk/order_quantity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/risk/position_quantity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/risk/pretrade_readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/broker_connectivity/risk/price_band.c"
)

if(BUILD_TESTING)
    function(umicom_add_broker_connectivity_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()

        add_executable(
            "${target}"
            "${CMAKE_CURRENT_LIST_DIR}/../tests/broker_connectivity/${source}"
        )
        target_link_libraries("${target}" PRIVATE Umicom::Framework)

        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()

        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties(
            "${test_name}"
            PROPERTIES LABELS
            "framework;trading;broker;paper;execution;risk;reconciliation;ibkr"
        )
    endfunction()

    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-types-test
        framework.broker_connectivity.types
        test_types.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-service-test
        framework.broker_connectivity.service
        test_service_catalogue.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-provider-registry-test
        framework.broker_connectivity.provider.registry
        test_provider_registry.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-session-supervisor-test
        framework.broker_connectivity.session.supervisor
        test_session_supervisor.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-account-store-test
        framework.broker_connectivity.account.store
        test_account_store.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-order-journal-test
        framework.broker_connectivity.order.journal
        test_order_journal.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-execution-reconciler-test
        framework.broker_connectivity.execution.reconciler
        test_execution_reconciler.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-position-store-test
        framework.broker_connectivity.position.store
        test_position_store.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-pretrade-guard-test
        framework.broker_connectivity.pretrade.guard
        test_pretrade_guard.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-audit-journal-test
        framework.broker_connectivity.audit.journal
        test_audit_journal.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-ibkr-adapter-test
        framework.broker_connectivity.ibkr.adapter
        test_ibkr_adapter.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-paper-runtime-test
        framework.broker_connectivity.paper.runtime
        test_paper_runtime.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-account-buying-power-test
        framework.broker_connectivity.account.buying.power
        test_account_buying_power.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-account-cash-test
        framework.broker_connectivity.account.cash
        test_account_cash.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-account-currency-mapping-test
        framework.broker_connectivity.account.currency.mapping
        test_account_currency_mapping.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-account-daily-pnl-test
        framework.broker_connectivity.account.daily.pnl
        test_account_daily_pnl.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-account-margin-utilisation-test
        framework.broker_connectivity.account.margin.utilisation
        test_account_margin_utilisation.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-account-net-liquidation-test
        framework.broker_connectivity.account.net.liquidation
        test_account_net_liquidation.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-account-realised-pnl-test
        framework.broker_connectivity.account.realised.pnl
        test_account_realised_pnl.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-account-reconciliation-test
        framework.broker_connectivity.account.reconciliation
        test_account_reconciliation.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-account-sync-test
        framework.broker_connectivity.account.sync
        test_account_sync.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-account-unrealised-pnl-test
        framework.broker_connectivity.account.unrealised.pnl
        test_account_unrealised_pnl.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-audit-causation-test
        framework.broker_connectivity.audit.causation
        test_audit_causation.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-audit-correction-test
        framework.broker_connectivity.audit.correction
        test_audit_correction.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-audit-gap-test
        framework.broker_connectivity.audit.gap
        test_audit_gap.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-audit-integrity-test
        framework.broker_connectivity.audit.integrity
        test_audit_integrity.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-audit-persistence-test
        framework.broker_connectivity.audit.persistence
        test_audit_persistence.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-audit-readiness-test
        framework.broker_connectivity.audit.readiness
        test_audit_readiness.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-audit-rejection-test
        framework.broker_connectivity.audit.rejection
        test_audit_rejection.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-audit-sequence-test
        framework.broker_connectivity.audit.sequence
        test_audit_sequence.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-audit-source-test
        framework.broker_connectivity.audit.source
        test_audit_source.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-audit-timestamp-test
        framework.broker_connectivity.audit.timestamp
        test_audit_timestamp.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-execution-audit-test
        framework.broker_connectivity.execution.audit
        test_execution_audit.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-execution-average-price-test
        framework.broker_connectivity.execution.average.price
        test_execution_average_price.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-execution-commission-test
        framework.broker_connectivity.execution.commission
        test_execution_commission.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-execution-correction-test
        framework.broker_connectivity.execution.correction
        test_execution_correction.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-execution-duplicate-detection-test
        framework.broker_connectivity.execution.duplicate.detection
        test_execution_duplicate_detection.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-execution-fill-progress-test
        framework.broker_connectivity.execution.fill.progress
        test_execution_fill_progress.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-execution-late-detection-test
        framework.broker_connectivity.execution.late.detection
        test_execution_late_detection.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-execution-quality-test
        framework.broker_connectivity.execution.quality
        test_execution_quality.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-execution-reconciliation-test
        framework.broker_connectivity.execution.reconciliation
        test_execution_reconciliation.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-execution-slippage-test
        framework.broker_connectivity.execution.slippage
        test_execution_slippage.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-ibkr-account-mapping-test
        framework.broker_connectivity.ibkr.account.mapping
        test_ibkr_account_mapping.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-ibkr-client-id-test
        framework.broker_connectivity.ibkr.client.id
        test_ibkr_client_id.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-ibkr-configuration-test
        framework.broker_connectivity.ibkr.configuration
        test_ibkr_configuration.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-ibkr-contract-mapping-test
        framework.broker_connectivity.ibkr.contract.mapping
        test_ibkr_contract_mapping.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-ibkr-error-mapping-test
        framework.broker_connectivity.ibkr.error.mapping
        test_ibkr_error_mapping.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-ibkr-execution-mapping-test
        framework.broker_connectivity.ibkr.execution.mapping
        test_ibkr_execution_mapping.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-ibkr-heartbeat-test
        framework.broker_connectivity.ibkr.heartbeat
        test_ibkr_heartbeat.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-ibkr-order-mapping-test
        framework.broker_connectivity.ibkr.order.mapping
        test_ibkr_order_mapping.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-ibkr-status-mapping-test
        framework.broker_connectivity.ibkr.status.mapping
        test_ibkr_status_mapping.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-ibkr-transport-test
        framework.broker_connectivity.ibkr.transport
        test_ibkr_transport.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-order-ack-latency-test
        framework.broker_connectivity.order.ack.latency
        test_order_ack_latency.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-order-cancel-gate-test
        framework.broker_connectivity.order.cancel.gate
        test_order_cancel_gate.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-order-idempotency-test
        framework.broker_connectivity.order.idempotency
        test_order_idempotency.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-order-mapping-test
        framework.broker_connectivity.order.mapping
        test_order_mapping.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-order-reject-attention-test
        framework.broker_connectivity.order.reject.attention
        test_order_reject_attention.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-order-replace-gate-test
        framework.broker_connectivity.order.replace.gate
        test_order_replace_gate.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-order-route-readiness-test
        framework.broker_connectivity.order.route.readiness
        test_order_route_readiness.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-order-state-sync-test
        framework.broker_connectivity.order.state.sync
        test_order_state_sync.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-order-submit-gate-test
        framework.broker_connectivity.order.submit.gate
        test_order_submit_gate.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-order-working-notional-test
        framework.broker_connectivity.order.working.notional
        test_order_working_notional.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-position-average-cost-test
        framework.broker_connectivity.position.average.cost
        test_position_average_cost.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-position-concentration-test
        framework.broker_connectivity.position.concentration
        test_position_concentration.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-position-freshness-test
        framework.broker_connectivity.position.freshness
        test_position_freshness.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-position-gross-exposure-test
        framework.broker_connectivity.position.gross.exposure
        test_position_gross_exposure.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-position-market-value-test
        framework.broker_connectivity.position.market.value
        test_position_market_value.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-position-net-exposure-test
        framework.broker_connectivity.position.net.exposure
        test_position_net_exposure.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-position-quantity-test
        framework.broker_connectivity.position.quantity
        test_position_quantity.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-position-realised-pnl-test
        framework.broker_connectivity.position.realised.pnl
        test_position_realised_pnl.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-position-reconciliation-test
        framework.broker_connectivity.position.reconciliation
        test_position_reconciliation.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-position-unrealised-pnl-test
        framework.broker_connectivity.position.unrealised.pnl
        test_position_unrealised_pnl.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-provider-authentication-test
        framework.broker_connectivity.provider.authentication
        test_provider_authentication.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-provider-capabilities-test
        framework.broker_connectivity.provider.capabilities
        test_provider_capabilities.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-provider-connection-test
        framework.broker_connectivity.provider.connection
        test_provider_connection.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-provider-contract-test
        framework.broker_connectivity.provider.contract
        test_provider_contract.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-provider-health-test
        framework.broker_connectivity.provider.health
        test_provider_health.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-provider-heartbeat-test
        framework.broker_connectivity.provider.heartbeat
        test_provider_heartbeat.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-provider-latency-test
        framework.broker_connectivity.provider.latency
        test_provider_latency.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-provider-live-mode-test
        framework.broker_connectivity.provider.live.mode
        test_provider_live_mode.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-provider-paper-mode-test
        framework.broker_connectivity.provider.paper.mode
        test_provider_paper_mode.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-provider-reconnect-test
        framework.broker_connectivity.provider.reconnect
        test_provider_reconnect.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-risk-buying-power-test
        framework.broker_connectivity.risk.buying.power
        test_risk_buying_power.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-risk-concentration-test
        framework.broker_connectivity.risk.concentration
        test_risk_concentration.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-risk-daily-loss-test
        framework.broker_connectivity.risk.daily.loss
        test_risk_daily_loss.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-risk-kill-switch-test
        framework.broker_connectivity.risk.kill.switch
        test_risk_kill_switch.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-risk-leverage-test
        framework.broker_connectivity.risk.leverage
        test_risk_leverage.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-risk-order-notional-test
        framework.broker_connectivity.risk.order.notional
        test_risk_order_notional.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-risk-order-quantity-test
        framework.broker_connectivity.risk.order.quantity
        test_risk_order_quantity.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-risk-position-quantity-test
        framework.broker_connectivity.risk.position.quantity
        test_risk_position_quantity.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-risk-pretrade-readiness-test
        framework.broker_connectivity.risk.pretrade.readiness
        test_risk_pretrade_readiness.c
    )
    umicom_add_broker_connectivity_test(
        umicom-broker-connectivity-risk-price-band-test
        framework.broker_connectivity.risk.price.band
        test_risk_price_band.c
    )
endif()

message(STATUS
    "Umicom broker connectivity, paper execution, reconciliation and IBKR boundary enabled")
