# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Checked payment pricing remains in finance; GTK is an optional presentation adapter.
include_guard(GLOBAL)
if(TARGET umicom_ui_gtk4)
    target_sources(umicom_ui_gtk4 PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../adapters/gtk4/payment_quote_gtk4.c")
    target_link_libraries(umicom_ui_gtk4 PUBLIC Umicom::finance)
endif()
if(BUILD_TESTING)
    foreach(kind IN ITEMS rate pricing)
        add_executable(umicom-payment-quote-${kind}-test "${CMAKE_CURRENT_LIST_DIR}/../tests/payment_quotes/test_${kind}.c")
        target_link_libraries(umicom-payment-quote-${kind}-test PRIVATE Umicom::finance)
        umicom_apply_warnings(umicom-payment-quote-${kind}-test)
        umicom_apply_sanitizers(umicom-payment-quote-${kind}-test)
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(umicom-payment-quote-${kind}-test)
        endif()
    endforeach()
    foreach(case IN ITEMS rounding limits invalid money)
        add_test(NAME framework.payment_quotes.rate.${case} COMMAND umicom-payment-quote-rate-test ${case})
        set_tests_properties(framework.payment_quotes.rate.${case} PROPERTIES TIMEOUT 30 LABELS "finance;payments;rounding;regression")
    endforeach()
    foreach(case IN ITEMS arbitrary-fee cap-before-add rule-atomic charge-overflow charge-atomic bad-identities quote cap-tax separate-rounding quote-overflow quote-invalid ownership text csv zero-fee)
        add_test(NAME framework.payment_quotes.pricing.${case} COMMAND umicom-payment-quote-pricing-test ${case})
        set_tests_properties(framework.payment_quotes.pricing.${case} PROPERTIES TIMEOUT 30 LABELS "finance;payments;quote;regression")
    endforeach()
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/PAYMENT_FEE_QUOTES.md"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/framework/docs COMPONENT Framework)
