# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
target_sources(umicom_developer PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/debug_runtime/source_catalog.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/debug_runtime/source_content.c")
if(TARGET umicom_ui_gtk4)
    target_sources(umicom_ui_gtk4 PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../adapters/gtk4/debug_sources.c")
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/DEBUG_SOURCE_BROWSER.html"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/umicom-framework/docs" COMPONENT Framework)
if(NOT BUILD_TESTING)
    return()
endif()
function(umicom_debug_source_test target source owner)
    add_executable("${target}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/debug_sources/${source}")
    target_link_libraries("${target}" PRIVATE "${owner}")
    set_target_properties("${target}" PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings("${target}")
    umicom_apply_sanitizers("${target}")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target("${target}")
    endif()
endfunction()
function(umicom_debug_source_case group target case)
    add_test(NAME framework.debug.sources.${group}.${case} COMMAND "${target}" "${case}" ${ARGN})
    set_tests_properties(framework.debug.sources.${group}.${case} PROPERTIES
        TIMEOUT 60 SKIP_RETURN_CODE 77 LABELS "framework;debug;sources;regression")
endfunction()
umicom_debug_source_test(umicom-debug-source-catalog-test test_catalog.c Umicom::developer)
foreach(case normal empty optional zero max-reference repeated unicode related escaped-keys negative large-reference fraction boolean nul array missing object related-object duplicate-key long-name capacity)
    umicom_debug_source_case(catalog umicom-debug-source-catalog-test "${case}")
endforeach()
umicom_debug_source_test(umicom-debug-source-content-test test_content.c Umicom::developer)
foreach(case normal empty unicode markup missing boolean nul surrogate mime duplicate command refuse capacity)
    umicom_debug_source_case(content umicom-debug-source-content-test "${case}")
endforeach()
if(TARGET umicom-native-attach-adapter-fixture)
    umicom_debug_source_test(umicom-debug-source-protocol-test test_protocol.c Umicom::developer)
    add_dependencies(umicom-debug-source-protocol-test umicom-native-attach-adapter-fixture)
    foreach(case normal refuse timeout malformed unsupported content-refuse content-timeout content-invalid zero large stale session closed reconnect list-exit content-exit restart)
        set(directory "${CMAKE_CURRENT_BINARY_DIR}/debug-sources/${case}")
        file(MAKE_DIRECTORY "${directory}")
        umicom_debug_source_case(protocol umicom-debug-source-protocol-test "${case}"
            "$<TARGET_FILE:umicom-native-attach-adapter-fixture>" "${directory}")
    endforeach()
endif()
if(TARGET umicom_ui_gtk4)
    umicom_debug_source_test(umicom-debug-source-gtk4-test test_gtk4.c Umicom::ui_gtk4)
    foreach(case normal filter pages path-only markup denied read-denied stale hidden retained old-row close-read invalid-host)
        umicom_debug_source_case(gtk4 umicom-debug-source-gtk4-test "${case}")
    endforeach()
endif()
