# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-web-closed-response-test "${CMAKE_CURRENT_LIST_DIR}/../tests/web/test_closed_response.c")
    target_link_libraries(umicom-web-closed-response-test PRIVATE Umicom::web)
    umicom_apply_warnings(umicom-web-closed-response-test)
    umicom_apply_sanitizers(umicom-web-closed-response-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-web-closed-response-test)
    endif()
    foreach(case get head no-content not-modified binary-body tiny-output status header-count header-name header-control header-unterminated length-header transfer-header connection-header body-limit empty-body)
        add_test(NAME framework.web.closed_response.${case} COMMAND umicom-web-closed-response-test ${case})
        set_tests_properties(framework.web.closed_response.${case} PROPERTIES TIMEOUT 30 LABELS "framework;web;http;regression")
    endforeach()
endif()
