# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_type_navigation_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-type-navigation-gtk4-test)
        return()
    endif()
    add_executable(umicom-type-navigation-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_type_navigation_gtk4.c")
    target_link_libraries(umicom-type-navigation-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-type-navigation-gtk4-test)
    umicom_apply_sanitizers(umicom-type-navigation-gtk4-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-type-navigation-gtk4-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-type-navigation-gtk4-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-type-navigation-gtk4-test)
    endif()
    foreach(case type-open type-read type-private type-empty type-selection type-multiline type-cancel type-retained type-unbind type-parent-close type-creation-unbind type-worker-unbind type-worker-parent-close type-input-change type-changed-back type-busy type-invalid-path type-stale type-invalidate-output type-apply type-read-only type-open-result type-invalid-kind type-selection-stale type-open-unbind type-invalid-selection type-remote implementation-open implementation-read implementation-private implementation-empty implementation-selection implementation-multiline implementation-cancel implementation-retained implementation-unbind implementation-parent-close implementation-creation-unbind implementation-worker-unbind implementation-worker-parent-close implementation-input-change implementation-changed-back implementation-busy implementation-invalid-path implementation-stale implementation-invalidate-output implementation-apply implementation-read-only implementation-open-result implementation-invalid-kind implementation-selection-stale implementation-open-unbind implementation-invalid-selection implementation-remote)
        add_test(NAME framework.document.type_navigation.gtk4.${case}
            COMMAND umicom-type-navigation-gtk4-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.document.type_navigation.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77
            LABELS "framework;document;language;type-navigation;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_type_navigation_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_type_navigation_checks)
endif()
