# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-web-request-gate-test "${CMAKE_CURRENT_LIST_DIR}/../tests/web/test_request_gate.c")
    target_link_libraries(umicom-web-request-gate-test PRIVATE Umicom::web)
    umicom_apply_warnings(umicom-web-request-gate-test)
    umicom_apply_sanitizers(umicom-web-request-gate-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-web-request-gate-test)
    endif()
    foreach(case numeric named mixed-case same-origin navigation without-metadata default-port default-port-explicit wrong-host wrong-port missing-host duplicate-host opaque-origin remote-origin other-local-origin secure-origin origin-path duplicate-origin cross-site same-site duplicate-site unknown-site header-count unterminated-name unterminated-value invalid-policy invalid-arguments gate-accept gate-refuse gate-unset gate-failure gate-clear gate-context closed-response)
        add_test(NAME framework.web.request_gate.${case} COMMAND umicom-web-request-gate-test ${case})
        set_tests_properties(framework.web.request_gate.${case} PROPERTIES TIMEOUT 30 LABELS "framework;web;http;regression")
    endforeach()
endif()
