# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-open-source-range-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_open_source_range.c")
    target_link_libraries(umicom-document-open-source-range-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-open-source-range-test)
    umicom_apply_sanitizers(umicom-document-open-source-range-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-open-source-range-test)
    endif()
    foreach(case new existing draft read-only untitled normalised read-error stat-error range-invalid unicode surrogate crlf remote nul history no-active provider-open provider-busy copied-uri arguments)
        add_test(NAME framework.document.open_source_range.${case} COMMAND umicom-document-open-source-range-test ${case})
        set_tests_properties(framework.document.open_source_range.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;source;review;regression")
    endforeach()
endif()
