# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-native-pull-diagnostics-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_native_pull_diagnostics.c")
    target_link_libraries(umicom-native-pull-diagnostics-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-native-pull-diagnostics-test)
    umicom_apply_sanitizers(umicom-native-pull-diagnostics-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-native-pull-diagnostics-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-native-pull-diagnostics-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-native-pull-diagnostics-test)
    endif()
    foreach(case valid unicode empty literal invalid timeout encoding shutdown cancel surrogate outside related choices unchanged related-report unsupported query-error)
        add_test(NAME framework.language_runtime.native_pull_diagnostics.${case} COMMAND umicom-native-pull-diagnostics-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.language_runtime.native_pull_diagnostics.${case} PROPERTIES TIMEOUT 40
            LABELS "framework;language;diagnostics;native;ownership;regression")
    endforeach()
endif()
