# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-directory-scan-test "${CMAKE_CURRENT_LIST_DIR}/../tests/platform/test_directory_scan.c")
    target_link_libraries(umicom-directory-scan-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-directory-scan-test)
    umicom_apply_sanitizers(umicom-directory-scan-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-directory-scan-test)
    endif()
    foreach(case empty exact-limit limit cancellation callback-stop relative dot-parent file-root missing null-visitor zero-limit maximum-limit shallow metadata)
        add_test(NAME framework.platform.directory_scan.${case} COMMAND umicom-directory-scan-test ${case})
        set_tests_properties(framework.platform.directory_scan.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77 LABELS "framework;document;recovery;regression")
    endforeach()
endif()
