# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/learning/filter-captured-choices.html"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/learning COMPONENT Learning)
if(BUILD_TESTING)
    add_executable(umicom-text-projection-test "${CMAKE_CURRENT_LIST_DIR}/../tests/text_projection/test_projection.c")
    target_link_libraries(umicom-text-projection-test PRIVATE Umicom::ui)
    umicom_apply_warnings(umicom-text-projection-test)
    umicom_apply_sanitizers(umicom-text-projection-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-text-projection-test)
    endif()
    foreach(case empty row-limit text-limit owned literal filter case hidden unicode invalid-retains disabled ascending descending restore invalid-output)
        add_test(NAME framework.text_projection.${case} COMMAND umicom-text-projection-test ${case})
        set_tests_properties(framework.text_projection.${case} PROPERTIES TIMEOUT 20 LABELS "framework;ui;projection;regression")
    endforeach()
    if(TARGET Umicom::ui_gtk4)
        add_executable(umicom-filtered-choices-gtk4-test "${CMAKE_CURRENT_LIST_DIR}/../tests/text_projection/test_gtk4.c")
        target_link_libraries(umicom-filtered-choices-gtk4-test PRIVATE Umicom::ui_gtk4)
        umicom_apply_warnings(umicom-filtered-choices-gtk4-test)
        umicom_apply_sanitizers(umicom-filtered-choices-gtk4-test)
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(umicom-filtered-choices-gtk4-test)
        endif()
        foreach(case sort filter hidden replacement clear invalid-utf8 external-model retained reentrant)
            add_test(NAME framework.filtered_choices.gtk4.${case} COMMAND umicom-filtered-choices-gtk4-test ${case})
            set_tests_properties(framework.filtered_choices.gtk4.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77 LABELS "framework;ui;gtk4;projection;ownership;regression")
        endforeach()
    endif()
endif()
