# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Extend the canonical distribution owner. This is not a parallel release engine.
include_guard(GLOBAL)
option(UMICOM_RELEASE_BASELINE_COMPOSITION_TESTS "Check immediate and deferred release evidence wiring" ON)
function(umicom_release_baseline_complete)
    if(NOT TARGET umicom_distribution)
        return()
    endif()
    get_target_property(_imported umicom_distribution IMPORTED)
    if(_imported)
        return()
    endif()
    get_property(_done TARGET umicom_distribution PROPERTY UMICOM_RELEASE_BASELINE_ATTACHED)
    if(_done)
        return()
    endif()
    set(_root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/..")
    set_property(TARGET umicom_distribution PROPERTY UMICOM_RELEASE_BASELINE_ATTACHED TRUE)
    target_sources(umicom_distribution PRIVATE
        "${_root}/src/distribution/runtime/evidence.c"
        "${_root}/src/distribution/runtime/evidence_text.c")
    add_executable(umicom-release-baseline "${_root}/tools/release_baseline/main.c")
    add_executable(umicom-release-baseline-example "${_root}/examples/release_baseline/review_notes_release.c")
    foreach(_target IN ITEMS umicom-release-baseline umicom-release-baseline-example)
        target_link_libraries(${_target} PRIVATE Umicom::distribution)
        set_target_properties(${_target} PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings(${_target})
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers(${_target})
        endif()
    endforeach()
    if(WIN32 AND NOT MSVC)
        target_link_options(umicom-release-baseline PRIVATE -municode)
    endif()
    include(GNUInstallDirs)
    install(TARGETS umicom-release-baseline umicom-release-baseline-example RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT Framework)
    install(FILES "${_root}/include/umicom/distribution/runtime/evidence.h" DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/umicom/distribution/runtime COMPONENT Framework)
    install(DIRECTORY "${_root}/docs/releases/core/" DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/core-release COMPONENT Learning)
    if(BUILD_TESTING)
        # Deferred completion must include definitions, never create subdirectories.
        include("${_root}/tests/release_baseline/CMakeLists.txt")
    endif()
endfunction()
if(TARGET umicom_distribution)
    umicom_release_baseline_complete()
else()
    cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" CALL umicom_release_baseline_complete)
endif()
