# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING AND (WIN32 OR UNIX) AND NOT EMSCRIPTEN)
    add_executable(umicom-web-native-exchange-test "${CMAKE_CURRENT_LIST_DIR}/../tests/web/test_native_connection.c")
    target_link_libraries(umicom-web-native-exchange-test PRIVATE Umicom::web)
    if(WIN32)
        target_link_libraries(umicom-web-native-exchange-test PRIVATE ws2_32)
    endif()
    umicom_apply_warnings(umicom-web-native-exchange-test)
    umicom_apply_sanitizers(umicom-web-native-exchange-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-web-native-exchange-test)
    endif()
    foreach(case get head post malformed partial-close read-timeout cancel-before stop loopback-policy invalid-timeout)
        add_test(NAME framework.web.native_exchange.${case} COMMAND umicom-web-native-exchange-test ${case})
        set_tests_properties(framework.web.native_exchange.${case} PROPERTIES TIMEOUT 30 LABELS "framework;web;http;regression")
    endforeach()
endif()
