#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomWorkspaceValueArchives.cmake
# PURPOSE: Verify portable workspace values in their real owning libraries.
# AUTHOR AND ORGANISATION: Sammy Hegab, Umicom Foundation
# LICENCE: MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/UmicomImplementationFingerprint.cmake")
set(_workspace_archive_root "${CMAKE_CURRENT_LIST_DIR}/..")

# Keep archive definitions in their established owners. This list is also a
# link contract: a stale or incomplete static library must fail a normal build
# rather than be discovered only when a downstream product tries to link it.
set(_workspace_archive_owners
    umicom_ai
    umicom_application
    umicom_compiler
    umicom_context_channel
    umicom_cross_application_panel
    umicom_data
    umicom_delivery
    umicom_designer
    umicom_developer
    umicom_distribution
    umicom_editor
    umicom_finance
    umicom_frontend
    umicom_integration
    umicom_language
    umicom_observability
    umicom_platform
    umicom_plugin
    umicom_repository
    umicom_runtime
    umicom_terminal
    umicom_test_platform
    umicom_toolchain
    umicom_trading
    umicom_trading_ui
    umicom_ui
    umicom_ui_components
    umicom_vcs
    umicom_web
    umicom_workbench_context_event
    umicom_workbench_context_host
    umicom_workbench_context_link
    umicom_workbench_context_source
    umicom_workbench_selection
    umicom_workbench_selection_provider
)
foreach(_owner IN LISTS _workspace_archive_owners)
    if(TARGET "${_owner}")
        target_link_libraries("${_owner}" PUBLIC Umicom::base)
        umicom_attach_implementation_fingerprint("${_owner}" "${_workspace_archive_root}")
    endif()
endforeach()

if(CMAKE_C_COMPILER_ID MATCHES "^(GNU|Clang|AppleClang)$" AND NOT MSVC)
    set(_workspace_archive_underscore OFF)
    if(APPLE OR (WIN32 AND CMAKE_SIZEOF_VOID_P EQUAL 4))
        set(_workspace_archive_underscore ON)
    endif()
    add_custom_target(umicom-workspace-archive-link-checks ALL)
    foreach(_owner IN LISTS _workspace_archive_owners)
        if(NOT TARGET "${_owner}")
            continue()
        endif()
        set(_manifest "${CMAKE_CURRENT_LIST_DIR}/link_contracts/${_owner}_workspace_archives.symbols")
        set(_check "${_owner}-workspace-archive-symbol-check")
        add_custom_target("${_check}"
            COMMAND "${CMAKE_COMMAND}"
                "-DARCHIVE=$<TARGET_FILE:${_owner}>" "-DSYMBOL_FILE=${_manifest}"
                "-DNM_TOOL=${CMAKE_NM}" "-DALLOW_LEADING_UNDERSCORE=${_workspace_archive_underscore}"
                "-DREPORT=${CMAKE_BINARY_DIR}/link-reports/$<CONFIG>/${_owner}-workspace-archives.json"
                -P "${CMAKE_CURRENT_LIST_DIR}/VerifyLibrarySymbols.cmake"
            COMMENT "Verify ${_owner} workspace archive definitions" VERBATIM)
        add_dependencies("${_check}" "${_owner}")
        add_dependencies(umicom-workspace-archive-link-checks "${_check}")
        if(BUILD_TESTING)
            add_test(NAME "framework.value_transfer.archive.${_owner}"
                COMMAND "${CMAKE_COMMAND}"
                    "-DARCHIVE=$<TARGET_FILE:${_owner}>" "-DSYMBOL_FILE=${_manifest}"
                    "-DNM_TOOL=${CMAKE_NM}" "-DALLOW_LEADING_UNDERSCORE=${_workspace_archive_underscore}"
                    "-DREPORT=${CMAKE_CURRENT_BINARY_DIR}/workspace-archive-tests/$<CONFIG>/${_owner}.json"
                    -P "${CMAKE_CURRENT_LIST_DIR}/VerifyLibrarySymbols.cmake")
            set_tests_properties("framework.value_transfer.archive.${_owner}" PROPERTIES
                TIMEOUT 90 LABELS "framework;value-archive;link;regression")
        endif()
    endforeach()
endif()

if(BUILD_TESTING)
    if(TARGET Umicom::application)
    add_executable(umicom-session-transfer-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/test_session_transfer.c")
    target_link_libraries(umicom-session-transfer-test PRIVATE Umicom::application)
    umicom_apply_warnings(umicom-session-transfer-test)
    umicom_apply_sanitizers(umicom-session-transfer-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-session-transfer-test)
    endif()
    foreach(case lifetime refused archive exhausted locked)
        add_test(NAME "framework.value_transfer.session.${case}" COMMAND umicom-session-transfer-test "${case}")
        set_tests_properties("framework.value_transfer.session.${case}" PROPERTIES
            TIMEOUT 60 LABELS "framework;value-archive;session;regression")
    endforeach()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-account-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_account.c")
    target_link_libraries(umicom-transfer-context-channel-account-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-account-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-account-test)
    add_test(NAME framework.value_transfer.context_channel.account COMMAND umicom-transfer-context-channel-account-test)
    set_tests_properties(framework.value_transfer.context_channel.account PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-account-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-audit-record-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_audit_record.c")
    target_link_libraries(umicom-transfer-context-channel-audit-record-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-audit-record-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-audit-record-test)
    add_test(NAME framework.value_transfer.context_channel.audit_record COMMAND umicom-transfer-context-channel-audit-record-test)
    set_tests_properties(framework.value_transfer.context_channel.audit_record PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-audit-record-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-binding-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_binding.c")
    target_link_libraries(umicom-transfer-context-channel-binding-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-binding-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-binding-test)
    add_test(NAME framework.value_transfer.context_channel.binding COMMAND umicom-transfer-context-channel-binding-test)
    set_tests_properties(framework.value_transfer.context_channel.binding PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-binding-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-bookmark-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_bookmark.c")
    target_link_libraries(umicom-transfer-context-channel-bookmark-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-bookmark-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-bookmark-test)
    add_test(NAME framework.value_transfer.context_channel.bookmark COMMAND umicom-transfer-context-channel-bookmark-test)
    set_tests_properties(framework.value_transfer.context_channel.bookmark PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-bookmark-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-capability-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_capability.c")
    target_link_libraries(umicom-transfer-context-channel-capability-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-capability-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-capability-test)
    add_test(NAME framework.value_transfer.context_channel.capability COMMAND umicom-transfer-context-channel-capability-test)
    set_tests_properties(framework.value_transfer.context_channel.capability PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-capability-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-channel-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_channel.c")
    target_link_libraries(umicom-transfer-context-channel-channel-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-channel-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-channel-test)
    add_test(NAME framework.value_transfer.context_channel.channel COMMAND umicom-transfer-context-channel-channel-test)
    set_tests_properties(framework.value_transfer.context_channel.channel PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-channel-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-delivery-receipt-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_delivery_receipt.c")
    target_link_libraries(umicom-transfer-context-channel-delivery-receipt-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-delivery-receipt-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-delivery-receipt-test)
    add_test(NAME framework.value_transfer.context_channel.delivery_receipt COMMAND umicom-transfer-context-channel-delivery-receipt-test)
    set_tests_properties(framework.value_transfer.context_channel.delivery_receipt PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-delivery-receipt-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-diagnostic-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_diagnostic.c")
    target_link_libraries(umicom-transfer-context-channel-diagnostic-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-diagnostic-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-diagnostic-test)
    add_test(NAME framework.value_transfer.context_channel.diagnostic COMMAND umicom-transfer-context-channel-diagnostic-test)
    set_tests_properties(framework.value_transfer.context_channel.diagnostic PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-diagnostic-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-filter-rule-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_filter_rule.c")
    target_link_libraries(umicom-transfer-context-channel-filter-rule-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-filter-rule-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-filter-rule-test)
    add_test(NAME framework.value_transfer.context_channel.filter_rule COMMAND umicom-transfer-context-channel-filter-rule-test)
    set_tests_properties(framework.value_transfer.context_channel.filter_rule PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-filter-rule-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-group-member-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_group_member.c")
    target_link_libraries(umicom-transfer-context-channel-group-member-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-group-member-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-group-member-test)
    add_test(NAME framework.value_transfer.context_channel.group_member COMMAND umicom-transfer-context-channel-group-member-test)
    set_tests_properties(framework.value_transfer.context_channel.group_member PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-group-member-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-history-entry-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_history_entry.c")
    target_link_libraries(umicom-transfer-context-channel-history-entry-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-history-entry-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-history-entry-test)
    add_test(NAME framework.value_transfer.context_channel.history_entry COMMAND umicom-transfer-context-channel-history-entry-test)
    set_tests_properties(framework.value_transfer.context_channel.history_entry PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-history-entry-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-instrument-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_instrument.c")
    target_link_libraries(umicom-transfer-context-channel-instrument-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-instrument-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-instrument-test)
    add_test(NAME framework.value_transfer.context_channel.instrument COMMAND umicom-transfer-context-channel-instrument-test)
    set_tests_properties(framework.value_transfer.context_channel.instrument PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-instrument-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-link-group-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_link_group.c")
    target_link_libraries(umicom-transfer-context-channel-link-group-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-link-group-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-link-group-test)
    add_test(NAME framework.value_transfer.context_channel.link_group COMMAND umicom-transfer-context-channel-link-group-test)
    set_tests_properties(framework.value_transfer.context_channel.link_group PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-link-group-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-media-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_media.c")
    target_link_libraries(umicom-transfer-context-channel-media-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-media-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-media-test)
    add_test(NAME framework.value_transfer.context_channel.media COMMAND umicom-transfer-context-channel-media-test)
    set_tests_properties(framework.value_transfer.context_channel.media PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-media-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-panel-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_panel.c")
    target_link_libraries(umicom-transfer-context-channel-panel-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-panel-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-panel-test)
    add_test(NAME framework.value_transfer.context_channel.panel COMMAND umicom-transfer-context-channel-panel-test)
    set_tests_properties(framework.value_transfer.context_channel.panel PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-panel-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-panel-instance-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_panel_instance.c")
    target_link_libraries(umicom-transfer-context-channel-panel-instance-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-panel-instance-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-panel-instance-test)
    add_test(NAME framework.value_transfer.context_channel.panel_instance COMMAND umicom-transfer-context-channel-panel-instance-test)
    set_tests_properties(framework.value_transfer.context_channel.panel_instance PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-panel-instance-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-permission-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_permission.c")
    target_link_libraries(umicom-transfer-context-channel-permission-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-permission-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-permission-test)
    add_test(NAME framework.value_transfer.context_channel.permission COMMAND umicom-transfer-context-channel-permission-test)
    set_tests_properties(framework.value_transfer.context_channel.permission PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-permission-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-policy-rule-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_policy_rule.c")
    target_link_libraries(umicom-transfer-context-channel-policy-rule-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-policy-rule-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-policy-rule-test)
    add_test(NAME framework.value_transfer.context_channel.policy_rule COMMAND umicom-transfer-context-channel-policy-rule-test)
    set_tests_properties(framework.value_transfer.context_channel.policy_rule PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-policy-rule-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-project-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_project.c")
    target_link_libraries(umicom-transfer-context-channel-project-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-project-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-project-test)
    add_test(NAME framework.value_transfer.context_channel.project COMMAND umicom-transfer-context-channel-project-test)
    set_tests_properties(framework.value_transfer.context_channel.project PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-project-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-provider-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_provider.c")
    target_link_libraries(umicom-transfer-context-channel-provider-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-provider-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-provider-test)
    add_test(NAME framework.value_transfer.context_channel.provider COMMAND umicom-transfer-context-channel-provider-test)
    set_tests_properties(framework.value_transfer.context_channel.provider PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-provider-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-provider-state-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_provider_state.c")
    target_link_libraries(umicom-transfer-context-channel-provider-state-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-provider-state-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-provider-state-test)
    add_test(NAME framework.value_transfer.context_channel.provider_state COMMAND umicom-transfer-context-channel-provider-state-test)
    set_tests_properties(framework.value_transfer.context_channel.provider_state PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-provider-state-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-recent-context-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_recent_context.c")
    target_link_libraries(umicom-transfer-context-channel-recent-context-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-recent-context-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-recent-context-test)
    add_test(NAME framework.value_transfer.context_channel.recent_context COMMAND umicom-transfer-context-channel-recent-context-test)
    set_tests_properties(framework.value_transfer.context_channel.recent_context PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-recent-context-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-route-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_route.c")
    target_link_libraries(umicom-transfer-context-channel-route-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-route-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-route-test)
    add_test(NAME framework.value_transfer.context_channel.route COMMAND umicom-transfer-context-channel-route-test)
    set_tests_properties(framework.value_transfer.context_channel.route PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-route-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-route-trace-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_route_trace.c")
    target_link_libraries(umicom-transfer-context-channel-route-trace-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-route-trace-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-route-trace-test)
    add_test(NAME framework.value_transfer.context_channel.route_trace COMMAND umicom-transfer-context-channel-route-trace-test)
    set_tests_properties(framework.value_transfer.context_channel.route_trace PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-route-trace-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-schema-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_schema.c")
    target_link_libraries(umicom-transfer-context-channel-schema-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-schema-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-schema-test)
    add_test(NAME framework.value_transfer.context_channel.schema COMMAND umicom-transfer-context-channel-schema-test)
    set_tests_properties(framework.value_transfer.context_channel.schema PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-schema-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-selection-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_selection.c")
    target_link_libraries(umicom-transfer-context-channel-selection-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-selection-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-selection-test)
    add_test(NAME framework.value_transfer.context_channel.selection COMMAND umicom-transfer-context-channel-selection-test)
    set_tests_properties(framework.value_transfer.context_channel.selection PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-selection-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-session-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_session.c")
    target_link_libraries(umicom-transfer-context-channel-session-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-session-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-session-test)
    add_test(NAME framework.value_transfer.context_channel.session COMMAND umicom-transfer-context-channel-session-test)
    set_tests_properties(framework.value_transfer.context_channel.session PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-session-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-source-location-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_source_location.c")
    target_link_libraries(umicom-transfer-context-channel-source-location-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-source-location-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-source-location-test)
    add_test(NAME framework.value_transfer.context_channel.source_location COMMAND umicom-transfer-context-channel-source-location-test)
    set_tests_properties(framework.value_transfer.context_channel.source_location PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-source-location-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-subscription-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_subscription.c")
    target_link_libraries(umicom-transfer-context-channel-subscription-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-subscription-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-subscription-test)
    add_test(NAME framework.value_transfer.context_channel.subscription COMMAND umicom-transfer-context-channel-subscription-test)
    set_tests_properties(framework.value_transfer.context_channel.subscription PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-subscription-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-trade-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_trade.c")
    target_link_libraries(umicom-transfer-context-channel-trade-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-trade-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-trade-test)
    add_test(NAME framework.value_transfer.context_channel.trade COMMAND umicom-transfer-context-channel-trade-test)
    set_tests_properties(framework.value_transfer.context_channel.trade PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-trade-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-transformer-rule-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_transformer_rule.c")
    target_link_libraries(umicom-transfer-context-channel-transformer-rule-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-transformer-rule-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-transformer-rule-test)
    add_test(NAME framework.value_transfer.context_channel.transformer_rule COMMAND umicom-transfer-context-channel-transformer-rule-test)
    set_tests_properties(framework.value_transfer.context_channel.transformer_rule PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-transformer-rule-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-value-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_value.c")
    target_link_libraries(umicom-transfer-context-channel-value-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-value-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-value-test)
    add_test(NAME framework.value_transfer.context_channel.value COMMAND umicom-transfer-context-channel-value-test)
    set_tests_properties(framework.value_transfer.context_channel.value PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-value-test)
    endif()
    endif()
    if(TARGET umicom_context_channel)
    add_executable(umicom-transfer-context-channel-workspace-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/context_channel_workspace.c")
    target_link_libraries(umicom-transfer-context-channel-workspace-test PRIVATE umicom_context_channel)
    umicom_apply_warnings(umicom-transfer-context-channel-workspace-test)
    umicom_apply_sanitizers(umicom-transfer-context-channel-workspace-test)
    add_test(NAME framework.value_transfer.context_channel.workspace COMMAND umicom-transfer-context-channel-workspace-test)
    set_tests_properties(framework.value_transfer.context_channel.workspace PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-context-channel-workspace-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-activation-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_activation.c")
    target_link_libraries(umicom-transfer-cross-application-panel-activation-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-activation-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-activation-test)
    add_test(NAME framework.value_transfer.cross_application_panel.activation COMMAND umicom-transfer-cross-application-panel-activation-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.activation PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-activation-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-bookmark-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_bookmark.c")
    target_link_libraries(umicom-transfer-cross-application-panel-bookmark-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-bookmark-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-bookmark-test)
    add_test(NAME framework.value_transfer.cross_application_panel.bookmark COMMAND umicom-transfer-cross-application-panel-bookmark-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.bookmark PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-bookmark-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-capability-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_capability.c")
    target_link_libraries(umicom-transfer-cross-application-panel-capability-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-capability-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-capability-test)
    add_test(NAME framework.value_transfer.cross_application_panel.capability COMMAND umicom-transfer-cross-application-panel-capability-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.capability PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-capability-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-collection-entry-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_collection_entry.c")
    target_link_libraries(umicom-transfer-cross-application-panel-collection-entry-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-collection-entry-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-collection-entry-test)
    add_test(NAME framework.value_transfer.cross_application_panel.collection_entry COMMAND umicom-transfer-cross-application-panel-collection-entry-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.collection_entry PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-collection-entry-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-command-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_command.c")
    target_link_libraries(umicom-transfer-cross-application-panel-command-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-command-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-command-test)
    add_test(NAME framework.value_transfer.cross_application_panel.command COMMAND umicom-transfer-cross-application-panel-command-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.command PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-command-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-context-binding-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_context_binding.c")
    target_link_libraries(umicom-transfer-cross-application-panel-context-binding-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-context-binding-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-context-binding-test)
    add_test(NAME framework.value_transfer.cross_application_panel.context_binding COMMAND umicom-transfer-cross-application-panel-context-binding-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.context_binding PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-context-binding-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-contribution-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_contribution.c")
    target_link_libraries(umicom-transfer-cross-application-panel-contribution-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-contribution-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-contribution-test)
    add_test(NAME framework.value_transfer.cross_application_panel.contribution COMMAND umicom-transfer-cross-application-panel-contribution-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.contribution PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-contribution-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-definition-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_definition.c")
    target_link_libraries(umicom-transfer-cross-application-panel-definition-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-definition-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-definition-test)
    add_test(NAME framework.value_transfer.cross_application_panel.definition COMMAND umicom-transfer-cross-application-panel-definition-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.definition PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-definition-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-diagnostic-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_diagnostic.c")
    target_link_libraries(umicom-transfer-cross-application-panel-diagnostic-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-diagnostic-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-diagnostic-test)
    add_test(NAME framework.value_transfer.cross_application_panel.diagnostic COMMAND umicom-transfer-cross-application-panel-diagnostic-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.diagnostic PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-diagnostic-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-event-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_event.c")
    target_link_libraries(umicom-transfer-cross-application-panel-event-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-event-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-event-test)
    add_test(NAME framework.value_transfer.cross_application_panel.event COMMAND umicom-transfer-cross-application-panel-event-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.event PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-event-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-factory-record-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_factory_record.c")
    target_link_libraries(umicom-transfer-cross-application-panel-factory-record-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-factory-record-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-factory-record-test)
    add_test(NAME framework.value_transfer.cross_application_panel.factory_record COMMAND umicom-transfer-cross-application-panel-factory-record-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.factory_record PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-factory-record-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-focus-state-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_focus_state.c")
    target_link_libraries(umicom-transfer-cross-application-panel-focus-state-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-focus-state-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-focus-state-test)
    add_test(NAME framework.value_transfer.cross_application_panel.focus_state COMMAND umicom-transfer-cross-application-panel-focus-state-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.focus_state PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-focus-state-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-host-slot-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_host_slot.c")
    target_link_libraries(umicom-transfer-cross-application-panel-host-slot-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-host-slot-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-host-slot-test)
    add_test(NAME framework.value_transfer.cross_application_panel.host_slot COMMAND umicom-transfer-cross-application-panel-host-slot-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.host_slot PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-host-slot-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-instance-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_instance.c")
    target_link_libraries(umicom-transfer-cross-application-panel-instance-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-instance-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-instance-test)
    add_test(NAME framework.value_transfer.cross_application_panel.instance COMMAND umicom-transfer-cross-application-panel-instance-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.instance PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-instance-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-layout-binding-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_layout_binding.c")
    target_link_libraries(umicom-transfer-cross-application-panel-layout-binding-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-layout-binding-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-layout-binding-test)
    add_test(NAME framework.value_transfer.cross_application_panel.layout_binding COMMAND umicom-transfer-cross-application-panel-layout-binding-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.layout_binding PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-layout-binding-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-metric-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_metric.c")
    target_link_libraries(umicom-transfer-cross-application-panel-metric-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-metric-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-metric-test)
    add_test(NAME framework.value_transfer.cross_application_panel.metric COMMAND umicom-transfer-cross-application-panel-metric-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.metric PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-metric-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-permission-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_permission.c")
    target_link_libraries(umicom-transfer-cross-application-panel-permission-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-permission-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-permission-test)
    add_test(NAME framework.value_transfer.cross_application_panel.permission COMMAND umicom-transfer-cross-application-panel-permission-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.permission PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-permission-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-session-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_session.c")
    target_link_libraries(umicom-transfer-cross-application-panel-session-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-session-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-session-test)
    add_test(NAME framework.value_transfer.cross_application_panel.session COMMAND umicom-transfer-cross-application-panel-session-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.session PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-session-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-view-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_view.c")
    target_link_libraries(umicom-transfer-cross-application-panel-view-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-view-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-view-test)
    add_test(NAME framework.value_transfer.cross_application_panel.view COMMAND umicom-transfer-cross-application-panel-view-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.view PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-view-test)
    endif()
    endif()
    if(TARGET umicom_cross_application_panel)
    add_executable(umicom-transfer-cross-application-panel-workspace-binding-test "${CMAKE_CURRENT_LIST_DIR}/../tests/value_archive/context/cross_application_panel_workspace_binding.c")
    target_link_libraries(umicom-transfer-cross-application-panel-workspace-binding-test PRIVATE umicom_cross_application_panel)
    umicom_apply_warnings(umicom-transfer-cross-application-panel-workspace-binding-test)
    umicom_apply_sanitizers(umicom-transfer-cross-application-panel-workspace-binding-test)
    add_test(NAME framework.value_transfer.cross_application_panel.workspace_binding COMMAND umicom-transfer-cross-application-panel-workspace-binding-test)
    set_tests_properties(framework.value_transfer.cross_application_panel.workspace_binding PROPERTIES TIMEOUT 60 LABELS "framework;value-archive;context;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-transfer-cross-application-panel-workspace-binding-test)
    endif()
    endif()
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/WORKSPACE_STATE_TRANSFER.html"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/umicom-framework/docs" COMPONENT Framework)
