# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-png-image-test "${CMAKE_CURRENT_LIST_DIR}/../tests/media/test_png_image.c")
    target_link_libraries(umicom-png-image-test PRIVATE Umicom::png_image)
    set_target_properties(umicom-png-image-test PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings(umicom-png-image-test)
    umicom_apply_sanitizers(umicom-png-image-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-png-image-test)
    endif()
    foreach(case rgba rgb gray gray-alpha palette gray-bit gray-wide transparent interlaced animated wide pixels zero depth broken-deflate signature crc truncated trailing missing-end unknown-critical many-chunks owned cancelled live-output null-output null-input input-limit unavailable row-import row-order row-short row-long row-index row-null-input row-null-surface)
        add_test(NAME framework.media.png.${case} COMMAND umicom-png-image-test ${case})
        set_tests_properties(framework.media.png.${case} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;media;png;regression")
    endforeach()
endif()
