# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# These isolated producers exercise real child-process lifetime without user commands.
include_guard(GLOBAL)
include(GNUInstallDirs)
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/TERMINAL_COMMAND_WORKFLOW.html"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/umicom/docs" COMPONENT Framework)

if(NOT BUILD_TESTING)
    return()
endif()
function(umicom_terminal_execution_target target source)
    add_executable("${target}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/terminal_execution/${source}")
    target_link_libraries("${target}" PRIVATE Umicom::terminal_ui)
    set_target_properties("${target}" PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings("${target}")
    umicom_apply_sanitizers("${target}")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target("${target}")
    endif()
endfunction()
umicom_terminal_execution_target(umicom-terminal-output-producer producer.c)
umicom_terminal_execution_target(umicom-terminal-job-session-test test_session.c)
umicom_terminal_execution_target(umicom-terminal-job-controller-test test_controller.c)
umicom_terminal_execution_target(umicom-terminal-job-rejection-test test_rejection.c)
foreach(target umicom-terminal-job-session-test umicom-terminal-job-controller-test umicom-terminal-job-rejection-test)
    add_dependencies("${target}" umicom-terminal-output-producer)
endforeach()
function(umicom_terminal_execution_case group target case)
    add_test(NAME framework.terminal_execution.${group}.${case}
        COMMAND "${target}" "${case}" "$<TARGET_FILE:umicom-terminal-output-producer>")
    set_tests_properties(framework.terminal_execution.${group}.${case} PROPERTIES
        TIMEOUT 30 LABELS "framework;terminal;process;ownership;regression")
endfunction()
foreach(case success stop timeout guards destroy large exit reuse)
    umicom_terminal_execution_case(session umicom-terminal-job-session-test "${case}")
endforeach()
foreach(case history switch destroy disarm)
    umicom_terminal_execution_case(controller umicom-terminal-job-controller-test "${case}")
endforeach()
foreach(case empty count pointer closed)
    umicom_terminal_execution_case(rejection umicom-terminal-job-rejection-test "${case}")
endforeach()

umicom_terminal_execution_target(umicom-terminal-directory-test test_directory.c)
add_dependencies(umicom-terminal-directory-test umicom-terminal-output-producer)
foreach(case relative missing capacity alias closed running independent)
    umicom_terminal_execution_case(directory umicom-terminal-directory-test "${case}")
endforeach()
