# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_code_action_review_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-code-action-review-gtk4-test)
        return()
    endif()
    add_executable(umicom-code-action-review-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_code_action_review_gtk4.c")
    target_link_libraries(umicom-code-action-review-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-code-action-review-gtk4-test)
    umicom_apply_sanitizers(umicom-code-action-review-gtk4-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-code-action-review-gtk4-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-code-action-review-gtk4-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-code-action-review-gtk4-test)
    endif()
    foreach(case context-valid context-empty context-invalid context-retire context-pending-change open apply undo no-preview no-approval stale cancel retained unbind parent-close creation-unbind worker-unbind input-change changed-back private busy invalid-path completion-unbind annotation choice-change multiline external resource empty choices choice-stale disabled command edit-command deferred literal read-only publication-invalidate approval-invalidate)
        add_test(NAME framework.document.code_action_review.gtk4.${case}
            COMMAND umicom-code-action-review-gtk4-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.document.code_action_review.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77
            LABELS "framework;document;language;code-actions;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_code_action_review_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_code_action_review_checks)
endif()
