# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING AND TARGET umicom_ui_gtk4)
    add_executable(umicom-document-replacement-set-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_replacement_set_gtk4.c")
    target_link_libraries(umicom-document-replacement-set-native-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-document-replacement-set-native-test)
    umicom_apply_sanitizers(umicom-document-replacement-set-native-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-replacement-set-native-test)
    endif()
    foreach(case apply no-review partial-review no-approval review-order stale-first stale-last undo busy cancel destroy unbind parent-close creation-unbind complete-unbind owned-inputs unchanged retained-approval)
        add_test(NAME framework.document.replacement_set.gtk4.${case} COMMAND umicom-document-replacement-set-native-test ${case})
        set_tests_properties(framework.document.replacement_set.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77 LABELS "framework;document;replacement;gtk4;regression")
    endforeach()
endif()
