# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-symbol-query-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_symbol_query.c")
    target_link_libraries(umicom-symbol-query-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-symbol-query-test)
    umicom_apply_sanitizers(umicom-symbol-query-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-symbol-query-test)
    endif()
    foreach(case valid object flat hierarchy empty unicode self-outside self-surrogate external missing disabled encoding sync fragmented notification error invalid-result mixed shutdown-error close-error timeout cancel-before cancel-during invalid-source state native-invalid read-error write-error wrong-id arguments)
        add_test(NAME framework.language_runtime.symbol_query.${case} COMMAND umicom-symbol-query-test ${case})
        set_tests_properties(framework.language_runtime.symbol_query.${case} PROPERTIES TIMEOUT 30
            LABELS "framework;language;navigation;ownership;regression")
    endforeach()
endif()
