# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# One shared native media workflow; application adapters contain presentation.
include_guard(GLOBAL)
include(GNUInstallDirs)
if(NOT TARGET Umicom::setup_centre)
    include("${CMAKE_CURRENT_LIST_DIR}/UmicomSetupCentre.cmake")
endif()
option(UMICOM_BOOT_MEDIA_ENABLE_DEVICE_WRITES
    "Enable unqualified physical removable-USB writer; destructive, explicit confirmation required" OFF)
set(_umi_boot_media_root "${CMAKE_CURRENT_LIST_DIR}/..")
add_library(umicom_boot_media STATIC
    "${_umi_boot_media_root}/src/boot_media/image.c"
    "${_umi_boot_media_root}/src/boot_media/io.c"
    "${_umi_boot_media_root}/src/boot_media/transfer.c"
    "${_umi_boot_media_root}/src/boot_media/cli.c")
if(WIN32)
    target_sources(umicom_boot_media PRIVATE "${_umi_boot_media_root}/src/boot_media/device_windows.c")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    target_sources(umicom_boot_media PRIVATE "${_umi_boot_media_root}/src/boot_media/device_linux.c")
else()
    target_sources(umicom_boot_media PRIVATE "${_umi_boot_media_root}/src/boot_media/device_unsupported.c")
endif()
add_library(Umicom::boot_media ALIAS umicom_boot_media)
set_target_properties(umicom_boot_media PROPERTIES EXPORT_NAME boot_media C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
target_include_directories(umicom_boot_media PUBLIC $<BUILD_INTERFACE:${_umi_boot_media_root}/include> $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
target_link_libraries(umicom_boot_media PUBLIC Umicom::setup_centre Umicom::native_launcher)
if(UMICOM_BOOT_MEDIA_ENABLE_DEVICE_WRITES)
    target_compile_definitions(umicom_boot_media PRIVATE UMICOM_BOOT_MEDIA_ENABLE_DEVICE_WRITES=1)
endif()
add_executable(umicom-media "${_umi_boot_media_root}/examples/boot_media/main.c")
target_link_libraries(umicom-media PRIVATE Umicom::boot_media)
add_executable(umicom-media-review-example "${_umi_boot_media_root}/examples/boot_media/review_lesson.c")
target_link_libraries(umicom-media-review-example PRIVATE Umicom::boot_media)
add_executable(umicom-media-image-example "${_umi_boot_media_root}/examples/boot_media/practice_image.c")
target_link_libraries(umicom-media-image-example PRIVATE Umicom::boot_media)
if(MINGW)
    target_link_options(umicom-media PRIVATE -municode -static-libgcc)
    target_link_options(umicom-media-image-example PRIVATE -municode -static-libgcc)
endif()
foreach(_target IN ITEMS umicom_boot_media umicom-media umicom-media-review-example umicom-media-image-example)
    set_target_properties(${_target} PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    if(COMMAND umicom_apply_warnings)
        umicom_apply_warnings(${_target})
    endif()
    if(COMMAND umicom_apply_sanitizers)
        umicom_apply_sanitizers(${_target})
    endif()
endforeach()
if(WIN32)
    enable_language(RC)
    add_executable(umicom-media-centre WIN32
        "${_umi_boot_media_root}/examples/boot_media/windows_main.c"
        "${_umi_boot_media_root}/adapters/win32/boot_media.c"
        "${_umi_boot_media_root}/examples/boot_media/resources/media.rc")
    target_include_directories(umicom-media-centre PRIVATE
        "${_umi_boot_media_root}/examples/boot_media/resources"
        "${_umi_boot_media_root}/examples/setup_centre/resources")
    target_link_libraries(umicom-media-centre PRIVATE Umicom::boot_media user32 gdi32 comctl32 comdlg32)
    target_compile_definitions(umicom-media-centre PRIVATE UNICODE _UNICODE)
    set_target_properties(umicom-media-centre PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    if(MINGW)
        target_link_options(umicom-media-centre PRIVATE -municode -static-libgcc)
    endif()
    if(COMMAND umicom_apply_warnings)
        umicom_apply_warnings(umicom-media-centre)
    endif()
    if(COMMAND umicom_apply_sanitizers)
        umicom_apply_sanitizers(umicom-media-centre)
    endif()
    if(COMMAND umicom_prepare_windows_application)
        umicom_prepare_windows_application(TARGET umicom-media-centre PRODUCT_NAME "Umicom Boot Media Centre" RESOURCE_ROOT "${_umi_boot_media_root}/resources" GUI)
    endif()
    install(TARGETS umicom-media-centre RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT Framework)
endif()
install(TARGETS umicom_boot_media EXPORT UmicomFrameworkTargets ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT Framework)
install(TARGETS umicom-media RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT Framework)
install(DIRECTORY "${_umi_boot_media_root}/include/umicom/boot_media" DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/umicom COMPONENT Framework)
install(FILES "${_umi_boot_media_root}/docs/learning/prepare-and-check-boot-media.html" DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/learning COMPONENT Learning)
if(BUILD_TESTING)
    add_subdirectory("${_umi_boot_media_root}/tests/boot_media" "${CMAKE_CURRENT_BINARY_DIR}/boot-media-tests")
endif()
unset(_umi_boot_media_root)
