# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# One portable catalogue serves Studio and future development frontends.
include_guard(GLOBAL)
target_sources(umicom_developer PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/developer_project/installed_files.c")
target_link_libraries(umicom_developer PRIVATE Umicom::document)
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/learning/review-installed-files.html"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/learning COMPONENT Learning)
if(BUILD_TESTING)
    add_executable(umicom-installed-files-test "${CMAKE_CURRENT_LIST_DIR}/../tests/installed_files/test_catalogue.c")
    target_link_libraries(umicom-installed-files-test PRIVATE Umicom::developer)
    umicom_apply_warnings(umicom-installed-files-test)
    umicom_apply_sanitizers(umicom-installed-files-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-installed-files-test)
    endif()
    foreach(case blank cancel-reset cancelled changed-build changed-file changed-manifest changed-root control cr-only crlf data-selection directory-entry duplicate embedded-nul empty empty-build empty-install entry-limit index invalid-utf8 missing-entry missing-manifest no-newline outside permissions prefix-itself prefix-sibling relative-path relative-source removed-file select-cancel traversal valid)
        add_test(NAME framework.installed_files.catalogue.${case} COMMAND umicom-installed-files-test ${case})
        set_tests_properties(framework.installed_files.catalogue.${case} PROPERTIES TIMEOUT 30 LABELS "framework;developer;install;regression")
    endforeach()
endif()
function(umicom_attach_installed_files_native_checks)
    if(NOT BUILD_TESTING OR NOT TARGET umicom_ui_gtk4 OR TARGET umicom-installed-files-gtk4-test)
        return()
    endif()
    add_executable(umicom-installed-files-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/installed_files/test_gtk4.c")
    target_link_libraries(umicom-installed-files-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-installed-files-gtk4-test)
    umicom_apply_sanitizers(umicom-installed-files-gtk4-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-installed-files-gtk4-test)
    endif()
    foreach(case apply changed-input data-selection model-destroy no-auto-read pending-destroy pending-hide read reentrant-entry reentrant-model removed-file selection-edit program)
        add_test(NAME framework.installed_files.gtk4.${case} COMMAND umicom-installed-files-gtk4-test ${case})
        set_tests_properties(framework.installed_files.gtk4.${case} PROPERTIES TIMEOUT 40 SKIP_RETURN_CODE 77 LABELS "framework;developer;install;gtk4;ownership;regression")
    endforeach()
    # Exercise source identity when filtering changes visible row positions,
    # including while a selected file is being checked asynchronously.
    foreach(case choices-sort choices-data choices-program choices-reentrant choices-external choices-pending-sort choices-pending-hidden)
        add_test(NAME framework.installed_files.gtk4.${case} COMMAND umicom-installed-files-gtk4-test ${case})
        set_tests_properties(framework.installed_files.gtk4.${case} PROPERTIES TIMEOUT 40 SKIP_RETURN_CODE 77 LABELS "framework;developer;install;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_installed_files_native_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_installed_files_native_checks)
endif()
