# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Keep source maintenance regression coverage beside its shared transaction owner.
include_guard(GLOBAL)
set(_umi_source_library_root "${CMAKE_CURRENT_LIST_DIR}/..")
if(BUILD_TESTING)
    add_executable(umicom-ai-source-change-test "${_umi_source_library_root}/tests/ai_workspace/test_source_change.c")
    target_include_directories(umicom-ai-source-change-test PRIVATE "${_umi_source_library_root}/src/ai_workspace")
    target_link_libraries(umicom-ai-source-change-test PRIVATE Umicom::ai_workspace)
    umicom_ai_workspace_configure_target(umicom-ai-source-change-test)
    foreach(case preview replace remove owned multiple grow collision missing duplicate empty-selection invalid-text arguments approval repeat stale external-writer other-owner outer-transaction noop noop-external new-collection collection-name full-capacity insufficient-capacity overflow busy recovery embedding noop-embedding frozen-replace frozen-remove reload sqlite-reload sqlite-rollback)
        add_test(NAME framework.ai_workspace.source_change.${case} COMMAND umicom-ai-source-change-test ${case})
        set_tests_properties(framework.ai_workspace.source_change.${case} PROPERTIES TIMEOUT 60 SKIP_RETURN_CODE 77 LABELS "framework;rag;source-library;transaction;regression")
    endforeach()
    if(TARGET Umicom::ai_workspace_gtk4)
        add_executable(umicom-ai-source-library-native-test "${_umi_source_library_root}/tests/ai_workspace/test_source_library_gtk4.c")
        target_include_directories(umicom-ai-source-library-native-test PRIVATE "${_umi_source_library_root}/src/ai_workspace")
        target_link_libraries(umicom-ai-source-library-native-test PRIVATE Umicom::ai_workspace_gtk4)
        umicom_ai_workspace_configure_target(umicom-ai-source-library-native-test)
        foreach(case replace remove copy no-preview no-approval empty selection-change mode-change text-change destination-change stale external-writer stale-list refresh collision retained preview-edit preview-destroy apply-destroy private busy)
            add_test(NAME framework.ai_workspace.source_library.gtk4.${case} COMMAND umicom-ai-source-library-native-test ${case})
            set_tests_properties(framework.ai_workspace.source_library.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77 LABELS "framework;rag;source-library;gtk4;lifetime;regression")
        endforeach()
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(umicom-ai-source-library-native-test)
        endif()
    endif()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-ai-source-change-test)
    endif()
endif()
if(UMICOM_BUILD_LEARNING_EXAMPLES)
    add_executable(umicom-ai-source-change-example "${_umi_source_library_root}/examples/ai_source_change_main.c")
    target_link_libraries(umicom-ai-source-change-example PRIVATE Umicom::ai_workspace)
    umicom_ai_workspace_configure_target(umicom-ai-source-change-example)
endif()
install(FILES "${_umi_source_library_root}/docs/learning/review-source-library-changes.html"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/umicom/framework/docs/learning" COMPONENT Framework)
unset(_umi_source_library_root)
