# Use the existing chart target so all consumers share one appearance codec.
target_sources(umicom_chart PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/chart/drawing_appearance.c")
if(BUILD_TESTING)
    function(umicom_appearance_cases group)
        set(target "umicom-drawing-appearance-${group}-test")
        add_executable(${target} "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/chart_appearance/test_${group}.c")
        target_link_libraries(${target} PRIVATE Umicom::trading_ui Umicom::trading_chart_persistence)
        umicom_apply_warnings(${target})
        umicom_apply_sanitizers(${target})
        foreach(case IN LISTS ARGN)
            add_test(NAME "framework.drawing_appearance.${group}.${case}" COMMAND ${target} "${case}")
            set_tests_properties("framework.drawing_appearance.${group}.${case}" PROPERTIES
                TIMEOUT 30 LABELS "framework;chart;regression")
        endforeach()
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(${target})
        endif()
    endfunction()
    umicom_appearance_cases(codec encode decode bounds unsupported malformed capacity unterminated hex)
    umicom_appearance_cases(edit apply no-op reset duplicate stale wrong-pane invalid unsupported-tool)
    umicom_appearance_cases(render defaults range-fill line level zero-fill fallback capacity hidden)
    umicom_appearance_cases(workspace apply guards persistence legacy-roundtrip)
endif()
if(BUILD_TESTING AND TARGET Umicom::ui_gtk4)
    add_executable(umicom-drawing-appearance-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/chart_appearance/test_native.c")
    target_link_libraries(umicom-drawing-appearance-native-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-drawing-appearance-native-test)
    umicom_apply_sanitizers(umicom-drawing-appearance-native-test)
    foreach(case apply defaults draft-refresh legacy locked-hidden invalid stale selection instrument retained no-load invalid-utf8-id)
        add_test(NAME "framework.drawing_appearance.native.${case}" COMMAND umicom-drawing-appearance-native-test "${case}")
        set_tests_properties("framework.drawing_appearance.native.${case}" PROPERTIES
            TIMEOUT 60 SKIP_RETURN_CODE 77 LABELS "framework;chart;gtk4;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-drawing-appearance-native-test)
    endif()
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/CHART_DRAWING_APPEARANCE.md"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom-framework/docs)
