#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomEnterpriseDataViewPlatform.cmake
#
# PURPOSE:
#   Extend canonical Umicom::ui with virtual grids, enterprise trees, property
#   inspectors and high-density data-view orchestration.
#
# ARCHITECTURE:
#   Existing list/tree/property/workstation/design contracts remain authoritative.
#   This platform adds scale, virtualisation and advanced interaction semantics.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_UI_ENTERPRISE_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
# Load the dependency only when the parent build has not already provided its target.
if(NOT TARGET umicom_ui)
    message(FATAL_ERROR "UmicomEnterpriseDataViewPlatform.cmake requires canonical umicom_ui")
endif()

# Enterprise data-view capability extends the existing canonical UI target.
target_sources(umicom_ui PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/accessibility_model.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/aggregation_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/aggregation_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/cell_cache.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/cell_style.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/cell_validation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/cell_value.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/change_batch.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/clipboard_export.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/column_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/column_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/column_order.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/column_resize.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/column_virtualizer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/column_visibility.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/conditional_format.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/csv_export.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/data_delta.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/data_provider.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/data_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/edit_commit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/edit_history.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/edit_session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/enterprise_data_service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/filter_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/filter_predicate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/focus_model.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/frozen_columns.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/group_node.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/grouping_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/hit_test.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/inspector_commit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/inspector_editor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/inspector_property.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/inspector_section.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/inspector_validation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/keyboard_navigation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/measurement_cache.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/pagination.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/pinned_rows.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/query_state.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/recycler_pool.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/row_cache.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/row_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/row_height.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/row_key.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/row_virtualizer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/selection_model.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/selection_range.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/sort_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/sort_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/sparse_index.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/streaming_window.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/summary_footer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/tree_expansion.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/tree_filter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/tree_lazy_loader.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/tree_node.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/tree_path.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/tree_projection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/tree_selection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/tree_sort.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/tree_table.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/viewport.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/enterprise/virtual_range.c"
)

# Register verification targets only when the developer has enabled testing.
if(BUILD_TESTING)
    # Define the add ui enterprise test build helper so parent and application projects apply
    # one consistent rule.
    function(umicom_add_ui_enterprise_test target test_name source)
        # Configure the optional target only when its feature has created it.
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_UI_ENTERPRISE_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::ui)
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;ui-enterprise;data-grid;tree-inspector;virtualisation")
    endfunction()

    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-types-test
        framework.ui_enterprise.types
        tests/ui_enterprise/test_types.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-accessibility-model-test
        framework.ui_enterprise.accessibility.model
        tests/ui_enterprise/test_accessibility_model.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-aggregation-descriptor-test
        framework.ui_enterprise.aggregation.descriptor
        tests/ui_enterprise/test_aggregation_descriptor.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-aggregation-result-test
        framework.ui_enterprise.aggregation.result
        tests/ui_enterprise/test_aggregation_result.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-cell-cache-test
        framework.ui_enterprise.cell.cache
        tests/ui_enterprise/test_cell_cache.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-cell-style-test
        framework.ui_enterprise.cell.style
        tests/ui_enterprise/test_cell_style.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-cell-validation-test
        framework.ui_enterprise.cell.validation
        tests/ui_enterprise/test_cell_validation.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-cell-value-test
        framework.ui_enterprise.cell.value
        tests/ui_enterprise/test_cell_value.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-change-batch-test
        framework.ui_enterprise.change.batch
        tests/ui_enterprise/test_change_batch.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-clipboard-export-test
        framework.ui_enterprise.clipboard.export
        tests/ui_enterprise/test_clipboard_export.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-column-catalogue-test
        framework.ui_enterprise.column.catalogue
        tests/ui_enterprise/test_column_catalogue.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-column-descriptor-test
        framework.ui_enterprise.column.descriptor
        tests/ui_enterprise/test_column_descriptor.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-column-order-test
        framework.ui_enterprise.column.order
        tests/ui_enterprise/test_column_order.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-column-resize-test
        framework.ui_enterprise.column.resize
        tests/ui_enterprise/test_column_resize.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-column-virtualizer-test
        framework.ui_enterprise.column.virtualizer
        tests/ui_enterprise/test_column_virtualizer.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-column-visibility-test
        framework.ui_enterprise.column.visibility
        tests/ui_enterprise/test_column_visibility.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-conditional-format-test
        framework.ui_enterprise.conditional.format
        tests/ui_enterprise/test_conditional_format.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-csv-export-test
        framework.ui_enterprise.csv.export
        tests/ui_enterprise/test_csv_export.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-data-delta-test
        framework.ui_enterprise.data.delta
        tests/ui_enterprise/test_data_delta.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-data-provider-test
        framework.ui_enterprise.data.provider
        tests/ui_enterprise/test_data_provider.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-data-snapshot-test
        framework.ui_enterprise.data.snapshot
        tests/ui_enterprise/test_data_snapshot.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-edit-commit-test
        framework.ui_enterprise.edit.commit
        tests/ui_enterprise/test_edit_commit.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-edit-history-test
        framework.ui_enterprise.edit.history
        tests/ui_enterprise/test_edit_history.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-edit-session-test
        framework.ui_enterprise.edit.session
        tests/ui_enterprise/test_edit_session.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-enterprise-data-service-test
        framework.ui_enterprise.enterprise.data.service
        tests/ui_enterprise/test_enterprise_data_service.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-filter-plan-test
        framework.ui_enterprise.filter.plan
        tests/ui_enterprise/test_filter_plan.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-filter-predicate-test
        framework.ui_enterprise.filter.predicate
        tests/ui_enterprise/test_filter_predicate.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-focus-model-test
        framework.ui_enterprise.focus.model
        tests/ui_enterprise/test_focus_model.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-frozen-columns-test
        framework.ui_enterprise.frozen.columns
        tests/ui_enterprise/test_frozen_columns.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-group-node-test
        framework.ui_enterprise.group.node
        tests/ui_enterprise/test_group_node.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-grouping-descriptor-test
        framework.ui_enterprise.grouping.descriptor
        tests/ui_enterprise/test_grouping_descriptor.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-hit-test-test
        framework.ui_enterprise.hit.test
        tests/ui_enterprise/test_hit_test.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-inspector-commit-test
        framework.ui_enterprise.inspector.commit
        tests/ui_enterprise/test_inspector_commit.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-inspector-editor-test
        framework.ui_enterprise.inspector.editor
        tests/ui_enterprise/test_inspector_editor.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-inspector-property-test
        framework.ui_enterprise.inspector.property
        tests/ui_enterprise/test_inspector_property.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-inspector-section-test
        framework.ui_enterprise.inspector.section
        tests/ui_enterprise/test_inspector_section.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-inspector-validation-test
        framework.ui_enterprise.inspector.validation
        tests/ui_enterprise/test_inspector_validation.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-keyboard-navigation-test
        framework.ui_enterprise.keyboard.navigation
        tests/ui_enterprise/test_keyboard_navigation.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-measurement-cache-test
        framework.ui_enterprise.measurement.cache
        tests/ui_enterprise/test_measurement_cache.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-pagination-test
        framework.ui_enterprise.pagination
        tests/ui_enterprise/test_pagination.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-pinned-rows-test
        framework.ui_enterprise.pinned.rows
        tests/ui_enterprise/test_pinned_rows.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-query-state-test
        framework.ui_enterprise.query.state
        tests/ui_enterprise/test_query_state.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-recycler-pool-test
        framework.ui_enterprise.recycler.pool
        tests/ui_enterprise/test_recycler_pool.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-row-cache-test
        framework.ui_enterprise.row.cache
        tests/ui_enterprise/test_row_cache.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-row-descriptor-test
        framework.ui_enterprise.row.descriptor
        tests/ui_enterprise/test_row_descriptor.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-row-height-test
        framework.ui_enterprise.row.height
        tests/ui_enterprise/test_row_height.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-row-key-test
        framework.ui_enterprise.row.key
        tests/ui_enterprise/test_row_key.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-row-virtualizer-test
        framework.ui_enterprise.row.virtualizer
        tests/ui_enterprise/test_row_virtualizer.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-selection-model-test
        framework.ui_enterprise.selection.model
        tests/ui_enterprise/test_selection_model.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-selection-range-test
        framework.ui_enterprise.selection.range
        tests/ui_enterprise/test_selection_range.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-sort-descriptor-test
        framework.ui_enterprise.sort.descriptor
        tests/ui_enterprise/test_sort_descriptor.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-sort-plan-test
        framework.ui_enterprise.sort.plan
        tests/ui_enterprise/test_sort_plan.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-sparse-index-test
        framework.ui_enterprise.sparse.index
        tests/ui_enterprise/test_sparse_index.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-streaming-window-test
        framework.ui_enterprise.streaming.window
        tests/ui_enterprise/test_streaming_window.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-summary-footer-test
        framework.ui_enterprise.summary.footer
        tests/ui_enterprise/test_summary_footer.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-tree-expansion-test
        framework.ui_enterprise.tree.expansion
        tests/ui_enterprise/test_tree_expansion.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-tree-filter-test
        framework.ui_enterprise.tree.filter
        tests/ui_enterprise/test_tree_filter.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-tree-lazy-loader-test
        framework.ui_enterprise.tree.lazy.loader
        tests/ui_enterprise/test_tree_lazy_loader.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-tree-node-test
        framework.ui_enterprise.tree.node
        tests/ui_enterprise/test_tree_node.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-tree-path-test
        framework.ui_enterprise.tree.path
        tests/ui_enterprise/test_tree_path.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-tree-projection-test
        framework.ui_enterprise.tree.projection
        tests/ui_enterprise/test_tree_projection.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-tree-selection-test
        framework.ui_enterprise.tree.selection
        tests/ui_enterprise/test_tree_selection.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-tree-sort-test
        framework.ui_enterprise.tree.sort
        tests/ui_enterprise/test_tree_sort.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-tree-table-test
        framework.ui_enterprise.tree.table
        tests/ui_enterprise/test_tree_table.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-viewport-test
        framework.ui_enterprise.viewport
        tests/ui_enterprise/test_viewport.c
    )
    umicom_add_ui_enterprise_test(
        umicom-ui-enterprise-virtual-range-test
        framework.ui_enterprise.virtual.range
        tests/ui_enterprise/test_virtual_range.c
    )
endif()

message(STATUS "Umicom enterprise virtual grid, tree and inspector platform enabled")
