# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING AND TARGET Umicom::creative_workspace_gtk4 AND (WIN32 OR UNIX) AND NOT EMSCRIPTEN)
    add_executable(umicom-creative-asset-archive-gtk-test "${CMAKE_CURRENT_LIST_DIR}/../tests/creative_assets/test_archive_gtk4.c")
    target_link_libraries(umicom-creative-asset-archive-gtk-test PRIVATE Umicom::creative_workspace_gtk4)
    umicom_creative_configure_target(umicom-creative-asset-archive-gtk-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-creative-asset-archive-gtk-test)
    endif()
    foreach(case reopen corrupt-retains cancelled-retains save-existing busy no-auto-open raw-copy invalid-path independent retained-control)
        add_test(NAME framework.creative_assets.archive_gtk.${case} COMMAND umicom-creative-asset-archive-gtk-test ${case})
        set_tests_properties(framework.creative_assets.archive_gtk.${case} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;creative-assets;archive;gtk4;regression")
    endforeach()
endif()
