# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-png-encode-test "${CMAKE_CURRENT_LIST_DIR}/../tests/media/test_png_encode.c")
    target_link_libraries(umicom-png-encode-test PRIVATE Umicom::png_image)
    set_target_properties(umicom-png-encode-test PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings(umicom-png-encode-test)
    umicom_apply_sanitizers(umicom-png-encode-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-png-encode-test)
    endif()
    foreach(case roundtrip deterministic independent null-surface null-pointer null-size live-output cancelled dimension-limit pixel-limit unavailable)
        add_test(NAME framework.media.png_encode.${case} COMMAND umicom-png-encode-test ${case})
        set_tests_properties(framework.media.png_encode.${case} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;media;png;regression")
    endforeach()
endif()
