# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-search-reader-test "${CMAKE_CURRENT_LIST_DIR}/../tests/platform/test_search_reader.c")
    target_link_libraries(umicom-search-reader-test PRIVATE Umicom::platform)
    umicom_apply_warnings(umicom-search-reader-test)
    umicom_apply_sanitizers(umicom-search-reader-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-search-reader-test)
    endif()
    foreach(case owned empty invalid-buffer binary oversized serialized-limit unsupported failed-allocation io-error sink-error cancel-before cancel-reader cancel-sink index-changed excluded no-read no-release no-limit descriptor-copy session-copy session-error raw-fallback literal-bom result-limit)
        add_test(NAME framework.search.reader.${case} COMMAND umicom-search-reader-test ${case})
        set_tests_properties(framework.search.reader.${case} PROPERTIES TIMEOUT 45 LABELS "framework;search;unicode;ownership;regression")
    endforeach()
endif()
