# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-web-exchange-test "${CMAKE_CURRENT_LIST_DIR}/../tests/web/test_connection.c")
    target_link_libraries(umicom-web-exchange-test PRIVATE Umicom::web)
    umicom_apply_warnings(umicom-web-exchange-test)
    umicom_apply_sanitizers(umicom-web-exchange-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-web-exchange-test)
    endif()
    foreach(case get fragmented head post binary-body missing-route malformed unsupported request-limit read-failure disconnected read-zero read-overcount write-failure write-zero write-overcount cancel-before cancel-read cancel-write handler-failure invalid-response cancelled-handler invalid-io invalid-bound)
        add_test(NAME framework.web.exchange.${case} COMMAND umicom-web-exchange-test ${case})
        set_tests_properties(framework.web.exchange.${case} PROPERTIES TIMEOUT 30 LABELS "framework;web;http;regression")
    endforeach()
endif()
