# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-recovery-coordinator-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_recovery_coordinator.c")
    target_link_libraries(umicom-recovery-coordinator-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-recovery-coordinator-test)
    umicom_apply_sanitizers(umicom-recovery-coordinator-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-recovery-coordinator-test)
    endif()
    foreach(case capture pending-typing capture-read-only selection unicode crlf large empty ownership other-active invalid-selection invalid-identity missing closed cancelled invalid-key null-capture restore restore-position restore-twice restore-existing restore-no-history null-restore)
        add_test(NAME framework.document.recovery_coordinator.${case} COMMAND umicom-recovery-coordinator-test ${case})
        set_tests_properties(framework.document.recovery_coordinator.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;recovery;ownership;regression")
    endforeach()
endif()
