# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-completion-response-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_completion_response.c")
    target_link_libraries(umicom-completion-response-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-completion-response-test)
    umicom_apply_sanitizers(umicom-completion-response-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-completion-response-test)
    endif()
    foreach(case array list null wrong-id string-id missing-id missing-protocol protocol duplicate-id mixed request error error-code error-message missing-result source-spans arguments cancel)
        add_test(NAME framework.language_runtime.completion_response.${case} COMMAND umicom-completion-response-test ${case})
        set_tests_properties(framework.language_runtime.completion_response.${case} PROPERTIES TIMEOUT 30
            LABELS "framework;language;completion;ownership;regression")
    endforeach()
    add_executable(umicom-platform-routing-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_platform_routing.c")
    target_link_libraries(umicom-platform-routing-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-platform-routing-test)
    umicom_apply_sanitizers(umicom-platform-routing-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-platform-routing-test)
    endif()
    foreach(case scoped wrong-server capacity latest-first oldest-first review buffer-change display-only change close reopen server-request next-request diagnostic-owner diagnostic-stale diagnostic-future diagnostic-unversioned diagnostic-current)
        add_test(NAME framework.language_runtime.platform_routing.${case} COMMAND umicom-platform-routing-test ${case})
        set_tests_properties(framework.language_runtime.platform_routing.${case} PROPERTIES TIMEOUT 30
            LABELS "framework;language;completion;ownership;regression")
    endforeach()
endif()
