# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-action-diagnostics-query-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_action_diagnostics_query.c")
    target_link_libraries(umicom-action-diagnostics-query-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-action-diagnostics-query-test)
    umicom_apply_sanitizers(umicom-action-diagnostics-query-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-action-diagnostics-query-test)
    endif()
    foreach(case oversized-context valid empty filter point raw stale wrong-uri missing invalid-publication outside action-error shutdown-error cancel-before encoding)
        add_test(NAME framework.language_runtime.action_diagnostics_query.${case} COMMAND umicom-action-diagnostics-query-test ${case})
        set_tests_properties(framework.language_runtime.action_diagnostics_query.${case} PROPERTIES TIMEOUT 30
            LABELS "framework;language;code-actions;ownership;regression")
    endforeach()
endif()
