#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomObservabilityPerformancePlatform.cmake
#
# PURPOSE:
#   Extend the canonical observability target with Framework-owned profiling,
#   metrics/traces, memory analysis, benchmarks, coverage, performance budgets
#   and toolkit-neutral operational dashboard state.
#
# ARCHITECTURE:
#   Existing diagnostics/observability/runtime implementations remain
#   authoritative. This platform adds reusable performance engineering state
#   without creating a competing observability library in an application.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_OBSERVABILITY_PERFORMANCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
# Load the dependency only when the parent build has not already provided its target.
if(NOT TARGET umicom_observability)
    message(FATAL_ERROR "UmicomObservabilityPerformancePlatform.cmake requires umicom_observability")
endif()

target_sources(umicom_observability PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_target.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_configuration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_capability.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_sample.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_sample_buffer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_frame.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_stack.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_thread.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_process.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_symbol.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_hotspot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_hotpath.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_call_tree.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_flamegraph.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_aggregation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/profiler_filter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/allocation_event.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/allocation_site.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/allocation_summary.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/heap_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/leak_candidate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/memory_pressure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/memory_budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/memory_regression.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/metric_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/metric_sample.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/metric_series.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/counter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/gauge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/histogram.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/trace_span.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/trace_event.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/trace_session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/trace_filter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/correlation_context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/timeline.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/benchmark_case.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/benchmark_run.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/benchmark_sample.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/benchmark_statistics.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/benchmark_baseline.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/benchmark_comparison.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/performance_regression.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/performance_budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/threshold_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/coverage_file.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/coverage_region.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/coverage_summary.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/coverage_baseline.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/coverage_regression.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/crash_signature.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/crash_correlation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/crash_cluster.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/resource_sample.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/resource_budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/process_telemetry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/io_telemetry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/network_telemetry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/runtime_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/observability_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/dashboard_card.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/dashboard_layout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/performance_session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/observability/performance/operations_dashboard.c"
)

# Register verification targets only when the developer has enabled testing.
if(BUILD_TESTING)
    # Define the add observability performance test build helper so parent and application
    # projects apply one consistent rule.
    function(umicom_add_observability_performance_test target test_name source)
        # Configure the optional target only when its feature has created it.
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_OBSERVABILITY_PERFORMANCE_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::observability)
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;observability-performance")
    endfunction()

    umicom_add_observability_performance_test(
        umicom-observability-performance-types-test
        framework.observability_performance.types
        tests/observability_performance/test_types.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-session-test
        framework.observability_performance.profiler.session
        tests/observability_performance/test_profiler_session.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-target-test
        framework.observability_performance.profiler.target
        tests/observability_performance/test_profiler_target.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-configuration-test
        framework.observability_performance.profiler.configuration
        tests/observability_performance/test_profiler_configuration.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-capability-test
        framework.observability_performance.profiler.capability
        tests/observability_performance/test_profiler_capability.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-sample-test
        framework.observability_performance.profiler.sample
        tests/observability_performance/test_profiler_sample.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-sample-buffer-test
        framework.observability_performance.profiler.sample.buffer
        tests/observability_performance/test_profiler_sample_buffer.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-frame-test
        framework.observability_performance.profiler.frame
        tests/observability_performance/test_profiler_frame.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-stack-test
        framework.observability_performance.profiler.stack
        tests/observability_performance/test_profiler_stack.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-thread-test
        framework.observability_performance.profiler.thread
        tests/observability_performance/test_profiler_thread.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-process-test
        framework.observability_performance.profiler.process
        tests/observability_performance/test_profiler_process.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-symbol-test
        framework.observability_performance.profiler.symbol
        tests/observability_performance/test_profiler_symbol.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-hotspot-test
        framework.observability_performance.profiler.hotspot
        tests/observability_performance/test_profiler_hotspot.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-hotpath-test
        framework.observability_performance.profiler.hotpath
        tests/observability_performance/test_profiler_hotpath.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-call-tree-test
        framework.observability_performance.profiler.call.tree
        tests/observability_performance/test_profiler_call_tree.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-flamegraph-test
        framework.observability_performance.profiler.flamegraph
        tests/observability_performance/test_profiler_flamegraph.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-aggregation-test
        framework.observability_performance.profiler.aggregation
        tests/observability_performance/test_profiler_aggregation.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-profiler-filter-test
        framework.observability_performance.profiler.filter
        tests/observability_performance/test_profiler_filter.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-allocation-event-test
        framework.observability_performance.allocation.event
        tests/observability_performance/test_allocation_event.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-allocation-site-test
        framework.observability_performance.allocation.site
        tests/observability_performance/test_allocation_site.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-allocation-summary-test
        framework.observability_performance.allocation.summary
        tests/observability_performance/test_allocation_summary.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-heap-snapshot-test
        framework.observability_performance.heap.snapshot
        tests/observability_performance/test_heap_snapshot.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-leak-candidate-test
        framework.observability_performance.leak.candidate
        tests/observability_performance/test_leak_candidate.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-memory-pressure-test
        framework.observability_performance.memory.pressure
        tests/observability_performance/test_memory_pressure.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-memory-budget-test
        framework.observability_performance.memory.budget
        tests/observability_performance/test_memory_budget.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-memory-regression-test
        framework.observability_performance.memory.regression
        tests/observability_performance/test_memory_regression.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-metric-descriptor-test
        framework.observability_performance.metric.descriptor
        tests/observability_performance/test_metric_descriptor.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-metric-sample-test
        framework.observability_performance.metric.sample
        tests/observability_performance/test_metric_sample.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-metric-series-test
        framework.observability_performance.metric.series
        tests/observability_performance/test_metric_series.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-counter-test
        framework.observability_performance.counter
        tests/observability_performance/test_counter.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-gauge-test
        framework.observability_performance.gauge
        tests/observability_performance/test_gauge.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-histogram-test
        framework.observability_performance.histogram
        tests/observability_performance/test_histogram.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-trace-span-test
        framework.observability_performance.trace.span
        tests/observability_performance/test_trace_span.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-trace-event-test
        framework.observability_performance.trace.event
        tests/observability_performance/test_trace_event.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-trace-session-test
        framework.observability_performance.trace.session
        tests/observability_performance/test_trace_session.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-trace-filter-test
        framework.observability_performance.trace.filter
        tests/observability_performance/test_trace_filter.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-correlation-context-test
        framework.observability_performance.correlation.context
        tests/observability_performance/test_correlation_context.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-timeline-test
        framework.observability_performance.timeline
        tests/observability_performance/test_timeline.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-benchmark-case-test
        framework.observability_performance.benchmark.case
        tests/observability_performance/test_benchmark_case.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-benchmark-run-test
        framework.observability_performance.benchmark.run
        tests/observability_performance/test_benchmark_run.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-benchmark-sample-test
        framework.observability_performance.benchmark.sample
        tests/observability_performance/test_benchmark_sample.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-benchmark-statistics-test
        framework.observability_performance.benchmark.statistics
        tests/observability_performance/test_benchmark_statistics.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-benchmark-baseline-test
        framework.observability_performance.benchmark.baseline
        tests/observability_performance/test_benchmark_baseline.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-benchmark-comparison-test
        framework.observability_performance.benchmark.comparison
        tests/observability_performance/test_benchmark_comparison.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-performance-regression-test
        framework.observability_performance.performance.regression
        tests/observability_performance/test_performance_regression.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-performance-budget-test
        framework.observability_performance.performance.budget
        tests/observability_performance/test_performance_budget.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-threshold-policy-test
        framework.observability_performance.threshold.policy
        tests/observability_performance/test_threshold_policy.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-coverage-file-test
        framework.observability_performance.coverage.file
        tests/observability_performance/test_coverage_file.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-coverage-region-test
        framework.observability_performance.coverage.region
        tests/observability_performance/test_coverage_region.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-coverage-summary-test
        framework.observability_performance.coverage.summary
        tests/observability_performance/test_coverage_summary.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-coverage-baseline-test
        framework.observability_performance.coverage.baseline
        tests/observability_performance/test_coverage_baseline.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-coverage-regression-test
        framework.observability_performance.coverage.regression
        tests/observability_performance/test_coverage_regression.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-crash-signature-test
        framework.observability_performance.crash.signature
        tests/observability_performance/test_crash_signature.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-crash-correlation-test
        framework.observability_performance.crash.correlation
        tests/observability_performance/test_crash_correlation.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-crash-cluster-test
        framework.observability_performance.crash.cluster
        tests/observability_performance/test_crash_cluster.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-resource-sample-test
        framework.observability_performance.resource.sample
        tests/observability_performance/test_resource_sample.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-resource-budget-test
        framework.observability_performance.resource.budget
        tests/observability_performance/test_resource_budget.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-process-telemetry-test
        framework.observability_performance.process.telemetry
        tests/observability_performance/test_process_telemetry.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-io-telemetry-test
        framework.observability_performance.io.telemetry
        tests/observability_performance/test_io_telemetry.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-network-telemetry-test
        framework.observability_performance.network.telemetry
        tests/observability_performance/test_network_telemetry.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-runtime-health-test
        framework.observability_performance.runtime.health
        tests/observability_performance/test_runtime_health.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-observability-snapshot-test
        framework.observability_performance.observability.snapshot
        tests/observability_performance/test_observability_snapshot.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-dashboard-card-test
        framework.observability_performance.dashboard.card
        tests/observability_performance/test_dashboard_card.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-dashboard-layout-test
        framework.observability_performance.dashboard.layout
        tests/observability_performance/test_dashboard_layout.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-performance-session-test
        framework.observability_performance.performance.session
        tests/observability_performance/test_performance_session.c
    )
    umicom_add_observability_performance_test(
        umicom-observability-performance-operations-dashboard-test
        framework.observability_performance.operations.dashboard
        tests/observability_performance/test_operations_dashboard.c
    )
endif()

message(STATUS "Umicom profiling, observability and performance engineering platform enabled")
