#-----------------------------------------------------------------------------
# Umicom Framework editor feature conformance tests.
# Created by Sammy Hegab, Umicom Foundation. Licence: MIT.
#-----------------------------------------------------------------------------
    umicom_add_framework_test(umicom-editor-features-01-tests framework.editor_features_01 tests/editor_features/test_editor_features_01.c)
    umicom_add_framework_test(umicom-editor-features-02-tests framework.editor_features_02 tests/editor_features/test_editor_features_02.c)
    umicom_add_framework_test(umicom-editor-features-03-tests framework.editor_features_03 tests/editor_features/test_editor_features_03.c)
    umicom_add_framework_test(umicom-editor-features-04-tests framework.editor_features_04 tests/editor_features/test_editor_features_04.c)
    umicom_add_framework_test(umicom-editor-features-05-tests framework.editor_features_05 tests/editor_features/test_editor_features_05.c)
    umicom_add_framework_test(umicom-editor-features-06-tests framework.editor_features_06 tests/editor_features/test_editor_features_06.c)
    umicom_add_framework_test(umicom-editor-features-07-tests framework.editor_features_07 tests/editor_features/test_editor_features_07.c)
    umicom_add_framework_test(umicom-editor-features-08-tests framework.editor_features_08 tests/editor_features/test_editor_features_08.c)
    umicom_add_framework_test(umicom-editor-features-09-tests framework.editor_features_09 tests/editor_features/test_editor_features_09.c)
    umicom_add_framework_test(umicom-editor-features-10-tests framework.editor_features_10 tests/editor_features/test_editor_features_10.c)
    umicom_add_framework_test(umicom-editor-features-11-tests framework.editor_features_11 tests/editor_features/test_editor_features_11.c)
    umicom_add_framework_test(umicom-editor-features-12-tests framework.editor_features_12 tests/editor_features/test_editor_features_12.c)
    umicom_add_framework_test(umicom-editor-features-13-tests framework.editor_features_13 tests/editor_features/test_editor_features_13.c)
    umicom_add_framework_test(umicom-editor-features-14-tests framework.editor_features_14 tests/editor_features/test_editor_features_14.c)
    umicom_add_framework_test(umicom-editor-features-15-tests framework.editor_features_15 tests/editor_features/test_editor_features_15.c)
    umicom_add_framework_test(umicom-editor-features-16-tests framework.editor_features_16 tests/editor_features/test_editor_features_16.c)
    umicom_add_framework_test(umicom-editor-features-17-tests framework.editor_features_17 tests/editor_features/test_editor_features_17.c)
    umicom_add_framework_test(umicom-editor-features-18-tests framework.editor_features_18 tests/editor_features/test_editor_features_18.c)
    umicom_add_framework_test(umicom-editor-features-19-tests framework.editor_features_19 tests/editor_features/test_editor_features_19.c)
    umicom_add_framework_test(umicom-editor-features-20-tests framework.editor_features_20 tests/editor_features/test_editor_features_20.c)
    umicom_add_framework_test(umicom-editor-features-21-tests framework.editor_features_21 tests/editor_features/test_editor_features_21.c)
    umicom_add_framework_test(umicom-editor-features-22-tests framework.editor_features_22 tests/editor_features/test_editor_features_22.c)
    umicom_add_framework_test(umicom-editor-features-23-tests framework.editor_features_23 tests/editor_features/test_editor_features_23.c)
    umicom_add_framework_test(umicom-editor-features-24-tests framework.editor_features_24 tests/editor_features/test_editor_features_24.c)

    # Workspace search and replacement platform.
    umicom_add_framework_test(umicom-workspace-search-pattern-tests framework.editor.workspace_search_pattern tests/test_workspace_search_pattern.c)
    umicom_add_framework_test(umicom-workspace-search-pattern-fuzz-tests framework.editor.workspace_search_pattern_fuzz tests/test_workspace_search_pattern_fuzz.c)
    umicom_add_framework_test(umicom-workspace-search-exclusion-tests framework.editor.workspace_search_exclusion tests/test_workspace_search_exclusion.c)
    umicom_add_framework_test(umicom-workspace-search-index-tests framework.editor.workspace_search_index tests/test_workspace_search_index.c)
    umicom_add_framework_test(umicom-workspace-search-query-tests framework.editor.workspace_search_query tests/test_workspace_search_query.c)
    umicom_add_framework_test(umicom-workspace-search-preview-tests framework.editor.workspace_search_preview tests/test_workspace_search_preview.c)
    umicom_add_framework_test(umicom-workspace-replace-plan-tests framework.editor.workspace_replace_plan tests/test_workspace_replace_plan.c)
    umicom_add_framework_test(umicom-workspace-replace-transaction-tests framework.editor.workspace_replace_transaction tests/test_workspace_replace_transaction.c)
    umicom_add_framework_test(umicom-workspace-search-orchestration-tests framework.editor.workspace_search_orchestration tests/test_workspace_search_orchestration.c)
    umicom_add_framework_test(umicom-workspace-search-command-tests framework.editor.workspace_search_command tests/test_workspace_search_command.c)

    # Completion and inline suggestion platform.
    umicom_add_framework_test(umicom-completion-candidate-tests framework.editor.completion_candidate tests/test_completion_candidate.c)
    umicom_add_framework_test(umicom-completion-provider-tests framework.editor.completion_provider tests/test_completion_provider.c)
    umicom_add_framework_test(umicom-completion-query-tests framework.editor.completion_query tests/test_completion_query.c)
    umicom_add_framework_test(umicom-completion-session-tests framework.editor.completion_session tests/test_completion_session.c)
    umicom_add_framework_test(umicom-completion-orchestration-tests framework.editor.completion_orchestration tests/test_completion_orchestration.c)
    umicom_add_framework_test(umicom-inline-suggestion-tests framework.editor.inline_suggestion tests/test_inline_suggestion.c)
    umicom_add_framework_test(umicom-inline-suggestion-session-tests framework.editor.inline_suggestion_session tests/test_inline_suggestion_session.c)
    umicom_add_framework_test(umicom-completion-command-tests framework.editor.completion_command tests/test_completion_command.c)

    # Professional diagnostics, Problems and SARIF platform.
    umicom_add_framework_test(umicom-diagnostic-provider-tests framework.diagnostics.provider tests/test_diagnostic_provider.c)
    umicom_add_framework_test(umicom-diagnostic-severity-policy-tests framework.diagnostics.severity_policy tests/test_diagnostic_severity_policy.c)
    umicom_add_framework_test(umicom-diagnostic-suppression-tests framework.diagnostics.suppression tests/test_diagnostic_suppression.c)
    umicom_add_framework_test(umicom-diagnostic-baseline-tests framework.diagnostics.baseline tests/test_diagnostic_baseline.c)
    umicom_add_framework_test(umicom-diagnostic-problem-model-tests framework.diagnostics.problem_model tests/test_diagnostic_problem_model.c)
    umicom_add_framework_test(umicom-diagnostic-sarif-tests framework.diagnostics.sarif tests/test_diagnostic_sarif.c)
    umicom_add_framework_test(umicom-diagnostic-sarif-fuzz-tests framework.diagnostics.sarif_fuzz tests/test_diagnostic_sarif_fuzz.c)
    umicom_add_framework_test(umicom-diagnostic-orchestration-tests framework.diagnostics.orchestration tests/test_diagnostic_orchestration.c)
    umicom_add_framework_test(umicom-diagnostic-command-tests framework.diagnostics.commands tests/test_diagnostic_command.c)

    # Professional navigation, peek and hierarchy experience.
    umicom_add_framework_test(umicom-navigation-provider-tests framework.editor.navigation_provider tests/test_navigation_provider.c)
    umicom_add_framework_test(umicom-navigation-query-session-tests framework.editor.navigation_query_session tests/test_navigation_query_session.c)
    umicom_add_framework_test(umicom-navigation-source-preview-tests framework.editor.navigation_source_preview tests/test_navigation_source_preview.c)
    umicom_add_framework_test(umicom-peek-navigation-session-tests framework.editor.peek_navigation_session tests/test_peek_navigation_session.c)
    umicom_add_framework_test(umicom-reference-navigation-session-tests framework.editor.reference_navigation_session tests/test_reference_navigation_session.c)
    umicom_add_framework_test(umicom-hierarchy-navigation-session-tests framework.editor.hierarchy_navigation_session tests/test_hierarchy_navigation_session.c)
    umicom_add_framework_test(umicom-symbol-navigation-session-tests framework.editor.symbol_navigation_session tests/test_symbol_navigation_session.c)
    umicom_add_framework_test(umicom-navigation-experience-tests framework.editor.navigation_experience tests/test_navigation_experience.c)


    # Advanced debugging platform.
    umicom_add_framework_test(umicom-debug-advanced-breakpoint-tests framework.debug.advanced_breakpoint tests/test_debug_advanced_breakpoint.c)
    umicom_add_framework_test(umicom-debug-adapter-contract-tests framework.debug.adapter_contract tests/test_debug_adapter_contract.c)
    umicom_add_framework_test(umicom-debug-thread-inspector-tests framework.debug.thread_inspector tests/test_debug_thread_inspector.c)
    umicom_add_framework_test(umicom-debug-register-bank-tests framework.debug.register_bank tests/test_debug_register_bank.c)
    umicom_add_framework_test(umicom-debug-memory-view-tests framework.debug.memory_view tests/test_debug_memory_view.c)
    umicom_add_framework_test(umicom-debug-disassembly-view-tests framework.debug.disassembly_view tests/test_debug_disassembly_view.c)
    umicom_add_framework_test(umicom-debug-inspection-session-tests framework.debug.inspection_session tests/test_debug_inspection_session.c)
    umicom_add_framework_test(umicom-debug-advanced-platform-tests framework.debug.advanced_platform tests/test_debug_advanced_platform.c)
