# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_completion_settings_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-completion-settings-test)
        return()
    endif()
    add_executable(umicom-completion-settings-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_completion_settings_gtk4.c")
    target_link_libraries(umicom-completion-settings-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-completion-settings-test)
    umicom_apply_sanitizers(umicom-completion-settings-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-completion-settings-test)
    endif()
    foreach(case save-load missing invalid-file language-mismatch invalid-save changed-back edit-during-load load-publication save-close worker-unbind retained private transient invalid-root creation-unbind busy save-newer-draft)
        add_test(NAME framework.document.completion_settings.gtk4.${case}
            COMMAND umicom-completion-settings-test ${case})
        set_tests_properties(framework.document.completion_settings.gtk4.${case} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77
            LABELS "framework;document;language;preferences;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_completion_settings_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_completion_settings_checks)
endif()
