# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Launch descriptions belong to the build owner and carry no GUI dependency.
include_guard(GLOBAL)
target_sources(umicom_build PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/build/launch_plan.c")
if(BUILD_TESTING)
    add_executable(umicom-launch-plan-test "${CMAKE_CURRENT_LIST_DIR}/../tests/launch_review/test_plan.c")
    target_link_libraries(umicom-launch-plan-test PRIVATE Umicom::build)
    umicom_apply_warnings(umicom-launch-plan-test)
    umicom_apply_sanitizers(umicom-launch-plan-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-launch-plan-test)
    endif()
    foreach(case relative owned provider bare dot-relative absolute missing conflict unterminated bad-quotes relative-root null drive-relative rooted-program select-program select-folder select-inplace select-invalid capacity control-path)
        add_test(NAME framework.launch_review.plan.${case} COMMAND umicom-launch-plan-test ${case})
        set_tests_properties(framework.launch_review.plan.${case} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77
            LABELS "framework;build;launch;regression")
    endforeach()
endif()
function(umicom_attach_launch_review_native_checks)
    if(NOT BUILD_TESTING OR NOT TARGET umicom_ui_gtk4 OR TARGET umicom-launch-review-gtk4-test)
        return()
    endif()
    # The fixture compiles the real controller under private symbol names and
    # substitutes only native picker requests. It does not launch a process.
    add_executable(umicom-launch-review-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/launch_review/test_gtk4.c")
    target_link_libraries(umicom-launch-review-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-launch-review-gtk4-test)
    umicom_apply_sanitizers(umicom-launch-review-gtk4-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-launch-review-gtk4-test)
    endif()
    foreach(case review-path review-bare review-invalid review-invalidate notify-destroy notify-edit notify-reentry program folder pending-destroy pending-hide pending-parent stale entry-reentry cancel remote)
        add_test(NAME framework.launch_review.gtk4.${case} COMMAND umicom-launch-review-gtk4-test ${case})
        set_tests_properties(framework.launch_review.gtk4.${case} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77
            LABELS "framework;build;launch;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_launch_review_native_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_launch_review_native_checks)
endif()
