# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_diagnostic_locations_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-diagnostic-locations-gtk4-test)
        return()
    endif()
    add_executable(umicom-diagnostic-locations-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_diagnostic_locations_gtk4.c")
    target_link_libraries(umicom-diagnostic-locations-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-diagnostic-locations-gtk4-test)
    umicom_apply_sanitizers(umicom-diagnostic-locations-gtk4-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-diagnostic-locations-gtk4-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-diagnostic-locations-gtk4-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-diagnostic-locations-gtk4-test)
    endif()
    foreach(case open primary same-draft related-draft unicode surrogate outside remote authority query read-only target-changed target-shortened primary-changed primary-changed-back caret-changed invalid-location invalid-diagnostic choice-reset no-related changed-settings worker-settings retained parent-close unbind literal model-invalidate selection-invalidate open-unbind hidden-apply)
        add_test(NAME framework.document.diagnostic_locations.gtk4.${case}
            COMMAND umicom-diagnostic-locations-gtk4-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.document.diagnostic_locations.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77
            LABELS "framework;document;language;diagnostic-locations;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_diagnostic_locations_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_diagnostic_locations_checks)
endif()
