# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_line_edits_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-line-edits-gtk4-test)
        return()
    endif()
    add_executable(umicom-line-edits-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_line_edit_gtk4.c")
    target_link_libraries(umicom-line-edits-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-line-edits-gtk4-test)
    umicom_apply_sanitizers(umicom-line-edits-gtk4-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-line-edits-gtk4-test)
    endif()
    foreach(case duplicate delete move-up move-down join indent outdent comment trim selection unicode crlf read-only invalid-kind no-document no-neighbor no-change unbound null-adapter completion-detach completion-destroy)
        add_test(NAME framework.document.line_edits.gtk4.${case}
            COMMAND umicom-line-edits-gtk4-test ${case})
        set_tests_properties(framework.document.line_edits.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77
            LABELS "framework;document;language;line-edit;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_line_edits_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_line_edits_checks)
endif()
