#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomFinancialPlatformCoreCompletion.cmake
#
# PURPOSE:
#   Complete the shared financial platform control plane across currencies,
#   parties, accounts, instruments, trades, positions, payments, ledger,
#   settlement, reconciliation, workflow and audit.
#
# ARCHITECTURE:
#   Existing Umicom::finance reference data, banking, payments, accounting,
#   settlement, valuation and regulatory engines remain authoritative. This
#   platform adds cross-domain control, lifecycle and evidence composition
#   without creating competing financial data models in applications.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

if(NOT TARGET umicom_finance)
    message(FATAL_ERROR
        "Financial Platform Core Completion requires canonical umicom_finance")
endif()

target_sources(umicom_finance PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/account/available_funds.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/account/balance_consistency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/account/currency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/account/identity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/account/ownership.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/account/reconciliation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/account/settlement.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/account/status.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/audit/actor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/audit/causation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/audit/immutability.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/audit/lineage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/audit/persistence.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/audit/readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/audit/sequence.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/audit/timestamp.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/currency/catalogue_coverage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/currency/code_validation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/currency/conversion_consistency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/currency/pair_readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/currency/precision_validation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/currency/rate_freshness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/currency/rate_tolerance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/currency/settlement_currency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/currency_rate_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/financial_audit_journal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/financial_control_service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/financial_platform_internal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/instrument/currency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/instrument/identity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/instrument/lifecycle.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/instrument/market_data.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/instrument/maturity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/instrument/price_precision.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/instrument/product_mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/instrument/settlement.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/instrument_link_store.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/ledger/account_mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/ledger/double_entry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/ledger/journal_validation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/ledger/period.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/ledger/posting.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/ledger/subledger.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/ledger/suspense.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/ledger/trial_balance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/ledger_batch.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/party/counterparty.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/party/identity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/party/kyc_readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/party/legal_entity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/party/lifecycle.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/party/ownership_consistency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/party/relationship_coverage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/party/role_coverage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/payment/amount.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/payment/approval.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/payment/beneficiary.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/payment/currency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/payment/cutoff.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/payment/instruction.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/payment/route.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/payment/settlement.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/payment_control_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/position/concentration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/position/currency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/position/gross_exposure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/position/market_value.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/position/net_exposure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/position/pnl.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/position/quantity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/position/reconciliation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/position_control_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/reconciliation/ageing.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/reconciliation/automation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/reconciliation/break_count.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/reconciliation/completion.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/reconciliation/coverage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/reconciliation/exception.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/reconciliation/matching.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/reconciliation/tolerance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/reconciliation_run.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/relationship_store.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/settlement/cash_leg.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/settlement/due_date.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/settlement/fail_age.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/settlement/instruction.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/settlement/netting.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/settlement/reconciliation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/settlement/securities_leg.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/settlement/status.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/settlement_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/trade/audit_coverage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/trade/counterparty.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/trade/economics.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/trade/identity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/trade/lifecycle.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/trade/notional.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/trade/position_impact.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/trade/settlement.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/trade_control_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/workflow/approval.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/workflow/completion.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/workflow/escalation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/workflow/role_coverage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/workflow/rollback.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/workflow/state_transition.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/workflow/task_coverage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/workflow/timeout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/financial_platform/workflow_instance.c"
)

if(BUILD_TESTING)
    function(umicom_add_financial_platform_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()

        add_executable(
            "${target}"
            "${CMAKE_CURRENT_LIST_DIR}/../tests/financial_platform/${source}"
        )

        target_link_libraries("${target}" PRIVATE Umicom::finance)

        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()

        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties(
            "${test_name}"
            PROPERTIES LABELS
            "framework;financial-platform;finance;payments;ledger;settlement;reconciliation"
        )
    endfunction()

    umicom_add_financial_platform_test(
        umicom-financial-platform-account-available-funds-test
        framework.financial_platform.account.available.funds
        test_account_available_funds.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-account-balance-consistency-test
        framework.financial_platform.account.balance.consistency
        test_account_balance_consistency.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-account-currency-test
        framework.financial_platform.account.currency
        test_account_currency.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-account-identity-test
        framework.financial_platform.account.identity
        test_account_identity.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-account-ownership-test
        framework.financial_platform.account.ownership
        test_account_ownership.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-account-reconciliation-test
        framework.financial_platform.account.reconciliation
        test_account_reconciliation.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-account-settlement-test
        framework.financial_platform.account.settlement
        test_account_settlement.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-account-status-test
        framework.financial_platform.account.status
        test_account_status.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-audit-actor-test
        framework.financial_platform.audit.actor
        test_audit_actor.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-audit-causation-test
        framework.financial_platform.audit.causation
        test_audit_causation.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-audit-immutability-test
        framework.financial_platform.audit.immutability
        test_audit_immutability.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-audit-lineage-test
        framework.financial_platform.audit.lineage
        test_audit_lineage.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-audit-persistence-test
        framework.financial_platform.audit.persistence
        test_audit_persistence.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-audit-readiness-test
        framework.financial_platform.audit.readiness
        test_audit_readiness.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-audit-sequence-test
        framework.financial_platform.audit.sequence
        test_audit_sequence.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-audit-timestamp-test
        framework.financial_platform.audit.timestamp
        test_audit_timestamp.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-broker-header-self-containment-test
        framework.financial_platform.broker.header.self.containment
        test_broker_header_self_containment.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-currency-catalogue-coverage-test
        framework.financial_platform.currency.catalogue.coverage
        test_currency_catalogue_coverage.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-currency-code-validation-test
        framework.financial_platform.currency.code.validation
        test_currency_code_validation.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-currency-conversion-consistency-test
        framework.financial_platform.currency.conversion.consistency
        test_currency_conversion_consistency.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-currency-pair-readiness-test
        framework.financial_platform.currency.pair.readiness
        test_currency_pair_readiness.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-currency-precision-validation-test
        framework.financial_platform.currency.precision.validation
        test_currency_precision_validation.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-currency-rate-book-test
        framework.financial_platform.currency.rate.book
        test_currency_rate_book.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-currency-rate-freshness-test
        framework.financial_platform.currency.rate.freshness
        test_currency_rate_freshness.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-currency-rate-tolerance-test
        framework.financial_platform.currency.rate.tolerance
        test_currency_rate_tolerance.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-currency-settlement-currency-test
        framework.financial_platform.currency.settlement.currency
        test_currency_settlement_currency.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-financial-audit-journal-test
        framework.financial_platform.financial.audit.journal
        test_financial_audit_journal.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-financial-control-service-test
        framework.financial_platform.financial.control.service
        test_financial_control_service.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-instrument-currency-test
        framework.financial_platform.instrument.currency
        test_instrument_currency.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-instrument-identity-test
        framework.financial_platform.instrument.identity
        test_instrument_identity.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-instrument-lifecycle-test
        framework.financial_platform.instrument.lifecycle
        test_instrument_lifecycle.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-instrument-link-store-test
        framework.financial_platform.instrument.link.store
        test_instrument_link_store.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-instrument-market-data-test
        framework.financial_platform.instrument.market.data
        test_instrument_market_data.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-instrument-maturity-test
        framework.financial_platform.instrument.maturity
        test_instrument_maturity.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-instrument-price-precision-test
        framework.financial_platform.instrument.price.precision
        test_instrument_price_precision.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-instrument-product-mapping-test
        framework.financial_platform.instrument.product.mapping
        test_instrument_product_mapping.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-instrument-settlement-test
        framework.financial_platform.instrument.settlement
        test_instrument_settlement.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-ledger-account-mapping-test
        framework.financial_platform.ledger.account.mapping
        test_ledger_account_mapping.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-ledger-batch-test
        framework.financial_platform.ledger.batch
        test_ledger_batch.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-ledger-double-entry-test
        framework.financial_platform.ledger.double.entry
        test_ledger_double_entry.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-ledger-journal-validation-test
        framework.financial_platform.ledger.journal.validation
        test_ledger_journal_validation.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-ledger-period-test
        framework.financial_platform.ledger.period
        test_ledger_period.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-ledger-posting-test
        framework.financial_platform.ledger.posting
        test_ledger_posting.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-ledger-subledger-test
        framework.financial_platform.ledger.subledger
        test_ledger_subledger.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-ledger-suspense-test
        framework.financial_platform.ledger.suspense
        test_ledger_suspense.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-ledger-trial-balance-test
        framework.financial_platform.ledger.trial.balance
        test_ledger_trial_balance.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-party-counterparty-test
        framework.financial_platform.party.counterparty
        test_party_counterparty.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-party-identity-test
        framework.financial_platform.party.identity
        test_party_identity.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-party-kyc-readiness-test
        framework.financial_platform.party.kyc.readiness
        test_party_kyc_readiness.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-party-legal-entity-test
        framework.financial_platform.party.legal.entity
        test_party_legal_entity.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-party-lifecycle-test
        framework.financial_platform.party.lifecycle
        test_party_lifecycle.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-party-ownership-consistency-test
        framework.financial_platform.party.ownership.consistency
        test_party_ownership_consistency.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-party-relationship-coverage-test
        framework.financial_platform.party.relationship.coverage
        test_party_relationship_coverage.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-party-role-coverage-test
        framework.financial_platform.party.role.coverage
        test_party_role_coverage.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-payment-amount-test
        framework.financial_platform.payment.amount
        test_payment_amount.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-payment-approval-test
        framework.financial_platform.payment.approval
        test_payment_approval.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-payment-beneficiary-test
        framework.financial_platform.payment.beneficiary
        test_payment_beneficiary.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-payment-control-book-test
        framework.financial_platform.payment.control.book
        test_payment_control_book.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-payment-currency-test
        framework.financial_platform.payment.currency
        test_payment_currency.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-payment-cutoff-test
        framework.financial_platform.payment.cutoff
        test_payment_cutoff.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-payment-instruction-test
        framework.financial_platform.payment.instruction
        test_payment_instruction.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-payment-route-test
        framework.financial_platform.payment.route
        test_payment_route.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-payment-settlement-test
        framework.financial_platform.payment.settlement
        test_payment_settlement.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-position-concentration-test
        framework.financial_platform.position.concentration
        test_position_concentration.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-position-control-book-test
        framework.financial_platform.position.control.book
        test_position_control_book.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-position-currency-test
        framework.financial_platform.position.currency
        test_position_currency.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-position-gross-exposure-test
        framework.financial_platform.position.gross.exposure
        test_position_gross_exposure.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-position-market-value-test
        framework.financial_platform.position.market.value
        test_position_market_value.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-position-net-exposure-test
        framework.financial_platform.position.net.exposure
        test_position_net_exposure.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-position-pnl-test
        framework.financial_platform.position.pnl
        test_position_pnl.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-position-quantity-test
        framework.financial_platform.position.quantity
        test_position_quantity.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-position-reconciliation-test
        framework.financial_platform.position.reconciliation
        test_position_reconciliation.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-reconciliation-ageing-test
        framework.financial_platform.reconciliation.ageing
        test_reconciliation_ageing.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-reconciliation-automation-test
        framework.financial_platform.reconciliation.automation
        test_reconciliation_automation.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-reconciliation-break-count-test
        framework.financial_platform.reconciliation.break.count
        test_reconciliation_break_count.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-reconciliation-completion-test
        framework.financial_platform.reconciliation.completion
        test_reconciliation_completion.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-reconciliation-coverage-test
        framework.financial_platform.reconciliation.coverage
        test_reconciliation_coverage.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-reconciliation-exception-test
        framework.financial_platform.reconciliation.exception
        test_reconciliation_exception.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-reconciliation-matching-test
        framework.financial_platform.reconciliation.matching
        test_reconciliation_matching.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-reconciliation-run-test
        framework.financial_platform.reconciliation.run
        test_reconciliation_run.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-reconciliation-tolerance-test
        framework.financial_platform.reconciliation.tolerance
        test_reconciliation_tolerance.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-relationship-store-test
        framework.financial_platform.relationship.store
        test_relationship_store.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-service-catalogue-test
        framework.financial_platform.service.catalogue
        test_service_catalogue.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-settlement-book-test
        framework.financial_platform.settlement.book
        test_settlement_book.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-settlement-cash-leg-test
        framework.financial_platform.settlement.cash.leg
        test_settlement_cash_leg.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-settlement-due-date-test
        framework.financial_platform.settlement.due.date
        test_settlement_due_date.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-settlement-fail-age-test
        framework.financial_platform.settlement.fail.age
        test_settlement_fail_age.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-settlement-instruction-test
        framework.financial_platform.settlement.instruction
        test_settlement_instruction.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-settlement-netting-test
        framework.financial_platform.settlement.netting
        test_settlement_netting.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-settlement-reconciliation-test
        framework.financial_platform.settlement.reconciliation
        test_settlement_reconciliation.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-settlement-securities-leg-test
        framework.financial_platform.settlement.securities.leg
        test_settlement_securities_leg.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-settlement-status-test
        framework.financial_platform.settlement.status
        test_settlement_status.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-trade-audit-coverage-test
        framework.financial_platform.trade.audit.coverage
        test_trade_audit_coverage.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-trade-control-book-test
        framework.financial_platform.trade.control.book
        test_trade_control_book.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-trade-counterparty-test
        framework.financial_platform.trade.counterparty
        test_trade_counterparty.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-trade-economics-test
        framework.financial_platform.trade.economics
        test_trade_economics.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-trade-identity-test
        framework.financial_platform.trade.identity
        test_trade_identity.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-trade-lifecycle-test
        framework.financial_platform.trade.lifecycle
        test_trade_lifecycle.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-trade-notional-test
        framework.financial_platform.trade.notional
        test_trade_notional.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-trade-position-impact-test
        framework.financial_platform.trade.position.impact
        test_trade_position_impact.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-trade-settlement-test
        framework.financial_platform.trade.settlement
        test_trade_settlement.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-types-test
        framework.financial_platform.types
        test_types.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-workflow-approval-test
        framework.financial_platform.workflow.approval
        test_workflow_approval.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-workflow-completion-test
        framework.financial_platform.workflow.completion
        test_workflow_completion.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-workflow-escalation-test
        framework.financial_platform.workflow.escalation
        test_workflow_escalation.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-workflow-instance-test
        framework.financial_platform.workflow.instance
        test_workflow_instance.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-workflow-role-coverage-test
        framework.financial_platform.workflow.role.coverage
        test_workflow_role_coverage.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-workflow-rollback-test
        framework.financial_platform.workflow.rollback
        test_workflow_rollback.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-workflow-state-transition-test
        framework.financial_platform.workflow.state.transition
        test_workflow_state_transition.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-workflow-task-coverage-test
        framework.financial_platform.workflow.task.coverage
        test_workflow_task_coverage.c
    )
    umicom_add_financial_platform_test(
        umicom-financial-platform-workflow-timeout-test
        framework.financial_platform.workflow.timeout
        test_workflow_timeout.c
    )
endif()

message(STATUS
    "Umicom shared financial platform core completion enabled")
