#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomUniversalDesignSystemPlatform.cmake
#
# PURPOSE:
#   Extend canonical Umicom::ui with typed design tokens, semantic component
#   specifications, responsive rules and cross-application design contracts.
#
# ARCHITECTURE:
#   Existing Umicom UI/component/workbench targets remain authoritative. This
#   layer adds semantic design data before GTK4, Qt6 and Native Web renderers.
#
# Created by: Sammy Hegab
# Organisation: Umicom Foundation
# Licence: MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_UI_DESIGN_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
if(NOT TARGET umicom_ui)
    message(FATAL_ERROR "UmicomUniversalDesignSystemPlatform.cmake requires canonical umicom_ui")
endif()

# Typed design-system capability extends the existing canonical UI target.
target_sources(umicom_ui PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/color.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/color_role.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/color_palette.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/typography.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/typography_scale.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/font_role.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/spacing_scale.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/radius_scale.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/elevation_scale.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/motion_scale.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/opacity_scale.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/density.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/size_class.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/breakpoint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/responsive_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/component_state.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/interaction_state.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/semantic_role.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/design_token.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/token_set.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/token_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/token_resolver.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/style_value.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/style_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/style_sheet.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/state_style.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/focus_ring.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/accessibility_contract.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/contrast.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/component_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/component_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/component_family.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/component_variant.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/component_size.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/component_capability.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/component_property.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/component_event.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/component_slot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/component_layout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/button_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/text_input_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/selection_control_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/menu_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/tab_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/toolbar_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/navigation_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/card_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/kpi_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/badge_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/alert_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/progress_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/form_field_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/dialog_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/list_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/table_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/tree_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/chart_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/gauge_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/heatmap_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/timeline_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/media_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/inspector_spec.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/design_system.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/application_brand.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/ui/design/conformance_profile.c"
)

# Contrast and colour-transfer calculations require the standard math library on Unix.
if(UNIX AND NOT APPLE)
    target_link_libraries(umicom_ui PRIVATE m)
endif()

if(BUILD_TESTING)
    function(umicom_add_ui_design_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_UI_DESIGN_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::ui)
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;ui-design;design-system;semantic-components")
    endfunction()

    umicom_add_ui_design_test(
        umicom-ui-design-types-test
        framework.ui_design.types
        tests/ui_design/test_types.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-color-test
        framework.ui_design.color
        tests/ui_design/test_color.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-color-role-test
        framework.ui_design.color.role
        tests/ui_design/test_color_role.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-color-palette-test
        framework.ui_design.color.palette
        tests/ui_design/test_color_palette.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-typography-test
        framework.ui_design.typography
        tests/ui_design/test_typography.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-typography-scale-test
        framework.ui_design.typography.scale
        tests/ui_design/test_typography_scale.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-font-role-test
        framework.ui_design.font.role
        tests/ui_design/test_font_role.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-spacing-scale-test
        framework.ui_design.spacing.scale
        tests/ui_design/test_spacing_scale.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-radius-scale-test
        framework.ui_design.radius.scale
        tests/ui_design/test_radius_scale.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-elevation-scale-test
        framework.ui_design.elevation.scale
        tests/ui_design/test_elevation_scale.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-motion-scale-test
        framework.ui_design.motion.scale
        tests/ui_design/test_motion_scale.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-opacity-scale-test
        framework.ui_design.opacity.scale
        tests/ui_design/test_opacity_scale.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-density-test
        framework.ui_design.density
        tests/ui_design/test_density.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-size-class-test
        framework.ui_design.size.class
        tests/ui_design/test_size_class.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-breakpoint-test
        framework.ui_design.breakpoint
        tests/ui_design/test_breakpoint.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-responsive-rule-test
        framework.ui_design.responsive.rule
        tests/ui_design/test_responsive_rule.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-component-state-test
        framework.ui_design.component.state
        tests/ui_design/test_component_state.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-interaction-state-test
        framework.ui_design.interaction.state
        tests/ui_design/test_interaction_state.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-semantic-role-test
        framework.ui_design.semantic.role
        tests/ui_design/test_semantic_role.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-design-token-test
        framework.ui_design.design.token
        tests/ui_design/test_design_token.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-token-set-test
        framework.ui_design.token.set
        tests/ui_design/test_token_set.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-token-registry-test
        framework.ui_design.token.registry
        tests/ui_design/test_token_registry.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-token-resolver-test
        framework.ui_design.token.resolver
        tests/ui_design/test_token_resolver.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-style-value-test
        framework.ui_design.style.value
        tests/ui_design/test_style_value.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-style-rule-test
        framework.ui_design.style.rule
        tests/ui_design/test_style_rule.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-style-sheet-test
        framework.ui_design.style.sheet
        tests/ui_design/test_style_sheet.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-state-style-test
        framework.ui_design.state.style
        tests/ui_design/test_state_style.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-focus-ring-test
        framework.ui_design.focus.ring
        tests/ui_design/test_focus_ring.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-accessibility-contract-test
        framework.ui_design.accessibility.contract
        tests/ui_design/test_accessibility_contract.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-contrast-test
        framework.ui_design.contrast
        tests/ui_design/test_contrast.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-component-descriptor-test
        framework.ui_design.component.descriptor
        tests/ui_design/test_component_descriptor.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-component-catalogue-test
        framework.ui_design.component.catalogue
        tests/ui_design/test_component_catalogue.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-component-family-test
        framework.ui_design.component.family
        tests/ui_design/test_component_family.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-component-variant-test
        framework.ui_design.component.variant
        tests/ui_design/test_component_variant.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-component-size-test
        framework.ui_design.component.size
        tests/ui_design/test_component_size.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-component-capability-test
        framework.ui_design.component.capability
        tests/ui_design/test_component_capability.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-component-property-test
        framework.ui_design.component.property
        tests/ui_design/test_component_property.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-component-event-test
        framework.ui_design.component.event
        tests/ui_design/test_component_event.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-component-slot-test
        framework.ui_design.component.slot
        tests/ui_design/test_component_slot.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-component-layout-test
        framework.ui_design.component.layout
        tests/ui_design/test_component_layout.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-button-spec-test
        framework.ui_design.button.spec
        tests/ui_design/test_button_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-text-input-spec-test
        framework.ui_design.text.input.spec
        tests/ui_design/test_text_input_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-selection-control-spec-test
        framework.ui_design.selection.control.spec
        tests/ui_design/test_selection_control_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-menu-spec-test
        framework.ui_design.menu.spec
        tests/ui_design/test_menu_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-tab-spec-test
        framework.ui_design.tab.spec
        tests/ui_design/test_tab_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-toolbar-spec-test
        framework.ui_design.toolbar.spec
        tests/ui_design/test_toolbar_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-navigation-spec-test
        framework.ui_design.navigation.spec
        tests/ui_design/test_navigation_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-card-spec-test
        framework.ui_design.card.spec
        tests/ui_design/test_card_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-kpi-spec-test
        framework.ui_design.kpi.spec
        tests/ui_design/test_kpi_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-badge-spec-test
        framework.ui_design.badge.spec
        tests/ui_design/test_badge_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-alert-spec-test
        framework.ui_design.alert.spec
        tests/ui_design/test_alert_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-progress-spec-test
        framework.ui_design.progress.spec
        tests/ui_design/test_progress_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-form-field-spec-test
        framework.ui_design.form.field.spec
        tests/ui_design/test_form_field_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-dialog-spec-test
        framework.ui_design.dialog.spec
        tests/ui_design/test_dialog_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-list-spec-test
        framework.ui_design.list.spec
        tests/ui_design/test_list_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-table-spec-test
        framework.ui_design.table.spec
        tests/ui_design/test_table_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-tree-spec-test
        framework.ui_design.tree.spec
        tests/ui_design/test_tree_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-chart-spec-test
        framework.ui_design.chart.spec
        tests/ui_design/test_chart_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-gauge-spec-test
        framework.ui_design.gauge.spec
        tests/ui_design/test_gauge_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-heatmap-spec-test
        framework.ui_design.heatmap.spec
        tests/ui_design/test_heatmap_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-timeline-spec-test
        framework.ui_design.timeline.spec
        tests/ui_design/test_timeline_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-media-spec-test
        framework.ui_design.media.spec
        tests/ui_design/test_media_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-inspector-spec-test
        framework.ui_design.inspector.spec
        tests/ui_design/test_inspector_spec.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-design-system-test
        framework.ui_design.design.system
        tests/ui_design/test_design_system.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-application-brand-test
        framework.ui_design.application.brand
        tests/ui_design/test_application_brand.c
    )
    umicom_add_ui_design_test(
        umicom-ui-design-conformance-profile-test
        framework.ui_design.conformance.profile
        tests/ui_design/test_conformance_profile.c
    )
endif()

message(STATUS "Umicom universal design system and semantic component catalogue enabled")
