# Registry and workspace translation units own the included history implementations.
if(BUILD_TESTING)
    function(umicom_history_cases group)
        set(target "umicom-drawing-history-${group}-test")
        add_executable(${target} "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/chart_history/test_${group}.c")
        target_link_libraries(${target} PRIVATE Umicom::trading_ui Umicom::trading_chart_persistence)
        umicom_apply_warnings(${target})
        umicom_apply_sanitizers(${target})
        foreach(case IN LISTS ARGN)
            add_test(NAME "framework.drawing_history.${group}.${case}" COMMAND ${target} "${case}")
            set_tests_properties("framework.drawing_history.${group}.${case}" PROPERTIES
                TIMEOUT 90 LABELS "framework;chart;regression")
        endforeach()
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(${target})
        endif()
    endfunction()
    umicom_history_cases(model empty create remove-order all-fields chain no-op-redo branch stale-revision other-pane external reset step-budget independent)
    umicom_history_cases(atomic failed-callback failed-redo wrong-pane reentry unchanged-order invalid-arguments full-registry oversize-step byte-budget)
    umicom_history_cases(workspace failed-first no-op move lock hidden appearance duplicate remove pane-hidden failed-edit selected-instrument restore-barrier save-redo stale-preview)
endif()
if(BUILD_TESTING AND TARGET Umicom::ui_gtk4)
    add_executable(umicom-drawing-history-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/chart_history/test_native.c")
    target_link_libraries(umicom-drawing-history-native-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-drawing-history-native-test)
    umicom_apply_sanitizers(umicom-drawing-history-native-test)
    foreach(case compact-inspector buttons key-y key-shift-z key-modifiers stale external instrument appearance-draft retained)
        add_test(NAME "framework.drawing_history.native.${case}" COMMAND umicom-drawing-history-native-test "${case}")
        set_tests_properties("framework.drawing_history.native.${case}" PROPERTIES
            TIMEOUT 60 SKIP_RETURN_CODE 77 LABELS "framework;chart;gtk4;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-drawing-history-native-test)
    endif()
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/CHART_DRAWING_HISTORY.md"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom-framework/docs)
