#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomHelixAutonomousEngineeringPlatform.cmake
#
# PURPOSE:
#   Extend the canonical developer platform with governed autonomous engineering, repair, regeneration, validation, rollback and software-evolution control-plane state.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_HELIX_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
if(NOT TARGET umicom_developer)
    message(FATAL_ERROR "UmicomHelixAutonomousEngineeringPlatform.cmake requires canonical umicom_developer")
endif()

# Helix composes existing developer/compiler/VCS/test/repository/observability services
# through stable evidence contracts; it does not duplicate their execution engines.
target_sources(umicom_developer PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/engineering_goal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/engineering_intent.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/scope_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/autonomy_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/autonomy_level.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/resource_budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/risk_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/risk_assessment.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/engineering_task.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/task_dependency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/plan_graph.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/engineering_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/plan_validator.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/change_request.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/file_change.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/change_set.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/patch_candidate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/patch_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/regeneration_request.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/regeneration_unit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/regeneration_graph.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/regeneration_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/repository_baseline.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/repository_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/workspace_fingerprint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/diagnostic_signal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/failure_classification.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/build_observation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/test_observation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/compiler_observation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/quality_observation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/repair_strategy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/repair_candidate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/repair_ranking.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/retry_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/feedback_event.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/feedback_loop.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/checkpoint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/checkpoint_store.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/validation_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/validation_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/validation_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/quality_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/safety_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/approval_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/execution_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/execution_step.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/execution_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/execution_session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/rollback_checkpoint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/rollback_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/rollback_decision.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/evolution_goal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/evolution_variant.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/evolution_generation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/fitness_score.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/selection_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/mutation_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/diversity_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/convergence_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/lineage_record.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/provenance_record.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/audit_event.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/helix_session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer/helix/helix_service.c"
)

if(BUILD_TESTING)
    function(umicom_add_helix_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_HELIX_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::Framework)
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;helix;autonomous-engineering")
    endfunction()

    umicom_add_helix_test(
        umicom-helix-types-test
        framework.helix.types
        tests/developer_helix/test_types.c
    )
    umicom_add_helix_test(
        umicom-helix-engineering-goal-test
        framework.helix.engineering.goal
        tests/developer_helix/test_engineering_goal.c
    )
    umicom_add_helix_test(
        umicom-helix-engineering-intent-test
        framework.helix.engineering.intent
        tests/developer_helix/test_engineering_intent.c
    )
    umicom_add_helix_test(
        umicom-helix-scope-policy-test
        framework.helix.scope.policy
        tests/developer_helix/test_scope_policy.c
    )
    umicom_add_helix_test(
        umicom-helix-autonomy-policy-test
        framework.helix.autonomy.policy
        tests/developer_helix/test_autonomy_policy.c
    )
    umicom_add_helix_test(
        umicom-helix-autonomy-level-test
        framework.helix.autonomy.level
        tests/developer_helix/test_autonomy_level.c
    )
    umicom_add_helix_test(
        umicom-helix-resource-budget-test
        framework.helix.resource.budget
        tests/developer_helix/test_resource_budget.c
    )
    umicom_add_helix_test(
        umicom-helix-risk-policy-test
        framework.helix.risk.policy
        tests/developer_helix/test_risk_policy.c
    )
    umicom_add_helix_test(
        umicom-helix-risk-assessment-test
        framework.helix.risk.assessment
        tests/developer_helix/test_risk_assessment.c
    )
    umicom_add_helix_test(
        umicom-helix-engineering-task-test
        framework.helix.engineering.task
        tests/developer_helix/test_engineering_task.c
    )
    umicom_add_helix_test(
        umicom-helix-task-dependency-test
        framework.helix.task.dependency
        tests/developer_helix/test_task_dependency.c
    )
    umicom_add_helix_test(
        umicom-helix-plan-graph-test
        framework.helix.plan.graph
        tests/developer_helix/test_plan_graph.c
    )
    umicom_add_helix_test(
        umicom-helix-engineering-plan-test
        framework.helix.engineering.plan
        tests/developer_helix/test_engineering_plan.c
    )
    umicom_add_helix_test(
        umicom-helix-plan-validator-test
        framework.helix.plan.validator
        tests/developer_helix/test_plan_validator.c
    )
    umicom_add_helix_test(
        umicom-helix-change-request-test
        framework.helix.change.request
        tests/developer_helix/test_change_request.c
    )
    umicom_add_helix_test(
        umicom-helix-file-change-test
        framework.helix.file.change
        tests/developer_helix/test_file_change.c
    )
    umicom_add_helix_test(
        umicom-helix-change-set-test
        framework.helix.change.set
        tests/developer_helix/test_change_set.c
    )
    umicom_add_helix_test(
        umicom-helix-patch-candidate-test
        framework.helix.patch.candidate
        tests/developer_helix/test_patch_candidate.c
    )
    umicom_add_helix_test(
        umicom-helix-patch-plan-test
        framework.helix.patch.plan
        tests/developer_helix/test_patch_plan.c
    )
    umicom_add_helix_test(
        umicom-helix-regeneration-request-test
        framework.helix.regeneration.request
        tests/developer_helix/test_regeneration_request.c
    )
    umicom_add_helix_test(
        umicom-helix-regeneration-unit-test
        framework.helix.regeneration.unit
        tests/developer_helix/test_regeneration_unit.c
    )
    umicom_add_helix_test(
        umicom-helix-regeneration-graph-test
        framework.helix.regeneration.graph
        tests/developer_helix/test_regeneration_graph.c
    )
    umicom_add_helix_test(
        umicom-helix-regeneration-policy-test
        framework.helix.regeneration.policy
        tests/developer_helix/test_regeneration_policy.c
    )
    umicom_add_helix_test(
        umicom-helix-repository-baseline-test
        framework.helix.repository.baseline
        tests/developer_helix/test_repository_baseline.c
    )
    umicom_add_helix_test(
        umicom-helix-repository-snapshot-test
        framework.helix.repository.snapshot
        tests/developer_helix/test_repository_snapshot.c
    )
    umicom_add_helix_test(
        umicom-helix-workspace-fingerprint-test
        framework.helix.workspace.fingerprint
        tests/developer_helix/test_workspace_fingerprint.c
    )
    umicom_add_helix_test(
        umicom-helix-diagnostic-signal-test
        framework.helix.diagnostic.signal
        tests/developer_helix/test_diagnostic_signal.c
    )
    umicom_add_helix_test(
        umicom-helix-failure-classification-test
        framework.helix.failure.classification
        tests/developer_helix/test_failure_classification.c
    )
    umicom_add_helix_test(
        umicom-helix-build-observation-test
        framework.helix.build.observation
        tests/developer_helix/test_build_observation.c
    )
    umicom_add_helix_test(
        umicom-helix-test-observation-test
        framework.helix.test.observation
        tests/developer_helix/test_test_observation.c
    )
    umicom_add_helix_test(
        umicom-helix-compiler-observation-test
        framework.helix.compiler.observation
        tests/developer_helix/test_compiler_observation.c
    )
    umicom_add_helix_test(
        umicom-helix-quality-observation-test
        framework.helix.quality.observation
        tests/developer_helix/test_quality_observation.c
    )
    umicom_add_helix_test(
        umicom-helix-repair-strategy-test
        framework.helix.repair.strategy
        tests/developer_helix/test_repair_strategy.c
    )
    umicom_add_helix_test(
        umicom-helix-repair-candidate-test
        framework.helix.repair.candidate
        tests/developer_helix/test_repair_candidate.c
    )
    umicom_add_helix_test(
        umicom-helix-repair-ranking-test
        framework.helix.repair.ranking
        tests/developer_helix/test_repair_ranking.c
    )
    umicom_add_helix_test(
        umicom-helix-retry-policy-test
        framework.helix.retry.policy
        tests/developer_helix/test_retry_policy.c
    )
    umicom_add_helix_test(
        umicom-helix-feedback-event-test
        framework.helix.feedback.event
        tests/developer_helix/test_feedback_event.c
    )
    umicom_add_helix_test(
        umicom-helix-feedback-loop-test
        framework.helix.feedback.loop
        tests/developer_helix/test_feedback_loop.c
    )
    umicom_add_helix_test(
        umicom-helix-checkpoint-test
        framework.helix.checkpoint
        tests/developer_helix/test_checkpoint.c
    )
    umicom_add_helix_test(
        umicom-helix-checkpoint-store-test
        framework.helix.checkpoint.store
        tests/developer_helix/test_checkpoint_store.c
    )
    umicom_add_helix_test(
        umicom-helix-validation-gate-test
        framework.helix.validation.gate
        tests/developer_helix/test_validation_gate.c
    )
    umicom_add_helix_test(
        umicom-helix-validation-plan-test
        framework.helix.validation.plan
        tests/developer_helix/test_validation_plan.c
    )
    umicom_add_helix_test(
        umicom-helix-validation-result-test
        framework.helix.validation.result
        tests/developer_helix/test_validation_result.c
    )
    umicom_add_helix_test(
        umicom-helix-quality-gate-test
        framework.helix.quality.gate
        tests/developer_helix/test_quality_gate.c
    )
    umicom_add_helix_test(
        umicom-helix-safety-gate-test
        framework.helix.safety.gate
        tests/developer_helix/test_safety_gate.c
    )
    umicom_add_helix_test(
        umicom-helix-approval-gate-test
        framework.helix.approval.gate
        tests/developer_helix/test_approval_gate.c
    )
    umicom_add_helix_test(
        umicom-helix-execution-policy-test
        framework.helix.execution.policy
        tests/developer_helix/test_execution_policy.c
    )
    umicom_add_helix_test(
        umicom-helix-execution-step-test
        framework.helix.execution.step
        tests/developer_helix/test_execution_step.c
    )
    umicom_add_helix_test(
        umicom-helix-execution-plan-test
        framework.helix.execution.plan
        tests/developer_helix/test_execution_plan.c
    )
    umicom_add_helix_test(
        umicom-helix-execution-session-test
        framework.helix.execution.session
        tests/developer_helix/test_execution_session.c
    )
    umicom_add_helix_test(
        umicom-helix-rollback-checkpoint-test
        framework.helix.rollback.checkpoint
        tests/developer_helix/test_rollback_checkpoint.c
    )
    umicom_add_helix_test(
        umicom-helix-rollback-plan-test
        framework.helix.rollback.plan
        tests/developer_helix/test_rollback_plan.c
    )
    umicom_add_helix_test(
        umicom-helix-rollback-decision-test
        framework.helix.rollback.decision
        tests/developer_helix/test_rollback_decision.c
    )
    umicom_add_helix_test(
        umicom-helix-evolution-goal-test
        framework.helix.evolution.goal
        tests/developer_helix/test_evolution_goal.c
    )
    umicom_add_helix_test(
        umicom-helix-evolution-variant-test
        framework.helix.evolution.variant
        tests/developer_helix/test_evolution_variant.c
    )
    umicom_add_helix_test(
        umicom-helix-evolution-generation-test
        framework.helix.evolution.generation
        tests/developer_helix/test_evolution_generation.c
    )
    umicom_add_helix_test(
        umicom-helix-fitness-score-test
        framework.helix.fitness.score
        tests/developer_helix/test_fitness_score.c
    )
    umicom_add_helix_test(
        umicom-helix-selection-policy-test
        framework.helix.selection.policy
        tests/developer_helix/test_selection_policy.c
    )
    umicom_add_helix_test(
        umicom-helix-mutation-policy-test
        framework.helix.mutation.policy
        tests/developer_helix/test_mutation_policy.c
    )
    umicom_add_helix_test(
        umicom-helix-diversity-policy-test
        framework.helix.diversity.policy
        tests/developer_helix/test_diversity_policy.c
    )
    umicom_add_helix_test(
        umicom-helix-convergence-policy-test
        framework.helix.convergence.policy
        tests/developer_helix/test_convergence_policy.c
    )
    umicom_add_helix_test(
        umicom-helix-lineage-record-test
        framework.helix.lineage.record
        tests/developer_helix/test_lineage_record.c
    )
    umicom_add_helix_test(
        umicom-helix-provenance-record-test
        framework.helix.provenance.record
        tests/developer_helix/test_provenance_record.c
    )
    umicom_add_helix_test(
        umicom-helix-audit-event-test
        framework.helix.audit.event
        tests/developer_helix/test_audit_event.c
    )
    umicom_add_helix_test(
        umicom-helix-helix-session-test
        framework.helix.helix.session
        tests/developer_helix/test_helix_session.c
    )
    umicom_add_helix_test(
        umicom-helix-helix-service-test
        framework.helix.helix.service
        tests/developer_helix/test_helix_service.c
    )
endif()

message(STATUS "Umicom Helix governed autonomous engineering platform enabled")
