# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
set(_umi_interest_root "${CMAKE_CURRENT_LIST_DIR}/..")
if(BUILD_TESTING)
    foreach(kind IN ITEMS calculation workflow storage)
        add_executable(umicom-bank-interest-${kind}-test "${_umi_interest_root}/tests/bank_interest/test_${kind}.c")
        target_link_libraries(umicom-bank-interest-${kind}-test PRIVATE Umicom::bank_operations)
        umicom_bank_review_target(umicom-bank-interest-${kind}-test)
    endforeach()
    foreach(case IN ITEMS rounding large overflow invalid)
        add_test(NAME framework.bank_interest.calculation.${case} COMMAND umicom-bank-interest-calculation-test ${case})
    endforeach()
    foreach(case IN ITEMS lifecycle fixed-principal invalid authority duplicate cancel-reject blocked funds overflow post-overflow close-pending capacity review stale-review)
        add_test(NAME framework.bank_interest.workflow.${case} COMMAND umicom-bank-interest-workflow-test ${case})
        set_tests_properties(framework.bank_interest.workflow.${case} PROPERTIES TIMEOUT 45 LABELS "bank;interest;regression")
    endforeach()
    foreach(case IN ITEMS restart write-failure stale-writer codec)
        add_test(NAME framework.bank_interest.storage.${case} COMMAND umicom-bank-interest-storage-test ${case}
            "${CMAKE_CURRENT_BINARY_DIR}/bank-interest-${case}.sqlite")
        set_tests_properties(framework.bank_interest.storage.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77 LABELS "bank;interest;sqlite;regression")
    endforeach()
endif()
unset(_umi_interest_root)

if(BUILD_TESTING)
    add_executable(umicom-bank-statement-text-test "${CMAKE_CURRENT_LIST_DIR}/../tests/bank_interest/test_statement.c")
    target_link_libraries(umicom-bank-statement-text-test PRIVATE Umicom::bank_operations)
    umicom_bank_review_target(umicom-bank-statement-text-test)
    foreach(case IN ITEMS range empty capacity invalid reversal snapshot)
        add_test(NAME framework.bank_interest.statement.${case} COMMAND umicom-bank-statement-text-test ${case})
        set_tests_properties(framework.bank_interest.statement.${case} PROPERTIES TIMEOUT 30 LABELS "bank;statement;regression")
    endforeach()
    if(TARGET Umicom::bank_operations_gtk4)
        add_executable(umicom-bank-interest-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/bank_interest/test_native.c")
        target_link_libraries(umicom-bank-interest-native-test PRIVATE Umicom::bank_operations Umicom::ui_gtk4)
        umicom_bank_review_target(umicom-bank-interest-native-test)
        foreach(case IN ITEMS form invalidation invalid close posting reverse statement)
            add_test(NAME framework.bank_interest.native.${case} COMMAND umicom-bank-interest-native-test ${case})
            set_tests_properties(framework.bank_interest.native.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77 LABELS "bank;interest;gtk4;regression")
        endforeach()
    endif()
endif()
