# Creator: Sammy Hegab | Umicom Foundation | MIT
function(umicom_add_developer_capability_tests)
    umicom_add_framework_test(umicom-developer-capabilities-01 framework.developer.capabilities.01 tests/developer_capabilities/test_developer_capabilities_01.c)
    umicom_add_framework_test(umicom-developer-capabilities-02 framework.developer.capabilities.02 tests/developer_capabilities/test_developer_capabilities_02.c)
    umicom_add_framework_test(umicom-developer-capabilities-03 framework.developer.capabilities.03 tests/developer_capabilities/test_developer_capabilities_03.c)
    umicom_add_framework_test(umicom-developer-capabilities-04 framework.developer.capabilities.04 tests/developer_capabilities/test_developer_capabilities_04.c)
    umicom_add_framework_test(umicom-developer-capabilities-05 framework.developer.capabilities.05 tests/developer_capabilities/test_developer_capabilities_05.c)
    umicom_add_framework_test(umicom-developer-capabilities-06 framework.developer.capabilities.06 tests/developer_capabilities/test_developer_capabilities_06.c)
    umicom_add_framework_test(umicom-developer-capabilities-07 framework.developer.capabilities.07 tests/developer_capabilities/test_developer_capabilities_07.c)
    umicom_add_framework_test(umicom-developer-capabilities-08 framework.developer.capabilities.08 tests/developer_capabilities/test_developer_capabilities_08.c)
    umicom_add_framework_test(umicom-developer-capabilities-09 framework.developer.capabilities.09 tests/developer_capabilities/test_developer_capabilities_09.c)
    umicom_add_framework_test(umicom-developer-capabilities-10 framework.developer.capabilities.10 tests/developer_capabilities/test_developer_capabilities_10.c)
    umicom_add_framework_test(umicom-developer-capabilities-11 framework.developer.capabilities.11 tests/developer_capabilities/test_developer_capabilities_11.c)
    umicom_add_framework_test(umicom-developer-capabilities-12 framework.developer.capabilities.12 tests/developer_capabilities/test_developer_capabilities_12.c)
    umicom_add_framework_test(umicom-developer-capabilities-13 framework.developer.capabilities.13 tests/developer_capabilities/test_developer_capabilities_13.c)
    umicom_add_framework_test(umicom-developer-capabilities-14 framework.developer.capabilities.14 tests/developer_capabilities/test_developer_capabilities_14.c)
    umicom_add_framework_test(umicom-developer-capabilities-15 framework.developer.capabilities.15 tests/developer_capabilities/test_developer_capabilities_15.c)
    umicom_add_framework_test(umicom-developer-capabilities-16 framework.developer.capabilities.16 tests/developer_capabilities/test_developer_capabilities_16.c)
    umicom_add_framework_test(umicom-developer-capabilities-17 framework.developer.capabilities.17 tests/developer_capabilities/test_developer_capabilities_17.c)
    umicom_add_framework_test(umicom-developer-capabilities-18 framework.developer.capabilities.18 tests/developer_capabilities/test_developer_capabilities_18.c)
    umicom_add_framework_test(umicom-developer-capabilities-19 framework.developer.capabilities.19 tests/developer_capabilities/test_developer_capabilities_19.c)
    umicom_add_framework_test(umicom-developer-capabilities-20 framework.developer.capabilities.20 tests/developer_capabilities/test_developer_capabilities_20.c)
    umicom_add_framework_test(umicom-developer-capabilities-21 framework.developer.capabilities.21 tests/developer_capabilities/test_developer_capabilities_21.c)
    umicom_add_framework_test(umicom-developer-capabilities-22 framework.developer.capabilities.22 tests/developer_capabilities/test_developer_capabilities_22.c)
    umicom_add_framework_test(umicom-developer-capabilities-23 framework.developer.capabilities.23 tests/developer_capabilities/test_developer_capabilities_23.c)
    umicom_add_framework_test(umicom-developer-capabilities-24 framework.developer.capabilities.24 tests/developer_capabilities/test_developer_capabilities_24.c)
endfunction()
