# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-recovery-budget-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_recovery_budget.c")
    target_link_libraries(umicom-recovery-budget-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-recovery-budget-test)
    umicom_apply_sanitizers(umicom-recovery-budget-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-recovery-budget-test)
    endif()
    foreach(case admit exact-bytes short-bytes record-limit existing-bytes oversized-existing invalid-count invalid-budget invalid-maximum cancelled)
        add_test(NAME framework.document.recovery_budget.${case} COMMAND umicom-recovery-budget-test ${case})
        set_tests_properties(framework.document.recovery_budget.${case} PROPERTIES TIMEOUT 45 LABELS "framework;document;recovery;scheduling;regression")
    endforeach()
endif()
