# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Shared image generation owns provider requests; native products compose its UI.
include_guard(GLOBAL)
include(GNUInstallDirs)
set(_umicom_seedream_root "${CMAKE_CURRENT_LIST_DIR}/..")
add_library(umicom_seedream STATIC
    "${_umicom_seedream_root}/src/media_generation/seedream_plan.c"
    "${_umicom_seedream_root}/src/media_generation/seedream_response.c"
    "${_umicom_seedream_root}/src/media_generation/seedream_http.c")
add_library(Umicom::seedream ALIAS umicom_seedream)
set_target_properties(umicom_seedream PROPERTIES EXPORT_NAME seedream C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
target_include_directories(umicom_seedream PUBLIC $<BUILD_INTERFACE:${_umicom_seedream_root}/include> $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
target_link_libraries(umicom_seedream PUBLIC Umicom::security Umicom::platform Umicom::png_image PRIVATE Umicom::developer Umicom::ai)
if(UMICOM_PROVIDER_CONNECTION_CHECK_HTTP_BUILT)
    target_compile_definitions(umicom_seedream PRIVATE UMICOM_SEEDREAM_HAS_HTTP=1)
    target_link_libraries(umicom_seedream PRIVATE PkgConfig::UMICOM_CONNECTION_CHECK_CURL)
endif()
umicom_apply_warnings(umicom_seedream)
umicom_apply_sanitizers(umicom_seedream)
target_link_libraries(umicom_framework INTERFACE Umicom::seedream)
install(TARGETS umicom_seedream EXPORT UmicomFrameworkTargets ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT Framework)
if(TARGET umicom_ui_gtk4)
    target_sources(umicom_ui_gtk4 PRIVATE "${_umicom_seedream_root}/adapters/gtk4/seedream_panel_gtk4.c")
    target_link_libraries(umicom_ui_gtk4 PUBLIC Umicom::seedream)
endif()

# Each executable uses deterministic local fixtures, never a real account/key.
function(umicom_seedream_checks name source owner)
    add_executable(${name} "${_umicom_seedream_root}/tests/media_generation/${source}")
    target_link_libraries(${name} PRIVATE ${owner})
    umicom_apply_warnings(${name})
    umicom_apply_sanitizers(${name})
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(${name})
    endif()
endfunction()
if(BUILD_TESTING)
    umicom_seedream_checks(umicom-seedream-test test_seedream.c Umicom::seedream)
    foreach(case success single-use immutable quoted-prompt prompt-limit empty-prompt unterminated invalid-utf8 invalid-model unapproved header-injection cancel-before cancel-response timeout redirect denied rate-limit overflow empty pad-bits bad-padding bad-alphabet non-png base64-length url-only wrong-format duplicate-data provider-error multiple wrong-data-type duplicate-image duplicate-model wrong-image-type escaped-nul image-error trailing embedded-nul)
        add_test(NAME framework.seedream.${case} COMMAND umicom-seedream-test ${case})
        set_tests_properties(framework.seedream.${case} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;media;seedream;privacy;regression")
    endforeach()
    if(UMICOM_PROVIDER_CONNECTION_CHECK_HTTP_BUILT)
        umicom_seedream_checks(umicom-seedream-http-test test_seedream_http.c Umicom::seedream)
        target_compile_definitions(umicom-seedream-http-test PRIVATE UMICOM_SEEDREAM_HAS_HTTP=1)
        target_link_libraries(umicom-seedream-http-test PRIVATE PkgConfig::UMICOM_CONNECTION_CHECK_CURL)
        foreach(case post redirect denied rate-limit timeout cancel overflow option-failure)
            add_test(NAME framework.seedream.http.${case} COMMAND umicom-seedream-http-test ${case})
            set_tests_properties(framework.seedream.http.${case} PROPERTIES TIMEOUT 20 LABELS "framework;media;seedream;http;privacy;regression")
        endforeach()
    endif()
    if(TARGET umicom_ui_gtk4)
        umicom_seedream_checks(umicom-seedream-gtk-test test_seedream_gtk4.c Umicom::ui_gtk4)
        foreach(case review unapproved model password alias prompt retained save-empty)
            add_test(NAME framework.seedream.gtk.${case} COMMAND umicom-seedream-gtk-test ${case})
            set_tests_properties(framework.seedream.gtk.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77 LABELS "framework;media;seedream;gtk4;ownership;regression")
        endforeach()
    endif()
endif()
install(FILES "${_umicom_seedream_root}/docs/learning/seedream-image-requests.html"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/learning COMPONENT Learning)
