# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_snippet_storage_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-snippet-storage-gtk4-test)
        return()
    endif()
    add_executable(umicom-snippet-storage-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_snippet_storage_gtk4.c")
    target_link_libraries(umicom-snippet-storage-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-snippet-storage-gtk4-test)
    umicom_apply_sanitizers(umicom-snippet-storage-gtk4-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-snippet-storage-gtk4-test)
    endif()
    foreach(case open creation-unbind save load load-apply load-expire-prepared save-before-expand overwrite unicode name-change body-change value-change save-stale worker-unbind worker-close retained missing malformed wrong-language wrong-id blank-name oversized-name load-retire busy save-start-retire)
        add_test(NAME framework.document.snippet_storage.gtk4.${case}
            COMMAND umicom-snippet-storage-gtk4-test ${case})
        set_tests_properties(framework.document.snippet_storage.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77
            LABELS "framework;document;editor;snippet;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_snippet_storage_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_snippet_storage_checks)
endif()
