# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-delimiter-commands-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_delimiter_commands.c")
    target_link_libraries(umicom-delimiter-commands-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-delimiter-commands-test)
    umicom_apply_sanitizers(umicom-delimiter-commands-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-delimiter-commands-test)
    endif()
    foreach(case match contents pair metadata prefix argument read-only c-profile json-profile unknown-profile no-document active-invalid message-bounds)
        add_test(NAME framework.document.delimiter.command.${case} COMMAND umicom-delimiter-commands-test ${case})
        set_tests_properties(framework.document.delimiter.command.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;delimiter;navigation;regression")
    endforeach()
endif()
