#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomCommodityDigitalAssetPlatform.cmake
#
# PURPOSE:
#   Extend canonical Umicom::finance with reusable physical commodity delivery,
#   logistics, inventory, digital-asset network, custody and transfer contracts.
#
# ARCHITECTURE:
#   Existing finance and trading targets remain authoritative. Commodity and
#   digital-asset semantics are implemented once in Framework while Trader,
#   Exchange, Bank, TMS and future products remain thin compositions.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_COMMODITY_DIGITAL_ASSET_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")

# Load the dependency only when the parent build has not already provided its target.
if(NOT TARGET umicom_finance)
    message(FATAL_ERROR "UmicomCommodityDigitalAssetPlatform.cmake requires canonical umicom_finance")
endif()

# Physical and digital-asset financial semantics extend the shared finance target.
target_sources(umicom_finance PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/commodity_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/commodity_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/grade_specification.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/quality_measure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/quality_specification.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/location.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/location_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/storage_facility.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/inventory_lot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/storage_inventory.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/inventory_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/unit_of_measure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/unit_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/quantity_conversion.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/loss_allowance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/storage_cost.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/transport_mode.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/transport_route.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/transport_leg.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/shipment.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/shipment_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/nomination.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/nomination_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/delivery_obligation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/delivery_schedule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/delivery_window.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/delivery_status.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/physical_contract.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/contract_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/transport_cost.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/physical_exposure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/commodity_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/commodity/commodity_service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/network_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/network_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/asset_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/asset_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/address.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/wallet.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/wallet_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/custody_account.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/custody_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/token_balance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/balance_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/transaction.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/transaction_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/transaction_status.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/confirmation_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/fee_quote.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/network_fee.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/key_reference.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/signing_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/signing_request.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/signing_session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/transfer_instruction.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/transfer_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/deposit_address.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/withdrawal_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/chain_observation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/block_reference.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/settlement_finality.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/digital_market.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/digital_market_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/digital_asset/digital_asset_service.c"
)

# Register verification targets only when the developer has enabled testing.
if(BUILD_TESTING)
    # Define the add commodity digital asset test build helper so parent and application
    # projects apply one consistent rule.
    function(umicom_add_commodity_digital_asset_test target test_name source domain_label)
        # Configure the optional target only when its feature has created it.
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_COMMODITY_DIGITAL_ASSET_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::finance)
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;${domain_label}")
    endfunction()

    umicom_add_commodity_digital_asset_test(
        umicom-commodity-types-test
        framework.commodity.types
        tests/finance_commodity/test_types.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-commodity-descriptor-test
        framework.commodity.commodity.descriptor
        tests/finance_commodity/test_commodity_descriptor.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-commodity-catalogue-test
        framework.commodity.commodity.catalogue
        tests/finance_commodity/test_commodity_catalogue.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-grade-specification-test
        framework.commodity.grade.specification
        tests/finance_commodity/test_grade_specification.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-quality-measure-test
        framework.commodity.quality.measure
        tests/finance_commodity/test_quality_measure.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-quality-specification-test
        framework.commodity.quality.specification
        tests/finance_commodity/test_quality_specification.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-location-test
        framework.commodity.location
        tests/finance_commodity/test_location.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-location-catalogue-test
        framework.commodity.location.catalogue
        tests/finance_commodity/test_location_catalogue.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-storage-facility-test
        framework.commodity.storage.facility
        tests/finance_commodity/test_storage_facility.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-inventory-lot-test
        framework.commodity.inventory.lot
        tests/finance_commodity/test_inventory_lot.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-storage-inventory-test
        framework.commodity.storage.inventory
        tests/finance_commodity/test_storage_inventory.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-inventory-book-test
        framework.commodity.inventory.book
        tests/finance_commodity/test_inventory_book.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-unit-of-measure-test
        framework.commodity.unit.of.measure
        tests/finance_commodity/test_unit_of_measure.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-unit-catalogue-test
        framework.commodity.unit.catalogue
        tests/finance_commodity/test_unit_catalogue.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-quantity-conversion-test
        framework.commodity.quantity.conversion
        tests/finance_commodity/test_quantity_conversion.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-loss-allowance-test
        framework.commodity.loss.allowance
        tests/finance_commodity/test_loss_allowance.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-storage-cost-test
        framework.commodity.storage.cost
        tests/finance_commodity/test_storage_cost.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-transport-mode-test
        framework.commodity.transport.mode
        tests/finance_commodity/test_transport_mode.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-transport-route-test
        framework.commodity.transport.route
        tests/finance_commodity/test_transport_route.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-transport-leg-test
        framework.commodity.transport.leg
        tests/finance_commodity/test_transport_leg.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-shipment-test
        framework.commodity.shipment
        tests/finance_commodity/test_shipment.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-shipment-book-test
        framework.commodity.shipment.book
        tests/finance_commodity/test_shipment_book.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-nomination-test
        framework.commodity.nomination
        tests/finance_commodity/test_nomination.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-nomination-book-test
        framework.commodity.nomination.book
        tests/finance_commodity/test_nomination_book.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-delivery-obligation-test
        framework.commodity.delivery.obligation
        tests/finance_commodity/test_delivery_obligation.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-delivery-schedule-test
        framework.commodity.delivery.schedule
        tests/finance_commodity/test_delivery_schedule.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-delivery-window-test
        framework.commodity.delivery.window
        tests/finance_commodity/test_delivery_window.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-delivery-status-test
        framework.commodity.delivery.status
        tests/finance_commodity/test_delivery_status.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-physical-contract-test
        framework.commodity.physical.contract
        tests/finance_commodity/test_physical_contract.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-contract-book-test
        framework.commodity.contract.book
        tests/finance_commodity/test_contract_book.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-transport-cost-test
        framework.commodity.transport.cost
        tests/finance_commodity/test_transport_cost.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-physical-exposure-test
        framework.commodity.physical.exposure
        tests/finance_commodity/test_physical_exposure.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-commodity-snapshot-test
        framework.commodity.commodity.snapshot
        tests/finance_commodity/test_commodity_snapshot.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-commodity-commodity-service-test
        framework.commodity.commodity.service
        tests/finance_commodity/test_commodity_service.c
        commodity-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-types-test
        framework.digital.asset.types
        tests/finance_digital_asset/test_types.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-network-descriptor-test
        framework.digital.asset.network.descriptor
        tests/finance_digital_asset/test_network_descriptor.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-network-catalogue-test
        framework.digital.asset.network.catalogue
        tests/finance_digital_asset/test_network_catalogue.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-asset-descriptor-test
        framework.digital.asset.asset.descriptor
        tests/finance_digital_asset/test_asset_descriptor.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-asset-catalogue-test
        framework.digital.asset.asset.catalogue
        tests/finance_digital_asset/test_asset_catalogue.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-address-test
        framework.digital.asset.address
        tests/finance_digital_asset/test_address.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-wallet-test
        framework.digital.asset.wallet
        tests/finance_digital_asset/test_wallet.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-wallet-book-test
        framework.digital.asset.wallet.book
        tests/finance_digital_asset/test_wallet_book.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-custody-account-test
        framework.digital.asset.custody.account
        tests/finance_digital_asset/test_custody_account.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-custody-book-test
        framework.digital.asset.custody.book
        tests/finance_digital_asset/test_custody_book.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-token-balance-test
        framework.digital.asset.token.balance
        tests/finance_digital_asset/test_token_balance.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-balance-book-test
        framework.digital.asset.balance.book
        tests/finance_digital_asset/test_balance_book.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-transaction-test
        framework.digital.asset.transaction
        tests/finance_digital_asset/test_transaction.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-transaction-book-test
        framework.digital.asset.transaction.book
        tests/finance_digital_asset/test_transaction_book.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-transaction-status-test
        framework.digital.asset.transaction.status
        tests/finance_digital_asset/test_transaction_status.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-confirmation-policy-test
        framework.digital.asset.confirmation.policy
        tests/finance_digital_asset/test_confirmation_policy.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-fee-quote-test
        framework.digital.asset.fee.quote
        tests/finance_digital_asset/test_fee_quote.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-network-fee-test
        framework.digital.asset.network.fee
        tests/finance_digital_asset/test_network_fee.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-key-reference-test
        framework.digital.asset.key.reference
        tests/finance_digital_asset/test_key_reference.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-signing-policy-test
        framework.digital.asset.signing.policy
        tests/finance_digital_asset/test_signing_policy.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-signing-request-test
        framework.digital.asset.signing.request
        tests/finance_digital_asset/test_signing_request.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-signing-session-test
        framework.digital.asset.signing.session
        tests/finance_digital_asset/test_signing_session.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-transfer-instruction-test
        framework.digital.asset.transfer.instruction
        tests/finance_digital_asset/test_transfer_instruction.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-transfer-book-test
        framework.digital.asset.transfer.book
        tests/finance_digital_asset/test_transfer_book.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-deposit-address-test
        framework.digital.asset.deposit.address
        tests/finance_digital_asset/test_deposit_address.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-withdrawal-policy-test
        framework.digital.asset.withdrawal.policy
        tests/finance_digital_asset/test_withdrawal_policy.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-chain-observation-test
        framework.digital.asset.chain.observation
        tests/finance_digital_asset/test_chain_observation.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-block-reference-test
        framework.digital.asset.block.reference
        tests/finance_digital_asset/test_block_reference.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-settlement-finality-test
        framework.digital.asset.settlement.finality
        tests/finance_digital_asset/test_settlement_finality.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-digital-market-test
        framework.digital.asset.digital.market
        tests/finance_digital_asset/test_digital_market.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-digital-market-catalogue-test
        framework.digital.asset.digital.market.catalogue
        tests/finance_digital_asset/test_digital_market_catalogue.c
        digital-asset-core
    )
    umicom_add_commodity_digital_asset_test(
        umicom-digital-asset-digital-asset-service-test
        framework.digital.asset.digital.asset.service
        tests/finance_digital_asset/test_digital_asset_service.c
        digital-asset-core
    )
endif()

message(STATUS
    "Umicom commodity physical-delivery and digital-asset platform core enabled")
