# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-creative-asset-archive-test "${CMAKE_CURRENT_LIST_DIR}/../tests/creative_assets/test_archive.c")
    target_link_libraries(umicom-creative-asset-archive-test PRIVATE Umicom::creative_workspace Umicom::native_launcher)
    umicom_creative_configure_target(umicom-creative-asset-archive-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-creative-asset-archive-test)
    endif()
    foreach(case roundtrip binary empty purposes unicode-label longest-label chunked deterministic fixture truncated trailing magic schema reserved kind empty-label long-label nul-label utf8-label control-label oversized-payload wrong-size corrupt-payload corrupt-digest cancelled-encode cancelled-decode live-output invalid-arguments)
        add_test(NAME framework.creative_assets.archive.${case} COMMAND umicom-creative-asset-archive-test ${case})
        set_tests_properties(framework.creative_assets.archive.${case} PROPERTIES TIMEOUT 30 LABELS "framework;creative-assets;archive;regression")
    endforeach()
endif()
