#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomStrategyResearchPlatform.cmake
#
# PURPOSE:
#   Compose deterministic strategy coding, backtesting, replay, performance
#   analysis, optimisation, studies and simulation evidence over canonical
#   trading/chart/replay services.
#
# ARCHITECTURE:
#   Research remains strictly non-live. Existing trading workspace, risk,
#   market-data, replay and chart engines remain authoritative; this target
#   adds deterministic analysis and research orchestration only.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

if(NOT TARGET umicom_trading_ui)
    message(FATAL_ERROR
        "Strategy Research Platform requires canonical umicom_trading_ui")
endif()

target_sources(umicom_trading_ui PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/strategy_research_internal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest_engine.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/replay_engine.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/optimisation_engine.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study_series.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/simulation_evidence.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/strategy_project.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/average_loss.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/average_win.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/expectancy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/exposure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/gross_loss.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/gross_profit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/loss_streak.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/max_drawdown.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/net_profit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/profit_factor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/recovery_factor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/trade_count.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/turnover.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/win_rate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/backtest/win_streak.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/optimisation/budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/optimisation/candidate_rank.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/optimisation/early_stop.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/optimisation/objective.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/optimisation/overfit_gap.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/optimisation/pareto.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/optimisation/robustness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/optimisation/sensitivity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/optimisation/stability.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/optimisation/walk_forward.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/performance/annualised_return.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/performance/annualised_volatility.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/performance/calmar.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/performance/downside_deviation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/performance/payoff_ratio.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/performance/sharpe.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/performance/sortino.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/performance/stability.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/performance/trade_efficiency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/performance/ulcer_index.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/replay/checkpoint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/replay/clock_drift.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/replay/data_quality.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/replay/event_rate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/replay/gap_count.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/replay/gap_ratio.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/replay/progress.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/replay/readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/replay/seek_distance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/replay/speed.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/simulation/cash_change.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/simulation/commission.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/simulation/evidence_quality.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/simulation/fill_ratio.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/simulation/latency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/simulation/notional.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/simulation/position_change.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/simulation/provenance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/simulation/slippage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/simulation/trade_pnl.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/strategy/entry_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/strategy/exit_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/strategy/position_size.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/strategy/risk_reward.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/strategy/signal_confidence.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/strategy/signal_expiry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/strategy/signal_score.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/strategy/stop_distance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/strategy/target_distance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/strategy/version_readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/atr.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/bollinger_position.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/crossover.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/ema.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/macd.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/range.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/rate_of_change.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/resistance_distance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/rsi.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/sma.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/support_distance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/trend_strength.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/volatility.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/volume_ratio.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/strategy_research/study/vwap.c"
)

if(BUILD_TESTING)
    function(umicom_add_strategy_research_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()

        add_executable(
            "${target}"
            "${CMAKE_CURRENT_LIST_DIR}/../tests/strategy_research/${source}"
        )
        target_link_libraries("${target}" PRIVATE Umicom::Framework)

        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()

        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties(
            "${test_name}"
            PROPERTIES LABELS
            "framework;strategy;backtest;replay;optimisation;studies;simulation"
        )
    endfunction()

    umicom_add_strategy_research_test(
        umicom-strategy-research-types-test
        framework.strategy_research.types
        test_types.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-service-test
        framework.strategy_research.service
        test_service_catalogue.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-engine-test
        framework.strategy_research.backtest_engine
        test_backtest_engine.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-replay-engine-test
        framework.strategy_research.replay_engine
        test_replay_engine.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-optimisation-engine-test
        framework.strategy_research.optimisation_engine
        test_optimisation_engine.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-series-test
        framework.strategy_research.study_series
        test_study_series.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-simulation-evidence-test
        framework.strategy_research.simulation_evidence
        test_simulation_evidence.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-strategy-project-test
        framework.strategy_research.strategy_project
        test_strategy_project.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-average-loss-test
        framework.strategy_research.backtest.average.loss
        test_backtest_average_loss.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-average-win-test
        framework.strategy_research.backtest.average.win
        test_backtest_average_win.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-expectancy-test
        framework.strategy_research.backtest.expectancy
        test_backtest_expectancy.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-exposure-test
        framework.strategy_research.backtest.exposure
        test_backtest_exposure.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-gross-loss-test
        framework.strategy_research.backtest.gross.loss
        test_backtest_gross_loss.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-gross-profit-test
        framework.strategy_research.backtest.gross.profit
        test_backtest_gross_profit.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-loss-streak-test
        framework.strategy_research.backtest.loss.streak
        test_backtest_loss_streak.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-max-drawdown-test
        framework.strategy_research.backtest.max.drawdown
        test_backtest_max_drawdown.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-net-profit-test
        framework.strategy_research.backtest.net.profit
        test_backtest_net_profit.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-profit-factor-test
        framework.strategy_research.backtest.profit.factor
        test_backtest_profit_factor.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-recovery-factor-test
        framework.strategy_research.backtest.recovery.factor
        test_backtest_recovery_factor.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-trade-count-test
        framework.strategy_research.backtest.trade.count
        test_backtest_trade_count.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-turnover-test
        framework.strategy_research.backtest.turnover
        test_backtest_turnover.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-win-rate-test
        framework.strategy_research.backtest.win.rate
        test_backtest_win_rate.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-backtest-win-streak-test
        framework.strategy_research.backtest.win.streak
        test_backtest_win_streak.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-optimisation-budget-test
        framework.strategy_research.optimisation.budget
        test_optimisation_budget.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-optimisation-candidate-rank-test
        framework.strategy_research.optimisation.candidate.rank
        test_optimisation_candidate_rank.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-optimisation-early-stop-test
        framework.strategy_research.optimisation.early.stop
        test_optimisation_early_stop.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-optimisation-objective-test
        framework.strategy_research.optimisation.objective
        test_optimisation_objective.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-optimisation-overfit-gap-test
        framework.strategy_research.optimisation.overfit.gap
        test_optimisation_overfit_gap.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-optimisation-pareto-test
        framework.strategy_research.optimisation.pareto
        test_optimisation_pareto.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-optimisation-robustness-test
        framework.strategy_research.optimisation.robustness
        test_optimisation_robustness.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-optimisation-sensitivity-test
        framework.strategy_research.optimisation.sensitivity
        test_optimisation_sensitivity.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-optimisation-stability-test
        framework.strategy_research.optimisation.stability
        test_optimisation_stability.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-optimisation-walk-forward-test
        framework.strategy_research.optimisation.walk.forward
        test_optimisation_walk_forward.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-performance-annualised-return-test
        framework.strategy_research.performance.annualised.return
        test_performance_annualised_return.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-performance-annualised-volatility-test
        framework.strategy_research.performance.annualised.volatility
        test_performance_annualised_volatility.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-performance-calmar-test
        framework.strategy_research.performance.calmar
        test_performance_calmar.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-performance-downside-deviation-test
        framework.strategy_research.performance.downside.deviation
        test_performance_downside_deviation.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-performance-payoff-ratio-test
        framework.strategy_research.performance.payoff.ratio
        test_performance_payoff_ratio.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-performance-sharpe-test
        framework.strategy_research.performance.sharpe
        test_performance_sharpe.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-performance-sortino-test
        framework.strategy_research.performance.sortino
        test_performance_sortino.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-performance-stability-test
        framework.strategy_research.performance.stability
        test_performance_stability.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-performance-trade-efficiency-test
        framework.strategy_research.performance.trade.efficiency
        test_performance_trade_efficiency.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-performance-ulcer-index-test
        framework.strategy_research.performance.ulcer.index
        test_performance_ulcer_index.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-replay-checkpoint-test
        framework.strategy_research.replay.checkpoint
        test_replay_checkpoint.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-replay-clock-drift-test
        framework.strategy_research.replay.clock.drift
        test_replay_clock_drift.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-replay-data-quality-test
        framework.strategy_research.replay.data.quality
        test_replay_data_quality.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-replay-event-rate-test
        framework.strategy_research.replay.event.rate
        test_replay_event_rate.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-replay-gap-count-test
        framework.strategy_research.replay.gap.count
        test_replay_gap_count.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-replay-gap-ratio-test
        framework.strategy_research.replay.gap.ratio
        test_replay_gap_ratio.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-replay-progress-test
        framework.strategy_research.replay.progress
        test_replay_progress.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-replay-readiness-test
        framework.strategy_research.replay.readiness
        test_replay_readiness.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-replay-seek-distance-test
        framework.strategy_research.replay.seek.distance
        test_replay_seek_distance.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-replay-speed-test
        framework.strategy_research.replay.speed
        test_replay_speed.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-simulation-cash-change-test
        framework.strategy_research.simulation.cash.change
        test_simulation_cash_change.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-simulation-commission-test
        framework.strategy_research.simulation.commission
        test_simulation_commission.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-simulation-evidence-quality-test
        framework.strategy_research.simulation.evidence.quality
        test_simulation_evidence_quality.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-simulation-fill-ratio-test
        framework.strategy_research.simulation.fill.ratio
        test_simulation_fill_ratio.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-simulation-latency-test
        framework.strategy_research.simulation.latency
        test_simulation_latency.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-simulation-notional-test
        framework.strategy_research.simulation.notional
        test_simulation_notional.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-simulation-position-change-test
        framework.strategy_research.simulation.position.change
        test_simulation_position_change.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-simulation-provenance-test
        framework.strategy_research.simulation.provenance
        test_simulation_provenance.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-simulation-slippage-test
        framework.strategy_research.simulation.slippage
        test_simulation_slippage.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-simulation-trade-pnl-test
        framework.strategy_research.simulation.trade.pnl
        test_simulation_trade_pnl.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-strategy-entry-gate-test
        framework.strategy_research.strategy.entry.gate
        test_strategy_entry_gate.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-strategy-exit-gate-test
        framework.strategy_research.strategy.exit.gate
        test_strategy_exit_gate.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-strategy-position-size-test
        framework.strategy_research.strategy.position.size
        test_strategy_position_size.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-strategy-risk-reward-test
        framework.strategy_research.strategy.risk.reward
        test_strategy_risk_reward.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-strategy-signal-confidence-test
        framework.strategy_research.strategy.signal.confidence
        test_strategy_signal_confidence.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-strategy-signal-expiry-test
        framework.strategy_research.strategy.signal.expiry
        test_strategy_signal_expiry.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-strategy-signal-score-test
        framework.strategy_research.strategy.signal.score
        test_strategy_signal_score.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-strategy-stop-distance-test
        framework.strategy_research.strategy.stop.distance
        test_strategy_stop_distance.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-strategy-target-distance-test
        framework.strategy_research.strategy.target.distance
        test_strategy_target_distance.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-strategy-version-readiness-test
        framework.strategy_research.strategy.version.readiness
        test_strategy_version_readiness.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-atr-test
        framework.strategy_research.study.atr
        test_study_atr.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-bollinger-position-test
        framework.strategy_research.study.bollinger.position
        test_study_bollinger_position.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-crossover-test
        framework.strategy_research.study.crossover
        test_study_crossover.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-ema-test
        framework.strategy_research.study.ema
        test_study_ema.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-macd-test
        framework.strategy_research.study.macd
        test_study_macd.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-range-test
        framework.strategy_research.study.range
        test_study_range.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-rate-of-change-test
        framework.strategy_research.study.rate.of.change
        test_study_rate_of_change.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-resistance-distance-test
        framework.strategy_research.study.resistance.distance
        test_study_resistance_distance.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-rsi-test
        framework.strategy_research.study.rsi
        test_study_rsi.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-sma-test
        framework.strategy_research.study.sma
        test_study_sma.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-support-distance-test
        framework.strategy_research.study.support.distance
        test_study_support_distance.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-trend-strength-test
        framework.strategy_research.study.trend.strength
        test_study_trend_strength.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-volatility-test
        framework.strategy_research.study.volatility
        test_study_volatility.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-volume-ratio-test
        framework.strategy_research.study.volume.ratio
        test_study_volume_ratio.c
    )
    umicom_add_strategy_research_test(
        umicom-strategy-research-study-vwap-test
        framework.strategy_research.study.vwap
        test_study_vwap.c
    )
endif()

message(STATUS
    "Umicom deterministic strategy research, backtest and replay platform enabled")
