# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# File fixtures have separate working folders so parallel tests cannot create ambiguity for each other.
include_guard(GLOBAL)
if(NOT BUILD_TESTING)
    return()
endif()
function(umicom_diagnostic_source_target target source library)
    add_executable("${target}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../${source}")
    target_link_libraries("${target}" PRIVATE "${library}")
    set_target_properties("${target}" PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings("${target}")
    umicom_apply_sanitizers("${target}")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target("${target}")
    endif()
endfunction()
umicom_diagnostic_source_target(umicom-diagnostic-location-test tests/compiler_stream/test_source_location.c Umicom::build)
umicom_diagnostic_source_target(umicom-path-root-test tests/test_path_root_containment.c Umicom::platform)
add_test(NAME framework.path.root_containment COMMAND umicom-path-root-test)
set_tests_properties(framework.path.root_containment PROPERTIES TIMEOUT 30 LABELS "framework;path;regression")
set(_umicom_source_cases source build absolute ambiguous same-root no-line uri pseudo unterminated missing escape generated-source bounds)
if(WIN32)
    list(APPEND _umicom_source_cases drive-relative alternate-stream network)
endif()
foreach(case IN LISTS _umicom_source_cases)
    set(directory "${CMAKE_CURRENT_BINARY_DIR}/diagnostic-source-fixtures/${case}")
    file(MAKE_DIRECTORY "${directory}")
    add_test(NAME framework.diagnostic_source.${case} COMMAND umicom-diagnostic-location-test "${case}")
    set_tests_properties(framework.diagnostic_source.${case} PROPERTIES
        WORKING_DIRECTORY "${directory}" TIMEOUT 30 LABELS "framework;build;diagnostics;source;regression")
endforeach()
if(TARGET Umicom::ui_gtk4)
    umicom_diagnostic_source_target(umicom-diagnostic-source-gtk-test tests/compiler_stream/test_source_gtk4.c Umicom::ui_gtk4)
    foreach(case cursor pending-page retained close stale)
        add_test(NAME framework.diagnostic_source.gtk4.${case} COMMAND umicom-diagnostic-source-gtk-test "${case}")
        set_tests_properties(framework.diagnostic_source.gtk4.${case} PROPERTIES
            TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;build;diagnostics;source;gtk4;ownership")
    endforeach()
endif()
