# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Import uses the established workspace transaction; optional native controls
# share the same service and bounded platform reader.
include_guard(GLOBAL)
set(_umi_import_root "${CMAKE_CURRENT_LIST_DIR}/..")
if(BUILD_TESTING)
    add_executable(umicom-ai-import-test "${_umi_import_root}/tests/ai_workspace/test_import.c")
    target_include_directories(umicom-ai-import-test PRIVATE "${_umi_import_root}/src/ai_workspace")
    target_link_libraries(umicom-ai-import-test PRIVATE Umicom::ai_workspace)
    umicom_ai_workspace_configure_target(umicom-ai-import-test)
    foreach(case preview apply owned unicode normalization long-line lines approval repeat collision collection-title stale external-writer capacity collections-full limits invalid arguments reload search grounded sqlite-rollback sqlite-reload outer-transaction other-owner revision-overflow maximum partial-capacity late-collision)
        add_test(NAME framework.ai_workspace.import.${case} COMMAND umicom-ai-import-test ${case})
        set_tests_properties(framework.ai_workspace.import.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77 LABELS "framework;rag;import;transaction;regression")
    endforeach()
    if(TARGET Umicom::ai_workspace_gtk4)
        add_executable(umicom-ai-import-native-test "${_umi_import_root}/tests/ai_workspace/test_import_gtk4.c")
        target_link_libraries(umicom-ai-import-native-test PRIVATE Umicom::ai_workspace_gtk4)
        umicom_ai_workspace_configure_target(umicom-ai-import-native-test)
        foreach(case apply no-preview no-approval text-change destination-change stale retained preview-edit preview-destroy private search)
            add_test(NAME framework.ai_workspace.import.gtk4.${case} COMMAND umicom-ai-import-native-test ${case})
            set_tests_properties(framework.ai_workspace.import.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77 LABELS "framework;rag;import;gtk4;lifetime;regression")
        endforeach()
        add_executable(umicom-ai-import-file-native-test "${_umi_import_root}/tests/ai_workspace/test_import_file_gtk4.c")
        # The fixture compiles the real panel once to reach its file boundary;
        # no second copy of the panel object is linked from its normal library.
        target_link_libraries(umicom-ai-import-file-native-test PRIVATE Umicom::ai_workspace Umicom::ui_gtk4)
        umicom_ai_workspace_configure_target(umicom-ai-import-file-native-test)
        foreach(case load invalid nul over-limit edit-pending close-pending missing)
            add_test(NAME framework.ai_workspace.import.file.gtk4.${case} COMMAND umicom-ai-import-file-native-test ${case})
            set_tests_properties(framework.ai_workspace.import.file.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77 LABELS "framework;rag;import;file;gtk4;lifetime;regression")
        endforeach()
    endif()
    foreach(target umicom-ai-import-test umicom-ai-import-native-test umicom-ai-import-file-native-test)
        if(TARGET ${target} AND COMMAND umicom_register_validation_target)
            umicom_register_validation_target(${target})
        endif()
    endforeach()
endif()
install(FILES "${_umi_import_root}/docs/learning/import-searchable-documents.html"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/umicom/framework/docs/learning" COMPONENT Framework)
unset(_umi_import_root)
