# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING AND (WIN32 OR UNIX) AND NOT EMSCRIPTEN)
    add_executable(umicom-png-file-test "${CMAKE_CURRENT_LIST_DIR}/../tests/media/test_png_file.c")
    target_link_libraries(umicom-png-file-test PRIVATE Umicom::png_image)
    set_target_properties(umicom-png-file-test PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings(umicom-png-file-test)
    umicom_apply_sanitizers(umicom-png-file-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-png-file-test)
    endif()
    foreach(case write unicode-path existing cancelled relative missing-parent null-surface null-result)
        add_test(NAME framework.media.png_file.${case} COMMAND umicom-png-file-test ${case})
        set_tests_properties(framework.media.png_file.${case} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;media;png;regression")
    endforeach()
endif()
