# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-creative-asset-core-test "${CMAKE_CURRENT_LIST_DIR}/../tests/creative_assets/test_asset.c")
    target_link_libraries(umicom-creative-asset-core-test PRIVATE Umicom::creative_workspace)
    umicom_creative_configure_target(umicom-creative-asset-core-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-creative-asset-core-test)
    endif()
    foreach(case binary empty owned-bytes owned-label unicode all-kinds invalid-kind empty-label control-label invalid-utf8 label-capacity null-bytes null-output live-output too-large cancel cancel-reset inspect-invalid view-invalid two-assets large-capture)
        add_test(NAME framework.creative_assets.core.${case} COMMAND umicom-creative-asset-core-test ${case})
        set_tests_properties(framework.creative_assets.core.${case} PROPERTIES TIMEOUT 30 LABELS "framework;creative-assets;regression")
    endforeach()
endif()
