# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Compiler command inspection shares the bounded JSON owner with project discovery.
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/UmicomJsonTree.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/UmicomInputFile.cmake")
target_sources(umicom_developer PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_project/compilation_database.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_project/compilation_database_settings.c")
if(TARGET umicom_ui_gtk4)
    target_sources(umicom_ui_gtk4 PRIVATE
        "${CMAKE_CURRENT_LIST_DIR}/../adapters/gtk4/compilation_database_gtk4.c")
endif()
if(NOT BUILD_TESTING)
    return()
endif()
function(umicom_compilation_database_test target source library)
    add_executable("${target}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/compilation_database/${source}")
    target_link_libraries("${target}" PRIVATE "${library}")
    set_target_properties("${target}" PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings("${target}")
    umicom_apply_sanitizers("${target}")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target("${target}")
    endif()
endfunction()
umicom_compilation_database_test(umicom-compilation-database-records-test test_records.c Umicom::developer)
umicom_compilation_database_test(umicom-compilation-database-rejected-test test_rejected.c Umicom::developer)
umicom_compilation_database_test(umicom-compilation-database-settings-test test_settings.c Umicom::developer)
umicom_compilation_database_test(umicom-compilation-database-limits-test test_limits.c Umicom::developer)
foreach(case empty command variants unicode arguments)
    add_test(NAME framework.compilation_database.records.${case} COMMAND umicom-compilation-database-records-test "${case}")
    set_tests_properties(framework.compilation_database.records.${case} PROPERTIES TIMEOUT 30 LABELS "framework;developer;compiler-database")
endforeach()
foreach(case object scalar-row missing-directory relative-directory missing-file no-command empty-arguments empty-compiler numeric-argument empty-command duplicate-field invalid-output escaped-nul partial syntax invalid-utf8 cancelled)
    add_test(NAME framework.compilation_database.rejected.${case} COMMAND umicom-compilation-database-rejected-test "${case}")
    set_tests_properties(framework.compilation_database.rejected.${case} PROPERTIES TIMEOUT 30 LABELS "framework;developer;compiler-database;regression")
endforeach()
foreach(case export-new export-existing export-duplicate append alias replace-equals replace-separate single-dash duplicate missing-value response terminator small relative)
    add_test(NAME framework.compilation_database.settings.${case} COMMAND umicom-compilation-database-settings-test "${case}")
    set_tests_properties(framework.compilation_database.settings.${case} PROPERTIES TIMEOUT 30 LABELS "framework;developer;compiler-database;settings")
endforeach()
foreach(case rows too-many-rows text too-long-text arguments too-many-arguments)
    add_test(NAME framework.compilation_database.limits.${case} COMMAND umicom-compilation-database-limits-test "${case}")
    set_tests_properties(framework.compilation_database.limits.${case} PROPERTIES TIMEOUT 120 LABELS "framework;developer;compiler-database;bounds")
endforeach()
if(TARGET umicom_ui_gtk4)
    umicom_compilation_database_test(umicom-compilation-database-gtk-test test_gtk4.c Umicom::ui_gtk4)
    foreach(case read use changed cancel hidden retained pending-close use-close missing other-window source)
        add_test(NAME framework.compilation_database.gtk4.${case} COMMAND umicom-compilation-database-gtk-test "${case}")
        set_tests_properties(framework.compilation_database.gtk4.${case} PROPERTIES
            TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;developer;compiler-database;gtk4;ownership")
    endforeach()
endif()

if(TARGET umicom_ui_gtk4)
    umicom_compilation_database_test(umicom-compilation-export-gtk-test test_export_gtk4.c Umicom::ui_gtk4)
    foreach(case draft invalid retained reentrant)
        add_test(NAME framework.compilation_database.export.gtk4.${case} COMMAND umicom-compilation-export-gtk-test "${case}")
        set_tests_properties(framework.compilation_database.export.gtk4.${case} PROPERTIES
            TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;developer;compiler-database;gtk4;settings")
    endforeach()
endif()
