# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING AND TARGET Umicom::creative_workspace_gtk4 AND (WIN32 OR UNIX) AND NOT EMSCRIPTEN)
    add_executable(umicom-creative-image-edit-test "${CMAKE_CURRENT_LIST_DIR}/../tests/creative_assets/test_image_edit_gtk4.c")
    target_link_libraries(umicom-creative-image-edit-test PRIVATE Umicom::creative_workspace_gtk4)
    umicom_creative_configure_target(umicom-creative-image-edit-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-creative-image-edit-test)
    endif()
    foreach(case crop rotate crop-rotate reset invalid-crop form-retirement pending-form-change export export-existing raw-copy unchanged-source)
        add_test(NAME framework.creative_assets.image_edit.${case} COMMAND umicom-creative-image-edit-test ${case})
        set_tests_properties(framework.creative_assets.image_edit.${case} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;creative-assets;image-edit;gtk4;regression")
    endforeach()
endif()
