# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-store-text-changes-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_store_text_changes.c")
    target_link_libraries(umicom-document-store-text-changes-test PRIVATE Umicom::platform)
    umicom_apply_warnings(umicom-document-store-text-changes-test)
    umicom_apply_sanitizers(umicom-document-store-text-changes-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-store-text-changes-test)
    endif()
    foreach(case apply empty unchanged forced mixed ownership duplicate stale-first stale-last closed saved external path name length dirty has-path unterminated null-text embedded-zero too-large too-many empty-set arguments)
        add_test(NAME framework.document.document_store_text_changes.${case} COMMAND umicom-document-store-text-changes-test ${case})
        set_tests_properties(framework.document.document_store_text_changes.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;store;transaction;regression")
    endforeach()
endif()
