#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomTradingBrokerageExchangePlatform.cmake
#
# PURPOSE:
#   Extend canonical Umicom::trading with advanced brokerage, routing, order
#   lifecycle, exchange matching, market structure and surveillance services.
#
# ARCHITECTURE:
#   Existing trading records, broker adapters, replay/research and finance
#   services remain authoritative. This adds reusable advanced trading semantics
#   without creating a competing target or moving logic into Trader/Exchange.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_TRADING_CORE_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
# Load the dependency only when the parent build has not already provided its target.
if(NOT TARGET umicom_trading)
    message(FATAL_ERROR "UmicomTradingBrokerageExchangePlatform.cmake requires canonical umicom_trading")
endif()

# Advanced brokerage and exchange capabilities extend the canonical trading target.
target_sources(umicom_trading PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/auction_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/auction_match.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/auction_order.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/best_execution.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/broker_route.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/broker_route_table.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/brokerage_account.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/brokerage_account_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/buying_power_model.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/cash_ledger.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/circuit_breaker.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/commission_calculation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/commission_schedule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/concentration_monitor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/consolidated_quote.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/consolidated_trade.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/exchange_service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/exchange_session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/exchange_trade_log.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/execution_aggregation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/execution_fill.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/execution_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/execution_quality.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/fee_calculation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/fee_schedule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/instrument_listing.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/limit_order_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/listing_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/lot_size_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/margin_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/margin_requirement.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/market_data_event.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/market_integrity_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/market_phase.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/market_status.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/matching_engine.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/matching_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/nbbo.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/order_book_level.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/order_cancel.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/order_event.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/order_event_log.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/order_identity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/order_instruction.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/order_replace.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/order_state_machine.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/order_validation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/position_ledger.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/posttrade_risk.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/pretrade_risk.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/price_band.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/slippage_analysis.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/smart_order_router.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/spoofing_detector.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/surveillance_alert.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/surveillance_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/tick_size_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/trade_capture.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/trading_calendar.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/trading_platform_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/venue_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/venue_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/venue_session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/volatility_interrupt.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading/core/wash_trade_detector.c"
)

# Register verification targets only when the developer has enabled testing.
if(BUILD_TESTING)
    # Define the add trading core test build helper so parent and application projects apply
    # one consistent rule.
    function(umicom_add_trading_core_test target test_name source)
        # Configure the optional target only when its feature has created it.
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_TRADING_CORE_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::trading)
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;trading-core;brokerage-core;exchange-core")
    endfunction()

    umicom_add_trading_core_test(
        umicom-trading-core-types-test
        framework.trading_core.types
        tests/trading_core/test_types.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-auction-book-test
        framework.trading_core.auction.book
        tests/trading_core/test_auction_book.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-auction-match-test
        framework.trading_core.auction.match
        tests/trading_core/test_auction_match.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-auction-order-test
        framework.trading_core.auction.order
        tests/trading_core/test_auction_order.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-best-execution-test
        framework.trading_core.best.execution
        tests/trading_core/test_best_execution.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-broker-route-test
        framework.trading_core.broker.route
        tests/trading_core/test_broker_route.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-broker-route-table-test
        framework.trading_core.broker.route.table
        tests/trading_core/test_broker_route_table.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-brokerage-account-test
        framework.trading_core.brokerage.account
        tests/trading_core/test_brokerage_account.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-brokerage-account-book-test
        framework.trading_core.brokerage.account.book
        tests/trading_core/test_brokerage_account_book.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-buying-power-model-test
        framework.trading_core.buying.power.model
        tests/trading_core/test_buying_power_model.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-cash-ledger-test
        framework.trading_core.cash.ledger
        tests/trading_core/test_cash_ledger.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-circuit-breaker-test
        framework.trading_core.circuit.breaker
        tests/trading_core/test_circuit_breaker.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-commission-calculation-test
        framework.trading_core.commission.calculation
        tests/trading_core/test_commission_calculation.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-commission-schedule-test
        framework.trading_core.commission.schedule
        tests/trading_core/test_commission_schedule.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-concentration-monitor-test
        framework.trading_core.concentration.monitor
        tests/trading_core/test_concentration_monitor.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-consolidated-quote-test
        framework.trading_core.consolidated.quote
        tests/trading_core/test_consolidated_quote.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-consolidated-trade-test
        framework.trading_core.consolidated.trade
        tests/trading_core/test_consolidated_trade.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-exchange-service-test
        framework.trading_core.exchange.service
        tests/trading_core/test_exchange_service.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-exchange-session-test
        framework.trading_core.exchange.session
        tests/trading_core/test_exchange_session.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-exchange-trade-log-test
        framework.trading_core.exchange.trade.log
        tests/trading_core/test_exchange_trade_log.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-execution-aggregation-test
        framework.trading_core.execution.aggregation
        tests/trading_core/test_execution_aggregation.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-execution-fill-test
        framework.trading_core.execution.fill
        tests/trading_core/test_execution_fill.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-execution-policy-test
        framework.trading_core.execution.policy
        tests/trading_core/test_execution_policy.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-execution-quality-test
        framework.trading_core.execution.quality
        tests/trading_core/test_execution_quality.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-fee-calculation-test
        framework.trading_core.fee.calculation
        tests/trading_core/test_fee_calculation.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-fee-schedule-test
        framework.trading_core.fee.schedule
        tests/trading_core/test_fee_schedule.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-instrument-listing-test
        framework.trading_core.instrument.listing
        tests/trading_core/test_instrument_listing.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-limit-order-book-test
        framework.trading_core.limit.order.book
        tests/trading_core/test_limit_order_book.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-listing-catalogue-test
        framework.trading_core.listing.catalogue
        tests/trading_core/test_listing_catalogue.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-lot-size-rule-test
        framework.trading_core.lot.size.rule
        tests/trading_core/test_lot_size_rule.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-margin-profile-test
        framework.trading_core.margin.profile
        tests/trading_core/test_margin_profile.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-margin-requirement-test
        framework.trading_core.margin.requirement
        tests/trading_core/test_margin_requirement.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-market-data-event-test
        framework.trading_core.market.data.event
        tests/trading_core/test_market_data_event.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-market-integrity-snapshot-test
        framework.trading_core.market.integrity.snapshot
        tests/trading_core/test_market_integrity_snapshot.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-market-phase-test
        framework.trading_core.market.phase
        tests/trading_core/test_market_phase.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-market-status-test
        framework.trading_core.market.status
        tests/trading_core/test_market_status.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-matching-engine-test
        framework.trading_core.matching.engine
        tests/trading_core/test_matching_engine.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-matching-policy-test
        framework.trading_core.matching.policy
        tests/trading_core/test_matching_policy.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-nbbo-test
        framework.trading_core.nbbo
        tests/trading_core/test_nbbo.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-order-book-level-test
        framework.trading_core.order.book.level
        tests/trading_core/test_order_book_level.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-order-cancel-test
        framework.trading_core.order.cancel
        tests/trading_core/test_order_cancel.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-order-event-test
        framework.trading_core.order.event
        tests/trading_core/test_order_event.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-order-event-log-test
        framework.trading_core.order.event.log
        tests/trading_core/test_order_event_log.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-order-identity-test
        framework.trading_core.order.identity
        tests/trading_core/test_order_identity.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-order-instruction-test
        framework.trading_core.order.instruction
        tests/trading_core/test_order_instruction.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-order-replace-test
        framework.trading_core.order.replace
        tests/trading_core/test_order_replace.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-order-state-machine-test
        framework.trading_core.order.state.machine
        tests/trading_core/test_order_state_machine.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-order-validation-test
        framework.trading_core.order.validation
        tests/trading_core/test_order_validation.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-position-ledger-test
        framework.trading_core.position.ledger
        tests/trading_core/test_position_ledger.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-posttrade-risk-test
        framework.trading_core.posttrade.risk
        tests/trading_core/test_posttrade_risk.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-pretrade-risk-test
        framework.trading_core.pretrade.risk
        tests/trading_core/test_pretrade_risk.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-price-band-test
        framework.trading_core.price.band
        tests/trading_core/test_price_band.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-slippage-analysis-test
        framework.trading_core.slippage.analysis
        tests/trading_core/test_slippage_analysis.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-smart-order-router-test
        framework.trading_core.smart.order.router
        tests/trading_core/test_smart_order_router.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-spoofing-detector-test
        framework.trading_core.spoofing.detector
        tests/trading_core/test_spoofing_detector.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-surveillance-alert-test
        framework.trading_core.surveillance.alert
        tests/trading_core/test_surveillance_alert.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-surveillance-rule-test
        framework.trading_core.surveillance.rule
        tests/trading_core/test_surveillance_rule.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-tick-size-rule-test
        framework.trading_core.tick.size.rule
        tests/trading_core/test_tick_size_rule.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-trade-capture-test
        framework.trading_core.trade.capture
        tests/trading_core/test_trade_capture.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-trading-calendar-test
        framework.trading_core.trading.calendar
        tests/trading_core/test_trading_calendar.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-trading-platform-snapshot-test
        framework.trading_core.trading.platform.snapshot
        tests/trading_core/test_trading_platform_snapshot.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-venue-catalogue-test
        framework.trading_core.venue.catalogue
        tests/trading_core/test_venue_catalogue.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-venue-descriptor-test
        framework.trading_core.venue.descriptor
        tests/trading_core/test_venue_descriptor.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-venue-session-test
        framework.trading_core.venue.session
        tests/trading_core/test_venue_session.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-volatility-interrupt-test
        framework.trading_core.volatility.interrupt
        tests/trading_core/test_volatility_interrupt.c
    )
    umicom_add_trading_core_test(
        umicom-trading-core-wash-trade-detector-test
        framework.trading_core.wash.trade.detector
        tests/trading_core/test_wash_trade_detector.c
    )
endif()

message(STATUS "Umicom trading, brokerage and exchange platform core enabled")
