# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-language-preferences-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_server_preferences.c")
    target_link_libraries(umicom-language-preferences-test PRIVATE Umicom::developer Umicom::platform)
    umicom_apply_warnings(umicom-language-preferences-test)
    umicom_apply_sanitizers(umicom-language-preferences-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-language-preferences-test)
    endif()
    foreach(case round-trip unicode empty-arguments capacity unterminated relative invalid-unicode control arguments empty-language documents byte-limit save-load invalid-save language-mismatch missing user-path case-sensitive path-separator path-capacity invalid-base language-limit)
        add_test(NAME framework.language_runtime.preferences.${case} COMMAND umicom-language-preferences-test ${case})
        set_tests_properties(framework.language_runtime.preferences.${case} PROPERTIES TIMEOUT 30
            LABELS "framework;language;preferences;ownership;regression")
    endforeach()
endif()
