# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_snippet_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-snippet-gtk4-test)
        return()
    endif()
    add_executable(umicom-snippet-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_snippet_gtk4.c")
    target_link_libraries(umicom-snippet-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-snippet-gtk4-test)
    umicom_apply_sanitizers(umicom-snippet-gtk4-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-snippet-gtk4-test)
    endif()
    foreach(case open private expand update linked selection empty multiline unicode final-stop literal preview approval apply undo stale template-change value-change retained native-close unbind parent-close creation-unbind completion-busy cancel-command choice choices invalid-value oversized-template model-retire callback-unbind)
        add_test(NAME framework.document.snippet.gtk4.${case}
            COMMAND umicom-snippet-gtk4-test ${case})
        set_tests_properties(framework.document.snippet.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77
            LABELS "framework;document;editor;snippet;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_snippet_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_snippet_checks)
endif()
