# Umicom Foundation | Sammy Hegab | MIT
# The adapter depends on toolkit-neutral market tape, never on Trader internals.
include_guard(GLOBAL)
include(GNUInstallDirs)
find_package(PkgConfig QUIET)
if(PkgConfig_FOUND)
    pkg_check_modules(UMICOM_MARKET_TAPE_GTK4 QUIET IMPORTED_TARGET GLOBAL gtk4>=4.10)
endif()
if(NOT TARGET PkgConfig::UMICOM_MARKET_TAPE_GTK4)
    message(STATUS "Market-tape GTK workspace not built: GTK4 >= 4.10 development files unavailable")
    return()
endif()
set(_umi_tape_gtk_root "${CMAKE_CURRENT_LIST_DIR}/..")
add_library(umicom_market_tape_gtk4 STATIC "${_umi_tape_gtk_root}/adapters/gtk4/market_tape_gtk4.c")
add_library(Umicom::market_tape_gtk4 ALIAS umicom_market_tape_gtk4)
set_target_properties(umicom_market_tape_gtk4 PROPERTIES EXPORT_NAME market_tape_gtk4)
target_link_libraries(umicom_market_tape_gtk4 PUBLIC Umicom::market_tape PkgConfig::UMICOM_MARKET_TAPE_GTK4)
target_compile_definitions(umicom_market_tape_gtk4 PUBLIC UMICOM_HAS_MARKET_TAPE_GTK4=1)
umicom_market_tape_target(umicom_market_tape_gtk4)
install(TARGETS umicom_market_tape_gtk4 EXPORT UmicomFrameworkTargets
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT Framework)
install(FILES "${_umi_tape_gtk_root}/include/umicom/ui/gtk4/market_tape.h"
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/umicom/ui/gtk4 COMPONENT Framework)
add_executable(umicom-market-tape-workbench "${_umi_tape_gtk_root}/examples/market_tape/gtk_main.c")
target_link_libraries(umicom-market-tape-workbench PRIVATE Umicom::market_tape_gtk4)
umicom_market_tape_target(umicom-market-tape-workbench)
install(TARGETS umicom-market-tape-workbench RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT Framework)
if(BUILD_TESTING)
    add_executable(umicom-market-tape-gtk-test "${_umi_tape_gtk_root}/tests/market_tape/test_gtk.c")
    target_link_libraries(umicom-market-tape-gtk-test PRIVATE Umicom::market_tape_gtk4)
    umicom_market_tape_target(umicom-market-tape-gtk-test)
    foreach(_case construction actions gap_reset independence retained_child wrapper_wrapper wrapper_parent)
        add_test(NAME framework.market_tape.gtk.${_case} COMMAND umicom-market-tape-gtk-test ${_case})
        set_tests_properties(framework.market_tape.gtk.${_case} PROPERTIES
            SKIP_RETURN_CODE 77 TIMEOUT 30 LABELS "market-tape;gtk4;lifecycle")
    endforeach()
endif()
install(FILES "${_umi_tape_gtk_root}/cmake/UmicomMarketTapeDependencies.cmake"
    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/UmicomFramework COMPONENT Framework)
unset(_umi_tape_gtk_root)
