# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# The core belongs to the existing build target. The optional GTK presenter
# copies snapshots and does not introduce a toolkit dependency into that core.
include_guard(GLOBAL)
if(BUILD_TESTING)
    foreach(kind session runner)
        add_executable(umicom-live-build-${kind}-test "${CMAKE_CURRENT_LIST_DIR}/../tests/live_build_output/test_${kind}.c")
        target_link_libraries(umicom-live-build-${kind}-test PRIVATE Umicom::build)
        umicom_apply_warnings(umicom-live-build-${kind}-test)
        umicom_apply_sanitizers(umicom-live-build-${kind}-test)
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(umicom-live-build-${kind}-test)
        endif()
    endforeach()
    add_executable(umicom-live-build-child "${CMAKE_CURRENT_LIST_DIR}/../tests/live_build_output/child.c")
    target_link_libraries(umicom-live-build-child PRIVATE Umicom::platform)
    umicom_apply_warnings(umicom-live-build-child)
    umicom_apply_sanitizers(umicom-live-build-child)
    add_dependencies(umicom-live-build-runner-test umicom-live-build-child)
    foreach(case idle invalid live oversized rolling exact empty binary phases phase-boundary-cancel cancel failure legacy repeat)
        add_test(NAME framework.live_build_output.session.${case} COMMAND umicom-live-build-session-test ${case})
        set_tests_properties(framework.live_build_output.session.${case} PROPERTIES
            TIMEOUT 30 LABELS "framework;build;output;regression")
    endforeach()
    foreach(case live unicode failure cancel timeout legacy invalid)
        set(directory "${CMAKE_CURRENT_BINARY_DIR}/qualification/live-build-output/${case}")
        file(MAKE_DIRECTORY "${directory}")
        add_test(NAME framework.live_build_output.runner.${case} COMMAND umicom-live-build-runner-test "$<TARGET_FILE:umicom-live-build-child>" ${case})
        set_tests_properties(framework.live_build_output.runner.${case} PROPERTIES
            WORKING_DIRECTORY "${directory}" TIMEOUT 30 LABELS "framework;build;output;process-fixture;regression")
    endforeach()
endif()
function(umicom_attach_live_build_output_gtk4)
    if(NOT TARGET umicom_ui_gtk4)
        return()
    endif()
    get_target_property(attached umicom_ui_gtk4 UMICOM_LIVE_BUILD_OUTPUT_ATTACHED)
    if(attached)
        return()
    endif()
    target_sources(umicom_ui_gtk4 PRIVATE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../adapters/gtk4/build_output_gtk4.c")
    target_sources(umicom_ui_gtk4 PRIVATE
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../adapters/gtk4/build_diagnostics_gtk4.c")
    target_link_libraries(umicom_ui_gtk4 PUBLIC Umicom::build)
    set_property(TARGET umicom_ui_gtk4 PROPERTY UMICOM_LIVE_BUILD_OUTPUT_ATTACHED TRUE)
    if(BUILD_TESTING)
        add_executable(umicom-build-diagnostic-pages-gtk4-test
            "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/compiler_stream/test_pages_gtk4.c")
        target_link_libraries(umicom-build-diagnostic-pages-gtk4-test PRIVATE Umicom::ui_gtk4)
        umicom_apply_warnings(umicom-build-diagnostic-pages-gtk4-test)
        umicom_apply_sanitizers(umicom-build-diagnostic-pages-gtk4-test)
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(umicom-build-diagnostic-pages-gtk4-test)
        endif()
        foreach(case paging phase operation invalid selection losses unicode reentrant retained)
            add_test(NAME framework.build_diagnostic_pages.gtk4.${case}
                COMMAND umicom-build-diagnostic-pages-gtk4-test "${case}")
            set_tests_properties(framework.build_diagnostic_pages.gtk4.${case} PROPERTIES
                TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;build;diagnostics;gtk4;regression")
        endforeach()
        add_executable(umicom-live-build-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/live_build_output/test_gtk4.c")
        target_link_libraries(umicom-live-build-gtk4-test PRIVATE Umicom::ui_gtk4)
        umicom_apply_warnings(umicom-live-build-gtk4-test)
        umicom_apply_sanitizers(umicom-live-build-gtk4-test)
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(umicom-live-build-gtk4-test)
        endif()
        foreach(case pause refresh resume copy binary split-utf8 invalid stale status retained unchanged)
            add_test(NAME framework.live_build_output.gtk4.${case} COMMAND umicom-live-build-gtk4-test ${case})
            set_tests_properties(framework.live_build_output.gtk4.${case} PROPERTIES
                TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;build;output;gtk4;regression")
        endforeach()
    endif()
endfunction()
umicom_attach_live_build_output_gtk4()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_live_build_output_gtk4)
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/learning/live-build-output.html"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/learning COMPONENT Learning)
