# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_typing_history_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-typing-history-gtk4-test)
        return()
    endif()
    add_executable(umicom-typing-history-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_typing_history_gtk4.c")
    target_link_libraries(umicom-typing-history-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-typing-history-gtk4-test)
    umicom_apply_sanitizers(umicom-typing-history-gtk4-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-typing-history-gtk4-test)
    endif()
    foreach(case insert selection reverse-selection unicode crlf empty unchanged nested two-actions detach destroy retained-buffer)
        add_test(NAME framework.document.typing_history.gtk4.${case}
            COMMAND umicom-typing-history-gtk4-test ${case})
        set_tests_properties(framework.document.typing_history.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77
            LABELS "framework;document;language;typing-history;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_typing_history_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_typing_history_checks)
endif()
