#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomEnterpriseValuationRiskPlatform.cmake
#
# PURPOSE:
#   Extend canonical Umicom::finance with enterprise market-data, calibration,
#   distributed valuation-grid, portfolio aggregation and risk orchestration.
#
# ARCHITECTURE:
#   Existing quantitative models, finance products and trading market structures
#   remain authoritative. This layer composes enterprise-scale valuation and risk
#   services without creating a competing finance target or application engine.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_ENTERPRISE_VALUATION_RISK_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
# Load the dependency only when the parent build has not already provided its target.
if(NOT TARGET umicom_finance)
    message(FATAL_ERROR "UmicomEnterpriseValuationRiskPlatform.cmake requires canonical umicom_finance")
endif()

# Enterprise valuation/risk capabilities extend the canonical finance target.
target_sources(umicom_finance PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/market_data_subscription.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/market_data_channel.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/market_data_topic.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/market_data_update.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/market_data_cache.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/market_data_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/market_data_snapshot_store.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/market_data_freshness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/market_data_quality.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/market_data_gap.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/market_data_entitlement.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/market_data_service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/calibration_job.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/calibration_dependency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/calibration_graph.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/curve_calibration_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/surface_calibration_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/calibration_cache.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/calibration_audit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_job.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_task.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_batch.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_dependency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_graph.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_queue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_worker.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_worker_pool.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_partition.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_cache_key.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_cache.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_result_store.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_grid.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/portfolio_position.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/portfolio_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/portfolio_aggregation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/portfolio_hierarchy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/portfolio_valuation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/portfolio_risk_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/risk_factor_vector.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/risk_factor_mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/risk_cube.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/risk_aggregation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/value_at_risk.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/expected_shortfall.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/historical_scenario.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/scenario_grid.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/scenario_partition.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/scenario_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/stress_scenario.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/stress_suite.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/pnl_explain_bucket.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/pnl_explain_report.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/pnl_attribution.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/risk_limit_evaluation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/risk_report.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/risk_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_lineage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_audit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_checkpoint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/valuation_replay.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/distributed_job.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/distributed_job_queue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/distributed_worker.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/enterprise/enterprise_risk_service.c"
)

# Apply this branch only when its contract condition is satisfied.
if(UNIX AND NOT APPLE)
    target_link_libraries(umicom_finance PRIVATE m)
endif()

# Register verification targets only when the developer has enabled testing.
if(BUILD_TESTING)
    # Define the add enterprise valuation risk test build helper so parent and application
    # projects apply one consistent rule.
    function(umicom_add_enterprise_valuation_risk_test target test_name source)
        # Configure the optional target only when its feature has created it.
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_ENTERPRISE_VALUATION_RISK_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::finance)
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;enterprise-valuation;portfolio-risk;market-data")
    endfunction()

    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-types-test
        framework.enterprise_valuation.types
        tests/finance_enterprise/test_types.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-market-data-subscription-test
        framework.enterprise_valuation.market.data.subscription
        tests/finance_enterprise/test_market_data_subscription.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-market-data-channel-test
        framework.enterprise_valuation.market.data.channel
        tests/finance_enterprise/test_market_data_channel.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-market-data-topic-test
        framework.enterprise_valuation.market.data.topic
        tests/finance_enterprise/test_market_data_topic.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-market-data-update-test
        framework.enterprise_valuation.market.data.update
        tests/finance_enterprise/test_market_data_update.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-market-data-cache-test
        framework.enterprise_valuation.market.data.cache
        tests/finance_enterprise/test_market_data_cache.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-market-data-snapshot-test
        framework.enterprise_valuation.market.data.snapshot
        tests/finance_enterprise/test_market_data_snapshot.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-market-data-snapshot-store-test
        framework.enterprise_valuation.market.data.snapshot.store
        tests/finance_enterprise/test_market_data_snapshot_store.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-market-data-freshness-test
        framework.enterprise_valuation.market.data.freshness
        tests/finance_enterprise/test_market_data_freshness.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-market-data-quality-test
        framework.enterprise_valuation.market.data.quality
        tests/finance_enterprise/test_market_data_quality.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-market-data-gap-test
        framework.enterprise_valuation.market.data.gap
        tests/finance_enterprise/test_market_data_gap.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-market-data-entitlement-test
        framework.enterprise_valuation.market.data.entitlement
        tests/finance_enterprise/test_market_data_entitlement.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-market-data-service-test
        framework.enterprise_valuation.market.data.service
        tests/finance_enterprise/test_market_data_service.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-calibration-job-test
        framework.enterprise_valuation.calibration.job
        tests/finance_enterprise/test_calibration_job.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-calibration-dependency-test
        framework.enterprise_valuation.calibration.dependency
        tests/finance_enterprise/test_calibration_dependency.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-calibration-graph-test
        framework.enterprise_valuation.calibration.graph
        tests/finance_enterprise/test_calibration_graph.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-curve-calibration-plan-test
        framework.enterprise_valuation.curve.calibration.plan
        tests/finance_enterprise/test_curve_calibration_plan.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-surface-calibration-plan-test
        framework.enterprise_valuation.surface.calibration.plan
        tests/finance_enterprise/test_surface_calibration_plan.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-calibration-cache-test
        framework.enterprise_valuation.calibration.cache
        tests/finance_enterprise/test_calibration_cache.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-calibration-audit-test
        framework.enterprise_valuation.calibration.audit
        tests/finance_enterprise/test_calibration_audit.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-job-test
        framework.enterprise_valuation.valuation.job
        tests/finance_enterprise/test_valuation_job.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-task-test
        framework.enterprise_valuation.valuation.task
        tests/finance_enterprise/test_valuation_task.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-batch-test
        framework.enterprise_valuation.valuation.batch
        tests/finance_enterprise/test_valuation_batch.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-dependency-test
        framework.enterprise_valuation.valuation.dependency
        tests/finance_enterprise/test_valuation_dependency.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-graph-test
        framework.enterprise_valuation.valuation.graph
        tests/finance_enterprise/test_valuation_graph.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-queue-test
        framework.enterprise_valuation.valuation.queue
        tests/finance_enterprise/test_valuation_queue.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-worker-test
        framework.enterprise_valuation.valuation.worker
        tests/finance_enterprise/test_valuation_worker.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-worker-pool-test
        framework.enterprise_valuation.valuation.worker.pool
        tests/finance_enterprise/test_valuation_worker_pool.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-partition-test
        framework.enterprise_valuation.valuation.partition
        tests/finance_enterprise/test_valuation_partition.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-cache-key-test
        framework.enterprise_valuation.valuation.cache.key
        tests/finance_enterprise/test_valuation_cache_key.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-cache-test
        framework.enterprise_valuation.valuation.cache
        tests/finance_enterprise/test_valuation_cache.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-result-store-test
        framework.enterprise_valuation.valuation.result.store
        tests/finance_enterprise/test_valuation_result_store.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-grid-test
        framework.enterprise_valuation.valuation.grid
        tests/finance_enterprise/test_valuation_grid.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-service-test
        framework.enterprise_valuation.valuation.service
        tests/finance_enterprise/test_valuation_service.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-portfolio-position-test
        framework.enterprise_valuation.portfolio.position
        tests/finance_enterprise/test_portfolio_position.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-portfolio-snapshot-test
        framework.enterprise_valuation.portfolio.snapshot
        tests/finance_enterprise/test_portfolio_snapshot.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-portfolio-aggregation-test
        framework.enterprise_valuation.portfolio.aggregation
        tests/finance_enterprise/test_portfolio_aggregation.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-portfolio-hierarchy-test
        framework.enterprise_valuation.portfolio.hierarchy
        tests/finance_enterprise/test_portfolio_hierarchy.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-portfolio-valuation-test
        framework.enterprise_valuation.portfolio.valuation
        tests/finance_enterprise/test_portfolio_valuation.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-portfolio-risk-result-test
        framework.enterprise_valuation.portfolio.risk.result
        tests/finance_enterprise/test_portfolio_risk_result.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-risk-factor-vector-test
        framework.enterprise_valuation.risk.factor.vector
        tests/finance_enterprise/test_risk_factor_vector.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-risk-factor-mapping-test
        framework.enterprise_valuation.risk.factor.mapping
        tests/finance_enterprise/test_risk_factor_mapping.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-risk-cube-test
        framework.enterprise_valuation.risk.cube
        tests/finance_enterprise/test_risk_cube.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-risk-aggregation-test
        framework.enterprise_valuation.risk.aggregation
        tests/finance_enterprise/test_risk_aggregation.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-value-at-risk-test
        framework.enterprise_valuation.value.at.risk
        tests/finance_enterprise/test_value_at_risk.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-expected-shortfall-test
        framework.enterprise_valuation.expected.shortfall
        tests/finance_enterprise/test_expected_shortfall.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-historical-scenario-test
        framework.enterprise_valuation.historical.scenario
        tests/finance_enterprise/test_historical_scenario.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-scenario-grid-test
        framework.enterprise_valuation.scenario.grid
        tests/finance_enterprise/test_scenario_grid.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-scenario-partition-test
        framework.enterprise_valuation.scenario.partition
        tests/finance_enterprise/test_scenario_partition.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-scenario-result-test
        framework.enterprise_valuation.scenario.result
        tests/finance_enterprise/test_scenario_result.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-stress-scenario-test
        framework.enterprise_valuation.stress.scenario
        tests/finance_enterprise/test_stress_scenario.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-stress-suite-test
        framework.enterprise_valuation.stress.suite
        tests/finance_enterprise/test_stress_suite.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-pnl-explain-bucket-test
        framework.enterprise_valuation.pnl.explain.bucket
        tests/finance_enterprise/test_pnl_explain_bucket.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-pnl-explain-report-test
        framework.enterprise_valuation.pnl.explain.report
        tests/finance_enterprise/test_pnl_explain_report.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-pnl-attribution-test
        framework.enterprise_valuation.pnl.attribution
        tests/finance_enterprise/test_pnl_attribution.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-risk-limit-evaluation-test
        framework.enterprise_valuation.risk.limit.evaluation
        tests/finance_enterprise/test_risk_limit_evaluation.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-risk-report-test
        framework.enterprise_valuation.risk.report
        tests/finance_enterprise/test_risk_report.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-risk-snapshot-test
        framework.enterprise_valuation.risk.snapshot
        tests/finance_enterprise/test_risk_snapshot.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-lineage-test
        framework.enterprise_valuation.valuation.lineage
        tests/finance_enterprise/test_valuation_lineage.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-audit-test
        framework.enterprise_valuation.valuation.audit
        tests/finance_enterprise/test_valuation_audit.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-checkpoint-test
        framework.enterprise_valuation.valuation.checkpoint
        tests/finance_enterprise/test_valuation_checkpoint.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-valuation-replay-test
        framework.enterprise_valuation.valuation.replay
        tests/finance_enterprise/test_valuation_replay.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-distributed-job-test
        framework.enterprise_valuation.distributed.job
        tests/finance_enterprise/test_distributed_job.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-distributed-job-queue-test
        framework.enterprise_valuation.distributed.job.queue
        tests/finance_enterprise/test_distributed_job_queue.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-distributed-worker-test
        framework.enterprise_valuation.distributed.worker
        tests/finance_enterprise/test_distributed_worker.c
    )
    umicom_add_enterprise_valuation_risk_test(
        umicom-enterprise-enterprise-risk-service-test
        framework.enterprise_valuation.enterprise.risk.service
        tests/finance_enterprise/test_enterprise_risk_service.c
    )
endif()

message(STATUS "Umicom enterprise valuation grid, market data and portfolio risk platform enabled")
