# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-native-rename-sources-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_native_rename_sources.c")
    target_link_libraries(umicom-native-rename-sources-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-native-rename-sources-test)
    umicom_apply_sanitizers(umicom-native-rename-sources-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-native-rename-sources-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-native-rename-sources-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-native-rename-sources-test)
    endif()
    foreach(case valid all prepare unicode outside stale unknown query-error shutdown-error)
        add_test(NAME framework.language_runtime.native_rename_sources.${case} COMMAND umicom-native-rename-sources-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.language_runtime.native_rename_sources.${case} PROPERTIES TIMEOUT 40
            LABELS "framework;language;rename;native;ownership;regression")
    endforeach()
endif()
