#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomProjectWorkspacePlatform.cmake
# PURPOSE:
#   Extend the canonical developer/project platform with multi-root workspace,
#   project graph, CMake understanding, profiles, import/migration and complete
#   New Umicom Application generation control. No application owns this logic.
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)
set(UMICOM_PROJECT_WORKSPACE_FRAMEWORK_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
# Load the dependency only when the parent build has not already provided its target.
if(NOT TARGET umicom_developer)
    message(FATAL_ERROR "UmicomProjectWorkspacePlatform.cmake requires umicom_developer")
endif()
target_sources(umicom_developer PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_identity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_root.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_root_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_multi_root.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_membership.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_configuration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_profile_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_state.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_trust_bridge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_recent_projects.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_import_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_migration_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_identity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_graph.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_dependency_edge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_dependency_cycle.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_ordering.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_activation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_capability.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_metadata.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_detection_evidence.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_import_candidate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_migration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_variant.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_configuration_set.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/environment_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/environment_overlay.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/build_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/run_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/debug_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/test_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/package_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/deploy_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/profile_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/profile_selection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/cmake_model.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/cmake_target.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/cmake_target_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/cmake_preset.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/cmake_cache_entry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/cmake_option.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/cmake_source_group.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/cmake_dependency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/cmake_install_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/cmake_test_model.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/cmake_configure_model.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_template_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/project_template_filter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/application_blueprint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/application_component_selection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/application_feature_selection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/application_frontend_selection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/application_generator_request.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/application_generator_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/application_generation_validation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/application_generation_evidence.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/repository_bootstrap_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_command.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_event.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_query.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_json.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/project/workspace/workspace_resource_binding.c"
)
# Register verification targets only when the developer has enabled testing.
if(BUILD_TESTING)
    # Define the add project workspace test build helper so parent and application projects
    # apply one consistent rule.
    function(umicom_add_project_workspace_test target test_name source)
        # Configure the optional target only when its feature has created it.
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_PROJECT_WORKSPACE_FRAMEWORK_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::Framework)
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;project-workspace")
    endfunction()
    umicom_add_project_workspace_test(
        umicom-project-workspace-types-test
        framework.project_workspace.types
        tests/project_workspace/test_types.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-identity-test
        framework.project_workspace.workspace.identity
        tests/project_workspace/test_workspace_identity.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-root-test
        framework.project_workspace.workspace.root
        tests/project_workspace/test_workspace_root.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-root-catalogue-test
        framework.project_workspace.workspace.root.catalogue
        tests/project_workspace/test_workspace_root_catalogue.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-multi-root-test
        framework.project_workspace.workspace.multi.root
        tests/project_workspace/test_workspace_multi_root.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-membership-test
        framework.project_workspace.workspace.membership
        tests/project_workspace/test_workspace_membership.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-configuration-test
        framework.project_workspace.workspace.configuration
        tests/project_workspace/test_workspace_configuration.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-profile-test
        framework.project_workspace.workspace.profile
        tests/project_workspace/test_workspace_profile.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-profile-catalogue-test
        framework.project_workspace.workspace.profile.catalogue
        tests/project_workspace/test_workspace_profile_catalogue.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-session-test
        framework.project_workspace.workspace.session
        tests/project_workspace/test_workspace_session.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-state-test
        framework.project_workspace.workspace.state
        tests/project_workspace/test_workspace_state.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-health-test
        framework.project_workspace.workspace.health
        tests/project_workspace/test_workspace_health.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-policy-test
        framework.project_workspace.workspace.policy
        tests/project_workspace/test_workspace_policy.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-trust-bridge-test
        framework.project_workspace.workspace.trust.bridge
        tests/project_workspace/test_workspace_trust_bridge.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-recent-projects-test
        framework.project_workspace.workspace.recent.projects
        tests/project_workspace/test_workspace_recent_projects.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-import-plan-test
        framework.project_workspace.workspace.import.plan
        tests/project_workspace/test_workspace_import_plan.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-migration-plan-test
        framework.project_workspace.workspace.migration.plan
        tests/project_workspace/test_workspace_migration_plan.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-identity-test
        framework.project_workspace.project.identity
        tests/project_workspace/test_project_identity.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-catalogue-test
        framework.project_workspace.project.catalogue
        tests/project_workspace/test_project_catalogue.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-graph-test
        framework.project_workspace.project.graph
        tests/project_workspace/test_project_graph.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-dependency-edge-test
        framework.project_workspace.project.dependency.edge
        tests/project_workspace/test_project_dependency_edge.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-dependency-cycle-test
        framework.project_workspace.project.dependency.cycle
        tests/project_workspace/test_project_dependency_cycle.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-ordering-test
        framework.project_workspace.project.ordering
        tests/project_workspace/test_project_ordering.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-activation-test
        framework.project_workspace.project.activation
        tests/project_workspace/test_project_activation.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-capability-test
        framework.project_workspace.project.capability
        tests/project_workspace/test_project_capability.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-metadata-test
        framework.project_workspace.project.metadata
        tests/project_workspace/test_project_metadata.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-detection-evidence-test
        framework.project_workspace.project.detection.evidence
        tests/project_workspace/test_project_detection_evidence.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-import-candidate-test
        framework.project_workspace.project.import.candidate
        tests/project_workspace/test_project_import_candidate.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-migration-test
        framework.project_workspace.project.migration
        tests/project_workspace/test_project_migration.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-variant-test
        framework.project_workspace.project.variant
        tests/project_workspace/test_project_variant.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-configuration-set-test
        framework.project_workspace.project.configuration.set
        tests/project_workspace/test_project_configuration_set.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-environment-profile-test
        framework.project_workspace.environment.profile
        tests/project_workspace/test_environment_profile.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-environment-overlay-test
        framework.project_workspace.environment.overlay
        tests/project_workspace/test_environment_overlay.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-build-profile-test
        framework.project_workspace.build.profile
        tests/project_workspace/test_build_profile.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-run-profile-test
        framework.project_workspace.run.profile
        tests/project_workspace/test_run_profile.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-debug-profile-test
        framework.project_workspace.debug.profile
        tests/project_workspace/test_debug_profile.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-test-profile-test
        framework.project_workspace.test.profile
        tests/project_workspace/test_test_profile.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-package-profile-test
        framework.project_workspace.package.profile
        tests/project_workspace/test_package_profile.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-deploy-profile-test
        framework.project_workspace.deploy.profile
        tests/project_workspace/test_deploy_profile.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-profile-binding-test
        framework.project_workspace.profile.binding
        tests/project_workspace/test_profile_binding.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-profile-selection-test
        framework.project_workspace.profile.selection
        tests/project_workspace/test_profile_selection.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-cmake-model-test
        framework.project_workspace.cmake.model
        tests/project_workspace/test_cmake_model.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-cmake-target-test
        framework.project_workspace.cmake.target
        tests/project_workspace/test_cmake_target.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-cmake-target-catalogue-test
        framework.project_workspace.cmake.target.catalogue
        tests/project_workspace/test_cmake_target_catalogue.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-cmake-preset-test
        framework.project_workspace.cmake.preset
        tests/project_workspace/test_cmake_preset.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-cmake-cache-entry-test
        framework.project_workspace.cmake.cache.entry
        tests/project_workspace/test_cmake_cache_entry.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-cmake-option-test
        framework.project_workspace.cmake.option
        tests/project_workspace/test_cmake_option.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-cmake-source-group-test
        framework.project_workspace.cmake.source.group
        tests/project_workspace/test_cmake_source_group.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-cmake-dependency-test
        framework.project_workspace.cmake.dependency
        tests/project_workspace/test_cmake_dependency.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-cmake-install-rule-test
        framework.project_workspace.cmake.install.rule
        tests/project_workspace/test_cmake_install_rule.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-cmake-test-model-test
        framework.project_workspace.cmake.test.model
        tests/project_workspace/test_cmake_test_model.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-cmake-configure-model-test
        framework.project_workspace.cmake.configure.model
        tests/project_workspace/test_cmake_configure_model.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-template-catalogue-test
        framework.project_workspace.project.template.catalogue
        tests/project_workspace/test_project_template_catalogue.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-project-template-filter-test
        framework.project_workspace.project.template.filter
        tests/project_workspace/test_project_template_filter.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-application-blueprint-test
        framework.project_workspace.application.blueprint
        tests/project_workspace/test_application_blueprint.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-application-component-selection-test
        framework.project_workspace.application.component.selection
        tests/project_workspace/test_application_component_selection.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-application-feature-selection-test
        framework.project_workspace.application.feature.selection
        tests/project_workspace/test_application_feature_selection.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-application-frontend-selection-test
        framework.project_workspace.application.frontend.selection
        tests/project_workspace/test_application_frontend_selection.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-application-generator-request-test
        framework.project_workspace.application.generator.request
        tests/project_workspace/test_application_generator_request.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-application-generator-plan-test
        framework.project_workspace.application.generator.plan
        tests/project_workspace/test_application_generator_plan.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-application-generation-validation-test
        framework.project_workspace.application.generation.validation
        tests/project_workspace/test_application_generation_validation.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-application-generation-evidence-test
        framework.project_workspace.application.generation.evidence
        tests/project_workspace/test_application_generation_evidence.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-repository-bootstrap-plan-test
        framework.project_workspace.repository.bootstrap.plan
        tests/project_workspace/test_repository_bootstrap_plan.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-command-test
        framework.project_workspace.workspace.command
        tests/project_workspace/test_workspace_command.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-event-test
        framework.project_workspace.workspace.event
        tests/project_workspace/test_workspace_event.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-query-test
        framework.project_workspace.workspace.query
        tests/project_workspace/test_workspace_query.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-snapshot-test
        framework.project_workspace.workspace.snapshot
        tests/project_workspace/test_workspace_snapshot.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-json-test
        framework.project_workspace.workspace.json
        tests/project_workspace/test_workspace_json.c
    )
    umicom_add_project_workspace_test(
        umicom-project-workspace-workspace-resource-binding-test
        framework.project_workspace.workspace.resource.binding
        tests/project_workspace/test_workspace_resource_binding.c
    )
endif()
message(STATUS "Umicom project/workspace orchestration and application generation enabled")
