# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING AND TARGET umicom_creative_workspace_gtk4 AND (WIN32 OR UNIX) AND NOT EMSCRIPTEN)
    add_executable(umicom-creative-asset-gtk-test "${CMAKE_CURRENT_LIST_DIR}/../tests/creative_assets/test_asset_gtk4.c")
    target_link_libraries(umicom-creative-asset-gtk-test PRIVATE Umicom::creative_workspace_gtk4)
    umicom_creative_configure_target(umicom-creative-asset-gtk-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-creative-asset-gtk-test)
    endif()
    foreach(case capture invalid-capture independent clear retained-control load failed-load busy cancel copy pending-close media music web-studio mobile-studio)
        add_test(NAME framework.creative_assets.gtk.${case} COMMAND umicom-creative-asset-gtk-test ${case})
        set_tests_properties(framework.creative_assets.gtk.${case} PROPERTIES SKIP_RETURN_CODE 77 TIMEOUT 30 LABELS "framework;creative-assets;regression")
    endforeach()
endif()
