# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-file-search-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_file_search.c")
    target_link_libraries(umicom-document-file-search-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-file-search-test)
    umicom_apply_sanitizers(umicom-document-file-search-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-file-search-test)
    endif()
    foreach(case utf8 utf8-bom utf16-le utf16-be crlf cr mixed empty bom-only literal-bom unicode scalar-preview invalid-utf8 truncated-utf8 odd-utf16 lone-high lone-low invalid-pair binary decoded-null decoded-limit encoded-limit filter case-fold case-sensitive cancel stale-index changed-index sink-error session session-filter session-stale locate)
        add_test(NAME framework.document.file_search.${case} COMMAND umicom-document-file-search-test ${case})
        set_tests_properties(framework.document.file_search.${case} PROPERTIES TIMEOUT 45 LABELS "framework;search;unicode;ownership;regression")
    endforeach()
endif()
