# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/UmicomBuildReview.cmake")
get_filename_component(_umi_review_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(TARGET umicom_ui_gtk4)
    # The existing Framework GUI host owns this adapter; Studio only calls it.
    target_sources(umicom_ui_gtk4 PRIVATE "${_umi_review_root}/adapters/gtk4/build_review_gtk4.c")
    target_link_libraries(umicom_ui_gtk4 PUBLIC Umicom::build_review)
    set(_umi_review_gui Umicom::ui_gtk4)
else()
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(BUILD_REVIEW_GTK4 REQUIRED IMPORTED_TARGET gtk4>=4.10)
    add_library(umicom_build_review_gtk4 STATIC "${_umi_review_root}/adapters/gtk4/build_review_gtk4.c")
    target_link_libraries(umicom_build_review_gtk4 PUBLIC Umicom::build_review PkgConfig::BUILD_REVIEW_GTK4)
    set(_umi_review_gui umicom_build_review_gtk4)
    set_target_properties(umicom_build_review_gtk4 PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    if(COMMAND umicom_apply_warnings)
        umicom_apply_warnings(umicom_build_review_gtk4)
    endif()
    if(COMMAND umicom_apply_sanitizers)
        umicom_apply_sanitizers(umicom_build_review_gtk4)
    endif()
endif()
if(BUILD_TESTING)
    add_executable(umicom-build-review-gtk4-test "${_umi_review_root}/tests/build_review/test_gtk4.c")
    target_link_libraries(umicom-build-review-gtk4-test PRIVATE ${_umi_review_gui})
    set_target_properties(umicom-build-review-gtk4-test PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    foreach(_case lifecycle detached-owner retained-child filter empty invalid-record)
        add_test(NAME framework.build_review.gtk4.${_case} COMMAND umicom-build-review-gtk4-test ${_case})
        set_tests_properties(framework.build_review.gtk4.${_case} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77)
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-build-review-gtk4-test)
    endif()
    if(COMMAND umicom_apply_warnings)
        umicom_apply_warnings(umicom-build-review-gtk4-test)
    endif()
    if(COMMAND umicom_apply_sanitizers)
        umicom_apply_sanitizers(umicom-build-review-gtk4-test)
    endif()
endif()
unset(_umi_review_root)
unset(_umi_review_gui)
