# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
target_sources(umicom_platform PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/platform/secure_random.c")
if(WIN32)
    target_link_libraries(umicom_platform PRIVATE bcrypt)
endif()
if(BUILD_TESTING)
    add_executable(umicom-secure-random-test "${CMAKE_CURRENT_LIST_DIR}/../tests/platform/test_secure_random.c")
    target_link_libraries(umicom-secure-random-test PRIVATE Umicom::platform)
    umicom_apply_warnings(umicom-secure-random-test)
    umicom_apply_sanitizers(umicom-secure-random-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-secure-random-test)
    endif()
    foreach(case empty null capacity bounded single maximum)
        add_test(NAME framework.platform.secure_random.${case} COMMAND umicom-secure-random-test ${case})
        set_tests_properties(framework.platform.secure_random.${case} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;platform;random;bounds;regression")
    endforeach()
endif()
