# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-native-symbols-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_native_symbols.c")
    target_link_libraries(umicom-native-symbols-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-native-symbols-test)
    umicom_apply_sanitizers(umicom-native-symbols-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-native-symbols-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-native-symbols-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-native-symbols-test)
    endif()
    foreach(case valid unicode empty flat hierarchy error invalid timeout encoding shutdown cancel range surrogate unknown-kind)
        add_test(NAME framework.language_runtime.native_symbols.${case} COMMAND umicom-native-symbols-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.language_runtime.native_symbols.${case} PROPERTIES TIMEOUT 40
            LABELS "framework;language;symbols;native;ownership;regression")
    endforeach()
endif()
