# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_quick_open)
    if(NOT TARGET umicom_ui_gtk4)
        return()
    endif()
    get_target_property(attached umicom_ui_gtk4 UMICOM_QUICK_OPEN_ATTACHED)
    if(attached)
        return()
    endif()
    set_target_properties(umicom_ui_gtk4 PROPERTIES UMICOM_QUICK_OPEN_ATTACHED TRUE)
    target_sources(umicom_ui_gtk4 PRIVATE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../adapters/gtk4/quick_open_gtk4.c")
    if(BUILD_TESTING)
        add_executable(umicom-quick-open-selection-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/developer_workbench/test_quick_open_selection.c")
        target_link_libraries(umicom-quick-open-selection-test PRIVATE Umicom::developer PkgConfig::GLIB)
        umicom_apply_warnings(umicom-quick-open-selection-test)
        umicom_apply_sanitizers(umicom-quick-open-selection-test)
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(umicom-quick-open-selection-test)
        endif()
        foreach(case valid offset stale-revision changed-root changed-query changed-path changed-name changed-size changed-time invalid-position invalid-page unterminated zero-revision null-input)
            add_test(NAME framework.developer.quick_open.selection.${case} COMMAND umicom-quick-open-selection-test ${case})
            set_tests_properties(framework.developer.quick_open.selection.${case} PROPERTIES TIMEOUT 30 LABELS "framework;developer;quick-open;index;regression")
        endforeach()
    endif()
    include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/UmicomQuickOpenNativeChecks.cmake")
endfunction()
umicom_attach_quick_open()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_quick_open)
endif()

install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/learning/quick-open.html" DESTINATION "${CMAKE_INSTALL_DATADIR}/doc/umicom/learning" COMPONENT Development)
