#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomTerminalRemoteDevelopmentPlatform.cmake
#
# PURPOSE:
#   Extend the canonical terminal target with persistent terminal/process
#   supervision and Framework-owned remote-development contracts.
#
# ARCHITECTURE:
#   This is additive to umicom_terminal. It does not introduce a competing
#   terminal runtime, shell subsystem or application-owned remote layer.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)
set(UMICOM_TERMINAL_REMOTE_FRAMEWORK_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
# Load the dependency only when the parent build has not already provided its target.
if(NOT TARGET umicom_terminal)
    message(FATAL_ERROR "UmicomTerminalRemoteDevelopmentPlatform.cmake requires umicom_terminal")
endif()
target_sources(umicom_terminal PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_identity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/shell_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/shell_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_session_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_persistence.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_restore.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_reconnect.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_heartbeat.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_capability.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_environment_overlay.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_working_directory.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_command_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_command_history.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_output_chunk.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_output_backpressure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_input_queue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_resize.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_encoding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_link_detection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_task_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_process_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/terminal_workspace_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/process_identity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/process_tree.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/process_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/process_lifecycle.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/process_exit_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/process_restart_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/process_resource_budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/process_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/process_log_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/background_service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/service_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/service_dependency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/service_supervision.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/service_restart.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/service_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_endpoint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_auth_method.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_connection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_connection_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_connection_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_capability.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_handshake.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_heartbeat.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_reconnect.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_workspace.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_workspace_mount.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_path_mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_file_operation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_file_transfer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_environment.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_toolchain.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_command.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_process.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_terminal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_port_forward.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_port_forward_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_tunnel.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_task_execution.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_debug_bridge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/terminal/remote/remote_language_bridge.c"
)
# Register verification targets only when the developer has enabled testing.
if(BUILD_TESTING)
    # Define the add terminal remote test build helper so parent and application projects
    # apply one consistent rule.
    function(umicom_add_terminal_remote_test target test_name source)
        # Configure the optional target only when its feature has created it.
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_TERMINAL_REMOTE_FRAMEWORK_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::terminal)
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;terminal-remote")
    endfunction()
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-types-test
        framework.terminal_remote.types
        tests/terminal_remote/test_types.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-identity-test
        framework.terminal_remote.terminal.identity
        tests/terminal_remote/test_terminal_identity.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-shell-profile-test
        framework.terminal_remote.shell.profile
        tests/terminal_remote/test_shell_profile.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-shell-catalogue-test
        framework.terminal_remote.shell.catalogue
        tests/terminal_remote/test_shell_catalogue.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-session-test
        framework.terminal_remote.terminal.session
        tests/terminal_remote/test_terminal_session.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-session-catalogue-test
        framework.terminal_remote.terminal.session.catalogue
        tests/terminal_remote/test_terminal_session_catalogue.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-persistence-test
        framework.terminal_remote.terminal.persistence
        tests/terminal_remote/test_terminal_persistence.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-restore-test
        framework.terminal_remote.terminal.restore
        tests/terminal_remote/test_terminal_restore.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-reconnect-test
        framework.terminal_remote.terminal.reconnect
        tests/terminal_remote/test_terminal_reconnect.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-heartbeat-test
        framework.terminal_remote.terminal.heartbeat
        tests/terminal_remote/test_terminal_heartbeat.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-health-test
        framework.terminal_remote.terminal.health
        tests/terminal_remote/test_terminal_health.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-capability-test
        framework.terminal_remote.terminal.capability
        tests/terminal_remote/test_terminal_capability.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-environment-overlay-test
        framework.terminal_remote.terminal.environment.overlay
        tests/terminal_remote/test_terminal_environment_overlay.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-working-directory-test
        framework.terminal_remote.terminal.working.directory
        tests/terminal_remote/test_terminal_working_directory.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-command-policy-test
        framework.terminal_remote.terminal.command.policy
        tests/terminal_remote/test_terminal_command_policy.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-command-history-test
        framework.terminal_remote.terminal.command.history
        tests/terminal_remote/test_terminal_command_history.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-output-chunk-test
        framework.terminal_remote.terminal.output.chunk
        tests/terminal_remote/test_terminal_output_chunk.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-output-backpressure-test
        framework.terminal_remote.terminal.output.backpressure
        tests/terminal_remote/test_terminal_output_backpressure.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-input-queue-test
        framework.terminal_remote.terminal.input.queue
        tests/terminal_remote/test_terminal_input_queue.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-resize-test
        framework.terminal_remote.terminal.resize
        tests/terminal_remote/test_terminal_resize.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-encoding-test
        framework.terminal_remote.terminal.encoding
        tests/terminal_remote/test_terminal_encoding.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-link-detection-test
        framework.terminal_remote.terminal.link.detection
        tests/terminal_remote/test_terminal_link_detection.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-task-binding-test
        framework.terminal_remote.terminal.task.binding
        tests/terminal_remote/test_terminal_task_binding.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-process-binding-test
        framework.terminal_remote.terminal.process.binding
        tests/terminal_remote/test_terminal_process_binding.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-terminal-workspace-binding-test
        framework.terminal_remote.terminal.workspace.binding
        tests/terminal_remote/test_terminal_workspace_binding.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-process-identity-test
        framework.terminal_remote.process.identity
        tests/terminal_remote/test_process_identity.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-process-tree-test
        framework.terminal_remote.process.tree
        tests/terminal_remote/test_process_tree.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-process-snapshot-test
        framework.terminal_remote.process.snapshot
        tests/terminal_remote/test_process_snapshot.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-process-lifecycle-test
        framework.terminal_remote.process.lifecycle
        tests/terminal_remote/test_process_lifecycle.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-process-exit-policy-test
        framework.terminal_remote.process.exit.policy
        tests/terminal_remote/test_process_exit_policy.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-process-restart-policy-test
        framework.terminal_remote.process.restart.policy
        tests/terminal_remote/test_process_restart_policy.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-process-resource-budget-test
        framework.terminal_remote.process.resource.budget
        tests/terminal_remote/test_process_resource_budget.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-process-health-test
        framework.terminal_remote.process.health
        tests/terminal_remote/test_process_health.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-process-log-binding-test
        framework.terminal_remote.process.log.binding
        tests/terminal_remote/test_process_log_binding.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-background-service-test
        framework.terminal_remote.background.service
        tests/terminal_remote/test_background_service.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-service-catalogue-test
        framework.terminal_remote.service.catalogue
        tests/terminal_remote/test_service_catalogue.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-service-dependency-test
        framework.terminal_remote.service.dependency
        tests/terminal_remote/test_service_dependency.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-service-supervision-test
        framework.terminal_remote.service.supervision
        tests/terminal_remote/test_service_supervision.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-service-restart-test
        framework.terminal_remote.service.restart
        tests/terminal_remote/test_service_restart.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-service-health-test
        framework.terminal_remote.service.health
        tests/terminal_remote/test_service_health.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-endpoint-test
        framework.terminal_remote.remote.endpoint
        tests/terminal_remote/test_remote_endpoint.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-auth-method-test
        framework.terminal_remote.remote.auth.method
        tests/terminal_remote/test_remote_auth_method.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-connection-test
        framework.terminal_remote.remote.connection
        tests/terminal_remote/test_remote_connection.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-connection-catalogue-test
        framework.terminal_remote.remote.connection.catalogue
        tests/terminal_remote/test_remote_connection_catalogue.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-connection-policy-test
        framework.terminal_remote.remote.connection.policy
        tests/terminal_remote/test_remote_connection_policy.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-capability-test
        framework.terminal_remote.remote.capability
        tests/terminal_remote/test_remote_capability.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-handshake-test
        framework.terminal_remote.remote.handshake
        tests/terminal_remote/test_remote_handshake.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-heartbeat-test
        framework.terminal_remote.remote.heartbeat
        tests/terminal_remote/test_remote_heartbeat.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-reconnect-test
        framework.terminal_remote.remote.reconnect
        tests/terminal_remote/test_remote_reconnect.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-health-test
        framework.terminal_remote.remote.health
        tests/terminal_remote/test_remote_health.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-workspace-test
        framework.terminal_remote.remote.workspace
        tests/terminal_remote/test_remote_workspace.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-workspace-mount-test
        framework.terminal_remote.remote.workspace.mount
        tests/terminal_remote/test_remote_workspace_mount.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-path-mapping-test
        framework.terminal_remote.remote.path.mapping
        tests/terminal_remote/test_remote_path_mapping.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-file-operation-test
        framework.terminal_remote.remote.file.operation
        tests/terminal_remote/test_remote_file_operation.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-file-transfer-test
        framework.terminal_remote.remote.file.transfer
        tests/terminal_remote/test_remote_file_transfer.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-environment-test
        framework.terminal_remote.remote.environment
        tests/terminal_remote/test_remote_environment.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-toolchain-test
        framework.terminal_remote.remote.toolchain
        tests/terminal_remote/test_remote_toolchain.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-command-test
        framework.terminal_remote.remote.command
        tests/terminal_remote/test_remote_command.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-process-test
        framework.terminal_remote.remote.process
        tests/terminal_remote/test_remote_process.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-terminal-test
        framework.terminal_remote.remote.terminal
        tests/terminal_remote/test_remote_terminal.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-port-forward-test
        framework.terminal_remote.remote.port.forward
        tests/terminal_remote/test_remote_port_forward.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-port-forward-catalogue-test
        framework.terminal_remote.remote.port.forward.catalogue
        tests/terminal_remote/test_remote_port_forward_catalogue.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-tunnel-test
        framework.terminal_remote.remote.tunnel
        tests/terminal_remote/test_remote_tunnel.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-task-execution-test
        framework.terminal_remote.remote.task.execution
        tests/terminal_remote/test_remote_task_execution.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-debug-bridge-test
        framework.terminal_remote.remote.debug.bridge
        tests/terminal_remote/test_remote_debug_bridge.c
    )
    umicom_add_terminal_remote_test(
        umicom-terminal-remote-remote-language-bridge-test
        framework.terminal_remote.remote.language.bridge
        tests/terminal_remote/test_remote_language_bridge.c
    )
endif()
message(STATUS "Umicom persistent terminal, process supervision and remote development enabled")
