# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-action-filter-query-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_action_filter_query.c")
    target_link_libraries(umicom-action-filter-query-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-action-filter-query-test)
    umicom_apply_sanitizers(umicom-action-filter-query-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-action-filter-query-test)
    endif()
    foreach(case all quickfix refactor imports fix-all descendants prefix-boundary missing-kind empty-response ignored-filter notification pull no-diagnostics primary-only raw disabled command deferred malformed-unrelated invalid-filter negative-filter null-options invalid-mode duplicate-source invalid-source cancel-before close-error shutdown-error action-error fragmented)
        add_test(NAME framework.language_runtime.action_filter_query.${case} COMMAND umicom-action-filter-query-test ${case})
        set_tests_properties(framework.language_runtime.action_filter_query.${case} PROPERTIES TIMEOUT 30
            LABELS "framework;language;diagnostic;ownership;regression")
    endforeach()
endif()
