# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Explicit ownership and consumer-side compilation extend the existing release
# inventory; header naming alone never grants ownership to a target.
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/UmicomPublicHeaderCompileChecks.cmake")
option(UMICOM_RELEASE_HEADER_CHECKS "Provide independent C23 compilation for declared public headers" OFF)

function(_umicom_release_declare_pair target header source)
    if(NOT TARGET "${target}")
        return()
    endif()
    get_property(_imported TARGET "${target}" PROPERTY IMPORTED)
    get_property(_alias TARGET "${target}" PROPERTY ALIASED_TARGET)
    if(_imported OR _alias)
        return()
    endif()
    get_property(_root GLOBAL PROPERTY UMICOM_RELEASE_INVENTORY_ROOT)
    file(REAL_PATH "${_root}/${source}" _anchor)
    if(NOT EXISTS "${_anchor}")
        return()
    endif()
    get_property(_directory TARGET "${target}" PROPERTY SOURCE_DIR)
    get_property(_sources TARGET "${target}" PROPERTY SOURCES)
    foreach(_source IN LISTS _sources)
        if(_source MATCHES "\\$<")
            continue()
        endif()
        file(REAL_PATH "${_source}" _actual BASE_DIRECTORY "${_directory}")
        if(_actual STREQUAL _anchor)
            umicom_release_inventory_own_headers("${target}" "${header}")
            return()
        endif()
    endforeach()
    # Focused builds may deliberately omit the implementation. Keep its header
    # unassigned in that build rather than attributing an absent capability.
endfunction()

function(umicom_release_contracts_prepare)
    get_property(_prepared GLOBAL PROPERTY UMICOM_RELEASE_CONTRACTS_PREPARED)
    if(_prepared)
        return()
    endif()
    set_property(GLOBAL PROPERTY UMICOM_RELEASE_CONTRACTS_PREPARED TRUE)
    # These explicit source/header pairs were inspected at the canonical owner.
    # They describe build ownership only, not symbol/ABI or runtime acceptance.
    foreach(_name IN ITEMS result memory text)
        _umicom_release_declare_pair(umicom_base "include/umicom/base/${_name}.h" "src/base/${_name}.c")
    endforeach()
    # version.h is a type-only base contract consumed by the runtime registry.
    _umicom_release_declare_pair(umicom_base include/umicom/base/version.h src/base/status.c)
    foreach(_name IN ITEMS config path directory cancellation settings filesystem atomic_file
            threading task task_queue process process_supervisor watcher workspace document
            document_store workspace_graph workspace_files file_index search search_session
            session_store recovery clock recent_items bookmarks resource_location workspace_history
            file_operation_queue resource_centre)
        _umicom_release_declare_pair(umicom_platform "include/umicom/platform/${_name}.h" "src/platform/${_name}.c")
    endforeach()
    foreach(_name IN ITEMS capability_registry capability_catalogue service_registry command_registry
            inventory contract health application_manifest suite module_registry master_controller scheduler)
        _umicom_release_declare_pair(umicom_runtime "include/umicom/runtime/${_name}.h" "src/runtime/${_name}.c")
    endforeach()
    _umicom_release_declare_pair(umicom_source_contracts include/umicom/source_contracts/source_contracts.h src/source_contracts/metadata.c)
    # Full SDK builds declare additional snapshot contracts only when each
    # canonical owner actually compiles its implementation source.
    if(COMMAND umicom_snapshot_contracts_declare_headers)
        umicom_snapshot_contracts_declare_headers()
    endif()
    if(NOT UMICOM_RELEASE_HEADER_CHECKS)
        return()
    endif()
    get_property(_root GLOBAL PROPERTY UMICOM_RELEASE_INVENTORY_ROOT)
    file(REAL_PATH "${_root}/include" _include)
    set(_output "${CMAKE_BINARY_DIR}/release-inventory/header-checks")
    file(MAKE_DIRECTORY "${_output}")
    add_custom_target(umicom-public-header-checks)
    file(WRITE "${_output}/manifest.tsv" "header\towner\tcompile-target\n")
    get_property(_owners GLOBAL PROPERTY UMICOM_RELEASE_HEADER_OWNERS)
    list(REMOVE_DUPLICATES _owners)
    set(_count 0)
    foreach(_owner IN LISTS _owners)
        get_property(_headers TARGET "${_owner}" PROPERTY UMICOM_RELEASE_PUBLIC_HEADERS)
        list(REMOVE_DUPLICATES _headers)
        foreach(_header IN LISTS _headers)
            file(RELATIVE_PATH _relative "${_include}" "${_header}")
            string(SHA256 _key "${_owner}\n${_relative}")
            set(_target "umicom-header-${_key}")
            umicom_add_public_header_compile_check("${_target}" "${_owner}" "${_include}" "${_header}")
            add_dependencies(umicom-public-header-checks "${_target}")
            file(APPEND "${_output}/manifest.tsv" "${_relative}\t${_owner}\t${_target}\n")
            math(EXPR _count "${_count} + 1")
        endforeach()
    endforeach()
    if(_count EQUAL 0)
        message(FATAL_ERROR "No declared public headers are available for compiler checks")
    endif()
    message(STATUS "Public-header compiler checks prepared for ${_count} declared headers; not yet executed")
endfunction()

function(umicom_release_policy_attach)
    get_property(_done TARGET umicom_distribution PROPERTY UMICOM_RELEASE_POLICY_ATTACHED)
    if(_done)
        return()
    endif()
    set_property(TARGET umicom_distribution PROPERTY UMICOM_RELEASE_POLICY_ATTACHED TRUE)
    get_property(_root GLOBAL PROPERTY UMICOM_RELEASE_INVENTORY_ROOT)
    target_sources(umicom_distribution PRIVATE "${_root}/src/distribution/runtime/test_policy.c" "${_root}/src/distribution/runtime/test_policy_text.c")
    target_sources(umicom-release-inventory PRIVATE "${_root}/tools/release_inventory/policy_cli.c")
    umicom_release_inventory_own_headers(umicom_distribution include/umicom/distribution/runtime/test_policy.h)
    include(GNUInstallDirs)
    install(FILES "${_root}/include/umicom/distribution/runtime/test_policy.h"
        DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/umicom/distribution/runtime COMPONENT Framework)
    install(FILES "${_root}/docs/learning/review-test-requirements.md" "${_root}/docs/learning/compile-public-headers.md"
        DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/learning COMPONENT Learning)
    install(FILES "${_root}/cmake/UmicomPublicHeaderCompileChecks.cmake"
        DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/cmake COMPONENT Framework)
    if(BUILD_TESTING)
        include("${_root}/tests/release_policy/CMakeLists.txt")
    endif()
endfunction()
