# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-line-edit-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_line_edit.c")
    target_link_libraries(umicom-document-line-edit-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-line-edit-test)
    umicom_apply_sanitizers(umicom-document-line-edit-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-line-edit-test)
    endif()
    foreach(case delete duplicate move-up move-down join indent outdent comment trim selected-indent selected-comment caret-only crlf unicode empty pending-typing read-only invalid-kind invalid-token no-neighbor no-change bare-cr closed null-owner undo-redo selection-history other-tab)
        add_test(NAME framework.document.line_edit.${case} COMMAND umicom-document-line-edit-test ${case})
        set_tests_properties(framework.document.line_edit.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;line-edit;history;regression")
    endforeach()
endif()
