# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING AND (WIN32 OR UNIX) AND NOT EMSCRIPTEN)
    add_executable(umicom-web-static-preview-test "${CMAKE_CURRENT_LIST_DIR}/../tests/web/test_static_preview.c")
    target_link_libraries(umicom-web-static-preview-test PRIVATE Umicom::web)
    umicom_apply_warnings(umicom-web-static-preview-test)
    umicom_apply_sanitizers(umicom-web-static-preview-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-web-static-preview-test)
    endif()
    foreach(case index directory-index html css binary unicode space decode-once empty exact-limit oversized missing missing-parent directory traversal encoded-traversal encoded-slash encoded-backslash raw-backslash nul bad-percent query fragment metadata device double-slash dot-segment trailing-dot relative-root root-overflow root-copy invalid-descriptor path-overflow head post fallback exact-priority exact-failure fallback-clear leaf-link parent-link root-link)
        add_test(NAME framework.web.static_preview.${case} COMMAND umicom-web-static-preview-test ${case})
        set_tests_properties(framework.web.static_preview.${case} PROPERTIES SKIP_RETURN_CODE 77 TIMEOUT 30 LABELS "framework;web;http;regression")
    endforeach()
endif()
