#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomDeveloperIntelligenceWorkbenchPlatform.cmake
#
# PURPOSE:
#   Compose the established Language Intelligence, Editor Intelligence, AI
#   Coding, RAG/Knowledge and AI Teacher engines into one Framework-owned
#   developer-intelligence workbench policy catalogue.
#
# ARCHITECTURE:
#   Existing engines remain authoritative. This layer adds bounded ranking,
#   routing, freshness, budgeting, trust and approval orchestration used by
#   Studio and future developer applications.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

if(NOT TARGET umicom_developer)
    message(FATAL_ERROR
        "Developer Intelligence Workbench requires canonical umicom_developer")
endif()
if(NOT TARGET umicom_language)
    message(FATAL_ERROR
        "Developer Intelligence Workbench requires canonical umicom_language")
endif()
if(NOT TARGET Umicom::ai)
    message(FATAL_ERROR
        "Developer Intelligence Workbench requires canonical Umicom::ai")
endif()

target_sources(umicom_developer PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/developer_intelligence_internal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/assembly_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/c23_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/call_hierarchy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/code_action_rank.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/code_lens.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/compilation_database.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/completion_context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/completion_prefix.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/completion_rank.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/cpp_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/declaration_route.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/diagnostic_dedupe.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/diagnostic_merge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/document_link.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/formatting_range.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/hover_merge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/implementation_route.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/include_graph.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/inlay_hint_rank.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/inline_value.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/linked_editing.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/project_template_score.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/provider_failover.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/provider_selection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/refactor_preview.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/reference_rank.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/rename_conflict.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/rename_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/request_budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/request_priority.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/response_freshness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/selection_range.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/semantic_token_delta.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/semantic_token_range.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/signature_active_parameter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/symbol_rank.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/symbol_search.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/type_definition_route.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/type_hierarchy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/language/workspace_edit_validation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/agent_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/agent_step.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/approval_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/change_review.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/checkpoint_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/citation_coverage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/citation_rank.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/code_completion.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/code_explanation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/code_refactor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/code_review.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/code_test_generation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/context_budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/context_source_rank.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/conversation_memory.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/edit_risk.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/local_runtime_route.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/model_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/model_route.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/privacy_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/prompt_budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/provider_fallback.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/rag_collection_rank.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/rag_source_rank.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/repository_change.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/repository_index.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/rerank_score.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/retrieval_fusion.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/retrieval_lexical.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/retrieval_vector.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/teacher_assessment.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/teacher_gap.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/teacher_hint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/teacher_mastery.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/teacher_progress.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/teacher_recommendation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/teacher_study_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/tool_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/tool_risk.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_intelligence/ai/workspace_memory.c"
)

target_link_libraries(umicom_developer PUBLIC
    Umicom::language
    Umicom::ai
)

if(BUILD_TESTING)
    function(umicom_add_developer_intelligence_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()

        add_executable(
            "${target}"
            "${CMAKE_CURRENT_LIST_DIR}/../tests/developer_intelligence/${source}"
        )
        target_link_libraries("${target}" PRIVATE Umicom::Framework)

        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()

        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()

        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties(
            "${test_name}"
            PROPERTIES LABELS
            "framework;developer-intelligence;language;ai;rag;teacher"
        )
    endfunction()

    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-types-test
        framework.developer_intelligence.types
        test_types.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-service-test
        framework.developer_intelligence.service
        test_service.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-assembly-profile-test
        framework.developer_intelligence.language.assembly.profile
        test_language_assembly_profile.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-c23-profile-test
        framework.developer_intelligence.language.c23.profile
        test_language_c23_profile.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-call-hierarchy-test
        framework.developer_intelligence.language.call.hierarchy
        test_language_call_hierarchy.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-code-action-rank-test
        framework.developer_intelligence.language.code.action.rank
        test_language_code_action_rank.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-code-lens-test
        framework.developer_intelligence.language.code.lens
        test_language_code_lens.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-compilation-database-test
        framework.developer_intelligence.language.compilation.database
        test_language_compilation_database.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-completion-context-test
        framework.developer_intelligence.language.completion.context
        test_language_completion_context.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-completion-prefix-test
        framework.developer_intelligence.language.completion.prefix
        test_language_completion_prefix.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-completion-rank-test
        framework.developer_intelligence.language.completion.rank
        test_language_completion_rank.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-cpp-profile-test
        framework.developer_intelligence.language.cpp.profile
        test_language_cpp_profile.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-declaration-route-test
        framework.developer_intelligence.language.declaration.route
        test_language_declaration_route.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-diagnostic-dedupe-test
        framework.developer_intelligence.language.diagnostic.dedupe
        test_language_diagnostic_dedupe.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-diagnostic-merge-test
        framework.developer_intelligence.language.diagnostic.merge
        test_language_diagnostic_merge.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-document-link-test
        framework.developer_intelligence.language.document.link
        test_language_document_link.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-formatting-range-test
        framework.developer_intelligence.language.formatting.range
        test_language_formatting_range.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-hover-merge-test
        framework.developer_intelligence.language.hover.merge
        test_language_hover_merge.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-implementation-route-test
        framework.developer_intelligence.language.implementation.route
        test_language_implementation_route.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-include-graph-test
        framework.developer_intelligence.language.include.graph
        test_language_include_graph.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-inlay-hint-rank-test
        framework.developer_intelligence.language.inlay.hint.rank
        test_language_inlay_hint_rank.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-inline-value-test
        framework.developer_intelligence.language.inline.value
        test_language_inline_value.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-linked-editing-test
        framework.developer_intelligence.language.linked.editing
        test_language_linked_editing.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-project-template-score-test
        framework.developer_intelligence.language.project.template.score
        test_language_project_template_score.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-provider-failover-test
        framework.developer_intelligence.language.provider.failover
        test_language_provider_failover.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-provider-selection-test
        framework.developer_intelligence.language.provider.selection
        test_language_provider_selection.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-refactor-preview-test
        framework.developer_intelligence.language.refactor.preview
        test_language_refactor_preview.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-reference-rank-test
        framework.developer_intelligence.language.reference.rank
        test_language_reference_rank.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-rename-conflict-test
        framework.developer_intelligence.language.rename.conflict
        test_language_rename_conflict.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-rename-plan-test
        framework.developer_intelligence.language.rename.plan
        test_language_rename_plan.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-request-budget-test
        framework.developer_intelligence.language.request.budget
        test_language_request_budget.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-request-priority-test
        framework.developer_intelligence.language.request.priority
        test_language_request_priority.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-response-freshness-test
        framework.developer_intelligence.language.response.freshness
        test_language_response_freshness.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-selection-range-test
        framework.developer_intelligence.language.selection.range
        test_language_selection_range.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-semantic-token-delta-test
        framework.developer_intelligence.language.semantic.token.delta
        test_language_semantic_token_delta.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-semantic-token-range-test
        framework.developer_intelligence.language.semantic.token.range
        test_language_semantic_token_range.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-signature-active-parameter-test
        framework.developer_intelligence.language.signature.active.parameter
        test_language_signature_active_parameter.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-symbol-rank-test
        framework.developer_intelligence.language.symbol.rank
        test_language_symbol_rank.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-symbol-search-test
        framework.developer_intelligence.language.symbol.search
        test_language_symbol_search.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-type-definition-route-test
        framework.developer_intelligence.language.type.definition.route
        test_language_type_definition_route.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-type-hierarchy-test
        framework.developer_intelligence.language.type.hierarchy
        test_language_type_hierarchy.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-language-workspace-edit-validation-test
        framework.developer_intelligence.language.workspace.edit.validation
        test_language_workspace_edit_validation.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-agent-plan-test
        framework.developer_intelligence.ai.agent.plan
        test_ai_agent_plan.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-agent-step-test
        framework.developer_intelligence.ai.agent.step
        test_ai_agent_step.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-approval-gate-test
        framework.developer_intelligence.ai.approval.gate
        test_ai_approval_gate.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-change-review-test
        framework.developer_intelligence.ai.change.review
        test_ai_change_review.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-checkpoint-policy-test
        framework.developer_intelligence.ai.checkpoint.policy
        test_ai_checkpoint_policy.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-citation-coverage-test
        framework.developer_intelligence.ai.citation.coverage
        test_ai_citation_coverage.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-citation-rank-test
        framework.developer_intelligence.ai.citation.rank
        test_ai_citation_rank.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-code-completion-test
        framework.developer_intelligence.ai.code.completion
        test_ai_code_completion.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-code-explanation-test
        framework.developer_intelligence.ai.code.explanation
        test_ai_code_explanation.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-code-refactor-test
        framework.developer_intelligence.ai.code.refactor
        test_ai_code_refactor.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-code-review-test
        framework.developer_intelligence.ai.code.review
        test_ai_code_review.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-code-test-generation-test
        framework.developer_intelligence.ai.code.test.generation
        test_ai_code_test_generation.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-context-budget-test
        framework.developer_intelligence.ai.context.budget
        test_ai_context_budget.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-context-source-rank-test
        framework.developer_intelligence.ai.context.source.rank
        test_ai_context_source_rank.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-conversation-memory-test
        framework.developer_intelligence.ai.conversation.memory
        test_ai_conversation_memory.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-edit-risk-test
        framework.developer_intelligence.ai.edit.risk
        test_ai_edit_risk.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-local-runtime-route-test
        framework.developer_intelligence.ai.local.runtime.route
        test_ai_local_runtime_route.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-model-health-test
        framework.developer_intelligence.ai.model.health
        test_ai_model_health.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-model-route-test
        framework.developer_intelligence.ai.model.route
        test_ai_model_route.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-privacy-policy-test
        framework.developer_intelligence.ai.privacy.policy
        test_ai_privacy_policy.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-prompt-budget-test
        framework.developer_intelligence.ai.prompt.budget
        test_ai_prompt_budget.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-provider-fallback-test
        framework.developer_intelligence.ai.provider.fallback
        test_ai_provider_fallback.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-rag-collection-rank-test
        framework.developer_intelligence.ai.rag.collection.rank
        test_ai_rag_collection_rank.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-rag-source-rank-test
        framework.developer_intelligence.ai.rag.source.rank
        test_ai_rag_source_rank.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-repository-change-test
        framework.developer_intelligence.ai.repository.change
        test_ai_repository_change.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-repository-index-test
        framework.developer_intelligence.ai.repository.index
        test_ai_repository_index.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-rerank-score-test
        framework.developer_intelligence.ai.rerank.score
        test_ai_rerank_score.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-retrieval-fusion-test
        framework.developer_intelligence.ai.retrieval.fusion
        test_ai_retrieval_fusion.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-retrieval-lexical-test
        framework.developer_intelligence.ai.retrieval.lexical
        test_ai_retrieval_lexical.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-retrieval-vector-test
        framework.developer_intelligence.ai.retrieval.vector
        test_ai_retrieval_vector.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-teacher-assessment-test
        framework.developer_intelligence.ai.teacher.assessment
        test_ai_teacher_assessment.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-teacher-gap-test
        framework.developer_intelligence.ai.teacher.gap
        test_ai_teacher_gap.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-teacher-hint-test
        framework.developer_intelligence.ai.teacher.hint
        test_ai_teacher_hint.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-teacher-mastery-test
        framework.developer_intelligence.ai.teacher.mastery
        test_ai_teacher_mastery.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-teacher-progress-test
        framework.developer_intelligence.ai.teacher.progress
        test_ai_teacher_progress.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-teacher-recommendation-test
        framework.developer_intelligence.ai.teacher.recommendation
        test_ai_teacher_recommendation.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-teacher-study-plan-test
        framework.developer_intelligence.ai.teacher.study.plan
        test_ai_teacher_study_plan.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-tool-policy-test
        framework.developer_intelligence.ai.tool.policy
        test_ai_tool_policy.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-tool-risk-test
        framework.developer_intelligence.ai.tool.risk
        test_ai_tool_risk.c
    )
    umicom_add_developer_intelligence_test(
        umicom-developer-intelligence-ai-workspace-memory-test
        framework.developer_intelligence.ai.workspace.memory
        test_ai_workspace_memory.c
    )
endif()

message(STATUS
    "Umicom Language + AI Developer Intelligence Workbench enabled")
