# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
# Reuse canonical operations, reviews and CSV ownership for reservation evidence.
target_sources(umicom_bank_operations PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/bank_operations/reservations.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/bank_operations/reservations_text.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/bank_operations/reservations_csv.c")
if(BUILD_TESTING)
    function(umicom_reservation_cases group)
        set(target "umicom-bank-reservations-${group}-test")
        add_executable(${target} "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/bank_reservations/test_${group}.c")
        target_link_libraries(${target} PRIVATE Umicom::bank_operations)
        umicom_bank_review_target(${target})
        foreach(case IN LISTS ARGN)
            add_test(NAME "framework.bank_reservations.${group}.${case}" COMMAND ${target} "${case}")
            set_tests_properties("framework.bank_reservations.${group}.${case}" PROPERTIES TIMEOUT 60 LABELS "bank;reservations;regression")
        endforeach()
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(${target})
        endif()
    endfunction()
    umicom_reservation_cases(capture all empty approved released voided captured refunded cancelled executed unknown invalid destination ownership bounds)
    umicom_reservation_cases(release manual card transfer execution-stale permission other-maker wrong-id wrong-action wrong-revision stale foreign)
    umicom_reservation_cases(reports text capacity csv immutable empty)
    umicom_reservation_cases(hold_review place authorise capture refund)
    umicom_reservation_cases(capacity full large)
    umicom_reservation_cases(storage)
    foreach(case reopen external-write reload)
        add_test(NAME "framework.bank_reservations.storage.${case}" COMMAND umicom-bank-reservations-storage-test "${case}"
            "${CMAKE_CURRENT_BINARY_DIR}/bank-reservations-${case}.sqlite")
        set_tests_properties("framework.bank_reservations.storage.${case}" PROPERTIES TIMEOUT 90 SKIP_RETURN_CODE 77 LABELS "bank;reservations;sqlite;regression")
    endforeach()
    if(TARGET umicom-bank-interest-native-test)
        foreach(case account copy cached close manual card transfer permission stale invalidate)
            add_test(NAME "framework.bank_reservations.native.${case}" COMMAND umicom-bank-interest-native-test "reservations-${case}")
            set_tests_properties("framework.bank_reservations.native.${case}" PROPERTIES TIMEOUT 90 SKIP_RETURN_CODE 77 LABELS "bank;reservations;gtk4;regression")
        endforeach()
    endif()
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/BANK_RESERVED_FUNDS.md" DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom-framework/docs)
