# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-format-owner-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_document_format.c")
    target_link_libraries(umicom-document-format-owner-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-format-owner-test)
    umicom_apply_sanitizers(umicom-document-format-owner-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-format-owner-test)
    endif()
    foreach(case lf crlf bare-cr unicode selection final empty encoding-only utf8-bom utf16-le utf16-be same-format pending-typing undo-redo ordinary-after-format redo-cleared read-only identity invalid-encoding invalid-ending invalid-final closed null-options)
        add_test(NAME framework.document.format_owner.${case} COMMAND umicom-document-format-owner-test ${case})
        set_tests_properties(framework.document.format_owner.${case} PROPERTIES TIMEOUT 45 LABELS "framework;document;format;history;regression")
    endforeach()
endif()
