# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-native-action-filter-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_native_action_filter.c")
    target_link_libraries(umicom-native-action-filter-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-native-action-filter-test)
    umicom_apply_sanitizers(umicom-native-action-filter-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-native-action-filter-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-native-action-filter-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-native-action-filter-test)
    endif()
    foreach(case valid all unicode outside stale unknown query-error shutdown-error disabled command empty-context diagnostic-error unchanged related-report quickfix refactor fix-all descendants ignored prefix-boundary malformed-unrelated choices)
        add_test(NAME framework.language_runtime.native_action_filter.${case} COMMAND umicom-native-action-filter-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.language_runtime.native_action_filter.${case} PROPERTIES TIMEOUT 40
            LABELS "framework;language;rename;native;ownership;regression")
    endforeach()
endif()
