#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomCrossPlatformDistributionPlatform.cmake
#
# PURPOSE:
#   Extend the canonical distribution target with cross-platform runtime, bundle,
#   package, installer, update, rollback, release and deployment control state.
#
# ARCHITECTURE:
#   Existing Umicom::distribution and Umicom::delivery remain authoritative.
#   This platform adds reusable cross-platform packaging/distribution policy and
#   does not move installer/update logic into individual applications.
#
# Created by: Sammy Hegab
# Organisation: Umicom Foundation
# Licence: MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_CROSS_PLATFORM_DISTRIBUTION_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
if(NOT TARGET umicom_distribution)
    message(FATAL_ERROR "UmicomCrossPlatformDistributionPlatform.cmake requires umicom_distribution")
endif()

target_sources(umicom_distribution PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/platform_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/platform_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/architecture_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/architecture_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/runtime_capability.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/runtime_probe.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/runtime_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/runtime_selector.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/runtime_compatibility.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/application_manifest.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/application_identity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/application_variant.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/application_bundle.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/bundle_file.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/bundle_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/bundle_manifest.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/bundle_layout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/resource_manifest.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/resource_pack.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/resource_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/dependency_manifest.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/dependency_resolution.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/dependency_bundle.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/runtime_dependency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/launcher_manifest.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/launch_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/environment_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/filesystem_layout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/path_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/executable_layout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/library_layout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/data_layout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/cache_layout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/configuration_layout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/package_format.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/package_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/package_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/installer_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/portable_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/archive_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/symbol_package.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/debug_package.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/source_package.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/sdk_package.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/component_package.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/package_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/channel.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/channel_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/update_manifest.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/update_candidate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/update_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/update_rollout.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/update_transaction.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/delta_package.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/rollback_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/install_state.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/install_receipt.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/install_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/signature_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/checksum_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/provenance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/release_manifest.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/release_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/deployment_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/distribution/runtime/distribution_session.c"
)

if(BUILD_TESTING)
    function(umicom_add_distribution_runtime_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_CROSS_PLATFORM_DISTRIBUTION_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::distribution)
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;distribution-runtime")
    endfunction()

    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-types-test
        framework.distribution_runtime.types
        tests/distribution_runtime/test_types.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-platform-descriptor-test
        framework.distribution_runtime.platform.descriptor
        tests/distribution_runtime/test_platform_descriptor.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-platform-catalogue-test
        framework.distribution_runtime.platform.catalogue
        tests/distribution_runtime/test_platform_catalogue.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-architecture-descriptor-test
        framework.distribution_runtime.architecture.descriptor
        tests/distribution_runtime/test_architecture_descriptor.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-architecture-catalogue-test
        framework.distribution_runtime.architecture.catalogue
        tests/distribution_runtime/test_architecture_catalogue.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-runtime-capability-test
        framework.distribution_runtime.runtime.capability
        tests/distribution_runtime/test_runtime_capability.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-runtime-probe-test
        framework.distribution_runtime.runtime.probe
        tests/distribution_runtime/test_runtime_probe.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-runtime-profile-test
        framework.distribution_runtime.runtime.profile
        tests/distribution_runtime/test_runtime_profile.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-runtime-selector-test
        framework.distribution_runtime.runtime.selector
        tests/distribution_runtime/test_runtime_selector.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-runtime-compatibility-test
        framework.distribution_runtime.runtime.compatibility
        tests/distribution_runtime/test_runtime_compatibility.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-application-manifest-test
        framework.distribution_runtime.application.manifest
        tests/distribution_runtime/test_application_manifest.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-application-identity-test
        framework.distribution_runtime.application.identity
        tests/distribution_runtime/test_application_identity.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-application-variant-test
        framework.distribution_runtime.application.variant
        tests/distribution_runtime/test_application_variant.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-application-bundle-test
        framework.distribution_runtime.application.bundle
        tests/distribution_runtime/test_application_bundle.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-bundle-file-test
        framework.distribution_runtime.bundle.file
        tests/distribution_runtime/test_bundle_file.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-bundle-catalogue-test
        framework.distribution_runtime.bundle.catalogue
        tests/distribution_runtime/test_bundle_catalogue.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-bundle-manifest-test
        framework.distribution_runtime.bundle.manifest
        tests/distribution_runtime/test_bundle_manifest.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-bundle-layout-test
        framework.distribution_runtime.bundle.layout
        tests/distribution_runtime/test_bundle_layout.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-resource-manifest-test
        framework.distribution_runtime.resource.manifest
        tests/distribution_runtime/test_resource_manifest.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-resource-pack-test
        framework.distribution_runtime.resource.pack
        tests/distribution_runtime/test_resource_pack.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-resource-policy-test
        framework.distribution_runtime.resource.policy
        tests/distribution_runtime/test_resource_policy.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-dependency-manifest-test
        framework.distribution_runtime.dependency.manifest
        tests/distribution_runtime/test_dependency_manifest.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-dependency-resolution-test
        framework.distribution_runtime.dependency.resolution
        tests/distribution_runtime/test_dependency_resolution.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-dependency-bundle-test
        framework.distribution_runtime.dependency.bundle
        tests/distribution_runtime/test_dependency_bundle.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-runtime-dependency-test
        framework.distribution_runtime.runtime.dependency
        tests/distribution_runtime/test_runtime_dependency.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-launcher-manifest-test
        framework.distribution_runtime.launcher.manifest
        tests/distribution_runtime/test_launcher_manifest.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-launch-profile-test
        framework.distribution_runtime.launch.profile
        tests/distribution_runtime/test_launch_profile.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-environment-profile-test
        framework.distribution_runtime.environment.profile
        tests/distribution_runtime/test_environment_profile.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-filesystem-layout-test
        framework.distribution_runtime.filesystem.layout
        tests/distribution_runtime/test_filesystem_layout.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-path-policy-test
        framework.distribution_runtime.path.policy
        tests/distribution_runtime/test_path_policy.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-executable-layout-test
        framework.distribution_runtime.executable.layout
        tests/distribution_runtime/test_executable_layout.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-library-layout-test
        framework.distribution_runtime.library.layout
        tests/distribution_runtime/test_library_layout.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-data-layout-test
        framework.distribution_runtime.data.layout
        tests/distribution_runtime/test_data_layout.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-cache-layout-test
        framework.distribution_runtime.cache.layout
        tests/distribution_runtime/test_cache_layout.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-configuration-layout-test
        framework.distribution_runtime.configuration.layout
        tests/distribution_runtime/test_configuration_layout.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-package-format-test
        framework.distribution_runtime.package.format
        tests/distribution_runtime/test_package_format.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-package-profile-test
        framework.distribution_runtime.package.profile
        tests/distribution_runtime/test_package_profile.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-package-plan-test
        framework.distribution_runtime.package.plan
        tests/distribution_runtime/test_package_plan.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-installer-plan-test
        framework.distribution_runtime.installer.plan
        tests/distribution_runtime/test_installer_plan.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-portable-plan-test
        framework.distribution_runtime.portable.plan
        tests/distribution_runtime/test_portable_plan.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-archive-plan-test
        framework.distribution_runtime.archive.plan
        tests/distribution_runtime/test_archive_plan.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-symbol-package-test
        framework.distribution_runtime.symbol.package
        tests/distribution_runtime/test_symbol_package.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-debug-package-test
        framework.distribution_runtime.debug.package
        tests/distribution_runtime/test_debug_package.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-source-package-test
        framework.distribution_runtime.source.package
        tests/distribution_runtime/test_source_package.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-sdk-package-test
        framework.distribution_runtime.sdk.package
        tests/distribution_runtime/test_sdk_package.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-component-package-test
        framework.distribution_runtime.component.package
        tests/distribution_runtime/test_component_package.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-package-catalogue-test
        framework.distribution_runtime.package.catalogue
        tests/distribution_runtime/test_package_catalogue.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-channel-test
        framework.distribution_runtime.channel
        tests/distribution_runtime/test_channel.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-channel-policy-test
        framework.distribution_runtime.channel.policy
        tests/distribution_runtime/test_channel_policy.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-update-manifest-test
        framework.distribution_runtime.update.manifest
        tests/distribution_runtime/test_update_manifest.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-update-candidate-test
        framework.distribution_runtime.update.candidate
        tests/distribution_runtime/test_update_candidate.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-update-policy-test
        framework.distribution_runtime.update.policy
        tests/distribution_runtime/test_update_policy.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-update-rollout-test
        framework.distribution_runtime.update.rollout
        tests/distribution_runtime/test_update_rollout.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-update-transaction-test
        framework.distribution_runtime.update.transaction
        tests/distribution_runtime/test_update_transaction.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-delta-package-test
        framework.distribution_runtime.delta.package
        tests/distribution_runtime/test_delta_package.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-rollback-plan-test
        framework.distribution_runtime.rollback.plan
        tests/distribution_runtime/test_rollback_plan.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-install-state-test
        framework.distribution_runtime.install.state
        tests/distribution_runtime/test_install_state.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-install-receipt-test
        framework.distribution_runtime.install.receipt
        tests/distribution_runtime/test_install_receipt.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-install-registry-test
        framework.distribution_runtime.install.registry
        tests/distribution_runtime/test_install_registry.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-signature-policy-test
        framework.distribution_runtime.signature.policy
        tests/distribution_runtime/test_signature_policy.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-checksum-policy-test
        framework.distribution_runtime.checksum.policy
        tests/distribution_runtime/test_checksum_policy.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-provenance-test
        framework.distribution_runtime.provenance
        tests/distribution_runtime/test_provenance.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-release-manifest-test
        framework.distribution_runtime.release.manifest
        tests/distribution_runtime/test_release_manifest.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-release-gate-test
        framework.distribution_runtime.release.gate
        tests/distribution_runtime/test_release_gate.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-deployment-profile-test
        framework.distribution_runtime.deployment.profile
        tests/distribution_runtime/test_deployment_profile.c
    )
    umicom_add_distribution_runtime_test(
        umicom-distribution-runtime-distribution-session-test
        framework.distribution_runtime.distribution.session
        tests/distribution_runtime/test_distribution_session.c
    )
endif()

message(STATUS "Umicom cross-platform runtime, packaging, update and deployment control plane enabled")
