# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(NOT TARGET Umicom::desktop_system)
    include("${CMAKE_CURRENT_LIST_DIR}/UmicomDesktopSystem.cmake")
endif()
if(NOT TARGET Umicom::ui_gtk4)
    message(FATAL_ERROR "Desktop System GTK requires the canonical GTK4 adapter")
endif()
add_library(umicom_desktop_system_gtk4 STATIC "${CMAKE_CURRENT_LIST_DIR}/../adapters/gtk4/desktop_system_gtk4.c")
add_library(Umicom::desktop_system_gtk4 ALIAS umicom_desktop_system_gtk4)
set_target_properties(umicom_desktop_system_gtk4 PROPERTIES EXPORT_NAME desktop_system_gtk4
    C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
target_link_libraries(umicom_desktop_system_gtk4 PUBLIC Umicom::desktop_system Umicom::ui_gtk4)
if(COMMAND umicom_apply_warnings)
    umicom_apply_warnings(umicom_desktop_system_gtk4)
endif()
if(COMMAND umicom_apply_sanitizers)
    umicom_apply_sanitizers(umicom_desktop_system_gtk4)
endif()
install(TARGETS umicom_desktop_system_gtk4 EXPORT UmicomFrameworkTargets
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT Framework)
if(BUILD_TESTING)
    add_executable(umicom-desktop-system-gtk4-test "${CMAKE_CURRENT_LIST_DIR}/../tests/desktop_system/test_gtk4.c")
    target_link_libraries(umicom-desktop-system-gtk4-test PRIVATE Umicom::desktop_system_gtk4)
    foreach(_case IN ITEMS construct refresh close-during-refresh)
        add_test(NAME framework.desktop_system.gtk4.${_case} COMMAND umicom-desktop-system-gtk4-test ${_case})
        set_tests_properties(framework.desktop_system.gtk4.${_case} PROPERTIES
            TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;desktop-system;gtk4;lifetime")
    endforeach()
    if(COMMAND umicom_apply_warnings)
        umicom_apply_warnings(umicom-desktop-system-gtk4-test)
    endif()
    if(COMMAND umicom_apply_sanitizers)
        umicom_apply_sanitizers(umicom-desktop-system-gtk4-test)
    endif()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-desktop-system-gtk4-test)
    endif()
endif()
