# Visibility lives on the existing chart owner and uses its batch publication.
target_sources(umicom_chart PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/chart/drawing_visibility.c")
if(BUILD_TESTING)
    function(umicom_chart_visibility_cases group file)
        set(target "umicom-chart-visibility-${group}-test")
        add_executable(${target} "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/chart_visibility/${file}")
        target_link_libraries(${target} PRIVATE Umicom::trading_ui Umicom::trading_chart_persistence)
        umicom_apply_warnings(${target})
        umicom_apply_sanitizers(${target})
        foreach(case IN LISTS ARGN)
            add_test(NAME "framework.chart_visibility.${group}.${case}" COMMAND ${target} "${case}")
            set_tests_properties("framework.chart_visibility.${group}.${case}" PROPERTIES
                TIMEOUT 30 LABELS "framework;chart;visibility;regression")
        endforeach()
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(${target})
        endif()
    endfunction()
    umicom_chart_visibility_cases(registry test_registry.c
        single duplicate stale wrong-pane invalid batch-stale empty batch-invalid batch future-tool)
    umicom_chart_visibility_cases(codec test_codec.c
        legacy visible hidden partial missing-schema version flags duplicate)
    umicom_chart_visibility_cases(geometry test_geometry.c
        trend support resistance range liquidity-zone ray invalid)
    umicom_chart_visibility_cases(storage test_storage.c roundtrip recovery stale immutable)
    umicom_chart_visibility_cases(workspace test_workspace.c guards persistence stale-preview scene noop pane)
endif()
if(BUILD_TESTING AND TARGET Umicom::ui_gtk4)
    add_executable(umicom-chart-visibility-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/chart_visibility/test_native.c")
    target_link_libraries(umicom-chart-visibility-native-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-chart-visibility-native-test)
    umicom_apply_sanitizers(umicom-chart-visibility-native-test)
    foreach(case single hidden-move locked pane stale-row stale-pane instrument-change retained)
        add_test(NAME "framework.chart_visibility.native.${case}" COMMAND umicom-chart-visibility-native-test "${case}")
        set_tests_properties("framework.chart_visibility.native.${case}" PROPERTIES
            TIMEOUT 60 SKIP_RETURN_CODE 77 LABELS "framework;chart;visibility;gtk4;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-chart-visibility-native-test)
    endif()
endif()
if(UMICOM_BUILD_LEARNING_EXAMPLES)
    add_executable(umicom-chart-visibility-example "${CMAKE_CURRENT_LIST_DIR}/../examples/chart/drawing_visibility.c")
    target_link_libraries(umicom-chart-visibility-example PRIVATE Umicom::chart)
    umicom_apply_warnings(umicom-chart-visibility-example)
    umicom_apply_sanitizers(umicom-chart-visibility-example)
    if(BUILD_TESTING)
        add_test(NAME framework.chart_visibility.lesson COMMAND umicom-chart-visibility-example)
        set_tests_properties(framework.chart_visibility.lesson PROPERTIES TIMEOUT 30 LABELS "chart;visibility;example")
    endif()
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/CHART_DRAWING_VISIBILITY.md"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom-framework/docs)
