#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomRuntimeBootstrapPlatform.cmake
#
# PURPOSE:
#   Extend the canonical runtime target with Framework-owned dependency
#   injection, scoped service graphs, conditional auto-configuration and
#   reusable application starters.
#
# ARCHITECTURE:
#   Existing UmiServiceRegistry, application feature packs, launcher and runtime
#   services remain authoritative. This platform adds orchestration metadata and
#   planning without creating an application-owned container or service locator.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_RUNTIME_BOOTSTRAP_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
if(NOT TARGET umicom_runtime)
    message(FATAL_ERROR "UmicomRuntimeBootstrapPlatform.cmake requires canonical umicom_runtime")
endif()

target_sources(umicom_runtime PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/service_key.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/service_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/dependency_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/binding_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/binding_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/service_graph.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/graph_node.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/graph_edge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/graph_validator.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/graph_ordering.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/scope_kind.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/scope_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/scope_context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/lifetime_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/factory_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/factory_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/provider_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/provider_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/constructor_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/instance_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/alias_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/optional_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/collection_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/resolution_request.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/resolution_trace.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/resolution_cache.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/resolution_context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/resolution_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/resolver.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/cycle_report.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/missing_dependency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/ambiguity_report.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/dependency_diagnostics.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/lifecycle_phase.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/lifecycle_hook.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/lifecycle_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/startup_order.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/shutdown_order.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/configuration_property.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/configuration_source.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/configuration_overlay.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/configuration_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/configuration_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/condition.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/condition_set.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/condition_evaluator.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/auto_configuration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/auto_configuration_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/auto_configuration_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/auto_configuration_report.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/feature_condition.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/capability_condition.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/platform_condition.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/environment_condition.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/property_condition.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/starter_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/starter_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/starter_dependency.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/starter_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/starter_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/bootstrap_context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/bootstrap_stage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/bootstrap_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/bootstrap_report.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/runtime/bootstrap/bootstrap_service.c"
)

if(BUILD_TESTING)
    function(umicom_add_runtime_bootstrap_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_RUNTIME_BOOTSTRAP_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::runtime)
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;runtime-bootstrap")
    endfunction()

    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-types-test
        framework.runtime_bootstrap.types
        tests/runtime_bootstrap/test_types.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-service-key-test
        framework.runtime_bootstrap.service.key
        tests/runtime_bootstrap/test_service_key.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-service-descriptor-test
        framework.runtime_bootstrap.service.descriptor
        tests/runtime_bootstrap/test_service_descriptor.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-dependency-descriptor-test
        framework.runtime_bootstrap.dependency.descriptor
        tests/runtime_bootstrap/test_dependency_descriptor.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-binding-descriptor-test
        framework.runtime_bootstrap.binding.descriptor
        tests/runtime_bootstrap/test_binding_descriptor.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-binding-registry-test
        framework.runtime_bootstrap.binding.registry
        tests/runtime_bootstrap/test_binding_registry.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-service-graph-test
        framework.runtime_bootstrap.service.graph
        tests/runtime_bootstrap/test_service_graph.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-graph-node-test
        framework.runtime_bootstrap.graph.node
        tests/runtime_bootstrap/test_graph_node.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-graph-edge-test
        framework.runtime_bootstrap.graph.edge
        tests/runtime_bootstrap/test_graph_edge.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-graph-validator-test
        framework.runtime_bootstrap.graph.validator
        tests/runtime_bootstrap/test_graph_validator.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-graph-ordering-test
        framework.runtime_bootstrap.graph.ordering
        tests/runtime_bootstrap/test_graph_ordering.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-scope-kind-test
        framework.runtime_bootstrap.scope.kind
        tests/runtime_bootstrap/test_scope_kind.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-scope-policy-test
        framework.runtime_bootstrap.scope.policy
        tests/runtime_bootstrap/test_scope_policy.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-scope-context-test
        framework.runtime_bootstrap.scope.context
        tests/runtime_bootstrap/test_scope_context.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-lifetime-policy-test
        framework.runtime_bootstrap.lifetime.policy
        tests/runtime_bootstrap/test_lifetime_policy.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-factory-descriptor-test
        framework.runtime_bootstrap.factory.descriptor
        tests/runtime_bootstrap/test_factory_descriptor.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-factory-registry-test
        framework.runtime_bootstrap.factory.registry
        tests/runtime_bootstrap/test_factory_registry.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-provider-descriptor-test
        framework.runtime_bootstrap.provider.descriptor
        tests/runtime_bootstrap/test_provider_descriptor.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-provider-registry-test
        framework.runtime_bootstrap.provider.registry
        tests/runtime_bootstrap/test_provider_registry.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-constructor-binding-test
        framework.runtime_bootstrap.constructor.binding
        tests/runtime_bootstrap/test_constructor_binding.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-instance-binding-test
        framework.runtime_bootstrap.instance.binding
        tests/runtime_bootstrap/test_instance_binding.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-alias-binding-test
        framework.runtime_bootstrap.alias.binding
        tests/runtime_bootstrap/test_alias_binding.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-optional-binding-test
        framework.runtime_bootstrap.optional.binding
        tests/runtime_bootstrap/test_optional_binding.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-collection-binding-test
        framework.runtime_bootstrap.collection.binding
        tests/runtime_bootstrap/test_collection_binding.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-resolution-request-test
        framework.runtime_bootstrap.resolution.request
        tests/runtime_bootstrap/test_resolution_request.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-resolution-trace-test
        framework.runtime_bootstrap.resolution.trace
        tests/runtime_bootstrap/test_resolution_trace.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-resolution-cache-test
        framework.runtime_bootstrap.resolution.cache
        tests/runtime_bootstrap/test_resolution_cache.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-resolution-context-test
        framework.runtime_bootstrap.resolution.context
        tests/runtime_bootstrap/test_resolution_context.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-resolution-plan-test
        framework.runtime_bootstrap.resolution.plan
        tests/runtime_bootstrap/test_resolution_plan.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-resolver-test
        framework.runtime_bootstrap.resolver
        tests/runtime_bootstrap/test_resolver.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-cycle-report-test
        framework.runtime_bootstrap.cycle.report
        tests/runtime_bootstrap/test_cycle_report.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-missing-dependency-test
        framework.runtime_bootstrap.missing.dependency
        tests/runtime_bootstrap/test_missing_dependency.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-ambiguity-report-test
        framework.runtime_bootstrap.ambiguity.report
        tests/runtime_bootstrap/test_ambiguity_report.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-dependency-diagnostics-test
        framework.runtime_bootstrap.dependency.diagnostics
        tests/runtime_bootstrap/test_dependency_diagnostics.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-lifecycle-phase-test
        framework.runtime_bootstrap.lifecycle.phase
        tests/runtime_bootstrap/test_lifecycle_phase.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-lifecycle-hook-test
        framework.runtime_bootstrap.lifecycle.hook
        tests/runtime_bootstrap/test_lifecycle_hook.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-lifecycle-plan-test
        framework.runtime_bootstrap.lifecycle.plan
        tests/runtime_bootstrap/test_lifecycle_plan.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-startup-order-test
        framework.runtime_bootstrap.startup.order
        tests/runtime_bootstrap/test_startup_order.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-shutdown-order-test
        framework.runtime_bootstrap.shutdown.order
        tests/runtime_bootstrap/test_shutdown_order.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-configuration-property-test
        framework.runtime_bootstrap.configuration.property
        tests/runtime_bootstrap/test_configuration_property.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-configuration-source-test
        framework.runtime_bootstrap.configuration.source
        tests/runtime_bootstrap/test_configuration_source.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-configuration-overlay-test
        framework.runtime_bootstrap.configuration.overlay
        tests/runtime_bootstrap/test_configuration_overlay.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-configuration-profile-test
        framework.runtime_bootstrap.configuration.profile
        tests/runtime_bootstrap/test_configuration_profile.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-configuration-binding-test
        framework.runtime_bootstrap.configuration.binding
        tests/runtime_bootstrap/test_configuration_binding.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-condition-test
        framework.runtime_bootstrap.condition
        tests/runtime_bootstrap/test_condition.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-condition-set-test
        framework.runtime_bootstrap.condition.set
        tests/runtime_bootstrap/test_condition_set.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-condition-evaluator-test
        framework.runtime_bootstrap.condition.evaluator
        tests/runtime_bootstrap/test_condition_evaluator.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-auto-configuration-test
        framework.runtime_bootstrap.auto.configuration
        tests/runtime_bootstrap/test_auto_configuration.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-auto-configuration-catalogue-test
        framework.runtime_bootstrap.auto.configuration.catalogue
        tests/runtime_bootstrap/test_auto_configuration_catalogue.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-auto-configuration-plan-test
        framework.runtime_bootstrap.auto.configuration.plan
        tests/runtime_bootstrap/test_auto_configuration_plan.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-auto-configuration-report-test
        framework.runtime_bootstrap.auto.configuration.report
        tests/runtime_bootstrap/test_auto_configuration_report.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-feature-condition-test
        framework.runtime_bootstrap.feature.condition
        tests/runtime_bootstrap/test_feature_condition.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-capability-condition-test
        framework.runtime_bootstrap.capability.condition
        tests/runtime_bootstrap/test_capability_condition.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-platform-condition-test
        framework.runtime_bootstrap.platform.condition
        tests/runtime_bootstrap/test_platform_condition.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-environment-condition-test
        framework.runtime_bootstrap.environment.condition
        tests/runtime_bootstrap/test_environment_condition.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-property-condition-test
        framework.runtime_bootstrap.property.condition
        tests/runtime_bootstrap/test_property_condition.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-starter-descriptor-test
        framework.runtime_bootstrap.starter.descriptor
        tests/runtime_bootstrap/test_starter_descriptor.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-starter-catalogue-test
        framework.runtime_bootstrap.starter.catalogue
        tests/runtime_bootstrap/test_starter_catalogue.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-starter-dependency-test
        framework.runtime_bootstrap.starter.dependency
        tests/runtime_bootstrap/test_starter_dependency.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-starter-plan-test
        framework.runtime_bootstrap.starter.plan
        tests/runtime_bootstrap/test_starter_plan.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-starter-profile-test
        framework.runtime_bootstrap.starter.profile
        tests/runtime_bootstrap/test_starter_profile.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-bootstrap-context-test
        framework.runtime_bootstrap.bootstrap.context
        tests/runtime_bootstrap/test_bootstrap_context.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-bootstrap-stage-test
        framework.runtime_bootstrap.bootstrap.stage
        tests/runtime_bootstrap/test_bootstrap_stage.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-bootstrap-plan-test
        framework.runtime_bootstrap.bootstrap.plan
        tests/runtime_bootstrap/test_bootstrap_plan.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-bootstrap-report-test
        framework.runtime_bootstrap.bootstrap.report
        tests/runtime_bootstrap/test_bootstrap_report.c
    )
    umicom_add_runtime_bootstrap_test(
        umicom-runtime-bootstrap-bootstrap-service-test
        framework.runtime_bootstrap.bootstrap.service
        tests/runtime_bootstrap/test_bootstrap_service.c
    )
endif()

message(STATUS
    "Umicom runtime dependency injection, auto-configuration and starters enabled")
