# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-delimiter-navigation-test "${CMAKE_CURRENT_LIST_DIR}/../tests/editor/test_delimiter_navigation.c")
    target_link_libraries(umicom-delimiter-navigation-test PRIVATE Umicom::editor)
    umicom_apply_warnings(umicom-delimiter-navigation-test)
    umicom_apply_sanitizers(umicom-delimiter-navigation-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-delimiter-navigation-test)
    endif()
    foreach(case c-spliced-cr c-adjacent-character c-prefixed-string round-open round-close after-close after-open square brace adjacent adjacent-unfinished nested-match inner-enclosing outer-enclosing empty-enclosing no-enclosing end-after-enclosing crossed stray-close recover-crossed unfinished-parent unfinished-open stray-only no-bracket empty literal-quote c-string c-character c-escaped-quote c-string-hidden c-line-comment c-block-comment c-comment-hidden c-unclosed-string c-unclosed-comment c-number-separator c-hex-separator json-string json-hidden json-no-comments unicode unicode-enclosing crlf crlf-interior utf8-interior c-spliced-comment c-spliced-comment-end c-spliced-line c-spliced-crlf null-view null-output metadata api capacity null-bytes caret-over syntax-low syntax-high embedded-nul invalid-utf8 depth-limit depth-over source-limit source-over)
        add_test(NAME framework.editor.delimiter.${case} COMMAND umicom-delimiter-navigation-test ${case})
        set_tests_properties(framework.editor.delimiter.${case} PROPERTIES TIMEOUT 30 LABELS "framework;editor;delimiter;navigation;regression")
    endforeach()
endif()
