# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
find_package(PkgConfig QUIET)
if(PkgConfig_FOUND)
    pkg_check_modules(IBKR_GTK4 QUIET IMPORTED_TARGET GLOBAL gtk4>=4.10)
endif()
if(NOT TARGET PkgConfig::IBKR_GTK4)
    message(STATUS "IBKR connection workbench unavailable: GTK4 >= 4.10 not found")
    return()
endif()
set(_ibkr_gtk_root "${CMAKE_CURRENT_LIST_DIR}/..")
add_library(umicom_ibkr_connection_gtk4 STATIC "${_ibkr_gtk_root}/adapters/gtk4/ibkr_connection.c")
add_library(Umicom::ibkr_connection_gtk4 ALIAS umicom_ibkr_connection_gtk4)
set_target_properties(umicom_ibkr_connection_gtk4 PROPERTIES EXPORT_NAME ibkr_connection_gtk4)
target_link_libraries(umicom_ibkr_connection_gtk4 PUBLIC Umicom::ibkr_connection PkgConfig::IBKR_GTK4)
# Position review reuses the canonical native UI when that optional frontend is
# enabled. The standalone connection inspector remains available without it.
if(TARGET Umicom::ui_gtk4)
    target_link_libraries(umicom_ibkr_connection_gtk4 PRIVATE Umicom::ui_gtk4)
    target_compile_definitions(umicom_ibkr_connection_gtk4 PRIVATE UMI_IBKR_HAS_FILTERED_CHOICES=1)
else()
    # Standalone broker inspectors still need logical control lookup in their
    # native fixtures. Compile only the small GTK lookup module when the complete
    # frontend is disabled; otherwise its existing UI library owns these symbols.
    target_sources(umicom_ibkr_connection_gtk4 PRIVATE
        "${_ibkr_gtk_root}/adapters/gtk4/widget_lookup_gtk4.c")
endif()
umicom_ibkr_target(umicom_ibkr_connection_gtk4)
install(TARGETS umicom_ibkr_connection_gtk4 EXPORT UmicomFrameworkTargets
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT Framework)
install(FILES "${_ibkr_gtk_root}/include/umicom/broker_connectivity/connection_gtk4.h"
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/umicom/broker_connectivity COMPONENT Framework)
install(FILES "${CMAKE_CURRENT_LIST_DIR}/UmicomIbkrGtkDependencies.cmake"
    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/UmicomFramework COMPONENT Framework)
add_executable(umicom-broker-workbench "${_ibkr_gtk_root}/examples/ibkr_connection/gtk_main.c")
target_link_libraries(umicom-broker-workbench PRIVATE Umicom::ibkr_connection_gtk4)
umicom_ibkr_target(umicom-broker-workbench)
if(COMMAND umicom_apply_application_branding)
    umicom_apply_application_branding(TARGET umicom-broker-workbench
        PRODUCT_NAME "Umicom Broker Connections" INTERNAL_NAME "umicom-broker-workbench"
        APPLICATION_ID "org.umicom.broker-connections" VERSION_MAJOR 1 VERSION_MINOR 0 VERSION_PATCH 0
        RESOURCE_ROOT "${_ibkr_gtk_root}/resources" DESKTOP_ENTRY WINDOWS_GUI)
endif()
install(TARGETS umicom-broker-workbench RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT Framework)
if(BUILD_TESTING)
    # Logical closure is separate from finalisation when clients retain objects.
    add_executable(umicom-gtk-window-removal-test "${_ibkr_gtk_root}/tests/ibkr_connection/test_window_removal.c")
    target_link_libraries(umicom-gtk-window-removal-test PRIVATE PkgConfig::IBKR_GTK4)
    umicom_ibkr_target(umicom-gtk-window-removal-test)
    foreach(_case IN ITEMS retained unrelated receiver-first reentrant release-receiver)
        add_test(NAME framework.gtk_window_removal.${_case} COMMAND umicom-gtk-window-removal-test ${_case})
        set_tests_properties(framework.gtk_window_removal.${_case} PROPERTIES SKIP_RETURN_CODE 77 TIMEOUT 20)
    endforeach()
    add_executable(umicom-ibkr-gtk-test "${_ibkr_gtk_root}/tests/ibkr_connection/test_gtk.c")
    target_link_libraries(umicom-ibkr-gtk-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-ibkr-gtk-test)
    foreach(_case IN ITEMS construction default_paper mode_ports live_ack retained_controls independent_windows retained_parent quote_controls)
        add_test(NAME framework.ibkr_connection.gtk_${_case} COMMAND umicom-ibkr-gtk-test ${_case})
        set_tests_properties(framework.ibkr_connection.gtk_${_case} PROPERTIES SKIP_RETURN_CODE 77 TIMEOUT 20)
    endforeach()
endif()
# Report lifecycle checks never connect to a broker or create a file.
if(BUILD_TESTING)
    foreach(case report-no-request report-reentrant report-retained)
        add_test(NAME framework.ibkr_observations.gtk.${case} COMMAND umicom-ibkr-gtk-test ${case})
        set_tests_properties(framework.ibkr_observations.gtk.${case} PROPERTIES SKIP_RETURN_CODE 77 TIMEOUT 20
            LABELS "framework;broker;csv;gtk4;ownership;regression")
    endforeach()
endif()
unset(_ibkr_gtk_root)

if(BUILD_TESTING AND TARGET Umicom::ui_gtk4)
    foreach(case position-no-capture position-retained)
        add_test(NAME framework.ibkr_positions.gtk4.${case} COMMAND umicom-ibkr-gtk-test ${case})
        set_tests_properties(framework.ibkr_positions.gtk4.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77
            LABELS "framework;broker;positions;gtk4;ownership;regression")
    endforeach()
endif()

# Native policy tests never connect; lifecycle assertions use the real controls.
if(BUILD_TESTING)
    add_executable(umicom-full-quantity-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/full_quantity/test_native.c")
    target_link_libraries(umicom-full-quantity-native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-full-quantity-native-test)
    foreach(case fields no-quote invalid retained reentrant close-notify)
        add_test(NAME framework.full_quantity.gtk4.${case} COMMAND umicom-full-quantity-native-test ${case})
        set_tests_properties(framework.full_quantity.gtk4.${case} PROPERTIES
            TIMEOUT 20 SKIP_RETURN_CODE 77 LABELS "framework;trading;gtk4;full-quantity;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-full-quantity-native-test)
    endif()
endif()

# Contract review has no order side effects; native probes also cover retained controls.
if(BUILD_TESTING)
    add_executable(umicom-contract-details-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_contract_native.c")
    target_link_libraries(umicom-contract-details-native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-contract-details-native-test)
    foreach(case no-quote abandon-empty retained reentrant close-notify)
        add_test(NAME framework.ibkr_contract_details.gtk4.${case} COMMAND umicom-contract-details-native-test ${case})
        set_tests_properties(framework.ibkr_contract_details.gtk4.${case} PROPERTIES
            TIMEOUT 20 SKIP_RETURN_CODE 77 LABELS "framework;broker;contract;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-contract-details-native-test)
    endif()
endif()

# Price-band controls cannot start a query without a captured instrument route.
if(BUILD_TESTING)
    add_executable(umicom-market-rule-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_market_rule_native.c")
    target_link_libraries(umicom-market-rule-native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-market-rule-native-test)
    foreach(case no-contract retained reentrant close-notify)
        add_test(NAME framework.ibkr_market_rule.gtk4.${case} COMMAND umicom-market-rule-native-test ${case})
        set_tests_properties(framework.ibkr_market_rule.gtk4.${case} PROPERTIES
            TIMEOUT 20 SKIP_RETURN_CODE 77 LABELS "framework;broker;price-increment;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-market-rule-native-test)
    endif()
endif()

# These native lifetime probes use unconnected controls.
if(BUILD_TESTING)
    add_executable(umicom-execution-capture-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_execution_native.c")
    target_link_libraries(umicom-execution-capture-native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-execution-capture-native-test)
    foreach(case no-account abandon-empty retained reentrant close-notify)
        add_test(NAME framework.ibkr_execution_capture.gtk4.${case} COMMAND umicom-execution-capture-native-test ${case})
        set_tests_properties(framework.ibkr_execution_capture.gtk4.${case} PROPERTIES
            TIMEOUT 20 SKIP_RETURN_CODE 77 LABELS "framework;broker;executions;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-execution-capture-native-test)
    endif()
endif()

# Native discovery and P&L controls must also remain safe after window removal.
if(BUILD_TESTING)
    add_executable(umicom-observation-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_observation_native.c")
    target_link_libraries(umicom-observation-native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-observation-native-test)
    foreach(group pnl symbol_search depth)
        foreach(case fields unconnected stop-empty retained reentrant close-notify)
            add_test(NAME framework.ibkr_${group}.gtk4.${case} COMMAND umicom-observation-native-test ${group} ${case})
            set_tests_properties(framework.ibkr_${group}.gtk4.${case} PROPERTIES
                TIMEOUT 20 SKIP_RETURN_CODE 77 LABELS "framework;broker;observations;gtk4;ownership;regression")
        endforeach()
    endforeach()
    add_test(NAME framework.ibkr_symbol_search.gtk4.apply-empty COMMAND umicom-observation-native-test symbol_search apply-empty)
    set_tests_properties(framework.ibkr_symbol_search.gtk4.apply-empty PROPERTIES
        TIMEOUT 20 SKIP_RETURN_CODE 77 LABELS "framework;broker;observations;gtk4;ownership;regression")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-observation-native-test)
    endif()
endif()

# Retained controls cannot call back into a closed broker window.
if(BUILD_TESTING)
    add_executable(umicom-order-recovery-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_order_native.c")
    target_link_libraries(umicom-order-recovery-native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-order-recovery-native-test)
    foreach(case fields unconnected retained reentrant close-notify)
        add_test(NAME framework.ibkr_order_recovery.gtk4.${case} COMMAND umicom-order-recovery-native-test ${case})
        set_tests_properties(framework.ibkr_order_recovery.gtk4.${case} PROPERTIES
            TIMEOUT 20 SKIP_RETURN_CODE 77 LABELS "framework;broker;orders;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-order-recovery-native-test)
    endif()
endif()

# Publication can close a window, so completed-history controls use the same owner guard.
if(BUILD_TESTING)
    add_executable(umicom-completed-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_completed_native.c")
    target_link_libraries(umicom-completed-native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-completed-native-test)
    foreach(case fields unconnected retained reentrant close-notify)
        add_test(NAME framework.ibkr_completed.gtk4.${case} COMMAND umicom-completed-native-test ${case})
        set_tests_properties(framework.ibkr_completed.gtk4.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77
            LABELS "framework;broker;completed-orders;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-completed-native-test)
    endif()
endif()

if(BUILD_TESTING)
    add_executable(umicom-completed-export-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_completed_export_native.c")
    target_link_libraries(umicom-completed-export-native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-completed-export-native-test)
    foreach(case fields unconnected relative-path retained reentrant close-notify)
        add_test(NAME framework.ibkr_completed_report.gtk4.${case} COMMAND umicom-completed-export-native-test ${case})
        set_tests_properties(framework.ibkr_completed_report.gtk4.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77
            LABELS "framework;broker;completed-orders;csv;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-completed-export-native-test)
    endif()
endif()

# The native workbench uses the separate historical presentation owner.
if(TARGET Umicom::ibkr_historical_chart)
    target_link_libraries(umicom_ibkr_connection_gtk4 PRIVATE Umicom::ibkr_historical_chart)
    target_compile_definitions(umicom_ibkr_connection_gtk4 PRIVATE UMI_IBKR_HAS_HISTORY_MODEL=1)
endif()
# Use the established Cairo chart adapter when available. Text observations
# remain available in a minimal broker-workbench build without this adapter.
if(TARGET Umicom::chart_cairo AND TARGET Umicom::ibkr_historical_chart)
    target_link_libraries(umicom_ibkr_connection_gtk4 PRIVATE Umicom::chart_cairo)
    target_compile_definitions(umicom_ibkr_connection_gtk4 PRIVATE UMI_IBKR_HAS_HISTORY_CHART=1)
endif()

if(BUILD_TESTING)
    add_executable(umicom-historical-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_historical_native.c")
    target_link_libraries(umicom-historical-native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-historical-native-test)
    foreach(case fields unconnected retained range-empty reentrant close-notify)
        add_test(NAME framework.ibkr_historical.gtk4.${case} COMMAND umicom-historical-native-test ${case})
        set_tests_properties(framework.ibkr_historical.gtk4.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77
            LABELS "framework;broker;historical-data;chart;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-historical-native-test)
    endif()
endif()

if(BUILD_TESTING)
    add_executable(umicom-historical-export-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_historical_export_native.c")
    target_link_libraries(umicom-historical-export-native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-historical-export-native-test)
    foreach(case fields unconnected relative-path retained reentrant close-notify)
        add_test(NAME framework.ibkr_historical_report.gtk4.${case} COMMAND umicom-historical-export-native-test ${case})
        set_tests_properties(framework.ibkr_historical_report.gtk4.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77
            LABELS "framework;broker;historical-data;csv;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-historical-export-native-test)
    endif()
endif()

if(BUILD_TESTING)
    add_executable(umicom-realtime_native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_realtime_native.c")
    target_link_libraries(umicom-realtime_native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-realtime_native-test)
    foreach(case fields unconnected retained range-empty reentrant close-notify)
        add_test(NAME framework.ibkr_realtime_native.gtk4.${case} COMMAND umicom-realtime_native-test ${case})
        set_tests_properties(framework.ibkr_realtime_native.gtk4.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77
            LABELS "framework;broker;streaming-bars;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-realtime_native-test)
    endif()
endif()

if(BUILD_TESTING)
    add_executable(umicom-realtime_export_native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_realtime_export_native.c")
    target_link_libraries(umicom-realtime_export_native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-realtime_export_native-test)
    foreach(case fields unconnected relative-path retained reentrant close-notify)
        add_test(NAME framework.ibkr_realtime_export_native.gtk4.${case} COMMAND umicom-realtime_export_native-test ${case})
        set_tests_properties(framework.ibkr_realtime_export_native.gtk4.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77
            LABELS "framework;broker;streaming-bars;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-realtime_export_native-test)
    endif()
endif()

if(BUILD_TESTING)
    add_executable(umicom-scanner_native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_scanner_native.c")
    target_link_libraries(umicom-scanner_native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-scanner_native-test)
    foreach(case fields unconnected retained reentrant close-notify)
        add_test(NAME framework.ibkr_scanner_native.gtk4.${case} COMMAND umicom-scanner_native-test ${case})
        set_tests_properties(framework.ibkr_scanner_native.gtk4.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77
            LABELS "framework;broker;discovery;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-scanner_native-test)
    endif()
endif()

if(BUILD_TESTING)
    add_executable(umicom-option_chain_native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_option_chain_native.c")
    target_link_libraries(umicom-option_chain_native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-option_chain_native-test)
    foreach(case fields unconnected retained reentrant close-notify)
        add_test(NAME framework.ibkr_option_chain_native.gtk4.${case} COMMAND umicom-option_chain_native-test ${case})
        set_tests_properties(framework.ibkr_option_chain_native.gtk4.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77
            LABELS "framework;broker;discovery;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-option_chain_native-test)
    endif()
endif()

if(BUILD_TESTING)
    add_executable(umicom-scanner_export_native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_scanner_export_native.c")
    target_link_libraries(umicom-scanner_export_native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-scanner_export_native-test)
    foreach(case fields unconnected relative-path retained reentrant close-notify)
        add_test(NAME framework.ibkr_scanner_export_native.gtk4.${case} COMMAND umicom-scanner_export_native-test ${case})
        set_tests_properties(framework.ibkr_scanner_export_native.gtk4.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77 LABELS "framework;broker;csv;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-scanner_export_native-test)
    endif()
endif()

if(BUILD_TESTING)
    add_executable(umicom-option_export_native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_option_export_native.c")
    target_link_libraries(umicom-option_export_native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-option_export_native-test)
    foreach(case fields unconnected relative-path retained reentrant close-notify)
        add_test(NAME framework.ibkr_option_export_native.gtk4.${case} COMMAND umicom-option_export_native-test ${case})
        set_tests_properties(framework.ibkr_option_export_native.gtk4.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77 LABELS "framework;broker;csv;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-option_export_native-test)
    endif()
endif()

if(BUILD_TESTING)
    add_executable(umicom-catalog_native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/ibkr_connection/test_catalog_native.c")
    target_link_libraries(umicom-catalog_native-test PRIVATE Umicom::ibkr_connection_gtk4)
    umicom_ibkr_target(umicom-catalog_native-test)
    foreach(case fields unconnected retained reentrant close-notify search-empty search-missing search-wrap search-unicode)
        add_test(NAME framework.ibkr_catalog_native.gtk4.${case} COMMAND umicom-catalog_native-test ${case})
        set_tests_properties(framework.ibkr_catalog_native.gtk4.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77
            LABELS "framework;broker;catalogue;gtk4;ownership;regression")
    endforeach()
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-catalog_native-test)
    endif()
endif()

# Welcome-screen environment choices do not open sockets or grant Live consent.
if(BUILD_TESTING)
    foreach(case environment-intent compact-tools retained-launcher)
        add_test(NAME framework.ibkr_connection.gtk_${case} COMMAND umicom-ibkr-gtk-test ${case})
        set_tests_properties(framework.ibkr_connection.gtk_${case} PROPERTIES
            SKIP_RETURN_CODE 77 TIMEOUT 20 LABELS "framework;broker;gtk4;ownership;regression")
    endforeach()
endif()
