# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING AND (WIN32 OR UNIX) AND NOT EMSCRIPTEN)
    add_executable(umicom-creative-asset-files-test "${CMAKE_CURRENT_LIST_DIR}/../tests/creative_assets/test_asset_file.c")
    target_link_libraries(umicom-creative-asset-files-test PRIVATE Umicom::creative_workspace)
    umicom_creative_configure_target(umicom-creative-asset-files-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-creative-asset-files-test)
    endif()
    foreach(case load unicode-path empty limit oversized missing directory relative changed-source copy copy-existing cancel-load cancel-copy bad-destination live-output chunked-copy)
        add_test(NAME framework.creative_assets.files.${case} COMMAND umicom-creative-asset-files-test ${case})
        set_tests_properties(framework.creative_assets.files.${case} PROPERTIES TIMEOUT 30 LABELS "framework;creative-assets;regression")
    endforeach()
endif()
