#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomDataServerEnterprisePlatform.cmake
#
# PURPOSE:
#   Extend the canonical Data Server target with portable schema metadata, ORM,
#   query planning, connection pooling, migrations, replication, backup/restore
#   and enterprise operational state without creating a competing data layer.
#
# ARCHITECTURE:
#   Existing umicom_data Data Server, transaction, SQLite, repository, migration,
#   backup and explorer implementations remain authoritative. This platform adds
#   reusable orchestration and policy contracts consumed by thin applications.
#
# Created by: Sammy Hegab
# Organisation: Umicom Foundation
# Licence: MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_DATA_ENTERPRISE_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
if(NOT TARGET umicom_data)
    message(FATAL_ERROR "UmicomDataServerEnterprisePlatform.cmake requires umicom_data")
endif()

# Enterprise data capabilities extend the existing canonical Data Server target.
target_sources(umicom_data PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/schema_identifier.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/schema_column.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/schema_index.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/schema_foreign_key.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/schema_table.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/schema_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/schema_diff.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/schema_compatibility.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/schema_fingerprint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/entity_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/field_mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/relation_mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/entity_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/identity_map.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/change_tracker.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/unit_of_work.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/repository_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/query_expression.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/query_predicate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/query_order.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/query_projection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/query_join.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/query_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/query_cost.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/query_parameter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/query_cache.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/statement_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/result_mapping.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/transaction_scope.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/savepoint_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/isolation_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/retry_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/connection_slot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/connection_pool.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/pool_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/pool_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/migration_step.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/migration_graph.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/migration_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/migration_validator.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/migration_checkpoint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/migration_resume.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/migration_history.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/replica_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/replica_set.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/replication_lag.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/read_routing_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/failover_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/consistency_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/backup_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/backup_manifest.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/restore_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/restore_validator.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/retention_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/integrity_scan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/data_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/data_metrics.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/data_session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/data_server_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/data_server_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/data_operation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/data_operation_queue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/data_audit_event.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/data_platform_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/data/enterprise/data_platform_service.c"
)

if(BUILD_TESTING)
    function(umicom_add_data_enterprise_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_DATA_ENTERPRISE_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::data)
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;data-enterprise")
    endfunction()

    umicom_add_data_enterprise_test(
        umicom-data-enterprise-types-test
        framework.data_enterprise.types
        tests/data_enterprise/test_types.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-schema-identifier-test
        framework.data_enterprise.schema.identifier
        tests/data_enterprise/test_schema_identifier.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-schema-column-test
        framework.data_enterprise.schema.column
        tests/data_enterprise/test_schema_column.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-schema-index-test
        framework.data_enterprise.schema.index
        tests/data_enterprise/test_schema_index.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-schema-foreign-key-test
        framework.data_enterprise.schema.foreign.key
        tests/data_enterprise/test_schema_foreign_key.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-schema-table-test
        framework.data_enterprise.schema.table
        tests/data_enterprise/test_schema_table.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-schema-snapshot-test
        framework.data_enterprise.schema.snapshot
        tests/data_enterprise/test_schema_snapshot.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-schema-diff-test
        framework.data_enterprise.schema.diff
        tests/data_enterprise/test_schema_diff.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-schema-compatibility-test
        framework.data_enterprise.schema.compatibility
        tests/data_enterprise/test_schema_compatibility.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-schema-fingerprint-test
        framework.data_enterprise.schema.fingerprint
        tests/data_enterprise/test_schema_fingerprint.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-entity-descriptor-test
        framework.data_enterprise.entity.descriptor
        tests/data_enterprise/test_entity_descriptor.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-field-mapping-test
        framework.data_enterprise.field.mapping
        tests/data_enterprise/test_field_mapping.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-relation-mapping-test
        framework.data_enterprise.relation.mapping
        tests/data_enterprise/test_relation_mapping.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-entity-registry-test
        framework.data_enterprise.entity.registry
        tests/data_enterprise/test_entity_registry.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-identity-map-test
        framework.data_enterprise.identity.map
        tests/data_enterprise/test_identity_map.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-change-tracker-test
        framework.data_enterprise.change.tracker
        tests/data_enterprise/test_change_tracker.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-unit-of-work-test
        framework.data_enterprise.unit.of.work
        tests/data_enterprise/test_unit_of_work.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-repository-plan-test
        framework.data_enterprise.repository.plan
        tests/data_enterprise/test_repository_plan.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-query-expression-test
        framework.data_enterprise.query.expression
        tests/data_enterprise/test_query_expression.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-query-predicate-test
        framework.data_enterprise.query.predicate
        tests/data_enterprise/test_query_predicate.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-query-order-test
        framework.data_enterprise.query.order
        tests/data_enterprise/test_query_order.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-query-projection-test
        framework.data_enterprise.query.projection
        tests/data_enterprise/test_query_projection.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-query-join-test
        framework.data_enterprise.query.join
        tests/data_enterprise/test_query_join.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-query-plan-test
        framework.data_enterprise.query.plan
        tests/data_enterprise/test_query_plan.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-query-cost-test
        framework.data_enterprise.query.cost
        tests/data_enterprise/test_query_cost.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-query-parameter-test
        framework.data_enterprise.query.parameter
        tests/data_enterprise/test_query_parameter.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-query-cache-test
        framework.data_enterprise.query.cache
        tests/data_enterprise/test_query_cache.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-statement-plan-test
        framework.data_enterprise.statement.plan
        tests/data_enterprise/test_statement_plan.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-result-mapping-test
        framework.data_enterprise.result.mapping
        tests/data_enterprise/test_result_mapping.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-transaction-scope-test
        framework.data_enterprise.transaction.scope
        tests/data_enterprise/test_transaction_scope.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-savepoint-plan-test
        framework.data_enterprise.savepoint.plan
        tests/data_enterprise/test_savepoint_plan.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-isolation-policy-test
        framework.data_enterprise.isolation.policy
        tests/data_enterprise/test_isolation_policy.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-retry-policy-test
        framework.data_enterprise.retry.policy
        tests/data_enterprise/test_retry_policy.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-connection-slot-test
        framework.data_enterprise.connection.slot
        tests/data_enterprise/test_connection_slot.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-connection-pool-test
        framework.data_enterprise.connection.pool
        tests/data_enterprise/test_connection_pool.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-pool-health-test
        framework.data_enterprise.pool.health
        tests/data_enterprise/test_pool_health.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-pool-policy-test
        framework.data_enterprise.pool.policy
        tests/data_enterprise/test_pool_policy.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-migration-step-test
        framework.data_enterprise.migration.step
        tests/data_enterprise/test_migration_step.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-migration-graph-test
        framework.data_enterprise.migration.graph
        tests/data_enterprise/test_migration_graph.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-migration-plan-test
        framework.data_enterprise.migration.plan
        tests/data_enterprise/test_migration_plan.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-migration-validator-test
        framework.data_enterprise.migration.validator
        tests/data_enterprise/test_migration_validator.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-migration-checkpoint-test
        framework.data_enterprise.migration.checkpoint
        tests/data_enterprise/test_migration_checkpoint.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-migration-resume-test
        framework.data_enterprise.migration.resume
        tests/data_enterprise/test_migration_resume.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-migration-history-test
        framework.data_enterprise.migration.history
        tests/data_enterprise/test_migration_history.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-replica-descriptor-test
        framework.data_enterprise.replica.descriptor
        tests/data_enterprise/test_replica_descriptor.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-replica-set-test
        framework.data_enterprise.replica.set
        tests/data_enterprise/test_replica_set.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-replication-lag-test
        framework.data_enterprise.replication.lag
        tests/data_enterprise/test_replication_lag.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-read-routing-policy-test
        framework.data_enterprise.read.routing.policy
        tests/data_enterprise/test_read_routing_policy.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-failover-policy-test
        framework.data_enterprise.failover.policy
        tests/data_enterprise/test_failover_policy.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-consistency-policy-test
        framework.data_enterprise.consistency.policy
        tests/data_enterprise/test_consistency_policy.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-backup-plan-test
        framework.data_enterprise.backup.plan
        tests/data_enterprise/test_backup_plan.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-backup-manifest-test
        framework.data_enterprise.backup.manifest
        tests/data_enterprise/test_backup_manifest.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-restore-plan-test
        framework.data_enterprise.restore.plan
        tests/data_enterprise/test_restore_plan.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-restore-validator-test
        framework.data_enterprise.restore.validator
        tests/data_enterprise/test_restore_validator.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-retention-policy-test
        framework.data_enterprise.retention.policy
        tests/data_enterprise/test_retention_policy.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-integrity-scan-test
        framework.data_enterprise.integrity.scan
        tests/data_enterprise/test_integrity_scan.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-data-health-test
        framework.data_enterprise.data.health
        tests/data_enterprise/test_data_health.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-data-metrics-test
        framework.data_enterprise.data.metrics
        tests/data_enterprise/test_data_metrics.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-data-session-test
        framework.data_enterprise.data.session
        tests/data_enterprise/test_data_session.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-data-server-profile-test
        framework.data_enterprise.data.server.profile
        tests/data_enterprise/test_data_server_profile.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-data-server-catalogue-test
        framework.data_enterprise.data.server.catalogue
        tests/data_enterprise/test_data_server_catalogue.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-data-operation-test
        framework.data_enterprise.data.operation
        tests/data_enterprise/test_data_operation.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-data-operation-queue-test
        framework.data_enterprise.data.operation.queue
        tests/data_enterprise/test_data_operation_queue.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-data-audit-event-test
        framework.data_enterprise.data.audit.event
        tests/data_enterprise/test_data_audit_event.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-data-platform-snapshot-test
        framework.data_enterprise.data.platform.snapshot
        tests/data_enterprise/test_data_platform_snapshot.c
    )
    umicom_add_data_enterprise_test(
        umicom-data-enterprise-data-platform-service-test
        framework.data_enterprise.data.platform.service
        tests/data_enterprise/test_data_platform_service.c
    )
endif()

message(STATUS
    "Umicom Data Server ORM, migration, replication, backup and enterprise operations enabled")
