# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-action-resolution-query-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_action_resolution_query.c")
    target_link_libraries(umicom-action-resolution-query-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-action-resolution-query-test)
    umicom_apply_sanitizers(umicom-action-resolution-query-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-action-resolution-query-test)
    endif()
    foreach(case maximum over-maximum valid no-data metadata reordered filter notification pull sources complete disabled command empty limit exact-limit zero-limit high-limit null-options invalid-filter invalid-mode invalid-source duplicate-source cancel-before cancel-resolve timeout-resolve read-error write-error close-error shutdown-error resolve-error second-error changed-title changed-data missing-edit added-command malformed wrong-id fragmented unsupported false-provider malformed-provider off)
        add_test(NAME framework.language_runtime.action_resolution_query.${case} COMMAND umicom-action-resolution-query-test ${case})
        set_tests_properties(framework.language_runtime.action_resolution_query.${case} PROPERTIES TIMEOUT 30
            LABELS "framework;language;diagnostic;ownership;regression")
    endforeach()
endif()
