# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_calls_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-calls-gtk4-test)
        return()
    endif()
    add_executable(umicom-calls-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_calls_gtk4.c")
    target_link_libraries(umicom-calls-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-calls-gtk4-test)
    umicom_apply_sanitizers(umicom-calls-gtk4-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-calls-gtk4-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-calls-gtk4-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-calls-gtk4-test)
    endif()
    foreach(case open read private empty selection multiline cancel retained unbind parent-close creation-unbind worker-unbind worker-parent-close input-change changed-back busy invalid-path stale invalidate-output apply read-only select-symbol select-site select-second-site invalid-direction selection-stale open-unbind invalid-selection invalid-result choice-only outgoing outgoing-site no-sites no-calls multiple model-retire invalid-destination)
        add_test(NAME framework.document.calls.gtk4.${case}
            COMMAND umicom-calls-gtk4-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.document.calls.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77
            LABELS "framework;document;language;calls;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_calls_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_calls_checks)
endif()
