# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Build-system collection stays here; reusable immutable inspection belongs to
# the existing distribution library. No release decision is made by this file.
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/UmicomReleaseInventoryFormat.cmake")
option(UMICOM_RELEASE_INVENTORY_CAPTURE "Capture configured targets, public headers and exact test names" OFF)
# The existing composition harness disables recursive composition checks.
option(UMICOM_RELEASE_INVENTORY_COMPOSITION_TESTS "Check release inventory collection in nested builds" ${UMICOM_RELEASE_BASELINE_COMPOSITION_TESTS})
set_property(GLOBAL PROPERTY UMICOM_RELEASE_INVENTORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
include("${CMAKE_CURRENT_LIST_DIR}/UmicomReleaseQualification.cmake")

# Header ownership is an explicit declaration, never a directory-name guess.
# Paths are relative to Framework's root (or absolute paths within that root).
function(umicom_release_inventory_own_headers target)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "Release header owner is not a configured target: ${target}")
    endif()
    get_property(_imported TARGET "${target}" PROPERTY IMPORTED)
    get_property(_alias TARGET "${target}" PROPERTY ALIASED_TARGET)
    if(_imported OR _alias)
        message(FATAL_ERROR "Declare release headers on their real, non-imported target")
    endif()
    get_property(_root GLOBAL PROPERTY UMICOM_RELEASE_INVENTORY_ROOT)
    file(REAL_PATH "${_root}/include/umicom" _public)
    foreach(_header IN LISTS ARGN)
        file(REAL_PATH "${_header}" _path BASE_DIRECTORY "${_root}")
        cmake_path(IS_PREFIX _public "${_path}" NORMALIZE _inside)
        if(NOT _inside OR NOT EXISTS "${_path}" OR IS_DIRECTORY "${_path}")
            message(FATAL_ERROR "Declared public header must exist within include/umicom: ${_header}")
        endif()
        string(SHA256 _key "${_path}")
        get_property(_owner GLOBAL PROPERTY "UMICOM_RELEASE_HEADER_${_key}")
        if(_owner AND NOT _owner STREQUAL target)
            message(FATAL_ERROR "Conflicting release owners for ${_header}: ${_owner}, ${target}")
        endif()
        set_property(GLOBAL PROPERTY "UMICOM_RELEASE_HEADER_${_key}" "${target}")
        set_property(TARGET "${target}" APPEND PROPERTY UMICOM_RELEASE_PUBLIC_HEADERS "${_path}")
        set_property(GLOBAL APPEND PROPERTY UMICOM_RELEASE_HEADER_OWNERS "${target}")
    endforeach()
endfunction()

function(_umicom_inventory_directory directory output)
    string(SHA256 _directory_key "${directory}")
    get_property(_visited GLOBAL PROPERTY "UMICOM_INVENTORY_DIRECTORY_${_directory_key}")
    if(_visited)
        message(FATAL_ERROR "Ambiguous repeated source-directory instance in release inventory: ${directory}")
    endif()
    set_property(GLOBAL PROPERTY "UMICOM_INVENTORY_DIRECTORY_${_directory_key}" TRUE)
    get_property(_targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(_target IN LISTS _targets)
        get_property(_source_dir TARGET "${_target}" PROPERTY SOURCE_DIR)
        set(_detail "")
        foreach(_property IN ITEMS TYPE SOURCES INTERFACE_SOURCES LINK_LIBRARIES
                INTERFACE_LINK_LIBRARIES INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES
                COMPILE_DEFINITIONS INTERFACE_COMPILE_DEFINITIONS COMPILE_OPTIONS
                INTERFACE_COMPILE_OPTIONS LINK_OPTIONS C_STANDARD)
            get_property(_value TARGET "${_target}" PROPERTY "${_property}")
            string(APPEND _detail "${_property}=${_value}\n")
        endforeach()
        _umicom_inventory_row("${output}" target "${_target}" "${_source_dir}" configured "${_detail}")
        get_property(_sources TARGET "${_target}" PROPERTY SOURCES)
        list(REMOVE_DUPLICATES _sources)
        foreach(_source IN LISTS _sources)
            # Expressions and generated inputs are intentionally unresolved.
            # The raw SOURCES property above retains the original list as well.
            set(_state unresolved)
            set(_detail "raw=${_source}\n")
            if(_source MATCHES "\\$<")
                set(_identity "${_source_dir}/${_source}")
            else()
                get_filename_component(_identity "${_source}" ABSOLUTE BASE_DIR "${_source_dir}")
                get_property(_generated SOURCE "${_source}" TARGET_DIRECTORY "${_target}" PROPERTY GENERATED)
                if(EXISTS "${_identity}" AND NOT IS_DIRECTORY "${_identity}" AND NOT _generated)
                    file(SHA256 "${_identity}" _sha)
                    string(APPEND _detail "sha256=${_sha}\n")
                    set(_state present)
                endif()
            endif()
            # CMake permits several spellings of the same source on one target.
            string(SHA256 _key "${_target}\n${_identity}")
            if(NOT DEFINED _seen_${_key})
                set(_seen_${_key} TRUE)
                _umicom_inventory_row("${output}" source "${_identity}" "${_target}" "${_state}" "${_detail}")
            endif()
        endforeach()
    endforeach()
    get_property(_tests DIRECTORY "${directory}" PROPERTY TESTS)
    foreach(_test IN LISTS _tests)
        _umicom_inventory_row("${output}" test "${_test}" "${directory}" registered "Configured registration; execution and required/optional policy are separate.")
    endforeach()
    get_property(_children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(_child IN LISTS _children)
        # Traverse the configured binary scope; refuse ambiguous repeated
        # instances instead of silently publishing only one of them.
        get_property(_binary DIRECTORY "${_child}" PROPERTY BINARY_DIR)
        _umicom_inventory_directory("${_binary}" "${output}")
    endforeach()
endfunction()

function(_umicom_inventory_capture_last)
    # Existing completion hooks can schedule more deferred hooks themselves.
    # Yield until they finish instead of capturing a plausible but partial list.
    cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" GET_CALL_IDS _pending)
    list(REMOVE_ITEM _pending umicom_inventory_final)
    if(_pending)
        get_property(_retries GLOBAL PROPERTY UMICOM_RELEASE_INVENTORY_RETRIES)
        if(NOT _retries)
            set(_retries 0)
        endif()
        math(EXPR _retries "${_retries} + 1")
        if(_retries GREATER 100)
            message(FATAL_ERROR "Deferred build registrations did not settle; inventory refused")
        endif()
        set_property(GLOBAL PROPERTY UMICOM_RELEASE_INVENTORY_RETRIES "${_retries}")
        cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" ID umicom_inventory_final CALL _umicom_inventory_capture_last)
        return()
    endif()
    # Prepare consumer probes after all owners exist, before inventory capture.
    # One shared completion hook avoids mutually waiting deferred finalisers.
    umicom_release_contracts_prepare()
    if(NOT UMICOM_RELEASE_INVENTORY_CAPTURE)
        return()
    endif()
    get_property(_root GLOBAL PROPERTY UMICOM_RELEASE_INVENTORY_ROOT)
    file(REAL_PATH "${_root}" _root)
    file(REAL_PATH "${CMAKE_SOURCE_DIR}" _source)
    file(REAL_PATH "${CMAKE_BINARY_DIR}" _build)
    if(_source STREQUAL _build)
        message(FATAL_ERROR "Release inventory requires a separate build directory")
    endif()
    if(_root MATCHES ";" OR _source MATCHES ";" OR _build MATCHES ";")
        message(FATAL_ERROR "Release inventory does not support semicolons in root paths")
    endif()
    set(_destination "${_build}/release-inventory")
    file(MAKE_DIRECTORY "${_destination}")
    set(_body "${_destination}/configured-records.tsv")
    file(WRITE "${_body}" "")
    file(GLOB_RECURSE _headers LIST_DIRECTORIES FALSE "${_root}/include/umicom/*.h")
    list(SORT _headers)
    foreach(_header IN LISTS _headers)
        file(REAL_PATH "${_header}" _path)
        string(SHA256 _key "${_path}")
        get_property(_owner GLOBAL PROPERTY "UMICOM_RELEASE_HEADER_${_key}")
        set(_state unassigned)
        if(_owner)
            set(_state declared)
        endif()
        file(RELATIVE_PATH _identity "${_root}" "${_header}")
        file(SHA256 "${_header}" _sha)
        _umicom_inventory_row("${_body}" header "${_identity}" "${_owner}" "${_state}" "sha256=${_sha}")
    endforeach()
    _umicom_inventory_directory("${CMAKE_BINARY_DIR}" "${_body}")
    file(SIZE "${_body}" _size)
    if(_size GREATER 66000000)
        message(FATAL_ERROR "Release inventory exceeds its bounded format; capture refused")
    endif()
    file(READ "${_body}" _records)
    string(RANDOM LENGTH 32 ALPHABET 0123456789abcdef _generation)
    string(HEX "${_source}" _source_hex)
    string(HEX "${_build}" _build_hex)
    if(CMAKE_CONFIGURATION_TYPES)
        set(_configs "${CMAKE_CONFIGURATION_TYPES}")
    elseif(CMAKE_BUILD_TYPE)
        set(_configs "${CMAKE_BUILD_TYPE}")
    else()
        set(_configs NoConfig)
    endif()
    foreach(_config IN LISTS _configs)
        if(NOT _config MATCHES "^[A-Za-z0-9_-]+$")
            message(FATAL_ERROR "Unsupported release inventory configuration name: ${_config}")
        endif()
        string(HEX "${_config}" _config_hex)
        # All captured user strings are hex, so file(GENERATE) cannot evaluate
        # generator expressions that belong to the source metadata.
        file(GENERATE OUTPUT "${_destination}/inventory-${_config}.tsv"
            CONTENT "UMICOM-RELEASE-INVENTORY\t1\ncontext\tcmake\t${_generation}\t${_source_hex}\t${_build_hex}\t${_config_hex}\n${_records}")
    endforeach()
    message(STATUS "Release inventory: ${_destination} (registration metadata only)")
endfunction()

function(umicom_release_inventory_complete)
    if(NOT TARGET umicom_distribution)
        return()
    endif()
    get_property(_imported TARGET umicom_distribution PROPERTY IMPORTED)
    get_property(_done TARGET umicom_distribution PROPERTY UMICOM_RELEASE_INVENTORY_ATTACHED)
    if(_imported OR _done)
        return()
    endif()
    set_property(TARGET umicom_distribution PROPERTY UMICOM_RELEASE_INVENTORY_ATTACHED TRUE)
    get_property(_root GLOBAL PROPERTY UMICOM_RELEASE_INVENTORY_ROOT)
    target_sources(umicom_distribution PRIVATE "${_root}/src/distribution/runtime/inventory.c" "${_root}/src/distribution/runtime/inventory_text.c")
    add_executable(umicom-release-inventory "${_root}/tools/release_inventory/main.c")
    target_link_libraries(umicom-release-inventory PRIVATE Umicom::distribution)
    set_target_properties(umicom-release-inventory PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    if(COMMAND umicom_apply_warnings)
        umicom_apply_warnings(umicom-release-inventory)
    endif()
    if(COMMAND umicom_apply_sanitizers)
        umicom_apply_sanitizers(umicom-release-inventory)
    endif()
    if(WIN32 AND NOT MSVC)
        target_link_options(umicom-release-inventory PRIVATE -municode)
    endif()
    umicom_release_policy_attach()
    if(TARGET umicom_base)
        umicom_release_inventory_own_headers(umicom_base include/umicom/base/status.h)
    endif()
    umicom_release_inventory_own_headers(umicom_distribution
        include/umicom/distribution/runtime/inventory.h
        include/umicom/distribution/runtime/evidence.h
        include/umicom/distribution/runtime/release_gate.h
        include/umicom/distribution/runtime/types.h)
    include(GNUInstallDirs)
    install(TARGETS umicom-release-inventory RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT Framework)
    install(FILES "${_root}/include/umicom/distribution/runtime/inventory.h" DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/umicom/distribution/runtime COMPONENT Framework)
    install(FILES "${_root}/docs/learning/inspect-build-registration.md" DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/learning COMPONENT Learning)
    if(BUILD_TESTING)
        include("${_root}/tests/release_inventory/CMakeLists.txt")
    endif()
    if(UMICOM_RELEASE_INVENTORY_CAPTURE)
        cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" ID umicom_inventory_final CALL _umicom_inventory_capture_last)
    elseif(UMICOM_RELEASE_HEADER_CHECKS)
        cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" ID umicom_inventory_final CALL _umicom_inventory_capture_last)
    endif()
endfunction()
if(TARGET umicom_distribution)
    umicom_release_inventory_complete()
else()
    cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" CALL umicom_release_inventory_complete)
endif()

