# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-source-navigation-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_source_navigation.c")
    target_link_libraries(umicom-document-source-navigation-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-source-navigation-test)
    umicom_apply_sanitizers(umicom-document-source-navigation-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-source-navigation-test)
    endif()
    foreach(case range caret unicode split-start split-end crlf cr read-only reversed line-outside column-outside inactive draft history history-invalid lookup duplicate unknown arguments large)
        add_test(NAME framework.document.source_navigation.${case} COMMAND umicom-document-source-navigation-test ${case})
        set_tests_properties(framework.document.source_navigation.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;source;review;regression")
    endforeach()
endif()
