# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-native-rename-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_native_rename.c")
    target_link_libraries(umicom-native-rename-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-native-rename-test)
    umicom_apply_sanitizers(umicom-native-rename-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-native-rename-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-native-rename-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-native-rename-test)
    endif()
    foreach(case valid unicode empty error invalid timeout encoding shutdown cancel stale null-version annotation outside resource external prepare prepare-placeholder prepare-null prepare-default prepare-invalid prepare-timeout)
        add_test(NAME framework.language_runtime.native_rename.${case} COMMAND umicom-native-rename-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.language_runtime.native_rename.${case} PROPERTIES TIMEOUT 40
            LABELS "framework;language;rename;native;ownership;regression")
    endforeach()
endif()
