# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_recovery_monitor_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-recovery-monitor-gtk4-test)
        return()
    endif()
    add_executable(umicom-recovery-monitor-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_recovery_monitor_gtk4.c")
    target_link_libraries(umicom-recovery-monitor-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-recovery-monitor-gtk4-test)
    umicom_apply_sanitizers(umicom-recovery-monitor-gtk4-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-recovery-monitor-gtk4-test)
    endif()
    foreach(case disabled periodic unchanged newer read-only multiple failure-pause disable parent-close unbind observer-detach form-enable form-pause)
        add_test(NAME framework.document.recovery_monitor.gtk4.${case} COMMAND umicom-recovery-monitor-gtk4-test ${case})
        set_tests_properties(framework.document.recovery_monitor.gtk4.${case} PROPERTIES TIMEOUT 60 SKIP_RETURN_CODE 77 LABELS "framework;document;recovery;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_recovery_monitor_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_recovery_monitor_checks)
endif()
