#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomIntegrationFabricEnterprisePlatform.cmake
#
# PURPOSE:
#   Extend the canonical Integration Fabric with enterprise service discovery,
#   routing, schemas, workflows, connectors, governance and distributed-service
#   operations.
#
# Created by: Sammy Hegab
# Organisation: Umicom Foundation
# Licence: MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_INTEGRATION_FABRIC_ENTERPRISE_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
if(NOT TARGET umicom_integration)
    message(FATAL_ERROR "UmicomIntegrationFabricEnterprisePlatform.cmake requires canonical umicom_integration")
endif()

target_sources(umicom_integration PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/service_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/service_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/service_instance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/service_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/service_lease.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/service_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/service_selection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/endpoint_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/endpoint_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/protocol_contract.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/transport_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/message_contract.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/message_header.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/message_envelope.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/correlation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/request_reply.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/request_deadline.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/request_retry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/idempotency_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/deduplication_window.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/delivery_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/dead_letter_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/route_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/route_table.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/route_matcher.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/routing_decision.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/content_type.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/schema_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/schema_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/schema_compatibility.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/schema_evolution.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/transform_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/transform_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/transform_pipeline.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/filter_expression.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/filter_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/split_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/aggregate_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/resequencing_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/workflow_step.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/workflow_graph.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/workflow_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/workflow_checkpoint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/workflow_execution.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/saga_step.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/saga_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/compensation_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/compensation_record.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/connector_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/connector_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/connector_binding.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/connector_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/api_operation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/api_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/api_gateway_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/rate_limit_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/circuit_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/bulkhead_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/security_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/audit_record.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/metric_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/trace_context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/fabric_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/fabric_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/integration/fabric/integration_fabric_service.c"
)

# Compose existing Framework capabilities rather than recreating transport, resilience, web or observability runtimes.
if(TARGET umicom_resilience)
    target_link_libraries(umicom_integration PUBLIC Umicom::resilience)
endif()
if(TARGET umicom_observability)
    target_link_libraries(umicom_integration PUBLIC Umicom::observability)
endif()
if(TARGET umicom_web)
    target_link_libraries(umicom_integration PUBLIC Umicom::web)
endif()

if(BUILD_TESTING)
    function(umicom_add_integration_fabric_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_INTEGRATION_FABRIC_ENTERPRISE_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::integration)
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;integration-fabric")
    endfunction()

    umicom_add_integration_fabric_test(
        umicom-integration-fabric-types-test
        framework.integration_fabric.types
        tests/integration_fabric/test_types.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-service-descriptor-test
        framework.integration_fabric.service.descriptor
        tests/integration_fabric/test_service_descriptor.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-service-catalogue-test
        framework.integration_fabric.service.catalogue
        tests/integration_fabric/test_service_catalogue.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-service-instance-test
        framework.integration_fabric.service.instance
        tests/integration_fabric/test_service_instance.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-service-registry-test
        framework.integration_fabric.service.registry
        tests/integration_fabric/test_service_registry.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-service-lease-test
        framework.integration_fabric.service.lease
        tests/integration_fabric/test_service_lease.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-service-health-test
        framework.integration_fabric.service.health
        tests/integration_fabric/test_service_health.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-service-selection-test
        framework.integration_fabric.service.selection
        tests/integration_fabric/test_service_selection.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-endpoint-descriptor-test
        framework.integration_fabric.endpoint.descriptor
        tests/integration_fabric/test_endpoint_descriptor.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-endpoint-registry-test
        framework.integration_fabric.endpoint.registry
        tests/integration_fabric/test_endpoint_registry.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-protocol-contract-test
        framework.integration_fabric.protocol.contract
        tests/integration_fabric/test_protocol_contract.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-transport-profile-test
        framework.integration_fabric.transport.profile
        tests/integration_fabric/test_transport_profile.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-message-contract-test
        framework.integration_fabric.message.contract
        tests/integration_fabric/test_message_contract.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-message-header-test
        framework.integration_fabric.message.header
        tests/integration_fabric/test_message_header.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-message-envelope-test
        framework.integration_fabric.message.envelope
        tests/integration_fabric/test_message_envelope.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-correlation-test
        framework.integration_fabric.correlation
        tests/integration_fabric/test_correlation.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-request-reply-test
        framework.integration_fabric.request.reply
        tests/integration_fabric/test_request_reply.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-request-deadline-test
        framework.integration_fabric.request.deadline
        tests/integration_fabric/test_request_deadline.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-request-retry-test
        framework.integration_fabric.request.retry
        tests/integration_fabric/test_request_retry.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-idempotency-policy-test
        framework.integration_fabric.idempotency.policy
        tests/integration_fabric/test_idempotency_policy.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-deduplication-window-test
        framework.integration_fabric.deduplication.window
        tests/integration_fabric/test_deduplication_window.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-delivery-policy-test
        framework.integration_fabric.delivery.policy
        tests/integration_fabric/test_delivery_policy.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-dead-letter-policy-test
        framework.integration_fabric.dead.letter.policy
        tests/integration_fabric/test_dead_letter_policy.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-route-rule-test
        framework.integration_fabric.route.rule
        tests/integration_fabric/test_route_rule.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-route-table-test
        framework.integration_fabric.route.table
        tests/integration_fabric/test_route_table.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-route-matcher-test
        framework.integration_fabric.route.matcher
        tests/integration_fabric/test_route_matcher.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-routing-decision-test
        framework.integration_fabric.routing.decision
        tests/integration_fabric/test_routing_decision.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-content-type-test
        framework.integration_fabric.content.type
        tests/integration_fabric/test_content_type.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-schema-descriptor-test
        framework.integration_fabric.schema.descriptor
        tests/integration_fabric/test_schema_descriptor.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-schema-registry-test
        framework.integration_fabric.schema.registry
        tests/integration_fabric/test_schema_registry.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-schema-compatibility-test
        framework.integration_fabric.schema.compatibility
        tests/integration_fabric/test_schema_compatibility.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-schema-evolution-test
        framework.integration_fabric.schema.evolution
        tests/integration_fabric/test_schema_evolution.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-transform-rule-test
        framework.integration_fabric.transform.rule
        tests/integration_fabric/test_transform_rule.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-transform-plan-test
        framework.integration_fabric.transform.plan
        tests/integration_fabric/test_transform_plan.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-transform-pipeline-test
        framework.integration_fabric.transform.pipeline
        tests/integration_fabric/test_transform_pipeline.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-filter-expression-test
        framework.integration_fabric.filter.expression
        tests/integration_fabric/test_filter_expression.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-filter-rule-test
        framework.integration_fabric.filter.rule
        tests/integration_fabric/test_filter_rule.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-split-rule-test
        framework.integration_fabric.split.rule
        tests/integration_fabric/test_split_rule.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-aggregate-rule-test
        framework.integration_fabric.aggregate.rule
        tests/integration_fabric/test_aggregate_rule.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-resequencing-policy-test
        framework.integration_fabric.resequencing.policy
        tests/integration_fabric/test_resequencing_policy.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-workflow-step-test
        framework.integration_fabric.workflow.step
        tests/integration_fabric/test_workflow_step.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-workflow-graph-test
        framework.integration_fabric.workflow.graph
        tests/integration_fabric/test_workflow_graph.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-workflow-plan-test
        framework.integration_fabric.workflow.plan
        tests/integration_fabric/test_workflow_plan.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-workflow-checkpoint-test
        framework.integration_fabric.workflow.checkpoint
        tests/integration_fabric/test_workflow_checkpoint.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-workflow-execution-test
        framework.integration_fabric.workflow.execution
        tests/integration_fabric/test_workflow_execution.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-saga-step-test
        framework.integration_fabric.saga.step
        tests/integration_fabric/test_saga_step.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-saga-plan-test
        framework.integration_fabric.saga.plan
        tests/integration_fabric/test_saga_plan.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-compensation-policy-test
        framework.integration_fabric.compensation.policy
        tests/integration_fabric/test_compensation_policy.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-compensation-record-test
        framework.integration_fabric.compensation.record
        tests/integration_fabric/test_compensation_record.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-connector-descriptor-test
        framework.integration_fabric.connector.descriptor
        tests/integration_fabric/test_connector_descriptor.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-connector-catalogue-test
        framework.integration_fabric.connector.catalogue
        tests/integration_fabric/test_connector_catalogue.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-connector-binding-test
        framework.integration_fabric.connector.binding
        tests/integration_fabric/test_connector_binding.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-connector-health-test
        framework.integration_fabric.connector.health
        tests/integration_fabric/test_connector_health.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-api-operation-test
        framework.integration_fabric.api.operation
        tests/integration_fabric/test_api_operation.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-api-catalogue-test
        framework.integration_fabric.api.catalogue
        tests/integration_fabric/test_api_catalogue.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-api-gateway-policy-test
        framework.integration_fabric.api.gateway.policy
        tests/integration_fabric/test_api_gateway_policy.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-rate-limit-policy-test
        framework.integration_fabric.rate.limit.policy
        tests/integration_fabric/test_rate_limit_policy.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-circuit-policy-test
        framework.integration_fabric.circuit.policy
        tests/integration_fabric/test_circuit_policy.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-bulkhead-policy-test
        framework.integration_fabric.bulkhead.policy
        tests/integration_fabric/test_bulkhead_policy.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-security-policy-test
        framework.integration_fabric.security.policy
        tests/integration_fabric/test_security_policy.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-audit-record-test
        framework.integration_fabric.audit.record
        tests/integration_fabric/test_audit_record.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-metric-snapshot-test
        framework.integration_fabric.metric.snapshot
        tests/integration_fabric/test_metric_snapshot.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-trace-context-test
        framework.integration_fabric.trace.context
        tests/integration_fabric/test_trace_context.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-fabric-health-test
        framework.integration_fabric.fabric.health
        tests/integration_fabric/test_fabric_health.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-fabric-snapshot-test
        framework.integration_fabric.fabric.snapshot
        tests/integration_fabric/test_fabric_snapshot.c
    )
    umicom_add_integration_fabric_test(
        umicom-integration-fabric-integration-fabric-service-test
        framework.integration_fabric.integration.fabric.service
        tests/integration_fabric/test_integration_fabric_service.c
    )
endif()

message(STATUS "Umicom enterprise Integration Fabric routing, workflow, connector and governance platform enabled")
