# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-typing-history-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_typing_history.c")
    target_link_libraries(umicom-document-typing-history-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-typing-history-test)
    umicom_apply_sanitizers(umicom-document-typing-history-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-typing-history-test)
    endif()
    foreach(case group selection unicode crlf empty unchanged pending-before-capture store-changed store-round-trip view-identity uri-changed read-only capture-read-only other-tab consumed closed null-owner null-capture other-owner invalid-selection)
        add_test(NAME framework.document.typing_history.${case} COMMAND umicom-document-typing-history-test ${case})
        set_tests_properties(framework.document.typing_history.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;history;selection;regression")
    endforeach()
endif()
