# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_pull_diagnostics_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-pull-diagnostics-gtk4-test)
        return()
    endif()
    add_executable(umicom-pull-diagnostics-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_pull_diagnostics_gtk4.c")
    target_link_libraries(umicom-pull-diagnostics-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-pull-diagnostics-gtk4-test)
    umicom_apply_sanitizers(umicom-pull-diagnostics-gtk4-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-pull-diagnostics-gtk4-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-pull-diagnostics-gtk4-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-pull-diagnostics-gtk4-test)
    endif()
    foreach(case open read private empty cancel retained unbind parent-close creation-unbind worker-unbind worker-parent-close changed-back stale apply read-only open-result choices literal related selection-stale open-unbind invalid-selection publication-invalidate choice-invalidate pull-toggle pull-toggle-back pull-output-toggle unsupported unchanged related-report invalid)
        add_test(NAME framework.document.pull_diagnostics.gtk4.${case}
            COMMAND umicom-pull-diagnostics-gtk4-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.document.pull_diagnostics.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77
            LABELS "framework;document;language;pull-diagnostics;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_pull_diagnostics_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_pull_diagnostics_checks)
endif()
