# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-delimiter-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_delimiter_navigation.c")
    target_link_libraries(umicom-document-delimiter-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-delimiter-test)
    umicom_apply_sanitizers(umicom-document-delimiter-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-delimiter-test)
    endif()
    foreach(case match reverse contents pair empty-pair read-only pending-typing unicode crlf selection other-tab history no-pair crossed closed invalid-action invalid-syntax zero-document null-owner)
        add_test(NAME framework.document.delimiter.${case} COMMAND umicom-document-delimiter-test ${case})
        set_tests_properties(framework.document.delimiter.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;delimiter;navigation;regression")
    endforeach()
endif()
