# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_workspace_symbols_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-workspace-symbols-gtk4-test)
        return()
    endif()
    add_executable(umicom-workspace-symbols-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_workspace_symbols_gtk4.c")
    target_link_libraries(umicom-workspace-symbols-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-workspace-symbols-gtk4-test)
    umicom_apply_sanitizers(umicom-workspace-symbols-gtk4-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-workspace-symbols-gtk4-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-workspace-symbols-gtk4-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-workspace-symbols-gtk4-test)
    endif()
    foreach(case open read private empty empty-query unicode-query selection multiline cancel retained unbind parent-close creation-unbind worker-unbind worker-parent-close input-change changed-back busy invalid-path stale invalidate-output apply read-only open-result hierarchy missing-range unknown-kind selection-stale open-unbind invalid-selection scope-toggle scope-back query-change query-back scope-output query-output)
        add_test(NAME framework.document.workspace_symbols.gtk4.${case}
            COMMAND umicom-workspace-symbols-gtk4-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.document.workspace_symbols.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77
            LABELS "framework;document;language;workspace-symbols;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_workspace_symbols_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_workspace_symbols_checks)
endif()
