# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# CMake adapts CTest's own JSON model. It does not run tests or parse C source.
cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/UmicomReleaseInventoryFormat.cmake")
if(NOT DEFINED BUILD OR NOT IS_DIRECTORY "${BUILD}" OR NOT DEFINED CONFIG
        OR NOT CONFIG MATCHES "^[A-Za-z0-9_-]+$")
    message(FATAL_ERROR "Pass -DBUILD=<existing binary directory> -DCONFIG=Debug (or NoConfig)")
endif()
file(REAL_PATH "${BUILD}" _build)
set(_folder "${_build}/release-inventory")
set(_inventory "${_folder}/inventory-${CONFIG}.tsv")
if(NOT EXISTS "${_inventory}" OR NOT EXISTS "${_build}/CMakeCache.txt")
    message(FATAL_ERROR "Configure this build with UMICOM_RELEASE_INVENTORY_CAPTURE=ON first")
endif()
file(SIZE "${_inventory}" _size)
if(_size GREATER 67108864)
    message(FATAL_ERROR "Configured inventory exceeds 64 MiB")
endif()
file(SHA256 "${_inventory}" _before)
file(READ "${_inventory}" _text)
if(NOT _text MATCHES "^UMICOM-RELEASE-INVENTORY\t1\ncontext\tcmake\t([0-9a-f]+)\t([0-9a-f]+)\t([0-9a-f]+)\t([0-9a-f]+)\n")
    message(FATAL_ERROR "Configured inventory has an invalid version or context")
endif()
set(_generation "${CMAKE_MATCH_1}")
set(_source_hex "${CMAKE_MATCH_2}")
set(_build_hex "${CMAKE_MATCH_3}")
set(_config_hex "${CMAKE_MATCH_4}")
string(LENGTH "${_generation}" _generation_size)
string(HEX "${_build}" _actual_build)
string(HEX "${CONFIG}" _actual_config)
file(STRINGS "${_build}/CMakeCache.txt" _home REGEX "^CMAKE_HOME_DIRECTORY:INTERNAL=" ENCODING UTF-8)
list(LENGTH _home _home_count)
if(NOT _home_count EQUAL 1)
    message(FATAL_ERROR "Build cache has no unique source root")
endif()
string(REGEX REPLACE "^CMAKE_HOME_DIRECTORY:INTERNAL=" "" _home "${_home}")
file(REAL_PATH "${_home}" _home)
string(HEX "${_home}" _actual_source)
if(NOT _generation_size EQUAL 32 OR NOT _actual_build STREQUAL _build_hex
        OR NOT _actual_config STREQUAL _config_hex OR NOT _actual_source STREQUAL _source_hex)
    message(FATAL_ERROR "Inventory context differs from this build; reconfigure and recapture")
endif()
set(_json_path "${_folder}/ctest-${CONFIG}.json")
execute_process(COMMAND "${CMAKE_CTEST_COMMAND}" --test-dir "${_build}" -C "${CONFIG}" --show-only=json-v1
    RESULT_VARIABLE _result OUTPUT_FILE "${_json_path}" ERROR_FILE "${_folder}/ctest-${CONFIG}-stderr.txt")
if(NOT _result STREQUAL "0")
    message(FATAL_ERROR "CTest registration capture failed: ${_result}; inspect ${_folder}")
endif()
file(SIZE "${_json_path}" _json_size)
if(_json_size GREATER 67108864)
    message(FATAL_ERROR "CTest JSON exceeds 64 MiB; capture refused")
endif()
file(READ "${_json_path}" _json)
string(JSON _kind GET "${_json}" kind)
string(JSON _major GET "${_json}" version major)
if(NOT _kind STREQUAL "ctestInfo" OR NOT _major EQUAL 1)
    message(FATAL_ERROR "Unsupported CTest JSON schema")
endif()
string(JSON _count LENGTH "${_json}" tests)
if(_count GREATER 200000)
    message(FATAL_ERROR "CTest inventory exceeds 200,000 records")
endif()
set(_temporary "${_folder}/ctest-${CONFIG}.tsv.pending")
file(WRITE "${_temporary}" "UMICOM-RELEASE-INVENTORY\t1\ncontext\tctest\t${_generation}\t${_source_hex}\t${_build_hex}\t${_config_hex}\n")
if(_count GREATER 0)
    math(EXPR _last "${_count} - 1")
    foreach(_index RANGE 0 ${_last})
        string(JSON _test GET "${_json}" tests ${_index})
        string(JSON _name GET "${_test}" name)
        set(_state registered)
        set(_detail "required-policy=unassigned\n")
        string(JSON _command ERROR_VARIABLE _command_error GET "${_test}" command)
        string(JSON _command_count ERROR_VARIABLE _count_error LENGTH "${_test}" command)
        if(_command_error OR _count_error OR _command_count EQUAL 0)
            set(_state missing-command)
            string(APPEND _detail "command=unavailable\n")
        else()
            # Preserve argument boundaries using the JSON array representation.
            string(APPEND _detail "command=${_command}\n")
        endif()
        string(JSON _properties LENGTH "${_test}" properties)
        if(_properties GREATER 0)
            math(EXPR _property_last "${_properties} - 1")
            foreach(_property_index RANGE 0 ${_property_last})
                string(JSON _property GET "${_test}" properties ${_property_index} name)
                # Do not copy environment variables or arbitrary properties.
                if(_property MATCHES "^(LABELS|WORKING_DIRECTORY|DISABLED|TIMEOUT|SKIP_RETURN_CODE|SKIP_REGULAR_EXPRESSION)$")
                    string(JSON _value GET "${_test}" properties ${_property_index} value)
                    string(APPEND _detail "${_property}=${_value}\n")
                    if(_property STREQUAL "DISABLED" AND _value)
                        if(_state STREQUAL "missing-command")
                            set(_state disabled-missing-command)
                        else()
                            set(_state disabled)
                        endif()
                    endif()
                endif()
            endforeach()
        endif()
        set(_owner "unavailable")
        string(JSON _backtrace ERROR_VARIABLE _trace_error GET "${_test}" backtrace)
        if(NOT _trace_error)
            string(JSON _node GET "${_json}" backtraceGraph nodes ${_backtrace})
            string(JSON _file GET "${_node}" file)
            string(JSON _owner GET "${_json}" backtraceGraph files ${_file})
            string(JSON _line ERROR_VARIABLE _line_error GET "${_node}" line)
            if(NOT _line_error)
                string(APPEND _detail "registration-line=${_line}\n")
            endif()
        endif()
        _umicom_inventory_row("${_temporary}" test "${_name}" "${_owner}" "${_state}" "${_detail}")
    endforeach()
endif()
file(SIZE "${_temporary}" _size)
if(_size GREATER 67108864)
    message(FATAL_ERROR "Encoded CTest inventory exceeds 64 MiB")
endif()
file(SHA256 "${_inventory}" _after)
if(NOT _before STREQUAL _after)
    message(FATAL_ERROR "Configuration changed during capture; recapture without concurrent configuration")
endif()
file(RENAME "${_temporary}" "${_folder}/ctest-${CONFIG}.tsv")
message(STATUS "Captured ${_count} registered tests; none executed. Compare with umicom-release-inventory.")

