#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomTreasuryRiskSettlementCollateralPlatform.cmake
#
# PURPOSE:
#   Extend canonical Umicom::finance with reusable treasury, liquidity, risk,
#   settlement, collateral, custody and securities-finance domain services.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_FINANCE_TREASURY_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
# Load the dependency only when the parent build has not already provided its target.
if(NOT TARGET umicom_finance)
    message(FATAL_ERROR "UmicomTreasuryRiskSettlementCollateralPlatform.cmake requires canonical umicom_finance")
endif()

# These domain services extend the shared finance target; TMS and other products
# remain thin consumers and do not own duplicate risk or settlement engines.
target_sources(umicom_finance PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/treasury_account.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/cash_position.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/cash_position_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/cash_forecast.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/liquidity_bucket.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/liquidity_profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/liquidity_buffer.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/liquidity_gap.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/funding_source.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/funding_source_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/funding_requirement.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/funding_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/cash_sweep_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/cash_sweep_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/bank_account.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/bank_account_registry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/nostro_account.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/payment_obligation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/settlement_obligation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/settlement_cycle.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/settlement_window.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/settlement_queue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/settlement_netting.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/settlement_failure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/settlement_repair.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/confirmation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/confirmation_matching.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/risk_factor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/risk_factor_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/risk_measure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/risk_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/risk_limit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/risk_limit_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/limit_utilization.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/limit_breach.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/exposure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/exposure_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/counterparty_exposure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/market_risk_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/liquidity_risk_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/credit_risk_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/collateral_asset.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/collateral_pool.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/collateral_agreement.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/eligibility_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/haircut_rule.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/collateral_valuation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/collateral_allocation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/margin_requirement.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/margin_call.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/margin_call_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/margin_dispute.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/netting_set.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/netting_result.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/custody_account.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/custody_position.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/custody_book.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/securities_lending_contract.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/repo_contract.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/stock_borrow_contract.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/securities_finance_exposure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/treasury_event.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/treasury_audit.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/treasury_snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/finance/treasury/treasury_service.c"
)

# Register verification targets only when the developer has enabled testing.
if(BUILD_TESTING)
    # Define the add finance treasury test build helper so parent and application projects
    # apply one consistent rule.
    function(umicom_add_finance_treasury_test target test_name source)
        # Configure the optional target only when its feature has created it.
        if(TARGET "${target}")
            return()
        endif()
        add_executable("${target}" "${UMICOM_FINANCE_TREASURY_ROOT}/${source}")
        target_link_libraries("${target}" PRIVATE Umicom::finance)
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        # Use the shared build helper when it is available from the parent composition.
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties("${test_name}" PROPERTIES LABELS "framework;finance-treasury;tms-core")
    endfunction()

    umicom_add_finance_treasury_test(
        umicom-finance-treasury-types-test
        framework.finance_treasury.types
        tests/finance_treasury/test_types.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-treasury-account-test
        framework.finance_treasury.treasury.account
        tests/finance_treasury/test_treasury_account.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-cash-position-test
        framework.finance_treasury.cash.position
        tests/finance_treasury/test_cash_position.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-cash-position-book-test
        framework.finance_treasury.cash.position.book
        tests/finance_treasury/test_cash_position_book.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-cash-forecast-test
        framework.finance_treasury.cash.forecast
        tests/finance_treasury/test_cash_forecast.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-liquidity-bucket-test
        framework.finance_treasury.liquidity.bucket
        tests/finance_treasury/test_liquidity_bucket.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-liquidity-profile-test
        framework.finance_treasury.liquidity.profile
        tests/finance_treasury/test_liquidity_profile.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-liquidity-buffer-test
        framework.finance_treasury.liquidity.buffer
        tests/finance_treasury/test_liquidity_buffer.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-liquidity-gap-test
        framework.finance_treasury.liquidity.gap
        tests/finance_treasury/test_liquidity_gap.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-funding-source-test
        framework.finance_treasury.funding.source
        tests/finance_treasury/test_funding_source.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-funding-source-catalogue-test
        framework.finance_treasury.funding.source.catalogue
        tests/finance_treasury/test_funding_source_catalogue.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-funding-requirement-test
        framework.finance_treasury.funding.requirement
        tests/finance_treasury/test_funding_requirement.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-funding-plan-test
        framework.finance_treasury.funding.plan
        tests/finance_treasury/test_funding_plan.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-cash-sweep-rule-test
        framework.finance_treasury.cash.sweep.rule
        tests/finance_treasury/test_cash_sweep_rule.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-cash-sweep-plan-test
        framework.finance_treasury.cash.sweep.plan
        tests/finance_treasury/test_cash_sweep_plan.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-bank-account-test
        framework.finance_treasury.bank.account
        tests/finance_treasury/test_bank_account.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-bank-account-registry-test
        framework.finance_treasury.bank.account.registry
        tests/finance_treasury/test_bank_account_registry.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-nostro-account-test
        framework.finance_treasury.nostro.account
        tests/finance_treasury/test_nostro_account.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-payment-obligation-test
        framework.finance_treasury.payment.obligation
        tests/finance_treasury/test_payment_obligation.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-settlement-obligation-test
        framework.finance_treasury.settlement.obligation
        tests/finance_treasury/test_settlement_obligation.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-settlement-cycle-test
        framework.finance_treasury.settlement.cycle
        tests/finance_treasury/test_settlement_cycle.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-settlement-window-test
        framework.finance_treasury.settlement.window
        tests/finance_treasury/test_settlement_window.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-settlement-queue-test
        framework.finance_treasury.settlement.queue
        tests/finance_treasury/test_settlement_queue.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-settlement-netting-test
        framework.finance_treasury.settlement.netting
        tests/finance_treasury/test_settlement_netting.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-settlement-failure-test
        framework.finance_treasury.settlement.failure
        tests/finance_treasury/test_settlement_failure.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-settlement-repair-test
        framework.finance_treasury.settlement.repair
        tests/finance_treasury/test_settlement_repair.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-confirmation-test
        framework.finance_treasury.confirmation
        tests/finance_treasury/test_confirmation.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-confirmation-matching-test
        framework.finance_treasury.confirmation.matching
        tests/finance_treasury/test_confirmation_matching.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-risk-factor-test
        framework.finance_treasury.risk.factor
        tests/finance_treasury/test_risk_factor.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-risk-factor-catalogue-test
        framework.finance_treasury.risk.factor.catalogue
        tests/finance_treasury/test_risk_factor_catalogue.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-risk-measure-test
        framework.finance_treasury.risk.measure
        tests/finance_treasury/test_risk_measure.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-risk-result-test
        framework.finance_treasury.risk.result
        tests/finance_treasury/test_risk_result.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-risk-limit-test
        framework.finance_treasury.risk.limit
        tests/finance_treasury/test_risk_limit.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-risk-limit-book-test
        framework.finance_treasury.risk.limit.book
        tests/finance_treasury/test_risk_limit_book.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-limit-utilization-test
        framework.finance_treasury.limit.utilization
        tests/finance_treasury/test_limit_utilization.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-limit-breach-test
        framework.finance_treasury.limit.breach
        tests/finance_treasury/test_limit_breach.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-exposure-test
        framework.finance_treasury.exposure
        tests/finance_treasury/test_exposure.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-exposure-book-test
        framework.finance_treasury.exposure.book
        tests/finance_treasury/test_exposure_book.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-counterparty-exposure-test
        framework.finance_treasury.counterparty.exposure
        tests/finance_treasury/test_counterparty_exposure.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-market-risk-snapshot-test
        framework.finance_treasury.market.risk.snapshot
        tests/finance_treasury/test_market_risk_snapshot.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-liquidity-risk-snapshot-test
        framework.finance_treasury.liquidity.risk.snapshot
        tests/finance_treasury/test_liquidity_risk_snapshot.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-credit-risk-snapshot-test
        framework.finance_treasury.credit.risk.snapshot
        tests/finance_treasury/test_credit_risk_snapshot.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-collateral-asset-test
        framework.finance_treasury.collateral.asset
        tests/finance_treasury/test_collateral_asset.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-collateral-pool-test
        framework.finance_treasury.collateral.pool
        tests/finance_treasury/test_collateral_pool.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-collateral-agreement-test
        framework.finance_treasury.collateral.agreement
        tests/finance_treasury/test_collateral_agreement.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-eligibility-rule-test
        framework.finance_treasury.eligibility.rule
        tests/finance_treasury/test_eligibility_rule.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-haircut-rule-test
        framework.finance_treasury.haircut.rule
        tests/finance_treasury/test_haircut_rule.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-collateral-valuation-test
        framework.finance_treasury.collateral.valuation
        tests/finance_treasury/test_collateral_valuation.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-collateral-allocation-test
        framework.finance_treasury.collateral.allocation
        tests/finance_treasury/test_collateral_allocation.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-margin-requirement-test
        framework.finance_treasury.margin.requirement
        tests/finance_treasury/test_margin_requirement.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-margin-call-test
        framework.finance_treasury.margin.call
        tests/finance_treasury/test_margin_call.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-margin-call-book-test
        framework.finance_treasury.margin.call.book
        tests/finance_treasury/test_margin_call_book.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-margin-dispute-test
        framework.finance_treasury.margin.dispute
        tests/finance_treasury/test_margin_dispute.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-netting-set-test
        framework.finance_treasury.netting.set
        tests/finance_treasury/test_netting_set.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-netting-result-test
        framework.finance_treasury.netting.result
        tests/finance_treasury/test_netting_result.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-custody-account-test
        framework.finance_treasury.custody.account
        tests/finance_treasury/test_custody_account.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-custody-position-test
        framework.finance_treasury.custody.position
        tests/finance_treasury/test_custody_position.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-custody-book-test
        framework.finance_treasury.custody.book
        tests/finance_treasury/test_custody_book.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-securities-lending-contract-test
        framework.finance_treasury.securities.lending.contract
        tests/finance_treasury/test_securities_lending_contract.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-repo-contract-test
        framework.finance_treasury.repo.contract
        tests/finance_treasury/test_repo_contract.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-stock-borrow-contract-test
        framework.finance_treasury.stock.borrow.contract
        tests/finance_treasury/test_stock_borrow_contract.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-securities-finance-exposure-test
        framework.finance_treasury.securities.finance.exposure
        tests/finance_treasury/test_securities_finance_exposure.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-treasury-event-test
        framework.finance_treasury.treasury.event
        tests/finance_treasury/test_treasury_event.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-treasury-audit-test
        framework.finance_treasury.treasury.audit
        tests/finance_treasury/test_treasury_audit.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-treasury-snapshot-test
        framework.finance_treasury.treasury.snapshot
        tests/finance_treasury/test_treasury_snapshot.c
    )
    umicom_add_finance_treasury_test(
        umicom-finance-treasury-treasury-service-test
        framework.finance_treasury.treasury.service
        tests/finance_treasury/test_treasury_service.c
    )
endif()

message(STATUS "Umicom treasury, risk, settlement, collateral and custody finance platform enabled")
