# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# This module extends the already-created creative owner; applications only
# compose its pages and never duplicate lyrics, timing or persistence logic.
include_guard(GLOBAL)
target_sources(umicom_creative_workspace PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/creative_workspace/song_plan.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/creative_workspace/song_plan_document.c")
target_link_libraries(umicom_creative_workspace PRIVATE Umicom::developer Umicom::ai Umicom::security)
if(TARGET umicom_creative_workspace_gtk4)
    target_sources(umicom_creative_workspace_gtk4 PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../adapters/gtk4/song_plan_gtk4.c")
    install(FILES "${CMAKE_CURRENT_LIST_DIR}/../include/umicom/ui/gtk4/song_plan_gtk4.h"
        DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/umicom/ui/gtk4" COMPONENT Framework)
endif()
if(BUILD_TESTING)
    add_executable(umicom-song-plan-test "${CMAKE_CURRENT_LIST_DIR}/../tests/creative_workspace/test_song_plan.c")
    target_link_libraries(umicom-song-plan-test PRIVATE Umicom::creative_workspace)
    umicom_apply_warnings(umicom-song-plan-test)
    umicom_apply_sanitizers(umicom-song-plan-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-song-plan-test)
    endif()
    foreach(case timing offset odd-tempo instrumental crlf duplicate-time outside seconds precision blank-cue markup utf8 unterminated capacity srt roundtrip import-duplicate import-trailing)
        add_test(NAME framework.song_plan.${case} COMMAND umicom-song-plan-test ${case})
        set_tests_properties(framework.song_plan.${case} PROPERTIES TIMEOUT 30 LABELS "framework;creative;regression")
    endforeach()
endif()
if(BUILD_TESTING AND TARGET umicom_creative_workspace_gtk4)
    add_executable(umicom-song-plan-gtk-test "${CMAKE_CURRENT_LIST_DIR}/../tests/creative_workspace/test_song_plan_gtk4.c")
    target_link_libraries(umicom-song-plan-gtk-test PRIVATE Umicom::creative_workspace_gtk4)
    umicom_apply_warnings(umicom-song-plan-gtk-test)
    umicom_apply_sanitizers(umicom-song-plan-gtk-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-song-plan-gtk-test)
    endif()
    foreach(case review path-approval draft-approval invalidate-title invalidate-lyrics invalidate-tempo open-denied save-empty retained)
        add_test(NAME framework.song_plan.gtk.${case} COMMAND umicom-song-plan-gtk-test ${case})
        set_tests_properties(framework.song_plan.gtk.${case} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;creative;regression;gtk4")
    endforeach()
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/learning/song-and-music-video-plans.html"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/umicom/framework/docs/learning" COMPONENT Learning)

if(BUILD_TESTING AND TARGET umicom_creative_workspace_gtk4)
    add_executable(umicom-song-video-composition-test "${CMAKE_CURRENT_LIST_DIR}/../tests/creative_workspace/test_song_video_composition_gtk4.c")
    target_link_libraries(umicom-song-video-composition-test PRIVATE Umicom::creative_workspace_gtk4)
    umicom_creative_configure_target(umicom-song-video-composition-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-song-video-composition-test)
    endif()
    foreach(profile media music)
        add_test(NAME framework.song_video.gtk.${profile} COMMAND umicom-song-video-composition-test ${profile})
        set_tests_properties(framework.song_video.gtk.${profile} PROPERTIES TIMEOUT 30 SKIP_RETURN_CODE 77 LABELS "framework;creative;gtk4;composition")
    endforeach()
endif()
