#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomDeveloperOperationsPlatform.cmake
#
# PURPOSE:
#   Complete the Framework-owned Build/Test/Debug/Terminal/VCS operational
#   projection layer consumed by Studio and future developer applications.
#
# ARCHITECTURE:
#   Canonical Test Platform, Debug Runtime, Terminal and VCS engines remain
#   authoritative. This platform adds bounded workbench projections only.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

if(NOT TARGET umicom_developer)
    message(FATAL_ERROR
        "Developer Operations Platform requires canonical umicom_developer")
endif()

target_sources(umicom_developer PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/developer_operations_internal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/branch.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/delta.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/file.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/filter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/function.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/group.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/history.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/line.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/navigation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/quality_gate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/region.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/run_compare.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/sort.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/summary.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/test_duration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/test_failure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/test_flaky.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/test_impact.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/test_result_summary.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/coverage/threshold.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/adapter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/breakpoint.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/call_stack.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/console.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/disassembly.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/frame.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/memory.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/module.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/navigation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/process.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/register.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/scope.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/snapshot.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/source.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/stop_reason.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/thread.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/toolbar.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/variable.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/debug/watch.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/command.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/environment.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/history.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/output_channel.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/output_filter.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/output_search.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/process.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/profile.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/search.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/session.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/split.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/tab.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/task_cancellation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/task_execution.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/task_group.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/task_history.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/task_progress.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/task_retry.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/transcript.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/terminal/working_directory.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/blame.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/branch.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/change_list.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/commit_graph.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/compare.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/conflict.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/diff.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/directory_compare.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/history.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/merge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/operation_journal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/partial_stage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/patch.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/repository.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/review.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/stage.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/stash.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/status.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/tag.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/developer_operations/vcs/worktree.c"
)

if(BUILD_TESTING)
    function(umicom_add_developer_operations_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()

        add_executable(
            "${target}"
            "${CMAKE_CURRENT_LIST_DIR}/../tests/developer_operations/${source}"
        )
        target_link_libraries("${target}" PRIVATE Umicom::Framework)

        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()

        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()

        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties(
            "${test_name}"
            PROPERTIES LABELS
            "framework;developer-operations;coverage;debug;terminal;vcs"
        )
    endfunction()

    umicom_add_developer_operations_test(
        umicom-developer-operations-types-test
        framework.developer_operations.types
        test_types.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-service-test
        framework.developer_operations.service
        test_service.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-branch-test
        framework.developer_operations.coverage.branch
        test_coverage_branch.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-delta-test
        framework.developer_operations.coverage.delta
        test_coverage_delta.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-file-test
        framework.developer_operations.coverage.file
        test_coverage_file.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-filter-test
        framework.developer_operations.coverage.filter
        test_coverage_filter.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-function-test
        framework.developer_operations.coverage.function
        test_coverage_function.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-group-test
        framework.developer_operations.coverage.group
        test_coverage_group.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-history-test
        framework.developer_operations.coverage.history
        test_coverage_history.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-line-test
        framework.developer_operations.coverage.line
        test_coverage_line.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-navigation-test
        framework.developer_operations.coverage.navigation
        test_coverage_navigation.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-quality-gate-test
        framework.developer_operations.coverage.quality.gate
        test_coverage_quality_gate.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-region-test
        framework.developer_operations.coverage.region
        test_coverage_region.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-run-compare-test
        framework.developer_operations.coverage.run.compare
        test_coverage_run_compare.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-sort-test
        framework.developer_operations.coverage.sort
        test_coverage_sort.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-summary-test
        framework.developer_operations.coverage.summary
        test_coverage_summary.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-test-duration-test
        framework.developer_operations.coverage.test.duration
        test_coverage_test_duration.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-test-failure-test
        framework.developer_operations.coverage.test.failure
        test_coverage_test_failure.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-test-flaky-test
        framework.developer_operations.coverage.test.flaky
        test_coverage_test_flaky.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-test-impact-test
        framework.developer_operations.coverage.test.impact
        test_coverage_test_impact.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-test-result-summary-test
        framework.developer_operations.coverage.test.result.summary
        test_coverage_test_result_summary.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-coverage-threshold-test
        framework.developer_operations.coverage.threshold
        test_coverage_threshold.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-adapter-test
        framework.developer_operations.debug.adapter
        test_debug_adapter.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-breakpoint-test
        framework.developer_operations.debug.breakpoint
        test_debug_breakpoint.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-call-stack-test
        framework.developer_operations.debug.call.stack
        test_debug_call_stack.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-console-test
        framework.developer_operations.debug.console
        test_debug_console.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-disassembly-test
        framework.developer_operations.debug.disassembly
        test_debug_disassembly.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-frame-test
        framework.developer_operations.debug.frame
        test_debug_frame.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-memory-test
        framework.developer_operations.debug.memory
        test_debug_memory.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-module-test
        framework.developer_operations.debug.module
        test_debug_module.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-navigation-test
        framework.developer_operations.debug.navigation
        test_debug_navigation.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-process-test
        framework.developer_operations.debug.process
        test_debug_process.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-register-test
        framework.developer_operations.debug.register
        test_debug_register.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-scope-test
        framework.developer_operations.debug.scope
        test_debug_scope.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-session-test
        framework.developer_operations.debug.session
        test_debug_session.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-snapshot-test
        framework.developer_operations.debug.snapshot
        test_debug_snapshot.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-source-test
        framework.developer_operations.debug.source
        test_debug_source.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-stop-reason-test
        framework.developer_operations.debug.stop.reason
        test_debug_stop_reason.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-thread-test
        framework.developer_operations.debug.thread
        test_debug_thread.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-toolbar-test
        framework.developer_operations.debug.toolbar
        test_debug_toolbar.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-variable-test
        framework.developer_operations.debug.variable
        test_debug_variable.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-debug-watch-test
        framework.developer_operations.debug.watch
        test_debug_watch.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-command-test
        framework.developer_operations.terminal.command
        test_terminal_command.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-environment-test
        framework.developer_operations.terminal.environment
        test_terminal_environment.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-history-test
        framework.developer_operations.terminal.history
        test_terminal_history.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-output-channel-test
        framework.developer_operations.terminal.output.channel
        test_terminal_output_channel.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-output-filter-test
        framework.developer_operations.terminal.output.filter
        test_terminal_output_filter.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-output-search-test
        framework.developer_operations.terminal.output.search
        test_terminal_output_search.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-process-test
        framework.developer_operations.terminal.process
        test_terminal_process.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-profile-test
        framework.developer_operations.terminal.profile
        test_terminal_profile.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-search-test
        framework.developer_operations.terminal.search
        test_terminal_search.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-session-test
        framework.developer_operations.terminal.session
        test_terminal_session.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-split-test
        framework.developer_operations.terminal.split
        test_terminal_split.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-tab-test
        framework.developer_operations.terminal.tab
        test_terminal_tab.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-task-cancellation-test
        framework.developer_operations.terminal.task.cancellation
        test_terminal_task_cancellation.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-task-execution-test
        framework.developer_operations.terminal.task.execution
        test_terminal_task_execution.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-task-group-test
        framework.developer_operations.terminal.task.group
        test_terminal_task_group.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-task-history-test
        framework.developer_operations.terminal.task.history
        test_terminal_task_history.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-task-progress-test
        framework.developer_operations.terminal.task.progress
        test_terminal_task_progress.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-task-retry-test
        framework.developer_operations.terminal.task.retry
        test_terminal_task_retry.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-transcript-test
        framework.developer_operations.terminal.transcript
        test_terminal_transcript.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-terminal-working-directory-test
        framework.developer_operations.terminal.working.directory
        test_terminal_working_directory.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-blame-test
        framework.developer_operations.vcs.blame
        test_vcs_blame.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-branch-test
        framework.developer_operations.vcs.branch
        test_vcs_branch.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-change-list-test
        framework.developer_operations.vcs.change.list
        test_vcs_change_list.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-commit-graph-test
        framework.developer_operations.vcs.commit.graph
        test_vcs_commit_graph.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-compare-test
        framework.developer_operations.vcs.compare
        test_vcs_compare.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-conflict-test
        framework.developer_operations.vcs.conflict
        test_vcs_conflict.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-diff-test
        framework.developer_operations.vcs.diff
        test_vcs_diff.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-directory-compare-test
        framework.developer_operations.vcs.directory.compare
        test_vcs_directory_compare.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-history-test
        framework.developer_operations.vcs.history
        test_vcs_history.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-merge-test
        framework.developer_operations.vcs.merge
        test_vcs_merge.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-operation-journal-test
        framework.developer_operations.vcs.operation.journal
        test_vcs_operation_journal.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-partial-stage-test
        framework.developer_operations.vcs.partial.stage
        test_vcs_partial_stage.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-patch-test
        framework.developer_operations.vcs.patch
        test_vcs_patch.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-repository-test
        framework.developer_operations.vcs.repository
        test_vcs_repository.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-review-test
        framework.developer_operations.vcs.review
        test_vcs_review.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-stage-test
        framework.developer_operations.vcs.stage
        test_vcs_stage.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-stash-test
        framework.developer_operations.vcs.stash
        test_vcs_stash.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-status-test
        framework.developer_operations.vcs.status
        test_vcs_status.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-tag-test
        framework.developer_operations.vcs.tag
        test_vcs_tag.c
    )
    umicom_add_developer_operations_test(
        umicom-developer-operations-vcs-worktree-test
        framework.developer_operations.vcs.worktree
        test_vcs_worktree.c
    )
endif()

message(STATUS
    "Umicom Developer Operations workbench projections enabled")
