# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_document_formats_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-document-formats-gtk4-test)
        return()
    endif()
    add_executable(umicom-document-formats-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_document_format_gtk4.c")
    target_link_libraries(umicom-document-formats-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-document-formats-gtk4-test)
    umicom_apply_sanitizers(umicom-document-formats-gtk4-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-formats-gtk4-test)
    endif()
    foreach(case lf crlf encoding-only read-only no-document unbound null-adapter parent-close completion-detach completion-destroy unchanged)
        add_test(NAME framework.document.document_formats.gtk4.${case}
            COMMAND umicom-document-formats-gtk4-test ${case})
        set_tests_properties(framework.document.document_formats.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77
            LABELS "framework;document;language;document-format;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_document_formats_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_document_formats_checks)
endif()
