# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-native-range-formatting-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_native_range_formatting.c")
    target_link_libraries(umicom-native-range-formatting-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-native-range-formatting-test)
    umicom_apply_sanitizers(umicom-native-range-formatting-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-native-range-formatting-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-native-range-formatting-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-native-range-formatting-test)
    endif()
    foreach(case valid unicode empty tabs error invalid timeout encoding shutdown cancel surrounding multiline)
        add_test(NAME framework.language_runtime.native_range_formatting.${case} COMMAND umicom-native-range-formatting-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.language_runtime.native_range_formatting.${case} PROPERTIES TIMEOUT 40
            LABELS "framework;language;formatting;native;ownership;regression")
    endforeach()
endif()
