# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-image-edit-test "${CMAKE_CURRENT_LIST_DIR}/../tests/media/test_image_edit.c")
    target_link_libraries(umicom-image-edit-test PRIVATE Umicom::media_engine)
    set_target_properties(umicom-image-edit-test PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings(umicom-image-edit-test)
    umicom_apply_sanitizers(umicom-image-edit-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-image-edit-test)
    endif()
    foreach(case identity crop crop-clockwise clockwise counterclockwise half-turn flip-horizontal flip-vertical one-pixel empty-width empty-height outside-x outside-y oversized-width oversized-height invalid-orientation cancelled live-output null-source null-edit null-output pixel-limit)
        add_test(NAME framework.media.image_edit.${case} COMMAND umicom-image-edit-test ${case})
        set_tests_properties(framework.media.image_edit.${case} PROPERTIES TIMEOUT 30 LABELS "framework;media;image-edit;regression")
    endforeach()
endif()
