# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-workspace-edit-scope-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_workspace_edit_scope.c")
    target_link_libraries(umicom-workspace-edit-scope-test PRIVATE Umicom::developer)
    umicom_apply_warnings(umicom-workspace-edit-scope-test)
    umicom_apply_sanitizers(umicom-workspace-edit-scope-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-workspace-edit-scope-test)
    endif()
    foreach(case single other multiple empty-other-group empty empty-edits null-uri empty-uri null-catalogue null-output cancelled version stale missing-version source-invalid source-caret annotation)
        add_test(NAME framework.language_runtime.workspace_edit_scope.${case} COMMAND umicom-workspace-edit-scope-test ${case})
        set_tests_properties(framework.language_runtime.workspace_edit_scope.${case} PROPERTIES TIMEOUT 30
            LABELS "framework;language;workspace-edits;ownership;regression")
    endforeach()
endif()
