# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
function(umicom_attach_workspace_rename_checks)
    if(NOT TARGET umicom_ui_gtk4 OR NOT BUILD_TESTING OR TARGET umicom-workspace-rename-gtk4-test)
        return()
    endif()
    add_executable(umicom-workspace-rename-gtk4-test "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/document/test_workspace_rename_gtk4.c")
    target_link_libraries(umicom-workspace-rename-gtk4-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-workspace-rename-gtk4-test)
    umicom_apply_sanitizers(umicom-workspace-rename-gtk4-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-workspace-rename-gtk4-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-workspace-rename-gtk4-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-workspace-rename-gtk4-test)
    endif()
    foreach(case apply-all undo readonly-dependency readonly-target stale-dependency stale-primary changed-back toggle worker-unbind parent-close unknown version-stale invalid-range other-language single-option private)
        add_test(NAME framework.document.workspace_rename.gtk4.${case}
            COMMAND umicom-workspace-rename-gtk4-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.document.workspace_rename.gtk4.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77
            LABELS "framework;document;language;rename;gtk4;ownership;regression")
    endforeach()
endfunction()
umicom_attach_workspace_rename_checks()
if(NOT TARGET umicom_ui_gtk4)
    cmake_language(DEFER CALL umicom_attach_workspace_rename_checks)
endif()
