# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-source-batch-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_source_batch.c")
    target_link_libraries(umicom-document-source-batch-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-source-batch-test)
    umicom_apply_sanitizers(umicom-document-source-batch-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-source-batch-test)
    endif()
    foreach(case capture ownership apply reverse-order empty unchanged mixed pending-typing return-to-store unchanged-pending undo redo stale-first stale-last round-trip caret selection language read-only closed external saved other-owner active-tab presentation approval revision restage incomplete duplicate missing invalid-id invalid-utf8 embedded-zero cursor-utf8 cursor-crlf large limits consumed arguments)
        add_test(NAME framework.document.source_batch.${case} COMMAND umicom-document-source-batch-test ${case})
        set_tests_properties(framework.document.source_batch.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;source;review;regression")
    endforeach()
endif()
