#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomLanguageIntelligencePlatform.cmake
#
# PURPOSE:
#   Complete the provider-neutral native language-intelligence control plane:
#   provider orchestration, routing, request governance, diagnostics/semantic
#   state, workspace indexes, advanced editor intelligence and supervision.
#
# ARCHITECTURE:
#   Extend the established umicom_language target. Do not create a competing
#   language stack and do not move reusable language behaviour into Studio.
#
# Created by: Sammy Hegab
# Organisation: Umicom Foundation
# Licence: MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

set(UMICOM_LANGUAGE_INTELLIGENCE_FRAMEWORK_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
if(NOT TARGET umicom_language)
    message(FATAL_ERROR
        "UmicomLanguageIntelligencePlatform.cmake requires umicom_language.")
endif()

target_sources(umicom_language PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/provider_descriptor.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/provider_catalogue.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/provider_selection.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/provider_priority.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/provider_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/provider_recovery.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/provider_supervision.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/provider_affinity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/provider_quarantine.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/capability_negotiation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/document_routing.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/document_ownership.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/workspace_routing.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/workspace_folder.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/workspace_configuration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/project_language_map.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/toolchain_language_bridge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/compilation_database_bridge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/file_watch_registration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/notebook_document.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/request_scheduler.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/request_priority.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/request_cancellation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/request_deadline.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/request_coalescing.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/request_throttle.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/request_budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/response_cache.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/result_freshness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/stale_result_policy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/diagnostics_merge.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/diagnostics_deduplication.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/diagnostics_suppression.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/diagnostics_baseline.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/diagnostics_pull_state.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/semantic_refresh.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/semantic_delta.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/semantic_legend.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/semantic_cache.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/semantic_budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/symbol_index.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/symbol_ranking.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/symbol_search.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/references_index.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/navigation_graph.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/declaration_query.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/implementation_query.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/type_definition_query.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/call_hierarchy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/type_hierarchy.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/selection_range.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/document_link.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/code_lens.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/inline_value.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/linked_editing.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/document_colour.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/colour_presentation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/moniker.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/rename_preview.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/workspace_edit_validation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/dynamic_registration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/progress_tracking.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/server_trace.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/performance_budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/language/intelligence/intelligence_session.c"
)

if(BUILD_TESTING)
    function(umicom_add_language_intelligence_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()
        add_executable(
            "${target}"
            "${UMICOM_LANGUAGE_INTELLIGENCE_FRAMEWORK_ROOT}/${source}"
        )
        target_link_libraries("${target}" PRIVATE Umicom::language)
        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()
        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties(
            "${test_name}"
            PROPERTIES LABELS "framework;language-intelligence"
        )
    endfunction()

    umicom_add_language_intelligence_test(
        umicom-language-intelligence-types-test
        framework.language_intelligence.types
        tests/language_intelligence/test_types.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-provider-descriptor-test
        framework.language_intelligence.provider.descriptor
        tests/language_intelligence/test_provider_descriptor.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-provider-catalogue-test
        framework.language_intelligence.provider.catalogue
        tests/language_intelligence/test_provider_catalogue.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-provider-selection-test
        framework.language_intelligence.provider.selection
        tests/language_intelligence/test_provider_selection.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-provider-priority-test
        framework.language_intelligence.provider.priority
        tests/language_intelligence/test_provider_priority.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-provider-health-test
        framework.language_intelligence.provider.health
        tests/language_intelligence/test_provider_health.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-provider-recovery-test
        framework.language_intelligence.provider.recovery
        tests/language_intelligence/test_provider_recovery.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-provider-supervision-test
        framework.language_intelligence.provider.supervision
        tests/language_intelligence/test_provider_supervision.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-provider-affinity-test
        framework.language_intelligence.provider.affinity
        tests/language_intelligence/test_provider_affinity.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-provider-quarantine-test
        framework.language_intelligence.provider.quarantine
        tests/language_intelligence/test_provider_quarantine.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-capability-negotiation-test
        framework.language_intelligence.capability.negotiation
        tests/language_intelligence/test_capability_negotiation.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-document-routing-test
        framework.language_intelligence.document.routing
        tests/language_intelligence/test_document_routing.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-document-ownership-test
        framework.language_intelligence.document.ownership
        tests/language_intelligence/test_document_ownership.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-workspace-routing-test
        framework.language_intelligence.workspace.routing
        tests/language_intelligence/test_workspace_routing.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-workspace-folder-test
        framework.language_intelligence.workspace.folder
        tests/language_intelligence/test_workspace_folder.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-workspace-configuration-test
        framework.language_intelligence.workspace.configuration
        tests/language_intelligence/test_workspace_configuration.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-project-language-map-test
        framework.language_intelligence.project.language.map
        tests/language_intelligence/test_project_language_map.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-toolchain-language-bridge-test
        framework.language_intelligence.toolchain.language.bridge
        tests/language_intelligence/test_toolchain_language_bridge.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-compilation-database-bridge-test
        framework.language_intelligence.compilation.database.bridge
        tests/language_intelligence/test_compilation_database_bridge.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-file-watch-registration-test
        framework.language_intelligence.file.watch.registration
        tests/language_intelligence/test_file_watch_registration.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-notebook-document-test
        framework.language_intelligence.notebook.document
        tests/language_intelligence/test_notebook_document.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-request-scheduler-test
        framework.language_intelligence.request.scheduler
        tests/language_intelligence/test_request_scheduler.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-request-priority-test
        framework.language_intelligence.request.priority
        tests/language_intelligence/test_request_priority.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-request-cancellation-test
        framework.language_intelligence.request.cancellation
        tests/language_intelligence/test_request_cancellation.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-request-deadline-test
        framework.language_intelligence.request.deadline
        tests/language_intelligence/test_request_deadline.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-request-coalescing-test
        framework.language_intelligence.request.coalescing
        tests/language_intelligence/test_request_coalescing.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-request-throttle-test
        framework.language_intelligence.request.throttle
        tests/language_intelligence/test_request_throttle.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-request-budget-test
        framework.language_intelligence.request.budget
        tests/language_intelligence/test_request_budget.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-response-cache-test
        framework.language_intelligence.response.cache
        tests/language_intelligence/test_response_cache.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-result-freshness-test
        framework.language_intelligence.result.freshness
        tests/language_intelligence/test_result_freshness.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-stale-result-policy-test
        framework.language_intelligence.stale.result.policy
        tests/language_intelligence/test_stale_result_policy.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-diagnostics-merge-test
        framework.language_intelligence.diagnostics.merge
        tests/language_intelligence/test_diagnostics_merge.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-diagnostics-deduplication-test
        framework.language_intelligence.diagnostics.deduplication
        tests/language_intelligence/test_diagnostics_deduplication.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-diagnostics-suppression-test
        framework.language_intelligence.diagnostics.suppression
        tests/language_intelligence/test_diagnostics_suppression.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-diagnostics-baseline-test
        framework.language_intelligence.diagnostics.baseline
        tests/language_intelligence/test_diagnostics_baseline.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-diagnostics-pull-state-test
        framework.language_intelligence.diagnostics.pull.state
        tests/language_intelligence/test_diagnostics_pull_state.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-semantic-refresh-test
        framework.language_intelligence.semantic.refresh
        tests/language_intelligence/test_semantic_refresh.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-semantic-delta-test
        framework.language_intelligence.semantic.delta
        tests/language_intelligence/test_semantic_delta.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-semantic-legend-test
        framework.language_intelligence.semantic.legend
        tests/language_intelligence/test_semantic_legend.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-semantic-cache-test
        framework.language_intelligence.semantic.cache
        tests/language_intelligence/test_semantic_cache.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-semantic-budget-test
        framework.language_intelligence.semantic.budget
        tests/language_intelligence/test_semantic_budget.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-symbol-index-test
        framework.language_intelligence.symbol.index
        tests/language_intelligence/test_symbol_index.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-symbol-ranking-test
        framework.language_intelligence.symbol.ranking
        tests/language_intelligence/test_symbol_ranking.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-symbol-search-test
        framework.language_intelligence.symbol.search
        tests/language_intelligence/test_symbol_search.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-references-index-test
        framework.language_intelligence.references.index
        tests/language_intelligence/test_references_index.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-navigation-graph-test
        framework.language_intelligence.navigation.graph
        tests/language_intelligence/test_navigation_graph.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-declaration-query-test
        framework.language_intelligence.declaration.query
        tests/language_intelligence/test_declaration_query.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-implementation-query-test
        framework.language_intelligence.implementation.query
        tests/language_intelligence/test_implementation_query.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-type-definition-query-test
        framework.language_intelligence.type.definition.query
        tests/language_intelligence/test_type_definition_query.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-call-hierarchy-test
        framework.language_intelligence.call.hierarchy
        tests/language_intelligence/test_call_hierarchy.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-type-hierarchy-test
        framework.language_intelligence.type.hierarchy
        tests/language_intelligence/test_type_hierarchy.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-selection-range-test
        framework.language_intelligence.selection.range
        tests/language_intelligence/test_selection_range.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-document-link-test
        framework.language_intelligence.document.link
        tests/language_intelligence/test_document_link.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-code-lens-test
        framework.language_intelligence.code.lens
        tests/language_intelligence/test_code_lens.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-inline-value-test
        framework.language_intelligence.inline.value
        tests/language_intelligence/test_inline_value.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-linked-editing-test
        framework.language_intelligence.linked.editing
        tests/language_intelligence/test_linked_editing.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-document-colour-test
        framework.language_intelligence.document.colour
        tests/language_intelligence/test_document_colour.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-colour-presentation-test
        framework.language_intelligence.colour.presentation
        tests/language_intelligence/test_colour_presentation.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-moniker-test
        framework.language_intelligence.moniker
        tests/language_intelligence/test_moniker.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-rename-preview-test
        framework.language_intelligence.rename.preview
        tests/language_intelligence/test_rename_preview.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-workspace-edit-validation-test
        framework.language_intelligence.workspace.edit.validation
        tests/language_intelligence/test_workspace_edit_validation.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-dynamic-registration-test
        framework.language_intelligence.dynamic.registration
        tests/language_intelligence/test_dynamic_registration.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-progress-tracking-test
        framework.language_intelligence.progress.tracking
        tests/language_intelligence/test_progress_tracking.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-server-trace-test
        framework.language_intelligence.server.trace
        tests/language_intelligence/test_server_trace.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-performance-budget-test
        framework.language_intelligence.performance.budget
        tests/language_intelligence/test_performance_budget.c
    )
    umicom_add_language_intelligence_test(
        umicom-language-intelligence-intelligence-session-test
        framework.language_intelligence.intelligence.session
        tests/language_intelligence/test_intelligence_session.c
    )
endif()

message(STATUS
    "Umicom native language-intelligence orchestration and advanced services enabled")
