# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-recovery-storage-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_recovery_storage.c")
    target_link_libraries(umicom-recovery-storage-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-recovery-storage-test)
    umicom_apply_sanitizers(umicom-recovery-storage-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-recovery-storage-test)
    endif()
    foreach(case save-load exclusive collision-different missing-directory empty-list list-limit scan-limit ignore-names list-directory file-root relative-root traversal-root unicode-root malformed truncated mismatched-key oversized cancelled-save cancelled-load cancelled-list invalid-key leaf-symlink root-symlink directory-path directory-capacity directory-relative-base null-save null-load null-list list-index)
        add_test(NAME framework.document.recovery_storage.${case} COMMAND umicom-recovery-storage-test ${case})
        set_tests_properties(framework.document.recovery_storage.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77 LABELS "framework;document;recovery;regression")
    endforeach()
endif()
