# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Register local evidence tests without granting any execution-provider access.
include_guard(GLOBAL)
if(BUILD_TESTING AND TARGET Umicom::trading_ui)
    foreach(kind IN ITEMS report exports)
        add_executable(umicom-trading-session-${kind}-test "${CMAKE_CURRENT_LIST_DIR}/../tests/trading_session/test_${kind}.c")
        target_link_libraries(umicom-trading-session-${kind}-test PRIVATE Umicom::trading_ui)
        umicom_apply_warnings(umicom-trading-session-${kind}-test)
        umicom_apply_sanitizers(umicom-trading-session-${kind}-test)
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(umicom-trading-session-${kind}-test)
        endif()
    endforeach()
    foreach(case IN ITEMS empty round-trip partial-cancel ownership current filters invalid quantity price status account environment
            duplicate-order orphan-fill duplicate-fill position-quantity position-price position-pnl missing-position contract currencies nonfinite bounds total-overflow different-owner)
        add_test(NAME framework.trading_session.report.${case} COMMAND umicom-trading-session-report-test ${case})
        set_tests_properties(framework.trading_session.report.${case} PROPERTIES TIMEOUT 30 LABELS "trading;report;reconciliation;regression")
    endforeach()
    foreach(case IN ITEMS text issues empty formula ownership invalid)
        add_test(NAME framework.trading_session.exports.${case} COMMAND umicom-trading-session-exports-test ${case})
        set_tests_properties(framework.trading_session.exports.${case} PROPERTIES TIMEOUT 30 LABELS "trading;report;csv;regression")
    endforeach()
    if(TARGET Umicom::ui_gtk4)
        add_executable(umicom-trading-session-native-test "${CMAKE_CURRENT_LIST_DIR}/../tests/trading_session/test_native.c")
        target_link_libraries(umicom-trading-session-native-test PRIVATE Umicom::ui_gtk4)
        umicom_apply_warnings(umicom-trading-session-native-test)
        umicom_apply_sanitizers(umicom-trading-session-native-test)
        if(COMMAND umicom_register_validation_target)
            umicom_register_validation_target(umicom-trading-session-native-test)
        endif()
        foreach(case IN ITEMS filter stale body-refresh failed-refresh detach mount-destroy)
            add_test(NAME framework.trading_session.native.${case} COMMAND umicom-trading-session-native-test ${case})
            set_tests_properties(framework.trading_session.native.${case} PROPERTIES TIMEOUT 45 SKIP_RETURN_CODE 77 LABELS "trading;report;gtk4;regression")
        endforeach()
    endif()
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/TRADING_SESSION_REVIEW.md"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/framework/docs COMPONENT Framework)
