#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/UmicomProfessionalTradingWorkstationPlatform.cmake
#
# PURPOSE:
#   Extend canonical trading presentation with professional workstation
#   calculations for watchlists, depth/DOM, charts, Time and Sales, guarded
#   execution, portfolio/P&L, alerts, scanners, events and linked context.
#
# ARCHITECTURE:
#   The existing trading workspace, market-data, order, risk and context
#   services remain authoritative. These sources calculate copied projections
#   and readiness state only; no second broker or execution engine is created.
#
# AUTHOR AND ORGANISATION:
#   Sammy Hegab
#   Umicom Foundation
#
# LICENCE:
#   MIT
#-----------------------------------------------------------------------------
include_guard(GLOBAL)

if(NOT TARGET umicom_trading_ui)
    message(FATAL_ERROR
        "Professional Trading Workstation requires canonical umicom_trading_ui")
endif()

target_sources(umicom_trading_ui PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/types.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/trading_workstation_internal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/service.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/chart_tape/activity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/chart_tape/chart_range.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/chart_tape/chart_readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/chart_tape/linked_context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/chart_tape/momentum.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/chart_tape/tape_readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/chart_tape/trade_rate.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/chart_tape/trade_size_signal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/chart_tape/volatility.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/chart_tape/volume_signal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/depth/ask_pressure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/depth/bid_pressure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/depth/imbalance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/depth/ladder_density.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/depth/microprice.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/depth/quality.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/depth/readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/depth/spread_ticks.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/depth/sweep_risk.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/depth/top_liquidity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/execution/buying_power_use.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/execution/cancel_readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/execution/fill_progress.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/execution/limit_distance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/execution/order_notional.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/execution/order_validation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/execution/readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/execution/risk_limit_use.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/execution/stop_distance.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/execution/submit_readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/market/feed_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/market/quote_change.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/market/quote_change_percent.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/market/quote_midprice.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/market/quote_readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/market/quote_spread.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/market/quote_staleness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/market/range_position.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/market/session_range.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/market/spread_basis_points.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/portfolio/concentration.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/portfolio/gross_exposure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/portfolio/margin_utilisation.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/portfolio/net_exposure.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/portfolio/position_count.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/portfolio/position_notional.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/portfolio/readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/portfolio/realised_pnl.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/portfolio/risk_budget.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/portfolio/unrealised_pnl.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/research/alert_attention.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/research/alert_density.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/research/alert_trigger.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/research/calendar_impact.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/research/calendar_proximity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/research/readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/research/research_quality.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/research/scanner_momentum.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/research/scanner_score.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/research/scanner_volume.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/watchlist/alert_density.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/watchlist/capacity.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/watchlist/context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/watchlist/instrument_count.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/watchlist/momentum.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/watchlist/ranking.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/watchlist/readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/watchlist/spread_quality.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/watchlist/visible_ratio.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/watchlist/volume_signal.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/workstation/account_context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/workstation/chart_sync.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/workstation/crosshair_sync.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/workstation/data_quality.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/workstation/instrument_context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/workstation/link_group_health.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/workstation/order_context.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/workstation/panel_readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/workstation/professional_readiness.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/trading_workstation/workstation/timeframe_sync.c"
)

if(BUILD_TESTING)
    function(umicom_add_professional_trading_test target test_name source)
        if(TARGET "${target}")
            return()
        endif()

        add_executable(
            "${target}"
            "${CMAKE_CURRENT_LIST_DIR}/../tests/trading_workstation/${source}"
        )
        target_link_libraries("${target}" PRIVATE Umicom::Framework)

        if(COMMAND umicom_apply_warnings)
            umicom_apply_warnings("${target}")
        endif()
        if(COMMAND umicom_apply_sanitizers)
            umicom_apply_sanitizers("${target}")
        endif()

        add_test(NAME "${test_name}" COMMAND "${target}")
        set_tests_properties(
            "${test_name}"
            PROPERTIES LABELS
            "framework;trading;professional-workstation;trader;market-data;risk"
        )
    endfunction()

    umicom_add_professional_trading_test(
        umicom-professional-trading-types-test
        framework.trading_workstation.types
        test_types.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-service-test
        framework.trading_workstation.service
        test_service_catalogue.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-chart_tape-activity-test
        framework.trading_workstation.chart_tape.activity
        test_chart_tape_activity.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-chart_tape-chart-range-test
        framework.trading_workstation.chart_tape.chart.range
        test_chart_tape_chart_range.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-chart_tape-chart-readiness-test
        framework.trading_workstation.chart_tape.chart.readiness
        test_chart_tape_chart_readiness.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-chart_tape-linked-context-test
        framework.trading_workstation.chart_tape.linked.context
        test_chart_tape_linked_context.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-chart_tape-momentum-test
        framework.trading_workstation.chart_tape.momentum
        test_chart_tape_momentum.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-chart_tape-tape-readiness-test
        framework.trading_workstation.chart_tape.tape.readiness
        test_chart_tape_tape_readiness.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-chart_tape-trade-rate-test
        framework.trading_workstation.chart_tape.trade.rate
        test_chart_tape_trade_rate.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-chart_tape-trade-size-signal-test
        framework.trading_workstation.chart_tape.trade.size.signal
        test_chart_tape_trade_size_signal.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-chart_tape-volatility-test
        framework.trading_workstation.chart_tape.volatility
        test_chart_tape_volatility.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-chart_tape-volume-signal-test
        framework.trading_workstation.chart_tape.volume.signal
        test_chart_tape_volume_signal.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-depth-ask-pressure-test
        framework.trading_workstation.depth.ask.pressure
        test_depth_ask_pressure.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-depth-bid-pressure-test
        framework.trading_workstation.depth.bid.pressure
        test_depth_bid_pressure.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-depth-imbalance-test
        framework.trading_workstation.depth.imbalance
        test_depth_imbalance.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-depth-ladder-density-test
        framework.trading_workstation.depth.ladder.density
        test_depth_ladder_density.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-depth-microprice-test
        framework.trading_workstation.depth.microprice
        test_depth_microprice.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-depth-quality-test
        framework.trading_workstation.depth.quality
        test_depth_quality.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-depth-readiness-test
        framework.trading_workstation.depth.readiness
        test_depth_readiness.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-depth-spread-ticks-test
        framework.trading_workstation.depth.spread.ticks
        test_depth_spread_ticks.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-depth-sweep-risk-test
        framework.trading_workstation.depth.sweep.risk
        test_depth_sweep_risk.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-depth-top-liquidity-test
        framework.trading_workstation.depth.top.liquidity
        test_depth_top_liquidity.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-execution-buying-power-use-test
        framework.trading_workstation.execution.buying.power.use
        test_execution_buying_power_use.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-execution-cancel-readiness-test
        framework.trading_workstation.execution.cancel.readiness
        test_execution_cancel_readiness.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-execution-fill-progress-test
        framework.trading_workstation.execution.fill.progress
        test_execution_fill_progress.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-execution-limit-distance-test
        framework.trading_workstation.execution.limit.distance
        test_execution_limit_distance.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-execution-order-notional-test
        framework.trading_workstation.execution.order.notional
        test_execution_order_notional.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-execution-order-validation-test
        framework.trading_workstation.execution.order.validation
        test_execution_order_validation.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-execution-readiness-test
        framework.trading_workstation.execution.readiness
        test_execution_readiness.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-execution-risk-limit-use-test
        framework.trading_workstation.execution.risk.limit.use
        test_execution_risk_limit_use.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-execution-stop-distance-test
        framework.trading_workstation.execution.stop.distance
        test_execution_stop_distance.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-execution-submit-readiness-test
        framework.trading_workstation.execution.submit.readiness
        test_execution_submit_readiness.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-market-feed-health-test
        framework.trading_workstation.market.feed.health
        test_market_feed_health.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-market-quote-change-test
        framework.trading_workstation.market.quote.change
        test_market_quote_change.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-market-quote-change-percent-test
        framework.trading_workstation.market.quote.change.percent
        test_market_quote_change_percent.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-market-quote-midprice-test
        framework.trading_workstation.market.quote.midprice
        test_market_quote_midprice.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-market-quote-readiness-test
        framework.trading_workstation.market.quote.readiness
        test_market_quote_readiness.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-market-quote-spread-test
        framework.trading_workstation.market.quote.spread
        test_market_quote_spread.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-market-quote-staleness-test
        framework.trading_workstation.market.quote.staleness
        test_market_quote_staleness.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-market-range-position-test
        framework.trading_workstation.market.range.position
        test_market_range_position.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-market-session-range-test
        framework.trading_workstation.market.session.range
        test_market_session_range.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-market-spread-basis-points-test
        framework.trading_workstation.market.spread.basis.points
        test_market_spread_basis_points.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-portfolio-concentration-test
        framework.trading_workstation.portfolio.concentration
        test_portfolio_concentration.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-portfolio-gross-exposure-test
        framework.trading_workstation.portfolio.gross.exposure
        test_portfolio_gross_exposure.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-portfolio-margin-utilisation-test
        framework.trading_workstation.portfolio.margin.utilisation
        test_portfolio_margin_utilisation.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-portfolio-net-exposure-test
        framework.trading_workstation.portfolio.net.exposure
        test_portfolio_net_exposure.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-portfolio-position-count-test
        framework.trading_workstation.portfolio.position.count
        test_portfolio_position_count.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-portfolio-position-notional-test
        framework.trading_workstation.portfolio.position.notional
        test_portfolio_position_notional.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-portfolio-readiness-test
        framework.trading_workstation.portfolio.readiness
        test_portfolio_readiness.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-portfolio-realised-pnl-test
        framework.trading_workstation.portfolio.realised.pnl
        test_portfolio_realised_pnl.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-portfolio-risk-budget-test
        framework.trading_workstation.portfolio.risk.budget
        test_portfolio_risk_budget.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-portfolio-unrealised-pnl-test
        framework.trading_workstation.portfolio.unrealised.pnl
        test_portfolio_unrealised_pnl.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-research-alert-attention-test
        framework.trading_workstation.research.alert.attention
        test_research_alert_attention.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-research-alert-density-test
        framework.trading_workstation.research.alert.density
        test_research_alert_density.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-research-alert-trigger-test
        framework.trading_workstation.research.alert.trigger
        test_research_alert_trigger.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-research-calendar-impact-test
        framework.trading_workstation.research.calendar.impact
        test_research_calendar_impact.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-research-calendar-proximity-test
        framework.trading_workstation.research.calendar.proximity
        test_research_calendar_proximity.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-research-readiness-test
        framework.trading_workstation.research.readiness
        test_research_readiness.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-research-research-quality-test
        framework.trading_workstation.research.research.quality
        test_research_research_quality.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-research-scanner-momentum-test
        framework.trading_workstation.research.scanner.momentum
        test_research_scanner_momentum.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-research-scanner-score-test
        framework.trading_workstation.research.scanner.score
        test_research_scanner_score.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-research-scanner-volume-test
        framework.trading_workstation.research.scanner.volume
        test_research_scanner_volume.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-watchlist-alert-density-test
        framework.trading_workstation.watchlist.alert.density
        test_watchlist_alert_density.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-watchlist-capacity-test
        framework.trading_workstation.watchlist.capacity
        test_watchlist_capacity.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-watchlist-context-test
        framework.trading_workstation.watchlist.context
        test_watchlist_context.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-watchlist-instrument-count-test
        framework.trading_workstation.watchlist.instrument.count
        test_watchlist_instrument_count.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-watchlist-momentum-test
        framework.trading_workstation.watchlist.momentum
        test_watchlist_momentum.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-watchlist-ranking-test
        framework.trading_workstation.watchlist.ranking
        test_watchlist_ranking.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-watchlist-readiness-test
        framework.trading_workstation.watchlist.readiness
        test_watchlist_readiness.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-watchlist-spread-quality-test
        framework.trading_workstation.watchlist.spread.quality
        test_watchlist_spread_quality.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-watchlist-visible-ratio-test
        framework.trading_workstation.watchlist.visible.ratio
        test_watchlist_visible_ratio.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-watchlist-volume-signal-test
        framework.trading_workstation.watchlist.volume.signal
        test_watchlist_volume_signal.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-workstation-account-context-test
        framework.trading_workstation.workstation.account.context
        test_workstation_account_context.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-workstation-chart-sync-test
        framework.trading_workstation.workstation.chart.sync
        test_workstation_chart_sync.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-workstation-crosshair-sync-test
        framework.trading_workstation.workstation.crosshair.sync
        test_workstation_crosshair_sync.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-workstation-data-quality-test
        framework.trading_workstation.workstation.data.quality
        test_workstation_data_quality.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-workstation-instrument-context-test
        framework.trading_workstation.workstation.instrument.context
        test_workstation_instrument_context.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-workstation-link-group-health-test
        framework.trading_workstation.workstation.link.group.health
        test_workstation_link_group_health.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-workstation-order-context-test
        framework.trading_workstation.workstation.order.context
        test_workstation_order_context.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-workstation-panel-readiness-test
        framework.trading_workstation.workstation.panel.readiness
        test_workstation_panel_readiness.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-workstation-professional-readiness-test
        framework.trading_workstation.workstation.professional.readiness
        test_workstation_professional_readiness.c
    )
    umicom_add_professional_trading_test(
        umicom-professional-trading-workstation-timeframe-sync-test
        framework.trading_workstation.workstation.timeframe.sync
        test_workstation_timeframe_sync.c
    )
endif()

message(STATUS
    "Umicom professional trading workstation calculations enabled")
