# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
target_sources(umicom_developer PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/debug_runtime/exception_information.c")
if(TARGET umicom_ui_gtk4)
    target_sources(umicom_ui_gtk4 PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../adapters/gtk4/debug_exception_information.c")
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/DEBUG_EXCEPTION_INFORMATION.html"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/umicom-framework/docs" COMPONENT Framework)
if(NOT BUILD_TESTING)
    return()
endif()
function(umicom_exception_information_test target source owner)
    add_executable("${target}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/debug_exception_information/${source}")
    target_link_libraries("${target}" PRIVATE "${owner}")
    set_target_properties("${target}" PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings("${target}")
    umicom_apply_sanitizers("${target}")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target("${target}")
    endif()
endfunction()
function(umicom_exception_information_case group target case)
    add_test(NAME framework.debug.exception_information.${group}.${case} COMMAND "${target}" "${case}" ${ARGN})
    set_tests_properties(framework.debug.exception_information.${group}.${case} PROPERTIES
        TIMEOUT 60 SKIP_RETURN_CODE 77 LABELS "framework;debug;exception-information;regression")
endfunction()
umicom_exception_information_test(umicom-exception-information-decode-test test_decode.c Umicom::developer)
foreach(case normal minimal empty-detail unknown-mode unicode expression escaped-key missing-id missing-mode id-type detail-type child-type children-type nul duplicate refuse command depth capacity message-limit)
    umicom_exception_information_case(decode umicom-exception-information-decode-test "${case}")
endforeach()
if(TARGET umicom-native-attach-adapter-fixture)
    umicom_exception_information_test(umicom-exception-information-protocol-test test_protocol.c Umicom::developer)
    add_dependencies(umicom-exception-information-protocol-test umicom-native-attach-adapter-fixture)
    foreach(case normal unsupported other-stop stale thread connection closed refuse timeout malformed continued)
        set(directory "${CMAKE_CURRENT_BINARY_DIR}/debug-exception-information/${case}")
        file(MAKE_DIRECTORY "${directory}")
        umicom_exception_information_case(protocol umicom-exception-information-protocol-test "${case}"
            "$<TARGET_FILE:umicom-native-attach-adapter-fixture>" "${directory}")
    endforeach()
endif()
if(TARGET umicom_ui_gtk4)
    umicom_exception_information_test(umicom-exception-information-gtk4-test test_gtk4.c Umicom::ui_gtk4)
    foreach(case normal denied hidden retained close-query invalid-host failed-refresh)
        umicom_exception_information_case(gtk4 umicom-exception-information-gtk4-test "${case}")
    endforeach()
endif()
