# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-line-edit-commands-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_line_edit_commands.c")
    target_link_libraries(umicom-line-edit-commands-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-line-edit-commands-test)
    umicom_apply_sanitizers(umicom-line-edit-commands-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-line-edit-commands-test)
    endif()
    foreach(case delete-line duplicate-line move-line-up move-line-down join-line-with-next trim-trailing-whitespace indent-lines outdent-lines toggle-line-comment metadata prefix argument empty-argument message-bounds read-only no-document)
        add_test(NAME framework.document.line_edit.command.${case} COMMAND umicom-line-edit-commands-test ${case})
        set_tests_properties(framework.document.line_edit.command.${case} PROPERTIES TIMEOUT 30 LABELS "framework;document;line-edit;history;regression")
    endforeach()
endif()
