# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
target_sources(umicom_developer PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/debug_runtime/module_page.c")
if(TARGET umicom_ui_gtk4)
    target_sources(umicom_ui_gtk4 PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../adapters/gtk4/debug_modules.c")
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/DEBUG_MODULE_BROWSER.html"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/umicom-framework/docs" COMPONENT Framework)
if(NOT BUILD_TESTING)
    return()
endif()
function(umicom_debug_module_test target source owner)
    add_executable("${target}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/debug_modules/${source}")
    target_link_libraries("${target}" PRIVATE "${owner}")
    set_target_properties("${target}" PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings("${target}")
    umicom_apply_sanitizers("${target}")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target("${target}")
    endif()
endfunction()
function(umicom_debug_module_case group target case)
    add_test(NAME framework.debug.modules.${group}.${case} COMMAND "${target}" "${case}" ${ARGN})
    set_tests_properties(framework.debug.modules.${group}.${case} PROPERTIES
        TIMEOUT 60 SKIP_RETURN_CODE 77 LABELS "framework;debug;modules;regression")
endfunction()
umicom_debug_module_test(umicom-debug-module-page-test test_page.c Umicom::developer)
foreach(case numeric typed-identities unknown-total first empty unknown-empty beyond-end unicode duplicate missing-id id-boolean nul boolean array total-small total-negative total-large empty-before-end capacity duplicate-key refuse command)
    umicom_debug_module_case(page umicom-debug-module-page-test "${case}")
endforeach()
if(TARGET umicom-native-attach-adapter-fixture)
    umicom_debug_module_test(umicom-debug-module-protocol-test test_protocol.c Umicom::developer)
    add_dependencies(umicom-debug-module-protocol-test umicom-native-attach-adapter-fixture)
    foreach(case normal unknown stale session refuse timeout malformed unsupported closed new-session legacy-refresh inflight-exit)
        set(directory "${CMAKE_CURRENT_BINARY_DIR}/debug-module-pages/${case}")
        file(MAKE_DIRECTORY "${directory}")
        umicom_debug_module_case(protocol umicom-debug-module-protocol-test "${case}"
            "$<TARGET_FILE:umicom-native-attach-adapter-fixture>" "${directory}")
    endforeach()
endif()
if(TARGET umicom_ui_gtk4)
    umicom_debug_module_test(umicom-debug-module-gtk4-test test_gtk4.c Umicom::ui_gtk4)
    foreach(case paging unknown denied stale hidden retained close-query invalid-host)
        umicom_debug_module_case(gtk4 umicom-debug-module-gtk4-test "${case}")
    endforeach()
endif()
