# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(NOT TARGET umicom_desktop_system)
    return()
endif()
if(TARGET umicom_ui_gtk4)
    target_sources(umicom_ui_gtk4 PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../adapters/gtk4/process_picker.c")
    target_link_libraries(umicom_ui_gtk4 PUBLIC Umicom::desktop_system)
endif()
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/PROCESS_DISCOVERY.html"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/umicom-framework/docs" COMPONENT Framework)
if(NOT BUILD_TESTING)
    return()
endif()
function(umicom_process_catalog_test target source owner)
    add_executable("${target}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/process_catalog/${source}")
    target_link_libraries("${target}" PRIVATE "${owner}")
    set_target_properties("${target}" PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    umicom_apply_warnings("${target}")
    umicom_apply_sanitizers("${target}")
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target("${target}")
    endif()
endfunction()
function(umicom_process_catalog_cases group target)
    foreach(case IN LISTS ARGN)
        add_test(NAME framework.process_catalog.${group}.${case} COMMAND "${target}" "${case}")
        set_tests_properties(framework.process_catalog.${group}.${case} PROPERTIES
            TIMEOUT 60 SKIP_RETURN_CODE 77 LABELS "framework;desktop-system;process-catalog;regression")
    endforeach()
endfunction()
umicom_process_catalog_test(umicom-process-catalog-test test_catalog.c Umicom::desktop_system)
umicom_process_catalog_cases(values umicom-process-catalog-test copy find bounds report null empty duplicate unterminated seen capacity display fixture identity-equal identity-reused identity-pid identity-unknown identity-zero identity-null cancel relative-root control-root unknown-current zero-current)
umicom_process_catalog_test(umicom-process-catalog-native-test test_native.c Umicom::desktop_system)
umicom_process_catalog_cases(native umicom-process-catalog-native-test current reused sorted)
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    umicom_process_catalog_test(umicom-process-catalog-linux-test test_linux_fixture.c Umicom::desktop_system)
    umicom_process_catalog_cases(proc umicom-process-catalog-linux-test capture mismatch cancel limit)
endif()
if(TARGET umicom_ui_gtk4)
    umicom_process_catalog_test(umicom-process-picker-gtk4-test test_gtk4.c Umicom::ui_gtk4)
    umicom_process_catalog_cases(gtk4 umicom-process-picker-gtk4-test normal search page old-row fixture unknown cancel close hidden retained failed-refresh denied close-choose)
endif()
