# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-document-format-persistence-test "${CMAKE_CURRENT_LIST_DIR}/../tests/document/test_format_persistence.c")
    target_link_libraries(umicom-document-format-persistence-test PRIVATE Umicom::document)
    umicom_apply_warnings(umicom-document-format-persistence-test)
    umicom_apply_sanitizers(umicom-document-format-persistence-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-document-format-persistence-test)
    endif()
    foreach(case utf8 utf8-bom utf16-le utf16-be crlf cr unicode undo-before-save undo-after-save failed-write busy-callback reload-format reload-encoding-only)
        add_test(NAME framework.document.format_persistence.${case} COMMAND umicom-document-format-persistence-test ${case})
        set_tests_properties(framework.document.format_persistence.${case} PROPERTIES TIMEOUT 45 LABELS "framework;document;format;history;regression")
    endforeach()
endif()
