# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-native-type-navigation-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_native_type_navigation.c")
    target_link_libraries(umicom-native-type-navigation-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-native-type-navigation-test)
    umicom_apply_sanitizers(umicom-native-type-navigation-test)
    if(WIN32 AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(umicom-native-type-navigation-test PRIVATE -municode)
    endif()
    add_dependencies(umicom-native-type-navigation-test umicom-language-process-fixture)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-native-type-navigation-test)
    endif()
    foreach(case type-valid type-unicode type-empty type-link type-error type-invalid type-timeout type-encoding type-shutdown type-cancel type-range implementation-valid implementation-unicode implementation-empty implementation-link implementation-error implementation-invalid implementation-timeout implementation-encoding implementation-shutdown implementation-cancel implementation-range)
        add_test(NAME framework.language_runtime.native_type_navigation.${case} COMMAND umicom-native-type-navigation-test ${case} "$<TARGET_FILE:umicom-language-process-fixture>")
        set_tests_properties(framework.language_runtime.native_type_navigation.${case} PROPERTIES TIMEOUT 40
            LABELS "framework;language;navigation;native;ownership;regression")
    endforeach()
endif()
