# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING AND (WIN32 OR UNIX) AND NOT EMSCRIPTEN)
    add_executable(umicom-creative-asset-archive-file-test "${CMAKE_CURRENT_LIST_DIR}/../tests/creative_assets/test_archive_file.c")
    target_link_libraries(umicom-creative-asset-archive-file-test PRIVATE Umicom::creative_workspace)
    umicom_creative_configure_target(umicom-creative-asset-archive-file-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-creative-asset-archive-file-test)
    endif()
    foreach(case roundtrip empty unicode-path existing cancelled-save cancelled-load relative-save relative-load missing-load directory-load truncated-load corrupted-load payload-limit source-removed live-output invalid-limit chunked source-privacy)
        add_test(NAME framework.creative_assets.archive_file.${case} COMMAND umicom-creative-asset-archive-file-test ${case})
        set_tests_properties(framework.creative_assets.archive_file.${case} PROPERTIES TIMEOUT 30 LABELS "framework;creative-assets;archive;native;regression")
    endforeach()
endif()
