# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
# Avatar generation shares local credentials and the configured curl dependency.
include_guard(GLOBAL)
include(GNUInstallDirs)
set(_umicom_heygen_root "${CMAKE_CURRENT_LIST_DIR}/..")
add_library(umicom_heygen STATIC
    "${_umicom_heygen_root}/src/media_generation/heygen_plan.c"
    "${_umicom_heygen_root}/src/media_generation/heygen_request.c"
    "${_umicom_heygen_root}/src/media_generation/heygen_response.c"
    "${_umicom_heygen_root}/src/media_generation/heygen_http.c")
add_library(Umicom::heygen ALIAS umicom_heygen)
set_target_properties(umicom_heygen PROPERTIES EXPORT_NAME heygen C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
target_include_directories(umicom_heygen PUBLIC $<BUILD_INTERFACE:${_umicom_heygen_root}/include> $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
target_link_libraries(umicom_heygen PUBLIC Umicom::security Umicom::platform PRIVATE Umicom::developer Umicom::ai)
if(UMICOM_PROVIDER_CONNECTION_CHECK_HTTP_BUILT)
    target_compile_definitions(umicom_heygen PRIVATE UMICOM_HEYGEN_HAS_HTTP=1)
    target_link_libraries(umicom_heygen PRIVATE PkgConfig::UMICOM_CONNECTION_CHECK_CURL)
endif()
umicom_apply_warnings(umicom_heygen)
umicom_apply_sanitizers(umicom_heygen)
target_link_libraries(umicom_framework INTERFACE Umicom::heygen)
install(TARGETS umicom_heygen EXPORT UmicomFrameworkTargets ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT Framework)
if(TARGET umicom_ui_gtk4)
    target_sources(umicom_ui_gtk4 PRIVATE "${_umicom_heygen_root}/adapters/gtk4/heygen_panel_gtk4.c")
    target_link_libraries(umicom_ui_gtk4 PUBLIC Umicom::heygen)
endif()

if(BUILD_TESTING)
    add_executable(umicom-heygen-test "${_umicom_heygen_root}/tests/media_generation/test_heygen.c")
    target_link_libraries(umicom-heygen-test PRIVATE Umicom::heygen)
    umicom_apply_warnings(umicom-heygen-test)
    umicom_apply_sanitizers(umicom-heygen-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-heygen-test)
    endif()
    foreach(case video avatar deny header-injection cancel-before cancel-confirmed timeout redirect unauthorized rate-limit in-progress overflow duplicate-data duplicate-id wrong-field-type escaped-nul trailing embedded-nul provider-error path-injection missing-request-key unterminated invalid-utf8 empty-script immutable prompt-limit catalogue catalogue-voices catalogue-duplicate catalogue-missing-cursor catalogue-empty catalogue-cancel cursor unexpected-field status status-mismatch status-url status-pending status-avatar status-subtitles status-subtitles-null status-subtitles-url status-subtitles-duplicate)
        add_test(NAME framework.heygen.${case} COMMAND umicom-heygen-test ${case})
        set_tests_properties(framework.heygen.${case} PROPERTIES TIMEOUT 20 LABELS "framework;heygen;privacy;regression")
    endforeach()
endif()

if(BUILD_TESTING AND UMICOM_PROVIDER_CONNECTION_CHECK_HTTP_BUILT)
    add_executable(umicom-heygen-http-test "${_umicom_heygen_root}/tests/media_generation/test_heygen_http.c")
    target_compile_definitions(umicom-heygen-http-test PRIVATE UMICOM_HEYGEN_HAS_HTTP=1)
    target_link_libraries(umicom-heygen-http-test PRIVATE Umicom::heygen PkgConfig::UMICOM_CONNECTION_CHECK_CURL)
    umicom_apply_warnings(umicom-heygen-http-test)
    umicom_apply_sanitizers(umicom-heygen-http-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-heygen-http-test)
    endif()
    foreach(case get post redirect denied rate-limit timeout cancel overflow option-failure)
        add_test(NAME framework.heygen.http.${case} COMMAND umicom-heygen-http-test ${case})
        set_tests_properties(framework.heygen.http.${case} PROPERTIES TIMEOUT 20 LABELS "framework;heygen;http;privacy;regression")
    endforeach()
endif()
if(BUILD_TESTING AND TARGET umicom_ui_gtk4)
    add_executable(umicom-heygen-gtk-test "${_umicom_heygen_root}/tests/media_generation/test_heygen_gtk4.c")
    target_link_libraries(umicom-heygen-gtk-test PRIVATE Umicom::ui_gtk4)
    umicom_apply_warnings(umicom-heygen-gtk-test)
    umicom_apply_sanitizers(umicom-heygen-gtk-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-heygen-gtk-test)
    endif()
    foreach(case review character unapproved edit password alias private-filter script portrait retained scene scene-image scene-duration scene-asset-edit)
        add_test(NAME framework.heygen.gtk.${case} COMMAND umicom-heygen-gtk-test ${case})
        set_tests_properties(framework.heygen.gtk.${case} PROPERTIES TIMEOUT 20 SKIP_RETURN_CODE 77 LABELS "framework;heygen;gtk4;ownership;regression")
    endforeach()
endif()

install(FILES "${_umicom_heygen_root}/docs/learning/avatar-video-requests.html"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/umicom/learning COMPONENT Learning)

if(BUILD_TESTING)
    add_executable(umicom-heygen-scene-test "${_umicom_heygen_root}/tests/media_generation/test_heygen_scene.c")
    target_link_libraries(umicom-heygen-scene-test PRIVATE Umicom::heygen)
    umicom_apply_warnings(umicom-heygen-scene-test)
    umicom_apply_sanitizers(umicom-heygen-scene-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-heygen-scene-test)
    endif()
    foreach(case text portrait image maximum short long zero asset-path image-portrait unused-title unused-voice unused-motion unused-subtitles read-scene-fields wrong-success-code credits missing-id)
        add_test(NAME framework.heygen.scene.${case} COMMAND umicom-heygen-scene-test ${case})
        set_tests_properties(framework.heygen.scene.${case} PROPERTIES TIMEOUT 20 LABELS "framework;heygen;privacy;regression")
    endforeach()
endif()
