# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
include(GNUInstallDirs)
include("${CMAKE_CURRENT_LIST_DIR}/UmicomDesignerNative.cmake")
find_package(PkgConfig REQUIRED)
pkg_check_modules(UMICOM_DESIGNER_NATIVE_GTK REQUIRED IMPORTED_TARGET GLOBAL gtk4>=4.10)
get_filename_component(_native_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
add_library(umicom_designer_native_gtk4 STATIC "${_native_root}/adapters/gtk4/designer_native_gtk4.c")
add_library(Umicom::designer_native_gtk4 ALIAS umicom_designer_native_gtk4)
set_target_properties(umicom_designer_native_gtk4 PROPERTIES EXPORT_NAME designer_native_gtk4
    C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
target_link_libraries(umicom_designer_native_gtk4 PUBLIC Umicom::designer_native PkgConfig::UMICOM_DESIGNER_NATIVE_GTK)
umicom_apply_warnings(umicom_designer_native_gtk4)
umicom_apply_sanitizers(umicom_designer_native_gtk4)
install(TARGETS umicom_designer_native_gtk4 EXPORT UmicomFrameworkTargets ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
install(FILES "${_native_root}/include/umicom/designer/native_gtk4.h" DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/umicom/designer)
if(BUILD_TESTING)
    add_executable(umicom-designer-native-gtk-test "${_native_root}/tests/designer_native/test_gtk.c")
    target_link_libraries(umicom-designer-native-gtk-test PRIVATE Umicom::designer_native_gtk4)
    umicom_apply_warnings(umicom-designer-native-gtk-test)
    umicom_apply_sanitizers(umicom-designer-native-gtk-test)
    foreach(_case IN ITEMS lifecycle count retained_action independent invalid editor_limit)
        add_test(NAME framework.designer_native.gtk.${_case} COMMAND umicom-designer-native-gtk-test ${_case})
        set_tests_properties(framework.designer_native.gtk.${_case} PROPERTIES SKIP_RETURN_CODE 77 TIMEOUT 30)
    endforeach()
endif()
