# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
if(BUILD_TESTING)
    add_executable(umicom-formatting-query-test "${CMAKE_CURRENT_LIST_DIR}/../tests/language_runtime/test_formatting_query.c")
    target_link_libraries(umicom-formatting-query-test PRIVATE Umicom::developer Umicom::editor Umicom::platform)
    umicom_apply_warnings(umicom-formatting-query-test)
    umicom_apply_sanitizers(umicom-formatting-query-test)
    if(COMMAND umicom_register_validation_target)
        umicom_register_validation_target(umicom-formatting-query-test)
    endif()
    foreach(case valid options object missing disabled encoding sync fragmented notification error invalid-edits overlap shutdown-error close-error timeout cancel-before cancel-during invalid-source invalid-options state empty unicode native-invalid read-error write-error escaped-limit)
        add_test(NAME framework.language_runtime.formatting_query.${case} COMMAND umicom-formatting-query-test ${case})
        set_tests_properties(framework.language_runtime.formatting_query.${case} PROPERTIES TIMEOUT 30
            LABELS "framework;language;formatting;ownership;regression")
    endforeach()
endif()
