#-----------------------------------------------------------------------------
# Umicom Framework
# File: cmake/VerifyLibrarySymbols.cmake
# PURPOSE: Check a real static archive before an application consumes it and
#          retain an exact, local JSON report for build troubleshooting.
# AUTHOR AND ORGANISATION: Sammy Hegab, Umicom Foundation
# LICENCE: MIT
#-----------------------------------------------------------------------------
cmake_minimum_required(VERSION 3.24)

# Invocation is an argument vector, not a shell command. Required variables:
# ARCHIVE, SYMBOL_FILE, NM_TOOL and REPORT. Symbol files contain one C function
# per line, with optional blank lines and # comments. GNU/LLVM nm POSIX output
# is used on GCC/Clang toolchains. No archive, source or Git state is modified.
function(JsonQuote value output)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(WriteReport state reason)
    JsonQuote("${ARCHIVE}" archiveJson)
    JsonQuote("${SYMBOL_FILE}" manifestJson)
    JsonQuote("${NM_TOOL}" toolJson)
    JsonQuote("${reason}" reasonJson)
    string(TIMESTAMP checkedAt "%Y-%m-%dT%H:%M:%SZ" UTC)
    set(items "")
    foreach(symbol IN LISTS required)
        if(NOT items STREQUAL "")
            string(APPEND items ",")
        endif()
        set(count 0)
        if(DEFINED count_${symbol})
            set(count "${count_${symbol}}")
        endif()
        string(APPEND items "\n    {\"name\":\"${symbol}\",\"code_definitions\":${count}}")
    endforeach()
    file(WRITE "${REPORT}"
        "{\n  \"schema\":1,\n  \"state\":\"${state}\",\n  \"checked_at\":\"${checkedAt}\",\n"
        "  \"archive\":${archiveJson},\n  \"archive_sha256\":\"${archiveHash}\",\n"
        "  \"symbol_file\":${manifestJson},\n  \"symbol_file_sha256\":\"${manifestHash}\",\n"
        "  \"tool\":${toolJson},\n  \"reason\":${reasonJson},\n  \"symbols\":[${items}\n  ]\n}\n")
endfunction()

function(FailCheck reason)
    WriteReport("failed" "${reason}")
    message(FATAL_ERROR "${reason}\nArchive: ${ARCHIVE}\nReport: ${REPORT}\nRebuild the owning library from the matching Framework sources. Do not supply dummy function bodies.")
endfunction()

if(NOT DEFINED REPORT OR REPORT STREQUAL "")
    message(FATAL_ERROR "MISSING_ARGUMENT: REPORT")
endif()
get_filename_component(reportDirectory "${REPORT}" DIRECTORY)
if(reportDirectory STREQUAL "")
    set(reportDirectory ".")
endif()
# A report destination must never overwrite the archive, manifest or tool.
# Resolve existing symlinks before comparing; this is an accidental-alias guard,
# not a defence against another process changing the filesystem concurrently.
foreach(destination IN ITEMS "${REPORT}" "${REPORT}.nm.txt" "${REPORT}.stderr.txt")
    get_filename_component(destinationPath "${destination}" REALPATH)
    if(WIN32)
        string(TOLOWER "${destinationPath}" destinationPath)
    endif()
    foreach(input IN ITEMS ARCHIVE SYMBOL_FILE NM_TOOL)
        if(DEFINED ${input} AND NOT "${${input}}" STREQUAL "")
            get_filename_component(inputPath "${${input}}" REALPATH)
            if(WIN32)
                string(TOLOWER "${inputPath}" inputPath)
            endif()
            if(destinationPath STREQUAL inputPath)
                message(FATAL_ERROR "REPORT_INPUT_ALIAS: choose a report destination separate from ${input}. No input was changed.")
            endif()
        endif()
    endforeach()
endforeach()
file(MAKE_DIRECTORY "${reportDirectory}")
set(required "")
set(archiveHash "")
set(manifestHash "")
# Replace any old success before starting; an interrupted check is incomplete.
WriteReport("incomplete" "Checking the selected archive.")
foreach(argument IN ITEMS ARCHIVE SYMBOL_FILE NM_TOOL)
    if(NOT DEFINED ${argument} OR "${${argument}}" STREQUAL "")
        FailCheck("MISSING_ARGUMENT: ${argument}")
    endif()
endforeach()

if(NOT EXISTS "${SYMBOL_FILE}" OR IS_DIRECTORY "${SYMBOL_FILE}")
    FailCheck("MISSING_MANIFEST: ${SYMBOL_FILE}")
endif()
file(SHA256 "${SYMBOL_FILE}" manifestHash)
file(STRINGS "${SYMBOL_FILE}" manifestLines ENCODING UTF-8)
foreach(line IN LISTS manifestLines)
    string(STRIP "${line}" line)
    if(line STREQUAL "" OR line MATCHES "^#")
        continue()
    endif()
    if(NOT line MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
        FailCheck("INVALID_MANIFEST: expected one C function name per line.")
    endif()
    if(line IN_LIST required)
        FailCheck("DUPLICATE_MANIFEST_SYMBOL: ${line}")
    endif()
    list(APPEND required "${line}")
    set(count_${line} 0)
    set(nonCode_${line} 0)
endforeach()
list(LENGTH required requiredCount)
if(requiredCount EQUAL 0)
    FailCheck("EMPTY_MANIFEST: at least one required function is needed.")
endif()
if(NOT EXISTS "${ARCHIVE}" OR IS_DIRECTORY "${ARCHIVE}")
    FailCheck("MISSING_ARCHIVE: ${ARCHIVE}")
endif()
file(SHA256 "${ARCHIVE}" archiveHash)
execute_process(COMMAND "${NM_TOOL}" --format=posix --extern-only --defined-only "${ARCHIVE}"
    RESULT_VARIABLE toolResult OUTPUT_VARIABLE symbolOutput ERROR_VARIABLE toolError
    TIMEOUT 45 ENCODING UTF-8)
file(WRITE "${REPORT}.nm.txt" "${symbolOutput}")
file(WRITE "${REPORT}.stderr.txt" "${toolError}")
if(NOT toolResult STREQUAL "0")
    FailCheck("TOOL_FAILURE: nm returned ${toolResult}. ${toolError}")
endif()
# Archive headers do not match this record shape. External references (U),
# private functions (t) and data objects (D/B/C) cannot satisfy a code contract.
string(REPLACE "\r\n" "\n" symbolOutput "${symbolOutput}")
string(REPLACE ";" "\\;" symbolOutput "${symbolOutput}")
string(REPLACE "\n" ";" symbolLines "${symbolOutput}")
foreach(line IN LISTS symbolLines)
    if(line MATCHES "^([^ \t]+)[ \t]+([A-Za-z?])[ \t]+")
        set(name "${CMAKE_MATCH_1}")
        set(kind "${CMAKE_MATCH_2}")
        foreach(symbol IN LISTS required)
            if(name STREQUAL symbol OR (ALLOW_LEADING_UNDERSCORE AND name STREQUAL "_${symbol}"))
                if(kind STREQUAL "T")
                    math(EXPR count_${symbol} "${count_${symbol}} + 1")
                else()
                    math(EXPR nonCode_${symbol} "${nonCode_${symbol}} + 1")
                endif()
            endif()
        endforeach()
    endif()
endforeach()
set(problems "")
foreach(symbol IN LISTS required)
    if(count_${symbol} EQUAL 0)
        if(nonCode_${symbol} GREATER 0)
            string(APPEND problems "NON_CODE_SYMBOL: ${symbol}\n")
        else()
            string(APPEND problems "MISSING_SYMBOL: ${symbol}\n")
        endif()
    elseif(count_${symbol} GREATER 1 OR nonCode_${symbol} GREATER 0)
        string(APPEND problems "DUPLICATE_DEFINITION: ${symbol}\n")
    endif()
endforeach()
if(NOT problems STREQUAL "")
    FailCheck("${problems}")
endif()
# Do not label a report successful if an external process replaced the inputs
# during inspection. Normal build dependencies keep these files stable.
file(SHA256 "${ARCHIVE}" finalArchiveHash)
file(SHA256 "${SYMBOL_FILE}" finalManifestHash)
if(NOT archiveHash STREQUAL finalArchiveHash OR NOT manifestHash STREQUAL finalManifestHash)
    FailCheck("INPUT_CHANGED: the archive or contract changed during inspection.")
endif()
WriteReport("passed" "Each required function has exactly one external code definition.")
list(LENGTH required checked)
message(STATUS "${checked} library functions verified: ${ARCHIVE}; report: ${REPORT}")
