/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: include/umicom/workbench_context_link/workbench_context_link.h
 *
 * PURPOSE:
 *   Expose the complete Framework-owned context-linked workbench platform.
 *
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
#ifndef UMICOM_WORKBENCH_CONTEXT_LINK_WORKBENCH_CONTEXT_LINK_H
#define UMICOM_WORKBENCH_CONTEXT_LINK_WORKBENCH_CONTEXT_LINK_H

#include "umicom/workbench_context_link/types.h"
#include "umicom/workbench_context_link/group_profile.h"
#include "umicom/workbench_context_link/panel_binding.h"
#include "umicom/workbench_context_link/application_binding.h"
#include "umicom/workbench_context_link/workspace_binding.h"
#include "umicom/workbench_context_link/layout_binding.h"
#include "umicom/workbench_context_link/monitor_binding.h"
#include "umicom/workbench_context_link/publish_request.h"
#include "umicom/workbench_context_link/delivery_target.h"
#include "umicom/workbench_context_link/delivery_plan.h"
#include "umicom/workbench_context_link/route_hop.h"
#include "umicom/workbench_context_link/route_trace.h"
#include "umicom/workbench_context_link/active_context.h"
#include "umicom/workbench_context_link/context_cache_entry.h"
#include "umicom/workbench_context_link/history_entry.h"
#include "umicom/workbench_context_link/navigation_entry.h"
#include "umicom/workbench_context_link/pinned_context.h"
#include "umicom/workbench_context_link/recent_context.h"
#include "umicom/workbench_context_link/focus_policy.h"
#include "umicom/workbench_context_link/activation_policy.h"
#include "umicom/workbench_context_link/selection_bridge.h"
#include "umicom/workbench_context_link/source_location_bridge.h"
#include "umicom/workbench_context_link/instrument_bridge.h"
#include "umicom/workbench_context_link/account_bridge.h"
#include "umicom/workbench_context_link/trade_bridge.h"
#include "umicom/workbench_context_link/project_bridge.h"
#include "umicom/workbench_context_link/workspace_bridge.h"
#include "umicom/workbench_context_link/media_bridge.h"
#include "umicom/workbench_context_link/permission.h"
#include "umicom/workbench_context_link/access_policy.h"
#include "umicom/workbench_context_link/audit_record.h"
#include "umicom/workbench_context_link/diagnostic.h"
#include "umicom/workbench_context_link/metric.h"
#include "umicom/workbench_context_link/conflict.h"
#include "umicom/workbench_context_link/sync_state.h"
#include "umicom/workbench_context_link/persistence_record.h"
#include "umicom/workbench_context_link/import_record.h"
#include "umicom/workbench_context_link/export_record.h"
#include "umicom/workbench_context_link/context_diff.h"
#include "umicom/workbench_context_link/inspector_row.h"
#include "umicom/workbench_context_link/group_picker_row.h"
#include "umicom/workbench_context_link/badge_model.h"
#include "umicom/workbench_context_link/panel_header_model.h"
#include "umicom/workbench_context_link/panel_host_model.h"
#include "umicom/workbench_context_link/toolbar_item.h"
#include "umicom/workbench_context_link/menu_item.h"
#include "umicom/workbench_context_link/status_model.h"
#include "umicom/workbench_context_link/accessibility_node.h"
#include "umicom/workbench_context_link/drag_drop_link.h"
#include "umicom/workbench_context_link/keyboard_navigation.h"
#include "umicom/workbench_context_link/search_result.h"
#include "umicom/workbench_context_link/filter.h"
#include "umicom/workbench_context_link/statistics.h"
#include "umicom/workbench_context_link/command.h"
#include "umicom/workbench_context_link/event.h"
#include "umicom/workbench_context_link/query.h"
#include "umicom/workbench_context_link/command_history.h"
#include "umicom/workbench_context_link/undo_record.h"
#include "umicom/workbench_context_link/session.h"
#include "umicom/workbench_context_link/workspace_link_model.h"
#include "umicom/workbench_context_link/application_link_model.h"
#include "umicom/workbench_context_link/multi_monitor_link_model.h"
#include "umicom/workbench_context_link/layout_link_model.h"
#include "umicom/workbench_context_link/panel_link_state.h"
#include "umicom/workbench_context_link/group_state.h"
#include "umicom/workbench_context_link/context_state.h"
#include "umicom/workbench_context_link/route_state.h"
#include "umicom/workbench_context_link/delivery_state.h"
#include "umicom/workbench_context_link/history_state.h"
#include "umicom/workbench_context_link/group_catalogue.h"
#include "umicom/workbench_context_link/binding_registry.h"
#include "umicom/workbench_context_link/active_context_store.h"
#include "umicom/workbench_context_link/history_store.h"
#include "umicom/workbench_context_link/pin_store.h"
#include "umicom/workbench_context_link/payload_builder.h"
#include "umicom/workbench_context_link/service.h"
#include "umicom/workbench_context_link/controller.h"
#include "umicom/workbench_context_link/snapshot.h"

#endif
