/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: include/umicom/context_channel/context_channel.h
 *
 * PURPOSE:
 *   Provide the complete public C23 surface for typed context channels and cross-application panels.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/

#ifndef UMICOM_CONTEXT_CHANNEL_CONTEXT_CHANNEL_H
#define UMICOM_CONTEXT_CHANNEL_CONTEXT_CHANNEL_H
#include "umicom/context_channel/account.h"
#include "umicom/context_channel/audit_record.h"
#include "umicom/context_channel/binding.h"
#include "umicom/context_channel/bookmark.h"
#include "umicom/context_channel/bridge.h"
#include "umicom/context_channel/capability.h"
#include "umicom/context_channel/capability_service.h"
#include "umicom/context_channel/channel.h"
#include "umicom/context_channel/colour.h"
#include "umicom/context_channel/command.h"
#include "umicom/context_channel/context_access.h"
#include "umicom/context_channel/context_backpressure.h"
#include "umicom/context_channel/context_bookmark_service.h"
#include "umicom/context_channel/context_browser.h"
#include "umicom/context_channel/context_codec.h"
#include "umicom/context_channel/context_conflict.h"
#include "umicom/context_channel/context_export.h"
#include "umicom/context_channel/context_federation.h"
#include "umicom/context_channel/context_filter.h"
#include "umicom/context_channel/context_group_service.h"
#include "umicom/context_channel/context_health.h"
#include "umicom/context_channel/context_history_query.h"
#include "umicom/context_channel/context_import.h"
#include "umicom/context_channel/context_inspector.h"
#include "umicom/context_channel/context_journal.h"
#include "umicom/context_channel/context_merge.h"
#include "umicom/context_channel/context_migration.h"
#include "umicom/context_channel/context_panel_service.h"
#include "umicom/context_channel/context_preference.h"
#include "umicom/context_channel/context_profile.h"
#include "umicom/context_channel/context_recovery.h"
#include "umicom/context_channel/context_replay.h"
#include "umicom/context_channel/context_schema_compatibility.h"
#include "umicom/context_channel/context_search.h"
#include "umicom/context_channel/context_security.h"
#include "umicom/context_channel/context_session_service.h"
#include "umicom/context_channel/context_snapshot_store.h"
#include "umicom/context_channel/context_statistics.h"
#include "umicom/context_channel/context_subscription_service.h"
#include "umicom/context_channel/context_sync.h"
#include "umicom/context_channel/context_throttle.h"
#include "umicom/context_channel/context_trace.h"
#include "umicom/context_channel/context_transform.h"
#include "umicom/context_channel/context_transport.h"
#include "umicom/context_channel/context_validator.h"
#include "umicom/context_channel/controller.h"
#include "umicom/context_channel/deduplication.h"
#include "umicom/context_channel/delivery_receipt.h"
#include "umicom/context_channel/diagnostic.h"
#include "umicom/context_channel/diagnostics_service.h"
#include "umicom/context_channel/event.h"
#include "umicom/context_channel/filter_engine.h"
#include "umicom/context_channel/filter_rule.h"
#include "umicom/context_channel/group_member.h"
#include "umicom/context_channel/group_service.h"
#include "umicom/context_channel/history_entry.h"
#include "umicom/context_channel/history_service.h"
#include "umicom/context_channel/instrument.h"
#include "umicom/context_channel/link_group.h"
#include "umicom/context_channel/media.h"
#include "umicom/context_channel/memory_store.h"
#include "umicom/context_channel/metrics.h"
#include "umicom/context_channel/panel.h"
#include "umicom/context_channel/panel_context.h"
#include "umicom/context_channel/panel_host.h"
#include "umicom/context_channel/panel_instance.h"
#include "umicom/context_channel/payload.h"
#include "umicom/context_channel/permission.h"
#include "umicom/context_channel/policy.h"
#include "umicom/context_channel/policy_rule.h"
#include "umicom/context_channel/project.h"
#include "umicom/context_channel/provider.h"
#include "umicom/context_channel/provider_state.h"
#include "umicom/context_channel/query.h"
#include "umicom/context_channel/recent_context.h"
#include "umicom/context_channel/registry.h"
#include "umicom/context_channel/route.h"
#include "umicom/context_channel/route_trace.h"
#include "umicom/context_channel/router.h"
#include "umicom/context_channel/schema.h"
#include "umicom/context_channel/selection.h"
#include "umicom/context_channel/service.h"
#include "umicom/context_channel/session.h"
#include "umicom/context_channel/snapshot.h"
#include "umicom/context_channel/source_location.h"
#include "umicom/context_channel/subscription.h"
#include "umicom/context_channel/trade.h"
#include "umicom/context_channel/transformer_engine.h"
#include "umicom/context_channel/transformer_rule.h"
#include "umicom/context_channel/types.h"
#include "umicom/context_channel/value.h"
#include "umicom/context_channel/workspace.h"
#endif
