# Umicom Framework | Sammy Hegab, Umicom Foundation | MIT
set(UMICOM_ENTERPRISE_RECOVERY_CASES
    query_defaults
    query_empty
    query_sort_id_desc
    query_sort_label
    query_sort_label_desc
    query_sort_quantity
    query_sort_quantity_desc
    query_filter_unicode
    query_filter_origin
    query_filter_multiline
    query_filter_case
    query_filter_none
    query_range
    query_exact_quantity
    query_invalid_utf8
    query_unterminated
    query_invalid_sort
    query_reverse_range
    query_range_overflow
    query_missing
    query_denied
    query_page_edges
    query_64_rows
    query_frozen
    query_lifetime
    query_copy_isolation
    recovery_preview
    recovery_workflow
    recovery_rejected
    recovery_cancelled
    recovery_disabled
    recovery_paused
    recovery_applied
    recovery_missing
    recovery_denied
    recovery_report
    recovery_lifetime
    recovery_stale
    recovery_actor_changed
    recovery_existing_id
    recovery_invalid_id
    recovery_revoked
    sqlite_write_failure
    sqlite_restart
    storage_changed_chunk
    storage_noop
    storage_unknown
    storage_missing
    storage_namespace
    storage_reprepare
    sqlite_changed_chunk
    sqlite_stale_writer
)
